### PR TITLE
Add number to string method for python and php

### PR DESCRIPTION
**Pull request by brandsimon**
As discussed in #4942 I implemented number to string method for python and php.
I added some testcases, I thought are necessary.
I removed the testcase with `-0.000000789999999999999` because in python it evaluated to `-0.00000079`.

### CODE REVIEW

**Comment by frosty00** [comment]
in other words your entire function can be replaced with

```
d = Decimal(str(7.9e-7))
return '{:f}'.format(d)
'0.00000079'
```

**Comment by brandsimon** [comment]
@frosty00 
Great, thank you. I changed the method.
I'd like to avoid a method where I need to specify a precision, because I will never know if my assumption (use this big number) will work in the future for everyone.

I can squash it after it is approved.

**Comment by kroitor** [comment]
@brandsimon thanks for your help and thx to @frosty00 for the review!

**Comment by frosty00** [comment]
I'm not sure we need this extra method to be so explicit (take up so many lines in php). Why couldn't you just use `decimalToPrecision` or implement this in your own code. I don't think `numberToString` this belongs in the CCXT library - where are we planning on using this? It just adds code bloat. @kroitor

**Comment by kroitor** [comment]
>  I don't think numberToString this belongs in the CCXT library - where are we planning on using this?

@brandsimon can you tell why would you need it, btw? We might try a different approach, depending on which particular use-case it is...

**Comment by frosty00** [comment]
I think we are better off using `decimalToPrecision` everywhere, because you know, bugs in the conversion code...

**Comment by kroitor** [comment]
@frosty00 personally, I would agree with you. But there still may be certain use-cases inside the lib, where precision is unknown. I suggest @brandsimon to show an example case where this might be needed and we will think on how to do it right in general.

**Comment by frosty00** [comment]
since we still convert `json str` -> `float` -> `decimal/bignumber` there are no use cases where we have unknown precision since we have max the precision of a float which is like 16 or so

**Comment by frosty00** [comment]
I have been suggesting to give the user the option to use decimals for a while, but there has just been so much other stuff going on. We should design the lib in a way the you can choose types: #4355

**Comment by brandsimon** [comment]
I implemented an exchange #4942 which has a representation for floats like this: 
```
{
    'value': 4
    'decimals': 7,
}
```
This represents `4 * 10 ^ -7 = 0.0000004`.
There is no conversion from json, since this is only needed for user input (create order).
I need to convert this to a string, because `precisionFromString` needs a string.

**Comment by frosty00** [comment]
@kroitor 

The argument for number to string is being stored as a floating point number. AKA if you wanted to retain maximum precision you would have to do `Decimal('4') * Decimal(`10`) ** Decimal('-7')` in python and then convert it to a string. Once you convert to a floating point number (by using pow) the `numberToString` method is useless. Therefore I suggest we use `decimalToPrecision(n, ROUND, 10, DECIMAL_PLACES, NO_PADDING)` instead. Using `numberToString` anywhere a bad idea because it doesn't take into account padding and some floats should break your function. 

How many decimals is 1/3 supposed to represent? 

FYI calling `number_to_string` will have 16 decimals in php and 18 in python/js. Just do 0.1+0.2 to find out why we don't want to do arithmetic using floating point and then try to convert it to a string (it's like trying to upscale a 240p video to 1080).

**Comment by brandsimon** [comment]
@frosty00 
Yes, you are absolutely right, there is a problem in my solution with 0-padded numbers, thank you.
I adapted the PR. I hope, this is correct now for every case.

`Decimal('4') * Decimal(10) ** Decimal('-7')`
Yes, also here is a problem in objectToNumber. I tried to fix it. (I hope it is)

Is there a cross language solution in ccxt to use decimals?

**Comment by frosty00** [comment]
> Is there a cross language solution in ccxt to use decimals?

not yet...

**Pull request merged**
