### PR TITLE
Okx fetchBorrowRateHistory, fetchBorrowRateHistories

### PR DESCRIPTION
**Pull request by Dan-krm**
Added fetchBorrowRateHistory and fetchBorrowRateHistories to Okx:
```
okx.fetchBorrowRateHistories ()
1220 ms
{
  BTC: [
    {
      info: {
        amt: '928.98122418',
        ccy: 'BTC',
        rate: '0.01',
        ts: '1643958000000'
      },
      currency: 'BTC',
      rate: '0.01',
      timestamp: '1643958000000',
      datetime: '2022-02-04T07:00:00.000Z'
    }
  ],
  ETH: [
    {
      info: {
        amt: '14124.22822828',
        ccy: 'ETH',
        rate: '0.01',
        ts: '1643958000000'
      },
      currency: 'ETH',
      rate: '0.01',
      timestamp: '1643958000000',
      datetime: '2022-02-04T07:00:00.000Z'
    }
  ],
...
}
```
```
okx.fetchBorrowRateHistory (BTC)
1181 ms
currency | rate |     timestamp |                 datetime
----------------------------------------------------------
     BTC | 0.01 | 1643958000000 | 2022-02-04T07:00:00.000Z
1 objects
```

### CODE REVIEW

**Comment by samgermain** [comment]
```
% node examples/js/cli okx fetchBorrowRateHistory SHIB 1640908800000 3
Debugger listening on ws://127.0.0.1:56339/df6ef0dc-19f7-4b04-a027-28d3c4a35939
For help, see: https://nodejs.org/en/docs/inspector
Debugger attached.
2022-02-04T07:41:30.310Z
Node.js: v14.17.0
CCXT v1.72.17
okx.fetchBorrowRateHistory (SHIB, 1640908800000, 3)
BadRequest okx.fetchBorrowRateHistory returned no data for SHIB
---------------------------------------------------
[BadRequest] okx.fetchBorrowRateHistory returned no data for SHIB

    at fetchBorrowRateHistory     ../../ccxt/ccxt/js/okx.js:3907          throw new BadRequest (this.id + '.fetchBorrowRateHistory returned no data for '…
    at processTicksAndRejections  internal/process/task_queues.js:95                                                                                      
    at async main                 ../../ccxt/ccxt/examples/js/cli.js:256  const result = await exchange[methodName] (... args)                            

okx.fetchBorrowRateHistory returned no data for SHIB
```

**Comment by Dan-krm** [comment]
> It looks like the limit params and since params aren't working like how you would expect

Can you elaborate further I'm not sure everything that's wrong? I see that specifying limit in fetchBorrowRateHistory isn't working properly even though these methods are based on what you implemented on FTX, if you call the fetchBorrowRateHistory method on FTX with those same arguments it gives the same 'Bad Request' error response.

**Comment by Dan-krm** [comment]
> It looks like the limit params and since params aren't working like how you would expect

I'm not sure everything that's wrong with the limit and since params not working properly, can you elaborate further?

**Comment by samgermain** [comment]
> > It looks like the limit params and since params aren't working like how you would expect
> 
> I'm not sure everything that's wrong with the limit and since params not working properly, can you elaborate further?

I can't pass a limit to `fetchBorrowRateHistory`, if I do pass a limit, `fetchBorrowRateHistories` will return the first 3 currencies, and if my currency isn't in there, then it says it wasn't found.

 the since parameter does nothing but change the timestamp, it doesn't look like I can get more than one borrow rate either

**Comment by Dan-krm** [comment]
Let me know if these changes are incorrect in any way or if there is any other adjustments that need to be made, so far these are the adjustments that I've made:

- Format the entered code on fetchBorrowRateHistory into a parameter argument object.
- Fix the since parameter doing nothing by assigning it to before instead of after.

This is what the api docs say describing before and after:

after | String | No | Pagination of data to return records earlier than the requested ts, Unix timestamp format in milliseconds, e.g. 1597026383085
-- | -- | -- | --
before | String | No | Pagination of data to return records newer than the requested ts, Unix timestamp format in milliseconds, e.g. 1597026383085

```
okex.fetchBorrowRateHistory (SHIB, 1644012000000, 3)
377 ms
{
  SHIB: [
    {
      info: {
        amt: '124227578281.86478826',
        ccy: 'SHIB',
        rate: '0.01',
        ts: '1644026400000'
      },
      currency: 'SHIB',
      rate: '0.01',
      timestamp: '1644026400000',
      datetime: '2022-02-05T02:00:00.000Z'
    },
    {
      info: {
        amt: '132915863880.96520246',
        ccy: 'SHIB',
        rate: '0.01',
        ts: '1644022800000'
      },
      currency: 'SHIB',
      rate: '0.01',
      timestamp: '1644022800000',
      datetime: '2022-02-05T01:00:00.000Z'
    },
    {
      info: {
        amt: '144063060592.34239801',
        ccy: 'SHIB',
        rate: '0.01',
        ts: '1644019200000'
      },
      currency: 'SHIB',
      rate: '0.01',
      timestamp: '1644019200000',
      datetime: '2022-02-05T00:00:00.000Z'
    }
  ]
}
```

**Pull request merged**
