### PR TITLE
Lykke symbol XPD alias Lykke XPD

### PR DESCRIPTION
**Pull request by gitlog**
PetroDollar (XPD) != Lykke XPD

### CODE REVIEW

**Comment by kroitor** [comment]
Hi! Can you plz move this edit to the JS file?

- https://github.com/ccxt/ccxt/blob/78544e8fca101d0b8e7f51e9f578f95ee775112f/python/ccxt/async_support/lykke.py#L3
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#multilanguage-support
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#multilanguage-support
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

Thx!

**Comment by kroitor** [comment]
Also, do you by chance know what is the actual token represented by `XPD` with Lykke?

**Comment by gitlog** [comment]
+ js/php

**Comment by kroitor** [comment]
@gitlog can you plz remove php and py files from this PR ? Since they are generated from JS.

**Comment by kroitor** [comment]
@gitlog https://github.com/ccxt/ccxt/blob/4a629a8de4620a9ce805a7a67ac852d7cd2cbf6e/php/lykke.php#L5

**Comment by gitlog** [comment]
> @gitlog can you plz remove php and py files from this PR ? Since they are generated from JS.

Ok.

**Comment by kroitor** [comment]
@gitlog thx so much! A quick question: do you know any details on which particular symbol is XPD on Lykke?

**Comment by gitlog** [comment]
> @gitlog thx so much! A quick question: do you know any details on which particular symbol is XPD on Lykke?

https://blockchainexplorer.lykke.com/asset/AauZ6yxKpRV7JEQRcJws6S8gpnkQeFzFzn
https://coinmarketcap.com/currencies/petrodollar/

**Pull request merged**
