### PR TITLE
Kucoin and Gdax fetchMarkets

### PR DESCRIPTION
**Pull request by wannesdemaeght**
Changes to kucoin and gdax for fees and precision in fetchMarkets

### CODE REVIEW

**Comment by kroitor** [comment]
Hey, haven't you seen the fetchCurrencies method there? )

**Comment by wannesdemaeght** [comment]
I did, but that doesn't change the fact that in fetchMarkets, the entry for precision is wrong. This fixes that.

**Comment by kroitor** [comment]
I mean, we should not fetch currencies in fetchMarkets. We should only fetch them in fetchCurrencies. Otherwise it will be inconsistent with other exchanges.

**Comment by wannesdemaeght** [comment]
True.

It is a public call though, and I see no other way to guarantee that fetchMarkets has the correct info.
We could link it to the .currencies, but only when loadMarkets was invoked instead of fetchCurrencies...

**Comment by kroitor** [comment]
> and I see no other way to guarantee that fetchMarkets has the correct info.

In fact, there is such a way. 

Currently, the call to `loadMarkets()` does the following:
1. `fetchMarkets()` + set this.markets
2. `fetchCurrencies()` + set this.currencies

We should reverse the call-chain, and from loadMarkets we should call in the following order:
1. `fetchCurrencies()` + set this.currencies
2. `fetchMarkets()` + set this.markets + use the already available this.currencies info

However, this is a significant change and it affects all exchanges, not just Kucoin. But, it seems, that we will have to do it sooner or later, hopefully sooner. Yet, in this solution would be different from this particular pull-request, and I'm now in doubt whether we should try merging it, or we should focus on fixing the callchain properly... I would go with a propex fix, but it implies closing this PR then, and I don't know if you're ok with it. I would not want you to stop participating in this project because of a closed PR.

**Comment by wannesdemaeght** [comment]
No, your solution makes total sense.
No hard feelings man, I will definitely keep participating and learning as we go along.

Regarding the Gdax changes I proposed, there should be no problems?

**Comment by kroitor** [comment]
@wannesdemaeght thanks for your understanding, really appreciate it!

> Regarding the Gdax changes I proposed, there should be no problems?

Yep, if you could just remove the Kucoin changes from this PR, I would merge it for GDAX shortly, and then we will return to solving the Kucoin problem anyway. How does it sound to you?

**Comment by wannesdemaeght** [comment]
If I only knew how to remove the kucoin changes... New to this whole github thingy...

**Comment by kroitor** [comment]
@wannesdemaeght oh, a simple command like `git checkout origin/master --  js/kucoin.js` should do the trick... Then commit it to your master branch, and there will be just the GDAX changes left (as expected).

**Comment by wannesdemaeght** [comment]
Will have to wait til I get home then... Or you could just manually change it I guess?

There's just 2 simple changes in the gdax file.

**Comment by kroitor** [comment]
@wannesdemaeght i'll merge it properly, no worries ) thx!

**Comment by wannesdemaeght** [comment]
Great, cheers man!

**Pull request closed without merging**
