### PR TITLE
waves  - precision prop fix

### PR DESCRIPTION
**Pull request by ttodua**
This PR is the next one in test-PR chain. This addresses `currency` tests, to check the expected currency structure across any exchange, in addition, this now includes the `precisionMode` tests to ensure that derived class developer has correctly implemented & handles the `TICK_SIZE` or `SIGNIFICANT_DIGITS`  modes.

### CODE REVIEW

**Comment by ttodua** [comment]
#lead this PR is ready for review. the affected exchange files have the needed changes, nothing is breaking-change.

**Comment by ttodua** [comment]
@carlosmiei just 1 second review

**Comment by ttodua** [comment]
@carlosmiei quick review would be enough for this

**Comment by carlosmiei** [comment]
LGTM ✅

**Review by carlosmiei — APPROVED** [review]

**Pull request merged**
