### PR TITLE
coinex: fetchCurrencies v2

### PR DESCRIPTION
**Pull request by Dan-krm**
Updated fetchCurrencies to v2 using a new endpoint and updated static currencies.

### CODE REVIEW

**Comment by carlosmiei** [comment]
can you check the build here

**Comment by Dan-krm** [comment]
@carlosmiei I fixed a few of the errors but I'm currently not sure why the remaining build errors are triggering

**Comment by carlosmiei** [comment]
@Dan-krm if you do `fetchCurrencies()`  it crashes 
```
 p coinex fetchCurrencies
Python v3.12.3
CCXT v4.3.41
Traceback (most recent call last):
  File "/Users/cjg/Git/ccxt9/ccxt/examples/py/cli.py", line 249, in <module>
    asyncio.run(main())
  File "/opt/homebrew/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/cjg/Git/ccxt9/ccxt/examples/py/cli.py", line 209, in main
    await exchange.load_markets()
  File "/Users/cjg/Git/ccxt9/ccxt/python/ccxt/async_support/base/exchange.py", line 276, in load_markets
    raise e
  File "/Users/cjg/Git/ccxt9/ccxt/python/ccxt/async_support/base/exchange.py", line 272, in load_markets
    result = await self.markets_loading
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/cjg/Git/ccxt9/ccxt/python/ccxt/async_support/base/exchange.py", line 263, in load_markets_helper
    return self.set_markets(markets, currencies)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/cjg/Git/ccxt9/ccxt/python/ccxt/base/exchange.py", line 2612, in set_markets
    self.currencies_by_id = self.index_by(self.currencies, 'id')
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/cjg/Git/ccxt9/ccxt/python/ccxt/base/exchange.py", line 1030, in index_by
    array = Exchange.keysort(array).values()
            ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/cjg/Git/ccxt9/ccxt/python/ccxt/base/exchange.py", line 974, in keysort
    return collections.OrderedDict(sorted(dictionary.items(), key=lambda t: t[0]))
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: '<' not supported between instances of 'NoneType' and 'str'
coinex requires to release all resources with an explicit call to the .close() coroutine. If you are using the exchange instance with async coroutines, add `await exchange.close()` to your code into a place when you're done with the exchange and don't need the exchange instance anymore (at the end of your async coroutine).
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x108762000>
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x109845670>, 338608.878711583), (<aiohttp.client_proto.ResponseHandler object at 0x109845f70>, 338608.94764375)]']
connector: <aiohttp.connector.TCPConnector object at 0x108869a00>
```

**Comment by carlosmiei** [comment]
coinex sometimes returns an empty structure, weird
image

**Pull request merged**
