### PR TITLE
bleutrade v3 implemention

### PR DESCRIPTION
**Pull request by npomfret**
Ready for review

### CODE REVIEW

**Comment by npomfret** [comment]
@kroitor this is ready for review.  There are 3 more methods i need to add but I can't test them yet. I've been waiting for the exchange to credit my account with a deposit for several days now.  As soon as they do I'll add fetchOpenOrders, createOrder and cancelOrder.

**Comment by npomfret** [comment]
Should `'fetchOrderTrades': false,` be in the base Exchange class?

**Comment by kroitor** [comment]
@npomfret yep

**Comment by npomfret** [comment]
@kroitor I'm added the remaining methods, it's ready for review.

**Comment by npomfret** [comment]
@kroitor any chance of getting a merge?  my client would like to try it out

**Comment by kroitor** [comment]
@npomfret i'll resolve it and will merge it this week, thx so much for your help!

**Pull request merged**
