### PR TITLE
Binance deposits withdrawals

### PR DESCRIPTION
**Pull request by firepol**
Hi @kroitor 

I'm testing fetching withdrawals and deposits and I noticed a little problem. the Exchange.parseTransactions doesn't have a param for "type" (side: deposit / withdrawal).

So also in cobinhood the `type` is null because no code is setting `type` properly. Of course when you call fetchWithdrawals you know that you are fetching withdrawals, but the property should be set correctly.

I tested PR #2526 from @grandmore and this is the fix based on the unified withdrawals and deposits transactions history (#1896).

I fixed the Exchange.parseTransactions method, so that it should not break existing implementations working without the `side` (gdax, gemini?) but ultimately I think the side param should be added to all implementations and eventually ignored if not needed.

Btw I noticed that in PHP, `side` is sort of implemented, but it looks kinda broken at first sight, maybe you wanna check it too...

When this is clarified and merged I'll submit a fix for cobinhood.

### CODE REVIEW

**Comment by firepol** [comment]
Btw if we agree on exchange.ParseTransactions to have the `side` parameter, I guess it would be better to place the `side` parameter directly after currency (as it will be probably used much more often than `since` and `limit`). Thoughts?

So, like this:

`parseTransactions (transactions, currency = undefined, side = undefined, since = undefined, limit = undefined)`

**Comment by kroitor** [comment]
Hi!

The `type` is the correct new name for `deposit` vs `withdrawal`, the `side` argument only allows two values, `buy` or `sell` everywhere else, so we won't use the side for `deposit` or `withdrawal`, instead we'll be using `type` to indicate that. Yes, we know that this is a reserved word in Python, but we're not breaking that aspect.

> So also in cobinhood the type is null because no code is setting type properly. Of course when you call fetchWithdrawals you know that you are fetching withdrawals, but the property should be set correctly.

We will not pass the `side` or `type` to `parseTransactions`, instead this should be done in exchange-specific way, where needed, not in the base class, see `parseOrders`, `parseTrades` for comparison. The `side` argument should not be passed from outside, it should be determined from the inside of the parser. I think passing anything but symbol from outside into the parseTransactions method is a strategically-bad design decision. If the exchange API does not allow to "guess" the type of the funding operation from the operation itself – we will add certain exchange-specific workarounds for that (including a possible bug with cobinhood, that you've mentioned).

> Btw I noticed that in PHP, side is sort of implemented, but it looks kinda broken at first sight, maybe you wanna check it too...

This may be a bug. I'll look further into it.

**Comment by firepol** [comment]
Hi @kroitor 

thanks for the answer (you are really the best open source project maintainer I've met so far! It's a pleasure to contribute for CCXT).

About "guessing" what a transaction is, without passing any hint, I have no idea how to achieve that. I guess you'll look into it?

Cobinhood has the same problem, there is some code to try to determine the type, but it's not working.

**Comment by kroitor** [comment]
> About "guessing" what a transaction is, without passing any hint, I have no idea how to achieve that. I guess you'll look into it?

Sure! I'm going to merge it together with the PR by @grandmore in a couple of days.

> Cobinhood has the same problem, there is some code to try to determine the type, but it's not working.

Yep, that's a leftover I missed, there's a bug there indeed and I'll fix it upon merging as well.

Thx for participating in this, @firepol , really appreciate your involvement!

**Comment by firepol** [comment]
@kroitor sorry to bother you again, I guess you are busy or have other priorities, but if you can clarify how the side (or type) can be determined, I'll be happy to test this for several exchanges I'm using and contribute where `fetchMyTrades` is missing.

**Pull request merged**
