### PR TITLE
Coinmarketcap lists NANO, but ccxt uses XRB.

### PR DESCRIPTION
**Pull request by miracle2k**

### CODE REVIEW

**Comment by kroitor** [comment]
Hey! ) Thx for your contribution again )

I feel like we should just revert to NANO for compliance with CMC, most users complain about their expectations not being met, when they're searching for NANO and finding XRB instead....

This is also noted here: https://github.com/ccxt/ccxt/issues/2007#issuecomment-369288154

Let me know what you think of it )

**Comment by miracle2k** [comment]
I think changing from XRB to NANO (or any other such changes) will cause problems for a lot of people - it certainly would for me. Some programs written using ccxt are likely to rely on the symbol "XRB" in some way, have database rows that reference the old symbol, and so on. A change of this kind is, I think, liable to cause trouble. 

A smaller concern, but worth mentioning, is that all the exchange implementation in ccxt itself need to be updated to rewrite the currency accordingly in the other direction - plenty of exchanges still use the XRB symbol internally, for the same reason I believe we should keep it - it's part of the API contract.

**Comment by kroitor** [comment]
@Surf-N-Code 

> Would it be just a matter of adjusting the following?

You should do this with the exchange in question:

```PHP
$exchange->commonCurrencies['NANO'] = 'NANO';
$exchange->commonCurrencies['XRB'] = 'NANO';
// your code & logic here...
```

**Comment by kroitor** [comment]
**XRB:**

```
Currencies: (test @ search-all-exchanges.js:107)

id    numericId  code  exchange  name  active  status  fee
-----------------------------------------------------------
NANO             XRB   binance
xrb              XRB   bitz
XRB              XRB   kucoin    Nano  true    ok      0.05
XRBC             XRBC  nova
nano  155        XRB   okex                                 (test @ search-all-exchanges.js:119)
---------------------------------------------------------------
```

**NANO:**

```
id     numericId  code   exchange       name       active  status  fee  type    payin  payout  transfer
-------------------------------------------------------------------------------------------------------
NANO              XRB    binance
NANO              NANO   coinmarketcap  Nano       true    ok
NANOX             NANOX  coinmarketcap  Project-X  true    ok
NANO              NANO   gateio
NANO              NANO   hitbtc
NANO              NANO   hitbtc2        NANO       false   ok           crypto  false  false   false
NANOX             NANOX  nova
nano   155        XRB    okex
NANOX             NANOX  yobit                                                                          (test @ search-all-exchanges.js:119)
---------------------------------------------------------------
```

> plenty of exchanges still use the XRB symbol internally

From the above list it looks like there's not so many of them. Just `bitz` and `kucoin`... Do you still think it would be a problem? Because, it really looks like that we will have to move from XRB towards NANO, as there has been a lot of confusion with this. Basically, we are trying to conform with CMC currency codes.

> Some programs written using ccxt are likely to rely on the symbol "XRB" in some way, have database rows that reference the old symbol, and so on. 

This is a concern, indeed, but we will announce it beforehand and will make this particular patch optional.I don't like switching these hardcoded codes myself, but it really looks like that we will have to, strategically this is something we should do for further compatibility.

**Comment by kroitor** [comment]
@miracle2k 

> Strong -1 from me.

But it shouldn't be a problem if you want to stay with XRB, you can add these to your config:

```
exchange = new ccxt[id] ({
    'commonCurrencies': {
        'NANO': 'XRB',
        'XRB': 'XRB',
    },
})
```

Because, it's easier to actually switch to proper codes earlier, rather than later...

**Comment by miracle2k** [comment]
@kroitor As a side note: It's interesting how nano and okex use `XRB` as the currency code, but `NANO` in the market symbol. I wonder what the reason for this is. 

As I said, I personally prefer stability in such a case - we will likely see more rebrandings, and if it's not a separate unit of account (i.e. the old symbol has a different value than the new symbol) I see no reason to cause trouble. 

It seems that when it comes to the stock market, ticker symbols sometimes change with a company name (but not always). So the idea of changing the symbol is not unprecedented, I suppose.

Anyhow, if you do make this change, I will figure something out, sure - it's not the end of the world. Replacing common currencies may be an option.

**Comment by kroitor** [comment]
> As a side note: It's interesting how nano and okex use XRB as the currency code, but NANO in the market symbol. I wonder what the reason for this is.

All about it right here: https://github.com/ccxt/ccxt/wiki/Manual#symbols-and-market-ids ) OKEX has a `commonCurrencies` setting here: https://github.com/ccxt/ccxt/blob/master/js/okex.js#L31

**Comment by kroitor** [comment]
> I wonder what the reason for this is.

Often the reason is some issue, like this one: https://github.com/ccxt/ccxt/issues/1853

**Comment by miracle2k** [comment]
FWIW, the  `commonCurrencies` option seems currently ignored by `coinmarketcap`.

**Comment by kroitor** [comment]
@miracle2k yep, their substitutions are a little more involved: https://github.com/ccxt/ccxt/blob/master/js/coinmarketcap.js#L93

I'll do something about it to make it unified soon.

**Pull request merged**
