### PR TITLE
`safeLeverageEntry` for `setLeverage`.

### PR DESCRIPTION
**Pull request by ttodua**
`safeLeverageEntry` to be used in `setLeverage`.
open for further improvements.

### CODE REVIEW

**Comment by ttodua** [comment]
after i've checked the common usage of this, I think this structure might fit, but open for improvements.

**Comment by kroitor** [comment]
> after i've checked the common usage of this, I think this structure might fit, but open for improvements.

> note1, I am not sure about 'status' but might be success in case if that method returns , it means the error is not thrown by exchange, and probably it's gone well, but still, if the exchange returns the status in response, then maybe it should be overriden over 'success'. or should it throw exception if status is not 'success' ?)

The unified possible statuses for all transactions and transfers:
- `ok`, means completely finished, sent out
- `pending`, submitted but not finished yet, awaiting some kind confirmation or approval, either onchain or manual, etc
- `rejected`, submitted, then rejected
- `failed`, submitted, processed and failed for whatever reason
 
> note2, `leverageMode` should be either isolated/cross.

The unified name for that piece of info is `marginType` (`options['marginType']`, `options['defaultMarginType']`, `params['marginType']`, etc). See mentions of `marginType` in the other exchanges in both CCXT and CCXT Pro (huobi, okx).

**Comment by ttodua** [comment]
I've set status to empty as default. idk, if you think the `safeX` methods should have `'status':'ok'`  as initial value, we can set them.

**Comment by kroitor** [comment]
> I've set status to empty as default. idk, if you think the `safeX` methods should have `'status':'ok'` as initial value, we can set them.

no, i think `undefined` is ok.

**Comment by ttodua** [comment]
@kroitor can you tell how travis fails with 2888the line in exchange.py, while there is not such line?

**Comment by kroitor** [comment]
> @kroitor can you tell how travis fails with 2888the line in exchange.py, while there is not such line?

I guess, you found the cause ? It's not travis, it's flake8. I'm not sure why 2888.

**Comment by ttodua** [comment]
yes, fixed. ready for merging

**Pull request closed without merging**
