### PR TITLE
BitMEX fetchMyTrades

### PR DESCRIPTION
**Pull request by andiradulescu**
Implemented fetchMyTrades for BitMEX and extended parseTrade method.

### CODE REVIEW

**Comment by kroitor** [comment]
Hi! Thanks for the contribution! Appreciate the effort! I have one question, however, is this different from this: https://github.com/ccxt/ccxt/pull/4256 ?

**Comment by andiradulescu** [comment]
Hi @kroitor, let me check more thoroughly

**Comment by andiradulescu** [comment]
I checked @kroitor, it is the same as https://github.com/ccxt/ccxt/pull/4256 but complete with `parseTrade`. I see that https://github.com/ccxt/ccxt/pull/4256 diverted to `fetchLedger` but we're using `fetchMyTrades` in our project. I thought this might be useful for other people too. Thanks!

**Comment by kroitor** [comment]
@andiradulescu got it, thx a lot! Will merge the two asap.

**Pull request merged**
