### PR TITLE
Poloniex: implement fetchClosedOrder

### PR DESCRIPTION
**Pull request by brandsimon**
As discussed in #9477 here is the implementation.
I am not sure the fee handling in createOrder is correct, but if it is, the fee handling in parseTrades should also be correct.

### CODE REVIEW

**Comment by kroitor** [comment]
I will need a bit of time to adjust it to the new approach that we are trying to implement, namely, the support for string-based precision numbers, that requires adding a few wrappers to fetchClosedOrder to parse the order with respect to user settings (whether one wants native floats or string-based precision). Will get it merged soon.

**Comment by brandsimon** [comment]
@kroitor 
Is there any info available for this new approach?

**Comment by kroitor** [comment]
@brandsimon we will add more on that to the CONTRIBUTING doc. The difference is that we don't add new `safeFloat` calls anymore, and we don't do the math in the `parseOrder` handler. Instead, we are replacing `safeFloat` calls with `safeNumber` calls, designed to return either floats or strings, depending on the user preferences. We also avoid doing the arithmetics in handlers, instead we are moving the maths out to the new `safeOrder` base method that does all the maths based on the new `Precise` base class (based on strings). Most of that can be found throughout the lib in various places. Since we have not finished transitioning yet, at this time it's a mix of the old approach (with safeFloats) and the new approach (with safeNumber + safeOrder).

**Comment by brandsimon** [comment]
@kroitor 
Great, thank you very much :)

**Comment by kroitor** [comment]
@brandsimon we appreciate your involvement!

**Comment by brandsimon** [comment]
@kroitor 
There is now an issue: `Precise class initiated with something other than a string or int`
Does the Precise class not support floats?

**Comment by kroitor** [comment]
@brandsimon nope, it does not, we have to feed it with safeString instead of safeNumber, will get fixed shortly.

**Comment by brandsimon** [comment]
@kroitor Any update on this?

**Comment by kroitor** [comment]
@brandsimon pardon, will get it done in a few hours today.

**Comment by kroitor** [comment]
@brandsimon plz let us know if you have this issue with version 1.52.76+, thanks for your help!

**Comment by brandsimon** [comment]
@kroitor 
amount, filled, ... is still a float. Is this the correct behavior?
As I understood, it should be returned as string?

**Comment by brandsimon** [comment]
@kroitor Why was my complete calculation removed? Was there anything wrong with it?

**Comment by frosty00** [comment]
@brandsimon you can change the `poloniex.number = str` to see it as a string, unfortunately @kroitor doesn't completely the point of this yet - for example you can't do

```
const x = this.safeNumber (response, 'a');
const y = x + z;
```

you need to do:

```
Precise.stringAdd (x, z)
```

otherwise it just adds more work for me...

**Comment by frosty00** [comment]
@kroitor this is particularly heinous cause it also defeats the entire point of safeOrder...

**Comment by frosty00** [comment]
@brandsimon look inside safeOrder, we are in the process of unifying it for strings

**Comment by brandsimon** [comment]
@frosty00 
Thank you very much, I understood it from kroiter that it is not possible to keep the old behavior (so it seamed like a bug to me).

Do you know why my calculation was removed?

**Comment by frosty00** [comment]
yeah because it duplicates the code in safeOrder

**Comment by brandsimon** [comment]
@frosty00 
Ah okay, but it was not duplicate, now there are a lot of fields undefined, before they were not.

**Comment by frosty00** [comment]
@brandsimon if that is the case then the fields you calculated were not calculated correctly, the code for safeOrder is designed in a particular way on purpose

**Comment by kroitor** [comment]
> Ah okay, but it was not duplicate, now there are a lot of fields undefined, before they were not.

@brandsimon can you please list those specific fields? I will take a look to see if populating them is possible.

**Pull request merged**
