### PR TITLE
Lykke API V2 requests compatability support

### PR DESCRIPTION
**Pull request by CryptoBeliever1**
The previous Lykke API version is deprecated now.
Added or updated createOrder, cancelOrder, cancelOrders functions to support new API version.

### CODE REVIEW

**Comment by kroitor** [comment]
Hi! 

First of all, thanks for your involvement! A quick question – can you please paste your verbose request+response for the edited calls here? 

Please, use [GitHub markdown](https://guides.github.com/features/mastering-markdown/) for readability and padding, surround your code and/or output with triple backticks (&#096;&#096;&#096;), like shown below:

&#096;&#096;&#096;
your output here
&#096;&#096;&#096;

Thanks again!

**Comment by kroitor** [comment]
Also, looks like `cancelOrders` should be renamed to `cancelAllOrders` and we should add that to the `has` metainfo.

The signature of `cancelOrders` is:

```JavaScript
async cancelOrders (ids, symbol = undefined, params = {} {
    // delete multiple orders by order ids
}
```

And the signature of `cancelAllOrders` is:

```JavaScript
async cancelAllOrders (symbol = undefined, params = {}) {
    // delete multiple orders (also apply the symbol, if it is specified in the arguments and supported by the exchange)
}
```

**Comment by CryptoBeliever1** [comment]
```createOrder()```
```
Request: POST https://hft-api.lykke.com/api/Orders/v2/limit {'api-key': 'myapikey', 'Accept': 'application/json', 'Content-Type': 'application/json', 'User-Agent': 'python-requests/2.24.0', 'Accept-Encoding': 'gzip, deflate'} {"AssetPairId":"BTCUSD","OrderAction":"Sell","Volume":0.01244592,"Price":9293.0}                                              
                                                                                                                 
Response: POST https://hft-api.lykke.com/api/Orders/v2/limit 200 {'Server': 'nginx', 'Date': 'Tue, 14 Jul 2020 23
:52:54 GMT', 'Content-Type': 'application/json; charset=utf-8', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Request-Context': 'appId=cid-v1:xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx'} {"Id":"xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"}
```

```cancelOrder()```
```
Request: DELETE https://hft-api.lykke.com/api/Orders/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx {'api-key': 'myapikey', 'Accept': 'application/json', 'Content-Type': 'application/json', 'User-Agent': 'python-requests/2.24.0', 'Accept-Enco
ding': 'gzip, deflate'} None                                                                                  

Response: DELETE https://hft-api.lykke.com/api/Orders/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx 200 {'Server': 'nginx', 'Date': 'Wed, 15 Jul 2020 08:17:08 GMT', 'Content-Length': '0', 'Connection': 'keep-alive', 'Request-Context': 'appId=cid-v1:xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx'}
```

```cancelOrders()```
```
Request: DELETE https://hft-api.lykke.com/api/Orders?assetPairId=BTCUSD&side=Buy {'api-key': 'myapikey', 'Accept': 'application/json', 'Content-Type': 'application/json', 'User-Agent': 'python-requests/2.24.0', 'Accept-Encoding': 'gzip, deflate'} None    
                                                                                                                                                                                                               
Response: DELETE https://hft-api.lykke.com/api/Orders?assetPairId=BTCUSD&side=Buy 200 {'Server': 'nginx', 'Date':
 'Tue, 14 Jul 2020 23:56:25 GMT', 'Content-Length': '0', 'Connection': 'keep-alive', 'Request-Context': 'appId=cid-v1:xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx'} 
```

Ok, I will create a new pull request with ```cancelAllOrders``` instead or ```cancelOrders```

**Comment by CryptoBeliever1** [comment]
Renamed `cancelOrders` and updated has `metainfo`

**Comment by kroitor** [comment]
@CryptoBeliever1 thanks so much! I'll get to it as soon as I can!

**Pull request merged**
