### PR TITLE
Added commonCurrencies for CELO on Coinbase, Coinbase Pro (and Coinbase Prime inherits)

### PR DESCRIPTION
**Pull request by martinvol**
CELO is listed as CGLD on Coinbase, so this PR makes ccxt aware of that.

### CODE REVIEW

**Comment by kroitor** [comment]
@martinvol thanks for your involvement!

For the future – we don't need to submit all the files, just one source .js file is enough to go. 

- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#multilanguage-support
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#transpiled-generated-files

Thx again!

**Comment by martinvol** [comment]
Shall I remove those files in this PR or they are good?

I auto-generated them with `npm run build`.

**Comment by kroitor** [comment]
> Shall I remove those files in this PR or they are good?

If you could remove everything except coinbasepro.js – i'll merge right away. Thank you!

> I auto-generated them with npm run build.

Yep, it is used for testing it locally. Our Travis CI will do the same and will rebuild the generated files upon merging anyway.

**Comment by martinvol** [comment]
Here we go!

**Pull request merged**
