### PR TITLE
 okcoinusd: more regression tests

### PR DESCRIPTION
**Pull request by mkutny**
As it touches `test.js` I tried to do it as little intrusive, as possible.

Apart from removing my old semicolons (thanks to linter) I implemented the following approach:
- `keys.json` now has `.extendedTest` property
- this property is set only for okex now (as it has trading permissions)
- I enabled few trading tests that rely on creating & canceling rights and they passed

What's next:
- I'll be slowly moving my regression suite into `test.js` if you're fine with it, there are much more tests there
- as we add trading permissions for other exchanges we'll be able to regress them as well

Apart from that:
- okex's handling of spot and futures markets is different (different error codes, different order creation params). I guess it might be the same with other exchanges, so we need to foresee testing of multiple symbols per exchange.

### CODE REVIEW

**Comment by kroitor** [comment]
We are merging this PR shortly. Thank you!

**Comment by kroitor** [comment]
Oops, the py-file somehow got in there ) Can you remove it? Or is it intentional?

**Comment by mkutny** [comment]
Hmm... Not sure I understand fully how does it happen from time to time.

When I see a conflict I merge master into PR branch. I resolve a conflict and get sure that `git diff master` reflects only PR's file(s). `git commit; git push` and a lot of unrelated files get into the branch.

How does it happen?

**Comment by mkutny** [comment]
And Travis also added a commit to this branch. Why?

**Comment by mkutny** [comment]
BTW, in Travis log, I see a lot of false negatives coming from Python2 "hostname doesn't match" error. As I far as I googled they seem to be a result of failed SSL verification when a server has several certificates.

Multi-certificate support is natively available in Python 2.7.9+. I'm not deep in Travis but I guess if we add this version to `.travis.yml` it should fix the issue?

**Comment by kroitor** [comment]
> When I see a conflict I merge master into PR branch. I resolve a conflict and get sure that git diff master reflects only PR's file(s). git commit; git push and a lot of unrelated files get into the branch.
> How does it happen?

Not sure, but maybe you're adding them somehow with `commit -am` by chance?

> And Travis also added a commit to this branch. Why?

Which one... I don't see it in the commit log for this pr, just the commits from you.

> Multi-certificate support is natively available in Python 2.7.9+. I'm not deep in Travis but I guess if we add this version to .travis.yml it should fix the issue?

This is slightly complicated, their default is Py3, and we install some other pythons down the road, in order for it to work. But, hey, thanks for the hint anyway, this has been bugging me for a while, will try switching to a newer version, for sure!

**Comment by mkutny** [comment]
>> And Travis also added a commit to this branch. Why?

> Which one... I don't see it in the commit log for this pr, just the commits from you.

I seem to pull repo in a state when Travis hasn't built and tagged the last commit yet. I merged and pushed that untagged version. Then Travis made a build, pushed and its tagged commit appeared along mine ones. It's gone after I pulled, merged and pushed the update. Quite strange still.

It's easier to see than explain but now I know what to watch for, will let you know when it happens.

> This is slightly complicated, their default is Py3, and we install some other pythons along the way, in order for it to work.

I'm not really deep in that, have got 2.7.9+ mentioned in their faq:
"[Python3 and Python 2.7.9+ include native support for SNI in their SSL modules](http://docs.python-requests.org/en/master/community/faq/)"

**Pull request merged**
