### PR TITLE
New exchange: Gooplex

### PR DESCRIPTION
**Pull request by jbiason**
Adding a Brazilian exchange: Gooplex

### CODE REVIEW

**Comment by jbiason** [comment]
Hi, sorry to bother, but did I forget something?

(My boss is asking if we can do something to have this approved :grimacing: )

**Comment by kroitor** [comment]
@jbiason hi! Pardon for the delays, we will get to it asap. Please, reach out to info@ccxt.trade if you wish to speed it up. Thank you!

**Comment by cj4c0b1** [comment]
Hallo @kroitor and @jbiason 
I'm working on a project that needs to integrate with gooplex and I get into the target code here and unfortunately all endpoints available are not working or out of the patterns, so almost useless for any integration purpose.
I did my own corrections only in python and get it to work for this endpoints that are important for my arbitrage/market making project:

- fetch_order_book
- create_order
- fetch_open_orders
- cancel_order
- fetch_balance

good luck.
Cya.

**Comment by jbiason** [comment]
Hi @cj4c0b1,

Can you point out the problems you found? I just did a `fetch_order_book` and it seems it is working fine:

```
from ccxt.gooplex import gooplex
g = gooplex(config={'apiKey': 'my_key', 'secret': 'my_secret'})
g.fetch_order_book('BTC/BRL')
# result: {'lastUpdateId': 15390086, 'bids': [['100481.00000000', '0.17318600'], ['100447.00000000', '0.00492800'], ['100442.00000000', '0.00110500'], ['100430.00000000', '0.52560000'], ['100380.00000000', '0.07434000'], ['100335.00000000', '0.00996600'], ['100329.00000000', '0.18377700'], ['100276.00000000', '0.52159300'], ['100245.00000000', '0.00100100'], ['100224.00000000', '0.48278100'], ...
```

It may be that the result is not the one you're expecting, but I think (but not totally sure) the results follow the spec used by ccxt (I clearly remember some tests failing 'cause the result was not in the proper format).

**Comment by fernandobender** [comment]
waiting for this merge!

**Review by jonhpham — APPROVED** [review]

**Comment by eduardoungaratto** [comment]
Hi @everyone!
I'm working with a lot of integrations, and at this point depends of this merge. 
Any estimates when this PR will be merged ?
Tks

**Comment by ttodua** [comment]
dead exchange

**Pull request closed without merging**
