### PR TITLE
[dsx] fix undefined symbol in parse order

### PR DESCRIPTION
**Pull request by npomfret**

### CODE REVIEW

**Comment by kroitor** [comment]
Is there a symbol that is not returned from their markets?

**Comment by npomfret** [comment]
I was getting an undefined symbol: https://github.com/ccxt/ccxt/issues/5770

... maybe I misunderstood the previous implementation?

**Comment by npomfret** [comment]
FYI - you don't need to specify a market as a parameter to the fetchOrders function.

**Comment by kroitor** [comment]
> I was getting an undefined symbol: #5770

Yep, I mean, which `marketId` was it? If it is not found in this.markets_by_id, then we might still have ways to parse it, depending on the symbol in question.

**Comment by npomfret** [comment]
bcheur

**Comment by npomfret** [comment]
Let me revert

**Comment by kroitor** [comment]
@npomfret looks like they renamed that id to bcceur? Or where does `bcheur` come from? Do they still return `bcheur` from some of their endpoints?

**Comment by npomfret** [comment]
https://dsx.uk/mapi/info doesn't have bcheur.  Would a better solution be to fall back on some _toUppserCase & split_ type logic?

**Comment by npomfret** [comment]
> Do they still return bcheur from some of their endpoints?

Yes

**Comment by kroitor** [comment]
@npomfret 

> Would a better solution be to fall back on some toUppserCase & split type logic?

Yes, I was thinking of something like that, however, their ids don't have a separator and variable-lengths, so it would be more difficult to parse it properly... I'll think on it a bit and will get this sorted shortly.

**Comment by npomfret** [comment]
Feel free to close/abandon this PR

**Comment by kroitor** [comment]
@npomfret i'm trying to understand what is designated by bch in bcheur – is it  bch before the fork, or is it some of the modern bch forks that was simply renamed to bcc ? Because it matters if those are the same symbol. So your bcc account balance should've been inherited from your bch account balance, is that correct?

**Comment by npomfret** [comment]
Yes, I believe it's the same token - no wired forks are involved.  I think they started out using BCC as the symbol for bitcoincash, then started (but didn't finish migrating their systems) to using BCH.

**Comment by kroitor** [comment]
@npomfret yep... the following is very confusing, however:

https://dsx.uk/developers/publicApiV2

> **Important notice**
> On March 12, 2018 the Bitcoin Cash ticker was changed from BCC to BCH at DSX platform. Hovewer, to ensure backward-compatibility, current API still uses the BCC ticker for Bitcoin Cash. The ticker will be changed to BCH in the next version of API.

So, they had bch, then it became bcc, and then it will become bch again? )
Anyways, adding a workaround for this now...

**Comment by kroitor** [comment]
Pairs like `usdtusd` don't really make it easy... Since you don't know if it's USDT / USD or USD / TUSD ))

**Comment by npomfret** [comment]
Perhaps if it's ambiguous we don't do the translation and log a warning or something?  Then fix when the new API is released.

**Comment by kroitor** [comment]
@npomfret no worries, i'm just commenting along the way, sorting it out now )

**Comment by kroitor** [comment]
@npomfret i think this should do the job... It will be awesome if you report back whether it works smoothly with build 1.18.1127 (expected to arrive in 15 minutes from now). Lmk if anything. Thx!

**Comment by npomfret** [comment]
@kroitor tested this morning - looks good.  Thanks

**Pull request merged**
