### PR TITLE
fix(huobi): ws try to decompress gziped message

### PR DESCRIPTION
**Pull request by lovepocky**
Sometimes huobi ws subscribtion receives gziped message, and cause exception

telegram-cloud-photo-size-5-6226484024419923568-w

### CODE REVIEW

**Comment by carlosmiei** [comment]
Hello @lovepocky, do you know how to reproduce this behavior? We have to make sure we always fix the issue for every supported language

**Comment by lovepocky** [comment]
> Hello @lovepocky, do you know how to reproduce this behavior? We have to make sure we always fix the issue for every supported language

It is not happen constantly, i will try to make a script later to reproduce it.

**Comment by lovepocky** [comment]
Sorry i cant reproduce it now. maybe has been fixed by huobi api.
If it appears again, i will append result here

**Comment by carlosmiei** [comment]
> Sorry i cant reproduce it now. maybe has been fixed by huobi api. If it appears again, i will append result here

@lovepocky I remember facing this issue in the past but yeah seems a bit random, nonetheless if you stumble on it again please let us know

**Comment by lovepocky** [comment]
> > Sorry i cant reproduce it now. maybe has been fixed by huobi api. If it appears again, i will append result here
> 
> @lovepocky I remember facing this issue in the past but yeah seems a bit random, nonetheless if you stumble on it again please let us know

I guess that huobi api send gziped data with wrong message type as text. so it can't be encode with utf8.

**Pull request closed without merging**
