### PR TITLE
tests - argvs parsing

### PR DESCRIPTION
**Pull request by ttodua**
once and for all we can move to a "bit better" parsing of args.
till date, the sequence mattered (i.e. first should have been exchange, second symbol,,,) and there was no easy way to pass method from `run-tests` till test.ts/php/js.

now, test.ts/php would not need to rely on order of the args, but filter them by `/` (symbol) or `()` (method) existence in args, to  detect them.

so, we can run:  
`node run-tests --js gate fetchTrades() --info` 

to test specific method for exchange (or omit `gate` exchange and it will test for all exchanges

Note: this update enhances all langs, but in python we only pass either symbol or method args, not both together ( python needs a bit complex changes in `test.py` and it can be done in future, the main need here is for `ts/js` because it is needed mostly during development.)

### CODE REVIEW

**Comment by ttodua** [comment]
adding python version soon

**Comment by ttodua** [comment]
python version is a bit complex, so i've not touched it much, just added an ability to get method names too in place of symbol.
no breaking change

**Comment by ttodua** [comment]
seems this has some bug, fixing now

**Comment by ttodua** [comment]
@carlosmiei  might be ready, unrelated issues happen

**Comment by ttodua** [comment]
@carlosmiei PR ready, lmk your thoughts

**Comment by carlosmiei** [comment]
> @carlosmiei PR ready, lmk your thoughts

@ttodua Yeah will merge it soon

**Comment by ttodua** [comment]
> @ttodua Yeah will merge it soon

ok 👍

**Comment by ttodua** [comment]
> > @carlosmiei PR ready, lmk your thoughts
> 
> @ttodua Yeah will merge it soon

whenever you find time for this, because tests would be (already are being) updated sideways and it might lead to conflicts..

**Pull request merged**
