### PR TITLE
Add support for MXC(https://mxc.ceo)

### PR DESCRIPTION
**Pull request by lobatt**
Preliminary support for https://mxc.ceo

This is not a high-quality integration since their own API is less than sufficient, e,g:
1. Order creation times are returned in GMT+8 timezone without specifying it
2. There is no way to get the true matched price/cost/fees for an order
3. there is no way to deposit/withdraw/transfer using API

However, this is working and I would like to contribute my effort to ccxt as an appreciation for the work that has been done before me. 
I hope this could be helpful to someone.

I didn't bother to include a Logo and/or referral link to them since I am not seeking to profit from this, so please feel free to add your own.

The functionality tested are:
1. getting market info
2. getting market depth
3. placing orders
4. querying orders
5. canceling orders

### CODE REVIEW

**Comment by lobatt** [comment]
Will reopen after CI failures fixed

**Comment by lobatt** [comment]
Bug fixed.
However I am not in anyway a JS expert, please let me know if there is anything missing.

**Comment by runvnc** [comment]
Hello, thank you so much for working on this!
One thing I don't understand though:  why are you using their v1 API rather than their v2 API?  Their v2 API has this:
```
 GET /open/api/v2/order/deal_detail
{
    "code": 200,
    "data": [
        {
            "symbol": "ETH_USDT",
            "order_id": "a39ea6b7afcf4f5cbba1e515210ff827",
            "quantity": "54.1",
            "price": "182.6317377",
            "amount": "9880.37700957",
            "fee": "9.88037700957",
            "trade_type": "BID",
            "fee_currency": "USDT",
            "is_taker": true,
            "create_time": 1572693911000
        }
    ]
}
```

**Comment by runvnc** [comment]
Actually I just realized that work was from December and its April now so they might now have had their v2 ready before.

**Comment by trumhemcut** [comment]
Hi all, what is the status for this? Can we bring this forward?

**Comment by kroitor** [comment]
@trumhemcut we will need the time to review and fix it:

- https://github.com/ccxt/ccxt/wiki/FAQ#what-is-the-status-of-this-pr-any-update

**Comment by lobatt** [comment]
> Actually I just realized that work was from December and its April now so they might not have had their v2 ready before.

Yes, that was exactly the case, would be super interested if anyone wants to migrate it to v2.

**Comment by lfzCarlosC** [comment]
Do we also include Python support in this ticket?

**Comment by kroitor** [comment]
@lfzCarlosC yes: https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#multilanguage-support

**Comment by fxmarty** [comment]
Any news?

**Pull request closed without merging**
