### PR TITLE
New Exchange: Deepwaters

### LINKED ISSUE #17035: Deepwaters integration
### Exchange Name

Deepwaters

### URL of the Exchange

https://deepwaters.xyz

### URL of the Exchange's API docs

https://rest.docs.api.deepwaters.xyz

### Why should this exchange be implemented?

I've already written the exchange integration: https://github.com/ccxt/ccxt/pull/17034/files

I realized I need to run it through the linter, so converted to a draft PR right now.

Let me know if there's anything mandatory with regards to error handling or parameter parsing that I missed

### PR DESCRIPTION
**Pull request by HartS**
closes #17035

### CODE REVIEW

**Comment by ttodua** [comment]
May I know, whether 17045 PR supersedes this PR? (so, this PR can be closed in favor of 17045)?

**Comment by HartS** [comment]
Sorry @ttodua I haven't paid any attention to the changes in ccxt lately, nor have I looked at the other branch you mentioned. To summarize my work on this branch briefly, I made an initial rough PR for adding deepwaters to ccxt, then while I was working on improvements, @gmussi created a new PR which seemed to build on top of my work and also added some improvements.

I did my best to integrate the changes from both branches, but it looks like  #17045 has had marginally more recent updates;  I'd wager that at this point it's more current, but I won't be looking more closely at ccxt or its various integrations in the near future to be able to say for sure.

**Comment by gmussi** [comment]
Yes, I had completely refactor the code to move it to typescript and add all the new features launched with ccxt 2.0 and 3.0.
I haven't come back to test the compatibility with ccxt 4.0 though, and do not intend to do so anytime soon, unless someone is sponsoring this work.

**Comment by ttodua** [comment]
Thank you guys for your input, I'll mark #17045 as more recent and will leave that PR open for future revision.

**Comment by carlosmiei** [comment]
@gmussi Can you please ping us on discord or telegram?

**Pull request closed without merging**
