### PR TITLE
Update okex.js

### PR DESCRIPTION
**Pull request by yyq321**
if (market['option'] || market['spot']) in fetch_ohlcv is meaningless and would influence the futures and swap OHLCV we get.

### CODE REVIEW

**Comment by kroitor** [comment]
@yyq321 hi! Can you please clarify a bit what you mean? See this related issue: https://github.com/ccxt/ccxt/issues/7478

**Comment by yyq321** [comment]
@kroitor Last time I post #7521 and I think I may not express my issue clearly.
Last time you give me the code:
```python
import ccxt

print('CCXT Version:', ccxt.__version__)

exchange = ccxt.okex({
    'enableRateLimit': True,  # required https://github.com/ccxt/ccxt/wiki/Manual#rate-limit
})
 
 markets = exchange.load_markets()
 
 ohlcvs = exchange.fetch_ohlcv('BTC-USDT-SWAP', '3m')
 
 num_ohlcvs = len(ohlcvs)
 
 for ohlcv in ohlcvs:
     print(exchange.iso8601(ohlcv[0]), ohlcv[1:])
 
 print('Fetched:', num_ohlcvs, 'ohlcvs')
 if num_ohlcvs:
     print('From:', exchange.iso8601(ohlcvs[0][0]))
     print('To:', exchange.iso8601(ohlcvs[-1][0]))
 ```
Say now is 8:04, if I run this code, I would get
 ```
...
2020-09-07T07:57:00.000Z [10139.6, 10139.7, 10115.9, 10117.8, 47.55]
2020-09-07T08:00:00.000Z [10117.7, 10117.8, 10108.6, 10109.7, 41.49]
Fetched: 300 ohlcvs
From: 2020-09-06T17:03:00.000Z
To: 2020-09-07T08:00:00.000Z
 ```
However, if I change `ohlcvs = exchange.fetch_ohlcv('BTC-USDT-SWAP', '3m')` to `ohlcvs = exchange.fetch_ohlcv('BTC/USDT', '3m')`, I would get
```
...
2020-09-07T08:00:00.000Z [10115.5, 10115.6, 10106.6, 10106.7, 26.49900899]
2020-09-07T08:03:00.000Z [10106.6, 10106.7, 10104.7, 10104.8, 5.94826376]
Fetched: 200 ohlcvs
From: 2020-09-06T22:06:00.000Z
To: 2020-09-07T08:03:00.000Z
```
You can see I can get the k-line start at 08:03:00 for `BTC/USDT` but cannot get it for `BTC-USDT-SWAP`. After I read `okex.js`, I find that `if (market['option'] || market['spot'])` is weird
```
if (market['option'] || market['spot']) {
            method = market['type'] + 'GetInstrumentsInstrumentIdCandles';
            if (since !== undefined) {
                if (limit !== undefined) {
                    request['end'] = this.iso8601 (this.sum (since, limit * duration * 1000));
                }
                request['start'] = this.iso8601 (since);
            } else {
                if (limit !== undefined) {
                    const now = this.milliseconds ();
                    request['start'] = this.iso8601 (now - limit * duration * 1000);
                    request['end'] = this.iso8601 (now);
                }
            }
        } else {
            method = market['type'] + 'GetInstrumentsInstrumentIdHistoryCandles';
            if (since !== undefined) {
                if (limit === undefined) {
                    limit = 300; // default
                }
                request['start'] = this.iso8601 (this.sum (since, limit * duration * 1000));
                request['end'] = this.iso8601 (since);
            } else {
                if (limit !== undefined) {
                    const now = this.milliseconds ();
                    request['end'] = this.iso8601 (now - limit * duration * 1000);
                    request['start'] = this.iso8601 (now);
                }
```
This if statement does not consider the situation of futures and swap. So, I remove this if-else statement. Actually, for okex, `GetInstrumentsInstrumentIdHistoryCandles` in else part is useless, because we can get history data by just change the parameter `since` and `limit` in `fetch_ohlcv`.

After I changed `okex.js`, I can get the information of current(8:03) k-line for `BTC-USDT-SWAP`.

**Comment by kroitor** [comment]
@yyq321 

> This if statement does not consider the situation of futures and swap. So, I remove this if-else statement. 

The logic goes this way:

```
if (option or spot) {
} else { // futures or swap
}
```

> Actually, for okex, GetInstrumentsInstrumentIdHistoryCandles in else part is useless, because we can get history data by just change the parameter since and limit in fetch_ohlcv.

As you can see from these issues https://github.com/ccxt/ccxt/issues/7478 + https://github.com/ccxt/ccxt/pull/7463, there's a problem with OKEX OHLCVs:
- we either use the recent candles, and then you can't go back in history too far
- or you can use the history endpoint, and then you can paginate back into the history, but you can't use certain pairs

We will add a configurable option to change this behavior depending on the user needs.

**Comment by yyq321** [comment]
@kroitor Ok, thanks.

**Pull request merged**
