### PR TITLE
Gate borrowMargin, repayMargin

### PR DESCRIPTION
**Pull request by Dan-krm**
Added borrowMargin and repayMargin to Gate.

borrowMargin:
https://www.gate.io/docs/apiv4/en/#lend-or-borrow
https://www.gate.io/docs/apiv4/en/#create-a-cross-margin-borrow-loan

repayMargin:
https://www.gate.io/docs/apiv4/en/#repay-a-loan
https://www.gate.io/docs/apiv4/en/#repay-cross-margin-loan

### Isolated borrowMargin:
```
node examples/js/cli gate borrowMargin USDT 100 LTC/USDT '{"rate":"0.0002"}'

gate.borrowMargin (USDT, 100, LTC/USDT, [object Object])
2022-06-28T05:31:18.982Z iteration 0 passed in 310 ms

{
  id: 34267439,
  currency: 'USDT',
  amount: 100,
  symbol: 'LTC/USDT',
  timestamp: 1656395427000,
  datetime: '2022-06-28T05:50:27.000Z',
  info: {
    id: '34267439',
    create_time: '1656395427',
    expire_time: '1657258279',
    status: 'loaned',
    side: 'borrow',
    currency: 'USDT',
    rate: '0.0002',
    amount: '100',
    days: '10',
    auto_renew: false,
    currency_pair: 'LTC_USDT',
    left: '0',
    repaid: '0',
    paid_interest: '0',
    unpaid_interest: '0.003333333333'
  }
}
2022-06-28T05:31:18.982Z iteration 1 passed in 310 ms
```

### Isolated repayMargin:
```
node examples/js/cli gate repayMargin USDT 100.003333333333 LTC/USDT '{"mode":"all","id":"34267439"}'

gate.repayMargin (USDT, 100.003333333333, LTC/USDT, [object Object])
2022-06-28T05:37:06.053Z iteration 0 passed in 374 ms

{
  id: 34267439,
  currency: 'USDT',
  amount: 100,
  symbol: 'LTC/USDT',
  timestamp: 1656395427000,
  datetime: '2022-06-28T05:50:27.000Z',
  info: {
    id: '34267439',
    create_time: '1656395427',
    expire_time: '1657258279',
    status: 'finished',
    side: 'borrow',
    currency: 'USDT',
    rate: '0.0002',
    amount: '100',
    days: '10',
    auto_renew: false,
    currency_pair: 'LTC_USDT',
    left: '0',
    repaid: '100',
    paid_interest: '0.003333333333',
    unpaid_interest: '0'
  }
}
2022-06-28T05:37:06.053Z iteration 1 passed in 374 ms
```

### cross borrowMargin:
```
gate.borrowMargin (USDT, 100)
2022-06-30T18:02:40.047Z iteration 0 passed in 247 ms

{
  id: 12629199,
  currency: 'USDT',
  amount: 100,
  symbol: undefined,
  timestamp: 1656612159852,
  datetime: '2022-06-30T18:02:39.852Z',
  info: {
    id: '12629199',
    create_time: '1656612159852',
    update_time: '1656612159852',
    currency: 'USDT',
    amount: '100',
    text: 'apiv4',
    status: '2',
    repaid: '0',
    repaid_interest: '0',
    unpaid_interest: '0.001620833333'
  }
}
2022-06-30T18:02:40.047Z iteration 1 passed in 247 ms
```

### cross repayMargin:
```
gate.repayMargin (USDT, 100.001620833333)
2022-06-30T18:05:39.081Z iteration 0 passed in 268 ms

{
  id: 12629207,
  currency: 'USDT',
  amount: 100,
  symbol: undefined,
  timestamp: 1656612326140,
  datetime: '2022-06-30T18:05:26.140Z',
  info: {
    id: '12629207',
    create_time: '1656612326140',
    update_time: '1656612326157',
    currency: 'USDT',
    amount: '100',
    text: 'apiv4',
    status: '3',
    repaid: '100',
    repaid_interest: '0.001620833333',
    unpaid_interest: '0'
  }
}
2022-06-30T18:05:39.081Z iteration 1 passed in 268 ms
```

### CODE REVIEW

**Comment by kroitor** [comment]
> These methods still need to be tested.

Let me know your results, or if anything.

**Comment by Dan-krm** [comment]
> Let me know your results, or if anything.

I currently don't have access to Gate in my country but am looking to get a high quality VPN, these methods would probably require KYC though

**Comment by dmatora** [comment]
repay for isolated requires loan id, is there a way to get it when borrowing done using auto borrowing on trade?

**Comment by Dan-krm** [comment]
@dmatora You should be able to just use the id returned when you call borrowMargin, createOrder or fetchOpenOrders

**Pull request merged**
