### PR TITLE
New exchange: btcex

### PR DESCRIPTION
**Pull request by sc0Vu**
Add btcex exchange

https://docs.btcex.com/

TODO:
- [ ] pass withdraw test from cli

### CODE REVIEW

**Comment by samgermain** [comment]
New exchange PRs should just be the one js file, the `fetch... -> ` lines should be moved to another PR, there's also a lot of transpiled PHP and python in this PR that should probably be removed

**Comment by frosty00** [comment]
@kroitor it's ready to merge, pls add the logo

**Review by frosty00 — APPROVED** [review]

**Comment by frosty00** [comment]
actually it looks like sc0vu copied and pasted most of the code from deribit, we should use inheritance...

**Comment by frosty00** [comment]
@kroitor pls add the logo to here when possible

**Comment by kroitor** [comment]
> @kroitor pls add the logo to here when possible

Sure, will do!

**Pull request merged**
