### PR TITLE
Update manual.rst: clarification trade vs. transaction structure

### PR DESCRIPTION
**Pull request by Bomper**

### CODE REVIEW

**Comment by carlosmiei** [comment]
@Bomper thanks for your contribuition but this file is generated automatically, can you please update Readme.md instead?

**Comment by Bomper** [comment]
I couldn't find a README.md that seems to correspond to that manual.rst. Why use .rst anyway instead of Markdown directly all the way? This makes it harder to do drive-by docs contribs.

**Comment by carlosmiei** [comment]
@Bomper Sorry, I meant `Manual.md` https://github.com/ccxt/ccxt/blob/master/wiki/Manual.md#trade-structure

**Comment by Bomper** [comment]
Done, see #23768

**Pull request closed without merging**
