### PR TITLE
Bitfinex fee parsing implemented

### PR DESCRIPTION
**Pull request by MSalopek**
In parseTrade.

### CODE REVIEW

**Comment by kroitor** [comment]
Right, but this method is also called for parsing public trades, that don't have the fee info, and if we access those keys without checking them first (like we do in other fetchMyTrades implementations with support for fees, see Liqui, Binance) Python won't like it (will throw a KeyError). Thus, the tests will most likely fail in that place.

**Comment by kroitor** [comment]
Here it is: https://travis-ci.org/ccxt/ccxt/builds/340519069

screen shot 2018-02-12 at 17 58 29

screen shot 2018-02-12 at 17 59 33

**Comment by kroitor** [comment]
Let me know if you want me to fix it, or if you want to do it yourself. Thx!

**Comment by Sukaesihessy** [comment]
Apa pasword untuk masuk ke lin3-tcr

Pada tanggal 12 Feb 2018 22.00, "Igor Kroitor" <notifications@github.com>
menulis:

**Comment by MSalopek** [comment]
Please check this.

**Pull request merged**
