### PR TITLE
Open Collective integration in Readme

### PR DESCRIPTION
**Pull request by znarf**
Following your support request on Open Collective (1), here is an update to the Readme that I think will correct a few issues you reported.

Does that looks correct? Any feedback?
https://github.com/opencollective/ccxt/blob/opencollective/README.md

For now, I'm using the `images-preview` service which is not the live one, so please don't merge!

(1) https://github.com/opencollective/opencollective/issues/1368#issuecomment-453708448

### CODE REVIEW

**Comment by kroitor** [comment]
@znarf yep, the readme does look correct, however, on our opencollective page we still see three logos instead of two:

screen shot 2019-01-17 at 15 49 59

Not merging and standing by for further instructions ) Let us know if we can help with anything on our side. Thx for your help!

**Comment by kroitor** [comment]
@znarf actually, nope, it's still not fully consistent – the opencollective website shows Nomics is our sponsors, however, it's not listed in sponsors on our website. Can you shed some light on that?

**Comment by znarf** [comment]
@kroitor On the Open Collective website, we're still showing the subscriptions that are not active anymore. In the Readme, we're not displaying these inactive subscriptions.

To make it consistent, I'm proposing to not display inactive subscriptions anymore on the Open Collective website? Would that make sense for you?

**Comment by kroitor** [comment]
> To make it consistent, I'm proposing to not display inactive subscriptions anymore on the Open Collective website? Would that make sense for you?

Yep, thx so much! I was just wondering if that is something we can control from with our user settings? Or is it an admin feature? I mean, is it set for each particular project specifically by opencollective?

**Comment by znarf** [comment]
@kroitor In that case, I'm thinking about first limiting the change to the "Tier" sidebar, and make that the default for everyone.

After that, I think we need more consideration before touching other parts of the Open Collective website.

**Comment by kroitor** [comment]
@znarf from the user perspective I think one would prefer to have two sections:
- a homepage with currently active subscriptions
- a history of donations (all tiers)
But we understand that this isn't that easy taking into account all the details.

So, for now, if we can somehow make it show the active subscriptions everywhere (both the opencollective and the readme) – that would be great. Let me know, if I'm misunderstanding something. Thx again!

**Comment by znarf** [comment]
@kroitor just pushed an update to the Open Collective website. See: https://opencollective.com/ccxt

screen shot 2019-01-18 at 14 45 42
screen shot 2019-01-18 at 14 45 37
screen shot 2019-01-18 at 14 45 33

**Comment by kroitor** [comment]
@znarf thx so much for your involvement! Should we merge this PR now? Or what's our plan? Thx again!

**Comment by znarf** [comment]
@kroitor It's good to go.

**Pull request merged**
