### PR TITLE
fix(tokocrypto) - migration to TICK_SIZE

### PR DESCRIPTION
**Pull request by ttodua**

### CODE REVIEW

**Comment by carlosmiei** [comment]
@ttodua if you change the precison scheme it's mandatory to update the static markets/currencies otherwise the build will not pass

**Comment by carlosmiei** [comment]
image

**Comment by ttodua** [comment]
yes sorry, forgot to draft this, in other PRs i did those changes too. will update this PR shortly

**Comment by ttodua** [comment]
@carlosmiei build passes

**Pull request merged**
