### PR TITLE
binance: nonce -> milliseconds

### PR DESCRIPTION
**Pull request by mkutny**
Not that important but congruent with "binance has no nonce".
Also removed mention of nonce from `sign` to avoid confusion.
And linting.

### CODE REVIEW

**Comment by kroitor** [comment]
Now I have a dilemma, should we throw an Error and transpile it properly, or should we return ExchangeError here instead. Maybe, NotImplemented?

**Comment by mkutny** [comment]
You probably meant `NotSupported`. I thought about it but it deals with exchange's methods not, ccxt methods. We could also remove `nonce()` altogether (so parent's one will be used). Or return `undefined`.

But no-one is expected to call this method anyway, right?

**Comment by mkutny** [comment]
Well, ok. Other exchanges that don't use nonce (like _1broker) don't mention this method at all. So I just think of removing it completely to be consistent with others.

**Comment by kroitor** [comment]
Yep, let's remove it from Binance for now and then, maybe, do something about it in the base class, if needed.

**Pull request merged**
