### PR TITLE
fix #963 - add withdraw method to bitstamp exchange

### LINKED ISSUE #963: Bitstamp withdraw function
Bitstamp exchnage don't implement a withdraw function.

when is ok, i will create a pr.

- OS: Win
- Programming Language: Node/JavaScript
- CCXT version: 1.10.477
- Exchange: Bitstamp
- Method: withdraw

```
↑↑↑ DO_NOT_DELETE_THE_BACKTICKS_AROUND_THE_CODE

MUST_READ_THIS https://github.com/kroitor/ccxt/wiki/Manual#troubleshooting

↓↓↓ DO_NOT_DELETE_THE_BACKTICKS_AROUND_THE_CODE
```

### PR DESCRIPTION
**Pull request by pmizel**
i hope this will help

### CODE REVIEW

**Comment by kroitor** [comment]
Hi!

Thanks for your contribution! Unfortunately, it break a few several rules from here:
https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#derived-exchange-classes

If you could clean it up a bit to conform to those transpilation rules, you would make it much easier for me to merge it. Let me know, if you're going to give it a try. Thx again!

Also related/duplicate to: #777, #963.

**Comment by pmizel** [comment]
Thanks for your support.

**Comment by kroitor** [comment]
@pmizel thx for contributing!

**Comment by Felipe-Mangueira** [comment]
Hey, @kroitor and @pmizel. I was following the updates from this issue and I would just like to report back to you that I tested the last implementation with Bitstamp withdrawals: it's working pretty fine!!! Thx both!

**Comment by kroitor** [comment]
@Felipe-Mangueira thanks for reporting!

**Pull request merged**
