### PR TITLE
binance.createOrder stoploss unification

### PR DESCRIPTION
**Pull request by samgermain**
```
% binance createOrder XRP/USDT limit sell 15 0.754 '{"stopPrice": 0.754}' 
Debugger listening on ws://127.0.0.1:62986/8a1b32d3-c491-4443-a2bc-309a3023c5a1
For help, see: https://nodejs.org/en/docs/inspector
Debugger attached.
2022-03-02T20:23:10.617Z
Node.js: v14.17.0
CCXT v1.74.67
binance.createOrder (XRP/USDT, limit, sell, 15, 0.754, [object Object])
2022-03-02T20:23:11.935Z iteration 0 passed in 646 ms

{
  info: {
    symbol: 'XRPUSDT',
    orderId: '...',
    orderListId: '-1',
    clientOrderId: '...',
    transactTime: '1646252592012',
    price: '0.75400000',
    origQty: '15.00000000',
    executedQty: '0.00000000',
    cummulativeQuoteQty: '0.00000000',
    status: 'NEW',
    timeInForce: 'GTC',
    type: 'STOP_LOSS_LIMIT',
    side: 'SELL',
    stopPrice: '0.75400000',
    fills: []
  },
  id: '...',
  clientOrderId: '...',
  timestamp: 1646252592012,
  datetime: '2022-03-02T20:23:12.012Z',
  lastTradeTimestamp: undefined,
  symbol: 'XRP/USDT',
  type: 'stop_loss_limit',
  timeInForce: 'GTC',
  postOnly: false,
  side: 'sell',
  price: 0.754,
  stopPrice: 0.754,
  amount: 15,
  cost: 0,
  average: undefined,
  filled: 0,
  remaining: 15,
  status: 'open',
  fee: undefined,
  trades: [],
  fees: []
}
```

----------------

```
% binanceusdm createOrder XRP/USDT market sell 20.5 0.754 '{"stopPrice": 0.754, "reduceOnly": true}'          
2022-03-02T19:20:51.154Z
Node.js: v14.17.0
CCXT v1.72.20
binanceusdm.createOrder (XRP/USDT, market, sell, 20.5, 0.754, [object Object])
178 ms
{
  info: {
    orderId: '...',
    symbol: 'XRPUSDT',
    status: 'NEW',
    clientOrderId: '...',
    price: '0',
    avgPrice: '0.00000',
    origQty: '20.5',
    executedQty: '0',
    cumQty: '0',
    cumQuote: '0',
    timeInForce: 'GTC',
    type: 'STOP_MARKET',
    reduceOnly: true,
    closePosition: false,
    side: 'SELL',
    positionSide: 'BOTH',
    stopPrice: '0.7540',
    workingType: 'CONTRACT_PRICE',
    priceProtect: false,
    origType: 'STOP_MARKET',
    updateTime: '1646248852677'
  },
  id: '...',
  clientOrderId: '...',
  timestamp: 1646248852677,
  datetime: '2022-03-02T19:20:52.677Z',
  lastTradeTimestamp: undefined,
  symbol: 'XRP/USDT',
  type: 'stop_market',
  timeInForce: 'GTC',
  postOnly: false,
  side: 'sell',
  price: undefined,
  stopPrice: 0.754,
  amount: 20.5,
  cost: 0,
  average: undefined,
  filled: 0,
  remaining: 20.5,
  status: 'open',
  fee: undefined,
  trades: [],
  fees: []
}
```

### CODE REVIEW

**Comment by kroitor** [comment]
@samgermain 

> So that we can just use the unified method of creating a stoploss order where you add stopPrice to params?

Yep, that's exactly what we want.

**Comment by samgermain** [comment]
This unifies the arguments, but the response isn't unified. The response type is `type: 'stop_market',`, but I think that we should unify it to `market` and add another key for `isStop` or something. On some exchanges, like kucoin, the response can be non-obvious as to whether it's a stop order (e.g. https://discord.com/channels/700048804539400213/888978375882977350/939446659212009492)

**Comment by samgermain** [comment]
@kroitor This PR should be all good in my opinion

**Comment by samgermain** [comment]
@kroitor This is a non-breaking PR, try to leave it open too long

**Pull request merged**
