### PR TITLE
hitbtc2: fetchTicker: close -> last

### PR DESCRIPTION
**Pull request by mkutny**

### CODE REVIEW

**Comment by mkutny** [comment]
Hmm... these results are surprising.

As I've got some values are `undefined` and if I do math with them it breaks Python.

I do remember I call for `safe*` family to extract such values from json but I don't remember I ever specifically checked if they are defined before doing a math. Still, I see these failures for the first time... Does it mean I haven't got them before by pure chance? Or there could be circumstances when Python just can do math with them?

**Comment by kroitor** [comment]
> Does it mean I haven't got them before by a pure chance?

Yep, seems like we've been lucky enough or didn't do math too complex to trigger an error.

> Or there could be circumstances when Python just can do math with them?

As far as I know, Python crashes on anything, which is a little annoying, however, in this particular case it's a proper indication of a problem indeed ) We can't rely on math with undefined values even in JS, or can we? )

**Comment by mkutny** [comment]
> We can't rely on math with undefined values even in JS, or can we? )

If math with `undefined` results in `undefined` this is actually what we can rely on.

So instead of verbose:
```javascript
let result = undefined
if (a is defined && b is defined)
    result = a + b
```

we can go with just `result = a + b`

**Comment by mkutny** [comment]
Anyway, I'll pay attention to that from now on.

**Comment by kroitor** [comment]
> If math with undefined results in undefined this is actually what we can rely on.

Yeah, I'd say that's a very outstanding feature of JS, as most other languages will disagree )

**Pull request merged**
