### PR TITLE
wex: fetchOpenOrders: work around exchange bug if we have no open orders

### PR DESCRIPTION
**Pull request by mkutny**
If we have no open orders then `wex` returns error:
```
wex POST https://wex.nz/tapi 
Request:
 { 'Content-Type': 'application/x-www-form-urlencoded',
  Key: 'XX-YY-ZZ',
  Sign: '0123asdf' } nonce=1510062887&method=ActiveOrders&pair=btc_usd
wex POST https://wex.nz/tapi 
Response:
{"success":0,"error":"no orders"}
```

Have no idea on how to integrate this workaround in a more organic way.

### CODE REVIEW

**Comment by kroitor** [comment]
I guess, we can actually put a try-catch inside the fetch\*Orders method and return []... That return would be consistent to what we expect from fetch\*Orders. Thx for your involvement, will merge it very soon!

**Comment by mkutny** [comment]
I knew there should have been a better way!
Will test and send an update shortly.

**Comment by kroitor** [comment]
@mkutny the only caveat there may be recognizing and distinguishing between a "no orders" error and all other errors. We may end up adding some kind of a hack or maybe, enhancing the transpiler so that it could handle that.

**Comment by mkutny** [comment]
Finally.
Not sure about transpilation errors, though.

**Comment by kroitor** [comment]
Awesome! Don't worry about the transpiler, I will edit it if needed. Thx!

**Pull request merged**
