### PR TITLE
fix(bybit) - fetchTickers subType

### PR DESCRIPTION
**Pull request by ttodua**
with exchange.options.defaultType='spot', the call `await e.fetchTickers (undefined, {subType:'linear'})` should be possible. atm, it would lead to `spot` request

### CODE REVIEW

**Comment by ttodua** [comment]
@carlosmiei this one too

**Comment by carlosmiei** [comment]
but the defaultType is swap here, so I don't think this is needed

**Comment by ttodua** [comment]
yes, but as said, people should be able to set `spot` for defaultType.

**Comment by ttodua** [comment]
not all traders/firms are trading contracts and some apps/clients might need `spot` as their preference

**Comment by ttodua** [comment]
what i mean, is as mentioned above, you should be able to call:
```
.fetchTickers ()
.fetchTickers (undefined, {subType:'linear'})
.fetchTickers (undefined, {subType:'inverse'})
```
to get spot, linear and inverse markets. at this moment, you cant with bybit

**Pull request merged**
