### PR TITLE
Documentation - fetchBalance

### PR DESCRIPTION
**Pull request by pcriadoperez**
Issue: https://github.com/ccxt/ccxt/issues/12140

- Docs example for fetchBalance.

The idea of this PR is to create a template for the documentation for all unified endpoints in the manual and those addressed in [this issue](https://github.com/ccxt/ccxt/issues/12140) using `fetchBalance` as an example.

### CODE REVIEW

**Comment by pcriadoperez** [comment]
Should use cross link reference instead

**Comment by samgermain** [comment]
@pcriadoperez Any reason you closed this?

**Comment by pcriadoperez** [comment]
@samgermain  Yes, I showed it to @kroitor  and he said we already have the description here (https://github.com/ccxt/ccxt/wiki/Manual#account-balance) and the structure here (https://github.com/ccxt/ccxt/wiki/Manual#balance-structure) So this would be repeating info that exists, and it's better to do a link to the existing documentation

**Comment by samgermain** [comment]
Reopened in https://github.com/ccxt/ccxt/pull/12220

**Pull request closed without merging**
