### PR TITLE
New Exchange: COSSDEX, https://dex.coss.io/

### PR DESCRIPTION
**Pull request by cossdex**
The centralized exchange of COSS has been implemented in ccxt, and the following is the implementation of the decentralized exchange of COSS.  
https://dex.coss.io/

### CODE REVIEW

**Comment by sglandsberg** [comment]
Is there any way to prioritize this addition? I'd like to start using it. Thanks.

**Comment by blaaaaaaa** [comment]
The centralized version of coss, https://coss.io/, even after more than 9 month after a alleged takeover still didn't give full access to users funds, this should be cleared up first I think.

**Review by jonhpham — APPROVED** [review]

**Comment by blaaaaaaa** [comment]
coss.io users did NOT get access to most of their funds after almost a year now.

**Comment by ttodua** [comment]
dead exchange

**Pull request closed without merging**
