### PR TITLE
bytetrade remove transfer and withdraw

### PR DESCRIPTION
**Pull request by frosty00**
these apis don't work anymore and they lead to getting the message ` {"code":1,"msg":"user is suspend"}` which is pretty much a dead account

apart from these apis and me getting $100 blocked by attempting to use them the exchange is still good to use (withdrawals via web still work)

### CODE REVIEW

**Comment by kroitor** [comment]
Hi, @leolianger, please check the above report. Is it related to a specific user or is it suspended for all users? Or is it related to KYC?

**Comment by frosty00** [comment]
@kroitor I'm 95% sure it is related to those apis

**Comment by frosty00** [comment]
The website is using a transfer api to withdraw so it looks like the withdraw operation is depreciated, plus it seems that it's a private blockchain so I can't just publish a transfer message without going through the api. It could also be because I'm using proxies. Anyway those functions don't work anymore.

**Comment by frosty00** [comment]
9529

**Comment by frosty00** [comment]
#10036

**Pull request closed without merging**
