### PR TITLE
fix the huobipro parseTrade cost precision issue

### PR DESCRIPTION
**Pull request by qinpeng2**
`cost = amount * price`
This line makes two float values do the multiple operation. It will lose precision for the computation result.

Let's say an example:
```
"info": {
    "symbol": "btcusdt",
    "price": "11230.94",
    "source": "spot-api",
    "filled-amount": "0.0025",
    ... ... 
}
```
The final ccxt my_trade cost result is float `(11230.94) * float(0.0025) = 28.077350000000003`.
Absolutely, the result is incorrect since the precision lost during the float multiply. It should be `28.07735`.

We should correct the cost value using the value-precision to make the cost value correct. 

Please kindly review the Pull Request and let me know if anything improper here.

### CODE REVIEW

**Comment by frosty00** [comment]
Hi @qinpeng2,

please take a look at https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md

in particular you need to make the edits to the js file since the python file is transpiled

thanks again for your participation!

**Comment by frosty00** [comment]
also for now this is not a change we are going to make, since we plan and adding an option for infinite precision in the future, just haven't got _round_ to it yet

**Comment by qinpeng2** [comment]
> also for now this is not a change we are going to make, since we plan and adding an option for infinite precision in the future, just haven't got _round_ to it yet

Thanks for the quick reply. 
BTW, do you have the exact release time for "adding an option for infinite precision"?

**Comment by frosty00** [comment]
>  BTW, do you have the exact release time for "adding an option for infinite precision"?

that is a good question, honestly we cannot tell you. we would have to add an option to `this.parseJson` that parses json as a `bignumber`/`decimal.Decimal`/whatever it is called in php.

**Pull request closed without merging**
