### PR TITLE
[dsx] added fetchTransactions, [kraken] added fetchOrdersByIds, [coinmate] added new markets, [binanceje] fixed trade fee

### PR DESCRIPTION
**Pull request by npomfret**

### CODE REVIEW

**Comment by npomfret** [comment]
@kroitor I don't understand the build error here:

```
ERROR: could not install deps [.[qa]]; v = InvocationError('C:\\projects\\ccxt\\python\\.tox\\qa\\Scripts\\python.EXE -m pip install .[qa] (see C:\\projects\\ccxt\\python\\.tox\\qa\\log\\qa-1.log)', 1)
510___________________________________ summary ___________________________________
511ERROR:   qa: could not install deps [.[qa]]; v = InvocationError('C:\\projects\\ccxt\\python\\.tox\\qa\\Scripts\\python.EXE -m pip install .[qa] (see C:\\projects\\ccxt\\python\\.tox\\qa\\log\\qa-1.log)', 1)

```
Can you advise?

**Comment by kroitor** [comment]
@npomfret it's a bug with appveyor versioning, so, no worries, can be safely ignored, it isn't an obstacle for a merge.

**Comment by npomfret** [comment]
Hi @kroitor - any chance of getting this merged?  Is there anything you need me to do?

**Comment by kroitor** [comment]
@npomfret hi! Good to hear from you! 

> any chance of getting this merged? 

Sorry for the delays, will get cracking, hope to merge it in a few days.

> Is there anything you need me to do?

I don't think so, but will let you know if anything. Thx again for the patience and for your help!

**Pull request merged**
