### PR TITLE
bibox add an error

### PR DESCRIPTION
**Pull request by frosty00**

### CODE REVIEW

**Comment by frosty00** [comment]
sorry ill git reset --hard and force push one sec

**Comment by frosty00** [comment]
https://github.com/frosty00/ccxt/blob/bibox-fees-2/js/bibox.js

Github not updating. Can you copy and paste and merge this file. Obviously check that the changes are correct using git diff and merge to master.

**Comment by kroitor** [comment]
@frosty00 will do shortly, no worries, and thx)

**Comment by kroitor** [comment]
Oh, now I see you new PR, will merge it in a sec )

**Pull request closed without merging**
