### PR TITLE
 bitfinex: withdrawal fees are now account-specific & handleErrors

### PR DESCRIPTION
**Pull request by mkutny**
1. `fetchFundingFees ()`

It would be handy to mount them somewhere, although now sure where exactly.
One candidate would be `fetchMarkets` although funding fees do not belong to markets.
Another candidate would be `describe` although one would not expect network access for exchange instantiation.
Do you have a recommendation on this?

2. `handleErrors ()`

I split `.exceptions` on two maps: `exact` and `broad` matches. Not sure if it makes sense, actually. It won't give any performance boost (until we have thousands of keys). Nothing more than semantical clarity.

Still, I think `findBroadlyMatchedKey ()` might be a part of the core, we'll use it frequently.

### CODE REVIEW

**Comment by mkutny** [comment]
That's strange, have no idea if it's possible to debug it while node session is open.

```
> const ccxt = require('./ccxt')
> const bfx = new ccxt['bitfinex']()
> bfx.loadMarkets()
// left session opened for few minutes
(node:76185) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 Runtime.executionContextCreated listeners added. Use emitter.setMaxListeners() to increase limit
(node:76185) UnhandledPromiseRejectionWarning: Error: bitfinex {"error":"ERR_RATE_LIMIT"}
    at bitfinex.handleErrors (/Users/max/src/ccxt/js/bitfinex.js:739:27)
    at response.text.then.responseBody (/Users/max/src/ccxt/js/base/Exchange.js:456:18)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)
```

**Comment by mkutny** [comment]
Ok... Narrowed it down. NVM.

**Comment by frosty00** [comment]
LOL I literally just made the exact same pull request. https://github.com/ccxt/ccxt/pull/1671

But who will get merged first... ? ?
---

Btw the unified API is fetchFees not fetchFundingFees.

**Comment by mkutny** [comment]
> LOL I literally just made the exact same pull request. #1671

That's cool! If I knew this I wouldn't make mine.

> But who will get merged first... ? ?

I don't mind if yours ) Just make sure it passes the buld )

> Btw the unified API is `fetchFees` not `fetchFundingFees`.

I didn't know that, honestly. Don't see it in the Manual too. Still, would be happy to have such method a part of unified API (and be sure than to update `.has` property).

At the same time, some exchanges may provide only trading fees, some only funding fees, so I'd go on with three methods: `fetchFees`, `fetchTradingFees`, `fetchFundingFees`.

**Comment by kroitor** [comment]
@frosty00 

> But who will get merged first... ? ?

Let's see... well, none of them )))

Just kidding, I think I'm going to merge both. One request from frosty and one from mkutny together make it a frutny, I guess )

@mkutny 

> Do you have a recommendation on this?

In general, our process goes like this: if we can fetch them from the API – then we check corresponding endpoints. Trading fees usually go into fetchMarkets, funding fees usually go into fetchCurrencies, if those are public. However, this is not always the case, and sometimes fees are available from a balance call, or from a separate endpoints on fees (like with Poloniex, Bitfinex and a few others). Sometimes fees depend on keys and should go into a separate method or into a family of `fetchFees/fetchFundingFees/fetchTradingFees()` methods. If there is no way to scrape them anyhow, then we hardcode them in `describe ()`.

**Comment by mkutny** [comment]
> One request from frosty and one from mkutny together make it a frutny

Oh, you made my day )))

> If there is no way to scrape them anyhow, then we hardcode them in describe ()

I didn't mean static fees. Ok, I'll ask from the different perspective.

Our users (and me) used to do the following mantra before actually start trading (excerpt from the Manual):
```
let kraken = new ccxt.kraken ()
let markets = await kraken.loadMarkets ()
```

So we used to have **everything** populated/instantiated after `loadMarkets ()` call. Now it seems to be changing: some additional info gets loaded by `fetchCurrencies()` or `fetchFees/fetchFundingFees/fetchTradingFees()`. So the question is: what's the unified approach to instantiate an exchange from now on?

**Comment by frosty00** [comment]
I propose we try to unify to the fees as such:

Each exchange inherits a fetchFees method from the base exchange class —> which will try to pull data from markets and currencies and returns withdraw, deposit, maker, taker and info (any other exchange specific data). Instead of having a family of methods I suggest we have just one which returns undefined or None in the occasion that an exchange doesn’t specify them.

I am currently in the process of coding a method called ‘loadFees’, which will call ‘fetchFees’ and attempt to populate the fees attribute of each exchange. ‘.fees’ will contain a boolean called loaded which can be used to distinguish between hardcoded and loaded fees. I think it is necessary to call this from loadMarkets since fees are just as essential as markets and currencies IMO. 

However, it would be fairly trivial to cache the network request in a similar fashion to how loadMarkets can take the reload argument. My only issue atm is that it is hard to distinguish between loaded and hardcoded fees since loadMarkets (and some fetchMarkets) populate the market data with the hardcoded fees. 

I do not think fetchFees should raise an error if no apiKey is provided so it would have to be caught and ignored. Anyway I will work on the Python implentation and @kroitor can decide whether to add it to the unified methods.

**Comment by kroitor** [comment]
@mkutny, @frosty00 wanted to clarify on fees: because not all applications actually require fee info, the library does not require that from the user either. In other words, we do require to load markets and currencies, as most of the time this is necessary in any application, however, we don't load something that is not absolutely necessary in all applications. Some users report of use-cases in short-living web responses, so they instantiate an instance upon generating a web page for their users, and we can't force them to always load fees. For trading applications we load them manually for now. Maybe we should think of adding some kind of *extended* instantiation flag for that...

**Comment by mkutny** [comment]
@kroitor , I'm ok if funding fees are loaded separately. No need for extended flag too, no problem instead of familiar:
```javascript
const exchange = new ccxt['exchange'] ()
await exchange.loadMarkets () // loads markets and trading fees
```
switch to:
```javascript
const exchange = new ccxt['exchange'] ()
await exchange.loadMarkets () // loads markets and trading fees
await exchange.loadFundingFees () // optional
```

I'm still confused by `fetchCurrencies` (it's been recently added and not yet in the Manual) and `fetchFees` (as I understand this is being added right now). I can update the Manual if you help me to clarify few points:
- do I ever need to call `fetchCurrencies` explicitly or this is for internal purpose (to be called by `loadMarkets`?
- every currency has `limits.[amount|price|cost]` property - how it correlates with properties of markets?
- can I count that once I call `loadMarkets` I have trading fees available or this exchange-dependent? 
- if trading fees are loaded by `loadMarkets` do we really need `fetchFees` or having `fetchFundingFees` is enough?

**Comment by kroitor** [comment]
> - do I ever need to call `fetchCurrencies` explicitly or this is for internal purpose (to be called by `loadMarkets`?

No, you don't have to call it explicitly, as it is called by loadMarkets (where defined on the exchange). However, not all of them have that method defined and not all of them have an endpoint for currencies at all, so we fallback to rebuilding currencies from markets – those are required for proper work of funding methods that have their goal to unify the currency codes as well. So, all of that is done for unification purposes mostly.

> - every currency has `limits.[amount|price|cost]` property - how it correlates with properties of markets?

That's an interesting aspect, most often, this info is unavailable from the exchange itself... However, sometimes it is. When you have some property, like `limits`, you just need to examine what it applies to. If it's market, those are trading limits. If it's a currency – those are funding (?) limits. It's still an open work. So, we think, the fee logic can also be done like that. So, currencies is all about funding. Markets is all about trading.

> - can I count that once I call `loadMarkets` I have trading fees available or this exchange-dependent? 

We would love to have trading fees available after loadMarkets, and the goal is to make it so. But some exchanges won't serve any fees from public APIs and will only serve them from private endpoints. So it will always be a compromise solution up to a certain point.

> - if trading fees are loaded by `loadMarkets` do we really need `fetchFees` or having `fetchFundingFees` is enough?

Yep, because of the above, we may have funding and trading fees served from separate private endpoints. And because of that we actually might reconsider the entire loadFees() approach... Basically, it's a problem of a *"chicken or an egg first"* type. From one point of view, the trading fees are not a property of the exchange at all, they are the property of a trading market. 

The same is true for funding fees – those are properties of particular assets, not the entire exchange. Logic kinda tells us that the cleanest possible way to implement this is not lifting the fees up to the exchange instance, keeping them where they belong. And I like this thinking best (sounds *robust* to me). 

However, for convenience, and I agree with @frosty00 here, we might still want to lift the `fees` up to the exchange instance, and from here we now have to decide on the propagation codeflow for that data.

**Comment by frosty00** [comment]
@mkutny [this](https://github.com/ccxt/ccxt/pull/1706) is what I had in mind yesterday. There are already a lot of exchanges which have a fetchFees method, but not all of them. How the base class loadFees would work is:

    .currencies['fee'] --> .fees['funding']
    .markets['taker'] && .markets['maker'] --> .fees['trading']

I'm coding an arbitrage bot so fees are an essential calculation. However the current fee related methods - calculateFee and fetchFees (sometimes) have their downsides. calulateFee requires you to know in advance whether your order will be a taker or maker (since they are often different rates), yet it is impossible to know the state of the trading engine a the exact moment before an order is submitted. My plan was to get the all the fees together into .fees so I could calculate the total fee concisely in one function and use `max(taker, maker)` as the trading fee.

> Yep, because of the above, we may have funding and trading fees served from separate private endpoints. And because of that we actually might reconsider the entire loadFees() approach... 

We could load fees from markets and currencies pretty easily seeing as this would not require a network request and this could be put into setMarkets. Thus the order would go something like this (arrows going to a function mean it is getting called by the one on the left):

    setMarkets() --> populateFeesFromCurrenciesAndMarkets()
    populateFeesFromNonstandardEndpoint() --> fetchFees() // seperate call by user

The naming is subject to change. 

> if trading fees are loaded by loadMarkets do we really need fetchFees or having fetchFundingFees is enough?

My issue is that they are not really loaded, but rather taken coded in the script itself. In a *perfect* world we should not rely on hardcoded fees at all, and I do not like how hardcoded fees are injected into the markets property. I think there should be at least some attempt to check if fees can be loaded before doing so.

**Comment by mkutny** [comment]
@kroitor , ok, it's clear what you say and it leads to the natural question.

On the one hand "currencies are all about funding". On the other hand, `fetchCurenncies` do not provide funding fees. I'd say it's a bit counter-intuitive but I understand technical limitations behind that and, well, we don't expose `fetchCurrencies` to users anyway so they won't be confused.

Still, the question is: what I, as a library user, should call to get funding fees in a unified manner? Should it be something like `loadFundingFees`? I understand that it's in flux now, that's all right. But what's the design goal?

> So, currencies are all about funding. Markets are all about trading.

I love this statement and completely support such separation.

Well, what if we have `loadMarkets`/`loadCurrencies` pair? I understand that right now `fetchCurrencies` is called by `loadMarkets` but, hey, they are not needed for trading, right? We lived without them happily all this time.

**Comment by kroitor** [comment]
> I love this statement and completely support such separation.

Yeah, I like it too, however, there's an oversimplification in it, let me explain...

> Well, what if we have loadMarkets/loadCurrencies pair? I understand that right now fetchCurrencies is called by loadMarkets but, hey, they are not needed for trading, right? 

Wrrrrright, but not exactly... )) You see, currencies are also used for balance parsing, especially when it comes to unifying currency codes ←→ ids across exchanges. And now we have direct references between a market and two currencies on your balance, that means, both currencies and markets are needed for trading, and for funding, we probably need just the currencies.

Also, there's another logical obstacle for pure separation of concerns: many exchanges don't serve them at all, and the only way to obtain them is to build them from markets. So, why loading them markets twice, right? No need to have fetchMarkets and fetchCurrencies calling the same endpoint, moreover, no need to do that twice in these circumstances... This obstacle can be tackled in a multitude of ways, starting from an off-application 3rd-party http cache, up to building that cache on the app-level, like we did in the lib (with the `reload` flag). But anyways, the actual caching layer is not a problem here, it does work even in its current rudimentary state. The problem is to come up with a proper design, hitting the internet as rarely as possible...

> We lived without them happily all this time.

This is just because we tried to do the calls on behalf of the library, so they weren't exposed, but they have been there for a few months now )

Naturally, we should think of what is a market and what is a currency, or an asset. And it turns out, that a market consists of two assets that are posed and weighed against each other. So, in an ideal world, we would make a `currency` class and would make a `market` class with `base` and `quote` properties that would reference corresponding instances of currency class. However, with some exchanges we were caught by surprise, when we found out that currency precision for withdrawals may not be the same as currency precision on a base or a quote side of the market for the same asset. This means, we can't really reference them directly. Moreover, the goal of the library itself is to be JSON-flat (read, *"easy"*)...

So, it turns out that whatever way we look at it, it would still be some sort of a compromise...

`loadMarkets()` (should be renamed to load() or something, with flags telling what to load)
1. if `has['fetchCurrencies']` loadCurrencies () (otherwise take hardcoded ones?)
2. if `has['fetchMarkets']` loadMarkets () (otherwise take hardcoded ones?)
3. if `currencies` are not present yet – restore them from markets
4. if `has['fetchFees']` loadFees () – split into funding/trading here
5. if `fees` are not present yet – restore them from markets and currencies
6. ...

**Comment by mkutny** [comment]
> any of the above should be accessible for calling as a standalone action: loadMarkets, loadCurrencies, loadFees, loadFundingFees, loadTradingFees...

I totally agree. If we have these bricks we'll be able to construct `load ()` for every purpose from them.

What I also like about this approach is that it allows us to reap benefits from new methods already. And in the process of using them, we'll come up with a better understanding of how that universal `load ()` should behave.

So, getting back to the original issue. May I expect that `fetchTradingFees` be a part of universal API?

**Comment by kroitor** [comment]
> May I expect that fetchTradingFees be a part of universal API?

Sure, but, as you now understand, we only have it implemented for Bitfinex for now )

**Comment by mkutny** [comment]
@kroitor That's absolutely fine, all I wanted to know where are we heading even if it's the first step.

But, you know, I'm looking at what I've written and just can't believe I made this stupid mistake. I wanted to ask about `fetchFundingFees`, actually )

**Comment by mkutny** [comment]
But as they all belong to the same breed I hope you'll be ok with this method too )

**Pull request merged**
