### PR TITLE
digifinex - fetchCurrencies

### LINKED ISSUE #15052: digifinex currencies not correct
OS: Windows 11
Programming Language version: PYTHON 3.10.5
CCXT version: "ccxt/ccxt": "^1.93.59",
Exchange: digifinex
Method: load_markets - currencies

hi . 
my code :
connection.load_markets()
markets = connection.currencies
print(markets)

output :
{'USDT': {'id': 'USDT', 'code': 'USDT', 'info': [{'deposit_status': '0', 'min_withdraw_fee': '5', 'withdraw_fee_currency': 'USDT', 'chain': 'OMNI', 'withdraw_fee_rate': '0', 'min_withdraw_amount': '10', 'currency': 'USDT', 'withdraw_status': '0', 'min_deposit_amount': '10'}, {'deposit_status': '1', 'min_withdraw_fee': '15', 'withdraw_fee_currency': 'USDT', 'chain': 'ERC20', 'withdraw_fee_rate': '0', 'min_withdraw_amount': '10', 'currency': 'USDT', 'withdraw_status': '1', 'min_deposit_amount': '10'}, {'deposit_status': '1', 'min_withdraw_fee': '1', 'withdraw_fee_currency': 'USDT', 'chain': 'TRC20', 'withdraw_fee_rate': '0', 'min_withdraw_amount': '10', 'currency': 'USDT', 'withdraw_status': '1', 'min_deposit_amount': '10'}, {'deposit_status': '1', 'min_withdraw_fee': '1', 'withdraw_fee_currency': 'USDT', 'chain': 'BEP20', 'withdraw_fee_rate': '0', 'min_withdraw_amount': '10', 'currency': 'USDT', 'withdraw_status': '1', 'min_deposit_amount': '10'}, {'deposit_status': '1', 'min_withdraw_fee': '2', 'withdraw_fee_currency': 'USDT', 'chain': 'Polygon', 'withdraw_fee_rate': '0', 'min_withdraw_amount': '10', 'currency': 'USDT', 'withdraw_status': '1', 'min_deposit_amount': '10'}], 'type': None, 'name': None, **'active': False, 'deposit': False, 'withdraw': False,** 'fee': 0.0, 'precision': 1e-08, 'limits': {'amount': {'min': None, 'max': None}, 'withdraw': {'min': 10.0, 'max': None}}}, 'USDC': {'id': 'USDC', 'code': 'USDC', ...

in this output usdt withdraw = False but in website usdt withdraw is enable.

### PR DESCRIPTION
**Pull request by pcriadoperez**
fix #15052

- Add networks to currency structure
- Sets withdraw and deposit to true if allowed on any of the networks instead of just checking the first network
- Add deposit limits to currency structure

### CODE REVIEW

**Comment by hosseinab** [comment]
@carlosmiei please check this request

**Comment by carlosmiei** [comment]
LGTM ✅ 
```
 'USDT': {'active': True,
          'code': 'USDT',
          'deposit': True,
          'fee': 0.0,
          'id': 'USDT',
          'info': [{'chain': 'OMNI',
                    'currency': 'USDT',
                    'deposit_status': '0',
                    'min_deposit_amount': '10',
                    'min_withdraw_amount': '10',
                    'min_withdraw_fee': '5',
                    'withdraw_fee_currency': 'USDT',
                    'withdraw_fee_rate': '0',
                    'withdraw_status': '0'},
                   {'chain': 'ERC20',
                    'currency': 'USDT',
                    'deposit_status': '1',
                    'min_deposit_amount': '10',
                    'min_withdraw_amount': '10',
                    'min_withdraw_fee': '5',
                    'withdraw_fee_currency': 'USDT',
                    'withdraw_fee_rate': '0',
                    'withdraw_status': '1'},
                   {'chain': 'TRC20',
                    'currency': 'USDT',
                    'deposit_status': '1',
                    'min_deposit_amount': '10',
                    'min_withdraw_amount': '10',
                    'min_withdraw_fee': '1',
                    'withdraw_fee_currency': 'USDT',
                    'withdraw_fee_rate': '0',
                    'withdraw_status': '1'},
                   {'chain': 'BEP20',
                    'currency': 'USDT',
                    'deposit_status': '1',
                    'min_deposit_amount': '10',
                    'min_withdraw_amount': '10',
                    'min_withdraw_fee': '1',
                    'withdraw_fee_currency': 'USDT',
                    'withdraw_fee_rate': '0',
                    'withdraw_status': '1'},
                   {'chain': 'Polygon',
                    'currency': 'USDT',
                    'deposit_status': '1',
                    'min_deposit_amount': '10',
                    'min_withdraw_amount': '10',
                    'min_withdraw_fee': '2',
                    'withdraw_fee_currency': 'USDT',
                    'withdraw_fee_rate': '0',
                    'withdraw_status': '1'}],
          'limits': {'amount': {'max': None, 'min': None},
                     'deposit': {'max': None, 'min': 10.0},
                     'withdraw': {'max': None, 'min': 10.0}},
          'name': None,
          'networks': {'BEP20': {'active': True,
                                 'deposit': True,
                                 'fee': 0.0,
                                 'id': 'BEP20',
                                 'info': {'chain': 'BEP20',
                                          'currency': 'USDT',
                                          'deposit_status': '1',
                                          'min_deposit_amount': '10',
                                          'min_withdraw_amount': '10',
                                          'min_withdraw_fee': '1',
                                          'withdraw_fee_currency': 'USDT',
                                          'withdraw_fee_rate': '0',
                                          'withdraw_status': '1'},
                                 'limits': {'amount': {'max': None,
                                                       'min': None},
                                            'deposit': {'max': None,
                                                        'min': 10.0},
                                            'withdraw': {'max': None,
                                                         'min': 10.0}},
                                 'name': None,
                                 'network': 'BEP20',
                                 'precision': 1e-08,
                                 'withdraw': True},
                       'ERC20': {'active': True,
                                 'deposit': True,
                                 'fee': 0.0,
                                 'id': 'ERC20',
                                 'info': {'chain': 'ERC20',
                                          'currency': 'USDT',
                                          'deposit_status': '1',
                                          'min_deposit_amount': '10',
                                          'min_withdraw_amount': '10',
                                          'min_withdraw_fee': '5',
                                          'withdraw_fee_currency': 'USDT',
                                          'withdraw_fee_rate': '0',
                                          'withdraw_status': '1'},
                                 'limits': {'amount': {'max': None,
                                                       'min': None},
                                            'deposit': {'max': None,
                                                        'min': 10.0},
                                            'withdraw': {'max': None,
                                                         'min': 10.0}},
                                 'name': None,
                                 'network': 'ERC20',
                                 'precision': 1e-08,
                                 'withdraw': True},
                       'OMNI': {'active': False,
                                'deposit': False,
                                'fee': 0.0,
                                'id': 'OMNI',
                                'info': {'chain': 'OMNI',
                                         'currency': 'USDT',
                                         'deposit_status': '0',
                                         'min_deposit_amount': '10',
                                         'min_withdraw_amount': '10',
                                         'min_withdraw_fee': '5',
                                         'withdraw_fee_currency': 'USDT',
                                         'withdraw_fee_rate': '0',
                                         'withdraw_status': '0'},
                                'limits': {'amount': {'max': None, 'min': None},
                                           'deposit': {'max': None,
                                                       'min': 10.0},
                                           'withdraw': {'max': None,
                                                        'min': 10.0}},
                                'name': None,
                                'network': 'OMNI',
                                'precision': 1e-08,
                                'withdraw': False},
                       'Polygon': {'active': True,
                                   'deposit': True,
                                   'fee': 0.0,
                                   'id': 'Polygon',
                                   'info': {'chain': 'Polygon',
                                            'currency': 'USDT',
                                            'deposit_status': '1',
                                            'min_deposit_amount': '10',
                                            'min_withdraw_amount': '10',
                                            'min_withdraw_fee': '2',
                                            'withdraw_fee_currency': 'USDT',
                                            'withdraw_fee_rate': '0',
                                            'withdraw_status': '1'},
                                   'limits': {'amount': {'max': None,
                                                         'min': None},
                                              'deposit': {'max': None,
                                                          'min': 10.0},
                                              'withdraw': {'max': None,
                                                           'min': 10.0}},
                                   'name': None,
                                   'network': 'POLYGON',
                                   'precision': 1e-08,
                                   'withdraw': True},
                       'TRC20': {'active': True,
                                 'deposit': True,
                                 'fee': 0.0,
                                 'id': 'TRC20',
                                 'info': {'chain': 'TRC20',
                                          'currency': 'USDT',
                                          'deposit_status': '1',
                                          'min_deposit_amount': '10',
                                          'min_withdraw_amount': '10',
                                          'min_withdraw_fee': '1',
                                          'withdraw_fee_currency': 'USDT',
                                          'withdraw_fee_rate': '0',
                                          'withdraw_status': '1'},
                                 'limits': {'amount': {'max': None,
                                                       'min': None},
                                            'deposit': {'max': None,
                                                        'min': 10.0},
                                            'withdraw': {'max': None,
                                                         'min': 10.0}},
                                 'name': None,
                                 'network': 'TRC20',
                                 'precision': 1e-08,
                                 'withdraw': True}},
          'precision': 1e-08,
          'type': None,
          'withdraw': True}
```

**Review by carlosmiei — APPROVED** [review]

**Comment by hosseinab** [comment]
@carlosmiei @kroitor @pcriadoperez  
thanks . fee in networks always zero ( 0 )

**Comment by pcriadoperez** [comment]
> @carlosmiei @kroitor @pcriadoperez thanks . fee in networks always zero ( 0 )

So the thing is that digifinex provides two fees, the minimum fee and the withdraw fee rate. Currently we are use the `withdraw_fee_rate` to populate the fee. Acording to digifinex:
 `if the actual fee is less than the minimum fee, it will be charged according to minimum fee; Otherwise, it will be charged according to the actual fee`
 @carlosmiei Given that all the `withdraw_fee_rate` of digifinex is always 0, and acording to ccxt docs we return a flat fee in the network structure, should I change the fee to be equal to the `min_withdraw_fee`?

**Comment by carlosmiei** [comment]
@pcriadoperez hum I'd say so, regarding fees we should probably always return the "worst-case scenario"

**Comment by pcriadoperez** [comment]
Opened a PR here for the change: https://github.com/ccxt/ccxt/pull/15215

**Pull request merged**
