### PR TITLE
new exchange: btcalpha

### PR DESCRIPTION
**Pull request by Deathamns**
#1285

### CODE REVIEW

**Comment by osnwt** [comment]
Thank you. But it should be tested a bit more, I think. Just some of issues:

1. Shouldn't exchange list include btcalpha? It doesn't.
2. fetchOpenOrders(): Error: btcalpha Wrong signature (keys work for non-ccxt code).
3. fetchTrades('VIC/BTC') works, but fetchTrades() doesn't.
4. fetchMyTrades('VIC/BTC'): this.privateGetTrades is not a function

**Comment by kroitor** [comment]
@osnwt thanks for testing!

On your comments:

1. Yep, but the exchange list itself gets updated automatically upon merging, so, @Deathamns did it properly.
2. can you please post your verbose output?
3. fetchTrades is not designed to work without a symbol, unfortunately, the argument is mandatory.
4. The entire fetchMyTrades is a copypaste from some other exchange, as this particular one does not offer an endpoint for trade history, if I get it correctly from looking at their `['api']`

**Comment by osnwt** [comment]
> 1. exchange list itself gets updated automatically upon merging

Ok, I was not sure, so asked.

> 2. fetchOpenOrders(): Error: btcalpha Wrong signature (keys work for non-ccxt code).

It does something wrong with parameters. It's GET request for private fetchOpenOrders, so params 
should be in the request string, not in a form. BtcAlpha uses some mix of POST and GET requests for similar calls (POST for creating orders, but GET for reading existing ones). And it also does NOT include nonce in a signature that makes it almost useless (allows replay attack for such requests).

My code works:
```
GET /api/v1/orders/own/?limit=2 HTTP/1.1
X-KEY: 677726f9...
X-SIGN: 175360bbe...
X-NONCE: 1518411155215
accept-encoding: gzip, deflate
referer: https://btc-alpha.com/api/v1/orders/own?limit=2
host: btc-alpha.com

[ { id: 14175345,
    type: 'buy',
    pair: 'VIC_BTC',
    price: '0.00002065',
    amount: '1.52445521',
    status: 1 },
  { id: 14140319,
    type: 'sell',
    pair: 'VIC_BTC',
    price: '0.00002634',
    amount: '0.00000000',
    status: 3 } ]
```

ccxt code doesn't:
```
handleRestResponse:
 btcalpha GET https://btc-alpha.com/api/v1/orders/own/ 400 Bad Request 
Response:
 { Accept: 'application/json',
  'Content-Type': 'application/x-www-form-urlencoded',
  'X-KEY': '677726f9...',
  'X-SIGN': '6b4f3bce...',
  'X-NONCE': 1518411227917 } 
 {"detail":"Wrong signature"} 
```

> 3.  fetchTrades is not designed to work without a symbol, unfortunately, the argument is mandatory.

```
GET /api/v1/exchanges/?limit=2 HTTP/1.1
accept-encoding: gzip, deflate
referer: https://btc-alpha.com/api/v1/exchanges?limit=2
host: btc-alpha.com
Connection: close

[ { id: 8330035,
    timestamp: 1518409540.781663,
    pair: 'UCASH_BTC',
    price: '0.00001510',
    amount: '68.85858134',
    type: 'sell' },
  { id: 8330034,
    timestamp: 1518409538.894172,
    pair: 'R7_ETH',
    price: '0.00005600',
    amount: '22.60000000',
    type: 'buy' } ]
```

> The entire fetchMyTrades is a copypaste from some other exchange, as this particular one does not offer an endpoint for trade history, if I get it correctly from looking at their ['api']

Same story as with Cryptopia...

```
GET /api/v1/exchanges/own/?limit=2 HTTP/1.1
accept-encoding: gzip, deflate
referer: https://btc-alpha.com/api/v1/exchanges/own?limit=2
host: btc-alpha.com
Connection: close

{ detail: 'Authentication credentials were not provided.' }

---

GET /api/v1/exchanges/own/?limit=2 HTTP/1.1
X-KEY: 677726f9...
X-SIGN: 175360bb...
X-NONCE: 1518409593265
accept-encoding: gzip, deflate
referer: https://btc-alpha.com/api/v1/exchanges/own?limit=2
host: btc-alpha.com
Connection: close

[ { id: 8321351,
    timestamp: 1518395447.026193,
    pair: 'VIC_BTC',
    price: '0.00002634',
    amount: '1.19760000',
    type: 'buy' },
  { id: 8313065,
    timestamp: 1518384907.489594,
    pair: 'VIC_BTC',
    price: '0.00002065',
    amount: '1.20000000',
    type: 'sell' } ]
```

**Comment by Deathamns** [comment]
2) Signing was incorrect, copy-paste artifacts... But I'm still not sure if it works now, I haven't tested it.
3) Updated. (However I'm not sure if I should allow this behavior @kroitor?)
4) Updated.
5) Maybe you've created a maker buy order, but someone created a taker sell order, which the trade shows. `fetchMyTrades` seem to be showing the same types as the website.

**Comment by osnwt** [comment]
Tested, here are results:

3. FIXED
fetchTrades() - OK
fetchTrades('VIC/BTC') - OK
fetchTrades(undefined, undefined, 2) - OK
fetchTrades('VIC/BTC', undefined, 2) - OK

4. Not OK:
fetchMyTrades() - OK
fetchMyTrades('VIC/BTC') - Wrong signature
fetchMyTrades(undefined, undefined, 2) - Wrong signature

The signature you calculate is different for all 3 requests. Actually it must be the same since parameters are sent via GET, but signature calculated using form variables. Since no changes in the form data (no form data), signature must be the same as for GET with no arguments. Then it works.

**Comment by osnwt** [comment]
5. Still the exchange reports wrong order types and for me they are DIFFERENT from what the website provides:

btcalpha

**Comment by Deathamns** [comment]
> it's stupid they do not sign GET data at all

Aha.

**Comment by osnwt** [comment]
4. FIXED
fetchMyTrades() - OK
fetchMyTrades('VIC/BTC') - OK
fetchMyTrades(undefined, undefined, 2) - OK

So only (5) buy/sell should be checked and probably fixed (by checking other exchanges). It's btcalpha's issue, not API. But if they provide swapped sides, it should be fixed here.

And thank you for the API!

**Comment by osnwt** [comment]
Just checked if ccxt/btcalpha work for my bot that checks and reports own trades. It was tested for cryptopia, now I only changed to btcalpha, and it works! Also the side was reported correctly. I did not compare with other exchanges on the lower level, but at least it's reported consistently (like it did for cryptopia).

btcalpha2

So I'd like it to be merged when possible. Good work, guys!

**Comment by Deathamns** [comment]
@osnwt Have you tested the other private APIs as well? If yes, do they work correctly?

**Comment by osnwt** [comment]
Not yet (only partially).

**Pull request merged**
