### PR TITLE
Fix market buy order amount issue for huobipro

### PR DESCRIPTION
**Pull request by qinpeng2**
I occurred this issue on the XRP/BTC symbol.
The min-order-value is 0.0001 which means the min market buy order accepted amount is 0.0001. 

But when I tried to create a market buy order with placing 0.0001 BTC, it returned this error "Paramemter `amount` is invalid.". 
It doesn't make sense, so I create another market buy order with placing 0.01 BTC on symbol XRP/BTC again. Still the same error. 

After checked the ccxt source, I found it always use the amount_to_precision() to adjust the request parameter `amount`.
It's incorrect for the market buy order case. It should be value_to_precision() here.

Please kindly review the Pull Request.

### CODE REVIEW

**Comment by kroitor** [comment]
Hi @qinpeng2 ! Thx for your involvement! Can you please move these edits to the source `.js` file? 

- https://github.com/ccxt/ccxt/pull/6013/files#diff-e4ce62a9f75b52d58624d6d5fdd59baaR3
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#multilanguage-support
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

**Comment by qinpeng2** [comment]
> Hi @qinpeng2 ! Thx for your involvement! Can you please move these edits to the source `.js` file?
> 
> * https://github.com/ccxt/ccxt/pull/6013/files#diff-e4ce62a9f75b52d58624d6d5fdd59baaR3
> * https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#multilanguage-support
> * https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

Sure!
I'll let you know when I'm done.

**Comment by kroitor** [comment]
@qinpeng2 check out the comments here: 

- https://github.com/ccxt/ccxt/pull/6013/files#diff-3147d8f981a48fe7a4ca528093501811R809

We don't really have a method called `valueToPrecision`, and this should be handled in the section linked above. So, it appears that you're trying to add something that is already there a few lines below. Or am I missing something?

**Comment by kroitor** [comment]
@qinpeng2 it would be great to get a comment from you on this:  https://github.com/ccxt/ccxt/pull/6013/files#diff-3147d8f981a48fe7a4ca528093501811R899. It looks like you're trying to do what's already done, no?

**Comment by qinpeng2** [comment]
> @qinpeng2 it would be great to get a comment from you on this: https://github.com/ccxt/ccxt/pull/6013/files#diff-3147d8f981a48fe7a4ca528093501811R899. It looks like you're trying to do what's already done, no?

@kroitor I reviewed the final change you did. 
Yes, it exactly matches what I supposed to do. All things work for me now.

Actually I did almost the same change in my local branch before the final change based on our discussion. As the screenshot below->


Thanks for your effort on this ticket. Cheers!~

**Comment by kroitor** [comment]
@qinpeng2 thx for your participation and for the feedback! )

**Pull request merged**
