### PR TITLE
Bump aiohttp from 3.6.2 to 3.6.3

### PR DESCRIPTION
**Pull request by THETCR**

### CODE REVIEW

**Comment by xmatthias** [comment]
I would argue that dependencies in `setup.py` should not be pinned to fixed versions at all [source](https://packaging.python.org/discussions/install-requires-vs-requirements/).

Requirement files should be used if pinned dependencies are necessary - `setup.py` should only specify min (and eventual max) versions of a dependency (see link)

This is especially problematic for libraries like ccxt - where a hard-pinned requirement like this can block all dependent packages from updating (or in the case of this PR - will force all dependent packages to update).

If they don't, then all other python packages are forced to upgrade aiohttp (if it's specified as explicit dependency) - otherwise they will encounter a `ContextualVersionConflict ` error when executing.

I don't think ccxt depends on exactly "this" version (neither 3.6.2, nor 3.6.3) - most likely, any version > 3.x will work for ccxt, and `setup.py` should reflect that.
obviously only @kroitor  can say for sure why dependencies are hard-pinned in setup.py...

**Comment by kroitor** [comment]
There's a specific reason for pinning the deps of this project. Most of packages like aiohttp will use a ton of other dependencies. This is lib is used to manage the users' funds (in the millions). So, if a forward-dep is broken or hacked and is injected with malicious code, then a rogue 3rd-party dep can update its code later and then try and do some financial damage to the user. That's the only reason for pinning those versions – even if that does not protect the user for 100%, it is still better than nothing.

> Requirement files should be used if pinned dependencies are necessary - setup.py should only specify min (and eventual max) versions of a dependency (see link)

In this case, the question is whether to pin them or not, regardless of where we pin them (either in requirements.txt or in setup.py).

> This is especially problematic for libraries like ccxt - where a hard-pinned requirement like this can block all dependent packages from updating (or in the case of this PR - will force all dependent packages to update).
> If they don't, then all other python packages are forced to upgrade aiohttp (if it's specified as explicit dependency) - otherwise they will encounter a ContextualVersionConflict error when executing.

We are aware of the above problem, and we're trying to mitigate that by stripping and moving all the deps inside CCXT's codebase (aka _"vendoring"_ them).

If you can suggest a better approach to solving the above conflict – please, let us know.

**Comment by xmatthias** [comment]
> There's a specific reason for pinning the deps of this project. Most of packages like aiohttp will use a ton of other dependencies. This lib manages the users' funds (in the millions). The deps are generic non-financial packages, though, so they don't focus on the security of their codebase that much. So, if a forward-dep is broken or hacked and is injected with malicious code, then a rogue 3rd-party dep can update its code later and then try and do some financial damage to the user. That's the only reason for pinning those versions. Even if that does not protect the user for 100%, it is still better than nothing.

@kroitor I understand your reasoning, but from a security standpoint, i think this is pointless **unless** you also pin each deps dependencies, and these projects subdependencies (and so forth).

For example aiohttp - depends on 7 subpackages ([source](https://github.com/aio-libs/aiohttp/blob/2d36ef6911a1d49001381da40d658a70d64168fa/setup.py#L53-L61).

Attacking either of these can result in the same effect than attacking aiohttp directly - as each imported package can override / monkeypatch a method in aiohttp (or any other package for that matter), redirecting calls to "someplace else" (assuming that's the attack vector you're refering to).

---

From a users point of view (if i'm managing a fund in the millions) - then i'd install ccxt (and whatever else i need) - then `pip freeze > requirements.txt` to have all versions pined - **vet all versions** that i got now very carefully - and then avoid updating ANY of the subpackages unless i reaudit them again / the changes done to them (this is how [big] banks handle dependencies, usually).
Obviously, you'll then only be able to install via requirements.txt

---

However, i don't think this is something a library i use should handle (just consider what happens if every library would try to handle this for the user) - but the user (fund in your example)  will have very strict procedures in place - assuming it's a fund that's audited regularly.

As said above, nothing against pinning dependencies *in the requirements file* - so if a user needs this additional "subdependency" security, installing via ccxt's requirements.txt file gives them your vetted versions - but it'll not break other packages as easily.

**Comment by kroitor** [comment]
@xmatthias thx for your comment, we will consider moving the deps to requirements.txt asap.

**Comment by THETCR** [comment]
@xmatthias I am a senior at ING Group. What is most common nowadays is to not use registries directly but for instance something like Artifactory, all dependencies get scanned through there by a couple of different measures. 
This way developers are allowed to use and update the dependencies, that are deemed safe, as they see fit.

**Comment by xmatthias** [comment]
well but still in Artifactory, only the ones that happen to come up as "safe" (by whatever methods) are actually made available through Artifactory (at least i hope so ...).


Example: safety testing of aiohttp==3.6.3 raised some odd issue and is considered non-safe until someone actually looks at it manually and approvs ... that would prevent the ccxt update since ccxt hard-pins aiohttp to 3.6.3 (as of now).

Not sure that's how it works for you or if "all" package updates make it through the test - but that's how i would think it should  work...

**Pull request merged**
