### PR TITLE
New Exchange: Tradeogre

### PR DESCRIPTION
**Pull request by ZacharyATanenbaum**
Added Trade Ogre exchange with the ability to fetch ticker, fetch balance and fetch markets.

### CODE REVIEW

**Comment by radeone** [comment]
when will this be added to python side? :P

**Comment by kroitor** [comment]
@radeone it's already on Python side, you just have to build it as described in the CONTRIBUTING doc, if you want to try it with Python.

- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#multilanguage-support
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-build--run-tests-on-your-local-machine

**Comment by PaxJaromeMalues** [comment]
dead branch?

**Comment by ttodua** [comment]
was added in ccxt #21767

**Pull request closed without merging**
