### PR TITLE
okex precision

### PR DESCRIPTION
**Pull request by frosty00**

### CODE REVIEW

**Comment by Rishirandhawa** [comment]
Thank you !

**Comment by kroitor** [comment]
@Rishirandhawa it's not fixed yet, but will be uploaded shortly! Thx for reporting!

**Comment by Rishirandhawa** [comment]
ah.. ok I thought the issue is marked closed merging in master. Just to confirm the problem is still there in 1.38.12
Also the same issue is seen in exchange.markets[instrument]['info']['tick_size']

**Comment by kroitor** [comment]
@Rishirandhawa please, check the answer here: https://github.com/ccxt/ccxt/issues/8018#issuecomment-731866092 let us know if that does not help.

**Pull request closed without merging**
