### PR TITLE
fixes parseticker crash when bittrex has just added a new market

### PR DESCRIPTION
**Pull request by hippylover**

### CODE REVIEW

**Comment by kroitor** [comment]
It was fixed 15 minutes ago, but thanks anyway )

**Comment by hippylover** [comment]
doh!

**Comment by hippylover** [comment]
Btw, you have tests that notice stuff like this automatically?

**Comment by kroitor** [comment]
- https://github.com/ccxt/ccxt/tree/master/js/test
- https://github.com/ccxt/ccxt/tree/master/php/test
- https://github.com/ccxt/ccxt/tree/master/python/test
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-build--run-tests-on-your-local-machine

**Pull request closed without merging**
