### PR TITLE
binance.has, okex.has, huobi.has

### PR DESCRIPTION
**Pull request by samgermain**
Added missing properties to has of binance, okex, and huobi, mostly as undefined.

I'll go through all the methods and change most of the undefined to true or false for these 3 exchanges first, before moving on to other certified exchanges

### CODE REVIEW

**Comment by frosty00** [comment]
> I'll go through all the methods and change most of the undefined to true or false for these 3 exchanges first, before moving on to other certified exchanges

I'd suggest to not spend too much time on this since we can script it

**Comment by samgermain** [comment]
> > I'll go through all the methods and change most of the undefined to true or false for these 3 exchanges first, before moving on to other certified exchanges
> 
> I'd suggest to not spend too much time on this since we can script it

No you can't, you need to either implement the method, or check that the exchange does not have the method capabilities

**Comment by kroitor** [comment]
@samgermain i think @frosty00 means, let's only add real true/false changes, we don't have to set all fields to `undefined` in every exchange, cause they are inherited from the base class.

**Comment by samgermain** [comment]
> @samgermain i think @frosty00 means, lets only add real true/false changes, we don't have to set all fields to `undefined` in every exchange, cause they are inherited from the base class.

Yeah but this just makes it easier to check what's still missing, cause the certified exchanges should probably have most of the methods implemented if possible

**Comment by frosty00** [comment]
> @samgermain i think, @frosty00 means, lets only add real true/false changes, we don't have to set all fields to undefined in every exchange, cause they are inherited from the base class.

No I actually mean I can write a script to detect and automatically fill the missing properties

**Comment by samgermain** [comment]
> > @samgermain i think, @frosty00 means, lets only add real true/false changes, we don't have to set all fields to undefined in every exchange, cause they are inherited from the base class.
> 
> No I actually mean I can write a script to detect and automatically fill the missing properties

Yeah

**Comment by kroitor** [comment]
@frosty00 how do you automatically determine if the exchange has or doesn't have a true/false endpoint for a ccxt unified method?

**Comment by samgermain** [comment]
> > @samgermain i think, @frosty00 means, lets only add real true/false changes, we don't have to set all fields to undefined in every exchange, cause they are inherited from the base class.
> 
> No I actually mean I can write a script to detect and automatically fill/correct the missing properties

What I'm trying to say is that each method that's currently undefined should ideally either be written, or set to false if it can't be written. These 3 exchanges are the priority, so we should try to write as many of the unified methods as we can for them, then after that, the certified exchanges should probably have a lot of the unified methods written for them as well

**Comment by frosty00** [comment]
> @frosty00 how do you automatically determine if the exchange has or doesn't have a true/false endpoint for a ccxt unified method?

it's possible to do, if it cannot be done dynamically in js then you can just parse the derived files like how it is done in transpile

**Comment by frosty00** [comment]
```
inspect.classify_class_attrs(ccxt.binance)
```

^ in python

**Comment by samgermain** [comment]
> > @frosty00 how do you automatically determine if the exchange has or doesn't have a true/false endpoint for a ccxt unified method?
> 
> it's possible to do, if it cannot be done dynamically in js then you can just parse the derived files like how it is done in transpile

I don't think we're talking about the same thing

**Pull request merged**
