### PR TITLE
`numberover` stands for remaining instead of filled in BitZ order info response

### PR DESCRIPTION
**Pull request by zjhmale**

### CODE REVIEW

**Comment by kroitor** [comment]
Hi! Can you please move this edit to the JS file?

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

**Comment by zjhmale** [comment]
@kroitor Sure, I will!

**Comment by kroitor** [comment]
@zjhmale No worries, I've merged it already )Thx! Will be happy to see more contributions from you!

**Comment by zjhmale** [comment]
@kroitor Cool :)

**Pull request merged**
