### PR TITLE
[#5843] Coinbase Pro - fetch_deposit_address() should POST, not GET

### PR DESCRIPTION
**Pull request by jbatalha1**
#5843

As per the documentation on Coinbase Pro API, fetch_deposit_address() should POST instead of GET. 

https://docs.pro.coinbase.com/#generate-a-crypto-deposit-address

Tested in Python, but since it was such an easy one I updated PHP and JS as well.

### CODE REVIEW

**Comment by kroitor** [comment]
Thanks a lot!

> Tested in Python, but since it was such an easy one I updated PHP and JS as well.

For the future – we only need to edit just the JS, other files are generated, as explained here:

- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#multilanguage-support

**Comment by kroitor** [comment]
Actually, I think you're confusing `createDepositAddress` with `fetchDepositAddress`: 

- https://github.com/ccxt/ccxt/issues/5843#issuecomment-533685836

↑ Let me know if that does not answer it.

**Comment by wehrstedt** [comment]
> Actually, I think you're confusing `createDepositAddress` with `fetchDepositAddress`:
> 
> * [#5843 (comment)](https://github.com/ccxt/ccxt/issues/5843#issuecomment-533685836)
> 
> ↑ Let me know if that does not answer it.

Hi, hasn't this been merged to master? In ccxt@1.37.7 the corresponding line is still `privateGetCoinbaseAccountsIdAddresses`. Calling `fetchDepositAddress('XRP')` currently results in
```
ExchangeError: coinbasepro Route not found
      at coinbasepro.handleErrors (node_modules\ccxt\js\coinbasepro.js:1092:23)
      at d:\exchange-price-storage\node_modules\ccxt\js\base\Exchange.js:600:18
      at processTicksAndRejections (internal/process/task_queues.js:93:5)
      at timeout (node_modules\ccxt\js\base\functions\time.js:195:24)
      at coinbasepro.request (node_modules\ccxt\js\coinbasepro.js:1099:26)
      at coinbasepro.fetchDepositAddress (node_modules\ccxt\js\coinbasepro.js:1045:26)
```

If I replace `privateGetCoinbaseAccountsIdAddresses` with `privatePostCoinbaseAccountsIdAddresses`, the above function resolves successfully.

Heres a screenshot of the network tab when requesting a deposit address via the web client (professionally edited with paint):
image

As you can see, coinbase pro itselfs do a post request against this route. Can you maybe recheck this PR please?
Thank you very much!

**Comment by kroitor** [comment]
@phillipmoran @wehrstedt please check `createDepositAddress` / `create_deposit_address`, it does a POST call as opposed to `fetchDepositAddress`. The reason this has not been merged is that Coinbase is very restrictive with signups, so we cannot test it on our side to see if a POST-call will return the same address on a consequent call (then it's `fetchDepositAddress`, not `createDepositAddress`), or if a POST-call will generate a new address on each subsequent call (then it's `createDepositAddress`, not `fetchDepositAddress`). If you could help test that and report back here – it would be awesome. We would add the necessary edits quickly.

```Python
import ccxt
print('CCXT Version:', ccxt.__version__)
exchange = ccxt.coinbasepro({
    'apiKey': 'YOUR_API_KEY',
    'secret': 'YOUR_SECRET',
    'password': 'YOUR_PASSWORD',
    'enableRateLimit': True,
})
markets = exchange.load_markets()
exchange.verbose = True
address1 = exchange.create_deposit_address('BTC')
address2 = exchange.create_deposit_address('BTC')
print(address1['address'] == address2['address'])
```

↑ Plz paste your output.

**Comment by wehrstedt** [comment]
```
CCXT Version: 1.37.7

Request: GET https://api.pro.coinbase.com/coinbase-accounts {'CB-ACCESS-KEY': 'XXXX', 'CB-ACCESS-SIGN': 'cYXoRjdjg3_5-v-/GBTb9xw2&L7}W)5eimT8!=A7782b', 'CB-ACCESS-TIMESTAMP': '1604156353', 'CB-ACCESS-PASSPHRASE': 'YYYY', 'Content-Type': 'application/json', 'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36', 'Accept-Encoding': 'gzip, deflate'} None

Response: GET https://api.pro.coinbase.com/coinbase-accounts 200 {'Date': 'Sat, 31 Oct 2020 14:59:14 GMT', 'Content-Type': 'application/json; charset=utf-8', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Set-Cookie': '__cfduid=dq6v9ao8qzjpcnnpv5nioy2uvddi4tmp3w22ef4m8t2v; expires=Mon, 30-Nov-20 14:59:13 GMT; path=/; domain=.pro.coinbase.com; HttpOnly; SameSite=Lax', 'Access-Control-Allow-Headers': 'Content-Type, Accept, cb-session, cb-fp, cb-form-factor', 'Access-Control-Allow-Methods': 'GET,POST,DELETE,PUT', 'Access-Control-Allow-Origin': '*', 'Access-Control-Expose-Headers': 'cb-before, cb-after, cb-gdpr', 'Access-Control-Max-Age': '7200', 'Cache-Control': 'no-store', 'Etag': 'W/"2509-vw7yf6x43i6d9hq7dpxb9mepkgd"', 'Strict-Transport-Security': 'max-age=15552000; includeSubDomains', 'X-Content-Type-Options': 'nosniff', 'X-Dns-Prefetch-Control': 'off', 'X-Download-Options': 'noopen', 'X-Frame-Options': 'SAMEORIGIN', 'X-Xss-Protection': '1; mode=block', 'CF-Cache-Status': 'MISS', 'cf-request-id': '4icht3zi8e96n3m9wg973wxnjo4as8b8', 'Expect-CT': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"', 'Vary': 'Accept-Encoding', 'Server': 'cloudflare', 'CF-RAY': '36cqn67z7z8h2nc3-DUS', 'Content-Encoding': 'gzip'} [{"id":"d8047fde-0492-4cde-93c6-ba01a231017c","name":"REN Wallet","balance":"0.00000000","currency":"REN","type":"wallet","primary":false,"active":true,"available_on_consumer":true,"hold_balance":"0.00","hold_currency":"EUR"},{"id":"56ba830a-e951-475a-a650-41332258af45","name":"WBTC Wallet","balance":"0.00000000","currency":"WBTC","type":"wallet","primary":false,"active":true,"available_on_consumer":true,"hold_balance":"0.00","hold_currency":"EUR"},{"id":"4e076893-de18-4d1d-8346-b36c979e7857","name":"BAL Wallet","balance":"0.00000000","currency":"BAL","type":"wallet","primary":false,"active":true,"available_on_consumer":true,"hold_balance":"0.00","hold_currency":"EUR"},{"id":"ba88c643-749d-42f2-b64c-ca314c8bdfd8","name":"REP Wallet","balance":"0.00000000","currency":"REP","type":"wallet","primary":false,"active":true,"available_on_consumer":true,"hold_balance":"0.00","hold_currency":"EUR"},{"id":"a49aea53-996a-4981-9948-9baf6626c2d2","name":"XRP Wallet","balance":"0.000000","currency":"XRP","type":"wallet","primary":false,"active":true,"available_on_consumer":true,"destination_tag_name":"XRP Tag","destination_tag_regex":"^\\d{1,10}$","hold_balance":"0.00","hold_currency":"EUR"},{"id":"d1cd60cf-69a3-4969-8138-5047c9c7a87d","name":"OMG Wallet","balance":"0.00000000","currency":"OMG","type":"wallet","primary":false,"active":true,"available_on_consumer":true,"hold_balance":"0.00","hold_currency":"EUR"},{"id":"0bf9e823-8888-40a5-84eb-2e0128f05c53","name":"ZRX Wallet","balance":"0.00000000","currency":"ZRX","type":"wallet","primary":false,"active":true,"available_on_consumer":true,"hold_balance":"0.00","hold_currency":"EUR"},{"id":"72585a8c-2908-4792-a8a3-b2c82582d23a","name":"YFI Wallet","balance":"0.00000000","currency":"YFI","type":"wallet","primary":false,"active":true,"available_on_consumer":true,"hold_balance":"0.00","hold_currency":"EUR"},{"id":"69a08893-1d6b-4b64-a54c-66e58b6e19b1","name":"NMR Wallet","balance":"0.00000000","currency":"NMR","type":"wallet","primary":false,"active":true,"available_on_consumer":true,"hold_balance":"0.00","hold_currency":"EUR"},{"id":"307599e5-c18a-46be-bfc1-5d68dfd18208","name":"CGLD Wallet","balance":"0.00000000","currency":"CGLD","type":"wallet","primary":false,"active":true,"available_on_consumer":true,"hold_balance":"0.00","hold_currency":"EUR"},{"id":"40328630-637d-4e09-baf2-fc2e10f49dc9","name":"LRC Wallet","balance":"0.00000000","currency":"LRC","type":"wallet","primary":false,"active":true,"available_on_consumer":true,"hold_balance":"0.00","hold_currency":"EUR"},{"id":"d9e82470-5b24-4d25-a431-6accb72b1f2a","name":"UMA Wallet","balance":"0.00000000","currency":"UMA","type":"wallet","primary":false,"active":true,"available_on_consumer":true,"hold_balance":"0.00","hold_currency":"EUR"},{"id":"8e94a118-ca95-4f8b-bf32-f25327f113c5","name":"ALGO Wallet","balance":"0.000000","currency":"ALGO","type":"wallet","primary":false,"active":true,"available_on_consumer":true,"hold_balance":"0.00","hold_currency":"EUR"},{"id":"002bf4b0-c162-497d-8ca9-bd1edae25d1e","name":"MKR Wallet","balance":"0.00000000","currency":"MKR","type":"wallet","primary":false,"active":true,"available_on_consumer":true,"hold_balance":"0.00","hold_currency":"EUR"},{"id":"c71d5e48-5832-41e2-acb3-80c29704b627","name":"UNI Wallet","balance":"0.00000000","currency":"UNI","type":"wallet","primary":false,"active":true,"available_on_consumer":true,"hold_balance":"0.00","hold_currency":"EUR"},{"id":"b9f1db5a-dbf6-4d91-8e5d-fbe1301c5a98","name":"BAND Wallet","balance":"0.00000000","currency":"BAND","type":"wallet","primary":false,"active":true,"available_on_consumer":true,"hold_balance":"0.00","hold_currency":"EUR"},{"id":"663de0e7-8a5e-45d0-a06d-761b55ca2d9d","name":"ZEC Wallet","balance":"0.00000000","currency":"ZEC","type":"wallet","primary":false,"active":true,"available_on_consumer":true,"hold_balance":"0.00","hold_currency":"EUR"},{"id":"ba39b9ca-45b0-4a34-a5d9-4d1d0d35afb5","name":"ETC Wallet","balance":"0.00000000","currency":"ETC","type":"wallet","primary":false,"active":true,"available_on_consumer":true,"hold_balance":"0.00","hold_currency":"EUR"},{"id":"8098f888-d14d-4de2-a6de-d22cb992e1f7","name":"LTC Wallet","balance":"0.00000000","currency":"LTC","type":"wallet","primary":false,"active":true,"available_on_consumer":true,"hold_balance":"0.00","hold_currency":"EUR"},{"id":"4b02812e-11c0-4b40-bade-e36c5f8970c1","name":"ATOM Wallet","balance":"4.572052","currency":"ATOM","type":"wallet","primary":false,"active":true,"available_on_consumer":true,"destination_tag_name":"ATOM Memo","destination_tag_regex":"^\\w{1,24}$","hold_balance":"0.00","hold_currency":"EUR"},{"id":"3531e1bb-e4dc-4c22-a613-402a5e1460fb","name":"KNC Wallet","balance":"2.28220052","currency":"KNC","type":"wallet","primary":false,"active":true,"available_on_consumer":true,"hold_balance":"0.00","hold_currency":"EUR"},{"id":"7b6b84b7-203c-4e45-a7f9-d6bb60075187","name":"COMP Wallet","balance":"0.05729323","currency":"COMP","type":"wallet","primary":false,"active":true,"available_on_consumer":true,"hold_balance":"0.00","hold_currency":"EUR"},{"id":"b8eaa32c-d440-479d-b707-279ea50e1997","name":"DASH Wallet","balance":"0.16442461","currency":"DASH","type":"wallet","primary":false,"active":true,"available_on_consumer":true,"hold_balance":"0.00","hold_currency":"EUR"},{"id":"8553447f-cc8f-4ef2-b3a8-82b26450603e","name":"BCH Wallet","balance":"0.00000000","currency":"BCH","type":"wallet","primary":false,"active":true,"available_on_consumer":true,"hold_balance":"0.00","hold_currency":"EUR"},{"id":"e268bf89-188b-4ccd-8ddf-d9218d77a5fe","name":"BAT Wallet","balance":"0.00000000","currency":"BAT","type":"wallet","primary":false,"active":true,"available_on_consumer":true,"hold_balance":"0.00","hold_currency":"EUR"},{"id":"d0029680-2903-43c7-be19-456252cee03b","name":"LINK Wallet","balance":"0.00000000","currency":"LINK","type":"wallet","primary":false,"active":true,"available_on_consumer":true,"hold_balance":"0.00","hold_currency":"EUR"},{"id":"3c4e8c6e-5375-446c-8a60-e5abeb1fb6c9","name":"EOS Wallet","balance":"0.4590","currency":"EOS","type":"wallet","primary":false,"active":true,"available_on_consumer":true,"destination_tag_name":"EOS Memo","destination_tag_regex":"^.{1,100}$","hold_balance":"0.00","hold_currency":"EUR"},{"id":"6c1281a5-605e-48ba-b994-68f373499daa","name":"XTZ Wallet","balance":"0.000000","currency":"XTZ","type":"wallet","primary":false,"active":true,"available_on_consumer":true,"hold_balance":"0.00","hold_currency":"EUR"},{"id":"2a9e3cb5-d5a9-4da5-913b-498c47ae5c8a","name":"DAI Wallet","balance":"0.00000000","currency":"DAI","type":"wallet","primary":false,"active":true,"available_on_consumer":true,"hold_balance":"0.00","hold_currency":"EUR"},{"id":"6d2590bd-148e-4b9d-aad1-d0a9cd1deda9","name":"ETH Wallet","balance":"0.02475663","currency":"ETH","type":"wallet","primary":false,"active":true,"available_on_consumer":true,"hold_balance":"0.00","hold_currency":"EUR"},{"id":"f59eced8-f090-4a2d-adbb-067cf3678f98","name":"OXT Wallet","balance":"0.00000000","currency":"OXT","type":"wallet","primary":false,"active":true,"available_on_consumer":true,"hold_balance":"0.00","hold_currency":"EUR"},{"id":"87a7e536-0329-48b2-95b0-5dbcff55198a","name":"USDC Wallet","balance":"0.000000","currency":"USDC","type":"wallet","primary":false,"active":true,"available_on_consumer":true,"hold_balance":"0.00","hold_currency":"EUR"},{"id":"275e3447-864b-44bc-9024-3e75ab1b39f4","name":"XLM Wallet","balance":"0.0000000","currency":"XLM","type":"wallet","primary":false,"active":true,"available_on_consumer":true,"destination_tag_name":"XLM Memo ID","destination_tag_regex":"^[ -~]{1,28}$","hold_balance":"0.00","hold_currency":"EUR"},{"id":"1db3c3a8-82ca-4ac7-85d1-68b1ec6e5687","name":"EUR Wallet","balance":"67.20","currency":"EUR","type":"fiat","primary":false,"active":true,"available_on_consumer":true,"sepa_deposit_information":{"iban":"EE297700771001961370","swift":"LHVBEE22","bank_name":"AS LHV Pank","bank_address":"Tartu mnt 2, 10145 Tallinn, Estonia","bank_country":{"code":"EE","name":"Estonia"},"account_name":"CB Payments, Ltd","account_address":"5 Fleet Place, London, England , EC4M 7RD, United Kingdom","reference":"CBAEURZNVDULCXEXC"},"hold_balance":"0.00","hold_currency":"EUR"},{"id":"bbe4e6a5-b333-4350-a512-bf480017283f","name":"BTC Wallet","balance":"0.00000000","currency":"BTC","type":"wallet","primary":true,"active":true,"available_on_consumer":true,"hold_balance":"0.00","hold_currency":"EUR"},{"id":"LOOM","name":"LOOM Wallet","balance":"0.00000000","currency":"LOOM","type":"wallet","primary":false,"active":true,"available_on_consumer":false,"hold_balance":"0.00","hold_currency":"EUR"},{"id":"MANA","name":"MANA Wallet","balance":"0.00000000","currency":"MANA","type":"wallet","primary":false,"active":true,"available_on_consumer":false,"hold_balance":"0.00","hold_currency":"EUR"},{"id":"DNT","name":"DNT Wallet","balance":"0.00000000","currency":"DNT","type":"wallet","primary":false,"active":true,"available_on_consumer":false,"hold_balance":"0.00","hold_currency":"EUR"},{"id":"CVC","name":"CVC Wallet","balance":"0.00000000","currency":"CVC","type":"wallet","primary":false,"active":true,"available_on_consumer":false,"hold_balance":"0.00","hold_currency":"EUR"},{"id":"GNT","name":"GNT Wallet","balance":"0.00000000","currency":"GNT","type":"wallet","primary":false,"active":true,"available_on_consumer":false,"hold_balance":"0.00","hold_currency":"EUR"}]

Request: POST https://api.pro.coinbase.com/coinbase-accounts/bbe4e6a5-b333-4350-a512-bf480017283f/addresses {'CB-ACCESS-KEY': 'XXXX', 'CB-ACCESS-SIGN': ',\4;rk}~9a6j<v}z3m!;5dwtqs3]6]&a^3(6h7u25:3\', 'CB-ACCESS-TIMESTAMP': '1604156354', 'CB-ACCESS-PASSPHRASE': 'YYYY', 'Content-Type': 'application/json', 'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36', 'Accept-Encoding': 'gzip, deflate'} None

Response: POST https://api.pro.coinbase.com/coinbase-accounts/bbe4e6a5-b333-4350-a512-bf480017283f/addresses 200 {'Date': 'Sat, 31 Oct 2020 14:59:14 GMT', 'Content-Type': 'application/json; charset=utf-8', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Set-Cookie': '__cfduid=kr57u9658h397i8ot4cdkr33zv87n5axxbgn8c8bnom; expires=Mon, 30-Nov-20 14:59:14 GMT; path=/; domain=.pro.coinbase.com; HttpOnly; SameSite=Lax', 'Access-Control-Allow-Headers': 'Content-Type, Accept, cb-session, cb-fp, cb-form-factor', 'Access-Control-Allow-Methods': 'GET,POST,DELETE,PUT', 'Access-Control-Allow-Origin': '*', 'Access-Control-Expose-Headers': 'cb-before, cb-after, cb-gdpr', 'Access-Control-Max-Age': '7200', 'Cache-Control': 'no-store', 'Etag': 'W/"3+4kr*#9#\%4>d)[@8~(w,v98i3(-,\"', 'Strict-Transport-Security': 'max-age=15552000; includeSubDomains', 'X-Content-Type-Options': 'nosniff', 'X-Dns-Prefetch-Control': 'off', 'X-Download-Options': 'noopen', 'X-Frame-Options': 'SAMEORIGIN', 'X-Xss-Protection': '1; mode=block', 'CF-Cache-Status': 'DYNAMIC', 'cf-request-id': '9wjquvh47m2e38u45m97ybiv4s3q9dfj', 'Expect-CT': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"', 'Server': 'cloudflare', 'CF-RAY': '97m7t5277gg3q675-DUS', 'Content-Encoding': 'gzip'} {"id":"9cbb3c37-bd73-490c-8cd5-ad8a4ee6e2f1","address":"tnm555o4swz6medvjt9stjnk5k24kke5hb","address_info":{"address":"tnm555o4swz6medvjt9stjnk5k24kke5hb"},"name":"New exchange deposit address","created_at":"2020-10-31T14:59:14Z","updated_at":"2020-10-31T14:59:14Z","network":"bitcoin","uri_scheme":"bitcoin","resource":"address","resource_path":"/v2/accounts/bbe4e6a5-b333-4350-a512-bf480017283f/addresses/9cbb3c37-bd73-490c-8cd5-ad8a4ee6e2f1","warnings":[{"title":"Nur Bitcoin (BTC) an diese Adresse senden","details":"Wenn Sie andere W�hrungen, u.�a. Bitcoin�Cash (BCH), senden, gehen diese unwiederbringlich verloren.","image_url":"https://dynamic-assets.coinbase.com/e785e0181f1a23a30d9476038d9be91e9f6c63959b538eabbc51a1abc8898940383291eede695c3b8dfaa1829a9b57f5a2d0a16b0523580346c6b8fab67af14b/asset_icons/b57ac673f06a4b0338a596817eb0a50ce16e2059f327dc117744449a47915cb2.png"}],"deposit_uri":"bitcoin:tnm555o4swz6medvjt9stjnk5k24kke5hb","callback_url":null,"exchange_deposit_address":true}

Request: POST https://api.pro.coinbase.com/coinbase-accounts/bbe4e6a5-b333-4350-a512-bf480017283f/addresses {'CB-ACCESS-KEY': 'XXXX', 'CB-ACCESS-SIGN': 't9+8v-ro#=h?e<*j,c^e3&%3b?2]m9tkc\kk+xo}89\j', 'CB-ACCESS-TIMESTAMP': '1604156355', 'CB-ACCESS-PASSPHRASE': 'YYYY', 'Content-Type': 'application/json', 'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36', 'Accept-Encoding': 'gzip, deflate'} None

Response: POST https://api.pro.coinbase.com/coinbase-accounts/bbe4e6a5-b333-4350-a512-bf480017283f/addresses 200 {'Date': 'Sat, 31 Oct 2020 14:59:15 GMT', 'Content-Type': 'application/json; charset=utf-8', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Set-Cookie': '__cfduid=b72ecomhhsm932viht73dtm77x4orcvw3n7xjt9nzva; expires=Mon, 30-Nov-20 14:59:15 GMT; path=/; domain=.pro.coinbase.com; HttpOnly; SameSite=Lax', 'Access-Control-Allow-Headers': 'Content-Type, Accept, cb-session, cb-fp, cb-form-factor', 'Access-Control-Allow-Methods': 'GET,POST,DELETE,PUT', 'Access-Control-Allow-Origin': '*', 'Access-Control-Expose-Headers': 'cb-before, cb-after, cb-gdpr', 'Access-Control-Max-Age': '7200', 'Cache-Control': 'no-store', 'Etag': 'W/"i/c5&6.:3(o#{\4+k@;47};&vu+?*78"', 'Strict-Transport-Security': 'max-age=15552000; includeSubDomains', 'X-Content-Type-Options': 'nosniff', 'X-Dns-Prefetch-Control': 'off', 'X-Download-Options': 'noopen', 'X-Frame-Options': 'SAMEORIGIN', 'X-Xss-Protection': '1; mode=block', 'CF-Cache-Status': 'DYNAMIC', 'cf-request-id': '8cpgiac3273982sqtd5oy8jx9i7432a3', 'Expect-CT': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"', 'Server': 'cloudflare', 'CF-RAY': 'h92a3h7qo5aot399-DUS', 'Content-Encoding': 'gzip'} {"id":"a23923f7-c6ee-41d6-ba49-97ad7c57c0dc","address":"8g8cu68oi75f5qfotopar3mc3co48vdcjj","address_info":{"address":"8g8cu68oi75f5qfotopar3mc3co48vdcjj"},"name":"New exchange deposit address","created_at":"2020-10-31T14:59:15Z","updated_at":"2020-10-31T14:59:15Z","network":"bitcoin","uri_scheme":"bitcoin","resource":"address","resource_path":"/v2/accounts/bbe4e6a5-b333-4350-a512-bf480017283f/addresses/a23923f7-c6ee-41d6-ba49-97ad7c57c0dc","warnings":[{"title":"Nur Bitcoin (BTC) an diese Adresse senden","details":"Wenn Sie andere W�hrungen, u.�a. Bitcoin�Cash (BCH), senden, gehen diese unwiederbringlich verloren.","image_url":"https://dynamic-assets.coinbase.com/e785e0181f1a23a30d9476038d9be91e9f6c63959b538eabbc51a1abc8898940383291eede695c3b8dfaa1829a9b57f5a2d0a16b0523580346c6b8fab67af14b/asset_icons/b57ac673f06a4b0338a596817eb0a50ce16e2059f327dc117744449a47915cb2.png"}],"deposit_uri":"bitcoin:8g8cu68oi75f5qfotopar3mc3co48vdcjj","callback_url":null,"exchange_deposit_address":true}
False
```

(note: i replaced the api-keys and uuids, if you need this for debugging purpose...)

**Comment by kroitor** [comment]
@wehrstedt so, as you see, it says "False", meaining that a POST-call will generate a new address everytime, so it corresponds to `createDepositAddress` and it does not match the `fetchDepositAddress` behaviour. And that probably answers your question, right?

**Comment by wehrstedt** [comment]
@kroitor You are right, i get the point. The api docu does not explicit mention a "list deposit addresses" route for coinbase pro. However, the pro api doc referes to the coinbase api doc "[for  more information](https://docs.pro.coinbase.com/#coinbase-accounts)" on coinbase accounts. And that docu in turn lists an endpoint for listing deposit addresses: https://developers.coinbase.com/api/v2#list-addresses.

But as mentioned [here](https://github.com/ccxt/ccxt/pull/7405#issuecomment-719942120), the request results with `Route not found`. Then coinbase pro seems not to support `fetchDepositAddress`, right?

**Comment by kroitor** [comment]
> Then coinbase pro seems not to support fetchDepositAddress, right?

Yes, that's correct. We will most likely remove that until they add it on their side. So we will keep the `createDepositAddress`, and will remove the `fetchDepositAddress`. What do you say?

**Comment by wehrstedt** [comment]
That's what I would suggest. Thank you for your efforts!

**Pull request closed without merging**
