### PR TITLE
Return order instead of id and throw error if nothing fetch

### PR DESCRIPTION
**Pull request by adi90x**
Only hitbtc.js 😁

### CODE REVIEW

**Comment by kroitor** [comment]
Thanks a lot! Appreciate it! Merging very soon.

**Comment by adi90x** [comment]
Correcting an Api end point error and some lint errors

**Comment by adi90x** [comment]
Any update on this one ?

**Comment by kroitor** [comment]
> Any update on this one ?

Almost done merging it, will upload soon.

**Pull request merged**
