### PR TITLE
new exchange: negociecoins

### PR DESCRIPTION
**Pull request by Deathamns**
#1029

### CODE REVIEW

**Comment by kroitor** [comment]
Double-kill!

**Comment by thijstriemstra** [comment]
@kroitor you can also label pull requests. a label for addition of new exchange would be useful.

**Comment by kroitor** [comment]
@thijstriemstra thx for the hint, will add some new labels there! )

**Comment by htadashi** [comment]
Thanks for writing the code for this important Brazilian exchange 👍 
Since last week, NegocieCoins also added support for a BRL/DASH market... could you also add this to the code? :)

Thanks again and best regards!

**Pull request merged**
