### PR TITLE
update allcoin's load markets method by using new URI

### PR DESCRIPTION
**Pull request by bugking**
the old web API urI "marketoverviews" apparently not working anymore, it always raises timeout error. I have tried to replace it with the Home/MarketOverViewDetail url

### CODE REVIEW

**Comment by bugking** [comment]
btw, the reason of adding 'www' to the web API uri is sometimes allcoin.com won't respond, but www.allcoin.com always responds

**Comment by kroitor** [comment]
Oh-oh.... Can you please exclude the doc-files from this pull request?
- README.md
- build/ccxt.browser.js
- doc/README.rst
- doc/exchanges-by-country.rst
- doc/exchanges.rst
- doc/manual.rst
- python/README.rst
- wiki/Exchange-Markets-By-Country.md
- wiki/Exchange-Markets.md
- wiki/Manual.md
- php/allcoin.php
- python/ccxt/allcoin.py
- python/ccxt/async/allcoin.py

All those files are generated and we should not commit them to avoid bloating the repository (it is over 200mb already). Basically, we need a single js/allcoin.js file. Can you clean it up for me please? I would be able to merge it quickly then.

More about it here: https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

**Comment by bugking** [comment]
sure :) let me fix this

**Comment by kroitor** [comment]
Thank you so much!

**Comment by kroitor** [comment]
Replaced by #966.

**Pull request closed without merging**
