### PR TITLE
PHP stuff for appveyor

### PR DESCRIPTION
**Pull request by kornrunner**
Not quite sure if I got it straight, but we'll find out once tests finish :)

### CODE REVIEW

**Comment by kroitor** [comment]
The problem there was with installing it properly, and the last time I tried it didn't see the curl extension (as well as other extensions, I suppose).

**Comment by prisis** [comment]
I have a easy way to install php for appveyor https://github.com/narrowspark/framework/blob/347b2e7bd26a2d11c4d107d5fb5e1e0305136fbf/appveyor.yml#L55-L56

**Comment by kroitor** [comment]
@prisis thx! Looks like @kornrunner saved me, as always ) There's now a minor transpilation error, but I've already uploaded a fix for it.

**Comment by kroitor** [comment]
@prisis, @kornrunner it is definitely installed now, but still doesn't want to see the curl or, I believe, doesn't see any extension at all.

**Comment by kornrunner** [comment]
It does see curl, but then it complained about mbstring, so I added that as well.

I'll push a merge with master, but as far as I can see - kucoin thing is still failing.

**Comment by kroitor** [comment]
@kornrunner don't worry about it, I'll fix it (uploaded another one, can't test locally at the moment).

**Comment by kornrunner** [comment]
I think this is okay now (failures relate to unrelated stuff)

**Comment by kroitor** [comment]
Yay, it has passed the build ) Thanks, @kornrunner , you're the man! )

**Comment by kroitor** [comment]
@kornrunner I have a question to you, as you are a familiar with PHP better than me, if it is possible to override an inherited method with an assignment operator in PHP (or maybe some other hack).
What I want is to allow a user to define a nonce-function in constructor params, however, the inherited `nonce()` method seems to be overriding my override ) And it turns out that in PHP we can't really override the nonce without subclassing it. So, I though, maybe you know of a way to achieve this:

```PHP
$exchange = \ccxt\someexchange (array ({ 'nonce': function () { ... } })); 
```

**Comment by kornrunner** [comment]
I'll think of something and submit a PR

**Comment by kroitor** [comment]
@kornrunner thank you! I think, this is related: http://php.net/manual/en/language.oop5.overloading.php#object.call , however, I'm not sure if it allows to retain the redefined nonce()-overrides (some derived classes override that method, this makes it a lot more complicated than it may seem at first, yet, I'm not very well informed here).

**Pull request merged**
