### PR TITLE
Add maintenanceMarginRate to fetchMarkets

### PR DESCRIPTION
**Pull request by samgermain**
2022-02-05T08:30:11.742Z
Node.js: v14.17.0
CCXT v1.72.29

# AAX

```
aax.fetchMarkets ()
1175 ms
           id |           symbol |      base | quote | settle |    baseId | quoteId | settleId | type |  spot | margin |  swap | future | option | active | contract | linear | inverse |  taker |  maker | contractSize | maintenanceMarginRatio | expiry | expiryDatetime | strike | optionType | quanto |                            precision |          limits
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
    BTCUSDTFP |    BTC/USDT:USDT |       BTC |  USDT |   USDT |       BTC |    USDT |     USDT | swap | false |  false |  true |  false |  false |   true |     true |   true |   false | 0.0004 | 0.0002 |        0.001 |                  0.005 |        |                |        |            |  false |            {"price":0.01,"amount":1} | [object Object]
...
    BCHABCBTC |          BCH/BTC |       BCH |   BTC |        |    BCHABC |     BTC |          | spot |  true |  false | false |  false |  false |  false |    false |        |         |      0 |      0 |              |                        |        |                |        |            |        |     {"price":0.00001,"amount":0.001} | [object Object]
       ELFBTC |          ELF/BTC |       ELF |   BTC |        |       ELF |     BTC |          | spot |  true |  false | false |  false |  false |  false |    false |        |         |  0.001 | 0.0006 |              |                        |        |                |        |            |        |            {"price":1e-8,"amount":1} | [object Object]
273 objects
```

# Mexc

```
mexc.fetchContractMarkets ()
246 ms
            id |                symbol |        base | quote | settle |    baseId | quoteId | settleId | type |  spot | margin | swap | future | option | active | contract | linear | inverse |  taker |  maker | contractSize | maintenanceMarginRatio | expiry | expiryDatetime | strike | optionType |                     precision |                                                                                 limits
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
    LOOKS_USDT |       LOOKS/USDT:USDT |       LOOKS |  USDT |   USDT |     LOOKS |    USDT |     USDT | swap | false |  false | true |  false |  false |   true |     true |   true |   false | 0.0006 | 0.0002 |            1 |                   0.02 |        |                |        |            |   {"price":0.0001,"amount":1} |   {"leverage":{"min":1,"max":20},"amount":{"min":1,"max":100000},"price":{},"cost":{}}
...
      CVC_USDT |         CVC/USDT:USDT |         CVC |  USDT |   USDT |       CVC |    USDT |     USDT | swap | false |  false | true |  false |  false |   true |     true |   true |   false | 0.0006 | 0.0002 |            1 |                   0.01 |        |                |        |            |  {"price":0.00001,"amount":1} |  {"leverage":{"min":1,"max":50},"amount":{"min":1,"max":1000000},"price":{},"cost":{}}
    WAVES_USDT |       WAVES/USDT:USDT |       WAVES |  USDT |   USDT |     WAVES |    USDT |     USDT | swap | false |  false | true |  false |  false |   true |     true |   true |   false | 0.0006 | 0.0002 |          0.1 |                   0.01 |        |                |        |            |   {"price":0.0001,"amount":1} |   {"leverage":{"min":1,"max":50},"amount":{"min":1,"max":300000},"price":{},"cost":{}}
202 objects
```

# Gateio Swap

```
gateio.fetchMarkets ()
352 ms
            id |              symbol |      base | quote | settle |    baseId | quoteId | settleId | type |  spot | margin | swap | future | option | active | contract | linear | inverse |     taker |      maker | contractSize | maintenanceMarginRatio | expiry | expiryDatetime | strike | optionType |                     precision |          limits
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
      CLV_USDT |       CLV/USDT:USDT |       CLV |  USDT |   USDT |       CLV |    USDT |     usdt | swap | false |  false | true |  false |  false |   true |     true |   true |   false | 0.0000075 | -0.0000025 |            1 |                  0.025 |        |                |        |            |   {"price":0.0001,"amount":1} | [object Object]
...
       EOS_USD |         EOS/USD:BTC |       EOS |   USD |    BTC |       EOS |     USD |      btc | swap | false |  false | true |  false |  false |   true |     true |  false |   false | 0.0000075 | -0.0000025 |       0.0001 |                  0.025 |        |                |        |            |    {"price":0.001,"amount":1} | [object Object]
       XRP_USD |         XRP/USD:BTC |       XRP |   USD |    BTC |       XRP |     USD |      btc | swap | false |  false | true |  false |  false |   true |     true |  false |   false | 0.0000075 | -0.0000025 |        0.001 |                  0.025 |        |                |        |            |   {"price":0.0001,"amount":1} | [object Object]
204 objects
```

# Gateio spot

```
gateio.fetchMarkets ()
229 ms
            id |                      symbol |                   base | quote | settle |    baseId | quoteId | settleId | type | spot | margin |  swap | future | option | active | contract | linear | inverse |  taker |  maker | contractSize | maintenanceMarginRatio | expiry | expiryDatetime | strike | optionType |                          precision |                                                                      limits
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
       IHT_ETH |                     IHT/ETH |                    IHT |   ETH |        |       IHT |     ETH |          | spot | true |  false | false |  false |  false |   true |    false |        |         |  0.002 |  0.002 |              |                        |        |                |        |            |        {"price":1e-9,"amount":0.1} |  {"leverage":{"min":1,"max":1},"amount":{},"price":{},"cost":{"min":0.001}}
Waiting for the debugger to disconnect...
...
      DSD_USDT |                    DSD/USDT |                    DSD |  USDT |        |       DSD |    USDT |          | spot | true |  false | false |  false |  false |   true |    false |        |         |  0.002 |  0.002 |              |                        |        |                |        |            |   {"price":0.00001,"amount":0.001} |      {"leverage":{"min":1,"max":1},"amount":{},"price":{},"cost":{"min":1}}
    ALPHR_USDT |                  ALPHR/USDT |                  ALPHR |  USDT |        |     ALPHR |    USDT |          | spot | true |  false | false |  false |  false |   true |    false |        |         |  0.002 |  0.002 |              |                        |        |                |        |            |   {"price":0.0001,"amount":0.0001} |      {"leverage":{"min":1,"max":1},"amount":{},"price":{},"cost":{"min":1}}
2474 objects
```

### CODE REVIEW

**Comment by frosty00** [comment]
I wouldn't call it `maintenanceMarginRatio` but `maintenanceMarginPercentage`, also I don't think we can add it since most exchanges have tiers

**Comment by samgermain** [comment]
> I wouldn't call it `maintenanceMarginRatio` but `maintenanceMarginPercentage`, also I don't think we can add it since most exchanges have tiers - aka the required maintenance margin changes as you increase your leverage and or increase the size of your position

I also have a PR for tiers, I'm trying to provide a way to get the maintenanceMarginRatio on most exchanges, an alternative would be to have one tier for each currency on these exchanges, with a floor of 0, and a cap of infinity or max int or something

**Comment by frosty00** [comment]
I don't think we can unify inside of markets because most exchanges don't provide the full information in the markets endpoint

**Comment by samgermain** [comment]
> I don't think we can unify inside of markets because most exchanges don't provide the full information in the markets endpoint

Do you like the idea of having one tier?

**Comment by frosty00** [comment]
> Do you like the idea of having one tier?

Not really, cause it doesn't reflect what the actual maintenance margin will be

**Comment by kroitor** [comment]
> I don't think we can unify inside of markets because most exchanges don't provide the full information in the markets endpoint

I think we will have to unify it in several places:

- either in markets (if available from the markets-endpoint, otherwise set to undefined in markets)
- or via a standalone endpoint (could be exchange-wide or per-market)
- maybe somewhere else as well

This way we cover most of the exchanges' differences and the user will have whatever data is available from the exchange. The goal is to just translate the data for the user to decide.

**Comment by samgermain** [comment]
> > I don't think we can unify inside of markets because most exchanges don't provide the full information in the markets endpoint
> 
> I think we will have to unify it in several places:
> 
>     * either in markets (if available from the markets-endpoint, otherwise set to undefined in markets) – added in this PR
> 
>     * or via a standalone endpoint (could be exchange-wide, or account-wide, or per-market) – not added yet
> 
>     * maybe somewhere else as well
> 
> 
> This way we cover most of the exchanges' differences and the user will have whatever data is available from the exchange. The goal is to just translate the data for the user to decide.

Yeah if we don't unify it in markets, then for the exchanges that don't have `fetchLeverageTiers`, users will have to access it by the exchange specific name in `info`, if it's undefined on most markets that's fine

**Comment by kroitor** [comment]
@samgermain I would suggest renaming it to maintenanceMarginRate, cause we use the term _rate_ in other such cases, but we don't really have `_ratio_` anywhere.

**Comment by samgermain** [comment]
> @samgermain I would suggest renaming it to maintenanceMarginRate, cause we use the term _rate_ in other such cases, but we don't really have _ratio_ anywhere.

I talked to someone from Binance's api customer service and they told me that `maintenanceMarginRate` is a percentage, so `maintenanceMarginRatio` might be more accurate

**Comment by kroitor** [comment]
> I talked to someone from Binance's api customer service and they told me that `maintenanceMarginRate` is a percentage, so `maintenanceMarginRatio` might be more accurate
> 
> This actually might not be true, I read over the convo again and they were kinda unclear

Since we use rate for that scale of values – i would suggest renaming it to `maintenanceMarginRate`.

**Pull request merged**
