### PR TITLE
bitget - fix currency ID vs CODE

### LINKED ISSUE #21112: Bitget error when use fetch_deposit_address
### Operating System

Windows 10 

### Programming Languages

Python

### CCXT Version

4.1.84

### Description

There is such a problem in bitget. I can't get the deposit address if there is a dollar sign in the ticker($AI, $ALT for example), I will get `{"code":"42017","msg":"The current chain does not support deposit the coin"` error. I removed the dollar using commonCurrency, but it doesn't help. I also noticed that commonCurrency does not work with bitget. For example, I included Toncoin there, but I will receive the following error - `code":"40019","msg":"Parameter coin cannot be empty`. I have not seen this with other exchanges. I also understand that if i put 'ALT':'ALT0', $ALT':'ALT', in commonCurrencies I always will got None as a result of my funcion but I dont know how to deal with it. 
  I also want to add, that after some test I think that this problem with obtaining a deposit address while currency in commonCurrencies occurs not only in bitget. For example, with gate and 'GTC'(Game.com in commonCurrencies) if we try exchange.fetchNetworkDepositAddress('GTC'), we will get  gate does not have currency code GTC, but if we try exchange.fetchNetworkDepositAddress('Game.com') we will get gate {"label":"INVALID_CURRENCY","message":"invalid currency"}. 
  With mexc for example if commonCurrency = {'GMT':'GOMINING, 'STEPN':'GMT',} if i use exchange.fetchDepositAddressesByNetwork('GMT') and exchange.fetchDepositAddressesByNetwork('GOMINING') I will get the same networks and addresses which are related only to STEPN GMT/ So if I use exchange.fetchDepositAddressesByNetwork('GOMINING') I will get wrong networks and sometimes addresses.
  I also admit that I did something wrong. In any case, it would be nice if you checked it out.

### PR DESCRIPTION
**Pull request by ttodua**
there were incorrect uses of currencies (currency-code) in request methods (instead of currency-id).

fix #21112

### CODE REVIEW

**Comment by carlosmiei** [comment]
@ttodua did you test the impacted methods?

**Comment by carlosmiei** [comment]
@ttodua this broke a lot of tests, so I'm suspicious about this edit 🤔 
image

**Comment by ttodua** [comment]
I have typo, `ie` key instead of `id` in parse currencies. fixed now.

**Comment by ttodua** [comment]
I'll move out this PR from draft once it passes tests, sorry for forgetting this

**Comment by ttodua** [comment]
@carlosmiei PR ready

**Pull request merged**
