### PR TITLE
fix for gateio.fetchFundingRateHistory

### PR DESCRIPTION
**Pull request by samgermain**
Small fix to request['settle'] param

### CODE REVIEW

**Comment by kroitor** [comment]
We will have to add `filterBySymbolSinceLimit` instead of `sortBy` to gate.io's `fetchFundingRateHistory`.

**Comment by kroitor** [comment]
The settle currency can be obtained from the market, i think, which is why we probably should require a symbol for fetchFundingRateHistory.

**Comment by samgermain** [comment]
> The settle currency can be obtained from the market, i think, which is why we probably should require a symbol for fetchFundingRateHistory.

The quote id is not the settleId, so this is assigning something to the wrong parameter

**Comment by kroitor** [comment]
> > The settle currency can be obtained from the market, i think, which is why we probably should require a symbol for fetchFundingRateHistory.
> 
> The quote id is not the settleId, so previously this was assigning something to the wrong parameter

Yeah, i accidentally posted here, was actually commenting on this other PR: https://github.com/ccxt/ccxt/pull/10383#discussion_r744113384 – we will need a symbol to get the settle currency there.

**Pull request merged**
