### PR TITLE
revert - remove fetch last prices

### PR DESCRIPTION
**Pull request by ttodua**
Revert "remove non-unified fetchLastPrices method"

This reverts commit 55d958ae074bd7654a3abf25a60aad2e9ed7fd9c.

### CODE REVIEW

**Comment by carlosmiei** [comment]
@ttodua Carlo wants at least 2 implementations before restoring this method iirc

**Comment by ttodua** [comment]
@carlosmiei 
I've added HTX- t had 3 endpoints (separate for each market type) specifically dedicated that goal.

as the endpoints were many, i'm not attaching the logs, instead you might look check:
to quickly see:
```
    e = new htx(); // binance
    e.options.subType= 'linear';
    e.options.defaultType= 'swap';
    const a1 = await e.fetchLastPrices ();

    e.options.subType= 'linear';
    e.options.defaultType= 'future';
    const a2 = await e.fetchLastPrices ();

    e.options.subType= 'inverse';
    e.options.defaultType= 'future';
    const a3 = await e.fetchLastPrices ();

    e.options.subType= 'inverse';
    e.options.defaultType= 'swap';
    const a4 = await e.fetchLastPrices ();
    debugger;
```

depending an exchange, some of them might have dedicated group of answers depending subtype, (i.e. binance has grouped by `linear` vs `inverse`) while others (i.e. HTX) has grouped of  `inverse swap -vs-  inverse future -vs- linear swap&future`

**Comment by ttodua** [comment]
I'm adding tests for them now

**Comment by ttodua** [comment]
@carlosmiei PR ready

**Pull request merged**
