### PR TITLE
binance: update apis

### PR DESCRIPTION
**Pull request by luzihang123**
### Overview
This Pull Request addresses inaccuracies in our current implementation of several Binance Portfolio Margin API endpoints. The issue was identified as an incorrect prefix in the endpoint URLs. The correction involves aligning the endpoints with the official Binance Portfolio Margin API documentation (https://binance-docs.github.io/apidocs/pm/en/).

### Corrections Made
The following API endpoints have been corrected:

1. **Repay Futures Switch (GET)**:
   - Previous: `portfolio/repay-futures-switch`
   - Corrected: `repay-futures-switch`
   
2. **Repay Futures Switch (POST)**:
   - Previous: `portfolio/repay-futures-switch`
   - Corrected: `repay-futures-switch`

3. **Repay Futures Negative Balance (POST)**:
   - Previous: `portfolio/repay-futures-negative-balance`
   - Corrected: `repay-futures-negative-balance`

### Reason for Changes
The initial implementation included an unnecessary `portfolio` prefix in the API endpoints. This discrepancy was causing issues in API calls, leading to failures in proper communication with the Binance PM services. Aligning the endpoints with the official documentation ensures accurate and successful API requests.

I appreciate your review and any further input on this Pull Request.

### CODE REVIEW

**Review by sc0Vu — COMMENTED** [review]
The js, python and php was produced automatically, please only push `ts/src/binance.ts` file.

**Comment by luzihang123** [comment]
> The js, python and php was produced automatically, please only push `ts/src/binance.ts` file.

ok

**Comment by carlosmiei** [comment]
Hello @luzihang123, thanks a lot for fixing it we will take a look asap.

Don't worry about the generated files, we will handle it.

**Comment by carlosmiei** [comment]
[🤖 TestsManager 🤖  Id: 655f219f303ff6da383e53d8]
 ```

Testing { exchanges: ["binance", "binance"], symbol: "all", debugKeys: { '--warnings': false, '--info': false }, langKeys: { '--ts': false, '--js': false, '--php': false, '--python': false, '--python-async': true, '--php-async': false }, exchangeSpecificFlags: { '--sandbox': false, '--verbose': false, '--private': false, '--privateOnly': true, '--info': false }, maxConcurrency: 5 } (run-tests.js:389)
[50%] Tested binance OK (testExchange @ run-tests.js:303)
[100%] Tested binance OK (testExchange @ run-tests.js:303)
All done, 2 succeeded (run-tests.js:410)


```

**Comment by carlosmiei** [comment]
[🤖 TestsManager 🤖  Id: 655f223a303ff6da383e53d9]
 ```

Testing { exchanges: ["binance"], symbol: "all", debugKeys: { '--warnings': false, '--info': false }, langKeys: { '--ts': false, '--js': false, '--php': false, '--python': false, '--python-async': true, '--php-async': false }, exchangeSpecificFlags: { '--sandbox': false, '--verbose': false, '--private': false, '--privateOnly': true, '--info': false }, maxConcurrency: 5 } (run-tests.js:389)
[100%] Tested binance OK (testExchange @ run-tests.js:303)
All done, 1 succeeded (run-tests.js:410)


```

**Comment by carlosmiei** [comment]
[🤖 TestsManager 🤖  Id: 655f223c303ff6da383e53da]
 ```

Testing { exchanges: ["binance"], symbol: "all", debugKeys: { '--warnings': false, '--info': false }, langKeys: { '--ts': false, '--js': false, '--php': false, '--python': false, '--python-async': true, '--php-async': false }, exchangeSpecificFlags: { '--sandbox': false, '--verbose': false, '--private': false, '--privateOnly': true, '--info': false }, maxConcurrency: 5 } (run-tests.js:389)
[100%] Tested binance OK (testExchange @ run-tests.js:303)
All done, 1 succeeded (run-tests.js:410)


```

**Pull request merged**
