### PR TITLE
kucoin: handleErrors: InsufficientFunds, OrderNotFound

### PR DESCRIPTION
**Pull request by mkutny**
@kornrunner , @wannesdemaeght , @hippylover , @gre , @marcvdm ,
I see you, guys did contributions to this file.

Have you happened to have some trades/funds on kucoin? If you do you can help me with making kucoin's error handling a little bit more robust.

What I do is run this exchange through a test suite which tries to trigger error responses and checks that for every error response an appropriate exception is thrown by ccxt.

One of the checks is to cancel an order which surely does not exist and ensure that `OrderNotFound` is thrown.
So I try `cancelOrder (1)`, `cancelOrder ('1')`, `cancelOrder ('a')` and for all that kucoin responds with:
```
{   success:  true,
       code: "OK",
        msg: "Operation succeeded.",
  timestamp:  1517487048613,
       data:  null                   }
```
while I'd expect `success: false` indeed.

So the question is: what it responds with if you cancel an existing order? If it fills `data` with the order id (instead of `null` which is returned currently) then we could rely on this property to check for order existence.

### CODE REVIEW

**Comment by mkutny** [comment]
It wants braces if I use comments after `if`?

**Comment by kroitor** [comment]
> It wants braces if I use comments after if?

Oh, no, it's a little more complicated. Here's what happens... Python uses indentation instead of brackets for code blocks, you probably already know this. Now, if you imagine how a line-to-line transpiler works with code block brackets, with python it has to strip the opening and the closing bracket. However, if you follow it further, after deleting the bracket there remains a space + comment, and it breaks the indentation. 

So, what we can do in Python is:
- either strip the entire line containing the closing bracket, deleting the comment as well (bad, because the comment won't arrive to Python version then)
- don't label the closing brackets at all and rely on the editor/ide, as most of modern editors show an image similar to this:
  screen shot 2018-02-01 at 15 29 49

What would you suggest?

**Comment by mkutny** [comment]
The issue is that in js it is:
```javascript
if (cond) // comment
    op;
```

and it gets transpiled as (note missing semicolon):
```python
if (cond) // without
    op;
```

**Comment by wannesdemaeght** [comment]
Created and cancelled an order:

```
C:\Trader\Logic>node Test.js
                                           Loading Gdax
                                          Loading Bittrex
                                          Loading Binance
                                          Loading Kucoin
                                          Loading Kraken
{ info:
   { success: true,
     code: 'OK',
     msg: 'OK',
     timestamp: 1517488796652,
     data: { orderOid: '5a730a9cfb4a171fd7d098cf' } },
  id: '5a730a9cfb4a171fd7d098cf' }
^C
C:\Trader\Logic>node Test.js
                                           Loading Gdax
                                          Loading Bittrex
                                          Loading Binance
                                          Loading Kucoin
                                          Loading Kraken
(node:8568) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error:
kucoin cancelOrder requires type (BUY or SELL) param
(node:8568) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future
, promise rejections that are not handled will terminate the Node.js process with a non-zero exit co
de.
^C
C:\Trader\Logic>node Test.js
                                           Loading Gdax
                                          Loading Bittrex
                                          Loading Binance
                                          Loading Kucoin
                                          Loading Kraken
{ success: true,
  code: 'OK',
  msg: 'Operation succeeded.',
  timestamp: 1517488964064,
  data: null }

```

**Comment by wannesdemaeght** [comment]
2 things learned: 
cancelOrder needs type parameter, and the response can not be trusted.

**Comment by kroitor** [comment]
@mkutny 

> and it gets transpiled as (note missing semicolon)

will add a rule for that to the transpiler shortly

**Comment by mkutny** [comment]
@wannesdemaeght , thanks a lot )

Can also try to cancel closed (e.g. fullfilled) order? Just to be sure.

**Comment by wannesdemaeght** [comment]
Tested with an orderID that was filled yesterday, same response.

**Comment by mkutny** [comment]
@wannesdemaeght , thanks!

**Comment by wannesdemaeght** [comment]
No problem.
Sorry it wasn't much use.
Their API needs some TLC on their end.

**Comment by mkutny** [comment]
@kroitor , can't test against null?

**Comment by kroitor** [comment]
@mkutny yeah, Python makes no distinction between `null` / `undefined`, that value will be `None`, so have to check `if (!order)` instead...

**Comment by mkutny** [comment]
No such linting rule for this.

**Comment by kroitor** [comment]
> No such linting rule for this.

Ouch. Well, I can make a special-case transpile-time warning for this.

**Comment by mkutny** [comment]
BTW, because of all these issues above forgot to ask.

There is an obsolete `request` method still there. I'd remove it but while resolving #997 you added one more error check in it **after** a response has been checked by handleErrors. Looks to me like it was done for the debugging purposes, just want to ensure.

**Comment by kroitor** [comment]
> Looks to me like it was done for the debugging purposes, just want to ensure.

Oh, no, actually, it was a workaround for python handle_errors callchain, but it's obsolete now, and we can remove it and yes, remove the request and get all code back into the handleErrors, where it belongs. Let me know if you want to clean it up, or if you want me to do it.

**Comment by kornrunner** [comment]
@mkutny sorry, didn't do any trading with this one yet, but will let you know if I find anything once I do

**Pull request merged**
