### PR TITLE
new exchange: coinex

### PR DESCRIPTION
**Pull request by Deathamns**
Incomplete. If someone wants to finish it, go for it.
Private APIs probably don't even work (I've only tried to implement them from examples found in the docs, but the docs aren't very clear).

#948

### CODE REVIEW

**Comment by kroitor** [comment]
Thanks a lot for your effort! I hope to get working on it asap.

**Comment by Deathamns** [comment]
If I decide to do another from [here](https://github.com/ccxt/ccxt/issues?q=is%3Aissue+is%3Aopen+%22New+Exchange%22+label%3Aenhancement), which one should I pick that you're not working on? Because I see that you were doing something with Deribit...

**Comment by kroitor** [comment]
@Deathamns yes, I'm working on Deribit, but I only have their public API and balance for now, no private API yet. If you want, I can upload it and you can carry on from there. Or you can choose whatever other exchange from that list, if you want to take a separate task. Let me know if you want me to upload deribit in its current version: https://gist.github.com/kroitor/e9eb37314334c7380bae25cf7953caad

**Comment by Deathamns** [comment]
No need, I'll start a new one.

**Comment by Deathamns** [comment]
I didn't really close it, just pushed to the wrong branch after rebasing...

**Pull request closed without merging**
