### PR TITLE
Add Okex Exchange V3

### PR DESCRIPTION
**Pull request by ericjjj**

### CODE REVIEW

**Comment by ericjjj** [comment]
In fact, I encountered network problems during development(in China, there is a firewall). I want to share my solution with others.

### 1

Suppose you have started shadowsocks, and the port is 1080.

```
$ brew install
$ polipo socksParentProxy=localhost:1080
```

### 2

``` js
const ccxt = require('../ccxt/ccxt.js');
const HttpsProxyAgent = require('https-proxy-agent')

const request = require('request');
const proxy = 'http://localhost:8123' // HTTP/HTTPS proxy to connect to
const agent = new HttpsProxyAgent(proxy)

const fetch = require('node-fetch')
const yourImplementationOfFetchInterface = function(url, options) {
    return fetch(url, Object.assign({}, options, { agent: agent }))
}

let binance = new ccxt.binance({
    apiKey: '',
    secret: '',
    verbose:true,
    fetchImplementation: yourImplementationOfFetchInterface
})
```

**Comment by yurenji** [comment]
@kroitor is there an estimated date to merge this PR ?

**Comment by kuskyfei** [comment]
> _No description provided._


> In fact, I encountered network problems during development(in China, there is a firewall). I want to share my solution with others.
> 
> ### 1
> Suppose you have started shadowsocks, and the port is 1080.
> 
> ```
> $ brew install
> $ polipo socksParentProxy=localhost:1080
> ```
> ### 2
> ```js
> const ccxt = require('../ccxt/ccxt.js');
> const HttpsProxyAgent = require('https-proxy-agent')
> 
> const proxy = 'http://localhost:8123' // HTTP/HTTPS proxy to connect to
> const agent = new HttpsProxyAgent(proxy)
> 
> const fetch = require('node-fetch')
> const yourImplementationOfFetchInterface = function(url, options) {
>     return fetch(url, Object.assign({}, options, { agent: agent }))
> }
> 
> let okex3 = new ccxt.okex3({
>     apiKey: '',
>     secret: '',
>     password: '',
>     verbose:true,
>     fetchImplementation: yourImplementationOfFetchInterface
> })
> ```
It's for nodejs.Is the python  ready?

**Comment by sushiparlour** [comment]
@kroitor - wondering if there are plans to merge this with the existing branch?

**Comment by imikay** [comment]
Other language support is transpiled from the js source,  so for those who can't wait to try the new v3 API in other language, you can clone @ericjjj 's branch and transpile the whole code. Here are the instructions:

`git clone https://github.com/ericjjj/ccxt.git`
`cd ccxt`
`git checkout okex_v3`
`npm install`
`npm run build`

After everyting is done, 

`okex = cccxt.okex3()`

Though Python version needs a little tweak: 
WX20190408-181419@2x
WX20190408-181446@2x

hmac encrypting needs bytes encoded, and sign nonce needs to be an int.

I just tested the on the wallet API. 

For the lazy ones like me, you can checkout my repo: https://github.com/imikay/ccxt_okexv3

Here are the changes I made:
https://github.com/imikay/ccxt_okexv3/blob/master/python/ccxt/okex3.py#L421-L436

Thanks.

**Comment by kroitor** [comment]
@imikay 

Thx!

> Though Python version needs a little tweak:

i've just added an edit to it, so the tweak is not necessary anymore.

**Comment by kroitor** [comment]
@sushiparlour yes, of course, i hope to get it done shortly after finishing the testing on our side, didn't have the time to do it right yet, will let you know of my progress.

**Comment by sushiparlour** [comment]
> @sushiparlour yes, of course, i hope to get it done shortly after finishing the testing on our side, didn't have the time to do it right yet, will let you know of my progress. It still needs the edits and testing to avoid the issues with encodings and other stuff similar to the above.

Wondering if it is close? Would prefer to work with the main branch if not I might just go with imikay's version for now. Thanks.

**Comment by ericjjj** [comment]
@kroitor How long can this pr be merged? Almost two months passed😂

**Comment by kroitor** [comment]
@ericjjj terribly sorry for the delay, we'll merge okex v3 within a week or maybe even less. Thx for your patience!

**Comment by yurenji** [comment]
any update?

**Comment by kroitor** [comment]
@yurenji almost there...

**Pull request merged**
