### PR TITLE
Add markets for bittrex

### PR DESCRIPTION
**Pull request by maxxpnz**
I added markets because bittrex .fetch_order_book() does not work.

### CODE REVIEW

**Comment by kroitor** [comment]
Hi! 

Sorry, but Bittrex is already fetching markets from their endpoint and there's no need to hardcode them like that. 

Did you read the manual on how to work with [markets](https://github.com/ccxt/ccxt/wiki/Manual#markets)?

Also this: https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md

Can you elaborate more on the purpose of this PR?

**Comment by maxxpnz** [comment]
I added markets because bittrex .fetch_order_book() does not work.
But bittrex.fetch_trades() work for the same symbol.

**Comment by kroitor** [comment]
Can you show your code?

**Comment by maxxpnz** [comment]
market = ccxt.bittrex()
orders = market.fetch_order_book('USDT-BTC') # This works good
trades = market.fetch_trades('USDT-BTC')         # This does not work:

File "C:\Python27\lib\site-packages\ccxt\bittrex.py", line 259, in fetch_trades
    'market': market['id'],
TypeError: string indices must be integers, not str

**Comment by kroitor** [comment]
@maxxpnz 

try this to see the list of supported symbols:

```Python
bittrex = ccxt.bittrex()
bittrex.load_markets()
print(bittrex.symbols)
```

Also, see this example: https://github.com/ccxt/ccxt/blob/master/examples/py/symbols.py
You can run the above example by typing `python examples/py/symbols.py bittrex`. It will output a table like this:

screen shot 2017-11-01 at 13 26 33

↑ As you see, market id != market symbol.

Read more about it here, **very carefully**: https://github.com/ccxt/ccxt/wiki/Manual#symbols-and-market-ids

**Comment by maxxpnz** [comment]
Ok, thanks!

I think that it is not good that USD has two names: USD and USDT, depending on market.

**Comment by kroitor** [comment]
@maxxpnz , see here: https://github.com/ccxt/ccxt/issues/302#issuecomment-335895181

**Pull request closed without merging**
