### PR TITLE
updates were made to bit2c exchange API that broke some methods.

### PR DESCRIPTION
**Pull request by JacobHanouna**
updated 'api' endpoints.
updated 'fetch_balance' to use new endpoint

### CODE REVIEW

**Comment by kroitor** [comment]
Hi) First of, thx for your contribution! However, we should not submit edits to derived python classes, because all derived exchange classes are transpiled from a common codebase and python files will be overwritten upon build: 

- https://github.com/ccxt/ccxt/pull/2528/files#diff-dc147cf6cfcfd557a0e065631dd12482R3
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

**Comment by kroitor** [comment]
@JacobHanouna can you please move the edits to the js-file?

**Comment by JacobHanouna** [comment]
changes were reverted and moved to js.

never worked with js so didn't know how to check that the code didn't got errors in the move process

**Comment by kroitor** [comment]
@JacobHanouna awesome! Thanks so much! No worries, will merge shortly!

**Comment by kroitor** [comment]
@JacobHanouna P.S. plz read this for future: https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#derived-exchange-classes. Hope to see more from you! Thanks again! )

**Comment by JacobHanouna** [comment]
yes I just read it! actually it is a nice idea.

anyway I will try to work on this exchange a bit more because more had change/missing
I am new to the project so still need to understand how it written

**Comment by kroitor** [comment]
@arielorvits exactly, there were also a few unnecessary \+ signs and padding issues (obviously, copypasted), cleaned it up.

**Pull request merged**
