### PR TITLE
fix(gate): php parseOrder - fix 

### PR DESCRIPTION
**Pull request by samgermain**
fix error:

```php
PHP Fatal error:  Uncaught TypeError: ccxt\async\Exchange::safe_number(): Argument #1 ($obj) must be of type array, null given
```

fixes: #17664

### CODE REVIEW

**Comment by carlosmiei** [comment]
LGTM

```
 ph gate createOrder "LTC/USDT" limit buy 0.15 50
PHP v8.2.1
CCXT version :4.0.48
gate->createOrder(LTC/USDT, limit, buy, 0.15, 50)
Array
(
    [id] => 377061954804
    [clientOrderId] => apiv4
    [timestamp] => 1691053160150
    [datetime] => 2023-08-03T08:59:20.150Z
    [lastTradeTimestamp] => 1691053160150
    [status] => open
    [symbol] => LTC/USDT
    [type] => limit
    [timeInForce] => GTC
    [postOnly] => 
    [reduceOnly] => 
    [side] => buy
    [price] => 50
    [stopPrice] => 
    [triggerPrice] => 
    [average] => 
    [amount] => 0.15
    [cost] => 0
    [filled] => 0
    [remaining] => 0.15
    [fee] => 
    [fees] => Array
        (
        )

    [trades] => Array
        (
        )

    [info] => Array
        (
            [id] => 377061954804
            [text] => apiv4
            [amend_text] => -
            [create_time] => 1691053160
            [update_time] => 1691053160
            [create_time_ms] => 1691053160150
            [update_time_ms] => 1691053160150
            [status] => open
            [currency_pair] => LTC_USDT
            [type] => limit
            [account] => spot
            [side] => buy
            [amount] => 0.15
            [price] => 50
            [biz_info] => ch:ccxt
            [time_in_force] => gtc
            [iceberg] => 0
            [left] => 0.15
            [fill_price] => 0
            [filled_total] => 0
            [fee] => 0
            [fee_currency] => LTC
            [point_fee] => 0
            [gt_fee] => 0
            [gt_maker_fee] => 0
            [gt_taker_fee] => 0
            [gt_discount] => 
            [rebated_fee] => 0
            [rebated_fee_currency] => USDT
            [finish_as] => open
        )

    [lastUpdateTimestamp] => 
    [takeProfitPrice] => 
    [stopLossPrice] => 
)
```

**Review by carlosmiei — APPROVED** [review]

**Comment by guifel** [comment]
This PR breaks the parser. In JS, before it was evaluating to undefined by default causing the not enter the if statement `if (put) {` below.
Now the filled amount always shows zero even when orders are filled.

**Comment by carlosmiei** [comment]
> 

@guifel thanks for letting us know, we will reevaluate (cc @samgermain )

**Comment by samgermain** [comment]
> This PR breaks the parser. By default in JS `put` was evaluating to undefined now it changed to `{}` which cause `if (put) {..}` at line 4041 to be true. This causes the filled amount always be zero even when orders are filled.

Sorry about that https://github.com/ccxt/ccxt/pull/18866 fixes the error

Thanks for letting us know

**Pull request merged**
