### PR TITLE
Bitmex: Add fetchMyTrades

### PR DESCRIPTION
**Pull request by milesalex**

### CODE REVIEW

**Comment by kroitor** [comment]
Because their `privateGetExecutionTradeHistory` endpoint returns this structure:

```
[
  {
    "execID": "string",
    "orderID": "string",
    "clOrdID": "string",
    "clOrdLinkID": "string",
    "account": 0,
    "symbol": "string",
    "side": "string",
    "lastQty": 0,
    "lastPx": 0,
    "underlyingLastPx": 0,
    "lastMkt": "string",
    "lastLiquidityInd": "string",
    "simpleOrderQty": 0,
    "orderQty": 0,
    "price": 0,
    "displayQty": 0,
    "stopPx": 0,
    "pegOffsetValue": 0,
    "pegPriceType": "string",
    "currency": "string",
    "settlCurrency": "string",
    "execType": "string",
    "ordType": "string",
    "timeInForce": "string",
    "execInst": "string",
    "contingencyType": "string",
    "exDestination": "string",
    "ordStatus": "string",
    "triggered": "string",
    "workingIndicator": true,
    "ordRejReason": "string",
    "simpleLeavesQty": 0,
    "leavesQty": 0,
    "simpleCumQty": 0,
    "cumQty": 0,
    "avgPx": 0,
    "commission": 0,
    "tradePublishIndicator": "string",
    "multiLegReportingType": "string",
    "text": "string",
    "trdMatchID": "string",
    "execCost": 0,
    "execComm": 0,
    "homeNotional": 0,
    "foreignNotional": 0,
    "transactTime": "2018-11-30T21:03:23.393Z",
    "timestamp": "2018-11-30T21:03:23.393Z"
  }
]
```

... which is different from the public trade structure, we also have to make sure that those private trades are properly parsed in `parseTrade`: https://github.com/ccxt/ccxt/pull/4256/files#diff-c23b6c3f281ff38df587025321e40445R405

Namely, there's no `size` there, and there's a few other differences as well. Would you want to give it a try, or do you want me to fix it?

**Comment by milesalex** [comment]
@kroitor I'll look into it!

**Comment by milesalex** [comment]
The other option is to use `fetchTransactions()` because of there's only one currency in this response

```js

{
    transactID: 'ef5b9e78-3525-2c98-d037-166e385bdddc',
    account: 54495,
    currency: 'XBt',
    transactType: 'RealisedPNL',
    amount: 4982172,
    fee: 0,
    transactStatus: 'Completed',
    address: 'XBTUSD',
    tx: '23c7b523-8c10-b88b-72aa-9ce22b74cc00',
    text: '',
    transactTime: '2018-10-02T12:00:00.000Z',
    walletBalance: 4421394518,
    marginBalance: null,
    timestamp: '2018-10-02T12:00:00.869Z'
}
```

**Comment by kroitor** [comment]
> I'm actually using the wrong endpoint. We need to be using privateGetUserWalletHistory()

I think, the wallet history is something we should wrap into a `fetchLedger` call, we are in the process of designing the datastructure for it now. However, I didn't quite understand, the following: we can't really use privateGetUserWalletHistory for `fetchMyTrades` in bitmex, because that other endpoint is closer to `fetchLedger`, so the question is what shall we do with the `fetchMyTrades` ?

> What's the status with the fetchLedger PR?

I'm going to spend a few more days on reviewing the exchanges APIs for the *ledger-type* calls to come up with a unified data structure for that, and from there, I think we'll start merging the ledger functionality, hopefully, this week.

> The other option is to use fetchTransactions() because of there's only one currency in this response

This sentence I didn't quite understand, can you clarify, please, I mean, use `fetchTransactions` as the other option instead of what / for what? )

**Comment by milesalex** [comment]
>  we can't really use privateGetUserWalletHistory for fetchMyTrades in bitmex, because that other endpoint is closer to fetchLedger, so the question is what shall we do with the fetchMyTrades ?

I think we should set `fetchMyTrades()` to be `false` because I don't think they have exactly this endpoint. They have `fetchClosedOrders()` but that wasn't returning the exact data I need.

>  think we'll start merging the ledger functionality, hopefully, this week.

Very excited about this! I'll quickly follow up with a PR for the ones that need it. Coinbase, bitmex, etc.

> This sentence I didn't quite understand, can you clarify, please, I mean, use fetchTransactions as the other option instead of what / for what? )

You can ignore this. I was saying that we might be able to use `fetchTransactions` because i only see one currency in the wallet response, but in CSV data I have, it's showing other types.

**Comment by milesalex** [comment]
> think we'll start merging the ledger functionality, hopefully, this week

Any luck here? Do you have a branch that I could start working from or help out with some of the grunt work?

**Comment by kroitor** [comment]
> Any luck here? Do you have a branch that I could start working from or help out with some of the grunt work?

Not yet, tbh, I just didn't have the time to add the base code, hope for your understanding. I will do my best to make the initial ledger entry structure, will add the base methods and will upload it before the end of this week, so that we can work on it together from there.

**Comment by kroitor** [comment]
@milesalex once again, pardon for the delay, after a lot of debates we propose to include the following in the Manual:

---------------------------------

Some exchanges provide additional endpoints for fetching the all-in-one ledger history. The ledger is simply the history of changes, actions done by the user or operations that altered balance in any way, that is, the history of movements of all funds from/to all accounts of the user. That includes deposits and withdrawals (funding), amounts incoming and outcoming in result of a trade or an order, including the trading fees, transfers between accounts, rebates, cashbacks and other types of events that are subject to accounting.

```JavaScript
async fetchLedger (code = undefined, since = undefined, limit = undefined, params = {})
```

```JavaScript
{
    id: string,                           // id of the ledger entry
    direction: 'out',                     // or 'in'
    account: 'my-account-id',             // string id of the account if any
    referenceId: 'trade-id',              // the reference type id
    referenceAccount: 'other-account-id', // string id of the opposite account if any
    type: 'trade',                        // string, reference type, see below
    currency: 'BTC',                      // string, unified currency code, 'ETH', 'USDT'...
    amount: 123.45,                       // absolute number
    timestamp: 1544582941735,             // milliseconds since epoch time in UTC
    datetime: "2018-12-12T02:49:01.735Z", // string of timestamp, ISO8601
    fee: {                                // object or or undefined
        cost: 54.321,                     // absolute number
        currency: 'ETH',                  // string, unified currency code, 'ETH', 'USDT'...
    }, 
    info: object,                         // raw ledger entry as is from the exchange
}
```

The type of the ledger entry is the type of the operation associated with it. If the amount comes due to a sell order, then it is associated with a corresponding `trade` type ledger entry, and the referenceId will contain associated trade id (if the exchange in question provides it). If the amount comes out due to a withdrawal, then is is associated with a corresponding transaction.

```
ledgerItemTypes: {
    trade,
    transaction,
    fee,
    rebate,
    cashback,
    referral,
    transfer,
    whatever,
    ...,
}
```

----------------------------

Let me know what you think about it and if we should add or remove anything. I'll then add the base methods for `parseLedgers` where necessary and after that we will start merging these PR hopefully, very soon. Your opinion is welcome!

**Comment by milesalex** [comment]
This is great!! Thank you for putting this together. My feedback will come in short snippets to help me get more context through asking questions.

>The type of the ledger entry is the type of the operation associated with it. If the amount comes due to a sell order, then it is associated with a corresponding trade type ledger entry, and the referenceId will contain associated trade id (if the exchange in question provides it).

```js
{
  currency: 'BTC', // string, unified currency code, 'ETH', 'USDT'...
}
```

Does this data structure assume that the "base" currency is the currency of the account? For example, If I'm selling BTC, which currency am I selling it for? Coinbase specifies this information. Not sure how other exchanges handle this.

@kroitor

**Comment by kroitor** [comment]
> Does this data structure assume that the "base" currency is the currency of the account? 

Nope, not really. This data structure assumes that it represent one row of a ledger – which is either an income to your account or an outcome from your account basically. So every income, outcome and every row in the ledger will have one currency and, also a direction. The currency in the ledger is not a *base* currency, nor a *quote* currency. It's simply a currency and that's it )

> For example, If I'm selling BTC, which currency am I selling it for? 

Ahha, if you're selling, then this is not a ledger – this is an order, which has a different documented structure which accounts for a pair of currencies and all that order stuff, and you use a different set of endpoints (*fetch\*Orders*). An order will be represented twice on the ledger as two separate ledger rows – if you're selling BTC you will have an outcome of BTC and most likely a subsequent or immediate income of another currency – that would be an order or a trade within an order.

> Coinbase specifies this information. 

We should treat it with `parseOrder` or a method alike, then.

> Not sure how other exchanges handle this.

I'm sure we'll work it out ) But thx for the questions, we'll add more clarifications on that aspect to the Manual. More of your questions are welcome ) I hope to get to the base methods for the ledger soon!

**Comment by milesalex** [comment]
> I'm sure we'll work it out ) But thx for the questions, we'll add more clarifications on that aspect to the Manual. More of your questions are welcome ) I hope to get to the base methods for the ledger soon!

Any update for this PR?

**Comment by milesalex** [comment]
@kroitor

**Comment by kroitor** [comment]
@milesalex 

> Any update for this PR?

Yep, will upload the updates to the Manual and to the code before the end of this week and will also upload one reference implementation for `fetchLedger` for Kraken to start with, and we'll begin adding those implementations where available from there.

**Comment by milesalex** [comment]
Any update here?

**Comment by kroitor** [comment]
@milesalex 

> Any update here?

Yay!) We're finally merging the PR for the reference implementation for Kraken today and will start adding missing `fetchLedger` methods everywhere at last, including this PR! Woohoo! )

- https://github.com/ccxt/ccxt/pull/4603

**Comment by milesalex** [comment]
Wooo!! Very excited!

**Comment by kroitor** [comment]
@milesalex thank you so much for your help and patience! Will do our best to merge quicker! )

**Comment by milesalex** [comment]
Happy to help!!

**Pull request merged**
