### PR TITLE
Bithumb createOrder return structure

### PR DESCRIPTION
**Pull request by brandsimon**

### CODE REVIEW

**Comment by brandsimon** [comment]
@kroitor 
Thank you, forgot to run `npm run build`

**Comment by brandsimon** [comment]
@kroitor 
Do you have experience with this exchange?
I created an order, now I am only getting this error:
https://translate.google.de/#view=home&op=translate&sl=auto&tl=en&text=%ED%9A%8C%EC%9B%90%20%EC%9E%90%EC%82%B0%EC%9D%84%20%EA%B0%80%EC%A0%B8%EC%98%AC%EC%88%98%EC%97%86%EC%8A%B5%EB%8B%88%EB%8B%A4.%20%EC%9E%A0%EC%8B%9C%ED%9B%84%20%EC%9D%B4%EC%9A%A9%20%EB%B6%80%ED%83%81%EB%93%9C%EB%A6%BD%EB%8B%88%EB%8B%A4

**Comment by kroitor** [comment]
@brandsimon i am familiar with it, but that doesn't really help me understand these error message – have no idea what it means. If you can provide more info (which method, endpoint) – we can try to make sense of it together using our experience with other Korean exchanges.

**Comment by kroitor** [comment]
This can help, though: https://apidocs.bithumb.com/docs/err_code

**Comment by kroitor** [comment]
Screen Shot 2020-04-23 at 04 48 23

Screen Shot 2020-04-23 at 04 50 04

**Comment by kroitor** [comment]
I know that the above does not shed much light on it... You probably want to address it to their tech support.

**Comment by brandsimon** [comment]
@kroitor 
Yes, it is createOrder (the same parameters worked before for this function, so I dont think it is a precision problem).
Thank you for the link, so for me this sounds like a problem on their side.
This is helpful for me, so I try to find out, if this is a temporary problem and go to bed :D 

Another little question, maybe you know:
I found their docs support fetchOrder and fetchOrders:
https://apidocs.bithumb.com/docs/orders_detail
https://apidocs.bithumb.com/docs/orders

I "implemented" both, but when I call them, they only return
https://translate.google.de/#view=home&op=translate&sl=auto&tl=en&text=%EC%A3%BC%EB%AC%B8%EB%82%B4%EC%97%AD%EC%9D%B4%20%EC%A1%B4%EC%9E%AC%ED%95%98%EC%A7%80%20%EC%95%8A%EC%8A%B5%EB%8B%88%EB%8B%A4

So I think, they dont really support these methods? (This is probably why they are not implemented in ccxt)

Have a good night, whenever this will be for you ;)

**Comment by kroitor** [comment]
> So I think, they dont really support these methods? 

Nope, I think they do have them, `orders` is probably for open orders, and the `orders_detail` is for closed orders. The naming is very confusing though.

> This is probably why they are not implemented in ccxt

No, not really, we just haven't implemented those for Bithumb yet.

**Pull request merged**
