### PR TITLE
Travis: try to prevent log truncation for failed python tests

### PR DESCRIPTION
**Pull request by brandsimon**

### CODE REVIEW

**Comment by brandsimon** [comment]
@kroitor 
This solves the problem:
https://travis-ci.org/ccxt/ccxt/builds/649217291?utm_source=github_status&utm_medium=notification

**Comment by brandsimon** [comment]
Besides, I dont think we should use `sys.excepthook`, but cover the stuff in main() with an try-except block.
If this is something you would merge, I'd do this.

**Comment by brandsimon** [comment]
@kroitor 
You have seen this PR?

**Comment by kroitor** [comment]
@brandsimon yep, thx a lot for your help on it! I'm about to test it and will merge shortly after.

**Pull request merged**
