### PR TITLE
added fetchIndexOHLCV and fetchMarkOHLCV to huobi

### PR DESCRIPTION
**Pull request by samgermain**
Spot just ignores the extra params. It looks like nothing is returned for futures `fetchIndexOHLCV`

-------------------------------------

# SWAP

```
huobi.fetchOHLCV (GRT/USD:GRT)
1637582520000 | 0.89201 | 0.89201 | 0.89201 | 0.89201 |                  0
1637582580000 | 0.89107 | 0.89107 | 0.89107 | 0.89107 | 44.889851526816074
...
1637642460000 | 0.90785 | 0.90785 | 0.90785 | 0.90785 |                  0
1000 objects
479 ms

huobi.fetchMarkOHLCV (GRT/USD:GRT)
1637582520000 | 0.89201 | 0.89201 | 0.89201 | 0.89201 | 0
1637582580000 | 0.89201 | 0.89201 | 0.89108 | 0.89108 | 0
...
1637642460000 | 0.90784 | 0.90784 | 0.90784 | 0.90784 | 0
1000 objects
873 ms

huobi.fetchIndexOHLCV (GRT/USD:GRT)
BadRequest huobiswap has no api endpoint for index kline data
---------------------------------------------------
...

huobi.fetchPremiumIndexOHLCV (GRT/USD:GRT)
1637582520000 |  0.0000495833333333 |  0.0000495833333333 |  0.0000495833333333 |  0.0000495833333333 | 0
1637582580000 |         0.000049375 |         0.000049375 |         0.000049375 |         0.000049375 | 0
...
1637642460000 |  0.0000414583333333 |  0.0000414583333333 |  0.0000414583333333 |  0.0000414583333333 | 0
1000 objects
883 ms
```

------------------------------------------------------------------------------------

# FUTURES

```
huobi.fetchOHLCV (LTC/USD:LTC-211231)
1637582940000 | 217.701 | 217.701 | 217.184 | 217.223 |   87.62916917325441
1637583000000 | 217.244 | 217.244 | 217.244 | 217.244 |  6.3523043214081865
...
1637642880000 | 213.051 | 213.051 | 213.051 | 213.051 |   6.477322331272794
1000 objects
986 ms

huobi.fetchMarkOHLCV (LTC/USD:LTC-211231)
1637582940000 | 217.601 | 217.656 | 217.304 | 217.304 | 0
1637583000000 | 217.277 | 217.277 | 217.244 | 217.244 | 0
...
1637642880000 | 212.973 | 212.973 | 212.973 | 212.973 | 0
1000 objects
880 ms

huobi.fetchIndexOHLCV (LTC/USD:LTC-211231)
[]
0 objects
...

huobi.fetchPremiumIndexOHLCV (LTC/USD:LTC-211231)
BadRequest huobi future has no api endpoint for premiumIndex kline data
---------------------------------------------------
...
```

------------------------------------------------------------------------------------

# SPOT
```
huobi.fetchOHLCV (ZEC/USDT, 1h)
1634043600000 | 112.28 | 116.95 | 112.28 | 116.19 |  9610.134523622166
1634047200000 | 116.19 |    117 |  114.2 | 114.82 |   5092.39912059156
...
1637640000000 | 209.74 | 211.76 |  208.9 | 209.01 |  3033.533751990814
1000 objects
351 ms

huobi.fetchMarkOHLCV (ZEC/USDT, 1h)
1634043600000 | 112.28 | 116.95 | 112.28 | 116.19 |  9610.134523622166
1634047200000 | 116.19 |    117 |  114.2 | 114.82 |   5092.39912059156
...
1637640000000 | 209.74 | 211.76 |  208.9 | 209.01 |  3033.533751990814
1000 objects
340 ms

huobi.fetchIndexOHLCV (ZEC/USDT, 1h)
1634043600000 | 112.28 | 116.95 | 112.28 | 116.19 |  9610.134523622166
1634047200000 | 116.19 |    117 |  114.2 | 114.82 |   5092.39912059156
...
1637640000000 | 209.74 | 211.76 |  208.9 | 209.01 |  3033.533751990814
1000 objects
358 ms

huobi.fetchPremiumIndexOHLCV (ZEC/USDT, 1h)
1634043600000 | 112.28 | 116.95 | 112.28 | 116.19 |  9610.134523622166
1634047200000 | 116.19 |    117 |  114.2 | 114.82 |   5092.39912059156
...
1637640000000 | 209.74 | 211.76 |  208.9 | 208.97 | 3035.2753519908138
1000 objects
932 ms
```

------------------------------------------------------------------------------------

### CODE REVIEW

**Comment by samgermain** [comment]
I tried modifying the sign method, I'm getting this error and tried following it with the debugger, but I'm not really sure what the string is that's undefined

```
[TypeError] Cannot read property 'replace' of undefined

    at implodeParams   js/base/functions/misc.js:97  string = string.replace ('{' + key + '}', params[key])                          
    at sign            js/huobi.js:1738              url = this.implodeParams (this.urls['api'][api], {                              
    at fetch2          js/base/Exchange.js:574       const request = this.sign (path, type, method, params, headers, body)           
    at fetchOHLCV      js/huobi.js:860               const response = await this[method] (this.extend (request, params));            
    at fetchMarkOHLCV  js/huobi.js:888               return await this.fetchOHLCV (symbol, timeframe, since, limit, this.extend (req…
    at async main      examples/js/cli.js:243        const result = await exchange[methodName] (... args)                            

ccxt/node_modules/ololog/build/ololog.js:228
Cannot read property 'replace' of undefined
ccxt/node_modules/ololog/build/ololog.js:228
```

**Comment by kroitor** [comment]
> I tried modifying the sign method, I'm getting this error and tried following it with the debugger, but I'm not really sure what the string is that's undefined

I'm rewriting most of it, and going to replace the existing `sign` method almost entirely.

**Comment by samgermain** [comment]
> > I tried modifying the sign method, I'm getting this error and tried following it with the debugger, but I'm not really sure what the string is that's undefined
> 
> I'm rewriting most of it, and going to replace the existing `sign` method almost entirely.

ok

**Comment by samgermain** [comment]
@kroitor How's progress on Huobi futures coming?

**Comment by kroitor** [comment]
@samgermain will hopefully get it finished this week.

**Pull request merged**
