### PR TITLE
Adding possibility to use http proxies via http settings

### PR DESCRIPTION
**Pull request by quorak**
Unfortunately the current proxy implementation does not support using traditionell Proxies where the request is not added to the url but send in the payload. In order to use `http-proxy-agent` with `node-fetch` we need to make the agent setting accessible though the exchange interface.

This is the most simple solution i cam up with. Open for feedback.

### CODE REVIEW

**Comment by kroitor** [comment]
@quorak thx! We already have that in Python, were missing the same in JS!

**Comment by szmcdull** [comment]
How to use it? Can you provide an example?

**Comment by kroitor** [comment]
@szmcdull which programming language? JavaScript?

**Comment by szmcdull** [comment]
> 
> 
> @szmcdull an example in which programming language? JavaScript?

Javascript and Python

**Comment by kroitor** [comment]
@szmcdull

JavaScript: 

- https://github.com/ccxt/ccxt/issues/6272
- https://github.com/ccxt/ccxt/issues/6989
- https://github.com/ccxt/ccxt/wiki/Install#javascript-proxies
 
Python: 

- https://github.com/ccxt/ccxt/issues/5394
- https://github.com/ccxt/ccxt/issues/358
- https://github.com/ccxt/ccxt/wiki/Install#python-proxies

Let us know if that does not answer your question.

**Comment by szmcdull** [comment]
@kroitor  Thanks. One thing I would note is that `https-proxy-agent` needed to be installed first :)

**Pull request merged**
