### PR TITLE
feat(binance): fix fetchCurrencies return params

### PR DESCRIPTION
**Pull request by cozy-hn**
* add depositmin using depositdust
* fix networkfee

### CODE REVIEW

**Comment by carlosmiei** [comment]
Hello @cozy-hn thanks a lot for fixing it!

**Comment by cozy-hn** [comment]
@carlosmiei 
For OKX, the withdrawMin value inside the limit object should ideally be calculated as withdrawMin + fee.

**Comment by carlosmiei** [comment]
@cozy-hn Usually we don't take the fee into consideration in the min withdraw

**Comment by cozy-hn** [comment]
@carlosmiei  But the minimum withdrawal amounts returned by Binance and Bybit api are consistent with the numbers shown on the actual withdrawal page. However, OKX return a minimum withdrawal of 3, but when considering the fee of 3, the actual amount displayed on the site becomes 6. This inconsistency is not aligned with standard practices.

**Pull request merged**
