### PR TITLE
new exchange VALR

### PR DESCRIPTION
**Pull request by DelAnt**
New VALR exchange added related to #5320

### CODE REVIEW

**Comment by DelAnt** [comment]
I there anything else I can do to help the review of VALR as a new exchange?

**Comment by carlosmiei** [comment]
@DelAnt We will try to review and test it soon, thanks for your contribution

**Review by DelAnt — COMMENTED** [review]
Two quick questions. 
1) Do you have any expectation as to when this could be reviewed? 
2) I'm currently working on the PRO version. Should I include it in this branch or keep them seperated for now? I assume it would be better to keep them seperated. Especioally as I've still got lots of work to do for it and I am still working to understand the framework required (I can't see any guide for contributing PRO stuff). So far, I have managed to get the first version of watchTicker and watchBalance working but it will need more refinements.

**Comment by DevinNorgarb** [comment]
@DelAnt Any further progress here?

**Pull request closed without merging**
