### PR TITLE
Update Exchange.js on HttpsProxyAgent usage (the proxy `agent` property)

### PR DESCRIPTION
**Pull request by guotie**
the compare will result in proxy cannot use.

when use HttpsProxyAgent create an agent, the agent.protocol is undefined

### CODE REVIEW

**Comment by kroitor** [comment]
@guotie what's your version of Node.js?

**Comment by guotie** [comment]
v10.16.3

windows

**Comment by kroitor** [comment]
@guotie can you plz share the code you use to instantiate the HttpsProxyAgent?

&#096;&#096;&#096;JavaScript
// your code
&#096;&#096;&#096;

↓

```JavaScript
// your code
```

**Comment by guotie** [comment]
```
        let config = {
            'apiKey': this.accessKey,
            'secret': this.secretKey,
        }
        if (opts.proxy) {
            config.agent = new HttpsProxyAgent((opts.proxy))
        }
        this.ex = new ccxt.huobipro(config)
```

**Comment by kroitor** [comment]
@guotie what is the contents of opts.proxy in your case? We don't need to see the addresses, mostly interested if there are any related fields in that config.

**Comment by guotie** [comment]
opts.proxy is just a url string, in my case, it is `http://127.0.0.1:25378/`

**Comment by kroitor** [comment]
@guotie does it work for you this way:

```JavaScript
        let config = {
            'apiKey': this.accessKey,
            'secret': this.secretKey,
        }
        if (opts.proxy) {
            config.agent = new HttpsProxyAgent({
                'hostname': '127.0.0.1',
                'port': :25378,
                'protocol': 'http:',
            })
        }
        this.ex = new ccxt.huobipro(config)
```

?

**Comment by guotie** [comment]
it doesn't work, agent.protocol is undefined

**Comment by kroitor** [comment]
@guotie even when you define it explicitly like shown in my previous comment?

**Comment by guotie** [comment]
I copy your code to my project, it doesn't work.

**Comment by guotie** [comment]
I have see http-proxy-agent code, it has no protocol varible.
```

function HttpsProxyAgent(opts) {
	if (!(this instanceof HttpsProxyAgent)) return new HttpsProxyAgent(opts);
	if ('string' == typeof opts) opts = url.parse(opts);
	if (!opts)
		throw new Error(
			'an HTTP(S) proxy server `host` and `port` must be specified!'
		);
	debug('creating new HttpsProxyAgent instance: %o', opts);
	Agent.call(this, opts);

	var proxy = Object.assign({}, opts);

	// if `true`, then connect to the proxy server over TLS. defaults to `false`.
	this.secureProxy = proxy.protocol
		? /^https:?$/i.test(proxy.protocol)
		: false;

	// prefer `hostname` over `host`, and set the `port` if needed
	proxy.host = proxy.hostname || proxy.host;
	proxy.port = +proxy.port || (this.secureProxy ? 443 : 80);

	// ALPN is supported by Node.js >= v5.
	// attempt to negotiate http/1.1 for proxy servers that support http/2
	if (this.secureProxy && !('ALPNProtocols' in proxy)) {
		proxy.ALPNProtocols = ['http 1.1'];
	}

	if (proxy.host && proxy.path) {
		// if both a `host` and `path` are specified then it's most likely the
		// result of a `url.parse()` call... we need to remove the `path` portion so
		// that `net.connect()` doesn't attempt to open that as a unix socket file.
		delete proxy.path;
		delete proxy.pathname;
	}

	this.proxy = proxy;
	this.defaultPort = 443;
}
inherits(HttpsProxyAgent, Agent);
```

**Comment by guotie** [comment]
https-proxy-agent instance doesn't has protocol field, this is the code:

```

function HttpsProxyAgent(opts) {
	if (!(this instanceof HttpsProxyAgent)) return new HttpsProxyAgent(opts);
	if ('string' == typeof opts) opts = url.parse(opts);
	if (!opts)
		throw new Error(
			'an HTTP(S) proxy server `host` and `port` must be specified!'
		);
	debug('creating new HttpsProxyAgent instance: %o', opts);
	Agent.call(this, opts);

	var proxy = Object.assign({}, opts);

	// if `true`, then connect to the proxy server over TLS. defaults to `false`.
	this.secureProxy = proxy.protocol
		? /^https:?$/i.test(proxy.protocol)
		: false;

	// prefer `hostname` over `host`, and set the `port` if needed
	proxy.host = proxy.hostname || proxy.host;
	proxy.port = +proxy.port || (this.secureProxy ? 443 : 80);

	// ALPN is supported by Node.js >= v5.
	// attempt to negotiate http/1.1 for proxy servers that support http/2
	if (this.secureProxy && !('ALPNProtocols' in proxy)) {
		proxy.ALPNProtocols = ['http 1.1'];
	}

	if (proxy.host && proxy.path) {
		// if both a `host` and `path` are specified then it's most likely the
		// result of a `url.parse()` call... we need to remove the `path` portion so
		// that `net.connect()` doesn't attempt to open that as a unix socket file.
		delete proxy.path;
		delete proxy.pathname;
	}

	this.proxy = proxy;
	this.defaultPort = 443;
}
inherits(HttpsProxyAgent, Agent);
```


The created instance has proxy field, and proxy may has protocol field if opts has.

**Comment by kroitor** [comment]
Related: https://github.com/ccxt/ccxt/pull/4648

**Pull request merged**
