### PR TITLE
binance accountsByType mapping

### PR DESCRIPTION
**Pull request by ndubel**

### CODE REVIEW

**Comment by frosty00** [comment]
i don't think this is correct, on binance the funding wallet refers to the binance pay wallet so the code should not be main

**Comment by ndubel** [comment]
agree with you, I didn't know that binance has pay wallet, now I see

**Comment by kroitor** [comment]
@ndubel @frosty00 shall we close this?

@ndubel thx for the PRs and help btw! Appreciate it!

**Comment by ndubel** [comment]
yes, close this PR please

**Pull request closed without merging**
