### PR TITLE
setup.py fix

### LINKED ISSUE #430: Python build not working
The python build is not working. Last stable version is 1.9.289

### PR DESCRIPTION
**Pull request by aking7**
#430 
I was unable to make an editable install using `pip install -e`. Fixed reference to `package.json`.

### CODE REVIEW

**Comment by aking7** [comment]
@kroitor Looks like a little deeper insight than mine is needed here.

**Comment by aking7** [comment]
This install works locally, but I'm still having trouble with `npm run build` and `node run-tests` on my machine.

**Comment by kroitor** [comment]
@aking7 sorry, but changing that path to package.json breaks the tox/Travis build (see .travis.yml). We should not change that path, but should just copy the package.json upon install. I'll fix for that. As for the `npm build` and `node run-tests` can you show the output?

**Comment by munrocket** [comment]
Lol i wanted to make same fix.

**Comment by aking7** [comment]
@kroitor Okay sounds good. I'll open a new issue for the build problem.

**Pull request closed without merging**
