### PR TITLE
Create Nebula Exchange js file

### PR DESCRIPTION
**Pull request by fredericramanda**
First commit for Nebula Exchange app.
https://nebula.exchange

### CODE REVIEW

**Comment by FndNur1Labs** [comment]
added possible :+1: 

https://github.com/CatalystCash/Catalyst-Evo/issues/15

**Comment by fredericramanda** [comment]
Hey guys, please review this file.
Thanks from Nebula Team (from Madagascar !!)

**Comment by FndNur1Labs** [comment]
madagaskar welcome @fredericramanda hope you interested our coins :+1:

**Comment by fredericramanda** [comment]
Some partners are whitelisted on Nebula Exchange (lessen rate limit)
With some public end points like fetchOrderBook, if you add { signed: true } as/with parameter, your request rate will not be limited.

**Comment by fredericramanda** [comment]
Travis CI build can't pass because of authentication.

**Comment by fredericramanda** [comment]
WARNING : nebula public api server will be renamed into https://tapi..... instead of https://api. On NOVEMBRE !!!

**Comment by kroitor** [comment]
@fedecaccia thx for the update!

**Comment by An-Net** [comment]
Shutdown

Снимок экрана 2020-07-22 в 13 36 14

**Pull request closed without merging**
