### PR TITLE
Ascendex safeNetwork

### PR DESCRIPTION
**Pull request by Dan-krm**
Attempted the safeNetwork method for ascendex, I'm a bit unsure of what is expected of this method since different exchanges have quite different implementations of it. Let me know of any changes I should make to complete this method correctly.

### CODE REVIEW

**Comment by frosty00** [comment]
@samgermain `.networks` is reversed for the forward mapping of `networkId`s to `networks` so we can't called it `networks` in the options, it would have to be called `reverseNetworks`

**Comment by Dan-krm** [comment]
I did some testing and this method seems to be working properly

**Comment by Dan-krm** [comment]
> 

I made a separate method for it that I deleted. All it does is take the network input from the exchange and output a standardized version so for ascendex the Solana network is 'Solana' and using the safeNetwork method it changes it to SOL. TRC20, ERC20, BEP2 and GO20 are unnecessary to have in the method

**Comment by Dan-krm** [comment]
> > I did some testing and this method seems to be working properly
> 
> Can you post the output?

I made a separate method for it that I deleted. All it does is take the network input from the exchange and output a standardized version so for ascendex the Solana network is 'Solana' and using the safeNetwork method it changes it to SOL. TRC20, ERC20, BEP2 and GO20 are unnecessary to have in the method because the input and output are the same

**Pull request merged**
