### PR TITLE
chore: tsconfig.json - removed duplicate strictNullChecks

### PR DESCRIPTION
**Pull request by samgermain**

### CODE REVIEW

**Comment by carlosmiei** [comment]
This is not needed, the commented value is the default you don't need to explicitly set it

**Comment by samgermain** [comment]
> This is not needed, the commented value is the default you don't need to explicitly set it

It's not needed but it's better, I've uncommented the value a few times and then received a warning, and if you don't fix this warning your value would be overwritten, and this way the description is beside the value, and it's easier to change `noImplicitAny` and `strictNullChecks` at the same time, as opposed to no benefits of leaving things as they are

**Comment by carlosmiei** [comment]
> I've uncommented the value a few times and then received a warning
wdym?

**Comment by samgermain** [comment]
> > I've uncommented the value a few times and then received a warning
> 
> wdym?

I'll do this and then notice there's 2 of them, by now it doesn't happen any more though because I'm aware of it

**Pull request closed without merging**
