### PR TITLE
fetchCurencies

### PR DESCRIPTION
**Pull request by munrocket**
Please decide whether to support fetchCurrencies functionality in the library or remove it totally.

### CODE REVIEW

**Comment by kroitor** [comment]
Well, we are going to support it in the library. Can you please update these three implementations to match the previously merged implementation for Bittrex?

https://github.com/ccxt/ccxt/blob/6d2ca6dc50a274d56a64a42ffe97f7e23aa5f910/js/bittrex.js#L227

That would make it somewhat easier for me to lift fetchCurrencies support to the base class. Thx a lot!

**Comment by munrocket** [comment]
Bittrex and Cryptopia was tested in python.
Also i think dictionary is more suitable as data structure for saving currency 'code'.

**Comment by kroitor** [comment]
> Also i think dictionary is more suitable as data structure for saving currency 'code'.

I agree, but we will index them by code in the base class anyway. Thanks a lot for your effort! I'm in the process of merging this! Respect!

**Comment by munrocket** [comment]
I want to add coinmacketcap fetchCurrencies(). I need fullname of coins. What you think about it?

**Comment by kroitor** [comment]
Sure! And thanks! That would be very cool! As you can see, i'm making some progress merging it alltogether, hope to finally unify it in a day or two.

**Comment by munrocket** [comment]
fetchCurrencies for coinmarketcap added, also i extend loadmarkets for all currencies

**Comment by kroitor** [comment]
Moved to #739

**Pull request closed without merging**
