### PR TITLE
eslint: now switched to json, new rules for 'tests' folder

### PR DESCRIPTION
**Pull request by mkutny**

### CODE REVIEW

**Comment by kroitor** [comment]
@mkutny, what does it want from me? )

screen shot 2018-01-17 at 17 44 43

**Comment by mkutny** [comment]
#### Short answer:
it wants you to remove the blank line 11.

But I'm sure you can guess it without me, so here goes a longer answer.

#### Longer answer:

Ok, the issue is that handling of the "no-empty-lines inside class declaration except class members" transpiler restriction is not trivial.

It's now covered by plenty of rules:
```
    "padded-blocks": ["error", "never"], // disallows blank lines after start and before end of a block
    "lines-between-class-members": "error", // enforces empty lines between functions inside classes
    "no-multiple-empty-lines": ["error", { "max": 1 }], // stylistic one, does not impact transpiler
    "padding-line-between-statements": ["error",
      {"blankLine": "never", "prev":"*", "next": "*" }, // disallows blank lines between statements
      {"blankLine": "always", "prev":"directive", "next": "*" }, // except that one between `'use strict'` and `require`
      {"blankLine": "always", "prev":"*", "next": "cjs-export" }, // except that one between `require` and `module.exports`
    ],
```

Need to mention that we're still missing the rules for various empty line cases like:
```
// won't lead to error
return {
    a,

    b,
}
```

#### Now back to the issue.

That linting error you stumbled upon is actually a side effect (the only one I discovered till now, so I think it's a good compromise) of `padded-blocks` rule.

If you disallow it, the following will be possible, which we don't want:
```
// padded block
return {

    a,
    b,

}
```

I tried to overcome the issue in question by the following exception:
```
{"blankLine": "always", "prev":"class", "next": "*" } // enforce empty line after `class` statement
```
but it didn't work. Maybe you'll be able to somehow force it if you will.

For some reason, these `blankLine` exceptions do not work reliably, as for me.

For example:
```
{"blankLine": "always", "prev":"directive", "next": "*" }, // blank line between `'use strict'` and `require`
{"blankLine": "always", "prev":"directive", "next": "cjs-import" }, // blank line between `'use strict'` and `require`
```
The first one works, the second one not, despite it's more stricter.

#### P.S.
I'm actually tool-neutral. I setup ESLint only because there was empty .eslintrc in the root. If you find ESLint too rigid I'm flexible to switch to whatever alternative you'll be happy with.

**Comment by kroitor** [comment]
> If you find ESLint too rigid I'm flexible to switch to whatever alternative you'll be happy with.

No, it's all fine, I'm just making sense of it step by step, no worries at all. I'm sure we'll find a way to make the linter handle it all for us no matter what ) Thx for the explanation, makes sense. Let's sacrifice the padded block rule until we find a workaround (I'll spend some time digging in this direction).

**Comment by kroitor** [comment]
@mkutny I'd say a more practical solution to this could be to workaround the empty lines in transpiler...

**Pull request merged**
