### PR TITLE
Gemini fetchTransactions

### PR DESCRIPTION
**Pull request by buddylindsey**
This pull request adds in getting transactions for funding on Gemini.

There are 2 issues in the current code PR.

1. I am not getting deposits and withdrawals through separate methods since they aren't available in the Gemini endpoint. Should I do a filter to get only those out?
2. There is a `no-unused-var` linting error for currency in the `fetchTransactions` method because we can't/don't use it in the api. Is there a suggestion to resolve this?

This PR work is based on the work of @lfern in pull request #2355. I checked out his code, and pushed a branch to my own working fork with gemini in place.

There are some hurdles I see in getting this merged.

1. #2355 needs to be merged first as this PR is based on it.
2. However, #2355 is held up by #2397 which seems to have stalled and now has conflicts merge. Per discussion in #1896.
3. Was going to list using `price`, but that was resolved during me writing this.

There is also #2526 and #2610 which adds support for `binance` and `gdax`, respectively.

Looking at the both the gdax and binance PRs they would conflict with #2355 since it is modifing the base `Exchange.js` file. It also isn't mergable from my understanding since `Exchange.py` and `Exchange.php` aren't updated as well. So that is something to note, and probably should be updated after on of the others is merged. They seemed to be based on #2355, but conflicting.

### CODE REVIEW

**Comment by frosty00** [comment]
Didn't see the new conflcts will resolve them now with the github online conflict tool.

Thanks for letting me know :)

**Comment by kroitor** [comment]
> So I could just close that branch.
Oh, noes! ) Please don't close it just yet, if possible, I'm actually merging your branch.

**Comment by buddylindsey** [comment]
@kroitor is there anything i can do to help with this or its dependencies to get this merged?

**Comment by frosty00** [comment]
Cleaned up my changes to #2397 feel free to use or not to use...

**Comment by kroitor** [comment]
@buddylindsey 

> @kroitor is there anything i can do to help with this or its dependencies to get this merged?

I'm a little overwhelmed by the amount of questions and PRs submitted, but I hope to merge this shortly after the promised #2397. I'm very sorry for taking so long. My apologies to you and to @frosty00 , as well as other people who have committed. Will do my best to resolve it as quickly as I can.

**Comment by buddylindsey** [comment]
@frosty00 thanks

@kroitor not a problem just offering to help if there was something I could have done.

**Pull request merged**
