### PR TITLE
Fix python ccxt.okex.fetch_balance()

### PR DESCRIPTION
**Pull request by jballard1991**
I discovered that the python ccxt.okex.fetch_balance() function was not returning balance data correctly. After some tests I discovered that the wrong method was being invoked to pull balance data, okex.privatePostUserInfo() appears to return balance data but infact it does not. I have no clue what it is doing, but okex.privatePostWalletInfo() correctly pulls data in a format in which the parser is able to read, so replacing that function makes fetch_balances work() now.

Cheers

### CODE REVIEW

**Comment by kroitor** [comment]
@jballard1991 please, read this: 

- https://github.com/ccxt/ccxt/pull/3911/files#diff-dfff4864d3f7db44542179d8211df20dR3
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

>  I discovered that the wrong method was being invoked to pull balance data

Can you, pls, elaborate what was wrong with it exactly?

**Comment by jballard1991** [comment]
Sure, sorry. The privatePostUserInfo() always returns zero balance. When switch for privatePostWalletInfo() it actually gets the real balances. I had an issue with a deposit not showing up in my balance using ccxt and tracked it down to this. Now calling ccxt.okex.fet_balance() gives me the account balance instead of all 0.0 for everything.

Thanks

**Comment by kroitor** [comment]
> Sure, sorry. The privatePostUserInfo() always returns zero balance. When switched for privatePostWalletInfo() it actually gets the real balances. I had an issue with a deposit not showing up in my balance using ccxt and tracked it down to this. Now calling ccxt.okex.fet_balance() gives me the account balance instead of all 0.0 for everything.

From what you're saying it looks like you don't understand how okex accounts work (this is also the same for a few other exchanges as well, like hitbtc, for example). So, when you transfer funds to it, the money gets to your wallet, and you can't trade with it. You have to transfer funds from/to your spot or fiat account to actually be able to trade with those funds. So you should poll the userinfo if you want to see your current trading balance, and you should call walletinfo only if you want to see your inactive funds, that are currently not used for trading. This lib is mostly focused on spot trading, so there's very little point in having the balance from non-trading wallet account by default, therefore we default to the trading account, that is userinfo. Again, a few other exchanges work like that, they split the funds and accounts, and fetchBalance always defaults to the active spot trading account (not your wallet account and not your margin trading account). Hope this clarifies it...

**Comment by kroitor** [comment]
Unfortunately, because of the above, I won't merge this PR, because this edit breaks the actual purpose of fetchBalance, sorry for that. But still, your desire to help and your involvement is really appreciated and welcome! We will be happy to see more contributions from you in the future, just make sure to read the guidelines first ;)

**Comment by kroitor** [comment]
@jballard1991 also, because we support all endpoints, you can transfer your funds between accounts with ccxt, explained here: https://github.com/ccxt/ccxt/wiki/Manual#implicit-api-methods

**Comment by jballard1991** [comment]
Thanks for the information, yes this is my first time working with OKEX and I suppose I look a bit silly here. 

Appreciate the project, thanks for dealing with my confusion here.

**Comment by kroitor** [comment]
@jballard1991 no worries, your participation is still very welcome! Thank you as well!

**Pull request closed without merging**
