### PR TITLE
fix(bingx)!: fetchDepositAddress renamed to fetchDepositAddressesByNetwork. fetchDepositAddress reimplemented to return a single deposit address structure

### PR DESCRIPTION
**Pull request by samgermain**
# Testing

```
% py bingx fetchDepositAddress USDT          
Python v3.9.6
CCXT v4.2.39
bingx.fetchDepositAddress(USDT)
{'address': '210bf3a3f628b21bb33a0c861e6fc8cce9e1a171',
 'currency': 'USDT',
 'info': {'address': '210bf3a3f628b21bb33a0c861e6fc8cce9e1a171',
          'coin': 'USDT',
          'coinId': '760',
          'network': 'ERC20',
          'tag': ''},
 'network': 'ERC20',
 'tag': None}
```

```
 % py bingx fetchDepositAddressesByNetwork USDT
Python v3.9.6
CCXT v4.2.39
bingx.fetchDepositAddressesByNetwork(USDT)
{'BEP20': {'address': '210bf3a3f628b21bb33a0c861e6fc8cce9e1a171',
           'currency': 'USDT',
           'info': {'address': '210bf3a3f628b21bb33a0c861e6fc8cce9e1a171',
                    'coin': 'USDT',
                    'coinId': '799',
                    'network': 'BEP20',
                    'tag': ''},
           'network': 'BEP20',
           'tag': None},
 'ERC20': {'address': '210bf3a3f628b21bb33a0c861e6fc8cce9e1a171',
           'currency': 'USDT',
           'info': {'address': '210bf3a3f628b21bb33a0c861e6fc8cce9e1a171',
                    'coin': 'USDT',
                    'coinId': '760',
                    'network': 'ERC20',
                    'tag': ''},
           'network': 'ERC20',
           'tag': None},
 'TRC20': {'address': 'TQhy6Ze3qnYU9ixcsVpjRU6EXk6ab95ykK',
           'currency': 'USDT',
           'info': {'address': 'TQhy6Ze3qnYU9ixcsVpjRU6EXk6ab95ykK',
                    'coin': 'USDT',
                    'coinId': '780',
                    'network': 'TRC20',
                    'tag': ''},
           'network': 'TRC20',
           'tag': None}}
```

```
 % py bingx fetchDepositAddress USDT '{"network": "TRC20"}'
Python v3.9.6
CCXT v4.2.39
bingx.fetchDepositAddress(USDT,{'network': 'TRC20'})
{'address': 'TQhy6Ze3qnYU9ixcsVpjRU6EXk6ab95ykK',
 'currency': 'USDT',
 'info': {'address': 'TQhy6Ze3qnYU9ixcsVpjRU6EXk6ab95ykK',
          'coin': 'USDT',
          'coinId': '780',
          'network': 'TRC20',
          'tag': ''},
 'network': 'TRC20',
 'tag': None}
```

### CODE REVIEW

**Comment by carlosmiei** [comment]
I'm not sure we should be implementing `fetchDepositAddressesByNetwork` because only returns 1 address 
```
 n bingx fetchDepositAddressesByNetwork USDT
Debugger attached.
2024-02-12T14:20:15.811Z
Node.js: v18.18.0
CCXT v4.2.43
bingx.fetchDepositAddressesByNetwork (USDT)
2024-02-12T14:20:23.900Z iteration 0 passed in 3263 ms

{
  TRC20: {
    currency: 'USDT',
    address: 'XX',
    network: 'TRC20',
    info: {
      coinId: '780',
      coin: 'USDT',
      network: 'TRC20',
      address: 'XX',
      tag: ''
    }
  }
}
```

**Comment by samgermain** [comment]
> I'm not sure we should be implementing `fetchDepositAddressesByNetwork` because only returns 1 address
> 
> ```
>  n bingx fetchDepositAddressesByNetwork USDT
> Debugger attached.
> 2024-02-12T14:20:15.811Z
> Node.js: v18.18.0
> CCXT v4.2.43
> bingx.fetchDepositAddressesByNetwork (USDT)
> 2024-02-12T14:20:23.900Z iteration 0 passed in 3263 ms
> 
> {
>   TRC20: {
>     currency: 'USDT',
>     address: 'XX',
>     network: 'TRC20',
>     info: {
>       coinId: '780',
>       coin: 'USDT',
>       network: 'TRC20',
>       address: 'XX',
>       tag: ''
>     }
>   }
> }
> ```

I don't know why that's happening for you. In my test above you can see that 3 addresses are returned

**Comment by carlosmiei** [comment]
> > I'm not sure we should be implementing `fetchDepositAddressesByNetwork` because only returns 1 address
> > ```
> >  n bingx fetchDepositAddressesByNetwork USDT
> > Debugger attached.
> > 2024-02-12T14:20:15.811Z
> > Node.js: v18.18.0
> > CCXT v4.2.43
> > bingx.fetchDepositAddressesByNetwork (USDT)
> > 2024-02-12T14:20:23.900Z iteration 0 passed in 3263 ms
> > 
> > {
> >   TRC20: {
> >     currency: 'USDT',
> >     address: 'XX',
> >     network: 'TRC20',
> >     info: {
> >       coinId: '780',
> >       coin: 'USDT',
> >       network: 'TRC20',
> >       address: 'XX',
> >       tag: ''
> >     }
> >   }
> > }
> > ```
> 
> I don't know why that's happening for you. In my test above you can see that 3 addresses are returned

@samgermain Ok might be something on my end, I will try it again

**Comment by carlosmiei** [comment]
@samgermain I had to create the address first in the WEB UI

**Pull request merged**
