### PR TITLE
useProxy flag in tests 

### PR DESCRIPTION
**Pull request by ttodua**
ability to run tests without proxies

### CODE REVIEW

**Comment by carlosmiei** [comment]
aren't we missing the part of skipping the proxies loading from skip-tests?

**Comment by ttodua** [comment]
> aren't we missing the part of skipping the proxies loading from skip-tests?

the PR includes changed `test.ts` where the proxies are being loaded only if that cliArg is present. do you think the check should also happen at other place?

**Comment by carlosmiei** [comment]
> > aren't we missing the part of skipping the proxies loading from skip-tests?
> 
> the PR includes changed `test.ts` where the proxies are being loaded only if that cliArg is present. do you think the check should also happen at other place?

@ttodua No I was missing it, but I have a question shouldn't we do the opposite? an option to skip proxies loading? most of the time these tests will be running on travis and using proxies

**Comment by ttodua** [comment]
> > > aren't we missing the part of skipping the proxies loading from skip-tests?
> > 
> > 
> > the PR includes changed `test.ts` where the proxies are being loaded only if that cliArg is present. do you think the check should also happen at other place?
> 
> @ttodua No I was missing it, but I have a question shouldn't we do the opposite? an option to skip proxies loading? most of the time these tests will be running on travis and using proxies

in my opinion, proxies are not somewhat inherent part of tests, and it's like optional thing (even though most of the time it's what we need) and by design it seems optionality to me. but as you say, lmk and I'll do it right away.

**Comment by carlosmiei** [comment]
@ttodua I think we can leave it as is then

**Pull request merged**
