### PR TITLE
poloniex deposit

### PR DESCRIPTION
**Pull request by Deathamns**
It automatically creates a new address if none exists for the selected currency.

Note that I used `currencyId` for the `withdraw` method too.

### CODE REVIEW

**Comment by kroitor** [comment]
Hi, thanks for this PR! However, we think it would be better to split this method into two to map each call to one http request explicitly. If you can separate that into two methods, something like deposit () and createDepositAddress () – that would be awesome. The library cannot decide on the order of requests for the user, unfortunately. Thanks! Let us know if you will edit it, please.

**Comment by kroitor** [comment]
This is also related to this PR, which I am merging now: https://github.com/ccxt/ccxt/pull/553

**Comment by Deathamns** [comment]
I can separate it, but do you want me to entirely remove deposit address generation from the `deposit` method or just add an extra `createDepositAddress` and use that?
I included deposit generation too, since I would prefer to immediately get some result instead of writing extra code for it. Some exchanges do this by default. bittrex for example ([getdepositaddress](https://bittrex.com/Home/Api)), so you couldn't even separate it there. I've implemented `[deposit](https://github.com/Deathamns/ccxt/commit/5e7c8e8a65b4c643174a55ca54be0afa460e8930)` for bittrex as well, but that uses multiple requests too (if the deposit address doesn't exist already). Should I change that too before pull request?

**Comment by Deathamns** [comment]
Also, how would `fetchCurencies` help here, if they're not implemented for every exchange?

**Comment by kroitor** [comment]
> I can separate it, but do you want me to entirely remove deposit address generation from the deposit method or just add an extra createDepositAddress and use that?

Well, from what you say on the aspects of practical use, I guess, the latter one.

> I included deposit generation too, since I would prefer to immediately get some result instead of writing extra code for it. Some exchanges do this by default. bittrex for example (getdepositaddress), so you couldn't even separate it there.

We should only do that if the user asked for it. I suggest to make it explicit. Let's think of an option that would make it create a new address, when uses calls the `deposit()` method. 

Maybe we should create the new address only...

```
if (the user did not pass an existing address in the arguments) && (a default address does not exist for that currency yet) {
}
```
? 

What do you think?

Also, no need for .throttle(), it is done automatically inside `fetch()`. Did you try deleting that line? ;)

> I've implemented deposit for bittrex as well, but that uses multiple requests too (if the deposit address doesn't exist already). Should I change that too before pull request?

Most likely, yes, just a partial rewrite for flexibility, with the above in mind. Anyway, we would be happy if you submit it, we can carry on together from there.

**Comment by kroitor** [comment]
> Also, how would fetchCurencies help here, if they're not implemented for every exchange?

It would not help, I'm just putting that here as a related issue, because fetchCurrencies and currencyId are related. Just to note that these implementations might undergo some slight changes, because I'm merging them all together.

**Comment by Deathamns** [comment]
> We should only do that if the user asked for it.

An extra argument is fine by me. However there many cases. For example:
`poloniex` - It won't give you an address, if you don't have one yet. So, you have to create one first with a separate request.
`bittrex` - If you have one it may or may not give it to you right away (sometimes it gives an empty address, but if you query it again, you'll get it). If you don't have one, it will automatically start generating it, but you only get a message that it is in progress, so you have to query the API again to see if it's ready.
`cryptopia` If you don't have one, it will generate one and give it to you in the same request.
Also there are exchanges that provide a parameter for renewing your address, like `bitfinex`. 

So, there could be actions for: create, expect, renew (all applies to the address).
`create`: If the exchange doesn't do it by default, then call the the `createDepositAddress`.
`expect`: Try to give a result immediately. So, if the `createDepositAddress` didn't get a result right away, then wait for it, or in case of `bittrex` query the API again, to make sure that you will get something.
`renew`: Pass a renew parameter if the exchange supports it. 

First of all, wouldn't it better to call it something like `getDepositAddress` or `fetchDepositAddress`, because it actually does that.
How should the signature of the method look like? 
`getDepositAddress(currency, actions = [], params = {})`? Actions empty by default.
Then you could `exchange.getDepositAddress('BTC', ['expect'])`.

> because fetchCurrencies() and currencyId() are related
> I'm merging them all together.

I won't change anything with those then, I'll leave it to you.

**Comment by Deathamns** [comment]
> no need for .throttle(),

I wanted to use it when `enableRateLimit` is disabled, I just missed the condition. Actually, wouldn't be possible an option to force rate limiting only for private APIs?

**Comment by kroitor** [comment]
> So, there could be actions for: create, expect, renew (all applies to the address).

I am all for `create` + `renew`, but I think `expect` is not something we should actually integrate inside the library, but we can do that as a convenience wrapper for Bittrex.

> Wouldn't it better to call it something like getDepositAddress or fetchDepositAddress, because it actually does that. 

Initially the name for `deposit()` method has been chosen to mirror the `withdraw`, but, you're right, we should rename it for clarity. And not only should we rename it, but we should also rework the deposit APIs and enhance them to account for the address generation logic.

> How should the signature of the method look like?

I guess, we need the following:

- `fetchDepositAddress (currency, create = false, renew = false)`: fetches a deposit address or no deposit address if it does not exist yet (maybe, throws an exception in that case). Creates or renews a deposit address for a particular currency, depending on `create` and `renew` flags, waits if needed to return an address (may end up in two calls for Bittrex implementation, but that is undesireable to have it implicit everywhere. We really-really do not want to wait arbitrary time for the user, even if it means more work on behalf of the user. But if it takes a couple of seconds and does no conflict to other calls otherwise, it is affordable to wait for the Bittrex case. This method should return a `{ currency: 'BTC', address: '...', ... , other_fields, ... }` object.

> I wanted to use it when enableRateLimit is disabled, I just missed the condition. 

This is what I am saying, we should remove it from there completely, don't put a conditional for it there. I've set default bitmex nonce to milliseconds (https://github.com/ccxt/ccxt/commit/d5d2742686edd6f8d28d9651fa32a0b3df4836e2), should be no conflict there from now on. So we don't need to do rate limiting if rate-limiter is disabled, obviously. Just let it run and it should work with a milliseconds nonce.

> Actually, wouldn't be possible an option to force rate limiting only for private APIs?

We have a flexible solution that allows setting a "call cost" per each particular endpoint and even single API calls. Disabling the rate limit for a particular call would mean setting the cost to zero. It's the *token bucket* algorithm behind the built-in rate limiter. Not fully documented yet.

**Comment by Deathamns** [comment]
> Initially the name for deposit() method has been chosen to mirror the withdraw, but, you're right, we should rename it for clarity. And not only should we rename it, but we should also rework the deposit APIs and enhance them to account for the address generation logic.

I we can do that, then I would like to step back from my proposals. My main problem was that the `deposit` method didn't give any information why the address was empty, so I didn't know what to do. But if we could add an extra status field (or something) which would explicitly say that the address is ok (I can work with it already), failed (something went wrong, maybe throw), still generating (I have to query again to see if it's ready), or non existent yet (I have to create a new one), then that would be enough for the user to write hist own logic around it. These statuses could be returned from `createDepositAddress` too.

**Comment by Deathamns** [comment]
I've sent a new commit. It has `createDepositAddress` and `fetchDepositAddress`, they both only do what their names implies, they don't try to do more. However, they return an extra `status` field, which helps the user to decide what to do next. If an error occurs, then they will throw.
So the `status` field can be 'ok', 'generating' or 'none'.

Ok, I see, you already merged...

**Comment by kroitor** [comment]
Do you mind if I change `generating` → `pending` ?

**Comment by Deathamns** [comment]
Not at all.

**Comment by kroitor** [comment]
> Can I implement it this way for more exchanges?

Sure! And thanks!

**Pull request merged**
