### PR TITLE
Add ExchangeId type to ccxt.d.ts

### PR DESCRIPTION
**Pull request by HartS**
This allows ccxt to be used with the `noImplicitAny` compiler option in a typescript project, for the following  case:

```
import ccxt from 'ccxt';
const myExchanges: ccxt.ExchangeName[] = ['kraken', 'binance', /*... and so on*/];
myExchanges.forEach((exchangeName: ccxt.ExchangeName): void => {
  const exchange: ccxt.Exchange = new ccxt[exchangeName]();
  // do something
});
```

without an ExchangeName type, we see the following error:
```
TSError: ⨯ Unable to compile TypeScript:
test.ts:4:15 - error TS7053: Element implicitly has an 'any' type because expression of type 'string' can't be used to index type 'typeof import("ccxt")'.
  No index signature with a parameter of type 'string' was found on type 'typeof import("ccxt")'.

4 const exchange: ccxt.Exchange = new ccxt[exchangeName];
                ~~~~~~~~~~~~~~

    at createTSError (/usr/local/lib/node_modules/ts-node/src/index.ts:513:12)
    at reportTSError (/usr/local/lib/node_modules/ts-node/src/index.ts:517:19)
    at getOutput (/usr/local/lib/node_modules/ts-node/src/index.ts:752:36)
    at Object.compile (/usr/local/lib/node_modules/ts-node/src/index.ts:968:32)
    at Module.m._compile (/usr/local/lib/node_modules/ts-node/src/index.ts:1056:42)
    at Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Object.require.extensions.<computed> [as .ts] (/usr/local/lib/node_modules/ts-node/src/index.ts:1059:12)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
 ```

### CODE REVIEW

**Comment by HartS** [comment]
CI build failures look entirely unrelated to this PR:

```
WARN xena (Python 3 Async): (explain @ run-tests.js:191)
	[ExchangeNotAvailable] xena GET https://cors-anywhere.herokuapp.com/https://trading.xena.exchange/api/common/currencies 403 Forbidden See /corsdemo for more info
	xena using proxy ``
	{'type': 'ExchangeNotAvailable', 'num_retries': 0, 'max_retries': 2} xena GET https://trading.xena.exchange/api/common/currencies 403 Forbidden <!DOCTYPE html>
	<!--[if lt IE 7]> <html class="no-js ie6 oldie" lang="en-US"> <![endif]-->
	<!--[if IE 7]>    <html class="no-
	xena using proxy `https://cors-anywhere.herokuapp.com/`
	{'type': 'ExchangeNotAvailable', 'num_retries': 1, 'max_retries': 2} xena GET https://cors-anywhere.herokuapp.com/https://trading.xena.exchange/api/common/currencies 403 Forbidden See /corsdemo for more info
	[ExchangeNotAvailable] xena GET https://cors-anywhere.herokuapp.com/https://trading.xena.exchange/api/common/currencies 403 Forbidden See /corsdemo for more info (explain @ run-tests.js:193)
FAILED coinone (JavaScript): (explain @ run-tests.js:190)
...
FAIL ["coinone"] (run-tests.js:271)
WARN ["bitforex", "bitmax", "bitmart", "btcmarkets", "btctradeua", "btcturk", "buda", "btcalpha", "chilebit", "coinegg", "coinfalcon", "coingi", "coinmate", "coinmarketcap", "coinfloor", "coinspot", "digifinex", "dsx", "eterbase", "exx", "fcoin", "fcoinjp", "equos", "flowbtc", "gemini", "foxbit", "luno", "mercado", "mixcoins", "rightbtc", "surbitcoin", "tidebit", "vaultoro", "vbtc", "xbtce", "xena"] (run-tests.js:272)
All done, 1 failed, 89 succeeded, 36 warnings (run-tests.js:276)
```

**Comment by kroitor** [comment]
@HartS thx for the PR! We will need to edit it a bit, namely, we can't hardcode exchange names, cause we're constantly listing new exchanges and delisting the old ones, and keeping a hardcoded list of names in ~10 ts/js/py/php files across the repo is not the way to go. Instead, we generate all those lists of exchange names in `build/transpile.js` and `build/export-exchanges.js`. That simplifies the maintenance of those lists significantly.

**Comment by HartS** [comment]
Thanks so much for the rework/merge @kroitor !

**Comment by kroitor** [comment]
@HartS appreciate your involvement!

**Pull request merged**
