### PR TITLE
coingi: fetchMarkets: ensure parseJsonResponse is restored

### PR DESCRIPTION
**Pull request by mkutny**

### CODE REVIEW

**Comment by Esc4pism** [comment]
Right now, loadMarkets() for coingi loads the homepage-url instead of the api:

´´´
fetch:
 coingi GET https://coingi.com 
Request:
 {} 
 undefined 

handleRestResponse:
 coingi GET https://coingi.com 200 OK 
Response:
 {}
...
´´´
...followed by the complete homepage/html in the json response

**Comment by kroitor** [comment]
@Esc4pism they don't have an API endpoint for markets, so we scrape them from their website, and it's better than hardcoding. What would you suggest? )

**Comment by Esc4pism** [comment]
I see, the problem seems to be that https://api.coingi.com/current/24hour-rolling-aggregation only returns aggregations from the past 24 hours, but not all pairs. If This is working and intended ill just try to filter out those logs so my log doesnt get too spammed.

**Comment by kroitor** [comment]
> If This is working and intended ill just try to filter out those logs so my log doesnt get too spammed.

Yep, it does work as intended. Let us know if we can help with anything else. Thx!

**Pull request merged**
