### PR TITLE
acx allcoin anxpro bcex bibox safeCurrencyCode 

### PR DESCRIPTION
**Pull request by frosty00**

### CODE REVIEW

**Comment by brandsimon** [comment]
@frosty00 
Was there a bug somewhere (what was it) or are these safeCurrencyCode  just code cleanups?

**Comment by kroitor** [comment]
@brandsimon mostly cleanups and generalizations

**Comment by brandsimon** [comment]
@kroitor 
Fast! ;) Great, thank you! :)

**Comment by kroitor** [comment]
@brandsimon Related: https://github.com/ccxt/ccxt/issues/5461

**Comment by brandsimon** [comment]
@kroitor 
I dont see how the error handling is related to the safeCurrencyCode  changes. Can you please elaborate?

**Comment by kroitor** [comment]
@brandsimon pardon, I confused the two posts. Nvm.

**Pull request merged**
