### PR TITLE
new exchange: ethfinex

### PR DESCRIPTION
**Pull request by frosty00**
Uses the same api as bitfinex. Has a subset of markets ATM but still in beta. I think they are adding more ETH pairs in the future. Some limited testing:

```
>>> len(bitfinex.markets)
105
>>> len(ethfinex.markets)
71
>>> set(bitfinex.markets) - set(ethfinex.markets)
{'IOTA/ETH', 'QTUM/BTC', 'NEO/BTC', 'BCH/ETH', 'LTC/USD', 'ETP/ETH', 'ZEC/USD', 'NEO/USD', 'DASH/USD', 'ETP/USD', 'BTG/USD', 'EOS/BTC', 'RRT/USD', 'DASH/BTC', 'ZEC/BTC', 'XRP/BTC', 'EOS/USD', 'XMR/USD', 'BTG/BTC', 'ETC/USD', 'BTC/EUR', 'BTC/USD', 'EOS/ETH', 'LTC/BTC', 'ETC/BTC', 'XRP/USD', 'XMR/BTC', 'NEO/ETH', 'IOTA/USD', 'IOTA/BTC', 'BCH/BTC', 'ETP/BTC', 'RRT/BTC', 'BCH/USD', 'QTUM/ETH', 'QTUM/USD', 'IOTA/EUR'}
>>> set(ethfinex.markets) - set(bitfinex.markets)
{'NEC/USD', 'NEC/ETH', 'NEC/BTC'}
>>> ethfinex.fetch_order_book('NEC/ETH')
{'bids': [[0.00125, 100.0], [0.00123, 4032.0], [0.00121, 100.0], [0.001202, 2000.0], [0.0012, 10100.0], [0.00115, 100.0], [0.0011, 22100.0], [0.00105, 100.0], [0.001001, 2000.0], [0.001, 52934.51011738], ...
```

### CODE REVIEW

**Comment by frosty00** [comment]
Could you maybe add to the wiki and serialize the picture link to a github url. 

Cheers, 
Frosty

**Comment by frosty00** [comment]
It seems that ethfinex.public_get_tickers() returns all of bitfinex markets, not just the ethfinex ones. 

```
>>> len(ethfinex.public_get_tickers())
105
```

which means

```
  File ".../ccxt/bitfinex.py", line 391, in fetch_tickers
    raise ExchangeError(self.id + ' fetchTickers() failed to recognize symbol ' + id + ' ' + self.json(ticker))
ccxt.base.errors.ExchangeError: ethfinex fetchTickers() failed to recognize symbol BTCUSD

**Comment by kroitor** [comment]
> Could you maybe add to the wiki and serialize the picture link to a github url.

This is done automatically upon the build, I'll add the image link, no worries about that.

**Comment by kroitor** [comment]
> It seems that ethfinex.public_get_tickers() returns all of bitfinex markets, not just the ethfinex ones.

I'll have to test it, can't tell beforehand... afaik, the Ethfinex is a contract-oriented version of Bitfinex, which means they will be mostly trading erc20 over ws (this is what we were planning to do for it)... anyways, I'll get to it shortly and we'll see...

**Pull request merged**
