### PR TITLE
binance add support for fiat to fetchDeposits/fetchWithdrawals

### PR DESCRIPTION
**Pull request by frosty00**

### CODE REVIEW

**Comment by frosty00** [comment]
todo: remove hardcoded fees

**Comment by phips28** [comment]
We also need to add the statuses to deposits:
```
parseTransactionStatusByType (status, type = undefined) {
        const statusesByType = {
            'deposit': {
                '0': 'pending',
                '1': 'ok',
                'Processing': 'pending',
                'Failed': 'failed',
                'Successful': 'ok',
                'Refunding': 'canceled',
                'Refunded': 'canceled',
                'Refund Failed': 'failed',
            },
            'withdrawal': {
                '0': 'pending', // Email Sent
                '1': 'canceled', // Cancelled (different from 1 = ok in deposits)
                '2': 'pending', // Awaiting Approval
                '3': 'failed', // Rejected
                '4': 'pending', // Processing
                '5': 'failed', // Failure
                '6': 'ok', // Completed
                // Fiat
                // Processing, Failed, Successful, Finished, Refunding, Refunded, Refund Failed, Order Partial credit Stopped
                'Processing': 'pending',
                'Failed': 'failed',
                'Successful': 'ok',
                'Refunding': 'canceled',
                'Refunded': 'canceled',
                'Refund Failed': 'failed',
            },
        };
        const statuses = this.safeValue (statusesByType, type, {});
        return this.safeString (statuses, status, status);
}
```

**Comment by phips28** [comment]
PR: https://github.com/ccxt/ccxt/pull/9843

**Comment by kroitor** [comment]
@phips28 thank you!

**Pull request merged**
