### PR TITLE
Add hibtc.com exchange

### PR DESCRIPTION
**Pull request by tssujt**

### CODE REVIEW

**Comment by yuesh** [comment]
is it a joke?

**Comment by yuesh** [comment]
shit code

**Comment by kroitor** [comment]
@yuesh lol, what an original name for an exchange ) on the code – it may be a bit dirty, but, no worries, i'll clean it up before merging anyways, your contributions are welcome as well ;)

Thx for your involvement, @xjw0914!

**Comment by yuesh** [comment]
@kroitor she is my friend,my comments were a joke.

If it confuses you,Please forgive me.

**Comment by kroitor** [comment]
The exchange website does not respond anymore. Let me know if we should reopen this.

**Pull request closed without merging**
