### PR TITLE
therock: fetchTicker: close -> removed

### PR DESCRIPTION
**Pull request by mkutny**

### CODE REVIEW

**Comment by kroitor** [comment]
https://github.com/ccxt/ccxt/commit/d524444e005408f07bdba22c2ac441ef99a8ea51#r27721897

**Comment by mkutny** [comment]
> Looks like we got a problem with close, there are users that rely on it...

Yeah, this change *is* breaking. Well, you know, I'm absolutely fine with breaking changes. If they are intended they are obviously for good. At the same time, they need to be properly communicated.

I just don't know if you reserve minor versions for the good times but if you're flexible with them I think that `npm version minor` instead of `npm version patch` should solve the issue.

> I think, I'm going to restore the close with that name and just document it as "previous close' in the Manual...

I believe this will confuse even more users. Of course, we may always repeat RTFM mantra but this term is **too** confusing. At the same time, if you're going to reserve `close` for the "previous close" you'll need to check all those closes and to split them on `current/previous` manually... And it's not trivial.

For example, when I was processing `therock` I noticed their `close` is a bit weird... And it really is. Compare two tickers: one from 7 a.m., the other one is from just now:
```
{      symbol:   "BTC/EUR",
    timestamp:    1519284741105,
     datetime:   "2018-02-22T07:32:21.105Z",
         high:    9190,
          low:    8300,
          bid:    8730.99,
          ask:    8749.75,
         vwap:    undefined,
         open:    9076.39,
        close:    8500,
         last:    8750.83,
       change:    undefined,
   percentage:    undefined,
      average:    undefined,
   baseVolume:    77.0915,
  quoteVolume:    665543.84,
         info: {          date: "2018-02-22T07:32:21.105Z",
                       fund_id: "BTCEUR",
                           bid:  8730.99,
                           ask:  8749.75,
                          last:  8750.83,
                          open:  9076.39,
                         close:  8500,
                           low:  8300,
                          high:  9190,
                        volume:  665543.84,
                 volume_traded:  77.0915                    } }
```

and

```
{      symbol:   "BTC/EUR",
    timestamp:    1519321413882,
     datetime:   "2018-02-22T17:43:33.882Z",
         high:    9190,
          low:    8300,
          bid:    7933.27,
          ask:    7954.42,
         vwap:    undefined,
         open:    9076.39,
        close:    8500,
        first:    undefined,
         last:    7943.83,
       change:    undefined,
   percentage:    undefined,
      average:    undefined,
   baseVolume:    73.5356,
  quoteVolume:    606867.03,
         info: {          date: "2018-02-22T17:43:33.882Z",
                       fund_id: "BTCEUR",
                           bid:  7933.27,
                           ask:  7954.42,
                          last:  7943.83,
                          open:  9076.39,
                         close:  8500,
                           low:  8300,
                          high:  9190,
                        volume:  606867.03,
                 volume_traded:  73.5356                    } }
```

How do you like this `close`?

**Comment by kroitor** [comment]
> Of course, we may always repeat RTFM mantra but this term is too confusing. At the same time, if you're going to reserve close for the "previous close" you'll need to check all those closes and to split them on current/previous manually... And it's not trivial.

You're right... However, newbies seem to be confused with having Open, High, Low, and not having Close (having Last instead)... Thus, I think, I will add previousClose as previous day close, and will restore close = last (will duplicate the same last price under both names and document it, for convenience). How does that sound to you?

**Comment by mkutny** [comment]
Well, if there is `previousClose` then it's presence effectively eliminates confusion about what `close` is. So there is probably no point in having `last` at all?

**Pull request merged**
