### PR TITLE
Python implementation of OHLCV aggregation method

### PR DESCRIPTION
**Pull request by samholt**
Direct port from: https://github.com/ccxt/ccxt/pull/695/files

( Also is the Websockets WIP (Async) in python, however feel free to exclude this. )

### CODE REVIEW

**Comment by kroitor** [comment]
Tons of thanks!

**Comment by bitsol** [comment]
Any updates on this WebSockets implementation?

**Comment by kroitor** [comment]
@bitsol merging it now, in progress.

**Comment by bitsol** [comment]
Thanks @kroitor!

**Comment by kroitor** [comment]
Ref: #637

**Comment by fuzzyTew** [comment]
It would be great to have the websocket stuff on a separate branch & PR, for others to look at and consider using and contributing to.

**Comment by fuzzyTew** [comment]
I believe I've separated out just the websocket work at https://github.com/fuzzyTew/ccxt/tree/websockets .  Haven't reviewed it to see how much more work is needed.  It at least needs to be ported to javascript.

**Comment by fuzzyTew** [comment]
It looks like samholt copied the python base exchange class, deleted the rest-api methods, and added in websocket-api methods.

I'm thinking it might be more DRY to factor the rest/websocket-api functions out of the exchange base class and put them into differently named utility classes.  Then exchange implementations can include one or more utility classes if they need, or perhaps even query to see if different utility classes exist on their platform to determine what functionality to advertise.  This would make things like generalized tcp streams or platform-specific pusher implementations reasonable in the future.

I found some old chat logs discussing this in a very general way ... is there some chat where ccxt development is discussed?

**Comment by kroitor** [comment]
@fuzzyTew, sure:

[Gitter](https://gitter.im/ccxt-dev/ccxt?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge)

**Comment by kroitor** [comment]
Merged OHLCV functions in #894

**Pull request closed without merging**
