### PR TITLE
Waves.Exchange currencies mapping

### PR DESCRIPTION
**Pull request by ndubel**

### CODE REVIEW

**Comment by blaaaaaaa** [comment]
is it possible to get more symbols right. I get errors for BSV and BNT

**Comment by kroitor** [comment]
@blaaaaaaa sure, will add those mappings shortly.

**Comment by blaaaaaaa** [comment]
also, when submitting order with more decimals than price/amount preciision of the market I get 
ValueError: invalid literal for int() with base 10: '288112312.312312'
is that supposed to be  like that and user land should take care of it to submit the right number of decimals, or does ccxt take care of that. I think it works for most exchanges to submit "more" decimals.

**Comment by kroitor** [comment]
@blaaaaaaa should be handled internally, can you plz share the arguments' values (symbol, type, side, amount, price, params), or the code to reproduce it?

**Comment by blaaaaaaa** [comment]
mkr_ex.create_order("ETH/USDT","limit","sell",0.1,288.1123123123123)
leads to 
Traceback (most recent call last):
  File "C:/Users/admin/IdeaProjects/py/ccxt_trading_bot/ccxt_wavesexchange_maker_bot.py", line 179, in <module>
    main()
  File "C:/Users/admin/IdeaProjects/py/ccxt_trading_bot/ccxt_wavesexchange_maker_bot.py", line 171, in main
    a = wavesexchange_maker_bot.mkr_ex.create_order("ETH/USDT","limit","sell",0.1,288.1123123123123)
  File "C:\Users\admin\IdeaProjects\py\ccxt_trading_bot\venv2\lib\site-packages\ccxt\wavesexchange.py", line 775, in create_order
    price = int(self.price_to_precision(symbol, price))
ValueError: invalid literal for int() with base 10: '288112312.312312'

**Comment by kroitor** [comment]
@blaaaaaaa thank you! Will get this fixed and resolved asap.

**Comment by blaaaaaaa** [comment]
@kroitor you guys are the real heroes here, thank you :)

**Pull request merged**
