### PR TITLE
transpiled precision testing :)

### PR DESCRIPTION
**Pull request by frosty00**
This commit adds precision test transpilling to python and php from the javascript "master" test file. This should be useful in ensuring the behaviour of the precision methods are the same in all languages. I already noticed some slight inconsistencies with the php `decimalToPrecision`:

```
<?php

include_once 'ccxt.php';
use ccxt\Exchange;
use const ccxt\AFTER_DOT;
use const ccxt\NO_PADDING;
use const ccxt\PAD_WITH_ZERO;
use const ccxt\ROUND;
use const ccxt\SIGNIFICANT_DIGITS;
use const ccxt\TRUNCATE;
$desc = 'decimalToPrecision failed with ';

print Exchange::decimalToPrecision('12', ROUND, 5, SIGNIFICANT_DIGITS, PAD_WITH_ZERO);
print "\n";
print Exchange::decimalToPrecision('12.3', ROUND, 5, SIGNIFICANT_DIGITS, PAD_WITH_ZERO);
```
---
```
> 12.000
> 12.3
```

And I'm sure many more little inconsitencies that we haven't spotted exist in other languages. 

This was my first attempt at transpilling using javascript so feel free to make any changes if you think you can make the code better. Oh, and I fixed the indentation in transpile.js - for some reason half the file was indented with an extra four spaces.

Also this makes most of the tests in ExchangeTest.php redundant, and it means that `'./js/test/base/functions/test.number.js'` is now more sensitive to syntax / formatting changes.

Finally, you may want to use a different difftool to github to show my changes to transpile.js better.

### CODE REVIEW

**Comment by frosty00** [comment]
Not sure why the appveyor build failed, test base is working on my end and I haven't made any changes to the base code.

**Comment by frosty00** [comment]
@kornrunner I just learned a little php and it's horrifying. I don't blame you for the behaviour as there are probably just as many (if not more) bugs waiting to found in python and javascript. Rigorous test cases will help iron them out.

**Comment by kroitor** [comment]
Merging this one next )

**Comment by frosty00** [comment]
@kroitor please take a look at https://github.com/ccxt/ccxt/pull/2397/files#diff-c6d18b6c7cb481416538ede931ab2766 and let me know when we can merge

**Comment by kroitor** [comment]
@frosty00 I've pulled your changes with my current version like a week ago (there were some restructuring edits), but didn't have a chance to test and finish the build since then yet. Determined to do that in 24-48 hrs and will let you know, of course. Thx!

**Comment by frosty00** [comment]
Awesome I just removed the indentation changes in transpile.js so you could see it better. Will also try get the builds to complete now.

**Comment by kroitor** [comment]
> Have you already starting building on my original branch?

Yep, I've cleaned it up a bit and generalized it further, hope you'll like it )

**Comment by frosty00** [comment]
Sweet, thanks @kroitor - I think the builds are passing but I can't tell because they seem to have hit errors unrelated to my commits. Once this is pushed I we can merge the bitfinex `decimalToPrecision` and I can start using bitfinex and ethfinex again.

**Comment by frosty00** [comment]
Oops it seems I've got the commits in this PR mixed up with my pythonJSON commits. Perhaps ignore those as I will do that on another branch and just push from your local copy instead. Cheers again,

**Comment by kroitor** [comment]
@frosty00 no worries, will sort it out )

**Comment by frosty00** [comment]
Awesome, can't wait to see the changes to `transpile.js`, although it'll probably be some regex that is way to complex for me to understand :P

**Comment by frosty00** [comment]
Ok let me revert the pythonJSON commits then you can commit this

**Comment by kroitor** [comment]
Ok, I've finally merged it, dunno why GitHub shows it as closed, as I've actually added most of the changes from this PR to the master.

@kornrunner i'm having trouble with the following testcases:

```
mbp:ccxt igorkroitor$ php -f php/test/decimal_to_precision.php

Warning: assert(): assert(decimal_to_precision('0', TRUNCATE, 0, DECIMAL_PLACES) === '0') failed in /Users/igorkroitor/ccxt/php/test/decimal_to_precision.php on line 55

Warning: assert(): assert(decimal_to_precision('0', TRUNCATE, 0, SIGNIFICANT_DIGITS) === '0') failed in /Users/igorkroitor/ccxt/php/test/decimal_to_precision.php on line 79

Warning: assert(): assert(decimal_to_precision('123', TRUNCATE, 0) === '123') failed in /Users/igorkroitor/ccxt/php/test/decimal_to_precision.php on line 137

Warning: assert(): assert(decimal_to_precision('0.', TRUNCATE, 0) === '0') failed in /Users/igorkroitor/ccxt/php/test/decimal_to_precision.php on line 145

Warning: assert(): assert(decimal_to_precision('1.45', ROUND, 1, DECIMAL_PLACES) === '1.5') failed in /Users/igorkroitor/ccxt/php/test/decimal_to_precision.php on line 152
mbp:ccxt igorkroitor$
```

If you could help with solving those – that would be really awesome!

Anyway, thanks to you both for your help on this project, @kornrunner , @frosty00!

**Pull request closed without merging**
