### PR TITLE
add intellisense to python with errorName = None in transpiled error class

### PR DESCRIPTION
**Pull request by frosty00**
imma get back to my hw that is due at 11:59

### CODE REVIEW

**Comment by kroitor** [comment]
@frosty00 thx!) tbh i'd rather just generate them, that would remove all questions and would also allow partial imports... let me know your thoughts when you have the time.

**Comment by frosty00** [comment]
i'd rather not, because it is actually easier to see the hierarchy the way it stands now. also you did say that transpilation + generating is a bad idea

**Comment by frosty00** [comment]
> allow partial imports...

wtf is partial imports in python

**Comment by frosty00** [comment]
we can probably do the same thing for php tbh...

**Comment by kroitor** [comment]
@frosty00 my concern is that it doesn't really fix the issue, it points the user to errors.py, but intellisense won't be able to recognize the class hierarchy and display the proper info, apart from ExceptionXXX = None...

**Comment by frosty00** [comment]
yeah it does, because all that intellisense is doing is checking that the variable exists in errors.py, and underlining it in red if it doesn't. Which is stupid to do because you can also add attributes to modules by doing `setattr(sys.modules[__name__], 'something', value)`

**Comment by kroitor** [comment]
@frosty00 when it's a class it can also display the constructor, the class hierarchy, the exception class type and some meta info:

Screen Shot 2019-12-07 at 10 10 39

But, anyways, i understand your arguments, going to merge it shortly, until we have another solution. Thanks )

**Comment by kroitor** [comment]
VSCode will only show a NoneType there:

Screen Shot 2019-12-08 at 01 30 44

**Comment by frosty00** [comment]
I don't know what extension you are using with vscode. Most people will use pycharm.

**Comment by frosty00** [comment]
nvm i see the issue

**Comment by frosty00** [comment]
i think this is as good as we're going to get.

**Comment by kroitor** [comment]
> i think this is as good as we're going to get.

Tbh, I don't think so... I mean, `object()` isn't much better than `None` there... Why not `Exception()` for example? Or why not any other constant value? The thing with intellisense is that we're not trying to silence the unrecognized symbols, we're trying to make it show the same thing by default as it would show if those were native classes. Whatever constants we put there – it won't match the default intellisense representation for the exceptions' native class hierarchy, regardless of which particular IDE it is. And, creating 20-30 objects upon an import just to silence the intellisense doesn't feel right to me.

**Comment by kroitor** [comment]
If i change `object()` to `Exception` (without brackets) it shows this:

Screen Shot 2019-12-08 at 03 34 16

This is a lot closed to what we need, but still very far from the ideal.

**Comment by kroitor** [comment]
One more thing – it is missing the `BaseError` class in the generated list of exceptions in errors.py.

**Comment by kroitor** [comment]
@frosty00 going to merge it in 15 minutes, i still think it's a lot better with this PR than it was before... we'll see if we need to change it further. Thx for helping me out on this!

**Pull request merged**
