### PR TITLE
add active attribute to gdax (python)

### PR DESCRIPTION
**Pull request by neuhaus**
Same as pull request #1181 but for python

### CODE REVIEW

**Comment by kroitor** [comment]
No need for this, it is generated automatically, and it is already there, check this out:
https://github.com/ccxt/ccxt/blob/master/python/ccxt/gdax.py#L193 ;)

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

**Comment by neuhaus** [comment]
ah, missed that. Generated code - excellent.

**Comment by kroitor** [comment]
@neuhaus thanks for the effort anyway! Really appreciate it. Hope to see more pull requests from you!

**Comment by neuhaus** [comment]
@kroitor your enthusiasm is infectious :tada:

**Pull request closed without merging**
