### PR TITLE
new exchange: bitz

### PR DESCRIPTION
**Pull request by Deathamns**
#860

### CODE REVIEW

**Comment by reubenjs** [comment]
Thank you for coding this. There is a fixe I can suggest to get posts (createOrder etc.) to work. The api documentation is not super clear.

- secret_key is not an additional parameter. just the secret key itself is appended.
- x-www-form-urlencoded is also a required header

so

```
sign (path, api = 'public', method = 'GET', params = {}, headers = undefined, body = undefined) {

...

headers = {'Content-type': 'application/x-www-form-urlencoded'}
let signature = this.hash (this.encode (body + this.secret));

...
}
```

**Comment by kroitor** [comment]
@reubenjs awesome, thanks for the feedback!

**Comment by Deathamns** [comment]
@reubenjs Thanks for the comment. If you find anything else, feel free to report it.

**Comment by reubenjs** [comment]
will do. testing a few things with this exchange. so far all good aside from the above.

**Comment by kroitor** [comment]
I'm merging this after cobinhood, the cobinhood should arrive shortly ) Thx!

**Comment by Deathamns** [comment]
The signature of the `fetchOrderBook` method needs to be updated...

**Comment by kroitor** [comment]
@Deathamns yep, thx, will do shortly.

**Comment by andrey-crypto** [comment]
does anyone understand what is 'nonce' here: https://www.bit-z.com/api.html ?

**Comment by Deathamns** [comment]
@andrey-crypto It's a six digit number.

**Comment by Showgofar** [comment]
Hi
Do you know does bit-z support IOC orders?

**Comment by kroitor** [comment]
@Showgofar afaik, they don't differentiate for order types in their API (no such option, no way to set timeInForce).

**Pull request merged**
