### PR TITLE
New Exchange: BloxXwop

### PR DESCRIPTION
**Pull request by dillonko**
Please review and add our exchange. Otherwise can we be added as a feature branch.

### CODE REVIEW

**Comment by kroitor** [comment]
@dillonko thx for the PR! If you can, plz remove php and py files from it – they're generated from js.

**Comment by dillonko** [comment]
Awesome! Will do right now.

**Comment by dillonko** [comment]
Hi @kroitor,
Please review. Really hoping to be apart of the repo.

**Comment by ttodua** [comment]
dead exchange

**Pull request closed without merging**
