### PR TITLE
Bitstamp fixes

### PR DESCRIPTION
**Pull request by tzachshabtay**
Fix "fetch my trades" for bitstamp.
Only tested the python version, don't have the capacity to test the other languages (but it was definitely broken before, so worst case it's still broken).

### CODE REVIEW

**Comment by kroitor** [comment]
Thank you! Merging it soon!

**Comment by kroitor** [comment]
Sorry, can you please delete py and php files from this commit? Those are generated files:
https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

**Comment by tzachshabtay** [comment]
That's sweet @kroitor , missed that it was auto generated. Ok, undid those changes.

**Comment by kroitor** [comment]
Cool! Thanks so much! ) Will merge very soon! )

**Comment by tzachshabtay** [comment]
@kroitor I see that the php transpiling is not working, it looked earlier that it's because of how trade id is converted to string. Do you want me to try and change it, or do you have other plans? Is this the reason you don't merge it in yet?
Thanks.

**Comment by kroitor** [comment]
> @kroitor I see that the php transpiling is not working, it looked earlier that it's because of how trade id is converted to string.
> Do you want me to try and change it, or do you have other plans?

I will fix it, no worries.

> Is this the reason you don't merge it in yet?

Nope, I just didn't have enough time to get to it (yet). But I am going to merge it shortly anyway. Will let you know, hopefully, very soon.

**Pull request merged**
