### PR TITLE
kraken: adjust clientOrderId handling in methods

### PR DESCRIPTION
**Pull request by Dan-krm**
Separated `clientOrderId` from `userref` in muliple methods: `fetchOpenOrders`, `fetchClosedOrders`, `cancelOrder` and added static request tests

### CODE REVIEW

**Comment by carlosmiei** [comment]
@Dan-krm can you check the static tests here? 
image

**Comment by Dan-krm** [comment]
@carlosmiei I'm not sure why the computed response is showing up blank in the tests

**Comment by carlosmiei** [comment]
@Dan-krm ok I'm going to check it

**Comment by carlosmiei** [comment]
@Dan-krm yeah parseOrders is removing the order from the array for some reason, checking it now


image

**Comment by carlosmiei** [comment]
yep this is the issue:
image

**Comment by carlosmiei** [comment]
@Dan-krm In short, we shouldn't use the symbol in these markets because they rely on `marketsByAltname` that is populated inside `fetchmarkets, but the static tests load markets from cache so fetchMarkets does not run

**Pull request merged**
