### PR TITLE
options are now more clever

### PR DESCRIPTION
**Pull request by frosty00**
previously:

```
from ccxt import binance
b = binance({'recvWindow':12})
b.options
{'recvWindow': 5000, 'timeDifference': 0, 'adjustForTimeDifference': False}
```

---

now:

```
from ccxt import binance
b = binance({'recvWindow':12})
b.options
{'recvWindow': 12, 'timeDifference': 0, 'adjustForTimeDifference': False}
```

### CODE REVIEW

**Comment by frosty00** [comment]
> There was an error while trying to fetch the log.

Mother of god 0:

**Comment by frosty00** [comment]
I really don't like the mix of camelCase and under_score notation in the base class code. Can we pick one and stick to it?

```
    substituteCommonCurrencyCodes = True
    lastRestRequestTimestamp = 0
    lastRestPollTimestamp = 0
    restRequestQueue = None
    restPollerLoopIsRunning = False
    rateLimitTokens = 16
    rateLimitMaxTokens = 16
    rateLimitUpdateTime = 0
    last_http_response = None
    last_json_response = None
    last_response_headers = None

**Comment by kroitor** [comment]
Sorry, @frosty00, but I don't think we should really merge the arrays of options, because we won't be able to add to the options in runtime, if we restrict them with a set of predefined options. I don't really think we should denormalize the arrays and mix them in constructor like that. I might be missing something, but is there a tech reason for mixing the options with the rest of params? I would probably keep them separate...

**Comment by frosty00** [comment]
I mean I guess one could always just:

    b = ccxt.binance({'options': {'recvWindow': 12}})

But the constructor I mentioned above seems more natural for people who haven't read the source code of the exchange. In hindsight I can see how this might become a problem in the future, for example if exchange-specific params have the same name as ccxt-params. Anways you decide whether to merge it (:

**Pull request closed without merging**
