### PR TITLE
eslint: airbnb style guide

### PR DESCRIPTION
**Pull request by mkutny**
This adds a package of airbnb's eslint rules.

Right now we're adding them one-by-one when we encounter an issue. This package immediately brings hundreds of them. Those which break existing code I explicitly switched off in the config.

### CODE REVIEW

**Comment by kroitor** [comment]
I'm going to spend a little time getting myself familiar with it and will merge right after. Thx so much!

**Comment by mkutny** [comment]
I'm fine if you decide to drop it, will be adding rules one-by-one then.

**Comment by kroitor** [comment]
Well, both deps seem healthy enough, let's go for it )

**Comment by mkutny** [comment]
These are the great news, thanks!

You know, I didn't say it before so not to influence your decision but airbnb style guide is quite reputable so I believe its existence in our CI will add a credibility to the project. Well, a bit )

**Pull request merged**
