### PR TITLE
bitfinex check withdrawal id

### PR DESCRIPTION
**Pull request by frosty00**

### CODE REVIEW

**Comment by kroitor** [comment]
Thanks again! ) Can you plz tell how to reproduce that zero? I mean, how did you get it? 
Respect! )

**Comment by frosty00** [comment]
I think it happens if you try to withdraw less than the minimum - i.e. trying to withdraw 0.1 eth when the minimum is 0.6

**Comment by frosty00** [comment]
Actually it seems even more common than that -

```
bitfinex.withdraw('ETH', '1', '0x75ffd20b0335eb0065681e0a3740d69917917f75')
ccxt.base.errors.ExchangeError: bitfinex withdraw returned an id of zero: {"status":"error","message":"Cannot withdraw 1.0027 ETH from your exchange wallet. The available balance is only 0.0 ETH. If you have limit orders, open positions, unused or active margin funding, this will decrease your available balance. To increase it, you can cancel limit orders or reduce/close your positions.","withdrawal_id":0,"fees":"0.0027"}
```

**Comment by frosty00** [comment]
It also returns a code of 200 (that's why it doesn't get picked up by handleErrors). Also we should probably change the amount.toString() above - to a `decimalToPrecision` just not sure about what the standard withdrawal precision should be.

**Pull request merged**
