### PR TITLE
Adds Alpaca Crypto Exchange

### PR DESCRIPTION
**Pull request by haxdds**
PR to add Alpaca's Crypto API to CCXT. Learn more about [Alpaca Crypto](https://alpaca.markets/crypto).

**A few things to note:** 
- Alpaca's Crypto API is currently in beta 
- Alpaca doesn't have any Public endpoints. API keys & secrets are needed to access all endpoints. This means you will need a key to access market data (fetchMarkets).
- Alpaca does not currently offer level 2 data OrderBook data. fetchOrderBook is emulated using a single BBO quote.
- Alpaca charges fees on trades using a spread markup. Learn more here: [Crypto Fees](https://alpaca.markets/support/what-are-the-fees-associated-with-crypto-trading/)
- Alpaca does not yet offer funding via API.

Thank you!

The methods that have been implemented and tested.
- [x]  fetchMarkets
- [x] fetchTicker
- [x] fetchTrades
- [x] fetchOrderBook
- [x] fetchBalance
- [x] createOrder
- [x] cancelOrder
- [x] fetchOrder
- [x] fetchOpenOrders

### CODE REVIEW

**Comment by haxdds** [comment]
Hi @kroitor !

Do you have any updates on when our PR will be reviewed?

Thanks!

**Comment by kroitor** [comment]
@haxdds hello! I will get to it before the end of this month.

**Comment by haxdds** [comment]
Hi @kroitor! Do you have any updates on when our PR will be reviewed? Thank you!

**Comment by newsum** [comment]
Yes this would be a great PR to get in there. @haxdds Do you have a CCXT.Pro integration built?

**Comment by Rishirandhawa** [comment]
Hi.. just wondering if CCXT has started supporting ALPACA yet?

**Comment by Chanka0** [comment]
Will this ever get reviewed? It's been a bit, and Alpaca is a good exchange to use. It'd be nice if it was integrated.

**Comment by umitanuki** [comment]
I think this would be tremendous if merged. I have heard friends waiting for it.

**Comment by kroitor** [comment]
@haxdds we are working on this PR very actively right now, will get it merged this week or next week, hopefully.

**Pull request merged**
