### PR TITLE
Workaround to fetch price in hitbtc2

### PR DESCRIPTION
**Pull request by adi90x**
Link to issue 798

### CODE REVIEW

**Comment by hippylover** [comment]
Will this still get an order if it has closed or canceled?

**Comment by adi90x** [comment]
@hippylover  as discussed in the issue I don't think that it will get it if order is closed , so probably not a good idea to merge that !

**Comment by hippylover** [comment]
Where is this privateGetHistoryOrder?

**Comment by hippylover** [comment]
oh. that's deepextend i guess.

**Comment by kroitor** [comment]
@hippylover 

> Where is this privateGetHistoryOrder?

https://github.com/ccxt/ccxt/wiki/Manual#implicit-api-methods

**Comment by kroitor** [comment]
@adi90x if I got you right, we should keep the existing behaviour, namely to fetch the order from historical endpoint, while offering fetchOpenOrder as an alternative (we think this reflects the reality, how it is with HitBTC). Would you mind if I close this PR then?

**Comment by adi90x** [comment]
No problem to close this PR, or we could do something in 2 part : 1st) pull
order statuts 2nd) fetch either using history or with order ?
In order to really implement a fetchOrder method ?

**Comment by hippylover** [comment]
I think curl -X GET -u "fake:fake" "https://api.hitbtc.com/api/2/history/order/14005689110/trades" is supposed to get the info, although i can't get it to work.

Also v1 api can use clientorderid to get the orderinfo and price. unless its sacrilege use that. i don't understand the point of unification unless all functions return the same info :P (then what is the benefit). I think this is more important than reflecting "the reality" of the exchange.

**Comment by kroitor** [comment]
@hippylover to better understand my point, try placing an order, and then fetching trades for it reliably from HitBTC. You'll find it really surprising how they serve that data for open and closed orders...

@adi90x 

> 1st) pull
> order statuts 2nd) fetch either using history or with order ?
> In order to really implement a fetchOrder method ?

Unfortunately, can't do that. Can't decide for the user which request should be next and how much time should be spent waiting for those requests to be executed. Therefore the policy throughout the library is to make one HTTP request per one call to keep it explicit (and let the user decide). This boils down to rate-limiter reasons, explained here: https://github.com/ccxt/ccxt/issues/1175

Does it make sense?

**Comment by hippylover** [comment]
How about we talk to hitbtc?

**Comment by kroitor** [comment]
@hippylover we've contacted them already on this. It usually takes 4-5 days for them to reply to a ticket. I don't know if they will change their API for us (this looks like a limitation of their engine/architecture to me), but, we will try again, why not. Will do that again and will report on the outcome...

**Comment by hippylover** [comment]
Remember "traders want it"!

**Comment by hippylover** [comment]
Hmm, well this popped into my head. Why not store the price when one does a buy/sell(createlimitorder etc i can't remember them all)?

**Comment by kroitor** [comment]
@hippylover we already do that because that popped into our head as well ) This is why I said, tha order cache is invalidated upon program exit ;)

**Comment by kroitor** [comment]
@hippylover here: https://github.com/ccxt/ccxt/blob/master/python/ccxt/hitbtc2.py#L842

**Comment by hippylover** [comment]
:( OK. Store data? In a text file? DB?

**Comment by kroitor** [comment]
> :( OK. Store data? In a text file? DB?

Well, you see, those are user tasks that are beyond the scope of the library. 

Can't decide for the db engine, it implies a ton of dependencies, the CAP theorem, it really depends on your use-case, etc, etc... you would not want a library that pretends to be an OS, trust me ) 

I'd say we must focus on what can be done within those limitations. And let the user do the rest of his business logic whatever way he wants it.

**Comment by hippylover** [comment]
Well, sqlite is part of the standard library in python. So i do not think dependencies are too much of a problem(it would surprise me if it was much different in javascript but i don't know javascript).

But! I fixed my problem by using a local db so i guess im cool. I won't be pushy on this, but it is a thought.

**Comment by kroitor** [comment]
> So i do not think dependencies are too much of a problem

It's a significant security problem in fact, more about it here: https://github.com/ccxt/ccxt/issues/943

But, hey, thanks a lot for your thoughts! Feedback does matter, and we will reconsider this carefully if needed, maybe some time later when we have more immediate work done.

**Comment by hippylover** [comment]
Ok!

**Comment by hippylover** [comment]
When you say "standalone wrapper lib" you mean there will be some setting in ccxt which one can set to enable persistent data?

Oh and btw i just want to say i completely understand your hesitance with db's. I was of the same opinion because a Db sounds... heavy. However! I think sqlite is not heavy(although i could be wrong).

hippylover out!

**Pull request closed without merging**
