### PR TITLE
kraken: do not crash on empty orderbook response

### PR DESCRIPTION
**Pull request by egorFiNE**

### CODE REVIEW

**Comment by egorFiNE** [comment]
Nope, not yet. Must debug further what's wrong with kraken here.

**Comment by egorFiNE** [comment]
Indeed kraken sometimes returns JSON string, not JSON. `this.publicGetDepth()` ...

**Comment by kroitor** [comment]
> Indeed kraken sometimes returns JSON string, not JSON. this.publicGetDepth() ...

Can you plz clarify this a little? Because we don't see anything like that... Are you sure about *"JSON string"* ? If it's HTML this may be a Cloudflare protection page or something.

**Comment by egorFiNE** [comment]
it's indeed a valid looking JSON, but `typeof response == 'string'`, not `object`. So some code inside `js/base/Exchange.js` fails to parse a JSON response as json.

It happens in < 1% of calls, which is still a lot for `fetchOrderbooks()`. 

I'm debugging it right now.

**Comment by egorFiNE** [comment]
Headers seem ok:

```
{ Date: 'Fri, 08 Jun 2018 15:16:15 GMT',
  'Content-Type': 'application/json; charset=utf-8',
  'Transfer-Encoding': 'chunked',
  Connection: 'close',
  'Set-Cookie':
   '__cfduid=df2a8cef0eed2f5d15a4cf0da1a27929b1528470975; expires=Sat, 08-Jun-19 15:16:15 GMT; path=/; domain=.kraken.com; HttpOnly',
  'Cache-Control': 'public,max-age=3,smaxage=3',
  'Content-Encoding': 'gzip',
  Vary: 'Accept-Encoding',
  'Cf-Cache-Status': 'EXPIRED',
  'Expect-Ct':
   'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"',
  Server: 'cloudflare',
  'Cf-Ray': '427c518a1b9db859-WAW' }
```

**Comment by egorFiNE** [comment]
how do I go about debugging it? where is JSON parsed exactly?

**Comment by kroitor** [comment]
https://github.com/ccxt/ccxt/blob/master/js/base/Exchange.js#L472

**Pull request closed without merging**
