### PR TITLE
Manual: ticker structure: change/percentage

### PR DESCRIPTION
**Pull request by mkutny**

### CODE REVIEW

**Comment by mkutny** [comment]
BTW, what's the difference between `first` and `open`?
```javascript
    'open':        float (open price),
    'first':       float (price of first trade),
```

From all the exchanges only bitlish has it set.

Also, as tickers are "live" it seems that `close` also have a little of sense, what do you think?

**Comment by kroitor** [comment]
You're right, they are redundant, and we should probably remove some redundant fields... The question is, which pair lives:
- `open` and `close`
- `first` and `last`...

For consistency with OHLCV, I would go for `open` and `close`, and would remove the latter pair. How does it sound to you?

**Comment by mkutny** [comment]
`close` sounds a little bit odd to me as ticker is supposed to be live. This is opposite to OHLCV which splits data into periods. I wasn't able to find Wiki article but here is what [Investopedia](https://www.investopedia.com/ask/answers/12/what-is-a-stock-ticker.asp) says:

> The ticker provides current information for certain stocks, including: the ticker symbol (the one- to four-letter code that represents a particular stock); quantity traded (volume for each transaction); price; a green "up" arrow if the price is higher than the previous day's closing value, or a red "down" arrow if the price is lower; and the net price change (either as a dollar amount or percentage) from the previous day's close.

So, as I see it:
- `open` - technically, we may say it's nearly the same as `previous day's close` as we deal with continuous trading sessions
- `last` - current price

BTW, look at binance's ticker which is in line with Investopedia's definition but its `close` is incorrectly interpreted by ccxt:

```
{      symbol:   "ETH/BTC",
        close:    0.087448,
        first:    undefined,
         last:    0.082666,
         open:    0.087431,
         info: {             symbol: "ETHBTC",
                     prevClosePrice: "0.08744800",
                          lastPrice: "0.08266600",
                          openPrice: "0.08743100" } }
```

**Comment by kroitor** [comment]
@mkutny from your posts I carried out that:
- `open` and `first` are the same thing (can be merged into a single value)
- `last` isn't the same as `close` (cannot be merged into a single value)

> we may say it's nearly the same as previous day's close as we deal with continuous trading sessions

Unless there was a service delay, like it was with Binance a few days ago ) In that case we may get a `close` price very different from the `open` price...

Still not sure if we should keep `close`, as, obviously, it is almost the same, but still not the same as `open`, those are two different trades, and this makes a difference in algorithmic sense...

**Comment by mkutny** [comment]
> Still not sure if we should keep close, as, obviously, it is almost the same, but still not the same as open, those are two different trades, and this makes a difference in algorithmic sense...

I was surprised to learn that someone used `fetchTicker` as a replacement for `fetchOrderBook` and still I will be surprised to learn that someone uses ticker's `open` and `close`values as a replacement to `fetchOHLCV`.

Nevertheless, I'm absolutely fine with keeping it on those rare cases when it's available. The only thing I'd rather suggest is to change it's name to `prevDayClose` to make it apparent it's not the same as `OHLCV's close` and not the same as `last`. You see, it was not apparent to us until we started this thread and obviously won't be apparent to users as well.

**Pull request merged**
