### PR TITLE
qryptos: maker/taker fees, fetchOpenOrders, error handling

### PR DESCRIPTION
**Pull request by mkutny**

### CODE REVIEW

**Comment by mkutny** [comment]
I still can't get `fetchOpenOrders` to pass down `symbol` parameter to native API. Need your help on it. I put `FIXME` on that line.

**Comment by mkutny** [comment]
Forgot to mention that not all order parameters are filled at the moment. I'll do that after I break through to the exchange.

**Comment by kroitor** [comment]
> I still can't get fetchOpenOrders to pass down symbol parameter to native API. Need your help on it. I put FIXME on that line.

Basically, we need to add the if (method == 'GET') to the private section of `sign` and populate the url like we do for public get requests:

```JavaScript

    sign (path, api = 'public', method = 'GET', params = {}, headers = undefined, body = undefined) {
        let url = '/' + this.implodeParams (path, params);
        let query = this.omit (params, this.extractParams (path));
        headers = {
            'X-Quoine-API-Version': this.version,
            'Content-Type': 'application/json',
        };
        if (api == 'public') {
            if (Object.keys (query).length)
                url += '?' + this.urlencode (query);
        } else {
            this.checkRequiredCredentials ();
            let nonce = this.nonce ();
            let request = {
                'path': url,
                'nonce': nonce,
                'token_id': this.apiKey,
                'iat': Math.floor (nonce / 1000), // issued at
            };
            // FIXME workaround ←-------------------------------------- start
            if (method == 'GET') {
                if (Object.keys (query).length)
                    url += '?' + this.urlencode (query);
            } else if (Object.keys (query).length) {
                body = this.json (query);
            }
            // FIXME workaround ←-------------------------------------- end
            headers['X-Quoine-Auth'] = this.jwt (request, this.secret);
        }
        url = this.urls['api'] + url;
        return { 'url': url, 'method': method, 'body': body, 'headers': headers };
    }
```

**Comment by mkutny** [comment]
> Basically, we need to add the if (method == 'GET') to the private section of sign and populate the url like we do for public get requests

I've got it, thanks!

**Pull request merged**
