### PR TITLE
[poloniex] removed the cache and some misleading methods

### PR DESCRIPTION
**Pull request by npomfret**

### CODE REVIEW

**Comment by npomfret** [comment]
Sorry, I meant to mark this as a work in progress.  But I see you've added some fixes, thanks.  Is there any more to do?

**Comment by kroitor** [comment]
> Is there any more to do?

Nope, I think I'll merge this shortly. However, we will have to bump the minor version first, because it may be a breaking change for some dependent code. Will do this today as soon as I get through my other parallel tasks.

**Comment by npomfret** [comment]
Agreed

**Comment by kroitor** [comment]
@npomfret actually, on a second thought, we may have to save the orders cache for the following reason. We are going to release CCXT Pro soon and when it comes to private websocket orders' feeds most of the exchanges require a user to maintain a database of open and closed orders, that is, basically, the `.orders` cache, and it is used in the WS implementation of private authenticated calls for Poloniex. In the light of that we may have to keep the `.orders` cache for Poloniex, including the cache-based rest methods, because basically they work in pair with WS... What do you think about it?

**Comment by npomfret** [comment]
I think the orders cache is a fine idea but I don't think it belongs in the core product.  IMO the orders cache needs to be something you pass in to the constructor which would allow people to provide their own implementation.

My current client uses ccxt in a distributed environment, which I imagine is a common pattern.  The current embedded orders cache can't work because the server that places the order may not be the same server as the one that read from the exchange.

They currently have a bug because as well as ccxt being used in a distributed environment, it is also being used in a stateless mode - ie, they create an instance, use it, and discard it.  So again, the orders cache won't work. They are assuming that `fetchOrders` in poloniex works as it does on other exchanges, but are just getting an empty array back.

Is it correct to assume that if any `has` feature contains the value `emulated` that means it's using the orders cache?  Because if so they can use that flag to avoid those methods entirely (for now).

I think a good solution would be to pass in an `OrderCache` object with a strictly defined interface (maybe just `loadOrder`, `saveOrder`?) if you choose to, but by default it is not passed in.  Then each `has` switch get's set to `false` if the implementation relies on the orders cache being present.  You can provide an in-memory implementation (`InMemoryOrderCache`), leaving other people free to write say `RedisOrderCache` and `DatabaseBackedOrderCache`.

**Comment by kroitor** [comment]
> Is it correct to assume that if any has feature contains the value emulated that means it's using the orders cache? Because if so they can use that flag to avoid those methods entirely (for now).

Yep, that was the reason for introducing the `'emulated'` flag in the first place ) It means that it's not a true fetchOrders method, but is emulated via fetchOpenOrders. So, basically if it's not strictly equal to `True`, then you can assume `False`, if you don't want to call the emulated methods.

> I think a good solution would be to pass in an OrderCache object with a strictly defined interface (maybe just loadOrder, saveOrder?) if you choose to, but by default it is not passed in. Then each has switch get's set to false if the implementation relies on the orders cache being present. You can provide an in-memory implementation (InMemoryOrderCache), leaving other people free to write say RedisOrderCache and DatabaseBackedOrderCache.

Thx for sharing your thoughts, I agree with the above. We are detaching the cache to a standalone abstract class with a sample implementation for WS anyway. We have the same caching layers in other exchages, like Exmo and a few more. And the code there is mostly duplicated, so we will probably use it as a base for a standalone caching class. WIll get back to this shortly.

**Comment by npomfret** [comment]
Ok, so shall we just close this?

**Comment by kroitor** [comment]
> Ok, so shall we just close this?

Yep, I really appreciate your help, but, if you don't mind, i'd close it for now. I will try to add an implementation based on an external-class and we will discuss it then.

**Pull request closed without merging**
