### PR TITLE
Option to always use max amount of rate limiter available

### PR DESCRIPTION
**Pull request by samgermain**
I'm trying to edit the rate limiter so that the max amount of your available limit is used before your requests start being slowed down, 

if 60 requests of weight 1 are made for

- an exchange with a max rate limit weight of 60
    - all 60 requests executed asynchronously at the same time.

- an exchange with a max rate limit weight of 30
    - 30 requests would be executed asynchronously at the same time at the beginning, with each other request being added every time some of the rate limiter opens up

### CODE REVIEW

**Comment by ttodua** [comment]
> I'm trying to edit the rate limiter so that the max amount of your available limit is used before your requests start being slowed down,
> 
> if 60 requests of weight 1 are made for
> 
> * an exchange with a max rate limit weight of 30
>   
>   * all 60 requests executed asynchronously at the same time.
> * an exchange with a max rate limit weight of 30
>   
>   * 30 requests would be executed asynchronously at the same time at the beginning, with each other request being added every time some of the rate limiter opens up

do you have a typo in the description?   `an exchange with a max rate limit weight of 30` is mentioned twice, so I suppose in first example you meant not 30, but 60, right?

**Comment by frosty00** [comment]
it's possible to do just by changing the capacity in the tokenbucket

**Comment by samgermain** [comment]
> it's possible to do just by changing the number of `tokens` in the tokenBucket

I don't understand how that would work, maybe I should make a diagram to explain this?

**Comment by samgermain** [comment]
If 
- there's a limit of 5 requests/min and 
- you send 7 requests at once, 

It's my understanding that our rate limiter would work like the diagram on the left, with one request being sent every 12s

I'm trying to update the rate limiter to work like the diagram on the right, where 
- 5 requests would be sent on the first second
- the 6th request would be sent at second 60
- the 7th request would be sent at second 72

-------------------

> it's possible to do just by changing the number of `tokens` in the tokenBucket

I don't understand how changing the number of tokens in the tokenBucket would do this

**Pull request closed without merging**
