### PR TITLE
Update oceanex.py

### PR DESCRIPTION
**Pull request by vxnuke**
Added capability to place market orders

### CODE REVIEW

**Comment by kroitor** [comment]
@vxnuke hi! Thx for the contribution! Can you please move these edits to the source file?

- https://github.com/ccxt/ccxt/pull/5335/files#diff-93aa4f0415f0e700ca3558fa18c839cdL3
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#multilanguage-support
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#derived-exchange-classes

**Comment by vxnuke** [comment]
@kroitor Sorry i am not familiar with js

**Comment by kroitor** [comment]
@vxnuke ok, no worries... on question, though – have you tested it?

**Comment by vxnuke** [comment]
Ill update with 100% working code as lines from 460 around about upwards have not been tested

**Comment by kroitor** [comment]
> Ill update with 100% working code as lines from 460 around about upwards have not been tested

We would revert lines above 460 anyway, because it's a step back, we've just moved from the version you proposed to the current version of fetch_balance in the master branch, and it's working ) We would not want to return back to a previous version of it ) However, if you can test the market orders with create_order – and report here with a verbose request/response – that would help a lot!

**Comment by vxnuke** [comment]
I have tested at it worked ill create new pull request

**Comment by kroitor** [comment]
@vxnuke awesome, thx!

**Comment by vxnuke** [comment]
:)
https://github.com/ccxt/ccxt/pull/5337

**Pull request closed without merging**
