### PR TITLE
js: kucoin: initial work on ohlcv #602

### PR DESCRIPTION
**Pull request by kornrunner**
#894 is blocking further work on OHLCV as per https://github.com/ccxt/ccxt/issues/602#issuecomment-351777727

### CODE REVIEW

**Comment by kroitor** [comment]
No worries, if it did work with new timeframes + a native endpoint, then we don't have to fall back to building ohlcv from trades, right? Or do I miss something?

**Comment by kornrunner** [comment]
Soz, my bad - in my previous commit I reverted the endpoint change before pushing.

Their `/open/kline` endpoint always returns `Operation succeeded.` but no data. So, building ohlcv from trades seems to be the only way (currently).

**Comment by kroitor** [comment]
> So, building ohlcv from trades seems to be the only way (currently). 

We also have a web endpoint for plan B ) But don't bother, I can wrap it up pretty quickly. So, if you have more time for this, I'd suggest to move on to their private API, and I'll do the rest of OHLCV today. What do you think?

**Comment by kornrunner** [comment]
Sure thing, I can continue with private API.

`open/chart/history` endpoint (which is used in this commit) seems to be working for both Web API and regular API, as far as I've tried.

Unless I've missed some link or something.

**Comment by kornrunner** [comment]
Last commit fixes sign method

**Comment by kornrunner** [comment]
I'm a bit confused, I'm not 100% sure how to map their API to ccxt unified API (their naming convention isn't very clear to me), would appreciate hints if you've got any. Thanks!

**Comment by kroitor** [comment]
Sure! I will review them now and will list the correspondence here in very short time. Thx!

**Comment by kroitor** [comment]
We now have public API + sign + fetchBalance.

So from here the next step would be to implement createOrder, cancelOrder, fetchOpenOrders (*"active"*), fetchClosedOrders (*"dealt"*). This would be a minimal viable unified trading API.

screen shot 2017-12-20 at 21 28 58

Then we can move on to the funding API, fetchDepositAddress + withdraw. This would be a unified public+trading+funding API.

screen shot 2017-12-20 at 22 31 06

And then, later, the withdrawal history, etc... 

Please let me know if you want me to do any or all of the these parts. Your contribution is impressive! Thank you!

**Comment by kornrunner** [comment]
Thank you very much. I've just pushed fetchOpenOrders. Could you please check it out, just to make sure I'm not going in the wrong direction?

**Comment by kroitor** [comment]
@kornrunner yes, everything looks very good! Thanks! Let me know if you have any questions, I'll stand by to assist.

**Comment by kornrunner** [comment]
Ok, here's fetchClosedOrders. I had to tweak parseOrder, and I'm really not 100% sure it's populating proper fields. Their response keys differ (`price`, `dealPrice`, `pendingAmount`, `amount`, `dealAmount`, `direction`, `dealDirection`, `type`) - so I'd appreciate if you could check up on that, I'm a bit new to all this terms.

Also, what should `fetchOrders` represent?

**Comment by kroitor** [comment]
> Ok, here's fetchClosedOrders. I had to tweak parseOrder, and I'm really not 100% sure it's populating proper fields. Their response keys differ (price, dealPrice, pendingAmount, amount, dealAmount, direction, dealDirection, type) - so I'd appreciate if you could check up on that, I'm a bit new to all these terms.

Sure, don't worry too much on the details, I will polish them anyway. Just for the sake of explanation:
- price is the ordered price
- dealPrice is the avg actual filling (closing) price per base unit (most often present in closed or partially filled orders only, absent in other orders)
- pendingAmount is the remaining (non-filled) volume of the order
- amount is the total volume of the order
- dealAmount is the filled volume of the order, so, amount should be = pendingAmount + dealAmount.
- direction – this is the direction of the maker order 
- dealDirection - this is the direction of the taker order (your order can land as a taker or maker)
- type – this field usually designates the limit/market/exchange-specific/other type of the order

> Also, what should fetchOrders represent?

That would represent a merged open+closed/canceled orders aka *all orders*. However, there's no standard across exchanges for this, a half of them has fetchOrders, the other half has fetchOpenOrders + fetchClosedOrders. Some exchanges, have all of those methods or allow to parameterize the fetchOrders for open-only, closed-only, etc... This is also one of the reasons for having a "metainfo" field for determining exchange capabilities programmatically in runtime.

**Comment by kornrunner** [comment]
Thank you very much for detailed explanation. I've pushed the `createOrder` and `cancelOrder` and I think I'll stop there for now.

Surely I've learned a lot about internals of ccxt, and it will be much easier to contribute in future.

**Comment by kroitor** [comment]
Just a note: in their particular case the `type` field is the param field, they don't return it within the orders, and in params the `type` acts as a filter for "BUY" or "SELL". I will re-check and will add edits where needed, no worries at all, and thx.

**Comment by kroitor** [comment]
I'm merging this shortly!

**Pull request merged**
