### PR TITLE
Bittrex api v3

### PR DESCRIPTION
**Pull request by Stolenko**

### CODE REVIEW

**Comment by npomfret** [comment]
@Stolenko thanks for this - i'd really like to start using bittrex v3 for trading

**Comment by SqueezedLight** [comment]
Thanks for the great work! Any estimation when this gets merged?

**Comment by ethanbrown3** [comment]
Any update on this? I appreciate all the work being done on this.

**Comment by kroitor** [comment]
@SqueezedLight @ethanbrown3 we're merging it shortly, it's among our prioritized PRs along with a few other exchanges. Hope to get it in master within a few days (as soon as we can).

**Comment by haydee-etoshi** [comment]
Any updates? Thanks!!

**Comment by aalstes** [comment]
Does Bittrex api v3 already work with CCXT Pro websockets?

**Comment by kroitor** [comment]
@aalstes yes, it's available in CCXT Pro: https://ccxt.pro

**Pull request merged**
