### PR TITLE
safeStatus

### PR DESCRIPTION
**Pull request by ttodua**
`safeTime` and `safeStatus` to be used in `fetchTime` and `fetchStatus`.
open for further improvements.

### CODE REVIEW

**Comment by kroitor** [comment]
I would remove `safeTime` – seems redundant.

**Comment by ttodua** [comment]
side-question: dont we need `safe_status` ? it has `eta` which are missing from many exchanges, while present in some exchanges. also, automatically sets `update` property.

**Comment by kroitor** [comment]
@ttodua if you can, please clean out safeTime.

**Comment by kroitor** [comment]
> _(so, in `fetchTime` we will never need to include `info` right? whatever response did exchange return , be it string, 10-13 digit integer or even utc-datetime string or whatsever)_

Yes, we just return the time value.

**Pull request merged**
