### PR TITLE
wazirxpro string math

### PR DESCRIPTION
**Pull request by samgermain**
```
2023-01-06T22:34:41.205Z
Node.js: v18.4.0
CCXT v2.5.36
wazirx.watchOrders ()
        id |                        clientOrderId |                 datetime |     timestamp | lastTradeTimestamp |   symbol |  type | timeInForce | postOnly |  side | price | stopPrice | triggerPrice | amount | filled | remaining | cost | average | status | fee | trades | fees
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
3524803377 | b0a97502-8d45-46d4-b57a-9dc74af012bf | 2023-01-06T22:35:05.000Z | 1673044505000 |                    | XRP/USDT | limit |             |          | limit |   0.3 |           |              |     20 |      0 |        20 |    0 |         |   open |     |     [] |   []
1 objects
```

```
Python v3.10.4
CCXT v2.5.36
wazirx.watchOrders()
[{'amount': 20.0,
  'average': None,
  'clientOrderId': '3757bafb-169a-41de-b34d-ac8541574c1d',
  'cost': 0.0,
  'datetime': '2023-01-06T22:39:14.000Z',
  'fee': None,
  'fees': [],
  'filled': 0.0,
  'id': '3524806031',
  'info': {'E': 1673044754062,
           'O': 1673044754000,
           'S': 'buy',
           'V': '20',
           'X': 'wait',
           'c': '3757bafb-169a-41de-b34d-ac8541574c1d',
           'i': 3524806031,
           'm': True,
           'o': 'limit',
           'p': '0.3',
           'q': '20',
           's': 'xrpusdt',
           'v': '0',
           'z': '0'},
  'lastTradeTimestamp': None,
  'postOnly': None,
  'price': 0.3,
  'remaining': 20.0,
  'side': 'limit',
  'status': 'open',
  'stopPrice': None,
  'symbol': 'XRP/USDT',
  'timeInForce': None,
  'timestamp': 1673044754000,
  'trades': [],
  'triggerPrice': None,
  'type': 'limit'}]
  ```

### CODE REVIEW

**Comment by frosty00** [comment]
we don't need to do stringMath on integers

**Comment by frosty00** [comment]
instead we should change that to safeInteger from safeNumber

**Comment by samgermain** [comment]
> instead we should change that to safeInteger from safeNumber

Ok, well I'm going to leave this PR open so that I remember to do that

**Comment by carlosmiei** [comment]
> > instead we should change that to safeInteger from safeNumber
> 
> Ok, well I'm going to leave this PR open so that I remember to do that

Yeah @samgermain integers are perfectly represented using base 2, the problem only affects floating point numbers

**Comment by kroitor** [comment]
I would not merge it and would keep it with integer math on milliseconds timestamps, should be all good on 64-bit systems. We only need string math for money-values (prices, coin amounts, fees, etc).

**Comment by samgermain** [comment]
> We only need string math for money values (prices, coin amounts, fees, etc).

[Look at this thread](https://discord.com/channels/690203284119617602/1046949453757689906/1047004257355845712)

**Comment by samgermain** [comment]
> > > instead we should change that to safeInteger from safeNumber
> > 
> > 
> > Ok, well I'm going to leave this PR open so that I remember to do that
> 
> Yeah @samgermain integers are perfectly represented using base 2, the problem only affects floating point numbers

I understand everything that everyone is saying here except for " integers are perfectly represented using base 2" which I'm just curious about now, why are you talking about base 2 numbers?

**Comment by samgermain** [comment]
> 

Basically any number obtained from an exchange response needs string math, because if the user sets their number type to a string, then `safeNumber` will return a string, so we can't do something like `8 * this.safeNumber (response, 'someKey')` because  you would be multiplying a number by a string

**Comment by kroitor** [comment]
@samgermain 

> Basically any number obtained from an exchange response needs string math

We use `safeInteger` for timestamps where 64-bit integer math is perfectly fine, no need for string math on timestamps in most cases.

**Pull request closed without merging**
