### PR TITLE
binance: createOrder: now returns order structure

### PR DESCRIPTION
**Pull request by mkutny**

### CODE REVIEW

**Comment by mkutny** [comment]
In this particular case it transpiles to `else if` instead of `elif`. Why is that?

**Comment by kroitor** [comment]
`} else if {` is the only recognized *else if* syntax supported by the transpiler, it currently demands the brackets for multiple else-cases, unfortunately.

**Comment by kroitor** [comment]
Hold on, I'll add `else if` to the transpiler...

**Comment by mkutny** [comment]
No problem! I used to brackets, remove them from one-line *if*s just for the sake of uniformness with your style.

**Pull request merged**
