### PR TITLE
tidex: withdraw fees

### PR DESCRIPTION
**Pull request by Deathamns**

### CODE REVIEW

**Comment by kroitor** [comment]
Hey ) Thanks for this pull request, as always! I'm going to merge it, but, in the meantime, I wanted to ask, what would you say if I proposed to add this endpoint:
tidex-fees
Would you make an attempt on adding that? We might be much better with scraping them, where possible, at least it would be first-hand info that is guaranteed to be up to date (seemingly). Let me know what you think, thx!

**Comment by kornrunner** [comment]
On the other hand, they don't support API withdrawals yet, as per:
https://tidex.com/public-api

screenshot-2018-1-11 public api description - cryptocurrency exchange and bitcoin btc trading platform buy sell margin t

And I've checked with their support, but haven't got much:
screenshot-2018-1-11 2642 withdrawcoin method support center

**Comment by Deathamns** [comment]
I thought about it, I copied the data from there actually, but since it is not part the official API, and it contains other data (like markets) I thought you wouldn't like the idea.

**Comment by kroitor** [comment]
@kornrunner yep, they share the same ex-BTC-e API with LIqui, WEX and a few others... However, that info might be useful for other purposes as well, so, even though they don't support withdrawals with their API (yet), they do allow withdrawals via their website, so it can still make more sense to parse that )

**Comment by kroitor** [comment]
@Deathamns 

> I thought you wouldn't like the idea.

Why wouldn't I like it? ) I like it much better than hardcode, frankly )

**Comment by Deathamns** [comment]
@kroitor OK, I can make an attempt.

**Comment by kroitor** [comment]
@Deathamns checkout other fetchCurrencies implementations, should be pretty much straightforward from there. Besides, you already have experience with adding new exchanges, so we would be very happy if you do that. Thankfully, the community is becoming very active.

**Pull request merged**
