### PR TITLE
tests: fetchTicker: more cases

### PR DESCRIPTION
**Pull request by mkutny**

### CODE REVIEW

**Comment by mkutny** [comment]
Anxpro failed on these tests and for a reason.
Their `vwap` is a complete nonsense.

Now I remember that I noticed this a while ago when I was fixing base/quote volumes for a number of exchanges but apparently I forgot to fix it that time.

**Comment by kroitor** [comment]
Thank you, appreciate your contributions!

**Comment by kroitor** [comment]
One of the added assertions (the `quoteVolume <= baseVolume * high` in particular) breaks TheRock. JFIY, I disabled that check temporarily, will investigate further into it.

**Comment by mkutny** [comment]
Thanks for letting me know!

Apparently, their ticker is broken.

This is what they report:
```
         info: {          date: "2017-12-31T20:43:10.769+01:00",
                       fund_id: "BTCUSD",
                           bid:  14001.01,
                           ask:  14600,
                          last:  14600,
                          open:  13580.01,
                         close:  12483.16,
                           low:  12000.01,
                          high:  13580.01,
                        volume:  2884.33,
                 volume_traded:  0.209                           } }
```

I just fetched last trades to check. 
Base/quote volume match recent trades (past 24h) exactly.

But it looks like they report OHLC for the day before (note that trade at 2017-12-30T16:38:03.894Z matches 'close'):

```

id | timestamp | datetime | symbol | side | price | amount | cost
-- | -- | -- | -- | -- | -- | -- | --
2883925 | 1514748628673 | 2017-12-31T19:30:28.673Z | BTC/USD | buy | 14600.00 | 0.0400 | 584
2883583 | 1514743572754 | 2017-12-31T18:06:12.754Z | BTC/USD | buy | 14600.00 | 0.0600 | 876
2883182 | 1514738855016 | 2017-12-31T16:47:35.016Z | BTC/USD | buy | 14868.00 | 0.0005 | 7
2878898 | 1514710456877 | 2017-12-31T08:54:16.877Z | BTC/USD | buy | 13099.99 | 0.0644 | 844
2878870 | 1514710220289 | 2017-12-31T08:50:20.289Z | BTC/USD | buy | 13099.99 | 0.0060 | 79
2878862 | 1514710169791 | 2017-12-31T08:49:29.791Z | BTC/USD | buy | 13001.00 | 0.0060 | 78
2878861 | 1514710159882 | 2017-12-31T08:49:19.882Z | BTC/USD | buy | 13001.00 | 0.0060 | 78
2878860 | 1514710151068 | 2017-12-31T08:49:11.068Z | BTC/USD | buy | 13001.00 | 0.0060 | 78
2878859 | 1514710141892 | 2017-12-31T08:49:01.892Z | BTC/USD | buy | 13000.99 | 0.0060 | 78
2878858 | 1514710131991 | 2017-12-31T08:48:51.991Z | BTC/USD | buy | 13000.99 | 0.0120 | 156
2878287 | 1514696208856 | 2017-12-31T04:56:48.856Z | BTC/USD | sell | 12701.00 | 0.0021 | 27
Last 24H total |   |   |   |   |   | 0.2090 | 2884

2873719 | 1514651883894 | 2017-12-30T16:38:03.894Z | BTC/USD | sell | 12483.16 | 0.0052 |  
2873714 | 1514651878343 | 2017-12-30T16:37:58.343Z | BTC/USD | sell | 12500.00 | 0.1000 |  



```

**Comment by kroitor** [comment]
@mkutny should we set ohlcv to undefined then? Or add an ".inconsistent" flag of some sort? Or add ohlcv timestamp ? In other words, what do you think would be a good workaround for this?

**Comment by mkutny** [comment]
Well, that depends on data quality.

For example, if `anxpro` reports `5` for `vwap` it doesn't make sense to keep this it.
But in this case of 'lagging' OHLC I can't say that the data is a complete nonsense. In some cases, it still may be better than nothing while in others it may lead to a loss.

I'd say that the flagging is optimal if the flag is accompanied by a notice of what's exactly wrong with the data so users could decide for themselves.

**Pull request merged**
