### PR TITLE
Add fetchOrder, fetchMyTrades to quadrigacx

### LINKED ISSUE #3309: Endpoint request: QuadrigaCX fetchOrder
- CCXT version: latest
- Exchange: QuadrigaCX
- Method: fetchOrder

Not sure when they implemented this but I notice in their API docs (https://www.quadrigacx.com/api_info) it's labelled new still.

Quadriga isn't my highest priority right now but I might take a look at adding this if someone else doesn't soon

Thanks.

### PR DESCRIPTION
**Pull request by JSRossiter**
This is my first contribution here so let me know if anything should be different. Quadriga's lookup_order endpoint doesn't return a lot of information so I just filled out what was available.

Closes #3309

### CODE REVIEW

**Comment by asghaier76** [comment]
I am trying to use the fetchOrder endpoint on QuadrigaCX but I am receiving this error

Cannot read property 'split' of undefined

other endpoints such as fetchOrderBook and createMarketOrder are working fine

**Comment by JSRossiter** [comment]
Yeah, this happens when Quadriga can't find the order (which seems to be old orders as well as incorrect IDs)

**Comment by asghaier76** [comment]
this order is returned among fetchMyTrades, how come it is not returned by fetchOrder

**Comment by JSRossiter** [comment]
I'm not sure, assuming you're experiencing the  same thing as me, running the direct API call to Quadriga will return an error message, it's just the error handling isn't complete yet in this library. You could try reaching out to Quadriga support

**Comment by kroitor** [comment]
@asghaier76 if you can provide your verbose request/response output we could fix it rather quickly: 

- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

**Comment by JSRossiter** [comment]
```
fetch:
 quadrigacx POST https://api.quadrigacx.com/v2/lookup_order
Request:
 { 'Content-Type': 'application/json' }
 {"key":"*******","nonce":1542379171579000,"signature":"********","id":"fddsafsd"}

handleRestResponse:
 quadrigacx POST https://api.quadrigacx.com/v2/lookup_order 200 OK
Response:
 { Date: 'Fri, 16 Nov 2018 14:39:32 GMT',
  'Content-Type': 'application/json',
  'Content-Length': '99',
  Connection: 'close',
  'Set-Cookie':
   '__cfduid=d0a5406492d36379fc9ae02c34d57cdfa1542379171; expires=Sat, 16-Nov-19 14:39:31 GMT; path=/; domain=.quadrigacx.com; HttpOnly',
  'Access-Control-Allow-Origin': '*',
  'Content-Encoding': 'gzip',
  Vary: 'Accept-Encoding',
  'X-Content-Type-Options': 'nosniff',
  'X-Frame-Options': 'SAMEORIGIN',
  'X-Powered-By': 'PHP/5.5.9-1ubuntu4.25',
  'X-Xss-Protection': '1; mode=block',
  'Expect-Ct':
   'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"',
  Server: 'cloudflare',
  'Cf-Ray': '47aab51ebe883b3e-YVR' }
 [{"id":"fddsafsd","error":{"code":106,"message":"Cannot perform request - not found"}}]

(node:16361) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'split' of undefined
    at quadrigacx.parseOrder (/Users/jeff/Coding/crypto/ccxt/js/quadrigacx.js:148:48)
    at Object.values.map.order (/Users/jeff/Coding/crypto/ccxt/js/base/Exchange.js:1136:64)
    at Array.map (<anonymous>)
    at quadrigacx.parseOrders (/Users/jeff/Coding/crypto/ccxt/js/base/Exchange.js:1136:45)
    at quadrigacx.fetchOrder (/Users/jeff/Coding/crypto/ccxt/js/quadrigacx.js:123:21)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:16361) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:16361) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Pull request merged**
