### PR TITLE
implement useV2 for param/options of other brand new v3 methods

### PR DESCRIPTION
**Pull request by olegtaranenko**
missing `position.leverage` in new v3 api broke my current application. This patch recovers functionality

### CODE REVIEW

**Comment by carlosmiei** [comment]
Hello @olegtaranenko, thanks a lot for your contribution.

**Comment by olegtaranenko** [comment]
> Hello @olegtaranenko, thanks a lot for your contribution.
Hey @carlosmiei ,
I want to add one more setting `Exchange.options.useFapiPrivateV2`, which will act as an umbrella for using v2 and not enumerate every single api endpoint in config. WDYT?
I noticed you added docs and tests. I think is required to document such a new setting somewhere in the Manual.md? Honestly not found the place with it is already done. Should I open the github issue for this?

**Comment by carlosmiei** [comment]
@olegtaranenko I don't think that is needed, if we use `handleOptionAndParams` to read `useV2` that method will read from `this.options` as well, so `useV2` can be used as a global option as well like `exchange.options['useV2'] = True` and inside each individual method we read it using the above mentioned method and we do the conditional request

**Comment by olegtaranenko** [comment]
@carlosmiei you are correct, and fixing this issue i figured out, how `handleOptionsAndParams` working, but thanks for more clarifying. I'm just thinking about possible future development. Currently there are only 2 incompatible api versions (between v2 and v3) which are affected. Pretty possible such more incompatible endpoints will arriving. To protect clients, which are bear against migration to not yet stable v3 and decided use maybe less effective, but definite more robust v2 version, it will be the better solution. This will allow to get transition to v3 more smooth and effective

**Pull request merged**
