### PR TITLE
Python: Add support for async context manager to auto-close connections

### PR DESCRIPTION
**Pull request by mrasband**
Since `.close` is required to close the aiohttp session, we can make the code simpler (and automatically close on all error cases) by using an [async context manager](https://www.python.org/dev/peps/pep-0492/#asynchronous-context-managers-and-async-with):

```
# this
try:
    exchange = ccxt.exchange({})
    return await exchange.fetch_balance()
finally:
    await exchange.close()

# becomes
async with ccxt.exchange({}) as exchange:
    return await exchange.fetch_balance()
```

This is opt-in, of course, so allows current usages to continue as normal.

### CODE REVIEW

**Comment by kroitor** [comment]
First of, thx for the pull request! ) 

One thing, though... Can you, please, explain this a bit to me, the following line doesn't want to work with my Python 3.6.2:

```Python
    if sys.version >= (3, 6):
```

```
TypeError: '>=' not supported between instances of 'str' and 'tuple'
```

Does that line work for you? Or should we compare to a string instead? Or should we match major/minor/patch numbers separately? Thx again!

**Comment by mrasband** [comment]
Oh shoot, that should be `version_info`, good catch thank you! I tested that in another script and lazily copied it.

```
>>> import sys
>>> sys.version_info >= (3, 5)
True
>>> sys.version_info
sys.version_info(major=3, minor=6, micro=5, releaselevel='final', serial=0)
>>> type(sys.version_info)
<class 'sys.version_info'>
>>> isinstance(sys.version_info, tuple)
True
>>> sys.version_info < (3, 5)
False
```

That looks better

**Comment by kroitor** [comment]
Unfortunately, there's still one more difficulty with merging this PR, namely, it will close the session on first __aexit__ rendering it impossible to do the following:

```Python
ccxt_exchange = ccxt.exchange()

# becomes
async with ccxt_exchange as exchange:
    return await exchange.fetch_balance()

# and then...
async with ccxt_exchange as exchange:
    return await exchange.fetch_balance()  # crash
```

@mrasband what do you think on the above?

**Comment by mrasband** [comment]
@kroitor You're probably most familiar with the use cases of the library, but most of mine revolve around some data download work to save off a bunch of data for clients. So the original use case in the OP are my intention:

```
async with ccxt.my_exchange({}) as exchange:
    balances  = await exchange.fetch_balance()['totals']
    tasks = await asyncio.wait([exchange.fetch_my_trades(), exchange.private1..., exchange.private2...])
    ...
```

However this is a good observation, I will make it re-open the client session on `__aenter__` if it is closed.

**Comment by mrasband** [comment]
🤔 On second look I am not sure that's possible if the user provides their own session, unless there is something with `aiohttp.ClientSession` I am overlooking. Are you familiar with any way to re-open a closed session?

**Comment by mrasband** [comment]
Sorry for the spam, thinking through this a little more and chatting with a few other asyncio based python devs - the use-case for context managers is typically expected to be single use as the intent is to dispose of resources after it has run.

For example, one wouldn't do this with a file:

```python
# INVALID
f = open('./my_file.json', 'rw')
with f:
    print(f.read())
with f:
    print(f.write())
```

As another sample from the aiohttp library, it supports the two options this currently supports, but not an arbitrary open/close of the same session: https://github.com/aio-libs/aiohttp/blob/master/aiohttp/client.py#L824-L828

**Pull request merged**
