### PR TITLE
binance: use v3, fetchDepositAddress

### PR DESCRIPTION
**Pull request by Deathamns**
#698
WIP, just pushing to public. Haven't tested all methods.
`fetchDepositAddress` returns the same address for BTC and BCH, don't know why.

### CODE REVIEW

**Comment by Deathamns** [comment]
> fetchDepositAddress returns the same address for BTC and BCH

Not just these two, and not only via the API, the web interface also returns the same addresses. I also tried to view deposit addresses for a few other coins, the first one returned a new address and then every other coin afterwards gave the same address back. So, I guess this is a binance issue.

Maybe @Ninj0r can say something about this?

**Comment by kroitor** [comment]
@Deathamns he said he is not responsible for the WAPI, he controls the main trading API only. They have different teams working on different parts of their system.

**Comment by Deathamns** [comment]
He may still forward the message...

**Comment by kroitor** [comment]
@Deathamns I've sent it to him, of course.

**Comment by kroitor** [comment]
```
Igor Kroitor, [29.11.17 13:21]
apparently, wapi returns the same address for BCH and BTC deposits

Ninj0r, [29.11.17 13:38]
while dangerous, I think this might be by design.

Ninj0r, [29.11.17 13:39]
I've asked the team; I'll let you know when I get a response.

Igor Kroitor, [29.11.17 13:39]
ok, thx

Ninj0r, [29.11.17 13:48]
Yeah, it's by design.

Igor Kroitor, [29.11.17 13:49]
> I also tried to view deposit addresses for a few other coins, the first one returned 
a new address and then every other coin afterwards gave the same address back.

Ninj0r, [29.11.17 13:49]
Yes, the same is done with the ERC20 tokens. All ERC20 tokens on an account use 
the same deposit address.

Igor Kroitor, [29.11.17 13:50]
I see, thanks for clarifying this, and, sorry for bothering

Ninj0r, [29.11.17 13:50] If you think this behavior should be changed, shoot an email 
to product@binance.com
```

**Comment by Deathamns** [comment]
Hmm. So, let's say that I want to withdraw 5 `BCH` from an exchange to Binance, then how would Binance know that I wanted to deposit into my `BCH` wallet, and not `BTC`?
I'm relatively knew to the crypto-currency world, so it's possible that I'm missing something very basic here.

**Comment by kroitor** [comment]
@Deathamns to put it simply, a BCH address is the same as a BTC address (same string), but that string stands for two different addresses (entities) in different blockchains. So if money arrives to the address via the BCH blockchain, it's obvious where it should go. Same with BTC.

**Comment by Deathamns** [comment]
Yeah, it does. Thanks. I just forgot that minor thing for a moment, where exchanges are built around blockchains, and they don't transfer currencies directly. No biggie.

**Pull request merged**
