### PR TITLE
unified fetchCurrencies interface with current status, withdrawal etc..

### PR DESCRIPTION
**Pull request by munrocket**
I think we really need this unified interface for checking status, get fullname of currency and withdrawal fees.

### CODE REVIEW

**Comment by munrocket** [comment]
This PR not fully working, i can't get why this code not transpiling to python

**Comment by munrocket** [comment]
In transpile.js i just added 1 line, but windows changed EOL.

**Comment by kroitor** [comment]
Hi! 

First of all, thx for your contributions!

It doesn't want to transpile because you violated several rules from the CONTRIBUTING doc, there should be no empty lines inside transpiled methods.

Also, I think we should use `fee` and `active` instead of `txFee` and `isActive`. That naming and structure does not look unified to me, it's a Bittrex-specific structure. We should actually see if we can derive the same structure from at least a few other exchanges. Can you do several other examples? 

BTW, there's a `.currencies` property (driven with market structures) on each exchange, have you considered linking currencies with markets? I think they should not be independent of each other...

We need to think more on this.

**Comment by munrocket** [comment]
>it's a Bittrex-specific structure

I think that we need something like this because:
1) We have several properties linked to one currency (not pair) such as
-withdrawal fees
-active status
-full names
-array of connected currency to saving arbitrage graph
etc..
2) Current model of withdrawal fees doesn't looks nice, because we store array currencies name for each property like fee and status. Maybe for trading fee is ok, because it's same to each other.

>We should actually see if we can derive the same structure from at least a few other exchanges. Can you do several other examples?

https://bittrex.com/api/v1.1/public/getcurrencies    
https://poloniex.com/public?command=returnCurrencies
https://www.cryptopia.co.nz/api/GetCurrencies

Maybe all transaction fees the same?

**Comment by kroitor** [comment]
@munrocket I mean, currently, if I merge this PR right away, we will have a `.currencies` property on Bittrex and a `fetchCurrencies()` method on Bittrex, and the difference is not very clear. That is somewhat confusing for a library user, because there are now two separate things for related data. And we should resolve that duplication and normalize currencies with markets + fetchCurrencies where possible (see how loadMarkets + fetchMarkets + setMarkets work).

**Comment by kroitor** [comment]
We probably also need to have both fees, deposit and withdraw for fiat currencies and withdraw fee (which is a txfee on most of exchanges) for cryptocurrencies...

**Comment by kroitor** [comment]
We think more like merging this PR, but we will have to work on it a little, so that currencies get loaded upon loading the markets. Thx again! Will push a few edits soon.

**Comment by munrocket** [comment]
>That is somewhat confusing for a library user, because there are now two separate things for related data. And we should resolve that duplication and normalize currencies with markets + fetchCurrencies where possible (see how loadMarkets + fetchMarkets + setMarkets work).

Yes, i don't really know how this will be transpiled in all languages, but in python as i know we can use statement that `.currencies` property is literally equal `fetchCurrencies().keys()` in this new notation. That's why to be honest we don't need new method. We just need to extend `.currencies` somehow in js. Or if we can't do this, we can use additionall method with name that not confused others.

**Comment by munrocket** [comment]
What if not all exchanges support fees request? I don't thinked about this lol.
For these purposes you created a Unified fee that way? Anyway we need active status somewhere.

**Comment by kroitor** [comment]
@munrocket , yeah, there's a little more to it, like precision digits and some other properties, but don't worry... we think that we figured out how to unify currencies and markets and we will add fetchCurrencies into the loadMarkets call this way or another. Thx!

**Comment by munrocket** [comment]
@kroitor If they will not update every second with loadMarkets it will be cool. You can add one example and i will help you with another exchanges right way.

**Comment by kroitor** [comment]
@munrocket, sure, loadMarkets are cached, so this is only called once, as described in the Manual... I will add a few examples and will let you know. Thx!

**Comment by munrocket** [comment]
@kroitor Ok i deleted one excess space and source transpiled successfully. What will we do?

**Comment by kroitor** [comment]
@munrocket I'm going to merge it very soon )

**Pull request merged**
