### PR TITLE
[WIP] [Deribit] Implementation for version 2 API

### PR DESCRIPTION
**Pull request by lacksfish**
Builds just fine, tests for JS pass.

```bash
root@zzzzzzzzzzzzz:/ccxt# node run-tests --js deribit2
Testing { exchanges: ["deribit2"], symbol: "all", keys: { '--js': true, '--php': false, '--python': false, '--python2': false, '--python3': false }, maxConcurrency: 5 } (run-tests.js:252)
[100%] Testing deribit2 OK (testExchange @ run-tests.js:169)
All done, 1 succeeded (run-tests.js:273)
```

One little thing though, for python it still gives me:

```bash
root@zzzzzzzzzzzzz:/ccxt# node run-tests --python deribit2
Testing { exchanges: ["deribit2"], symbol: "all", keys: { '--js': false, '--php': false, '--python': true, '--python2': false, '--python3': false }, maxConcurrency: 5 } (run-tests.js:252)
[100%] Testing deribit2 FAIL (testExchange @ run-tests.js:169)

FAILED deribit2 (Python): (explain @ run-tests.js:187)

        <type 'exceptions.KeyError'> 'deribit2' 
        
          File "python/test/test.py", line 409, in <module>
            main()
        
          File "python/test/test.py", line 386, in main
            exchange = exchanges[argv.exchange] (explain @ run-tests.js:190)
FAIL ["deribit2"] (run-tests.js:268)
All done, 1 failed (run-tests.js:273)
```

My guess is it would be a minor detail missing in a config? Any hints highly appreciated.

### CODE REVIEW

**Comment by kroitor** [comment]
> My guess is it would be a minor detail missing in a config? Any hints highly appreciated.

If it builds fine, then it means that you have a `ccxt` in your site-packages installed which interferes with the built version in the ccxt repo you're trying to test. You need to pip uninstall the global ccxt to check the local one. Let me know if that is the case.

**Comment by kroitor** [comment]
@lacksfish have you tested the private APIs? We need to make sure that it conforms to the unified API, however `node run-tests` will not test those unless you've configured the `keys.local.json` or `keys.json`. We also need to verify that it handles the common exceptions, AuthenticationError, InsufficientFunds...

**Comment by lacksfish** [comment]
I did run it with a pair of mainnet API keys set in my `keys.local.json`. Please double-check though :)

Error handling I mostly migrated over from the v1 API ccxt implementation, let me review this once more, will amend title to WIP

**Comment by lacksfish** [comment]
All the error codes are updated, unfortunately, tests only pass for the JS version. I still get the following error for the transpiled python libs:

```sh
FAILED deribit2 (Python): (explain @ run-tests.js:187)

        <type 'exceptions.KeyError'> 'deribit2' 
        
          File "python/test/test.py", line 410, in <module>
            main()
        
          File "python/test/test.py", line 387, in main
            exchange = exchanges[argv.exchange] (explain @ run-tests.js:190)
```

Any help here? :)

**Comment by XhrCkYsSgZokJL** [comment]
Is there still a push to bring up v2?  Does it need assistance?   Would be happy to look at it this weekend.

**Comment by kroitor** [comment]
@lacksfish @XhrCkYsSgZokJL pardon for the delays with the answer on my side, i'm a bit overloaded and occupied with the work on the other parts of the lib right now, i'll do my best to review it asap and will get back to you with feedback.

**Comment by orikalinski** [comment]
Hey guys, were you able to use the trading api? account api works well with the code above but
For some reason i'm getting bad request for the create / cancel / edit order.

**Comment by CryptoGnome** [comment]
Looks like this is complete, is there a reason it has not made it to the main branch yet?

**Comment by kroitor** [comment]
@CryptoGnome it doesn't really pass the tests yet: https://travis-ci.org/ccxt/ccxt/builds/563114170#L2012

**Comment by mostar** [comment]
What the status of it?

**Comment by CryptoGnome** [comment]
Bump, any updates on this?

**Comment by kroitor** [comment]
@CryptoGnome it is still broken, so we can't merge it as is, I didn't have the time to fix it yet, but will hopefully resolve the integration backlog after releasing CCXT Pro soon.

**Comment by kroitor** [comment]
Deribit v2 has been added in CCXT 1.23.88+: https://github.com/ccxt/ccxt/issues/6602

**Pull request merged**
