### PR TITLE
 binance: parseOrder: amount/cost: stick to precision

### PR DESCRIPTION
**Pull request by mkutny**
Without it, I happen to get something like `0.041830000000000006` as a remaining amount.

### CODE REVIEW

**Comment by kroitor** [comment]
I'll merge this after #2397 if you don't mind, as current implementations of *ToPrecision don't work very well in Python, haven't switched to the new decimalToPrecision implementation yet. #2397 is currently my topmost priority. Will let you know asap.

**Comment by mkutny** [comment]
I don't mind but this PR is unrelated to #2397 as it uses old implementation from the base class (e.g. does not use *ToPrecision).

**Comment by kroitor** [comment]
I mean, it uses amountToPrecision, priceToPrecision and costToprecision which are known to be broken  in Python, whereas the newcoming decimalToPrecision does not have that bug (to be merged very soon). Thanks for your participation, and respect!)

**Comment by mkutny** [comment]
Ok, clear now.

**Comment by frosty00** [comment]
@kroitor are we still using amountToPrecision, priceToPrecision. They could still be rewritten in the python base class so that

```
def price_to_precision(self, symbol, price):
    return decimal_to_precision(price, ...)
```

**Comment by kroitor** [comment]
@frosty, yep, exactly, however, I would do that after merging the transpileable tests for that functionality, I'm mostly done with it, but haven't implemented the negative precisions uniformly yet (some major exchanges like Binance use them). I'll keep you informed here and in the other PRs on this, hope to get it done soon, and then we can start the full-on migration from the older versions of precision methods to the newest ones.

**Pull request merged**
