### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by vikachirsky**
Added required library "six".

### CODE REVIEW

**Comment by mariuszskon** [comment]
I stumbled upon this as well. Surely it would be better to add this as a dependency in the python package?

**Comment by kroitor** [comment]
@vikachirsky @mariuszskon thx for your feedback! We're working on stripping out the `six` dependency, since it was mostly needed for the Python2 compatibility.

**Comment by vikachirsky** [comment]
> @vikachirsky @mariuszskon thx for your feedback! We're working on stripping out the `six` dependency, since it was mostly needed for the compatibility with the now-deprecated Python2.

thx @kroitor  , but "six" package is also required even for Python 3.9 (tested in clear venv and conda environments)

**Comment by kroitor** [comment]
@vikachirsky do you mean the most recent version of the lib?

**Pull request closed without merging**
