### PR TITLE
new exchange: abucoins (partial support)

### PR DESCRIPTION
**Pull request by lfern**
Not all API method are implemented, but this could be used as initial version.

### CODE REVIEW

**Comment by lfern** [comment]
Sorry, I am editing from github and I made some lint errors. I have just resolve them. There are still errors in python module. Is it necesary to implement python/php abuicoins module for merging into master?

**Comment by kroitor** [comment]
> Is it necesary to implement python/php abuicoins module for merging into master?

Nope, it's not ) The only thing that is necessary, is the JS. However, we need to make sure the JS code is clean, namely check against these rules: https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#derived-exchange-classes 

Let me know if you have further questions with it. Thx!

**Comment by kroitor** [comment]
@lfern see this build log to check for errors: https://travis-ci.org/ccxt/ccxt/builds/349720695?utm_source=github_status&utm_medium=notification

**Comment by kroitor** [comment]
Fixes #1281

**Comment by lfern** [comment]
> @lfern see this build log to check for remaining error (with the Object keyword): https://travis-ci.org/ccxt/ccxt/builds/349720695?utm_source=github_status&utm_medium=notification

I think this error is raised because I didn't create python class:
./python/ccxt/abucoins.py:417:23: F821 undefined name 'Object'
./python/ccxt/async/abucoins.py:417:23: F821 undefined name 'Object'

How can I create an empty python body to prevent this error?

**Comment by kroitor** [comment]
@lfern 

>

Nope, it is because of this particular line: https://github.com/ccxt/ccxt/pull/2135/files#diff-2b8f2f79baa16cb0a416a374f385e07bR445

You can't use `Object.assign`, use the assignment operator instead, as the `Object.assign` isn't portable/transpileable to Python or PHP at all. Apart from that particular line, I don't see any remaining transpilation errors. ;)

**Comment by kroitor** [comment]
You could just delete the Object.assign and write

```JavaScript
            headers = {
                'AC-ACCESS-KEY': this.apiKey,
                'AC-ACCESS-SIGN': signature, // this.decode (signature),
                'AC-ACCESS-TIMESTAMP': nonce,
                'AC-ACCESS-PASSPHRASE': this.password,
            };
```

But the way you did it is also fine, nevermind ) Thx a lot! Will spend some time testing it and will merge soon.

**Comment by lfern** [comment]
Ok, I think it is fixed. But it fails when testing abucoins:

[ExchangeError] ('abucoins https://api.abucoins.com/products GET [Errno 1] _ssl.c:510: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure',) (explain @ run-tests.js:173)

When I test this API call in node it works. Maybe python needs extra configuration for SSL validation?

**Comment by kroitor** [comment]
Ok, now we have passed over the transpilation stage, and there remains the testing itself. Thx for your effort!

**Pull request closed without merging**
