### PR TITLE
fix(bitget): setMarginMode removed

### PR DESCRIPTION
**Pull request by samgermain**
marginMode should be set using createOrder via params["marginMode"]

- removes setMarginMode method (this method does not set the marginMode)
- edits createOrder docstring
- relocates response comments in fetchPositions

fixes: #21435

### CODE REVIEW

**Comment by carlosmiei** [comment]
@samgermain 
> removes setMarginMode method (this method does not set the marginMode)

I'm not so sure about this, why I call setMarginMode I can clearly see the margin mode changing in the UI
image
image

**Comment by samgermain** [comment]
> @samgermain
> 
> > removes setMarginMode method (this method does not set the marginMode)
> 
> I'm not so sure about this, why I call setMarginMode I can clearly see the margin mode changing in the UI image image

but this doesn't change the api usage, any order created using the api will be cross unless `params["marginMode"]` is assigned in `createOrder`. This is misleading to the user. The way that our `setMarginMode` method should be used is that orders created after calling it should be in the marginMode that was set in `setMarginMode`

**Comment by carlosmiei** [comment]
@samgermain We can improve the docs/ add an example but that does not mean the endpoint itself is not working

**Comment by samgermain** [comment]
> @samgermain We can improve the docs/ add an example but that does not mean the endpoint itself is not working

Our codebase is for use with the api. The endpoint only changes whether the market is set to cross/isolated relative to the web interface. This means nothing to api users. As far as our codebase goes the method is useless

**Pull request closed without merging**
