### PR TITLE
add BW.com exchange

### PR DESCRIPTION
**Pull request by mukedian0**
bw

### CODE REVIEW

**Comment by mukedian0** [comment]
any updates? thx.

**Comment by ourarash** [comment]
Is this PR going to be merged into the main branch?

**Comment by kroitor** [comment]
@ourarash yes, but we will have to rework and polish it a bit, because it still has errors in the code. We will do this as soon as we can: https://github.com/ccxt/ccxt/wiki/FAQ

**Comment by kroitor** [comment]
Merged in #5757

**Pull request closed without merging**
