### PR TITLE
Handle cryptopia returning non-string ticker id

### PR DESCRIPTION
**Pull request by tchklovski**
fix for #1912

### CODE REVIEW

**Comment by kroitor** [comment]
Oops, I've just uploaded a fix for it %)

**Comment by kroitor** [comment]
https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

**Comment by tchklovski** [comment]
got it, thanks for the fix!

**Comment by kroitor** [comment]
@tchklovski thx to you for reporting!

**Pull request closed without merging**
