### PR TITLE
binance - reorganizing exception codes

### PR DESCRIPTION
**Pull request by ttodua**

### CODE REVIEW

**Comment by ttodua** [comment]
@carlosmiei PR ready. had to make many changes and where there where 3 or more (among 5) market types match for same error code, i've migrated them into "commons" block, and for remaining 2 (or 1) market type, i've overrided with generic 'ExchangeError' (because we don't have any info about that market type error, so we have to avoid misleading users, thus we need a blanket overrides for them)

**Comment by ttodua** [comment]
@carlosmiei lmk if this needs updates

**Comment by ttodua** [comment]
@carlosmiei lmk also on this, this was last needed update in exceptions to have final version

**Comment by ttodua** [comment]
i had checked those error codes one by one across 5 api docs (spot/inv/lin/opt/portf), so, what can i say is that, these would be the most exact representation we can offer for now

**Comment by carlosmiei** [comment]
@ttodua right now is this a breaking change or only a reorg?

**Comment by ttodua** [comment]
this should not be breaking change, i've just combined same error codes under "common" ones.
minor changes could have been in cases, where i.e. in 3 markets, previously, I might had set i.e. `OperationRejected` for same problem, while in 4th market i might had `BadRequest`, and now, as I've combined the same exception type could be `OperationRejected`, thus shadowing that 4th market's `BadRequest` with it. however, those occasions would have been very rare. users shouldn't notice this update

**Comment by ttodua** [comment]
but, as long as it's binance, i think (if you agree) i'll write some snippet to manually check and compare the tree difference between the two commits.
ok, give me some more time then, i'll switch this to draft

**Comment by ttodua** [comment]
@carlosmiei i have compared each types and these few ones were 'breaking' changes:
```
spot:
-1013:  OperationFailed   --> BadRequest


linear
-2010:  OrderNotFound     --> InvalidOrder
-4016:  OperationRejected --> BadRequest
-4061:  BadRequest            --> OperationRejected
-4082:  OperationRejected --> BadRequest
-4083:  OperationFailed     --> OperationRejected
```

**Comment by ttodua** [comment]
@carlosmiei ^

**Pull request merged**
