### PR TITLE
fix not getting id on liqui when one takes more than 1 order

### PR DESCRIPTION
**Pull request by hippylover**

### CODE REVIEW

**Comment by kroitor** [comment]
Fixed in https://github.com/ccxt/ccxt/commit/5b1ca28fe58403d49fb7bb08a85f8894e5edf12a

**Comment by hippylover** [comment]
Hmm. Are you sure this fixed the problem? Maybe it fixed an unrelated problem. If you see: https://github.com/ccxt/ccxt/pull/1456 order_id is sat to 0 when one takes multiple orders at the same time and that is why i sat it to init_order_id which is sat to a useable order number whether one takes one or more orders at the same time.

**Comment by kroitor** [comment]
@hippylover yep, pretty sure I fixed it it exactly as you said. Why? Doesn't it work for you?

**Comment by kroitor** [comment]
@hippylover basically, I fixed the safe_string method that was causing a faulty behaviour, so now the id is properly populated form either `order_id` or `init_order_id`, if `order_id === 0`. This was the problem, and it should be gone now.

**Comment by hippylover** [comment]
ah. ok, i saw in the commit you linked you only changed safe_string method.

**Pull request closed without merging**
