### PR TITLE
BtcTurk APIs are updated with new urls and data types

### PR DESCRIPTION
**Pull request by yucelalbar**

### CODE REVIEW

**Comment by kroitor** [comment]
Hi! Can you plz move those edits to the JS file instead of Py? 

- https://github.com/ccxt/ccxt/pull/7825/files#diff-ec37b2564e4917ddea5f24c835d104c2687167cb93f13154d441dc21dd0dc6e7R3
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#multilanguage-support
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#transpiled-generated-files

**Comment by c0dehunter** [comment]
FYI; I just tried this and it doesn't work with fetchBalance(). It seems old API v1 endpoints are being used in this code.

Referenced from https://github.com/ccxt/ccxt/pull/6945#issuecomment-728993233

**Comment by kroitor** [comment]
@c0dehunter ah, pardon, this PR is not transpileable yet, we will convert it asap.

**Comment by c0dehunter** [comment]
> @c0dehunter ah, pardon, this PR is not transpileable yet, we will convert it asap.

It won't help as "private" still points to old v1 API: https://github.com/ccxt/ccxt/pull/7825/files#diff-ec37b2564e4917ddea5f24c835d104c2687167cb93f13154d441dc21dd0dc6e7R43

**Comment by kroitor** [comment]
@c0dehunter yep, we will have to combine, fix, rewrite and merge the two PRs, will get to it as soon as we can. Thx for your help, much appreciated!

**Review by jonhpham — APPROVED** [review]

**Pull request closed without merging**
