### PR TITLE
feat(oceanex): fetchDepositAddress

### PR DESCRIPTION
**Pull request by samgermain**
```
% oceanex fetchDepositAddressesByNetwork USDT
2024-09-25T03:23:07.082Z
Node.js: v18.12.0
CCXT v4.4.6
oceanex.fetchDepositAddressesByNetwork (USDT)
2024-09-25T03:23:13.463Z iteration 0 passed in 3673 ms

{
  USDT: {
    info: {
      chain_name: 'ERC20',
      currency_id: 'usdt',
      address: '0x6d42ba2932a655001c41d5c1549d28e2f68fcb9a',
      memo: '',
      deposit_status: 'enabled'
    },
    currency: 'USDT',
    address: '0x6d42ba2932a655001c41d5c1549d28e2f68fcb9a',
    tag: undefined,
    network: 'ERC20'
  }
}
2024-09-25T03:23:13.463Z iteration 1 passed in 3673 ms
```

----------

Could not test in python due to this error that always happens for oceanex PRs

```
ValueError: ('Could not deserialize key data. The data may be in an incorrect format, it may be encrypted with an unsupported algorithm, or it may be an unsupported key type (e.g. EC curves with explicit parameters).', [<OpenSSLError(code=503841036, lib=60, reason=524556, reason_text=unsupported)>])
oceanex requires to release all resources with an explicit call to the .close() coroutine. If you are using the exchange instance with async coroutines, add `await exchange.close()` to your code into a place when you're done with the exchange and don't need the exchange instance anymore (at the end of your async coroutine).
```

### CODE REVIEW

**Comment by samgermain** [comment]
[failed build error](https://app.travis-ci.com/github/ccxt/ccxt/builds/272465572), I don't know what it means

```
[INFO:MAIN] Exchange to test: oceanex

file:///home/travis/build/ccxt/ccxt/js/src/test/tests.helpers.js:11

    throw new Error(exceptionMessage(e));

    ^

Error: [Error] Error: [Error] Error: join.decode input should be string

    at decode (file:///home/travis/build/ccxt/ccxt/js/src/static_dependencies/scure-base/index.js:59:23)

    at file:///home/travis/build/ccxt/ccxt/js/src/static_dependencies/scure-base/index.js:9:37

    at jwt (file:///home/travis/build/ccxt/ccxt/js/src/base/functions/rsa.js:33:37)

    at oceanex.sign (file:///home/travis/build/ccxt/ccxt/js/src/oceanex.js:1019:31)

    at oceanex.fetch2 (file:///home/travis/build/ccxt/ccxt/js/src/base/Exchange.js:3874:30)

    at oceanex.request (file:///home/travis/build/ccxt/ccxt/js/src/base/Exchange.js:3904:27)

    at oceanex.partial (file:///home/travis/build/ccxt/ccxt/js/src/base/Exchange.js:402:78)

    at oceanex.fetchDepositAddressesByNetwork (file:///home/travis/build/ccxt/ccxt/js/src/oceanex.js:930:37)

    at async callExchangeMethodDynamically (file:///home/travis/build/ccxt/ccxt/js/src/test/tests.helpers.js:119:12)

    at async testMainClass.testRequestStatically (file:///home/travis/build/ccxt/ccxt/js/src/test/tests.js:1075:17)

    at process.<anonymous> (file:///home/travis/build/ccxt/ccxt/js/src/test/tests.helpers.js:19:11)

    at process.emit (node:events:514:28)

    at emit (node:internal/process/promises:149:20)

    at processPromiseRejections (node:internal/process/promises:283:27)

    at process.processTicksAndRejections (node:internal/process/task_queues:96:32)

    at process.<anonymous> (file:///home/travis/build/ccxt/ccxt/js/src/test/tests.helpers.js:11:11)

    at process.emit (node:events:514:28)

    at process._fatalException (node:internal/process/execution:149:25)
```

**Comment by carlosmiei** [comment]
image
this call is throwing the error

**Comment by samgermain** [comment]
> image this call is throwing the error

Inside that JWT method `base64ToBinary` is being called and the value passed into it is `false`, whereas the method is expecting a string

This error isn't thrown if we remove `utf8.encode(` surrounding `secret` [on this line ](https://github.com/ccxt/ccxt/blob/04f7eebc4deb83b9d847929889621e814dba59d3/js/src/base/functions/rsa.js#L39)

I think it can't be encoded because it's an RSA key or it should be a pem. I'm guessing that this is the same issue causing the python cli error

**Comment by samgermain** [comment]
> image this call is throwing the error

Prior to this, [this branch](https://github.com/ccxt/ccxt/blob/2592465bfd5ce898d47ca4d365ce6efb5222ed39/js/src/base/functions/rsa.js#L38) was not being executed ever, because this is the first time that jwt is being called with the parameter `isRSA` being set to true

**Comment by samgermain** [comment]
It's [coming from here](https://github.com/ccxt/ccxt/blob/04f7eebc4deb83b9d847929889621e814dba59d3/js/src/static_dependencies/jsencrypt/lib/jsbn/rsa.js#L285), `n` isn't defined

**Comment by carlosmiei** [comment]
@samgermain we just needed to override the secret used in the test here: https://github.com/ccxt/ccxt/pull/23811/commits/6e5cdf3ca55f58a66d5779c598daa278a4412013

**Comment by samgermain** [comment]
> @samgermain we just needed to override the secret used in the test here: [6e5cdf3](https://github.com/ccxt/ccxt/commit/6e5cdf3ca55f58a66d5779c598daa278a4412013)

What is `this.n` though and why does overriding the secret change things? I tried changing the secret value to something like 
```
"-----BEGIN RSA PRIVATE KEY-----secretsecret-----END RSA PRIVATE KEY-----"
```
and was still receiving the error

**Pull request merged**
