### PR TITLE
Btcalpha - fix ts & ob (from `skipped` list)

### PR DESCRIPTION
**Pull request by ttodua**
about fetchOrderBook not working: 
- https://btc-alpha.github.io/api-docs/#get-orderbook
as seen in API, the request https://btc-alpha.com/api/v1/orderbook/BTC_USD should work, but it doesn't work. neither adding parameters change anything.

### CODE REVIEW

**Comment by carlosmiei** [comment]
LGTM ✅

**Review by carlosmiei — APPROVED** [review]

**Comment by ttodua** [comment]
@ndubel thanks for the feedback! Strange, but till this moment I got different exception message.
I'll revert this PR.

**Comment by ttodua** [comment]
strange, the last `/` slash made the problem in ccxt.

**Comment by carlosmiei** [comment]
@ttodua well you found the issue, kudos 🙂 , we can fix fetchOrderBook now and re-enable it  inside `has` 

Curiously even their docs show the / in the end
image

**Comment by ttodua** [comment]
I've found further glitch with them :) if you look best bid vs best ask, the prices are overlapping each other in same response - bid price is higher than ask price :)

**Pull request merged**
