### PR TITLE
ascendex - fetchTransfers

### PR DESCRIPTION
**Pull request by pcriadoperez**
No endpoint to `fetchTransfers`

### CODE REVIEW

**Comment by kroitor** [comment]
What about these: https://github.com/ccxt/ccxt/pull/12503/files#diff-29cf0958543c67805f333e75031ae44e991de486979a39331fc05baf14dfd779R169 ?

**Comment by pcriadoperez** [comment]
In the link I only see:
```
'fetchTransfer': false,
'fetchTransfers': false,
```

Which endpoint did you mean?

**Comment by kroitor** [comment]
Pardon, i mean these endpoints: https://github.com/pcriadoperez/ccxt/blob/ascendex-fetchTransfers/js/ascendex.js#L169

**Comment by kroitor** [comment]
Nevermind, those are post-endpoints, my bad.

**Pull request merged**
