### PR TITLE
fix(poloniex): handle new ticker structure

### PR DESCRIPTION
**Pull request by paulofreitas**
- Fix `parseTicker()` method to handle new ticker structure (handles new `bid` and `ask` values and changes `percentChange` to `dailyChange`)
- Update `fetchTicker()` and `fetchTickers()` methods for updated ticker structure

### CODE REVIEW

**Comment by carlosmiei** [comment]
Hello again @paulofreitas, thanks once again 🙂  will check it soon

**Review by carlosmiei — APPROVED** [review]

**Comment by paulofreitas** [comment]
> Hello again @paulofreitas, thanks once again 🙂 will check it soon

Hey @carlosmiei, glad to help once again, thanks again for reviewing! 🙂

Note that I left `askQuantity` and `bidQuantity` out because it didn't matched their actual volumes, I later found in their [docs](https://docs.poloniex.com/#public-endpoints-market-data- ticker) they're meant to be the _best_ bid/ask quantity and not the total, don't know how this is useful to anyone but it's their API. 😄

**Comment by carlosmiei** [comment]
> askQuantity

@paulofreitas Yeah but I think that is actually the goal 🙂 

from the docs:

```
       'bidVolume':     float, // current best bid (buy) amount (may be missing or undefined)
       'ask':           float, // current best ask (sell) price
       'askVolume':     float, // current best ask (sell) amount (may be missing or undefined)
```

We might have some inconsistencies in across the lib though.

**Comment by paulofreitas** [comment]
> @paulofreitas Yeah but I think that is actually the goal 🙂

Oh, you're right, I just read [/src/test/Exchange/base/test.ticker.ts](https://github.com/ccxt/ccxt/blob/34311c551fed07eb22b43043a982c706d4fa52b3/ts/src/test/Exchange /base/test.ticker.ts#L15), tbh I thought it was supposed to be he total but yeah, it's exactly what Poloniex provides. 😀

I think I've seen some exchanges display the total in their APIs, but to be sure I'll look for inconsistencies, if I find any I'll come with the patch. Thanks again for leading me into the right direction, I appreciate that! 🙂

**Pull request merged**
