### PR TITLE
Tradesatoshi 1781

### PR DESCRIPTION
**Pull request by morevproj**
Added the rest methods and corrected few added before. Guys from tabtrader and I would like to add tradesatoshi to ccxt. "sign" method is changed because the previous didn't work well with private methods.

### CODE REVIEW

**Comment by morevproj** [comment]
Hm, I wanted to add changes to PR 1781 but not sure I did all the correct way.
And appVeyor built has failed before it even got to the actual building.
Could you help me to add changes to PR 1781 and overcome problems with addVeyor built?

**Comment by kroitor** [comment]
@morevproj i've merged the `master` branch into `tradesatoshi`, because appveyor has updated php73 → php74. However, it breaks during the build here:

- https://ci.appveyor.com/project/ccxt/ccxt/builds/29206988#L555

**Comment by kroitor** [comment]
https://github.com/ccxt/ccxt/issues/1576#issuecomment-604736399

**Comment by kroitor** [comment]
https://twitter.com/TradeSatoshi/status/1230509341142220800

**Pull request closed without merging**
