### PR TITLE
extend in php

### PR DESCRIPTION
**Pull request by ttodua**
for the sake of completeness (external uses for users to simplify unified use of `extend`) we can have it in php too.
also, in tests/custom snippets we somewhere also need to use `.extend` in unifiish way to avoid custom string replacing in transpiler.

### CODE REVIEW

**Comment by carlosmiei** [comment]
@ttodua right now, we convert it directly to array_merge, should we remove this replacement since we're implementing extend?

**Comment by carlosmiei** [comment]
image

**Comment by ttodua** [comment]
I am not sure, you should decide. in my opinion, as long as "extend" is not native javascript function (and neither native methods in other langs) we should not convert it to native 'array_merge' in php, and instead use similarly base method 'extend' (its body does not matter what implementation is in the body, either oneline array_merge or array_merge_recursive or etc).
so, you should decide.

**Comment by carlosmiei** [comment]
@ttodua Yes I would rather use the implementation inside `exchange.php` to make it more consistent with the other languages and easier to update if needed

**Comment by carlosmiei** [comment]
> ok, so what is the next step now, should we merge this at first, or?

@ttodua I think we have to remove the transpilation step from extend to array_merge first from transpile.js

**Comment by ttodua** [comment]
I meant this PR to be straightforward (so i could use 'extend' quickly), while removing the transpilation might involve deeper changes and more thorough review (i.e. if some sub-tests /other php files/examples files, where in php there is no `exchange` object available and array_merge could be used in plain). i'll revise that's a bit later

**Comment by carlosmiei** [comment]
@ttodua it's a oneline fix
image

**Comment by ttodua** [comment]
done Y.

**Comment by ttodua** [comment]
@carlosmiei PR passes practically

**Pull request merged**
