### PR TITLE
fix(bybit): handle inverse futures subscription

### PR DESCRIPTION
**Pull request by carlosmiei**
- relates to https://github.com/ccxt/ccxt/issues/22884

### CODE REVIEW

**Comment by carlosmiei** [comment]
DEMO

```
 p bybit watchTrades  "BTC/USD:BTC-241227" --sandbox          
Python v3.11.9
CCXT v4.3.75
bybit.watchTrades(BTC/USD:BTC-241227)
[{'amount': 1.0,
  'cost': 1.7136051682331e-05,
  'datetime': '2024-08-06T15:01:40.944Z',
  'fee': None,
  'fees': [],
  'id': '2edf5d5c-fc67-5baf-9051-c23abda0094d',
  'info': {'BT': False,
           'L': 'ZeroPlusTick',
           'S': 'Buy',
           'T': 1722956500944,
           'i': '2edf5d5c-fc67-5baf-9051-c23abda0094d',
           'p': '58356.50',
           's': 'BTCUSDZ24',
           'v': '1'},
  'order': None,
  'price': 58356.5,
  'side': 'buy',
  'symbol': 'BTC/USD:BTC-241227',
  'takerOrMaker': None,
  'timestamp': 1722956500944,
  'type': None}]
```

**Comment by carlosmiei** [comment]
```
p bybit watchOrders "BTC/USD:BTC-241227" --sandbox          
Python v3.11.9
CCXT v4.3.75
bybit.watchOrders(BTC/USD:BTC-241227)
[{'amount': 1.0,
  'average': 58377.12,
  'clientOrderId': None,
  'cost': 1.713e-05,
  'datetime': '2024-08-06T15:02:13.821Z',
  'fee': {'cost': 1e-08, 'currency': 'BTC'},
  'fees': [{'cost': 1e-08, 'currency': 'BTC'}],
  'filled': 1.0,
  'id': '9e8cab7a-2bcb-479c-93e9-a9a755da2d69',
  'info': {'avgPrice': '58377.12',
           'blockTradeId': '',
           'cancelType': 'UNKNOWN',
           'category': 'inverse',
           'closeOnTrigger': False,
           'createType': 'CreateByUser',
           'createdTime': '1722956533821',
           'cumExecFee': '0.00000001',
           'cumExecQty': '1',
           'cumExecValue': '0.00001713',
           'isLeverage': '',
           'lastPriceOnCreated': '58356.50',
           'leavesQty': '0',
           'leavesValue': '0',
           'orderId': '9e8cab7a-2bcb-479c-93e9-a9a755da2d69',
           'orderIv': '',
           'orderLinkId': '',
           'orderStatus': 'Filled',
           'orderType': 'Market',
           'placeType': '',
           'positionIdx': 0,
           'price': '61274.00',
           'qty': '1',
           'reduceOnly': False,
           'rejectReason': 'EC_NoError',
           'side': 'Buy',
           'slLimitPrice': '',
           'slTriggerBy': 'UNKNOWN',
           'smpGroup': 0,
           'smpOrderId': '',
           'smpType': 'None',
           'stopLoss': '0.00',
           'stopOrderType': 'UNKNOWN',
           'symbol': 'BTCUSDZ24',
           'takeProfit': '0.00',
           'timeInForce': 'IOC',
           'tpLimitPrice': '',
           'tpTriggerBy': 'UNKNOWN',
           'tpslMode': 'UNKNOWN',
           'triggerBy': 'UNKNOWN',
           'triggerDirection': 0,
           'triggerPrice': '0.00',
           'updatedTime': '1722956533824'},
  'lastTradeTimestamp': 1722956533824,
  'lastUpdateTimestamp': 1722956533824,
  'postOnly': False,
  'price': 61274.0,
  'reduceOnly': False,
  'remaining': 0.0,
  'side': 'buy',
  'status': 'closed',
```

**Comment by dudalev** [comment]
fyi - it also happens with options, e.g. SOL/USDC:USDC-240816-115-P

**Comment by carlosmiei** [comment]
@dudalev Can you please elaborate a bit more on the issue you're facing with options?

**Comment by dudalev** [comment]
just the same traceback as with inverve futures - i reckon everything that goes to wss://stream.bybit.com/v5/public/option fails in the same way:

`2024-08-06T15:16:42.004Z connecting to wss://stream.bybit.com/v5/public/option with timeout 10000 ms
2024-08-06T15:16:42.505Z connected
2024-08-06T15:16:42.505Z ping loop
2024-08-06T15:16:42.505Z sending {'req_id': 2, 'op': 'ping'}
2024-08-06T15:16:42.506Z sending {'op': 'subscribe', 'req_id': 1, 'args': ['orderbook.500.SOL-16AUG24-115-P']}
2024-08-06T15:16:42.668Z message {"args":["1722957402583"],"op":"pong"}
2024-08-06T15:16:42.668Z message {"success":true,"conn_id":"bfc43e81-31c7-4878-9429-c27f8876fbde","data":{"failTopics":[],"successTopics":["orderbook.500.SOL-16AUG24-115-P"]},"type":"COMMAND_RESP"}

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[17], line 1
----> 1 res = await exchange.watch_order_book("SOL[/USDC](http://10.244.42.110:8888/USDC):USDC-240816-115-P")

File ~/.cache/pypoetry/virtualenvs/scrape2-AgR29CFR-py3.12/lib/python3.12/site-packages/ccxt/pro/bybit.py:635, in bybit.watch_order_book(self, symbol, limit, params)
    626 async def watch_order_book(self, symbol: str, limit: Int = None, params={}) -> OrderBook:
    627     """
    628     watches information on open orders with bid(buy) and ask(sell) prices, volumes and other data
    629     :see: https://bybit-exchange.github.io/docs/v5/websocket/public/orderbook
   (...)
    633     :returns dict: A dictionary of `order book structures <[https://docs.ccxt.com/#/?id=order-book-structure>`](https://docs.ccxt.com/#/?id=order-book-structure%3E%60) indexed by market symbols
    634     """
--> 635     return await self.watch_order_book_for_symbols([symbol], limit, params)

File ~/.cache/pypoetry/virtualenvs/scrape2-AgR29CFR-py3.12/lib/python3.12/site-packages/ccxt/pro/bybit.py:670, in bybit.watch_order_book_for_symbols(self, symbols, limit, params)
    668     messageHash = 'orderbook:' + symbol
    669     messageHashes.append(messageHash)
--> 670 orderbook = await self.watch_topics(url, messageHashes, topics, params)
    671 return orderbook.limit()

File ~/.cache/pypoetry/virtualenvs/scrape2-AgR29CFR-py3.12/lib/python3.12/site-packages/ccxt/pro/bybit.py:1811, in bybit.watch_topics(self, url, messageHashes, topics, params)
   1805 request: dict = {
   1806     'op': 'subscribe',
   1807     'req_id': self.request_id(),
   1808     'args': topics,
   1809 }
   1810 message = self.extend(request, params)
-> 1811 return await self.watch_multiple(url, messageHashes, message, topics)

File ~/.cache/pypoetry/virtualenvs/scrape2-AgR29CFR-py3.12/lib/python3.12/site-packages/ccxt/async_support/base/ws/future.py:41, in Future.race.<locals>.callback(done)
     39 for i, f in enumerate(complete):
     40     try:
---> 41         f.result()
     42     except ExchangeClosedByUser as e:
     43         if len(pending) == 0 and i == len(complete) - 1:

File ~/.cache/pypoetry/virtualenvs/scrape2-AgR29CFR-py3.12/lib/python3.12/site-packages/ccxt/async_support/base/ws/fast_client.py:27, in FastClient.receive_loop.<locals>.handler()
     25 message = self.stack.popleft()
     26 try:
---> 27     self.handle_message(message)
     28 except Exception as error:
     29     self.reject(error)

File ~/.cache/pypoetry/virtualenvs/scrape2-AgR29CFR-py3.12/lib/python3.12/site-packages/ccxt/async_support/base/ws/aiohttp_client.py:34, in AiohttpClient.handle_message(self, message)
     31 def handle_message(self, message):
     32     # self.log(iso8601(milliseconds()), message)
     33     if message.type == WSMsgType.TEXT:
---> 34         self.handle_text_or_binary_message(message.data)
     35     elif message.type == WSMsgType.BINARY:
     36         data = message.data

File ~/.cache/pypoetry/virtualenvs/scrape2-AgR29CFR-py3.12/lib/python3.12/site-packages/ccxt/async_support/base/ws/aiohttp_client.py:29, in AiohttpClient.handle_text_or_binary_message(self, data)
     27     data = data.decode()
     28 decoded = json.loads(data) if is_json_encoded_object(data) else data
---> 29 self.on_message_callback(self, decoded)

File ~/.cache/pypoetry/virtualenvs/scrape2-AgR29CFR-py3.12/lib/python3.12/site-packages/ccxt/pro/bybit.py:1956, in bybit.handle_message(self, client, message)
   1954 for i in range(0, len(keys)):
   1955     key = keys[i]
-> 1956     if topic.find(keys[i]) >= 0:
   1957         method = methods[key]
   1958         method(client, message)

AttributeError: 'NoneType' object has no attribute 'find'

2024-08-06T15:17:00.507Z sending {'req_id': 3, 'op': 'ping'}
2024-08-06T15:17:00.669Z message {"args":["1722957420585"],"op":"pong"}
2024-08-06T15:17:18.507Z sending {'req_id': 4, 'op': 'ping'}
2024-08-06T15:17:18.671Z message {"args":["1722957438585"],"op":"pong"}`

**Comment by carlosmiei** [comment]
@dudalev That specific error, will be fixed by this PR as well.

**Pull request merged**
