### PR TITLE
added support for `fetchOrder` in bibox

### PR DESCRIPTION
**Pull request by benediamond**
related to #3073

actually @kroitor, you had already done all the hard work, in:
https://github.com/ccxt/ccxt/blob/887b7ee4058a4cb44d8b043b1164002f8cf11b67/js/bibox.js#L424-L466
in any case, this seems to work!

### CODE REVIEW

**Comment by kroitor** [comment]
I'm afraid this is a little more complicated ) 
Have you tested it against both open and closed orders? Because their naming (`privatePostOrderpending`) is very confusing...

**Comment by benediamond** [comment]
Hi @kroitor, I've tested this successfully on both open and closed (i.e., filled and unfilled) orders. It appears to work. What are your concerns? If you're more specific, I can look into them.

**Comment by kroitor** [comment]
> What are your concerns? If you're more specific, I can look into them.

The main concern is that it might not work for orders closed, say, yesterday. If you can test for that – that will also be very helpful of you! I'll merge this PR anyways, shortly.

**Comment by benediamond** [comment]
Ok, I'll attempt to test that as well.

**Pull request merged**
