### PR TITLE
[coinmate] fetchOrders, fetchOpenOrders, fetchMyTrades, error handling

### PR DESCRIPTION
**Pull request by npomfret**
* added fetchOrders and improved fetchMyTrades
* added some error handling
* improved fetchMyTrades
* added fetchOpenOrders

### CODE REVIEW

**Comment by npomfret** [comment]
@kroitor think i'm done with this now

**Comment by npomfret** [comment]
@kroitor I've been trying to add fetchOrder (just pushed it) but the cli is giving me an error that i don't understand:

```
...

 {"error":false,"errorMessage":null,"data":{"id":781246605,"timestamp":1584480015133,"trailingUpdatedTimestamp":null,"type":"SELL","price":0.0345,"remainingAmount":0.01,"originalAmount":0.01,"stopPrice":null,"originalStopPrice":null,"marketPriceAtLastUpdate":null,"marketPriceAtOrderCreation":null,"status":"CANCELLED","orderTradeType":"LIMIT","hidden":false,"avgPrice":null,"trailing":false}} 

[TypeError] Cannot convert undefined or null to object

    at keys                                                                                                            
    at element             examples/js/cli.js:176            let keys = Object.keys (element)                          
    at map                                                                                                             
    at printHumanReadable  examples/js/cli.js:175            log (result.length > 0 ? asTable (result.map (element => {
    at main                examples/js/cli.js:273            printHumanReadable (exchange, result)                     
    at _tickCallback       internal/process/next_tick.js:68                                                            


```

**Comment by kroitor** [comment]
@npomfret are you trying to parseOrder with parseOrders instead of parseOrder ? )

**Comment by npomfret** [comment]
Nope:

```
    async fetchOrder (id, symbol = undefined, params = {}) {
        await this.loadMarkets ();
        const request = {
            'orderId': id,
        };
        const res = await this.privatePostOrderById (this.extend (request, params));
        return this.parseOrder (res['data']);
    }

```

**Comment by kroitor** [comment]
@npomfret actually, the error is coming from cli, not from the coinmate implementation... Are you using --table with the commandline keys with cli?

**Comment by npomfret** [comment]
Yes, that's it.  thanks.

**Comment by kroitor** [comment]
@npomfret ok, i'll add a human-readable error handler to cli for that specific case

**Comment by npomfret** [comment]
@kroitor thanks for your help again

**Pull request merged**
