### PR TITLE
freqtrade fixes

### PR DESCRIPTION
**Pull request by frosty00**
freqtrade is hitting maxCapacity sometimes according to discord, have increased it a bit

### CODE REVIEW

**Comment by kroitor** [comment]
> freqtrade is hitting maxCapacity sometimes according to discord, have increased it a bit

Please, elaborate a bit.

**Comment by frosty00** [comment]
according to discord

**Comment by kroitor** [comment]
@frosty00 i mean, how to reproduce that error reliably?

**Comment by frosty00** [comment]
probably with enough asyncio.gathers

**Pull request merged**
