### PR TITLE
bitlish: fetchTicker: symbol added

### PR DESCRIPTION
**Pull request by mkutny**

### CODE REVIEW

**Comment by kroitor** [comment]
We just came to a conclusion, that we might need to parse bidAmount and askAmount as well... I'll start adding those fields where applicable.

**Comment by mkutny** [comment]
They are quite scarce... and transient.
While a ticker could give a rough idea whether to dip into or not, those top two orders won't give any advise. One would need to fetch orderbook if decided to go deeper.

**Comment by kroitor** [comment]
@mkutny well, those two fields should be trivial to add where available, no worries, I'll do that in the background, and will eventually update them all.

**Comment by mkutny** [comment]
@kroitor what I think would be actually helpful is a midspread. I constantly see it used here and there.

**Comment by kroitor** [comment]
@mkutny agreed!

**Pull request merged**
