### PR TITLE
exchange.currencyStructure -> exchange.safeCurrencyStructure

### PR DESCRIPTION
**Pull request by samgermain**
I think that this should be implemented this way instead actually. 

@ttodua What do you think?

### CODE REVIEW

**Comment by ttodua** [comment]
Initially I was also thinking about this way, it seems a bit more convenient, but maybe we don't need to name it with `safe...`, that is the only thought that comes to my mind, as "safe..." methods are more for parsing the incoming data, not used during definitions (i.e. we dont use `safeMarket` in fetchMarkets, and we also dont use `safeCurrency...` in fetchCurrencies). but idk, maybe it can have that name

**Comment by ttodua** [comment]
@carlosmiei this might look better. the only thing I was inherently dubious is whether we should set any "default precision" in currency objects created from "markets". if we have to add somewhat default precision to currencies (which are not fetched from "currencies" endpoint, or even fetched from that endpoint, but having no precision defined).

so, we should have one approach imo - either not adding any "default precision" to any currency out there, or adding default precision everywhere (even inside `fetchCurrencies` where we set `undefined` to currencies if exchange doesn't provide precision from "fetch-currencies" endpoint )

**Comment by carlosmiei** [comment]
> - either not adding any "default precision" to any currency out there, or adding default precision everywhere

@ttodua  I'm ok with this method. Regarding the currency, I'm not sure how many exchanges out there have it `undefined`?.  How does that impact methods like transfer/withdraw/etc?

**Comment by ttodua** [comment]
@carlosmiei there are many exchanges that does have `undefined`.  it does impact withdraw/transfer methods, without currency's precision it becomes buggy to use withdraw/transfer, because `amount` can not be rounded and if user provides 1.2345678 it might be out of exchange's supported precision for that currency, thus returning the sporadic exceptions to users, and users have to themselves find out the precision for specific currency. 

ccxt assumed that "8" decimals might be somewhat "default" precision, but I doubt that it might not work with most of tokens (i havent done "withdraw/transfer" for 1000s tokens :) 

so, we should re-think if we artificially define precision for all currencies or for none. and if we define, then, I think that precision  `4` is better than `8` because one of the most expensive coin (bitcoin) uses 4 or 5 decimals (depending excahnges) for withdrawal, so other "cheaper" coins would also be more "ok" with 4-5 decimals.

**Comment by carlosmiei** [comment]
> heaper" coins would also be more "ok" with 4-5 decimals.

@ttodua I'm questioning, if we should set the default here, or an exchange per exchange basis

**Comment by ttodua** [comment]
> > heaper" coins would also be more "ok" with 4-5 decimals.
> 
> @ttodua I'm questioning, if we should set the default here, or an exchange per exchange basis

that's I was referring to - I am not sure, because that code has been there for a long time before me and I don't know the full context. But from my view, I think that we should not default there. but it will require quite some modifications across all exchange files and is extra burden at this moment and not critical. so we can leave it as is, and return to it later.
this PR is ok atm.

**Comment by carlosmiei** [comment]
LGTM ✅

**Review by carlosmiei — APPROVED** [review]

**Pull request merged**
