### PR TITLE
New Exchange:  BingX

### PR DESCRIPTION
**Pull request by sc0Vu**
Add new exchange: BingX ccxt/ccxt#13206
API doc: https://bingx-api.github.io/docs/swap/trade-api.html#_1-place-a-new-order

> This branch (PR) is outdated, please take a look at this: https://github.com/ccxt/ccxt/pull/17924

### CODE REVIEW

**Comment by sc0Vu** [comment]
I always got `Please login again` error when call private api, wait for their customer support......

**Comment by nascarjake** [comment]
Hi all - is this still being worked on? Or is there another bingX initiative going on?

**Comment by ttodua** [comment]
@sc0Vu can you please tell two words about the status of BingX ?

**Comment by sc0Vu** [comment]
@ttodua the api key I applied is for perpetual market, but the api documentation was for spot market at that time. Also, I got their reply that they'll release api for perpetual later.

Anyway, I'll check their api documentation again.

**Comment by LeonAlvarez** [comment]
any update?

**Comment by IEthMiner** [comment]
Hi guys, what's the status of this? @sc0Vu thanks!

**Comment by Tomas-MP** [comment]
> Hi guys, what's the status of this? @sc0Vu thanks!

Also curious as I want to add it to my tradingbot.

**Comment by carlosmiei** [comment]
@LeonAlvarez @IEthMiner @Tomas-MP we're currently working on it, and we will do our best to release it in a few weeks (if everything goes well)

**Comment by jayhao2000** [comment]
any updates?

**Comment by samgermain** [comment]
merged in #17924

**Pull request closed without merging**
