### PR TITLE
Add ProBit exchange

### PR DESCRIPTION
**Pull request by probitexchange**

### CODE REVIEW

**Comment by eseiker** [comment]
any update please? it's been over a month XD

**Comment by riswandizone** [comment]
Good project

**Comment by newsum** [comment]
can we merge this one in soon?

**Comment by combicola** [comment]
Please merget probit.com soon

**Comment by 1amth30n3** [comment]
Hi,

How is work going on this one? Any chance soon?

**Comment by kroitor** [comment]
@1amth30n3 , @newsum, @combicola, @vkristjan , @eseiker , @riswandizone the ProBit integration is in the works now, and it will be added within a few days.

**Comment by fl4p** [comment]
The line
```const suspendedReason = this.safeString (currency, 'suspended_reason');```
should fallback to an empty string if the property is null. It currently crashes at ` if (suspendedReason.length > 0) {`

**Comment by kroitor** [comment]
@fl4p 

> The line
> `const suspendedReason = this.safeString (currency, 'suspended_reason');`
> should fallback to an empty string if the property is null. It currently crashes at ` if (suspendedReason.length > 0) {`

You're testing some older version of it, because there is no such line in the current version of this PR.

**Comment by kroitor** [comment]
@fl4p see this commit (added in April) https://github.com/ccxt/ccxt/pull/5608/commits/d31ef5687f70d28fbc07b445806a9db1f21e3761 – that line has been removed two weeks ago.

**Comment by fl4p** [comment]
@kroitor thanks! You're right I was on an old commit.

**Pull request merged**
