### PR TITLE
binance edit handleErrors

### PR DESCRIPTION
**Pull request by frosty00**
Simillar to #2210 for the wapi endpoint.

```
>>> b.wapi_get_withdrawfee()
Request: GET https://api.binance.com/wapi/v3/withdrawFee.html?timestamp=1521562209825&recvWindow=5000&signature=6335
Response: GET https://api.binance.com/wapi/v3/withdrawFee.html?timestamp=1521562209825&recvWindow=5000&signature=6335 200 {'Date': 'Tue, 20 Mar 2018 16:10:10 GMT' {"msg":"The coin does not exist.","success":false}
{'msg': 'The coin does not exist.', 'success': False}
>>> b.wapi_get_withdrawfee({'asset': 'ETH'})
Request: GET https://api.binance.com/wapi/v3/withdrawFee.html?timestamp=1521562309839&recvWindow=5000&asset=ETH&signature=b30927
Response: GET https://api.binance.com/wapi/v3/withdrawFee.html?timestamp=1521562309839&recvWindow=5000&asset=ETH&signature=b30927 200 {'Date': 'Tue, 20 Mar 2018 16:11:50 GMT', {"success":true,"withdrawFee":0.01}
{'success': True, 'withdrawFee': 0.01}
>>> b.public_get_time()
Request: GET https://api.binance.com/api/v1/time {'User-Agent': 'python-requests/2.18.4', 'Accept-Encoding': 'gzip, deflate'} None
Response: GET https://api.binance.com/api/v1/time 200 {'Date': 'Tue, 20 Mar 2018 16:12:36 GMT', 'Content-Type': 'application/json', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Server': 'nginx', 'Vary': 'Accept-Encoding', 'Strict-Transport-Security': 'max-age=31536000; includeSubdomains', 'X-Frame-Options': 'SAMEORIGIN', 'X-Xss-Protection': '1; mode=block', 'X-Content-Type-Options': 'nosniff', 'Content-Security-Policy': "default-src 'self'", 'X-Content-Security-Policy': "default-src 'self'", 'X-WebKit-CSP': "default-src 'self'", 'Cache-Control': 'no-cache, no-store, must-revalidate', 'Pragma': 'no-cache', 'Expires': '0', 'Content-Encoding': 'gzip'} {"serverTime":1521562356006}
{'serverTime': 1521562356006}
```

We always raise errors for http status codes above 400 in the python and javascript base classes regardless.

### CODE REVIEW

**Comment by frosty00** [comment]
Is it safe to assume that the body passed to handleErrors will always be a string a response will be json or None depending on the value of `self.parseJsonResponse`?

**Comment by mkutny** [comment]
I see that you moved `JSON.parse` out of checks. But there is an idea behind:
https://github.com/ccxt/ccxt/blob/9895b95b473a0e7b3e2cea108676f23ddbdfb063/js/binance.js#L859-L862

Usually, we expect exchanges to return json. If what we receive is not json, it's probably a malformed response and we shall throw generic `ExchangeError` when we encounter it.

Still, the most common cause of receiving non-json body is not an exchange internal error but rather ddos protection/captcha html page which is handled by the `defaultErrorHandler`. This method checks for specific clues and if it thinks it's indeed a ddos protection page it throws more specific `DDoSProtection`.

So as of now, the `handleErrors` logic is the following (it will change when we switch to one-time json parse):
- check if body is json
- if not json -> fallback to the `defaultErrorHandler` maybe it's a ddos protection page
- parse json
- check for exchange errors in json and throw if found

With the change you provided ccxt will now throw `ExchangeError` on ddos pages.

**Comment by kroitor** [comment]
> Is it safe to assume that the body passed to handleErrors will always be a string and response will always be json or None depending on the value of this.parseJsonResponse?

@frosty00, @mkutny, what if we say, that we should always send a body into handleErrors, which should be either of:
- `typeof body === 'undefined'` (`None`, `null`)
- `typeof body === 'string'` (non-JSON HTML or plain text)
- `typeof body !== 'undefined' && typeof body !== 'string'` (a JSON-response) ← for this check we might want to add some helper base method like `this.isObject (body)`.

↑ This way we would reduce the arguments count, the body will always be the body, whatever it is. We would remove the `response` then. Let me know what you guys think about it.

**Comment by mkutny** [comment]
> This way we would reduce the arguments count, the body will always be the body, whatever it is. We would remove the response then.

All the `handleError` methods I can think of simply fallback if the body is not json. And in prospective unified flow if the body is not json then `handleErrors` won't be called at all.

In other words, we won't be needing any checks against `body`, `handleErrors` may expect that it will be json only whatever name that argument has. `this.isObject (body)` won't be needed either.

At the same time, I have two side notes:

> This way we would reduce the arguments count

Well, I'm not sure we have such a goal. Do we?

I've seen a case (can't recall it, though) when I would handle error code differently depending on the request. Something like:
```javascript
if (/* handling response of order creation */)
    throw new InsufficientFunds()
if (/* handling response of order cancelation */)
    throw new OrderNotFound()
```

Still, the `request` is not available for `handleErrors`.

So I'd say "we need to be flexible with arbitrary number arguments when we need them" rather than "we need to reduce arguments count".


> the body will always be the body, whatever it is

This way we reduce the possibility of static type checking (I think of typescript, go or whatever future langue we support). Well, we definitely can live without it... still do we really want to do it deliberately?

**Comment by frosty00** [comment]
> This way we would reduce the arguments count, the body will always be the body, whatever it is.

I don't think this is a good idea.

We already are using that the body is a string in the case for binance, and probably others:

>  if (body.indexOf ('LOT_SIZE') >= 0) {

I see, I was trying to parse the JSON before the string checks. Anyway I have reworked the python sync and async `handleErrors/handleRestResponse` to parse JSON (only once) and provide it to handleError, so is it just php that remains?

**Comment by kroitor** [comment]
> All the handleError methods I can think of simply fallback if the body is not json. And in prospective unified flow if the body is not json then handleErrors won't be called at all.

The problem with this approach is that some exchanges do return plain text responses for some calls, like, for example, when fetching a deposit address, they can report just the plain text address. And the body can still contain a plain text error message in case of an error... We can't really skip handleErrors in general case, can we? 

> In other words, we won't be needing any checks against body, handleErrors may expect that it will be json only whatever name that argument has. this.isObject (body) won't be needed either.

We are currently checking if the body is JSON (in most cases). If we are going to move the JSON-parsed body to a separate argument, then in general case we will have to check if the actual response body is coming in the `body` as text or is coming in `response` (as JSON). So, in general, the handleErrors can either accept JSON or text (if not JSON). To me it boils down to checking the incoming type anyway, be it two arguments or just one. Let me know if you think differently.

**Comment by mkutny** [comment]
> And the body can still contain a plain text error message in case of an error... We can't really skip handleErrors in general case, can we?

If error response can be either plaintext or json then not. Do you have any exchange in mind that returns such responses? Will check its `handleErrors`, curious how it's handled.

**Comment by kroitor** [comment]
> If error response can be either plaintext or json then can't. Do you have any exchange in mind that returns such responses?

- Bitmarket can return plain text transaction ids for `withdraw()`.
- SouthXChange `createDepositAddress()` returns plaintext addresses...
- Some of them, like Cryptopia, do return NULL-values as recoverable errors...

If you want, I could probably make a complete list, yet, I'd say, in common case we still need at least one check.

> Will check its handleErrors, curious how it's handled.

I'll tell you right away: 90% probability of a bug there )) To be fixed as soon as I get there

**Comment by mkutny** [comment]
Ok, found a case too:
https://github.com/ccxt/ccxt/blob/9895b95b473a0e7b3e2cea108676f23ddbdfb063/js/qryptos.js#L416-L426

> Bitmarket can return plain text transaction ids for withdraw().

Do you mean that in case of error it will be plaintext as well? Because if it is (and we want to handle it) the whole flow needs to be reconsidered:
```
try {
    this.requireJsonResponse = false
    let response = await this.withdraw()
} catch (e) {
    this.requireJsonResponse = true
    throw e
}
this.requireJsonResponse = true
```

The reason is that `handleErrors` does not get called if we expect json response but it's not. I don't say it's the right thing to do but it works this way at the moment.

**Comment by kroitor** [comment]
> Do you mean that in case of error it will be plaintext as well? 

To be honest, I didn't have a chance to check that particular endpoint extensively, but I'm just deducing, if they reply with a plaintext address, then they can reply with a plaintext error as well, I guess. Will be able to answer exactly when I get to it...

> Because if it is (and we want to handle it) the whole flow needs to be reconsidered:

Yep, we might need to reconsider it again because of the above, and yes, I'm aware that we currently skip it and it's a bug, we've just been fortunate enough, as those plaintext are rare. I'm going to address this after merging new fee loading functionality, probably in a couple of days.

**Comment by frosty00** [comment]
One reason to keep body as a string, for now, is for use in error decriptions. There isn't much point in going through all the effort to parse json once if we are going to have to stringify it again for all errors. Moreover most errors thrown in `handleErrors` do not use `self.raise_error` as I think the php/javascript base class is missing that method. A good example of this is livecoin:

```
                let response = JSON.parse (body);
                if ('errorCode' in response) {
                    let error = response['errorCode'];
                    // todo: rework for error-maps, like in liqui or okcoinusd
                    if (error === 1) {
                        throw new ExchangeError (this.id + ' ' + this.json (response));
                    } else if (error === 2) {
                        if ('errorMessage' in response) {
                            if (response['errorMessage'] === 'User not found')
                                throw new AuthenticationError (this.id + ' ' + response['errorMessage']);
                        } else {
                            throw new ExchangeError (this.id + ' ' + this.json (response));
                        }
```

We are parsing the body string then unparsing it instead of just throwing the body string. I fear these types of problems will happen with one response argument.

**Comment by kroitor** [comment]
> There isn't much point in going through all the effort to parse json once if we are going to have to stringify it again for all errors. 

You're right, not too much point in doing that, that is just for historical reasons (legacy old code which isn't perfect at all). Basically, the reasoning was: not having a comprehensive transpileable Error class we would still want to see the error in its entirety... 

In other words, we wanted to see not just the error string, but the error code and probably some other related info as well, therefore the quick solution was to dump it into a string anyways. That "solution" isn't a good solution anyways, as the user cannot really parse the error string returned from ccxt. 

The proper way of fixing it would be to declare the BaseError class to have the following properties:
- type
- code
- message
- file
- line
- url
- endpoint
- request (headers and body)
- response (headers and body)

Having a generalized base error class with language-agnostic properties would solve the issue, as we don't really need to json-stringify in handleErrors. However, supporting the above structure may be even harder that it is now... But this is something we would need to do anyways.

**Comment by mkutny** [comment]
> To be honest, I didn't have a chance to check that particular endpoint extensively, but I'm just deducing, if they reply with a plaintext address, then they can reply with a plaintext error as well, I guess.

Well, what's seemed strange to me is that if we don't prepend plaintext-responding method with `this.parseJsonResponse = false` then we'll be throwing error.

So I checked out why would it work while it definitely should not have to.

#### southxchange

They definitely return a plaintext... Still, it's a perfectly valid json. We just used to json that represents complex objects, but primitive types (e.g. strings) are valid jsons too:
```
handleRestResponse:
 southxchange POST https://www.southxchange.com/api/generatenewaddress 200 OK 
Response:
 { Date: 'Wed, 21 Mar 2018 10:16:39 GMT',
  ...
  'Content-Encoding': 'gzip' } 
 "3BZk9pcXCfvYWZmJtAAWbhYcsEsGFWBEf2" 

{ currency: "BTC",
   address: "3BZk9pcXCfvYWZmJtAAWbhYcsEsGFWBEf2",
       tag:  undefined,
    status: "ok",
      info: "3BZk9pcXCfvYWZmJtAAWbhYcsEsGFWBEf2"  }
```

#### bitmarket

I don't have funds on bitmarket to check how their plaintext transaction id looks like but they throw json error on `withdraw`:
```
handleRestResponse:
 bitmarket POST https://www.bitmarket.pl/api2/ 200 OK 
Response:
 { Date: 'Wed, 21 Mar 2018 10:09:54 GMT',
   ...
  'Cf-Ray': '3fefa02b0fb6473a-EWR' } 
 {"error":504,"errorMsg":"Insufficient privileges","time":1521626994,"limit":{"used":2,"allowed":100,"expires":1521627000}} 

{ info: {    error:    504,
          errorMsg:   "Insufficient privileges",
              time:    1521626994,
             limit: { used: 2, allowed: 100, expires: 1521627000 } },
    id: {    error:    504,
          errorMsg:   "Insufficient privileges",
              time:    1521626994,
             limit: { used: 2, allowed: 100, expires: 1521627000 } }  }
```

I just suspect their plaintext transaction id is also a valid json.

> Yep, we might need to reconsider it again because of the above, and yes, I'm aware that we currently skip it and it's a bug, we've just been fortunate enough, as those plaintext are rare.

So it's probably/hopefully not a bug...

**Comment by mkutny** [comment]
@frosty00 , did you test these lines?

```
// response in format {'msg': 'The coin does not exist.', 'success': true/false}
let success = this.safeString (response, 'success', 'true');
if (success === 'false') {
    throw new ExchangeError (this.id + ': unknown error code: ' + body);
}
```

I'm asking because I guess it won't work (at least, as expected).

**Comment by frosty00** [comment]
Yeah sorry about that, will do tests whenever modifying handleErrors, think I've learnt my lesson. I forgot that "true" in javascript != "True" in Python.

**Comment by frosty00** [comment]
Also what do you guys think of adding handleError tests? It could be just one or two calls that should raise a particular error.

**Comment by mkutny** [comment]
@frosty00 , still if you extend this test suit with funding methods it would be great!

**Comment by kroitor** [comment]
@frosty00 and alternative approach would be to replicate or, maybe, even transpile the tests to js/py/php... Currently JS is the most tested version, and python/php test are kinda "behind a little", so, if you could help add more testing to the python side – that would be appreciated as well! ) Thx! )

**Comment by frosty00** [comment]
I will when I have more time. However I don’t think it is necessary to replicate all tests in python and php, but just language specific ones - like the base class. 

Moreover, I think instead of having three different language precision testing files we should have one file with the decimal, arguments and result after calling decimalToPrecision and load them into the tests for each language.

**Comment by frosty00** [comment]
Can you merge this? I have been running this branch's commits without any problems.

**Comment by mkutny** [comment]
@frosty00 , I now had a chance to look deeper into it.

When binance returns an error response it fills in both error 'code' and error 'message'.

The proper way to check the response is against codes, of course, still there were legacy checks against messages.

The issue is that they were run before the default `ExchangeError` is thrown. Now they are moved after... and seems they never get called. Asking in case I miss something or there was some purpose or intention behind it.

**Pull request merged**
