### PR TITLE
Added method get_type to exchange

### PR DESCRIPTION
**Pull request by samgermain**
Makes it so that code blocks which look like

```
const defaultType = this.safeString2 (this.options, 'fetchBalance', 'defaultType', 'spot');
const type = this.safeString (params, 'type', defaultType);
params = this.omit (params, 'type');
```

can now be written like

```
const type = this.getType ('fetchBalance', params);
params = this.omit (params, 'type');
```

### CODE REVIEW

**Comment by kroitor** [comment]
I would generalize it further a bit to add the support for an optional market (that will also contain the type). We can also move the omit action inside. Will add that to this PR.

**Comment by samgermain** [comment]
@kroitor I added the omit action

**Comment by kroitor** [comment]
> @kroitor I added the omit action

In PHP the arrays and dicts are always passed by value (with copying), not by reference, unless you add an ampersand `&` before the argument. I was thinking of returning the edited params and the detected type from this method in an array, like we do here, for example:

- https://github.com/ccxt/ccxt/blob/master/js/base/Exchange.js#L2042
- https://github.com/ccxt/ccxt/blob/master/js/binance.js#L3661

**Comment by samgermain** [comment]
> In PHP the arrays and dicts are always passed by value (with copying), not by reference, unless you add an ampersand `&` before the argument. I was thinking of returning the edited params and the detected type from this method in an array, like we do here, for example:
> 
>     * https://github.com/ccxt/ccxt/blob/master/js/base/Exchange.js#L2042
> 
>     * https://github.com/ccxt/ccxt/blob/master/js/binance.js#L3661

sure

**Comment by samgermain** [comment]
@kroitor I changed my mind, the optional market is in there

**Comment by samgermain** [comment]
There's a problem for when params is returned, but it's not needed
```
1629:26  error  'params' is assigned a value but never used  no-unused-vars

✖ 1 problem (1 error, 0 warnings)
```

**Comment by kroitor** [comment]
> There's a problem for when params is returned, but it's not needed
> 
> ```
> 1629:26  error  'params' is assigned a value but never used  no-unused-vars
> 
> ✖ 1 problem (1 error, 0 warnings)
> ```

How do you trigger this error?

The usage for it is:

```JavaScript
async fooBar (..., params  {}) {
    [ type, params ] = this.handleMarketTypeAndParams ('foobar', market, params);
    // or
    [ type, params ] = this.handleMarketTypeAndParams ('foobar', undefined, params);
}
```

**Pull request merged**
