### PR TITLE
unify fetchMarkets (same return type as fetchCurrencies)

### PR DESCRIPTION
**Pull request by frosty00**
used a regex

### CODE REVIEW

**Comment by frosty00** [comment]
> [74%] Testing bitkk OK (testExchange @ run-tests.js:152)

seems to be working on my machine, can you retrigger travis?

**Comment by frosty00** [comment]
I guess we will never know the reply which made travis fail 0;

**Comment by kroitor** [comment]
@frosty00 yeah, it isn't always straightforward to catch all those failures properly... i'll be able to try it on my side a little bit later to see if we can fix it or add better reporting at least...

**Comment by frosty00** [comment]
We could test all the exchanges `fetchMarkets` instead of just the ones you have apikeys for, since it is usually a public request.

**Comment by kroitor** [comment]
> We could test all the exchanges fetchMarkets instead of just the ones you have apikeys for, since it is usually a public request.

We actually do – I mean, we're testing all public APIs (*) and only test private APIs with Travis for exchanges having api keys in keys.json. 

* for all exchanges that aren't "skipped" in keys.json due to their availability issues

**Comment by kroitor** [comment]
Looks like returning markets indexed by symbol as well as currencies indexed by code isn't the best idea, especially if it comes to support futures markets later. Symbols will get duplicated. And if we index by symbol one market will effectively overwrite the other with the same symbol. So, it turns out that we might do better with the opposite if we change the `fetchCurrencies` (to return arrays instead of dicts) to correspond to `fetchMarkets` instead...

**Comment by frosty00** [comment]
> And if we index by symbol one market will effectively overwrite the other with the same symbol

Wouldn't we just merge the data of one market and its corresponding future into the same key in this case?

**Comment by kroitor** [comment]
> But this only delays the issue to loadMarkets which would still return a dict?

Yes, you're right... I'd rather make it not return anything – just populate the state with proper data... Or rethink `loadMarkets` completely.

**Pull request closed without merging**
