### PR TITLE
delist all blinktrade exchanges: vtbc, foxbit, surbitcoin

### PR DESCRIPTION
**Pull request by frosty00**
https://github.com/ccxt/ccxt/pull/9007#issuecomment-831783692

^ No REST API docs and it is impossible to find any volume data

Also no REST API for fetchMarkets

Brazilian reals supported on Binance: https://www.binance.com/en/support/faq/2604a5d35bd947d485dc30d865539e3e

### CODE REVIEW

**Comment by frosty00** [comment]
according to their own API they have no volume:

```
{
  symbol: 'BTC/BRL',
  timestamp: 1620155015972,
  datetime: '2021-05-04T19:03:35.972Z',
  high: 0,
  low: 0,
  bid: 24666.03,
  bidVolume: undefined,
  ask: 25199.99,
  askVolume: undefined,
  vwap: undefined,
  open: undefined,
  close: 0,
  last: 0,
  previousClose: undefined,
  change: undefined,
  percentage: undefined,
  average: undefined,
  baseVolume: 0,
  quoteVolume: 0,
  info: {
    high: 0,
    vol: 0,
    buy: 24666.03,
    last: 0,
    low: 0,
    pair: 'BTCBRL',
    sell: 25199.99,
    vol_brl: 0
  }
}
```

**Comment by frosty00** [comment]
Screenshot 2021-05-04 at 20 14 30

look at the huge spread on the surbitcoin website... it is also dead

**Comment by frosty00** [comment]
vbtc has the most volume in the entire blinktrade network, but still pretty low volume at less than one btc

Screenshot 2021-05-04 at 20 31 25

I don't think their api is good enough / provides enough utility to our users to justify having the blinktrade exchanges listed with ccxd

**Comment by frosty00** [comment]
also VND is now supported with Binance https://www.binance.com/en/support/faq/b3ae940199b740b39fb14ed8201dccef

**Comment by c0dehunter** [comment]
See FoxBit's API docs here: https://github.com/ccxt/ccxt/pull/9007#issuecomment-834300108

**Pull request merged**
