### PR TITLE
Feature: Add wiki and readme-file as PR-exclude file

### PR DESCRIPTION
**Pull request by winkidney**

### CODE REVIEW

**Comment by kroitor** [comment]
Uhm... oops... It's the wrong info in that section now. I mean, those files can be commited, if a commit introduces some significant change to the text, but should not be committed just for URL edits )) So forbidding them entirely isn't what we should really do, otherwise everybody will stop committing to the text of the Manual...

**Comment by winkidney** [comment]
Make sense.

**Comment by kroitor** [comment]
@winkidney sorry for not being clear enough, hope to see more from you anyways )

**Comment by winkidney** [comment]
@kroitor never mind~

**Pull request closed without merging**
