### PR TITLE
CryptoCom: margin error ACCOUNT_NOT_FOUND

### PR DESCRIPTION
**Pull request by phips28**
When a user has not activated the **margin** account, then we receive a 20005 error.
Response: `{"id":"123xxx","method":"private/margin/xxx","code":"20005","message":"ACCOUNT_NOT_FOUND"}`

@kroitor I am not sure what the error should be? your suggestion?

### CODE REVIEW

**Comment by kroitor** [comment]
I'd say it's more like your permission to margin-trade is denied despite that your other trading is ok. Which is why i think PermissionDenied would work better. Otherwise we need a new error class for these situations. What do you think?

**Comment by phips28** [comment]
Basically, there is no margin account available. Because the user needs to create one first. 
We could say its a permission error, but also its not :D I am ok with that.

**Comment by kroitor** [comment]
@phips28 here's our complete error hierarchy: https://github.com/ccxt/ccxt/blob/master/js/base/errorHierarchy.js i think if we add a new error, it should go to the AuthenticationError branch ? What would be a good name for it? AccountNotEnabled ? TradingNotEnabled ? FeatureNotEnabled ? AccountNotFound ? something else?

**Comment by phips28** [comment]
I like `AuthenticationError => AccountNotEnabled` 🙂

**Comment by phips28** [comment]
thx :)

**Pull request merged**
