### PR TITLE
Bitmex: Only set url params when using GET

### PR DESCRIPTION
**Pull request by brandsimon**
This does not fix anything, but I think it is correct to only set the url params when using GET.

### CODE REVIEW

**Comment by kroitor** [comment]
> I think it is correct to only set the url params when using GET.

You're right, all non-GET params are sent as formData (in the body), but there's still one case where BitMEX can accept url-query params in a POST-request:

Screen Shot 2019-05-01 at 13 08 41

**Comment by brandsimon** [comment]
@kroitor 
Great research, thanks, I did not know that!
So in the current version this is broken with the PUT method too.

What is the correct solution?
If the method is not GET, should we inspect the params for `_format` and send only this field?
Should we just sent the parameters with every request?

**Comment by kroitor** [comment]
> If the method is not GET, should we inspect the params for _format and send only this field?

Yes, most likely, however, just to clarify:

> send only this field

... in the URL and send other fields in the body )

> Should we just sent the parameters with every request?

Well, not all of them should be sent in the URL query format ) But yeah, we are going to generalize the way we handle params even further and will add to the base code to distinguish between url and body params in exchange implementations. This implies some changes in the api definition format, so, for now, I'd go with your first suggestion. Thx for your help!

**Comment by brandsimon** [comment]
Okay, I updated it.
There is no delete/del/unset translation, so I did not delete _format, I tested it, bitmex ignores it.

**Comment by brandsimon** [comment]
this.omit, great, thank you, learned something again :)

**Comment by kroitor** [comment]
@brandsimon yep, we have a family of helpers including:

- omit
- groupBy
- indexBy
- filterBy
- extend
- deepExtend
- pluck
- unique
- ...

Most of them will return a new object (won't mutate the original argument).

**Comment by brandsimon** [comment]
@kroitor 
Great! Thank you very much :)

**Pull request merged**
