### PR TITLE
Add fetchAssetValuation for okex

### PR DESCRIPTION
**Pull request by ngugcx**
Add a new function fetchAssetValuation for okex.

### CODE REVIEW

**Comment by ngugcx** [comment]
Hi, @kroitor .
I have one more question which may not be related to this PR.
I tried to install my ccxt fork directly by "python setup.py install", but failed with the following error:
```error: multidict 5.2.0 is installed but multidict<5.0,>=4.5 is required by {'aiohttp'}```

Is there any better way for me to use my ccxt fork before the PR in it is merged and released?

**Comment by kroitor** [comment]
@ngugcx hi! You should be able to build it following a clone from the ccxt master repository. Apparently, you have a pip3 package version conflict with aiohttp/multidict. You can resolve that with `pip3 list`. Also, make sure that your fork is up to date with CCXT master.
I will merge this PR shortly.

**Comment by ngugcx** [comment]
@kroitor , I just found that the parameter ccy cannot be replaced with code, it may be fiat.
```
Asset valuation calculation unit
BTC 、USDT
USD 、CNY 、JPY、KRW、RUB、EUR
VND 、IDR 、INR、PHP、THB、TRY
AUD 、SGD 、ARS、SAR、AED、IQD
The default is the valuation in BTC
```

**Comment by kroitor** [comment]
@ngugcx tbh, i would remove that method, since it's okex-specific, you can still use the implicit API endpoint directly:

```Python
response = exchange.privateGetAssetAssetValuation({'ccy': 'USD'})
```

**Comment by ngugcx** [comment]
Ok, that's fine.

**Pull request merged**
