### PR TITLE
Implement DSX V2 API

### PR DESCRIPTION
**Pull request by ongkhua**
Implemented a few DSX v2 private functions

This is my first attempt at contributing, and I'm new to Github, sorry if I'm making any mistake.

### CODE REVIEW

**Comment by ongkhua** [comment]
just realized the API key in keys.json for DSX is not working, what key should I put ?

**Comment by kroitor** [comment]
> just realized the API key in keys.json for DSX is not working, what key should I put ?

No worries about it, we'll use our private keys for testing anyways. Thank you! Hope to test the pirvate part and merge this asap, in a day or two.

**Comment by ongkhua** [comment]
I have implemented order, orderstatus and cancel.  Tested them working at my side.

**Comment by kroitor** [comment]
Thank you, @ongkhua ! Sorry for a long wait, I will merge this PR as soon as I can, hopefully, sooner.

**Comment by ongkhua** [comment]
Found a problem, there's a function "updateCachedOrders" which after transpiled to PHP, the function declaration is "update_cached_orders" but the function call in "fetch_orders" in dsx class is "updateCachedOrders" (camelcase) instead of underscore notation.  This was correctly using underscore notation in liqui class. How do I fix this ?

**Comment by kroitor** [comment]
@ongkhua sorry, I didn't quite get the question, can you elaborate, plz? If you look into current Liqui implementation, it **currently** has camelcase in JS and underscore in Py/PHP:

- https://github.com/ccxt/ccxt/blob/master/js/liqui.js#L529
- https://github.com/ccxt/ccxt/blob/master/js/liqui.js#L587

↑ this gets transpiled into this in PHP ↓

- https://github.com/ccxt/ccxt/blob/master/php/liqui.php#L534
- https://github.com/ccxt/ccxt/blob/master/php/liqui.php#L592

... and into this in Python ↓

- https://github.com/ccxt/ccxt/blob/master/python/ccxt//liqui.py#L495
- https://github.com/ccxt/ccxt/blob/master/python/ccxt//liqui.py#L545

Let me know if that does not answer the question..

**Comment by ongkhua** [comment]
` public function fetch_orders ($symbol = null, $since = null, $limit = null, $params = array ()) {
        if (is_array ($this->options) && array_key_exists ('fetchOrdersRequiresSymbol', $this->options))
            if ($this->options['fetchOrdersRequiresSymbol'])
                if ($symbol === null)
                    throw new ExchangeError ($this->id . ' fetchOrders requires a $symbol argument');
        $this->load_markets();
        $request = array ();
        $market = null;
        if ($symbol !== null) {
            $market = $this->market ($symbol);
            $request['pair'] = $market['id'];
        }
        $response = $this->privatePostOrders (array_merge ($request, $params));
        // liqui etc can only return 'open' orders (i.e. no way to fetch 'closed' orders)
        $openOrders = array ();
        if (is_array ($response) && array_key_exists ('return', $response))
            $openOrders = $this->parse_orders($response['return'], $market);
        $allOrders = $this->updateCachedOrders ($openOrders, $symbol);
        $result = $this->filter_by_symbol($allOrders, $symbol);
        return $this->filter_by_since_limit($result, $since, $limit);
    }`

See the call to "$this->updateCachedOrders" ??  It's supposed to be "$this->update_cached_orders"

**Comment by ongkhua** [comment]
I modified the base class "exchange.php" function __call to look for underscore notation function name
This work-around solves temporary solves the problem earlier. Should I commit this exchange.php base class? 

`
public function __call ($function, $params) {
        if (array_key_exists ($function, $this)) {
            return call_user_func_array ($this->$function, $params);
        } else {
            /* check underscore notation */
            $underscore_function = strtolower(preg_replace('/(?<=\\w)(?=[A-Z])/',"_$1", $function));
            if (method_exists ($this, $underscore_function)) {
                return call_user_func_array (array($this,$underscore_function), $params);
            }
            else {
                /* handle errors */
                throw new ExchangeError ($function . ' and '.$underscore_function.' method not found');
            }
        }
    }
`

**Comment by kroitor** [comment]
@ongkhua 

> See the call to "$this->updateCachedOrders" ?? It's supposed to be "$this->update_cached_orders"

yep, I see it, but can you show how the body of `updateCachedOrders` method is declared in the js file you're editing?

**Comment by kroitor** [comment]
@ongkhua I don't think we really need to cache them in DSX as they seem to have a complete set of endpoints now:
 
screen shot 2018-09-19 at 12 39 40

But anyways, no worries about the updateCachedOrders, I'll resolve this where necessary. Thank you once again for the effort, really appreciate it!

**Comment by ongkhua** [comment]
It's declared in Liqui class, not DSX.   I copied the fetch_orders from liqui and made changes, but I retained the caching part, because I'm not sure whether they are needed elsewhere

**Pull request merged**
