### PR TITLE
Add a new exchange trading api: Hotbit

### PR DESCRIPTION
**Pull request by leodai2**
Hotbit is a growing digital currency exchange. Hope you can accept.

### CODE REVIEW

**Comment by Matoran** [comment]
Hello leodai2, you should read this: https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

Python code (PHP too) is generated from javascript version. Could you submit the javascript version ?

**Comment by jaro2k** [comment]
was there any progress since Nov 2018? I believe Hotbit support is still pending for implementation or am I missing something? tks.

**Comment by madnai** [comment]
any news?

**Comment by kroitor** [comment]
@madnai we can't merge it as long as it fails the public tests (Travis CI) and the private tests as well.

**Comment by p-i-** [comment]
Bump!
Seems a pity to lose this work!
It would be great to add HotBit support to ccxt.

**Comment by Matoran** [comment]
> Bump!
> Seems a pity to lose this work!
> It would be great to add HotBit support to ccxt.

translate code to javascript and it will be accepted, it's an open-source project for this kind of things :).

**Comment by Matoran** [comment]
@kroitor this pull request can be closed, https://www.hotbit.io/support?page=api `Hotbit API will be opened soon, please stay with us for further information.`

They do not provide an API anymore (and it will probably not be the same API). Anyway this pull request is inactive for a long time.

**Comment by samgermain** [comment]
The website doesn't link to the api docs, but it looks like their [api docs are on github](https://github.com/hotbitex/hotbit.io-api-docs/blob/master/rest_api_en.md)

**Comment by Matoran** [comment]
Yes but you can’t have API keys to use it.

**Pull request closed without merging**
