### PR TITLE
bleutrade parseOrder fix

### PR DESCRIPTION
**Pull request by ndubel**
some difference from bittrex in parseOrder

### CODE REVIEW

**Comment by kroitor** [comment]
> some difference from bittrex in parseOrder

Could you please elaborate on which particular differences?

**Comment by ndubel** [comment]
Bittrex put price in "Limit" (but also has "Price")
image

Bleutrade put price in "Price"
image

**Comment by kroitor** [comment]
@ndubel alright, thx for the clarification!

P.S. your editor rewrites spaces to tabs for some reason, btw ;)

**Comment by ndubel** [comment]
> P.S. your editor rewrites spaces to tabs for some reason, btw ;)

sorry, I'll try to be more attentive :)

**Pull request merged**
