### PR TITLE
Fix for the PSR-4 error report

### PR DESCRIPTION
**Pull request by deakzsolt**
@kroitor please check is this what you meant?
This is a supposed fix for the issue #6777

### CODE REVIEW

**Comment by deakzsolt** [comment]
There are now errors for the const, will need to find a better solution for that. Leave open this pr or if someone can fix this faster then please do.

**Comment by kroitor** [comment]
@deakzsolt sure! A quick question: can you plz remove the generated files (all php files) from this PR? Since it will be regenerated on Travis CI, therefore we need just the JS in this case.

**Comment by deakzsolt** [comment]
@kroitor sure thing with the next update will remove the files

**Comment by deakzsolt** [comment]
@kroitor this should be a workaround for the const not showing up in the siblings class from Exchange. Not the best solution as all the const files should be Exchange::CONST_NAME. Not sure where can I change that in the builder, but for now this should resolve all the issues. If you tell me how can I change in the builder and not break the other scripts then I can implement it as mentioned above. Also can you check what is the conflict and is there anything else I should change?

**Comment by kroitor** [comment]
@deakzsolt if you could remove the generated php files, it would help speed up the merge. Thx!

**Comment by deakzsolt** [comment]
@kroitor I think in the last merge they are deleted but I got this conflict and can't see what is the issue. Can you tell me what files should I delete?

**Comment by kroitor** [comment]
@deakzsolt it will probably be easier to resubmit just the edits in the .js and Exchange.php, since restoring other files will be tedious, so, if you can, please reopen a new one with just those needed files, I will carry on from there. Thx again, appreciate your help!

**Comment by deakzsolt** [comment]
@kroitor ok wil do that

**Comment by kroitor** [comment]
@deakzsolt awesome, thank you!

**Pull request closed without merging**
