### PR TITLE
New exchange bitbns

### PR DESCRIPTION
**Pull request by abhishekr700**
Build: Passed
Checks: Passed

### CODE REVIEW

**Comment by kroitor** [comment]
Thx for the contribution! )

We will need to rework it somewhat, because it currently breaks the unification guidelines:

- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#sending-market-ids
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#parsing-symbols
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#new-exchange-integrations

**Comment by abhishekr700** [comment]
@kroitor I believe you're talking about places I've parsed the ccxt symbols. 
But if I parse exchange symbols, would that be okay ? The exchange needs slightly different strings to be passed for USDT & Non-USDT Markets.

**Comment by gthedifferentone** [comment]
@kroitor looking forward to using this library for bitbns as I trade India crypto markets. 
By when can we expect this to be ready for public use ?

**Comment by kroitor** [comment]
@abhishekr700 

> I believe you're talking about places I've parsed the ccxt symbols.

Yes, but this is a bit more complicated. We don't want to do repetitive string operations on symbols upon every call to every method at all. We want to do that just once (there's no point in doing so many times) and export the proper list of markets from `fetchMarkets()` (see how it is implemented in all other exchanges). 

The list of markets contains unified structures of a certain type, as described here:

- https://github.com/ccxt/ccxt/wiki/Requirements

Apart from other fields, each market has an `id` and a `symbol`, as explained here:

- https://github.com/ccxt/ccxt/wiki/Manual#symbols-and-market-ids

The `id` is used for passing to the exchange, the `symbol` is used for passing to the user. So, `fetchMarkets()` has to fill a proper exchange-specific `id` for each market. That `id` can have the same format for most of the symbols and have a different format for the USDT markets (the parsing for those should be done if `fetchMarkets` just once). The `symbol` is what you return to the user from your `parseOrder` (which is not implemented in this PR yet), `parseOrders`, `parseTrade`, and other parsing methods. See how parse-methods work in all other exchanges. Let me know if that does not help.

**Comment by abhishekr700** [comment]
@kroitor I read through it. I would like a little something to your attention here.
The parsing is needed at certain positions, only `id` is going insufficient for me unless I add those fields to the market structure returned from fetchMarkets.

Example: 
For fetchOrderbook/fetchTrades the symbol like `BTCUSDT` is used, but for createOrder the exchange api requires sending symbol as `BTC_USDT`.
Therefore,`id` is being used as it is for the public routes, but for private ones, such cases arise.
What should be done in such a case ?

**Comment by kroitor** [comment]
@abhishekr700 

> What should be done in such a case ?

```JavaScript
// pseudocode
const market = this.market (symbol);
request: {
    'symbol': (market['quote'] === 'USDT') ? market['id'] : market['base'], // covers all cases
};
```

**Comment by kroitor** [comment]
@abhishekr700 or, alternatively, we can add a non-standard field to the market structure for the second type of id that would store BTC_USDT where necessary.

**Comment by abhishekr700** [comment]
@kroitor Wouldn't adding a non standard field break tests in terms of expected fields ?
I'll try to change the code as much as I can using the `base` property and will let you know later.

**Comment by kroitor** [comment]
> Wouldn't adding a non standard field break tests in terms of expected fields ?

For markets – it would not, because we have a few of those non-standard fields around, can't completely avoid them, but anyways, it will still work faster and will use less resources if we don't do operations on the same strings every time. Apart from that, we would reduce code duplication in the js file that way.

**Comment by abhishekr700** [comment]
@kroitor Okay, will add a field to store the underscored market names.
Also, here's a snippet I'm concerned about
```js
if (market['base'] === 'USDT') {
            request['side'] = 'usdtcancelOrder';
} else {
            request['side'] = 'cancelOrder';
 }
```
I think this is okay ? It is not a heavy string operation

**Comment by kroitor** [comment]
@abhishekr700 

> I think this is okay ? It is not a heavy string operation

Yep, it's ok, since it does not do any concatenations or splits, just a basic assignment to a string literal. However, I would rewrite it for a bit more compact syntax:

```JavaScript
const request = {
    // ...
    'side': (market['quote'] === 'USDT') ? 'usdtcancelOrder' : 'cancelOrder',
    // ...
};
```

Let me know if anything. Thx!

**Comment by abhishekr700** [comment]
@kroitor I've made the string related changes.

**Comment by abhishekr700** [comment]
@kroitor  Can you merge this now ?

**Comment by kroitor** [comment]
Hi, @abhishekr700 ! Can you plz explain this URL a bit: https://github.com/ccxt/ccxt/pull/6077/files#diff-db4e0da094a2fb4ae044f5e19f1bccd6R45 ? It's not common to have direct links to AWS instances for the API backend. Is it possible for bitbns to add the docs for both the public API and the private API to the website?

**Comment by abhishekr700** [comment]
@kroitor  We will get the docs added to the api as soon as possible. The AWS link we can modify & route via bitbns if needed.

**Comment by kroitor** [comment]
@abhishekr700 that would be fantastic!

**Comment by abhishekr700** [comment]
@kroitor  Would it be okay if we route the public endpoint via `http://ccxt.bitbns.com/` ?

**Comment by kroitor** [comment]
@abhishekr700 sure! Thanks again!

**Comment by abhishekr700** [comment]
@kroitor I've made the public endpoints go through bitbns.com. Hope we can merge this asap.

**Comment by abhishekr700** [comment]
@kroitor  Any updates on this ?

**Comment by gthedifferentone** [comment]
Eagerly awaiting to see this live @kroitor

**Comment by shreyanshjain212** [comment]
Any updates here?

**Comment by kroitor** [comment]
@abhishekr700 @gthedifferentone @shreyanshjain212 

> Any updates here?

Hi! I will get to it as soon as I get through this: #6332. Hopefully, should not be too long from here.

**Comment by abhishekr700** [comment]
@kroitor Since #6332 is over now, I hope you can review this !

**Comment by kroitor** [comment]
@abhishekr700 yes, i'll do my best to get it resolved soon, thank so much for your involvement!

**Comment by capedcrusader23** [comment]
Any updates on this to go live @kroitor

**Comment by aastha980** [comment]
Hoping to see this live soon!

**Comment by apoorvasingh17** [comment]
When will this be merged? The PR looks in good shape.

**Comment by ishween** [comment]
Hoping to get merged soon!

**Comment by sanket-k** [comment]
Hi, I am building a bot for arbitrage and Indian exchanges have good arbitrage opportunities. Only bitbns seems to have ccxt integration done right now. If this PR is merged that would be helpful. 
eagerly waiting for the PR to happen, any timeline @kroitor ?

**Comment by tanmesh** [comment]
Have a college project I am doing for which I need to collate data for Indian exchanges. Bitbns right now seem to have good volume. I would want to take data from it. When we might expect this to be merged?

**Comment by kroitor** [comment]
@capedcrusader23 , @apoorvasingh17 @sanket-k @tanmesh asking the "when" question does not really help merge it faster:

- https://github.com/ccxt/ccxt/wiki/FAQ#can-you-implement-feature-foo-in-exchange-bar
- https://github.com/ccxt/ccxt/wiki/FAQ#whats-your-progress-on-adding-the-feature-foo-that-was-requested-earlier-how-do-you-do-implementing-exchange-bar
- https://github.com/ccxt/ccxt/wiki/FAQ#what-is-the-status-of-this-pr-any-update

The implementation in this PR currently has a lot of errors. We have to clean them up before being able to merge. 

@capedcrusader23 , @apoorvasingh17 @sanket-k @tanmesh your help with fixing and testing it would speed up the merge.

The code in this implementation violates the [CONTRIBUTING guidelines](https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#derived-exchange-classes) and it fails if you try running private tests in JS/Py/PHP. Therefore we can't merge it yet, because it breaks. I hope to get to fixing it as soon as I can. Your help with testing it, pointing out the errors and fixing those would be really appreciated. Asking the "when" question is a waste of time, because the answer will always be "as soon as it is cleaned up and ready to merge".

**Comment by sanket-k** [comment]
@kroitor thanks for the update, will go through the testing part and try to help to fix this as soon as possible.

**Comment by abhishekr700** [comment]
@kroitor I've tested this on my end with private tests, please test it out on your end for the tests it was failing before.

**Comment by kroitor** [comment]
@abhishekr700 thx for the updates and for the fixes! Appreciate your help!

We still need to fix a few places:

- https://github.com/ccxt/ccxt/pull/6077/files#diff-db4e0da094a2fb4ae044f5e19f1bccd6R430
  Need to make sure that we use quotes keys, because in Python and PHP a trade dictionary doesn't have a `date` property, but has a `date` key. It violates this rule: https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#accessing-dictionary-keys (need to make that we use quotes assoc keys everywhere throughout the file).

- https://github.com/ccxt/ccxt/pull/6077/files#diff-db4e0da094a2fb4ae044f5e19f1bccd6R380
  We don't want to set the values that are undefined – to zero. The summing operation below is also not necessary, it currently violates this rule: https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#adding-numbers-and-concatenating-strings. I would remove the sum-line entirely.

- need to clean up commented-out console.log statements

- instead of two lines like `const order = await foobar(); return order;` we can simply do `return await foobar()` everywhere throughout the file.

- https://github.com/ccxt/ccxt/pull/6077/files#diff-db4e0da094a2fb4ae044f5e19f1bccd6R175
  Need to make sure that we propagate user overrides from params to the endpoint calls everywhere throughout the file with `this.extend(request, params)`: https://github.com/ccxt/ccxt/wiki/Manual#overriding-unified-api-params (see how this is done in all other exchanges).

**Comment by abhishekr700** [comment]
@kroitor I'll start cleaning this up over the following days. I'll let you know when I believe things are done on my end.

**Comment by abhishekr700** [comment]
@kroitor You mentioned that in fetchBalance, I should report the truth i.e. undefined instead of making it 0. But if I do so, the base method parseBalance will fail. Is this expected ?

**Comment by kroitor** [comment]
@abhishekr700 `parseBalance()` should not fail on empty/missing values – can you plz post the details about the failure?

**Comment by abhishekr700** [comment]
@kroitor if the free,used values for a currency is undefined, python tests for fetchBalance fails with a `KeyError 'total'`. Please let me know if you need any more information.

**Comment by kroitor** [comment]
> if the free,used values for a currency is undefined, python tests for fetchBalance fails with a KeyError 'total'.

If neither `free`, `used` nor `total` is specified for a currency in the exchange response – we should not set that currency code in `balances`. We should only set a currency in `balances` before passing balances to `parseBalance` if at least one of the three values is defined for that currency in the exchange response. In other words – if the exchange response does not have that currency then we should indicate the truth to the user – there should be no such currency code in the balance response.

**Comment by kroitor** [comment]
@abhishekr700 to clarify, we should change this:

```JavaScript
        for (let i = 0; i < symbols.length; i++) {
            const symbol = symbols[i];
            const availableOrderString = 'availableorder' + symbol;
            const free = this.safeFloat (currencybalances, availableOrderString);
            const inorderString = 'inorder' + symbol;
            const used = this.safeFloat (currencybalances, inorderString);
            balances[symbol] = {
                'free': free,
                'used': used,
            };
        }
```

to this:

```JavaScript
        for (let i = 0; i < codes.length; i++) {
            const code = codes[i];
            const currency = this.currency (code);
            const currencyId = currency['id'];
            const availableOrderString = 'availableorder' + currencyId;
            const inorderString = 'inorder' + currencyId;
            const free = this.safeFloat (currencybalances, availableOrderString);
            const used = this.safeFloat (currencybalances, inorderString);
            if ((free !== undefined) || (used !== undefined)) {
                balances[code] = {
                    'free': free,
                    'used': used,
                };
            }
        }
```

**Comment by kroitor** [comment]
@abhishekr700 one of the aspects in the above snippet is to distinguish unified currency codes from exchange-specific ids and avoid mixing them.

**Comment by abhishekr700** [comment]
@kroitor  Thank you for the deep explanation ! I'll add the undefined checks & also make sure I use exchange specific ids !

**Comment by abhishekr700** [comment]
@kroitor I've cleaned up some things on my end, can you please review it and suggest changes,if any

**Comment by abhishekr700** [comment]
@kroitor I'm getting this new error which I was not getting before on running tests 
```python3
<class 'TypeError'> 'coroutine' object is not subscriptable
File "python/test/test_async.py", line 446, in <module>
	    asyncio.get_event_loop().run_until_complete(main())

	  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
	    return future.result()

	  File "python/test/test_async.py", line 433, in main
	    await try_all_proxies(exchange, proxies)

	  File "python/test/test_async.py", line 372, in try_all_proxies
	    await test_exchange(exchange)

	  File "python/test/test_async.py", line 311, in test_exchange
	    await test_symbol(exchange, symbol)

	  File "python/test/test_async.py", line 270, in test_symbol
	    await test_order_book(exchange, symbol)

	  File "python/test/test_async.py", line 127, in test_order_book
	    orderbook['datetime'], (explain @ run-tests.js:191)
```.

**Comment by kroitor** [comment]
@abhishekr700 that error means that we're missing an `await` keyword here: https://github.com/ccxt/ccxt/pull/6077/files#diff-db4e0da094a2fb4ae044f5e19f1bccd6R186 – Python requires it in async mode.

**Comment by abhishekr700** [comment]
@kroitor Thank you, that fixed things. Are there any more changes needed on my end ?

**Comment by kroitor** [comment]
@abhishekr700 thanks to you! I'll do my best to review it again shortly and will let you know if anything. I think, we should be pretty close to merging.

**Comment by abhishekr700** [comment]
Hi @kroitor !
Were you able to review this ?

**Comment by abhishekr700** [comment]
@kroitor I hope we can get this merged now ?

**Comment by sanket-k** [comment]
hi, @kroitor is there anything else missing for the merge ??

**Pull request closed without merging**
