### PR TITLE
New Exchange: Eterbase

### PR DESCRIPTION
**Pull request by prgmtx**
Adding support for [Eterbase Exchange](https://www.eterbase.com) including functions for RFC 2616 date formatting as discussed in https://github.com/ccxt/ccxt/issues/5894

### CODE REVIEW

**Comment by prgmtx** [comment]
Hi @kroitor. Any idea when you can review my PR?

**Comment by galvanizze** [comment]
Hi @kroitor, is there any problem with this merge request? Thanks

**Comment by kroitor** [comment]
@galvanizze I need to resolve the conflicts and test the private API as described here: 

- https://github.com/ccxt/ccxt/pull/6122#issuecomment-555298544

Your help with testing it is welcome, I'll do my best to get to it [ASAP]( https://github.com/ccxt/ccxt/issues/6332)

**Comment by kroitor** [comment]
Hi @prgmtx! A quick question, can you please update your fork to the current master (to make it up to date)? If you can, I will upload the edits to it, and we will get to merging it. If not, I will have to create a new fork for it. Let me know if you can do that, your response will be very much appreciated!

**Comment by prgmtx** [comment]
Hi @kroitor. I have merged the fork with upstream master. 

node run-tests eterbase --js is OK
node run-tests eterbase --php is OK
node run-tests eterbase --python gives some errors which I didn't understood

**Comment by kroitor** [comment]
@prgmtx fantastic! Thank you so much!

**Pull request merged**
