### PR TITLE
binance support internal transfers

### PR DESCRIPTION
**Pull request by frosty00**

### CODE REVIEW

**Comment by frosty00** [comment]
```
output of fetchTransfers

[
  {
    info: {
      timestamp: 1616173880000,
      asset: 'USDT',
      amount: '1',
      type: 'MAIN_MARGIN',
      status: 'CONFIRMED',
      tranId: 45600961449
    },
    timestamp: 1616173880000,
    datetime: '2021-03-19T17:11:20.000Z',
    id: '45600961449',
    status: 'confirmed',
    amount: 1,
    currency: 'USDT',
    from: 'spot',
    to: 'margin'
  },
  {
    info: {
      timestamp: 1616173741000,
      asset: 'USDT',
      amount: '1',
      type: 'MAIN_MARGIN',
      status: 'CONFIRMED',
      tranId: 45600641863
    },
    timestamp: 1616173741000,
    datetime: '2021-03-19T17:09:01.000Z',
    id: '45600641863',
    status: 'confirmed',
    amount: 1,
    currency: 'USDT',
    from: 'spot',
    to: 'margin'
  },
  ```

**Comment by frosty00** [comment]
https://binance-docs.github.io/apidocs/spot/en/#user-universal-transfer

**Comment by kroitor** [comment]
@frosty00 I think okex requires transferring to specific positions per derivative/symbol. Which is why we might have to add a `symbol` alongside `currency` in fetchTransfers, though i'm not sure yet.

**Comment by frosty00** [comment]
I think the okex transfer is compatible with the current signature

**Pull request merged**
