### PR TITLE
add keepalive js

### PR DESCRIPTION
**Pull request by frosty00**
i found kraken to be a particular good exchange to test this on because they have pretty lax ratelimits

```
// node fetch profiling

let ccxt = require ('./ccxt')

;(async () => {
    const start = process.hrtime ()
    const kraken = new ccxt.kraken ()
    for (let i = 0; i < 20; i++) {
        await kraken.fetchTicker ('ETH/BTC')
    }
    const end = process.hrtime (start)
    console.log (end[0] + end[1] / 1000000000)
}) ()
```

### CODE REVIEW

**Comment by kroitor** [comment]
@frosty00 it breaks the browser version, unfortunately

**Comment by frosty00** [comment]
it's working for me...

**Comment by kroitor** [comment]
@frosty00 that's weird, let me check on my side again...

on another issue – removing the .agent breaks the old proxying code, since we have told everyone to use the .agent property and this has been in our docs for the entire time here: https://github.com/ccxt/ccxt/wiki/Install#javascript-proxies

**Comment by frosty00** [comment]
i'm using `new window.ccxt.kraken ({'proxy': 'https://cors-anywhere.herokuapp.com/'})` and it works in browser with the new agent

**Comment by kroitor** [comment]
@frosty00 no, i mean the SOCKS/https proxies, not the CORS...
'proxy' is just for the CORS... for the https proxies, however, the JS users have to override the .agent

**Comment by kroitor** [comment]
@frosty00 yep, on a second attempt, it does work in the browser ) https://github.com/browserify/browserify#compatibility

we need to decide on the `.agent` property...

**Comment by frosty00** [comment]
supported

**Pull request merged**
