### PR TITLE
Bibox: initial impl

### PR DESCRIPTION
**Pull request by kornrunner**
https://www.bibox.com/

They're currently under maintenance so I couldn't test it all, but most of it is tested.
Transpiling passes in current state.
I don't know how you're handling logos, so didn't do that.

I'd appreciate your comments. Thank you!

### CODE REVIEW

**Comment by kroitor** [comment]
You did a fantastic job, I must say! Thanks a lot! Really mean it! I'll put down my comments in the diff and will merge it then )

**Comment by kornrunner** [comment]
Actually, I've just remembered that they're returning both asks and bids in a single array - that needs to be remmaped before passing to `parseOrders`

**Comment by kroitor** [comment]
In fact, I don't have any significant comments on the code itself. I haven't tested it yet (will do that upon merging), but looks very clean. There are a few things I would change, but I would not focus your attention and would not want you to waste time on those, like double quotes → single quotes, and other minor formatting things. This is not difficult to merge at all (will do that shortly). Travis complained because of the image URL but it's ok, I'll add it, no worries.

**Comment by kroitor** [comment]
Unfortunately, they just went down for a system upgrade %) Will wait for them to get back online ) However, only they know if they will change anything in their API or not %)

**Comment by kornrunner** [comment]
Another fix for OHLCV, and they're back online...

**Pull request merged**
