### PR TITLE
Register ccxt with composers PSR4 autoloader.

### PR DESCRIPTION
**Pull request by ShaunR**
composer has the ability to autoload classes rather than having to require/include every single class you want to use. Before when using composer you would still need to do the following to use a class

```
require __DIR__ . '/vendor/autoload.php';
require __DIR__ . '/vendor/ccxt/ccxt/ccxt.php';
$gdax = new ccxt\gdax();
```

Now you will be able to do
```
require __DIR__ . '/vendor/autoload.php';
$gdax = new ccxt\gdax();
```

### CODE REVIEW

**Comment by ShaunR** [comment]
We can take this one step further and I'll look into it if your interested... ccxt is registering it's own autoloader and requiring files it needs. We should be able to remove this autoloader and those requires in place of composer's autoloader.  Let me know your thoughts.

**Comment by kroitor** [comment]
Hi! Thank you for the contribution! Sorry for a long wait... I'm not very familiar with Composer in particular, therefore I'm not sure if this indeed fixes the problem and does not mask it instead. Did you test it? Sorry, if the question is silly. I tried running it with my setup and it still cannot find the class (same as in [your issue](https://github.com/ccxt/ccxt/issues/862)).

**Comment by darthf1** [comment]
Would be great to have a better PSR-4 implementation so we can use the USE statement instead of the REQUIRE file.

**Comment by kroitor** [comment]
@darthf1 excellent proposal, thank you! That would be awesome! I'm not very familiar with Composer, so I'm not sure on the correct way to autoload it, your guidance will be appreciated!

**Comment by kroitor** [comment]
Just a related reference: https://github.com/ccxt/ccxt/issues/633

**Comment by darthf1** [comment]
I think the change proposed by @ShaunR  is all you need in composer, and then you can remove all the `include_once` from the PHP files if you keep the current namespaces.

**Comment by kroitor** [comment]
@darthf1 have you tried it? It says "class not found" on my side...

**Comment by darthf1** [comment]
Yeah i got `PHP Fatal error:  Class 'ccxt\Exchange' not found in ....\vendor\ccxt\ccxt\php\bitstamp.php on line 5`. Will check for a fix.

**Comment by kroitor** [comment]
@darthf1 the line 5 in bitstamp.php (as in any other derived exchange file) is generated, we can change it or remove it if it is not necessary... More on our build process here: https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md

**Comment by darthf1** [comment]
New pull request #873

**Pull request closed without merging**
