### PR TITLE
added algo orders for okex futures

### PR DESCRIPTION
**Pull request by omarayad1**
## added new algo orders for okex futures:

- Place algo order: https://www.okex.com/docs/en/#futures-algo_order
- Cancel algo order: https://www.okex.com/docs/en/#futures-algo_cancel_order
- Get algo orders: https://www.okex.com/docs/en/#futures-algo_list

### CODE REVIEW

**Comment by tudorelu** [comment]
Could we please have an example of how to place & cancel algo orders?

**Comment by kroitor** [comment]
@tudorelu will post here shortly.

**Comment by tudorelu** [comment]
Hei @kroitor,

After finding the [Implicit API Methods](https://github.com/ccxt/ccxt/wiki/Manual#implicit-api-methods) section in the manual I figured it out!

The following worked for me for placing a trigger spot market order, that works like a stop-loss: when the market price of 'ETH-BTC' hits the trigger_price, 0.09 ETH is sold for BTC at market price. 

```py
exchange = ccxt.okex({
    'apiKey':'...',
    'secret':'....',
    'password':'...',
})

args = {
    'instrument_id' : 'ETH-BTC', 
    'order_type':'1',      # trigger
    'mode':'1',            # spot, 2 is margin
    'side': 'sell', 
    'size': 0.09, 
    'trigger_price': 0.04, 
    'algo_type':'2'        # market
    }

response = exchange.spotPostOrderAlgo(args)
```

I can make a pull request and attach it as an example.

**Comment by kroitor** [comment]
@tudorelu i'd recommend to also enable the rate-limiter: https://github.com/ccxt/ccxt/wiki/Manual#rate-limit

**Pull request merged**
