### PR TITLE
Kucion fetchOpenOrders without a symbol

### PR DESCRIPTION
**Pull request by Umbralith**
Created fetchAllOpenOrders function for Kucoin to get all open orders rather than just open orders by symbol

### CODE REVIEW

**Comment by kroitor** [comment]
Unfortunately, this is not a correct way of doing this according to CCXT semantics. Instead, we usually just make the `symbol` argument for `fetchOpenOrders` optional so that it will return all orders without a symbol...

**Comment by kroitor** [comment]
Can you unify your implementation with https://github.com/ccxt/ccxt/pull/3188/files#diff-03145d38fecb5a74e76f74154826789dR689 ? I mean, can you make the `symbol` there optional?

**Comment by kroitor** [comment]
Nevermind, edited it. Thx for your involvement anyways! Appreciate it!

**Comment by Umbralith** [comment]
Thank you so much. This is the first time I've ever contributed to an open-source repo. Sorry about not making it unified

**Comment by kroitor** [comment]
@Umbralith no worries, and thank you for participation! )

**Pull request merged**
