### PR TITLE
Update bittrex.py

### PR DESCRIPTION
**Pull request by serebryakov-av**
Bittrex started returning None for some currencies.

### CODE REVIEW

**Comment by kroitor** [comment]
Ouch: 

- https://github.com/ccxt/ccxt/pull/4760/commits/cd7e9e0bccfd4fd14ec02914cedda33d46d8966d#diff-f51fffffc44315dd1b59540264aa1f44R3
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#multilanguage-support
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#derived-exchange-classes

**Comment by kroitor** [comment]
> Bittrex started returning None for some currencies.

Would be great if you can specify which particular currencies ) Thx! )

**Comment by serebryakov-av** [comment]
I think that it is not depends on particular currencies.
I am getting None for ETH, NEO, PART.

**Comment by kroitor** [comment]
@serebryakov-av alright, i've added safe-wrappers to workaround the issue in python and merged it. Should be ok as of 1.18.304. Thx!

**Pull request merged**
