### PR TITLE
[binance] Fix RSA key signatures

### PR DESCRIPTION
**Pull request by pietrodn**
When authenticating to a Binance subaccount with a RSA key, CCXT fails in Python.

Here's the script to reproduce the issue:

```python
import asyncio
from pathlib import Path

from ccxt.pro import binance

SECRET_KEY = (Path.home() / "Downloads" / "binance.pem").read_text()


async def main() -> None:
    client = binance(
        config={
            "newUpdates": True,
            "apiKey": "my_api_key_from_binance",
            "secret": SECRET_KEY,
        }
    )

    print(await client.fetch_balance())
    await client.close()


if __name__ == "__main__":
    asyncio.run(main())
```

If we run this code on CCXT 2.6.36, it raises:
```
Traceback (most recent call last):
  File "/Users/pd/git/cryptocracker/cryptocracker/run/binance_rsa.py", line 23, in <module>
    asyncio.run(main())
  File "/Users/pd/.pyenv/versions/3.10.6/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Users/pd/.pyenv/versions/3.10.6/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/Users/pd/git/cryptocracker/cryptocracker/run/binance_rsa.py", line 18, in main
    print(await client.fetch_balance())
  File "/Users/pd/git/cryptocracker/.venv/lib/python3.10/site-packages/ccxt/async_support/binance.py", line 2083, in fetch_balance
    await self.load_markets()
  File "/Users/pd/git/cryptocracker/.venv/lib/python3.10/site-packages/ccxt/async_support/base/exchange.py", line 194, in load_markets
    raise e
  File "/Users/pd/git/cryptocracker/.venv/lib/python3.10/site-packages/ccxt/async_support/base/exchange.py", line 190, in load_markets
    result = await self.markets_loading
  File "/Users/pd/git/cryptocracker/.venv/lib/python3.10/site-packages/ccxt/async_support/base/exchange.py", line 179, in load_markets_helper
    currencies = await self.fetch_currencies()
  File "/Users/pd/git/cryptocracker/.venv/lib/python3.10/site-packages/ccxt/async_support/binance.py", line 1525, in fetch_currencies
    response = await self.sapiGetCapitalConfigGetall(params)
  File "/Users/pd/git/cryptocracker/.venv/lib/python3.10/site-packages/ccxt/async_support/binance.py", line 6192, in request
    response = await self.fetch2(path, api, method, params, headers, body, config, context)
  File "/Users/pd/git/cryptocracker/.venv/lib/python3.10/site-packages/ccxt/async_support/base/exchange.py", line 1298, in fetch2
    request = self.sign(path, api, method, params, headers, body)
  File "/Users/pd/git/cryptocracker/.venv/lib/python3.10/site-packages/ccxt/async_support/binance.py", line 6098, in sign
    signature = self.rsa(self.encode(query), self.encode(self.secret))
  File "/Users/pd/git/cryptocracker/.venv/lib/python3.10/site-packages/ccxt/base/exchange.py", line 1333, in rsa
    return priv_key.sign(Exchange.encode(request), padding.PKCS1v15(), algorithm)
  File "/Users/pd/git/cryptocracker/.venv/lib/python3.10/site-packages/ccxt/base/exchange.py", line 1396, in encode
    return string.encode('latin-1')
AttributeError: 'bytes' object has no attribute 'encode'. Did you mean: 'decode'?
```

The fix in this PR allows the client to correctly get the balance in Python.
**Note**: I didn't test this in JS.

### CODE REVIEW

**Review by sc0Vu — COMMENTED** [review]
Cool, it also works in js & php!

**Comment by pietrodn** [comment]
@carlosmiei how can I test API calls using the command line like you do?

**Comment by pietrodn** [comment]
@frosty00 the build failed for unrelated reasons, can you restart it? Thanks

**Comment by carlosmiei** [comment]
> @frosty00 the build failed for unrelated reasons, can you restart it? Thanks

@pietrodn restarted

**Pull request merged**
