### PR TITLE
feat(base): uncamelcase python/php base invocations programatically

### PR DESCRIPTION
**Pull request by ttodua**

### CODE REVIEW

**Comment by frosty00** [comment]
let's wait until after #15085 is done to look at this

**Comment by ttodua** [comment]
@carlosmiei travis passed

**Comment by carlosmiei** [comment]
build is broken here:
image

**Comment by ttodua** [comment]
hm,my last push seems broke it, sorry. give me 1 min

**Comment by ttodua** [comment]
@carlosmiei travis build didnt break, you can revise now

**Comment by carlosmiei** [comment]
image
image

I think we have some unintended changes here

**Comment by ttodua** [comment]
> I think we have some unintended changes here


@carlosmiei two things: 
1) md5 does not seem breaking change, instead, if you look closely (one line above) the `hmac` method expects the methods itself to be passed (i've also checked iirc and argument is not expected to be a string). so imo it fixes some existing mistake

2) i've pushed a manual fix in transpiler for it.

**Comment by ttodua** [comment]
@carlosmiei travis seems to be passing (95% now) so this PR might be ready for re-review?

**Pull request merged**
