### PR TITLE
Add support for overriding IP

### PR DESCRIPTION
**Pull request by janeCMD**

### CODE REVIEW

**Comment by kroitor** [comment]
Reference: #824

**Comment by kroitor** [comment]
Hi, @janeCMD ! Would you mind if I rename that option from `ipOverride` → `curl_interface` ?

**Comment by janeCMD** [comment]
@kroitor it doesnt really matter. Important is its possible to override :)

**Comment by kroitor** [comment]
@janeCMD thx! Merged it, available in current version of ccxt ) Cheers!

**Pull request merged**
