### PR TITLE
Fetch Withdrawals fix

### PR DESCRIPTION
**Pull request by akatyal**
To remove exchange error as the exchange is not returning fee

### CODE REVIEW

**Comment by kroitor** [comment]
Sorry, but poloniex actually does return the fees:

```Python
mbp:ccxt igorkroitor$ python examples/py/cli.py poloniex fetch_withdrawals
[{'address': '0x731015ff2e75261d50433fbd05bd57e942336149',
  'amount': 0.155,
  'currency': u'ETH',
  'datetime': '2017-12-24T07:08:09.000Z',
  'fee': {'cost': 0.005, 'currency': u'ETH'},  # ←---------------------------------- HERE IT IS
  'id': '9290444',
  'info': {u'address': u'0x731015ff2e75261d50433fbd05bd57e942336149',
           u'amount': u'0.15500000',
           u'currency': u'ETH',
           u'fee': u'0.00500000',  # ←---------------------------------- HERE IT IS
           u'ipAddress': u'5.228.227.214',
           u'status': u'COMPLETE: 0x74d444493b4bca668992021fd9e54b5292b8e71d9927af1f076f554e4bea5b2d',
           u'timestamp': 1514099289,
           'type': 'withdrawal',
           u'withdrawalNumber': 9290444},
  'status': 'ok',
  'tag': None,
  'timestamp': 1514099289000,
  'txid': '0x74d444493b4bca668992021fd9e54b5292b8e71d9927af1f076f554e4bea5b2d',
  'type': 'withdrawal',
  'updated': None},
...
```

Also, we should not edit *.py files as described in the *.py file you edited and in our CONTRIBUTING doc:

- https://github.com/ccxt/ccxt/pull/4272/files#diff-abe4453f677bdb11e34892d3217574ccR3
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#multilanguage-support
- https://github.com/ccxt/ccxt/wiki/FAQ#hey-the-fix-youve-uploaded-is-in-js-would-you-fix-python--php-as-well-please

Anyways, we will be happy to see more PRs from you in future, as we appreciate your participation and your effort!

**Comment by kroitor** [comment]
@akatyal if there's a particular withdrawal that does not parse correctly, please paste your verbose output here, as decribed in https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

**Comment by akatyal** [comment]
I think this happens when you immediately fetch withdrawals after initiating a withdrawal transaction. In any case I agree with you that fees comes in all normal cases.

**Comment by akatyal** [comment]
Now I am getting a “string indices must be integers” exception if deposits are pending. This seems to be in the method filterByCurrencySinceLimit however still exploring

**Comment by kroitor** [comment]
@akatyal `parseTransactions` accepts a currency structure, not a code string. Therefore the place you copy-pasted above has no bug in it. The actual bug with the withdrawal fee should be fixed by now in version 1.17.578 or higher. Or do you still have issues with it after updating the CCXT? If you still have a problem after updating, then we'd ask you to provide the verbose output of the fetchTransactions method as described here:

- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue
- https://github.com/ccxt/ccxt/wiki/FAQ#im-trying-to-run-the-code-but-its-not-working-how-do-i-fix-it

**Comment by akatyal** [comment]
The patch I have pasted is the fixed version ... currently it is passing
the code not currency causing exceptions.
I am new so don't know how to contribute code but will read up.  This I
just pasted to let you know there is an issue and this is the fix

**Comment by kroitor** [comment]
@akatyal ok, now i see it, thx for explaining it! Indeed, there was a bug with it, and I've added a fix for it as well, this one will be available as of version 1.17.580+ (again, the build will require some not very long time, so it will downloadable in 10 minutes or so). Thx again for reporting it, your involvement is really helpful!

**Pull request closed without merging**
