### PR TITLE
Propagate loaded fees to markets and currencies

### PR DESCRIPTION
**Pull request by frosty00**
`fetchMarkets` needs a lot of cleaning up on many exchanges so I will make another pull requests for that.

Nonetheless this pull request propagates the loaded fees to markets and currencies. The order in which is does is such:

* First, it extends .markets with the hardcoded fee information

* Next, it will overwrite that fee information with any fees that came from fetchMarkets

* Finally, it will attempt to extend markets with any fees that have been loaded from non-standard endpoints (hence the `fee_loaded`).

This works really well for livecoin and bitfinex (poloniex is the only other exchange that has fetch_fees but it works less well because it needs to have the .has['fetchFees'] and is not yet separated in fetchTradingFees and fetchFundingFees. Prior to loading fees bitfinex did not have any fees inside currencies and now it does (if load_fees is called).

### CODE REVIEW

**Comment by frosty00** [comment]
Also is it worth considering changing the default behavior of setMarkets to extend currencies with hardcoded fees and then loaded withdrawal fees in a similar fashion to what we are doing with markets?

**Comment by frosty00** [comment]
Sorry to bother,

Can we assume that a market is active in fetchMarkets?

https://github.com/ccxt/ccxt/blob/master/js/kraken.js#L282

**Comment by kroitor** [comment]
> Can we just assume that a market is active in fetchMarkets?

With Kraken it's a little different than with other exchanges. Most of them will still list delisted symbols with `active = true` (or some flag indicating their *non-trading* status). But with Kraken, delisted symbols are filtered on the exchange side, and we always get a list of currently traded symbols from that endpoint. This is the reason for having a Kraken-specific method named `appendInactiveMarkets()` here: https://github.com/ccxt/ccxt/blob/master/js/kraken.js#L305

**Comment by kroitor** [comment]
> Also is it worth considering changing the default behavior of setMarkets to extend currencies with hardcoded fees and then loaded withdrawal fees in a similar fashion to what we are doing with markets?

I don't really think we should mix them in this way... What I like better is to have the following:

- `load()` (calls loadPublic, loadPrivate)
- `loadPublic()` (calls loadMarkets, loadCurrencies)
- `loadPrivate()` (calls loadFees(), probably loads some other info as well such as traded volume, currently available user accounts, where many of them are supported, etc...)
- `loadMarkets()` (calls fetchMarkets, setMarkets)
- `loadCurrencies()` (calls fetchCurrencies, setCurrencies)
- `loadFees()` (calls loadFundingFees, loadTradingFees)
- `loadFundingFees()` (calls fetchFundingFees, setFundingFees)
- `loadTradingFees()`(calls fetchTradingFees, setTradingFees)
- \+ whatever we might need...

Seems there should be a separate propagation layer on top and it has to satisfy the following:
- **funding**:
  - take funding fees from whatever source is accurate/appropriate:
    - loaded currencies
    - predefined values
    - loaded funding fees (this often falls into the private part of the API, unfortunately, and this also add to the reasoning behind the list of methods above)
  - propagate funding fees to whatever destination is appropriate:
    - currencies
    - `.fees['funding']`
- **trading**:
  - take trading fees from whatever source is accurate/appropriate:
    - loaded markets
    - predefined values
    - loaded trading fees
  - propagate trading fees to whatever destination is appropriate:
    - markets
    - `.fees['trading']`
- don't lose the info that is necessary to distinct the *predefined* from *loaded*

**Comment by frosty00** [comment]
What you described is a pretty large refactor of the base class code. Perhaps you would like to make a new branch that we can work on? 

Furthermore if we implement the base exchange class in the way you described it would be backwards incompatible, since loadMarkets would no longer load currencies as well. Are you ok with this?

I am definitely be willing to help you work towards this goal - at least for the python base class. I agree with this loading things this way (even if it is a bit verbose) as it is the only sane way to manage three different languages. 

I'm going to save your comment so that we can that anybody who wants to help us on the refactor understands what to do.

**Pull request closed without merging**
