### PR TITLE
Add p2pb2b exchange

### PR DESCRIPTION
**Pull request by ftuyama**
Related to & fixes https://github.com/ccxt/ccxt/issues/4158

### CODE REVIEW

**Comment by karlandoh** [comment]
+1

**Comment by ftuyama** [comment]
I've been using this API integration for quite some time and had no more issues. This PR is not very clean, but it's working fine.

**Comment by 1amth30n3** [comment]
Hi

Any chance of implementation soon?

**Comment by kroitor** [comment]
@1amth30n3 hi! This is answered here: https://github.com/ccxt/ccxt/wiki/FAQ#can-you-implement-feature-foo-in-exchange-bar. We will get to it as soon as possible.

**Comment by ftuyama** [comment]
We've been using for a while this branch to connect to p2pb2b successfully. Maybe we can merge it, @kroitor ? Do you have any comments about it?

**Pull request closed without merging**
