### PR TITLE
base.exchange.fetchPosition

### PR DESCRIPTION
**Pull request by samgermain**
```
% gateio fetchPosition BTC/USD:BTC         
2022-01-08T01:29:19.678Z
Node.js: v14.17.0
CCXT v1.66.26
gateio.fetchPosition (BTC/USD:BTC)
179 ms
{
  info: {
    value: '0.005215942397',
    leverage: '100',
    mode: 'single',
    realised_point: '0',
    contract: 'BTC_USD',
    entry_price: '42037.83',
    mark_price: '41986.66',
    history_point: '0',
    realised_pnl: '-0.000002500605',
    close_order: null,
    size: '-219',
    cross_leverage_limit: '10',
    pending_orders: '1',
    adl_ranking: '5',
    maintenance_rate: '0.005',
    unrealised_pnl: '0.00000634962',
    user: '6693577',
    leverage_max: '100',
    history_pnl: '-0.000036292217',
    risk_limit: '100',
    margin: '0.000056003122',
    last_close_pnl: '-0.000005727294',
    liq_price: '42250.3'
  },
  symbol: 'BTC/USD:BTC',
  timestamp: undefined,
  datetime: undefined,
  initialMargin: 0.00005607138076775,
  initialMarginPercentage: 0.01075,
  maintenanceMargin: 0.000026079711985,
  maintenanceMarginPercentage: 0.005,
  entryPrice: 42037.83,
  notional: 0.005215942397,
  leverage: 100,
  unrealizedPnl: 0.00000634962,
  contracts: -219,
  contractSize: 0,
  marginRatio: undefined,
  liquidationPrice: 42250.3,
  markPrice: 41986.66,
  collateral: 0.000056003122,
  marginType: undefined,
  side: 'sell',
  percentage: 11.32417271174468
}
```

```
2022-01-08T01:32:36.199Z
Node.js: v14.17.0
CCXT v1.66.26
gateio.fetchPositions ()
178 ms
        symbol | timestamp | datetime | initialMargin | initialMarginPercentage | maintenanceMargin | maintenanceMarginPercentage | entryPrice | notional | leverage | unrealizedPnl | contracts | contractSize | marginRatio | liquidationPrice |   markPrice | collateral | marginType | side | percentage
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 BTC/USDT:USDT |           |          |             0 |                         |                 0 |                       0.005 |          0 |        0 |      100 |             0 |         0 |       0.0001 |             |                0 |    41999.18 |          0 |            |      |           
...
MOVR/USDT:USDT |           |          |             0 |                         |                 0 |                       0.025 |          0 |        0 |        0 |             0 |         0 |         0.01 |             |                0 |      165.13 |          0 |            |      |           
GALA/USDT:USDT |           |          |             0 |                         |                 0 |                       0.025 |          0 |        0 |        0 |             0 |         0 |           10 |             |                0 |     0.35012 |          0 |            |      |           
9 objects

2022-01-08T01:32:48.084Z
Node.js: v14.17.0
CCXT v1.66.26
gateio.fetchPositions (BTC/USD:BTC)
202 ms
     symbol | timestamp | datetime |      initialMargin | initialMarginPercentage | maintenanceMargin | maintenanceMarginPercentage | entryPrice |       notional | leverage |  unrealizedPnl | contracts | contractSize | marginRatio | liquidationPrice | markPrice |     collateral | marginType | side |        percentage
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
BTC/USD:BTC |           |          | 0.0000560536781945 |                 0.01075 |  0.00002607147823 |                       0.005 |   42037.83 | 0.005214295646 |      100 | 0.000004702869 |      -219 |            0 |             |          42250.3 |  41999.92 | 0.000056003122 |            | sell | 8.389938272527933
1 objects

2022-01-08T01:32:58.265Z
Node.js: v14.17.0
CCXT v1.66.26
gateio.fetchPositions (BTC/USD:BTC,BTC/USDT:USDT)
BadRequest gateio fetchPositions symbols must all be settled in the same currency
---------------------------------------------------

2022-01-08T01:33:23.187Z
Node.js: v14.17.0
CCXT v1.66.26
gateio.fetchPositions (BTC/USDT:USDT,GALA/USDT:USDT)
170 ms
        symbol | timestamp | datetime | initialMargin | initialMarginPercentage | maintenanceMargin | maintenanceMarginPercentage | entryPrice | notional | leverage | unrealizedPnl | contracts | contractSize | marginRatio | liquidationPrice | markPrice | collateral | marginType | side | percentage
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 BTC/USDT:USDT |           |          |             0 |                         |                 0 |                       0.005 |          0 |        0 |      100 |             0 |         0 |       0.0001 |             |                0 |  41994.74 |          0 |            |      |           
GALA/USDT:USDT |           |          |             0 |                         |                 0 |                       0.025 |          0 |        0 |        0 |             0 |         0 |           10 |             |                0 |   0.35042 |          0 |            |      |           
2 objects
```

### CODE REVIEW

**Comment by frosty00** [comment]
on minor issue - `fetchPositions` returns an array with one element whereas `fetchPosition` will return an object so we need to dereference the first item of the array

**Comment by samgermain** [comment]
> on minor issue - `fetchPositions` returns an array with one element whereas `fetchPosition` will return an object so we need to dereference the first item of the array

`fetchPosition` only takes a symbol command, but there might be multiple positions for the same symbol, even at the same time

**Comment by frosty00** [comment]
> on minor issue - fetchPositions returns an array with one element whereas fetchPosition will return an object so we need to dereference the first item of the array
fetchPosition only takes a symbol command, but there might be multiple positions for the same symbol, even at the same time

That's only in hedged mode which imo is a noob mode cause you pay more fees

**Comment by frosty00** [comment]
but yeah we'll need to support it

**Comment by samgermain** [comment]
> on minor issue - `fetchPositions` returns an array with one element whereas `fetchPosition` will return an object so we need to dereference the first item of the array

When I try to use `return await this.safeValue (this.fetchPositions ([symbol], params), 0);`, I get undefined as a response, but `return await this.fetchPositions ([symbol], params);` returns the one item

**Comment by kroitor** [comment]
> When I try to use `return await this.safeValue (this.fetchPositions ([symbol], params), 0);`

You've misplaced the `await` keyword in the above expression.

**Comment by samgermain** [comment]
@kroitor Are there any more problems with this PR?

**Comment by kroitor** [comment]
@samgermain i think, if we're emulating fetchPosition with fetchPositions, then the default value of fetchPosition must be `emulated` and the exchanges that don't have a true `fetchPosition` endpoint must not override that capability to `true`. Let me know if you agree.

**Comment by samgermain** [comment]
> @samgermain i think, if we're emulating fetchPosition with fetchPositions, then the default value of fetchPosition must be `emulated` and the exchanges that don't have a true `fetchPosition` endpoint must not override that capability to `true`. Let me know if you agree.

If the default state is emulated, will it be emulated on every exchange? Even the ones that don't implement `fetchPositions`?

**Comment by kroitor** [comment]
> If the default state is emulated, will it be emulated on every exchange? Even the ones that don't implement `fetchPositions`?

Yes, but it will throw an exception, if those exchanges don't have `fetchPositions`.
Alternatively, we can set `fetchPosition = 'emulated'` on just those exchanges that have `fetchPositions` but don't have `fetchPosition`.

**Comment by samgermain** [comment]
> > If the default state is emulated, will it be emulated on every exchange? Even the ones that don't implement `fetchPositions`?
> 
> Yes, but it will throw an exception, if those exchanges don't have `fetchPositions`. Alternatively, we can set `fetchPosition = 'emulated'` on just those exchanges that have `fetchPositions` but don't have `fetchPosition`.

It would be better if we could come up with a dynamic solution, like have something at the end of loadMarkets where we check if `fetchPositions` is defined, but not `fetchPosition` and set `fetchPosition` to emulated if it is. It would also work for `fetchBorrowRate` so maybe something at the end that takes a list of tuples like

```
setFirstToEmulatedIfHasSecondButNotFirst([
    ('fetchPosition', 'fetchPositions'),
    ('fetchBorrowRate', 'fetchBorrowRates'),
]
```

**Comment by kroitor** [comment]
@samgermain i'll think about adding that in the base classes, but probably not in loadMarkets, but in a standalone method called from the constructor.

**Comment by samgermain** [comment]
> @samgermain i'll think about adding that in the base classes, but probably not in loadMarkets, but in a standalone method called from the constructor.

That's what I meant, sorry

**Comment by samgermain** [comment]
@kroitor I added the functionality to add `emulated` to `has` if the multi market method is implemented, but take a look at this PR https://github.com/ccxt/ccxt/pull/12008 . It actually creates the single market method if the multi market one is implemented

**Comment by samgermain** [comment]
Since https://github.com/ccxt/ccxt/pull/12008 was closed, this PR should be fine. The `emulateSingleMarketMethod` will be useful on other PRs also

**Comment by samgermain** [comment]
@kroitor Can this be merged or do you want some changes with it?

**Pull request closed without merging**
