### PR TITLE
feat(bigone):assets to v3

### PR DESCRIPTION
**Pull request by cjh-cao**

### CODE REVIEW

**Comment by cjh-cao** [comment]
@kroitor @frosty00 please reviewe,thanks

**Comment by carlosmiei** [comment]
@cjh-cao, aren't we losing the networks information here?

**Comment by cjh-cao** [comment]
> @cjh-cao, aren't we losing the networks information here?

Did not lose the networking information; we streamlined the networking information.

**Comment by carlosmiei** [comment]
@cjh-cao got it, thanks!

**Pull request merged**
