### PR TITLE
Bitcoincoid orders

### PR DESCRIPTION
**Pull request by Cengkaruk**
- fetchOrder

Got inconsistent in IDR symbol response, so parseOrder need detect this. Sample response [here](https://pastebin.com/BEkBmrgQ)

- fetchOrders

Working smothly.

- fetchClosedOrders

However, `status` with value `filled` are not filtered. Still got empty array. Sample response [here](https://pastebin.com/x4ZY02ZJ)

### CODE REVIEW

**Comment by kroitor** [comment]
Thank you for your involvement! Merging very soon!

**Comment by Cengkaruk** [comment]
You are welcome, more request are coming :)

**Comment by Cengkaruk** [comment]
Hi @kroitor 

Why you remove `fetchOrders`?

**Comment by kroitor** [comment]
> Why you remove fetchOrders?

Because it can only fetch closed orders. So, bitcoin.co.id does not have that method. Check out the implementation of liqui to see how we emulate those methods via fetchOpenOrders + cache. Hope it answers your question. Thx!

**Comment by Cengkaruk** [comment]
Aaaah, i see. Thanks.

**Comment by kroitor** [comment]
@Cengkaruk thanks to you, actually )

**Pull request merged**
