### PR TITLE
ftx fetchOHLCV fixes #12258

### LINKED ISSUE #12258: Candle recovery issue on FTX, using the "since" argument
Hello,
There is a candle recovery issue on FTX, using the "since" argument.
It works for some time units, but not for monthly or weekly.
I'm using CCXT version `1.75.18` under TypeScript.

```
        const symbol = 'BTC/USD'
        const exchange = new ccxt.ftx()

        console.log(exchange.timeframes)

        const timeFrameMonthly = '1M'
        const timeFrameWeekly = '1w'
        const timeFrameDaily = '1d'
        const timeFrame4h = '4h'

        let from = 1609459200 * 1000 // first day of 2021

        console.log('---')
        console.log('from', from, new Date(from))

        let ohlcvList = await exchange.fetchOHLCV(symbol, timeFrameMonthly, from)
        console.log('monthly', ohlcvList.length)

        ohlcvList = await exchange.fetchOHLCV(symbol, timeFrameWeekly, from)
        console.log('weekly', ohlcvList.length)

        ohlcvList = await exchange.fetchOHLCV(symbol, timeFrameDaily, from)
        console.log('daily', ohlcvList.length)

        ohlcvList = await exchange.fetchOHLCV(symbol, timeFrame4h, from)
        console.log('4hours', ohlcvList.length)

        from = 1640995200 * 1000 // first day of 2022
        console.log('---')
        console.log('from', from, new Date(from))


        ohlcvList = await exchange.fetchOHLCV(symbol, timeFrameMonthly, from)
        console.log('monthly', ohlcvList.length)

        ohlcvList = await exchange.fetchOHLCV(symbol, timeFrameWeekly, from)
        console.log('weekly', ohlcvList.length)

        ohlcvList = await exchange.fetchOHLCV(symbol, timeFrameDaily, from)
        console.log('daily', ohlcvList.length)

        ohlcvList = await exchange.fetchOHLCV(symbol, timeFrame4h, from)
        console.log('4hours', ohlcvList.length)

        console.log('---')
        ohlcvList = await exchange.fetchOHLCV(symbol, timeFrameMonthly)
        console.log('monthly (no since)', ohlcvList.length)
        console.log('first candle date', ohlcvList[0][0], new Date(ohlcvList[0][0]))

        console.log('---')
        ohlcvList = await exchange.fetchOHLCV(symbol, timeFrameWeekly)
        console.log('weekly (no since)', ohlcvList.length)
        console.log('first candle date', ohlcvList[0][0], new Date(ohlcvList[0][0]))
```

Résult :

```
{
  '15s': '15',
  '1m': '60',
  '5m': '300',
  '15m': '900',
  '1h': '3600',
  '4h': '14400',
  '1d': '86400',
  '3d': '259200',
  '1w': '604800',
  '2w': '1209600',
  '1M': '2592000'
}
---
from 1609459200000 2021-01-01T00:00:00.000Z
monthly 0
weekly 0
daily 433
4hours 1501
---
from 1640995200000 2022-01-01T00:00:00.000Z
monthly 0
weekly 0
daily 68
4hours 407
---
monthly (no since) 34
first candle date 1563667200000 2019-07-21T00:00:00.000Z
---
weekly (no since) 138
first candle date 1563667200000 2019-07-21T00:00:00.000Z
```

### PR DESCRIPTION
**Pull request by ttodua**
The realistic way to achieve best results, seems this approach.
notes: the default amount was not 1501, but it seems to be 1499  (i.e. [check this](https://ftx.com/api/markets/BTC/USD/candles?resolution=60)). 

_[fixes #12258]_

### CODE REVIEW

**Comment by kroitor** [comment]
This fix isn't entirely correct cause the FTX exchange can return 1500 candles, not just 1499.

**Comment by ttodua** [comment]
@kroitor very strange. Now, when I go on that link, I do confirm - there are 1500 items. However, for sure I can say, that by the time I was working and posted that, have checked that dozen times, and was returning 1499 items. 
I'll catch the similar occasion and will notify you on the fly to see it yourself.

**Comment by ttodua** [comment]
Funny thing - I've had that tab left in browser. See [example screenshot](https://i.imgur.com/kXUYrdP.png) . it shows 1499 items. the time was 20:34 (16:34 UTC). but when I visit the same link, it now returns 1500 items.

**Comment by kroitor** [comment]
@ttodua the timestamping math there is not intuitive (on the exchange side, so the code that was there – was there for a reason) but if you investigate deeper, i'm sure you will see and understand it.

**Comment by ttodua** [comment]
Announcement:
- To avoid frustration and inconsistency by default usage of ccxt (so, users don't get unexpected result, instead of expected unified approach), from `fetch OHLCV` method we are removing timeframes above 1 day (3d, 1w, 1M ..) , because those data are aligned to the current realtime moment, i.e.when you request 1week candles, the CLOSE price will be the current price, and the OPEN price will be the price of 7 days ago exactly from the request moment. 
Thus, the 'rotating' candles actually are not the candles that falls under standard of definition of bar/candle: it should start from the fixed time and end at fixed time, i.e. 1 Week candle should start from Monday. But FTX API doesn't work this way, so we are removing 'timeframe' property support above 1 day (candles under <= 1 day work as intended).

However, whoever still wants such data, of course they can set the params, like:

```
params = { 'resolution': 86400 * 3}; // 3 day
fetchOHLCV (........ , params );
```

**Comment by ttodua** [comment]
I don't quite understand why the code is the way it is (unanswered question still about limits, why it's 1501 max, while it has max 5000, and even why number 1501, while it has 1499 and 1500 cases too), but it's ok if users dont have problem anylonger.

**Pull request merged**
