### PR TITLE
Class docstrings

### PR DESCRIPTION
**Pull request by samgermain**
JS class docstrings are transpiled from this

```
/**
 * @class
 * @name aax
 * @description exchange class for aax api
 */
```

into python

```
"""
exchange class for aax api
"""
```

and PHP

```
/**
 * exchange class for aax api
 */
```

### CODE REVIEW

**Comment by kroitor** [comment]
@samgermain thx, will get to it shortly!

**Comment by samgermain** [comment]
@kroitor Once this PR get's merged, I'll be able to create autogenerated documentation for each exchange, which I'm thinking is going to be a pretty big SEO boost

**Comment by samgermain** [comment]
@carlosmiei Can you take a look at this? I have some other PRs that are dependant on these changes

**Comment by samgermain** [comment]
@kroitor @frosty00 @carlosmiei 

Could this PR get merged? I need it to finish up exchange specific documentation. Also with the amount of files edited, there's a higher chance of merge conflicts coming up, and if merge conflicts start showing up in `transpile.js` I'm going to have a really difficult time resolving them because the last time I worked on this was a long time ago

**Comment by samgermain** [comment]
reopened in #18064

**Pull request closed without merging**
