### PR TITLE
fix(kucoinfutures) - fix funding value

### LINKED ISSUE #20894: Incorrect output of the financing rate
### Operating System

Windows 11

### Programming Languages

Python

### CCXT Version

4.2.18

### Description

On the kucoinfutures exchange in async_support, the response in the fetch_funding_rate() function is not output correctly. In the **fundingRate** key the **predictedValue** is written, not the usual value. Accordingly, **predictedValue** should be written to **nextFundingRate**. I would like you to add **fundingTimestamp**, to calculate it we need to add **granularity** to **timePoint**. The code is taken from the file venv\Lib\site-packages\ccxt\async_support\kucoinfutures.py

### Code

```
  async def fetch_funding_rate(self, symbol: str, params={}):
        """
        fetch the current funding rate
        :see: https://www.kucoin.com/docs/rest/futures-trading/market-data/get-current-funding-rate
        :param str symbol: unified market symbol
        :param dict [params]: extra parameters specific to the exchange API endpoint
        :returns dict: a `funding rate structure <https://docs.ccxt.com/#/?id=funding-rate-structure>`
        """
        await self.load_markets()
        market = self.market(symbol)
        request = {
            'symbol': market['id'],
        }
        response = await self.futuresPublicGetFundingRateSymbolCurrent(self.extend(request, params))
        #
        #    {
        #        "code": "200000",
        #        "data": {
        #            "symbol": ".ETHUSDTMFPI8H",
        #            "granularity": 28800000,
        #            "timePoint": 1637380800000,
        #            "value": 0.0001,
        #            "predictedValue": 0.0001,
        #        },
        #    }
        #
        data = self.safe_value(response, 'data')
        fundingTimestamp = self.safe_number(data, 'timePoint')
        # the website displayes the previous funding rate as "funding rate"
        return {
            'info': data,
            'symbol': market['symbol'],
            'markPrice': None,
            'indexPrice': None,
            'interestRate': None,
            'estimatedSettlePrice': None,
            'timestamp': None,
            'datetime': None,
            'fundingRate': self.safe_number(data, 'predictedValue'),
            'fundingTimestamp': None,
            'fundingDatetime': None,
            'nextFundingRate': None,
            'nextFundingTimestamp': None,
            'nextFundingDatetime': None,
            'previousFundingRate': self.safe_number(data, 'value'),
            'previousFundingTimestamp': fundingTimestamp,
            'previousFundingDatetime': self.iso8601(fundingTimestamp),
        }

```

### PR DESCRIPTION
**Pull request by ttodua**
fix #20894

### CODE REVIEW

**Comment by carlosmiei** [comment]
are you sure about this? we have this comment in the code 
image

**Comment by ttodua** [comment]
> are you sure about this? we have this comment in the code 
I am not sure, but that same comment seems to be copy-pasted between `poloniexfutures` and `kucoinfutures`, so which one is correct, I can't say. 
I'm checking that with Kucoin Api support rep.

**Comment by ttodua** [comment]
api docs page (linked above) seems to be intuitive and specific. however, actually it does not come true: 
i.e. when comparing : https://www.kucoin.com/futures/trade/XBTUSDTM
to
https://api-futures.kucoin.com/api/v1/funding-rate/XBTUSDM/current

I see no relation with each other. what i see that , from above API response the `value` seems to be same as in `history funding rates`'s last occurred value (so, yes, it seems "previous funding rate")

https://api-futures.kucoin.com/api/v1/contract/funding-rates?symbol=XBTUSDM&from=1705800255000&to=1705870255000

**Comment by ttodua** [comment]
@carlosmiei it's a funny now. look at this official (documented) urls:
- https://api-futures.kucoin.com/api/v1/contracts/XBTUSDM
and 
- https://api-futures.kucoin.com/api/v1/contracts/active (find  XBTUSDM )

fundingFeeRate have quite different values across those two

**Comment by ttodua** [comment]
ah mistake.

**Comment by ttodua** [comment]
@carlosmiei so
when comparing : https://www.kucoin.com/futures/trade/XBTUSDTM
to
https://api-futures.kucoin.com/api/v1/funding-rate/XBTUSDTM/current

seems that UI shows the "current" FR as "value" field, and when you mouseover in UI number, it switches to "Predicted Value" which is same as from api.
So, I suppose this PR is correct.

**Pull request merged**
