### PR TITLE
Bl3p precise

### PR DESCRIPTION
**Pull request by samgermain**
```
2022-09-20T19:22:12.105Z
Node.js: v18.9.0
CCXT v1.93.66
bl3p.fetchOrderBook (BTC/EUR)
2022-09-20T19:22:12.963Z iteration 0 passed in 830 ms

{
  symbol: 'BTC/EUR',
  bids: [
    [ 19079.93999, 0.11399 ],
    ...
    [ 0.01, 100100 ]
  ],
  asks: [
    [ 19170, 0.0227 ],
    ...
    [ 1000000, 0.15148712 ]
  ],
  timestamp: undefined,
  datetime: undefined,
  nonce: undefined
}
2022-09-20T19:22:12.963Z iteration 1 passed in 830 ms
```

### CODE REVIEW

**Comment by frosty00** [comment]
this code returns a string and not a number for the orderbook objects. let's make sure we fully test the precise code edits...

**Comment by samgermain** [comment]
> this code returns a string and not a number for the orderbook objects. let's make sure we fully test the precise code edits...

I didn't test it because I don't have apiKeys.

Also if the PR is a draft, that means it's not ready to merge. There's a good chance that it isn't fully tested if it's a draft.

**Comment by samgermain** [comment]
```
% bl3p createOrder BTC/EUR limit buy 0.001 12000
2022-09-20T19:20:31.485Z
Node.js: v18.9.0
CCXT v1.93.66
bl3p.createOrder (BTC/EUR, limit, buy, 0.001, 12000)
(node:16358) ExperimentalWarning: The Fetch API is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
2022-09-20T19:20:32.253Z iteration 0 passed in 728 ms

{
  info: { result: 'success', data: { order_id: '179092203' } },
  id: '179092203'
}
2022-09-20T19:20:32.253Z iteration 1 passed in 728 ms
```

```
2022-09-20T19:22:12.105Z
Node.js: v18.9.0
CCXT v1.93.66
bl3p.fetchOrderBook (BTC/EUR)
2022-09-20T19:22:12.963Z iteration 0 passed in 830 ms

{
  symbol: 'BTC/EUR',
  bids: [
    [ 19079.93999, 0.11399 ],
    ...
    [ 0.01, 100100 ]
  ],
  asks: [
    [ 19170, 0.0227 ],
    ...
    [ 1000000, 0.15148712 ]
  ],
  timestamp: undefined,
  datetime: undefined,
  nonce: undefined
}
2022-09-20T19:22:12.963Z iteration 1 passed in 830 ms
```

**Comment by carlosmiei** [comment]
LGTM ✅ 

```
 p bl3p fetchOrderBook "BTC/EUR" 2          
Python v3.9.7
CCXT v1.93.66
bl3p.fetchOrderBook(BTC/EUR,2)
{'asks': [[20000.86288, 0.0238],
          [20012.86032, 0.0476],
          [20031.47, 0.099828],
          [20031.64456, 0.0952],
          [20032.05425, 0.3808],
          [20041.46999, 0.41618769],
          [20041.64039, 0.1904],
          [20045.25537, 0.7616],
          [20299.0, 0.2],
          [20350.0, 0.02513884],
```

**Review by carlosmiei — APPROVED** [review]

**Pull request merged**
