### PR TITLE
gateio: fetchOrder, cancelOrder, createOrder, queryDeposit, handleErrors

### PR DESCRIPTION
**Pull request by egorFiNE**
based on initial work by @lfern

### CODE REVIEW

**Comment by frosty00** [comment]
@kroitor any chance you could merge this soon?

**Comment by kroitor** [comment]
@frosty00 fingers crossed, yes, there is a chance, i mean, i'm currently finishing the work on transpiled tests (right now), and if everything goes well, i'll merge most of these PRs right after.

**Comment by frosty00** [comment]
Awesome, @egorFiNE this PR still needs alot of cleaning up, getting a couple of errors still so will merge my branch once this gets merged.

**Comment by egorFiNE** [comment]
> Awesome, @egorFiNE this PR still needs alot of cleaning up, getting a couple of errors still so will merge my branch once this gets merged.

I believe I will push another PR immediately after this one is merged, we're working on gateio now. 

@frosty00  Meanwhile I would greatly appreciate feedback on what cleanup is needed, what kind of errors do you get and what's the unified signature?

**Comment by frosty00** [comment]
```
  File "/home/carlo/arbitrage/ccxt/gateio.py", line 418, in create_order
    return self.parse_order(response, None, symbol, side, amount)
  File "/home/carlo/arbitrage/ccxt/gateio.py", line 345, in parse_order
    market = self.safe_value(self.marketsById, order['currencyPair'])
KeyError: 'currencyPair'
```
I reverted to an older version. What I mean by the unified function signature is that `parseOrder` should only take two arguments - order and market. Just take a look at any other exchange file - https://github.com/ccxt/ccxt/blob/master/js/bittrex.js#L502

**Comment by kroitor** [comment]
@egorFiNE that KeyError in python says: *"no such key named `currencyPair` in order dictionary"* – python is much more strict about it, and we have to check if the key is there before dereferencing it, otherwise it will complain.

**Comment by egorFiNE** [comment]
@kroitor updated fix for python. 

Regarding the unified signature, how do we go around the fact that `cancelOrder()` might know something that is not supplied to `parseOrder()`? What would be your suggestions, @kroitor @frosty00 ?

**Comment by kroitor** [comment]
> Regarding the unified signature, how do we go around the fact that cancelOrder() might know something that is not supplied to parseOrder()? What would be your suggestions, @kroitor @frosty00 ?

I'd say it depends on the information in questions. Most of the time it should go to `info`.

**Comment by egorFiNE** [comment]
> I'd say it depends on the information in question. Most of the time it should go to info (containing the entire exchange response as is).

Excuse me for ambiguous question :) What I meant to say that there is some information that we have POSTed to the exchange which wasn't returned back from the `cancelOrder()` call. Say, I certainly know the order id being cancelled. The exchange response doesn't contain the order id and I might as well augment `parseOrder()`s result from within `cancelOrder()` or just supply additional arguments to `parseOrder()`. 

What's better?

**Comment by kroitor** [comment]
> The exchange response doesn't contain the order id and I might as well augment parseOrder()s result from within cancelOrder() or just supply additional arguments to parseOrder().
> What's better?

I'd do it in the way that would not require changing methods' signatures. So, if `parseOrder` does accept a raw `order` and `market = undefined` in the arguments, then we should pass the order `id` coming from the arguments of cancelOrder in the `order` argument of the `parseOrder`. This is probably less convenient, but it's more portable. So, I'd do this by augmentation from within cancelOrder.

On the other hand, you can define `parseOrderInYourOwnSpecificWay (yourArgumentsInTheOrderYouPrefer)`, and do the augmentation inside there and call `parseOrder` from there. So, in a situation where you still need some extra arguments, the best approach is to define a wrapper, not an override.

**Pull request merged**
