### PR TITLE
adding async example

### PR DESCRIPTION
**Pull request by fedecaccia**
Example to make requests to different exchanges asynchronously.

### CODE REVIEW

**Comment by fedecaccia** [comment]
The Travis CI build failed with this error:
`ERROR: InvocationError for command 'C:\\projects\\ccxt\\python\\.tox\\qa\\Scripts\\flake8.EXE' (exited with code 1)`
what is that?

**Comment by kroitor** [comment]
@fedecaccia flake is a common pythonic tool to make sure that the code and syntax corresponds to PEP8 guidelines (python standards for writing code): https://www.python.org/dev/peps/pep-0008/

**Comment by kroitor** [comment]
> is too long

Yep, it is, but we ignore a few rules and exceptions, as shown here: https://github.com/ccxt/ccxt/blob/master/python/setup.cfg#L8

You should only pay attention to critical ones, those listed on travis: 
https://travis-ci.org/ccxt/ccxt/builds/412377594?utm_source=github_status&utm_medium=notification

```
qa create: /home/travis/build/ccxt/ccxt/python/.tox/qa
qa installdeps: .[qa]
qa installed: ccxt==1.17.78,certifi==2018.4.16,chardet==3.0.4,flake8==3.5.0,idna==2.7,mccabe==0.6.1,pycodestyle==2.3.1,pyflakes==1.6.0,requests==2.19.1,urllib3==1.23
qa runtests: PYTHONHASHSEED='101594170'
qa runtests: commands[0] | flake8
./examples/py/async-tickers-mult-exchanges.py:35:43: E226 missing whitespace around arithmetic operator
./examples/py/async-tickers-mult-exchanges.py:41:42: E226 missing whitespace around arithmetic operator
```

↑ Just these two )

**Comment by fedecaccia** [comment]
Great, I haven't seen that, I thought errors where not reported, sorry. Thanks for your help!

**Comment by kroitor** [comment]
Actually, because you're not polling tickers from Binance in a repeatable fashion, it's ok to merge this example as is. Thx so much for your involvement! )

**Pull request merged**
