### PR TITLE
precision methods

### PR DESCRIPTION
**Pull request by frosty00**
need to write tests and implement significant digit + rounding but I'll do that at a later date

### CODE REVIEW

**Comment by kroitor** [comment]
Related to #1635

**Comment by kroitor** [comment]
One more significant note on this (still not implemented in JS version yet) – we also need negative precision numbers (rounding to tens, hundreds, and so on) for certain currencies and markets. Thx a lot for your effort, @frosty00 ! Let me know if you need any assistance or have questions. I'm standing by for your command.

**Comment by frosty00** [comment]
Working my way through the tests now...

**Comment by frosty00** [comment]
I'll give the code a cleanup, the test doesn't seem to like the star import.

**Pull request merged**
