### PR TITLE
delist southxchange

### PR DESCRIPTION
**Pull request by frosty00**

### CODE REVIEW

**Review by mrbaguvix — APPROVED** [review]

**Comment by ttodua** [comment]
May you write some comments when you make such updates?
I mean, the comments why XYZ exchange was delisted or whatever..

**Comment by kroitor** [comment]
@ttodua yes, we will post announcements in the future.

**Comment by ttodua** [comment]
@kroitor  Can you say two words about SouthXchange, why it was delisted.

**Comment by kroitor** [comment]
@ttodua mostly for low volumes and for locking a few accounts without a reason or notification.

**Pull request closed without merging**
