### PR TITLE
 implement negative precision in python and test 

### PR DESCRIPTION
**Pull request by frosty00**

### CODE REVIEW

**Comment by frosty00** [comment]
js and php not implemented yet..

**Comment by kroitor** [comment]
> js and php not implemented yet..

That's fine, thx anyways. I'd agree with your comments, having negative precisions is a very exchnage-specific thing, mostly for hitbtc for now... We'll add missing implementations in JS and PHP and will merge this together with #3663 hopefully, today or tomorrow. ) Also, there's an old JSON-related PR that I wanted to merge as well, however, I thought of doing a rework of exceptions first, so that they would include all necessary verbose information without the need for the `verbose` flag itself, effectively removing the `verbose` flag completely. This is something I'm going to do in JS first and I'll push to a separate branch in the coming days, so your help with porting it to Python would also be very appreciated. ;)

**Comment by adi90x** [comment]
Any update on this ?

**Comment by frosty00** [comment]
@adi90x If this gets merged then all tests for js and php will fail until someone writes the neccessary code. I guess I'll try to *maybe* do it this weekend.

**Comment by frosty00** [comment]
@kroitor just js left now

**Comment by abletaz** [comment]
any updates? I'd love this to be completed (for js) so that my trades on hitbtc can work ....

**Comment by adi90x** [comment]
Any update on this ?

**Comment by kroitor** [comment]
Merged in #4226

**Pull request closed without merging**
