### PR TITLE
Add new Exchange : WazirX 

### PR DESCRIPTION
**Pull request by dhruvv90**

### CODE REVIEW

**Comment by dhruvv90** [comment]
@kroitor Just wanted to check if you have seen this one ? Let me know your comments please.

**Review by jonhpham — APPROVED** [review]

**Comment by dhruvv90** [comment]
@kroitor  Just to follow up again - can this be merged/closed or we're looking to make some changes here?

**Comment by Eternal-Sunshine** [comment]
Plus one for this.

Waiting for merge.

**Comment by kroitor** [comment]
@dhruvv90 @Eternal-Sunshine we will get to it as soon as we can, and hopefully will get it merged soon. I don't have an ETA, but will try to resolve it asap.

**Comment by floyds1995** [comment]
Hi @kroitor ,

Any idea when this will be integrated ?
Also @dhruvv90 , kudos on the wonderfull work to integrate Wazirx !

**Comment by Sanyambansal76** [comment]
@kroitor Any deadline for getting it merged?

**Pull request closed without merging**
