### PR TITLE
Bibox fetch withdrawls and fetch deposits

### PR DESCRIPTION
**Pull request by samgermain**
```
% bibox fetchWithdrawals                            
2022-10-21T17:11:28.518Z
Node.js: v18.4.0
CCXT v2.0.53
(node:27281) ExperimentalWarning: The Fetch API is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
bibox.fetchWithdrawals ()
2022-10-21T17:11:30.331Z iteration 0 passed in 587 ms

     id |                                                               txid |     timestamp |                 datetime | network |                                    address |                                  addressTo | addressFrom | tag | tagTo | tagFrom |       type |   amount | currency | status | updated |                             fee
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
2230041 | 0xe293de66b67d75f6583be5d79831e07d49e3a2737ace8fcc8b315b5ae5590fca | 1666324662000 | 2022-10-21T03:57:42.000Z | Polygon | 0xa4d50e44877cbf7fe983420967d27a783807a79f | 0xa4d50e44877cbf7fe983420967d27a783807a79f |             |     |       |         | withdrawal | 54.08252 |    MATIC |     ok |         | {"cost":0.5,"currency":"MATIC"}
1 objects
2022-10-21T17:11:30.331Z iteration 1 passed in 587 ms
```

```
% bibox fetchDeposits                          
2022-10-21T17:11:36.283Z
Node.js: v18.4.0
CCXT v2.0.53
(node:27290) ExperimentalWarning: The Fetch API is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
bibox.fetchDeposits ()
2022-10-21T17:11:38.044Z iteration 0 passed in 527 ms

     id |                                                               txid |     timestamp |                 datetime |    network |                                    address |                                  addressTo | addressFrom | tag | tagTo | tagFrom |    type | amount | currency | status | updated |                           fee
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
2525535 | 0xb487989496012906f1739cd5c7d0cacf8348bfa11054bafc99938ea16b0bfe1b | 1640326664000 | 2021-12-24T06:17:44.000Z | BEP20(BSC) | 0xf1458ba28073b056e9666c4b2bbbc60451cda0fd | 0xf1458ba28073b056e9666c4b2bbbc60451cda0fd |             |     |       |         | deposit |   19.2 |    BUSDT |     ok |         | {"cost":0,"currency":"BUSDT"}
2548164 | 0x2e1369130bd95aebfe900235b94a90fe93c0ed55a0faa32ed0e3f30149c6e72a | 1641694620000 | 2022-01-09T02:17:00.000Z | BEP20(BSC) | 0xf1458ba28073b056e9666c4b2bbbc60451cda0fd | 0xf1458ba28073b056e9666c4b2bbbc60451cda0fd |             |     |       |         | deposit |   20.2 |    BUSDT |     ok |         | {"cost":0,"currency":"BUSDT"}
2626552 | 0x2843ea6937bb62847606549c021d638dc8a4076d06a1dd174bf7975c17ed7006 | 1645969929000 | 2022-02-27T13:52:09.000Z | BEP20(BSC) | 0xf1458ba28073b056e9666c4b2bbbc60451cda0fd | 0xf1458ba28073b056e9666c4b2bbbc60451cda0fd |             |     |       |         | deposit |   20.2 |    BUSDT |     ok |         | {"cost":0,"currency":"BUSDT"}
3034577 | 0xe7230e23de2fa74a14b0f6e8f9e8f598c96f0bfbeec66bad3c6a558709596298 | 1653494980000 | 2022-05-25T16:09:40.000Z | BEP20(BSC) | 0xf1458ba28073b056e9666c4b2bbbc60451cda0fd | 0xf1458ba28073b056e9666c4b2bbbc60451cda0fd |             |     |       |         | deposit |     15 |    BUSDT |     ok |         | {"cost":0,"currency":"BUSDT"}
3553023 | 0x2f2319c4ae804893369aeeeef06dd429abf2833b61290ea2bd63ec0e363ebce6 | 1663367581000 | 2022-09-16T22:33:01.000Z | BEP20(BSC) | 0xf1458ba28073b056e9666c4b2bbbc60451cda0fd | 0xf1458ba28073b056e9666c4b2bbbc60451cda0fd |             |     |       |         | deposit |  14.71 |    BUSDT |     ok |         | {"cost":0,"currency":"BUSDT"}
3624010 | 0x5d5fbcbe94bacf370a70dc3e8b62116b84596177c222b4f626df4b0b66e3f71a | 1666323940000 | 2022-10-21T03:45:40.000Z | BEP20(BSC) | 0xf1458ba28073b056e9666c4b2bbbc60451cda0fd | 0xf1458ba28073b056e9666c4b2bbbc60451cda0fd |             |     |       |         | deposit |  44.71 |    BUSDT |     ok |         | {"cost":0,"currency":"BUSDT"}
6 objects
2022-10-21T17:11:38.044Z iteration 1 passed in 527 ms
```

### CODE REVIEW

**Comment by carlosmiei** [comment]
LGTM ✅ 

```
p bibox fetchDeposits      
Python v3.9.7
CCXT v2.0.71
bibox.fetchDeposits()
[{'address': 'TQEDyGDwDTa2Ac4XxtqQkFAhzWgmJFg1DG',
  'addressFrom': None,
  'addressTo': 'TQEDyGDwDTa2Ac4XxtqQkFAhzWgmJFg1DG',
  'amount': 20.0,
  'currency': 'TUSDT',
  'datetime': '2022-10-13T14:20:09.000Z',
  'fee': {'cost': 0, 'currency': 'TUSDT'},
  'id': '3606266',
  'info': {'amount': '20.00000000',
           'chain_type': 'TRC20',
           'coin_symbol': 'tUSDT',
           'confirmCount': '3',
           'createdAt': '1665670809000',
           'id': '3606266',
           'status': '2',
           'to_address': 'TQEDyGDwDTa2Ac4XxtqQkFAhzWgmJFg1DG',
           'tx_id': '69bdddf4085b4201a59b56c79aaee90e798cc46139820db75ec499cdb6486b12',
           'type': 'deposit'},
  'network': 'TRC20',
  'status': 'ok',
  'tag': None,
  'tagFrom': None,
  'tagTo': None,
  'timestamp': 1665670809000,
  'txid': '69bdddf4085b4201a59b56c79aaee90e798cc46139820db75ec499cdb6486b12',
  'type': 'deposit',
  'updated': None}]
```

**Review by carlosmiei — APPROVED** [review]

**Comment by ndubel** [comment]
@samgermain @carlosmiei why USDT renamed to BUSDT here?

**Comment by samgermain** [comment]
> @samgermain @carlosmiei why USDT renamed to BUSDT here?

BUSDT is the id that bibox uses for USDT, we're converting it to be USDT to be unified

**Comment by ndubel** [comment]
so it should be 
`'BUSDT': 'USDT',`
not
`'USDT': 'BUSDT',`

**Comment by samgermain** [comment]
> so it should be `'BUSDT': 'USDT',` not `'USDT': 'BUSDT',`

Yeah I see that it's not giving the correct currency code right now, unfortunately I'm getting an `internal server error` when I try to test it so I'll need to look at it later

**Comment by ndubel** [comment]
yeah, now USDT just became BUSDT everywhere

**Comment by samgermain** [comment]
> yeah, now USDT just became BUSDT everywhere

sorry about that, I fixed it in #15588

**Pull request merged**
