### PR TITLE
Add fetchTransactions, fetchWithdrawals, fetchDeposits to poloniex

### PR DESCRIPTION
**Pull request by buddylindsey**
I am still learning some of the best practices of code in ccxt. Please let me know what to improve.

A couple of notes. 
1. Poloniex does not have separate endpoints for withdrawals and deposits. So you have to use the single endpoint. To keep things slimmed down I have the seperate `fetchWithdrawals` and `fetchDeposits` calling `fetchTransactions`.
2. `start` and `end` are required so I kind of add and assumption that if you only add a `since` then you want to start at that time and get until `now`. Not sure if we should add assumptions like that. However, it can override by adding`end` to `params`.
3. I am not sure about using `type` in the JS since `type` is a reserved word in python. Should I change it to `_type`?

Please let me know what if anything I did wrong and I'll make changes.

### CODE REVIEW

**Comment by buddylindsey** [comment]
Okay I solved one issue for this not passing. The other one has to do with using `now` since I am doing trying to make an assumption about time to keep the API more consistent. I am not sure the proper way to solve this. Any hints are welcome.

**Comment by kroitor** [comment]
We got some helpers for timestamps available on the exchange instance: https://github.com/ccxt/ccxt/wiki/Manual#working-with-datetimes-and-timestamps )

now = this.seconds () or this.milliseconds () depending on the context, and you can multiply by a thousand and divide by a thousand, like so:

```JavaScript
fetchTransactions (code, since =  undefined, limit = undefined, params = {}) {
    // just for example
    let now = this.milliseconds ();
    let nowInSeconds = parseInt (now / 1000);
    //↑↓
    let nowInSeconds = this.seconds ();
    let nowInMilliseconds = nowInSeconds * 1000;
    ...
}
```

**Comment by kroitor** [comment]
@buddylindsey one caveat there, in the upper layer of CCXT we're using UTC timestamps in milliseconds everywhere, and exchanges may be using seconds or non-UTC timestamps. They may even use different timezones within the same exchange for different endpoints (yes, we've seen a lot)...

**Comment by buddylindsey** [comment]
If that is the case how about I just remove the now usage, and add an check in params for `end` and throw an `ArgumentRequired` if it isn't there? That puts the work on the user to make sure they are getting things correctly. I was trying to do it to be nice, but if it could cause a maintenance issue. I'd rather not see it there.

**Comment by kroitor** [comment]
Both the `start` and the `end` are overrideable by specifying *since* and *params*, but it still tries fetching at least something up to the current date if no timerange is specified. You can play with the offset back in time to see if it allows or rejects *too wide* queries. If it allows to fetch unlimited timespans of history, then we can simply set the start to a date before crypto by default.

```JavaScript
    const year = 31104000; // 60 * 60 * 24 * 30 * 12 = one year of history, why not
    const now = this.seconds ();
    let start = (since !== undefined) ? parseInt (since / 1000) : now - year;
    const request = {
        'start': start, // UNIX timestamp, required
        'end': now, // UNIX timestamp, required
    };
    ...
    let response = await this.privatePostReturnDepositsWithdrawals (this.extend (request, params));
```

**Comment by buddylindsey** [comment]
@kroitor okay pushed a new commit that incorporates your suggestions. Also the `npm run build` finishes locally so we shall see with the automation. Thanks for the feedback. :)

**Comment by buddylindsey** [comment]
Did not realize there was a `this.filterBy` on the base class. Nice.

**Comment by kroitor** [comment]
> Did not realize there was a this.filterBy on the base class. Nice.

Yep, there's also a set of helpers like `groupBy`, `indexBy`, etc... also, filterBySymbolSinceLimit, filterByCurrencySinceLimit, etc...  Those are transpiled as well. We often use those base methods for dirty work. )

**Comment by kroitor** [comment]
@buddylindsey most of helpers are listed here: https://github.com/ccxt/ccxt/blob/master/js/base/functions/generic.js

**Pull request merged**
