### PR TITLE
Leverage tiers types

### PR DESCRIPTION
**Pull request by samgermain**

### CODE REVIEW

**Comment by samgermain** [comment]
Getting these errors, because it looks like the transpiler is adding 2 any imports

```
ccxt\async_support\okx.py:12:20: F811 Redefinition of unused `Any` from line 10
ccxt\okx.py:11:20: F811 Redefinition of unused `Any` from line 9
```

**Comment by carlosmiei** [comment]
> Getting these errors, because it looks like the transpiler is adding 2 any imports
> 
> ```
> ccxt\async_support\okx.py:12:20: F811 Redefinition of unused `Any` from line 10
> ccxt\okx.py:11:20: F811 Redefinition of unused `Any` from line 9
> ```

@samgermain will check it

**Comment by carlosmiei** [comment]
DEMO

```

> ccxt@4.3.30 cli.cs
> dotnet run --project "./cs/cli/cli.csproj" binanceusdm FetchLeverageTiers --sandbox

[]
{
  "tiers": {
    "ICX/USDT:USDT": [
      {
        "tier": 1,
        "currency": "USDT",
        "minNotional": 0.0,
        "maxNotional": 5000.0,
        "maintenanceMarginRate": 0.01,
        "maxLeverage": 50.0,
        "info": {
          "bracket": 1,
          "initialLeverage": 50,
          "notionalCap": 5000,
          "notionalFloor": 0,
          "maintMarginRatio": 0.01,
          "cum": 0.0
        }
      },
      {
        "tier": 2,
        "currency": "USDT",
        "minNotional": 5000.0,
        "maxNotional": 25000.0,
        "maintenanceMarginRate": 0.025,
        "maxLeverage": 20.0,
        "info": {
          "bracket": 2,
          "initialLeverage": 20,
          "notionalCap": 25000,
          "notionalFloor": 5000,
          "maintMarginRatio": 0.025,
          "cum": 75.0
        }
      },
```

**Comment by carlosmiei** [comment]
```
Python v3.11.7
CCXT v4.3.30
binanceusdm.fetchLeverageTiers()
{'1000BONK/USDC:USDC': [{'currency': 'USDC',
                         'info': {'bracket': '1',
                                  'cum': '0.0',
                                  'initialLeverage': '50',
                                  'maintMarginRatio': '0.01',
                                  'notionalCap': '5000',
                                  'notionalFloor': '0'},
                         'maintenanceMarginRate': 0.01,
                         'maxLeverage': 50.0,
                         'maxNotional': 5000.0,
                         'minNotional': 0.0,
                         'tier': 1.0},
                        {'currency': 'USDC',
                         'info': {'bracket': '2',
                                  'cum': '50.0',
                                  'initialLeverage': '25',
                                  'maintMarginRatio': '0.02',
                                  'notionalCap': '50000',
                                  'notionalFloor': '5000'},
                         'maintenanceMarginRate': 0.02,
                         'maxLeverage': 25.0,
                         'maxNotional': 50000.0,
                         'minNotional': 5000.0,
```

**Pull request merged**
