### PR TITLE
gate - fetchTickers

### PR DESCRIPTION
**Pull request by AlgoQ**

### CODE REVIEW

**Comment by carlosmiei** [comment]
LGTM ✅ 

```
 p gate fetchTickers '["BTC/USDT"]'                  
Python v3.9.7
CCXT v2.2.12
gate.fetchTickers(['BTC/USDT'])
{'BTC/USDT': {'ask': 16447.2,
              'askVolume': None,
              'average': None,
              'baseVolume': 10395.256543154,
              'bid': 16444.6,
              'bidVolume': None,
              'change': None,
              'close': 16444.7,
              'datetime': None,
              'high': 16670.2,
              'info': {'base_volume': '10395.256543154',
                       'change_percentage': '2.22',
                       'change_utc0': '1.34',
                       'change_utc8': '1.23',
                       'currency_pair': 'BTC_USDT',
                       'high_24h': '16670.2',
                       'highest_bid': '16444.6',
                       'last': '16444.7',
                       'low_24h': '16048',
                       'lowest_ask': '16447.2',
                       'quote_volume': '170730199.23621'},
              'last': 16444.7,
              'low': 16048.0,
              'open': None,
              'percentage': 2.22,
              'previousClose': None,
              'quoteVolume': 170730199.23621,
              'symbol': 'BTC/USDT',
              'timestamp': None,
              'vwap': 16423.85625861708}}
```
```
 p gate fetchTickers '["BTC/USDT:USDT"]' --swap
Python v3.9.7
CCXT v2.2.12
gate.fetchTickers(['BTC/USDT:USDT'])
{'BTC/USDT:USDT': {'ask': None,
                   'askVolume': None,
                   'average': None,
                   'baseVolume': 11251.0,
                   'bid': None,
                   'bidVolume': None,
                   'change': None,
                   'close': 16444.2,
                   'datetime': None,
                   'high': 16650.0,
                   'info': {'change_percentage': '2.21',
                            'contract': 'BTC_USDT',
                            'funding_rate': '0.000018',
                            'funding_rate_indicative': '0.000018',
                            'high_24h': '16650',
                            'index_price': '16451.39',
                            'last': '16444.2',
                            'low_24h': '16030.1',
                            'mark_price': '16451.44',
                            'total_size': '119932148',
                            'volume_24h': '112510486',
                            'volume_24h_base': '11251',
                            'volume_24h_quote': '185014493',
                            'volume_24h_settle': '185014493'},
                   'last': 16444.2,
                   'low': 16030.1,
                   'open': None,
                   'percentage': 2.21,
                   'previousClose': None,
                   'quoteVolume': 185014493.0,
                   'symbol': 'BTC/USDT:USDT',
                   'timestamp': None,
                   'vwap': 16444.2709981335}}
```

**Review by carlosmiei — APPROVED** [review]

**Comment by mdh12342** [comment]
AlgoQ:gate-fetchTickers

**Comment by mdh12342** [comment]
AlgoQ:gate-fetchTickers

**Comment by mdh12342** [comment]
#15806

**Comment by mdh12342** [comment]
@kroitor

**Comment by carlosmiei** [comment]
@mdh12342 what happened?

**Pull request merged**
