### PR TITLE
ohlcv: replaces outdated #695

### PR DESCRIPTION
**Pull request by mkutny**

### CODE REVIEW

**Comment by vaunus** [comment]
Hello. Any updates on getting this merged please?

**Comment by kroitor** [comment]
@vaunus working on it, hope to merge soon.

**Comment by mkutny** [comment]
Oh, guys, if I'm not too late.

From time to time I stumble on markets which show relatively big volumes but when I dig further I find that it comes from the relatively small amount of scarce trades.

So I added a method that reports a number of trades but to be backward-compatible retained good old `fetchOHLCV`.

I hope it won't hurt anybody!

**Comment by kroitor** [comment]
@mkutny, just in time 👍  ))

**Comment by vaunus** [comment]
Sorry to chase again. Any plans on resolving the conflicts with this and merging soon?

**Comment by mkutny** [comment]
I planned to resolve it after #1635 is merged, otherwise, #1635 would conflict with this one if this one is merged earlier.

**Comment by kroitor** [comment]
no worries about the conflicts, I can merge it, not @mkutny's fault, this request was submitted earlier than the breaking changes, let me know if you want me to do that, thx!

**Pull request merged**
