### PR TITLE
phemex: added v2 endpoints

### PR DESCRIPTION
**Pull request by cheunhong**
There are some v2 endpoints listed in [here](https://github.com/phemex/phemex-api-docs/blob/master/Public-Hedged-Perpetual-API.md) that hasn't been added.

### CODE REVIEW

**Comment by carlosmiei** [comment]
@cheunhong 
Can you fix the build? 
image

**Comment by cheunhong** [comment]
@carlosmiei my bad, has fixed it

**Comment by carlosmiei** [comment]
> @carlosmiei my bad, has fixed it

@cheunhong thanks, can you please point me to the v2 docs? Can't find them

**Comment by cheunhong** [comment]
> @cheunhong thanks, can you please point me to the v2 docs? Can't find them
@carlosmiei  v2 docs is not specifically listed in any place, but the they are listed here.
https://github.com/phemex/phemex-api-docs/blob/master/Public-Hedged-Perpetual-API.md

**Comment by carlosmiei** [comment]
> > @cheunhong thanks, can you please point me to the v2 docs? Can't find them
> > @carlosmiei  v2 docs is not specifically listed in any place, but the endpoints are listed here.
> > https://github.com/phemex/phemex-api-docs/blob/master/Public-Hedged-Perpetual-API.md

@cheunhong thank you

**Comment by carlosmiei** [comment]
LGTM ✅ 

```
n phemex v2GetMdV2Trade '{"symbol":"BTCUSDT"}'          
Debugger attached.
2022-12-27T11:48:23.683Z
Node.js: v17.9.0
CCXT v2.4.55
phemex.v2GetMdV2Trade ([object Object])
2022-12-27T11:48:24.546Z iteration 0 passed in 468 ms

{
  error: null,
  id: '0',
  result: {
    sequence: '402345955',
    symbol: 'BTCUSDT',
    trades_p: [
      [ 1672141693657463000, 'Buy', '16820.9', '0.019' ],
      [ 1672141693009021200, 'Sell', '16820.8', '0.79' ],
      [ 1672141679718618000, 'Sell', '16820.8', '0.37' ],
      [ 1672141679718618000, 'Sell', '16820.8', '0.305' ],
      [ 1672141674248036400, 'Buy', '16819.4', '0.059' ],
      [ 1672141671121537300, 'Buy', '16819.2', '0.046' ],
      [ 1672141668886425900, 'Buy', '16819.2', '0.05' ],
      [ 1672141663882946300, 'Sell', '16819.1', '0.775' ],
      [ 1672141655666829600, 'Sell', '16816.4', '1' ],
      [ 1672141649794647000, 'Buy', '16816.5', '0.004' ],
      [ 1672141644108005600, 'Sell', '16816.4', '0.375' ],
      [ 1672141634432706600, 'Sell', '16816.4', '0.34' ],
      [ 1672141622860579600, 'Sell', '16816.4', '0.219' ],
      [ 1672141622860579600, 'Sell', '16816.4', '0.013' ],
      [ 1672141622860579600, 'Sell', '16816.4', '0.264' ],
      [ 1672141622860579600, 'Sell', '16816.4', '0.494' ],
      [ 1672141616195028700, 'Sell', '16816.4', '0.5' ],
      [ 1672141604552413200, 'Sell', '16816.4', '1.005' ],
      [ 1672141595692773600, 'Sell', '16816.4', '0.48' ],
      [ 1672141587337923000, 'Sell', '16816.4', '0.705' ],
      [ 1672141581225759500, 'Sell', '16816.4', '1.05' ],
      [ 1672141568006765300, 'Buy', '16816.5', '0.183' ],
      [ 1672141560050023200, 'Buy', '16816.5', '0.2' ],
      [ 1672141554599799300, 'Buy', '16816.6', '1.85' ],
      [ 1672141546153974500, 'Buy', '16816.6', '0.7' ],
      [ 1672141534575030800, 'Buy', '16816.6', '1.358' ],
      [ 1672141534575030800, 'Buy', '16816.6', '0.242' ],
      [ 1672141525068066600, 'Sell', '16816.5', '2.3' ],
      [ 1672141512036776200, 'Sell', '16819.7', '1.5' ],
      [ 1672141503556777700, 'Buy', '16819.8', '0.361' ],
      [ 1672141490179372000, 'Buy', '16819.9', '1.575' ],
      [ 1672141481200328700, 'Sell', '16820.8', '0.011' ],
      [ 1672141481200328700, 'Sell', '16820.8', '0.289' ],
      [ 1672141467758767400, 'Sell', '16820.6', '0.339' ],
      [ 1672141457365472800, 'Sell', '16820.6', '0.178' ],
      [ 1672141451070966300, 'Sell', '16820.6', '0.9' ],
      [ 1672141436433616000, 'Sell', '16820.6', '0.38' ],
      [ 1672141429068601600, 'Sell', '16820.6', '0.25' ],
      [ 1672141423252008700, 'Sell', '16820.8', '0.292' ],
      [ 1672141409443865600, 'Sell', '16820.7', '0.573' ],
      [ 1672141401085980000, 'Sell', '16820.7', '0.322' ],
      [ 1672141390760869000, 'Sell', '16820.7', '0.31' ],
      [ 1672141381854198300, 'Sell', '16820.7', '0.3' ],
      [ 1672141372401249000, 'Sell', '16820.7', '0.4' ],
      [ 1672141365902142500, 'Sell', '16820.7', '0.6' ],
      [ 1672141356777887500, 'Sell', '16820.7', '1.892' ],
      [ 1672141356777887500, 'Sell', '16820.7', '0.608' ],
      [ 1672141351648220400, 'Sell', '16820.8', '0.067' ],
      [ 1672141343576683000, 'Sell', '16820.8', '0.155' ],
      [ 1672141330143805200, 'Sell', '16820.8', '0.1' ],
      [ 1672141322585184500, 'Sell', '16820.7', '0.15' ],
      [ 1672141316489751300, 'Sell', '16820.7', '0.116' ],
      [ 1672141308126711000, 'Sell', '16820.7', '0.205' ],
      [ 1672141302365537800, 'Sell', '16820.7', '0.49' ],
      [ 1672141287579830300, 'Sell', '16820.7', '0.28' ],
      [ 1672141280353976800, 'Sell', '16820.7', '0.096' ],
      [ 1672141280353976800, 'Sell', '16820.7', '2.224' ],
      [ 1672141269284315600, 'Sell', '16820.8', '0.368' ],
      [ 1672141262185351700, 'Sell', '16820.8', '0.299' ],
      [ 1672141255180638000, 'Sell', '16820.8', '0.443' ],
      [ 1672141243168535600, 'Sell', '16820.8', '0.421' ],
      [ 1672141237211695000, 'Sell', '16820.8', '0.387' ],
      [ 1672141229269949000, 'Sell', '16820.7', '0.37' ],
      [ 1672141217425789400, 'Sell', '16820.7', '0.76' ],
      [ 1672141209463628500, 'Sell', '16820.8', '0.429' ],
      [ 1672141194557280800, 'Sell', '16820.7', '0.09' ],
      [ 1672141194557280800, 'Sell', '16820.7', '1.34' ],
      [ 1672141187514418000, 'Sell', '16820.8', '0.131' ],
      [ 1672141181400185000, 'Sell', '16820.8', '0.17' ],
      [ 1672141176392408800, 'Sell', '16820.7', '0.28' ],
      [ 1672141166304879400, 'Sell', '16820.7', '0.078' ],
      [ 1672141158332816400, 'Sell', '16820.8', '0.124' ],
      [ 1672141143605829000, 'Sell', '16820.8', '0.18' ],
      [ 1672141135604646700, 'Sell', '16820.7', '0.17' ],
      [ 1672141127658449400, 'Sell', '16820.7', '0.17' ],
      [ 1672141121623938600, 'Sell', '16820.7', '0.19' ],
      [ 1672141111373791000, 'Sell', '16820.7', '0.815' ],
      [ 1672141097731304200, 'Sell', '16820.7', '0.45' ],
      [ 1672141091388522000, 'Sell', '16820.7', '0.535' ],
      [ 1672141080495143700, 'Sell', '16820.7', '0.62' ],
      [ 1672141080495143700, 'Sell', '16820.7', '0.13' ],
      [ 1672141068000452000, 'Sell', '16820.7', '0.4' ],
      [ 1672141061051216600, 'Sell', '16820.7', '0.79' ],
      [ 1672141054290307600, 'Sell', '16820.7', '0.8' ],
      [ 1672141041149273300, 'Sell', '16820.7', '0.525' ],
      [ 1672141030109487400, 'Sell', '16820.7', '0.29' ],
      [ 1672141018344362200, 'Sell', '16820.7', '1.3' ],
      [ 1672141011719657200, 'Sell', '16820.7', '1.515' ],
      [ 1672141011719657200, 'Sell', '16820.7', '0.285' ],
      [ 1672140997893098800, 'Sell', '16819.6', '0.227' ],
      [ 1672140985158990600, 'Sell', '16819.6', '0.166' ],
      [ 1672140977851884800, 'Buy', '16819.7', '0.67' ],
      [ 1672140968112365800, 'Buy', '16819.7', '0.336' ],
      [ 1672140968112365800, 'Buy', '16819.7', '0.069' ],
      [ 1672140956493911600, 'Buy', '16819.7', '0.28' ],
      [ 1672140949429597000, 'Sell', '16819.5', '0.35' ],
      [ 1672140937587851000, 'Sell', '16819.5', '0.395' ],
      [ 1672140930592091400, 'Sell', '16818.1', '0.526' ],
      [ 1672140930592091400, 'Sell', '16818.1', '0.424' ],
      [ 1672140923309031200, 'Sell', '16815.9', '0.783' ]
    ],
    type: 'snapshot'
  }
}
2022-12-27T11:48:24.546Z iteration 1 passed in 468 ms

```

**Review by carlosmiei — APPROVED** [review]

**Pull request merged**
