### PR TITLE
Nova add fees

### PR DESCRIPTION
**Pull request by cod3gen**
Add fees array and include it in fetchMarkets. Would also like to add limits but i am quite unsure about how to handle them since orders minimum amount need to have a fee of 0.00000020 BTC

### CODE REVIEW

**Comment by kroitor** [comment]
> Would also like to add limits but i am quite unsure about how to handle them since orders minimum amount need to have a fee of 0.00000020 BTC

Not sure how fees are related to order minimums in this case, can you elaborate plz? )

**Comment by cod3gen** [comment]
> > Would also like to add limits but i am quite unsure about how to handle them since orders minimum amount need to have a fee of 0.00000020 BTC
> 
> Not sure how fees are related to order minimums in this case, can you elaborate plz? )

I'm not good at explaining but here it goes :-D... 

Using ArtByte (ABY) as an example, i would like to sell 1000 ABY for the price of 0.00000001 BTC each which would give me 0.00001 BTC minus fees. Fees would be 0.00000002 BTC (0.2%), however to proceed with the order, Nova requires that the fee to be paid is minimum 0.0000002 which is 10 times more... IE minimum order amount for ABY->BTC market would be 10000 ABY

**Comment by kroitor** [comment]
> IE minimum order amount for ABY->BTC market would be 10000 ABY

That's an indirect conclusion, I mean, the min fee does not really define the min order limit, those are two unrelated limits, really, because the fee depends not just on the base amount, but also on on the quoted price that can fluctuate +/- 100% or more. It depends on how Nova defines those limits, though, because I don't see any indications on the minimums in their docs or in API responses... Can you shed more light on that?

**Comment by cod3gen** [comment]
I cannot find any information about this in their docs either(theyre docs is limited.. Theyre api also :-P).. However i got that message when i tried to sell 3k ABY.. "Fee must add up to 0.00000020 BTC."

Giving a second try on buying 10 LinX i get the same message, so it is same for both buying and selling, min fee to pay must be 0.00000020 BTC.

http://prntscr.com/ol2e4p

**Comment by kroitor** [comment]
@cod3gen ok, from what you write i'd carry that we should not try to guess or hardcode order limits from fee limits. Do you agree? )

**Comment by cod3gen** [comment]
> @cod3gen ok, thx! ) From what you write i'd carry that we should not try to guess or hardcode order limits from fee limits (should just throw an exception in this case). Do you agree? )

Yes i agree, minimum order limits cannot be hardcoded. It moves with the market, only place we would actually be able to know this limit would be in ticker where we know price

**Pull request merged**
