### PR TITLE
add bytetrade.com DEX public and private API support

### PR DESCRIPTION
**Pull request by leolianger**
add bytetrade.com DEX public and private API support

### CODE REVIEW

**Comment by leolianger** [comment]
the ByteTrade DEX's funciton need ecdsa library, could you please install it in the check environment by 'pip install ecdsa' command? thanks a lot

**Comment by kroitor** [comment]
@leolianger unfortunately, we can't merge it this way, because it's too dirty and fails with tests. It also adds exchange-specific code to the basecode which is against the design of the lib. We are going to merge `ecdsa` functionality soon: https://github.com/ccxt/ccxt/pull/5650

After that we will need this PR to be reworked precisely according to these guidelines:

- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#derived-exchange-classes

**Comment by leolianger** [comment]
@kroitor thanks for your review, and i will rewrite the code using the ecdsa functionality which you merge in [ #5650](https://github.com/ccxt/ccxt/pull/5650), and make it to be reworked precisely according to these guidelines.
Considering the complexity of the signature and serialization of DEX, we add exchange-specific code to the basecode, and we need your help to review and maybe refactor it.  
We had send email to Peter Opdahl, and look forward to your reply.

**Comment by leolianger** [comment]
a new PR #5681[https://github.com/ccxt/ccxt/pull/5681](url) is posted, please reveiw again, thank you

**Comment by leolianger** [comment]
a new PR  [#5681](https://github.com/ccxt/ccxt/pull/5681) is posted, please reveiw again, thank you

**Pull request closed without merging**
