### PR TITLE
Add new exchange Bitrue

### PR DESCRIPTION
**Pull request by firepol**
Hi, I've seen this PR: https://github.com/ccxt/ccxt/pull/7148

As it seems dead (since June no updates) I tried to give my contributions.
Dust didn't seem to get the idea how it works...

@binares did a good job. I fixed a few syntax errors I saw when running `yarn build`.

Something I don't understand, is why many methods got wiped when running `yarn transpile` and also the generated code looked very differently in python, e.g. some variables like `takerOrMaker` did not get transpiled in the pythonic way `taker_or_maker`. So either there is an issue with the transpiler, or this branch got something broken, no idea.

I think the python file was edited manually...

I really have no time to work on this further, but I fixed:
`parse_trade` (before `cost` was missing).

This sure needs more work and testing, but I was thinking it was worth to push my PR.
This works for me in my accounting software where I need basically these 2 things: 1) fetch trades history and 2) fetch balances.
Cheers

### CODE REVIEW

**Comment by binares** [comment]
@firepol The python and php files don't need to be included in the PR, only the js file. The private methods got wiped because it transpiles `bitrue.js -> (bitrue.py, bitrue.php)`, and I did not have time to manually backwards-transpile _all of_ bitrue.py to bitrue.js.

**Comment by kroitor** [comment]
@firepol if you could restore the generated files and keep just the `bitrue.js` file in this PR – that would be fantastic )
What @binares said is 100% correct, more about it here:

- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#multilanguage-support

**Comment by firepol** [comment]
> I did not have time to manually backwards-transpile all of bitrue.py to bitrue.js.
@binares "manually backwards-transpile" you mean you wrote first in python and then manually wrote the js or is there a way to transpile from python to js? I'm about to write the fetchBalance method in js manually, but if there is a way to automate it, that would be nice...

**Comment by binares** [comment]
> "manually backwards-transpile" you mean you wrote first in python and then manually wrote the js or is there a way to transpile from python to js?
@firepol The python files were written by the author of the previous PR. Currently there is indeed no way to automatically transpile from python or php to js.

**Review by jonhpham — APPROVED** [review]

**Comment by pangkungzaa** [comment]
Good

**Comment by firepol** [comment]
@kroitor finally I took some time to add the missing methods. I tested the methods I added. I'm not 100% sure if the method `loadTimeDiff` and `loadTimeDifference` are really needed. I basically took the work from @binares and the work from dust and merged them. It works for me. Can't guarantee it's bug free, but it's usable. More testing is welcome.

Kroitor: some variables don't get transpiled correctly in python, I wonder why, e.g. `baseVolume` should become `base_volume`... or only method names get transpiled?

I hope to see this merged in ccxt soon. Its half a year I'm waiting for bitrue to be integrated in ccxt.
Cheers

**Comment by kroitor** [comment]
@firepol thx for all your efforts!

> Kroitor: some variables don't get transpiled correctly in python, I wonder why, e.g. baseVolume should become base_volume... or only method names get transpiled?

Only method names get transpiled.

**Comment by firepol** [comment]
Dear @kroitor I tested this and I'm using it regularly. Is there something not ok with this pull request? Need something else from my side to speed up its merge? Thx for letting me know & cheers

**Comment by HartS** [comment]
Also waiting for this. @firepol not sure if you noticed that it's failing the build due to eslint issues that look super quick/easy to address. Perhaps that's the reason it hasn't been merged yet?

```
/home/travis/build/ccxt/ccxt
v6.8.0
/home/travis/build/ccxt/ccxt/js/bitrue.js
  426:15  error  'states' is assigned a value but never used         no-unused-vars
  428:13  error  'request' is never reassigned. Use 'const' instead  prefer-const
```

**Comment by kroitor** [comment]
@HartS thx for your review! Indeed, there are some issues in the code that prevents it from merging. I'll do my best to clean it up in the coming days.

**Comment by HartS** [comment]
I created a new PR building on top of this work, which fixes some issues: #9837

**Pull request merged**
