### PR TITLE
add dragonex

### PR DESCRIPTION
**Pull request by caoshitong369**
add dragonex

### CODE REVIEW

**Comment by caoshitong369** [comment]
I want to add dragonex Api(python), Add js in a few days.

**Comment by kroitor** [comment]
@caoshitong369 

> I want to add dragonex Api(python), Add js in a few days.

Plz read this first:

- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#multilanguage-support
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#transpiled-files
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#derived-exchange-classes

**Comment by caoshitong369** [comment]
@kroitor 
I only need to write js, then I can compile it into python and php？

**Comment by kroitor** [comment]
@caoshitong369 yep, and it will be transpiled automatically, the only thing that is very important – is to follow all the following JS guidelines literally (to a word): https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#derived-exchange-classes

**Comment by caoshitong369** [comment]
> @caoshitong369 yep, and it will be transpiled automatically, the only thing that is very important – is to follow all the following JS guidelines literally (to a word): https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#derived-exchange-classes

ok,thanks

**Comment by frosty00** [comment]
you might want to base it on this - https://github.com/ccxt/ccxt/pull/3817

**Comment by caoshitong369** [comment]
@frosty00 thanks,
I feel that your sign has some problems, you need to call the interface to create a new token.

**Comment by kroitor** [comment]
@caoshitong369 

> you need to call the interface to create a new token.

In that case we need to implement a unified `signIn` method. Check out how this is handled in other integrated exchanges:

- https://github.com/ccxt/ccxt/blob/master/js/mandala.js#L238
- https://github.com/ccxt/ccxt/blob/master/js/mandala.js#L1812

--------

- https://github.com/ccxt/ccxt/blob/master/js/bitmart.js#L163
- https://github.com/ccxt/ccxt/blob/master/js/bitmart.js#L846

-----------

- https://github.com/ccxt/ccxt/blob/master/js/dx.js#L433
- https://github.com/ccxt/ccxt/blob/master/js/dx.js#L521

**Comment by caoshitong369** [comment]
@kroitor ERROR: InvocationError for command /home/travis/build/ccxt/ccxt/python/.tox/qa/bin/flake8 --exclude static_dependencies,.tox

**Comment by kroitor** [comment]
@caoshitong369 https://travis-ci.org/ccxt/ccxt/builds/614411313#L1603

**Comment by caoshitong369** [comment]
@kroitor 
When I was in the local npm run build.
Fatal error: Uncaught ErrorException: Invalid argument supplied for foreach() in /Users/a1/ccxt/ccxt/php/base/Exchange.php on line 1044 in /Users/a1/ccxt/ccxt/php/test/syntax.php:12
Stack trace:
#0 /Users/a1/ccxt/ccxt/php/base/Exchange.php(1044): on_error(2, 'Invalid argumen...', '/Users/a1/ccxt/...', 1044, Array)
#1 /Users/a1/ccxt/ccxt/php/base/Exchange.php(1019): ccxt\Exchange->define_rest_api(Array, 'request')
#2 /Users/a1/ccxt/ccxt/php/test/syntax.php(21): ccxt\Exchange->__construct(Array)
#3 {main}
  thrown in /Users/a1/ccxt/ccxt/php/test/syntax.php on line 12

**Comment by caoshitong369** [comment]
@kroitor 
When I was in the local npm run build.
Fatal error: Uncaught ErrorException: Invalid argument supplied for foreach() in /Users/a1/ccxt/ccxt/php/base/Exchange.php on line 1044 in /Users/a1/ccxt/ccxt/php/test/syntax.php:12
Stack trace:
#0 /Users/a1/ccxt/ccxt/php/base/Exchange.php(1044): on_error(2, 'Invalid argumen...', '/Users/a1/ccxt/...', 1044, Array)
#1 /Users/a1/ccxt/ccxt/php/base/Exchange.php(1019): ccxt\Exchange->define_rest_api(Array, 'request')
#2 /Users/a1/ccxt/ccxt/php/test/syntax.php(21): ccxt\Exchange->__construct(Array)
#3 {main}
  thrown in /Users/a1/ccxt/ccxt/php/test/syntax.php on line 12

**Comment by kroitor** [comment]
@caoshitong369 change the logo to a URL, it contains character sequences that won't pass the transpiler.

**Comment by caoshitong369** [comment]
@kroitor 
https://user-images.githubusercontent.com/
How to change the logo domain name to this

**Comment by kroitor** [comment]
@caoshitong369 drag&drop it in the text area where you type your comments, then wait a few seconds, GitHub will generate the url )

**Comment by caoshitong369** [comment]
@kroitor FAILED dragonex (Python): (explain @ run-tests.js:187)
	dragonex using proxy `` (explain @ run-tests.js:190)
FAIL ["dragonex"] (run-tests.js:268)

**Comment by kroitor** [comment]
@caoshitong369 

```
npm run build
python python/test/test.py dragonex --verbose
```

**Comment by caoshitong369** [comment]
@kroitor thanks bro i passed

**Comment by kroitor** [comment]
@caoshitong369 it would really help a lot if you could delete all the generated files from this PR, leaving just the `dragonex.js` file and the `gmt` function, can you do that?

**Comment by caoshitong369** [comment]
@kroitor ok

**Comment by caoshitong369** [comment]
@kroitor hi bro i solved it.

**Comment by caoshitong369** [comment]
@kroitor bro 
how long will it take me to pip install ccxt and
print(ccxt.exchanges) will appear dragonex

**Comment by frosty00** [comment]
@caoshitong369, as soon as igor reviews it and merges it )

https://github.com/ccxt/ccxt/wiki/FAQ#what-is-the-status-of-this-pr-any-update

**Comment by caoshitong369** [comment]
@frosty00 thanks bro

**Comment by caoshitong369** [comment]
@kroitor hi bro 
Does my code pass?

**Comment by kroitor** [comment]
@caoshitong369 i don't know yet, didn't have the time to test it so far. It would be great if you could remove the edits to auto-generated files from this PR, leaving just the actual related edits:

```
# Files to remove
ccxt.d.ts
ccxt.js 
dist/ccxt.browser.js 
doc/README.rst 
doc/exchanges.rst 
doc/manual.rst 
package.json 
python/README.rst 
python/ccxt/__init__.py 
python/ccxt/async_support/__init__.py 
wiki/Exchange-Markets-By-Country.md 
wiki/Exchange-Markets.md 
```

↑ All of the above will ve overwritten upon building anyway. So if you could remove them from this PR – that would help keep it clean.

We need just the following files:

```
# Files to keep
js/base/functions/time.js 
js/dragonex.js 
php/base/Exchange.php 
```

↑ Looks like python implementation of `gmt` is missing here.

**Comment by kroitor** [comment]
@caoshitong369 plz don't delete the files themselves, delete your edits to those files by just checking them out from master branch )

```
git checkout origin/master dist/ccxt.browser.js
```

**Comment by caoshitong369** [comment]
@kroitor 
I re-clone and resubmit, many files have been deleted.

**Comment by caoshitong369** [comment]
@kroitor soory
I have deleted my modification before, I thought I did not delete it, and then deleted the file.

**Comment by kroitor** [comment]
@caoshitong369 if it's easier for, then you can simply close this PR and resumbit a new clean one, with just the files we need – that would be awesome )

**Comment by caoshitong369** [comment]
@kroitor ok

**Pull request closed without merging**
