### PR TITLE
fix(base): remove starknet js json

### PR DESCRIPTION
**Pull request by sc0Vu**
I think we can remove json dependency from starknet js. It seems also break esm in react.

### CODE REVIEW

**Comment by carlosmiei** [comment]
@sc0Vu did you check if paradex is still working?

**Comment by carlosmiei** [comment]
DEMO

```
 ccxt git:(remove-starknet-js-json) ✗ n paradex createOrder "SOL/USD:USDC" market buy 1  --sandbox         
2024-08-13T14:19:32.917Z
Node.js: v18.18.0
CCXT v4.3.80
paradex.createOrder (SOL/USD:USDC, market, buy, 1)
2024-08-13T14:19:35.382Z iteration 0 passed in 1293 ms

{
  id: '1723558775240201703953770000',
  timestamp: 1723558775245,
  datetime: '2024-08-13T14:19:35.245Z',
  lastUpdateTimestamp: 1723558775245,
  status: 'open',
  symbol: 'SOL/USD:USDC',
  type: 'market',
  side: 'buy',
  stopPrice: 0,
  triggerPrice: 0,
  amount: 1,
  filled: 0,
  remaining: 1,
  trades: [],
  fee: {},
  info: {
    id: '1723558775240201703953770000',
    account: '0x3ea26cacadcbacd3941dba68986f1102181d834a76ad8ad7d6b17678c815b79',
    market: 'SOL-USD-PERP',
    side: 'BUY',
    type: 'MARKET',
    size: '1',
    remaining_size: '1',
    price: '0',
    status: 'NEW',
    created_at: '1723558775245',
    last_updated_at: '1723558775245',
    timestamp: '1723558774000',
    cancel_reason: '',
    client_id: '',
    seq_no: '1723558775245642237',
    instruction: '',
    avg_fill_price: '',
    stp: 'EXPIRE_TAKER',
    received_at: '1723558775239',
    published_at: '1723558775247',
    flags: [],
    trigger_price: '0'
  },
  fees: [ {} ]
}
2024-08-13T14:19:35.382Z iteration 1 passed in 1293 ms
```

**Comment by sc0Vu** [comment]
@carlosmiei Yes, I try private reuqests. And it worked.

**Comment by carlosmiei** [comment]
@sc0Vu tested as well just to make sure 😅

**Pull request merged**
