### PR TITLE
Update okex3.py

### PR DESCRIPTION
**Pull request by livehl**
修复bug

### CODE REVIEW

**Comment by kroitor** [comment]
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#multilanguage-support

**Comment by kroitor** [comment]
@livehl unfortunately, we can't merge it this way, since we should not edit py files, we should rather edit the JS source, as described in the CONTRIBUTING doc.

Can you please post your verbose request and response for the parsing error in question?

```Python
exchange.load_markets()
exchange.verbose = True
exchange.YOUR_CALL ( ... )  # paste verbose request/response for it
```

**Comment by kroitor** [comment]
https://github.com/ccxt/ccxt/blob/ea278adec64dbce58b70a2c4ad78556710277737/python/ccxt/okex3.py#L3

**Comment by aazhou** [comment]
exchange-connect_exchange-connect_1 | 2019-08-29T10:11:13.514047322Z   File "/usr/local/lib/python3.6/dist-packages/ccxt/okex3.py", line 2025, in fetch_withdrawals
exchange-connect_exchange-connect_1 | 2019-08-29T10:11:13.514840081Z     return self.parseTransactions(response, currency, since, limit, params)
exchange-connect_exchange-connect_1 | 2019-08-29T10:11:13.514850545Z   File "/usr/local/lib/python3.6/dist-packages/ccxt/base/exchange.py", line 1561, in parse_transactions
exchange-connect_exchange-connect_1 | 2019-08-29T10:11:13.515268149Z     array = [self.extend(self.parse_transaction(transaction, currency), params) for transaction in array]
exchange-connect_exchange-connect_1 | 2019-08-29T10:11:13.515274924Z   File "/usr/local/lib/python3.6/dist-packages/ccxt/base/exchange.py", line 1561, in <listcomp>
exchange-connect_exchange-connect_1 | 2019-08-29T10:11:13.515653180Z     array = [self.extend(self.parse_transaction(transaction, currency), params) for transaction in array]
exchange-connect_exchange-connect_1 | 2019-08-29T10:11:13.515660009Z   File "/usr/local/lib/python3.6/dist-packages/ccxt/okex3.py", line 2127, in parse_transaction
exchange-connect_exchange-connect_1 | 2019-08-29T10:11:13.516232849Z     feeCost = float(feeWithoutCurrencyId)
exchange-connect_exchange-connect_1 | 2019-08-29T10:11:13.516239945Z ValueError: could not convert string to float: '0.00000000okdk'

this error is becuase of that CurrencyId is upper 'OKDK', it not replace by 'okdk' to empty.

**Comment by aazhou** [comment]
TIM截图20190829181945

**Pull request closed without merging**
