### PR TITLE
feat(coinbase): public endpoints added for fetchTicker, fetchMarkets,  fetchOHLCV, and fetchOrderBook

### PR DESCRIPTION
**Pull request by samgermain**
- adds public endpoints
- updates fetchTicker, fetchMarkets,  fetchOHLCV, and fetchOrderBook to use public endpoints
- adds response comments to fetchMarkets

# Testing

```
Python v3.9.6
CCXT v4.3.2
coinbase.fetchOrderBook(BTC/USDT)
{'asks': [[66915.02, 0.03119498],
          ...
          [73422.53, 0.00023485]],
 'bids': [[66896.06, 0.03650588],
          ...
          [58666.06, 0.00187671]],
 'datetime': '2024-04-23T01:23:51.787Z',
 'nonce': None,
 'symbol': 'BTC/USDT',
 'timestamp': 1713835431787}
```

```
Python v3.9.6
CCXT v4.3.2
coinbase.fetchMarkets()
[{'active': True,
  'base': 'BTC',
  'baseId': 'BTC',
  'contract': False,
  'contractSize': None,
  'created': None,
  'expiry': None,
  'expiryDatetime': None,
  'future': False,
  'id': 'BTC-USD',
  'index': False,
  'info': {'alias': '',
           'alias_to': ['BTC-USDC'],
           'auction_mode': False,
           'base_currency_id': 'BTC',
           'base_display_symbol': 'BTC',
           'base_increment': '0.00000001',
           'base_max_size': '3400',
           'base_min_size': '0.00000001',
           'base_name': 'Bitcoin',
           'cancel_only': False,
           'display_name': 'BTC-USD',
           'fcm_trading_session_details': None,
           'is_disabled': False,
           'limit_only': False,
           'mid_market_price': '',
           'new': False,
           'post_only': False,
           'price': '66988.69',
           'price_increment': '0.01',
           'price_percentage_change_24h': '2.2579154120148',
           'product_id': 'BTC-USD',
           'product_type': 'SPOT',
           'product_venue': 'CBE',
           'quote_currency_id': 'USD',
           'quote_display_symbol': 'USD',
           'quote_increment': '0.01',
           'quote_max_size': '150000000',
           'quote_min_size': '1',
           'quote_name': 'US Dollar',
           'status': 'online',
           'trading_disabled': False,
           'view_only': False,
           'volume_24h': '10797.61741257',
           'volume_percentage_change_24h': '127.67890464614174',
           'watched': False},
  'inverse': None,
  'limits': {'amount': {'max': 3400.0, 'min': 1e-08},
             'cost': {'max': 150000000.0, 'min': 1.0},
             'leverage': {'max': None, 'min': None},
             'price': {'max': None, 'min': None}},
  'linear': None,
  'lowercaseId': None,
  'maker': 0.006,
  'margin': None,
  'option': False,
  'optionType': None,
  'precision': {'amount': 1e-08, 'price': 0.01},
  'quote': 'USD',
  'quoteId': 'USD',
  'settle': None,
  'settleId': None,
  'spot': True,
  'strike': None,
  'subType': None,
  'swap': False,
  'symbol': 'BTC/USD',
  'taker': 0.008,
  'type': 'spot'},
 ...
 {'active': True,
  'base': 'ARB',
  'baseId': 'ARB',
  'contract': True,
  'contractSize': 1.0,
  'created': None,
  'expiry': None,
  'expiryDatetime': None,
  'future': False,
  'id': 'ARB-PERP-INTX',
  'index': None,
  'info': {'alias': '',
           'alias_to': [],
           'auction_mode': False,
           'base_currency_id': '',
           'base_display_symbol': '',
           'base_increment': '0.1',
           'base_max_size': '66336458.5176012736600035',
           'base_min_size': '0.1',
           'base_name': '',
           'cancel_only': False,
           'display_name': 'ARB PERP',
           'fcm_trading_session_details': None,
           'future_product_details': {'contract_code': 'ARB',
                                      'contract_display_name': 'ARB PERPETUAL',
                                      'contract_expiry': None,
                                      'contract_expiry_timezone': '',
                                      'contract_expiry_type': 'PERPETUAL',
                                      'contract_root_unit': 'ARB',
                                      'contract_size': '1',
                                      'group_description': '',
                                      'group_short_description': '',
                                      'perpetual_details': {'funding_rate': '0.000011',
                                                            'funding_time': '2024-04-23T01:00:00.000003Z',
                                                            'max_leverage': '10',
                                                            'open_interest': '0'},
                                      'risk_managed_by': 'MANAGED_BY_VENUE',
                                      'venue': ''},
           'is_disabled': False,
           'limit_only': False,
           'mid_market_price': '1.215',
           'new': False,
           'post_only': False,
           'price': '1.217',
           'price_increment': '0.001',
           'price_percentage_change_24h': '2.18303946263644',
           'product_id': 'ARB-PERP-INTX',
           'product_type': 'FUTURE',
           'product_venue': 'INTX',
           'quote_currency_id': 'USDC',
           'quote_display_symbol': 'USDC',
           'quote_increment': '0.001',
           'quote_max_size': '50000000',
           'quote_min_size': '10',
           'quote_name': 'USDC',
           'status': '',
           'trading_disabled': False,
           'view_only': False,
           'volume_24h': '55493.2',
           'volume_percentage_change_24h': '-5.23297613456859',
           'watched': False},
  'inverse': False,
  'limits': {'amount': {'max': 66336458.517601274, 'min': 0.1},
             'cost': {'max': 50000000.0, 'min': 10.0},
             'leverage': {'max': None, 'min': None},
             'price': {'max': None, 'min': None}},
  'linear': True,
  'lowercaseId': None,
  'maker': 0.04,
  'margin': False,
  'option': False,
  'optionType': None,
  'precision': {'amount': 0.1, 'price': 0.001},
  'quote': 'USDC',
  'quoteId': 'USDC',
  'settle': 'USDC',
  'settleId': 'USDC',
  'spot': False,
  'strike': None,
  'subType': None,
  'swap': True,
  'symbol': 'ARB/USDC:USDC',
  'taker': 0.06,
  'type': 'swap'}]
```

```
Python v3.9.6
CCXT v4.3.2
coinbase.fetchOHLCV(BTC/USDT)
[[1713817740000, 66597.46, 66597.46, 66558.51, 66561.89, 0.73658489],
 ...
 [1713835560000, 66955.48, 66955.48, 66925.46, 66925.46, 0.00561543]]
```

```
Python v3.9.6
CCXT v4.3.2
coinbase.fetchTicker(BTC/USDT)
{'ask': 66943.17,
 'askVolume': None,
 'average': None,
 'baseVolume': None,
 'bid': 66926.07,
 'bidVolume': None,
 'change': None,
 'close': 66945.63,
 'datetime': '2024-04-23T01:27:21.075904Z',
 'high': None,
 'info': {'ask': '',
          'bid': '',
          'price': '66945.63',
          'product_id': 'BTC-USDT',
          'side': 'BUY',
          'size': '0.01014051',
          'time': '2024-04-23T01:27:21.075904Z',
          'trade_id': '19690348'},
 'last': 66945.63,
 'low': None,
 'open': None,
 'percentage': None,
 'previousClose': None,
 'quoteVolume': None,
 'symbol': 'BTC/USDT',
 'timestamp': 1713835641075,
 'vwap': None}
 ```

### CODE REVIEW

**Comment by samgermain** [comment]
> locally i get
> 
> ```
> [AuthenticationError] coinbase GET https://api.coinbase.com/api/v3/brokerage/transaction_summary 401 Unauthorized Unauthorized
> 
>     at handleHttpStatusCode       Users/cjg/Git/ccxt9/ccxt/js/src/base/Exchange.js:1075  
>     at                            Users/cjg/Git/ccxt9/ccxt/js/src/base/Exchange.js:977   
>     at processTicksAndRejections  node:internal/process/task_queues:95                   
>     at fetch2                     Users/cjg/Git/ccxt9/ccxt/js/src/base/Exchange.js:3672  
>     at request                    Users/cjg/Git/ccxt9/ccxt/js/src/base/Exchange.js:3675  
>     at all                                                                               
>     at fetchMarketsV3             Users/cjg/Git/ccxt9/ccxt/js/src/coinbase.js:1326       
>     at fetchMarkets               Users/cjg/Git/ccxt9/ccxt/js/src/coinbase.js:1105       
>     at loadMarketsHelper          Users/cjg/Git/ccxt9/ccxt/js/src/base/Exchange.js:1000  
>     at async run                  Users/cjg/Git/ccxt9/ccxt/examples/js/cli.js:300        
> 
> coinbase GET https://api.coinbase.com/api/v3/brokerage/transaction_summary 401 Unauthorized Unauthorized
> ```

That sounds like a problem with your apiKey maybe?  Also `https://api.coinbase.com/api/v3/brokerage/transaction_summary` isn't one of the methods that I added

**Comment by carlosmiei** [comment]
@samgermain "https://api.coinbase.com/api/v3/brokerage/transaction_summary" this method is part of `fetchMarkets`, so if they're preventing it from loading we should probably check if keys are available or not before firing the requests.

image

**Comment by carlosmiei** [comment]
@samgermain ok i think I found the issue, `transactionSummay` remained private, and we're not handling the exceptions around the spotPromises

**Comment by carlosmiei** [comment]
One more difference, previously this worked
```
2024-04-23T11:13:48.768Z
Node.js: v18.18.0
CCXT v4.3.2
coinbase.fetchOHLCV (BTC/USDC)
fetch Request:
 coinbase GET https://api.coinbase.com/api/v3/brokerage/products/BTC-USDC/candles?granularity=ONE_MINUTE&start=1713852831&end=1713870831 
RequestHeaders:
 {
````
and now throws:
```
 n coinbase fetchOHLCV "BTC/USDC"                             
Debugger attached.
2024-04-23T11:11:32.193Z
Node.js: v20.7.0
CCXT v4.3.5
coinbase.fetchOHLCV (BTC/USDC)
BadRequest coinbase {"error":"INVALID_ARGUMENT","error_details":"product_id argument is invalid ","message":"product_id argument is invalid "}
---------------------------------------------------
```

**Comment by carlosmiei** [comment]
@samgermain one more thing,  after a few requests I get a too many requests error
```
} 
RequestBody:
 undefined 

handleRestResponse:
 coinbase GET https://api.coinbase.com/api/v3/brokerage/market/products/BTC-USD/candles?granularity=ONE_MINUTE&start=1713853372&end=1713871372 429 Too Many Requests 
ResponseHeaders:
```

**Comment by samgermain** [comment]
> @samgermain one more thing, after a few requests I get a too many requests error
> 
> ```
> } 
> RequestBody:
>  undefined 
> 
> handleRestResponse:
>  coinbase GET https://api.coinbase.com/api/v3/brokerage/market/products/BTC-USD/candles?granularity=ONE_MINUTE&start=1713853372&end=1713871372 429 Too Many Requests 
> ResponseHeaders:
> ```

I don't know how this would be solved, it looks like the rate limits are calculated correctly base on https://docs.cloud.coinbase.com/advanced-trade-api/docs/rest-api-rate-limits

Maybe this warning has something to do with it?

**Comment by samgermain** [comment]
> One more difference, previously this worked
> 
> ```
> 2024-04-23T11:13:48.768Z
> Node.js: v18.18.0
> CCXT v4.3.2
> coinbase.fetchOHLCV (BTC/USDC)
> fetch Request:
>  coinbase GET https://api.coinbase.com/api/v3/brokerage/products/BTC-USDC/candles?granularity=ONE_MINUTE&start=1713852831&end=1713870831 
> RequestHeaders:
>  {
> ```
> 
> and now throws:
> 
> ```
>  n coinbase fetchOHLCV "BTC/USDC"                             
> Debugger attached.
> 2024-04-23T11:11:32.193Z
> Node.js: v20.7.0
> CCXT v4.3.5
> coinbase.fetchOHLCV (BTC/USDC)
> BadRequest coinbase {"error":"INVALID_ARGUMENT","error_details":"product_id argument is invalid ","message":"product_id argument is invalid "}
> ---------------------------------------------------
> ```

It looks like USDC markets aren't working correctly for any of the public endpoints. They return data for `BTC/USD`

The following three endpoints all return data for BTC-USD

https://api.coinbase.com/api/v3/brokerage/market/products/BTC-USDC/ticker?limit=1
https://api.coinbase.com/api/v3/brokerage/market/product_book?product_id=BTC-USDC
https://api.coinbase.com/api/v3/brokerage/market/products/BTC-USDC/ticker 

The candles endpoint doesn't work for USDC markets at all (returns `INVALID_ARGUMENT` error)

https://api.coinbase.com/api/v3/brokerage/market/products/BTC-USDC/candles?granularity=ONE_MINUTE&start=1713883556&end=1713901556

returns 
```
{"error":"INVALID_ARGUMENT","error_details":"product_id argument is invalid ","message":"product_id argument is invalid "}
```

----------------

All of these endpoint work correctly for markets with a quote currency that is not USDC

--------------

I posted about this in the coinbase discord

**Comment by samgermain** [comment]
> One more difference, previously this worked
> 
> ```
> 2024-04-23T11:13:48.768Z
> Node.js: v18.18.0
> CCXT v4.3.2
> coinbase.fetchOHLCV (BTC/USDC)
> fetch Request:
>  coinbase GET https://api.coinbase.com/api/v3/brokerage/products/BTC-USDC/candles?granularity=ONE_MINUTE&start=1713852831&end=1713870831 
> RequestHeaders:
>  {
> ```
> 
> and now throws:
> 
> ```
>  n coinbase fetchOHLCV "BTC/USDC"                             
> Debugger attached.
> 2024-04-23T11:11:32.193Z
> Node.js: v20.7.0
> CCXT v4.3.5
> coinbase.fetchOHLCV (BTC/USDC)
> BadRequest coinbase {"error":"INVALID_ARGUMENT","error_details":"product_id argument is invalid ","message":"product_id argument is invalid "}
> ---------------------------------------------------
> ```

This was a problem with coinbases exchange, it's fixed now

**Pull request merged**
