### PR TITLE
bitmex new endpoints

### PR DESCRIPTION
**Pull request by ndubel**
https://www.bitmex.com/api/explorer/#!/

for `precision amount` https://blog.bitmex.com/api_announcement/spot-order-book-trading-now-live-on-testnet-ahead-of-q2-launch/ 

> lotSize denotes the lot size in base currency. Using XBT_USDT as an example, its lotSize is 10,000, with underlyingToPositionMultiplier as 100,000,000, it means the lot size is 0.0001 XBT.

https://www.bitmex.com/api/v1/instrument/active
looks like some contracts have `underlyingToPositionMultiplier: null`, and some contracts and spot have this multiplier

### CODE REVIEW

**Comment by ndubel** [comment]
https://github.com/ccxt/ccxt/pull/18089
I see some big discussion about precisions on spot, but `precision` `amount` are still wrong:
https://www.bitmex.com/app/trade/XBT_USDT we can see here that `precision`  `amount` is `0.0001`, so it is `lotSize / underlyingToPositionMultiplier`. But probably if we merge this PR, some other methods will be broken...
```
{
  id: 'XBT_USDT',
  lowercaseId: undefined,
  symbol: 'BTC/USDT',
  base: 'BTC',
  quote: 'USDT',
  settle: undefined,
  baseId: 'XBT',
  quoteId: 'USDT',
  settleId: undefined,
  type: 'spot',
  spot: true,
  margin: false,
  swap: false,
  future: false,
  option: false,
  index: undefined,
  active: true,
  contract: false,
  linear: undefined,
  inverse: false,
  subType: undefined,
  taker: 0.00075,
  maker: -0.00025,
  contractSize: undefined,
  expiry: undefined,
  expiryDatetime: undefined,
  strike: undefined,
  optionType: undefined,
  precision: { amount: 10000, price: 0.5 },
  limits: {
    leverage: { min: undefined, max: undefined },
    amount: { min: undefined, max: 100000000000 },
    price: { min: undefined, max: 1000000 },
    cost: { min: undefined, max: undefined }
  },
  created: 1652760000000,
  info: {
    symbol: 'XBT_USDT',
    rootSymbol: 'XBT',
    state: 'Open',
    typ: 'IFXXXP',
    listing: '2022-05-17T04:00:00.000Z',
    front: null,
    expiry: null,
    settle: null,
    listedSettle: null,
    relistInterval: null,
    positionCurrency: '',
    underlying: 'XBT',
    quoteCurrency: 'USDT',
    underlyingSymbol: '',
    reference: 'BMEX',
    referenceSymbol: '',
    calcInterval: null,
    publishInterval: null,
    publishTime: null,
    maxOrderQty: '100000000000',
    maxPrice: '1000000',
    lotSize: '10000',
    tickSize: '0.5',
    multiplier: '1',
    settlCurrency: '',
    underlyingToPositionMultiplier: '100000000',
    underlyingToSettleMultiplier: null,
    quoteToSettleMultiplier: '1000000',
    isQuanto: false,
    isInverse: false,
    initMargin: '1',
    maintMargin: '1',
    riskLimit: null,
    riskStep: null,
    limit: null,
    taxed: true,
    deleverage: false,
    makerFee: '-0.00025',
    takerFee: '0.00075',
    settlementFee: '0',
    fundingBaseSymbol: '',
    fundingQuoteSymbol: '',
    fundingPremiumSymbol: '',
    fundingTimestamp: null,
    fundingInterval: null,
    fundingRate: null,
    indicativeFundingRate: null,
    rebalanceTimestamp: null,
    rebalanceInterval: null,
    prevClosePrice: '43909.5',
    limitDownPrice: null,
    limitUpPrice: null,
    totalVolume: '2460657180000',
    volume: '0',
    volume24h: '226130000',
    prevTotalTurnover: '562497127186750',
    totalTurnover: '562497127186750',
    turnover: '0',
    turnover24h: '98753094400',
    homeNotional24h: '2.2613000000000003',
    foreignNotional24h: '98753.0944',
    prevPrice24h: '44058',
    vwap: '43670.93901737938',
    highPrice: '44200',
    lowPrice: '43231.5',
    lastPrice: '43600',
    lastPriceProtected: '43600',
    lastTickDirection: 'PlusTick',
    lastChangePcnt: '-0.0083',
    bidPrice: '43652.5',
    midPrice: '43656',
    askPrice: '43659.5',
    impactBidPrice: '43652.5',
    impactMidPrice: '43656',
    impactAskPrice: '43659.5',
    hasLiquidity: true,
    openInterest: '0',
    openValue: '0',
    fairMethod: '',
    fairBasisRate: null,
    fairBasis: null,
    fairPrice: null,
    markMethod: 'LastPrice',
    markPrice: '43600',
    indicativeSettlePrice: null,
    settledPriceAdjustmentRate: null,
    settledPrice: null,
    instantPnl: false,
    timestamp: '2023-12-21T19:12:38.054Z'
  },
  tierBased: undefined,
  percentage: undefined,
  quanto: false
} 
```

**Comment by carlosmiei** [comment]
@ndubel Hey, the precision change needs to be analyzed carefully, do you think that we could split this pR in two? one adds the missing methods and can be merged fast the other updates the precision and we can discuss it there

**Comment by ndubel** [comment]
> @ndubel Hey, the precision change needs to be analyzed carefully, do you think that we could split this pR in two? one adds the missing methods and can be merged fast the other updates the precision and we can discuss it there

Yes, probably we need to split it. Should I close this and make two separate PRs?

**Comment by carlosmiei** [comment]
@ndubel yes that or revert the precision changes from this one, and open a new one only with that part

**Comment by ndubel** [comment]
I've remove precisions but add some `parseTrade` fixes. For spot in all cases `fee` `currency` is `quote` (and equal to `currency` in response) and also now spot maker fees are negative for all users https://www.bitmex.com/wallet/fees/spot and fee comes as negative value in these cases.
2023-12-22_14h26_40

**Comment by ndubel** [comment]
@carlosmiei can you take a look please?

**Comment by carlosmiei** [comment]
@ndubel Sorry, I have been busy with other issues, will try to pick this one soon

**Pull request merged**
