### PR TITLE
fix a numberToString bug

### PR DESCRIPTION
**Pull request by frosty00**

### CODE REVIEW

**Comment by kroitor** [comment]
https://travis-ci.org/github/ccxt/ccxt/builds/716707077#L2292

**Comment by kroitor** [comment]
I wonder why it did not break the build. Need to fix that as well.

**Comment by frosty00** [comment]
lol i just fixed js then php breaks 0:

**Comment by frosty00** [comment]
going to go to sleep then look at this tomorrow. im running tests for the python client all night

**Comment by kroitor** [comment]
@frosty00 can you investigate into why those failed PHP assertions don't break it?

**Comment by frosty00** [comment]
doesn't seem critical. we probably need to fix the behaviour of php though

**Comment by kroitor** [comment]
@frosty00 i mean, if the assertion fails in PHP, and the test survives, then we're not asserting really.

**Comment by frosty00** [comment]
yeah it has to do with how assertions happen in php, i can change it but the solution is pretty ugly. the tldr is that assertions just trigger a warning in php

**Comment by frosty00** [comment]
if you want to support php5 then you have to trigger a callback for assert https://www.php.net/manual/en/function.assert.php

**Comment by frosty00** [comment]
tbh i would rather just keep it is it is and not do anything

**Comment by kroitor** [comment]
@frosty00 i don't think we need a callback, we should simply https://www.php.net/manual/en/function.set-error-handler.php and catch-and-throw-on-everything

**Comment by kroitor** [comment]
> tbh i would rather just keep it is it is and not do anything

But then one third of our base tests is not executed right (not breaking when expected).

**Comment by kroitor** [comment]
@frosty00 nvm, i'll add the proper handling for those warnings, but we will still need to fix numberToString uniformly

**Comment by kroitor** [comment]
@frosty00 now it fails as expected, lol )

**Pull request merged**
