### PR TITLE
Idex exchange basic fetchTicker(s)

### PR DESCRIPTION
**Pull request by valentinbora**
Related to #1559

### CODE REVIEW

**Comment by valentinbora** [comment]
@kroitor question... I see most exchanges have a github image source (e.g. https://user-images.githubusercontent.com/....), what's the approach here? Size/proportion limits, where to upload etc.

**Comment by kroitor** [comment]
> what's the approach here? Size/proportion limits, where to upload etc.

Size / limits 85x25 2-3kb .jpg, drop the file into the comment edit textarea here on GitHub and grab the url from it. But anyways, you don't have bother at all, as we rewrite them upon merging anyway.

**Comment by valentinbora** [comment]
@kroitor right, I just see Travis being picky about it :)

**Comment by mahapo** [comment]
@kroitor Any chance to merge this pr?

**Comment by kroitor** [comment]
Moved to https://github.com/ccxt/ccxt/pull/4545

**Pull request closed without merging**
