### PR TITLE
link logos to referral/url

### PR DESCRIPTION
**Pull request by frosty00**
clickable logos as suggested in an email

### CODE REVIEW

**Comment by frosty00** [comment]
checkout https://github.com/frosty00/ccxt/blob/link_logos/README.md and https://github.com/frosty00/ccxt/blob/link_logos/wiki/Exchange-Markets-By-Country.md compared to the tiny logos [here](https://github.com/ccxt/ccxt/wiki/Exchange-Markets-By-Country)

also ignore the second commit message that was before I was using markdown

**Comment by kroitor** [comment]
> compared to the tiny logos

Yep, that's because in the wiki, the navigation sidebar on the right shrinks the content area width on the left... (`_Sidebar.html`)

**Comment by frosty00** [comment]
I think the issue is in the css of the page, in particular `max-width: 100%;`. This means the images cannot be larger than their parent divs. If you change it using the inspector in chrome/firefox to `max-width: none;` they go back to being 85x25

**Comment by frosty00** [comment]
take a look at my readme, this also fixes the logos appearing too small https://i.imgur.com/kFOpef5.png

**Comment by kroitor** [comment]
@frosty00 thx! I need to check the .md → .rst conversion, though, because NPM wants `md` and PyPI wants `rst`, so we have a separate stage of doc conversions that does `md`→`rst` and copies files where necessary. So the version that will be displayed depends on where it is displayed. However, there's an issue with PyPI+`rst`. Turned out, they couldn't show the `rst` if it was converted as is (images in tables were forbidden as well as some other constructs), so, we now have this ugly stage that does `rst` stripping: https://github.com/ccxt/ccxt/blob/master/update-badges.js#L8 in a very unexpected place, so that PyPI could render it properly... If PyPI fails to render it – it simply dumps it in plaintext to the page which looks uglier than a properly stripped `rst`. In fact, since then PyPI might have changes their rules and might have relaxed their restrictions, so, basically in order to merge this PR we have to check and make sure that it works with md/rst when uploaded to PyPI... That isn't an easy thing to debug though, as it requires a standalone project for the testing, so that we don't interfere with commit history in this repo.

**Comment by frosty00** [comment]
is there anyway I can help out with this? Should I make a pypy repo? Also the logos are not shown for not certified exchanges on https://pypi.org/project/ccxt/. Do you want to display the logos for all the projects?

I think we could use https://pypi.org/project/cctx/ to test

**Comment by frosty00** [comment]
https://github.com/frosty00/ccxt/blob/link_logos/README.md is much nicer )

**Comment by frosty00** [comment]
@kroitor it also fixes the readme on mobile. **pls merge**

**Pull request merged**
