### PR TITLE
Deribit parse position

### LINKED ISSUE #13313: Deribit - wrong contractSize at fetch_position for USDC marginated contracts
CCXT returns bad value for 'contracts' for USDC marginated contracts

- OS: ChromeOS
- Programming Language version: Python 3.10.2
- CCXT version: 1.82.91

```
import ccxt
d = ccxt.deribit()
d.apiKey = 'xxx'
d.secret = 'xxx'
d.fetch_position('BTC/USDC:USDC')
```

I have an open position (on BTC/USDC:USDC) with size 1 contract. Field value 'contracts' should be 1. Instead I get 30.015878, which is the size of position in USDC. 
For BTC marginated contract with position 10 USD (1 contract) I get 'contractSize' = 10 and 'contracts' = 10, which is also weird since contractSize * contracts does not fit the position size in USD.

### PR DESCRIPTION
**Pull request by Dan-krm**
Set contracts to undefined and adjusted maintenanceMargin, initialMargin and their percentages of the notional value:
Fixes #13313
```
deribit.fetchPosition (SOL/USD:SOL)
2022-05-21T06:34:06.676Z iteration 0 passed in 178 ms

{
  info: {
    total_profit_loss: '-0.001131489',
    size_currency: '0.603420186',
    size: '30.0',
    settlement_price: '52.09',
    realized_profit_loss: '0.000615087',
    realized_funding: '0.00000443',
    open_orders_margin: '0.0',
    mark_price: '49.72',
    maintenance_margin: '0.012070224',
    leverage: '25',
    kind: 'future',
    instrument_name: 'SOL-PERPETUAL',
    initial_margin: '0.024138628',
    index_price: '49.72',
    floating_profit_loss: '-0.001131489',
    estimated_liquidation_price: '21.98',
    direction: 'buy',
    delta: '0.603420186',
    average_price: '49.81'
  },
  symbol: 'SOL/USD:SOL',
  timestamp: 1653114846676,
  datetime: '2022-05-21T06:34:06.676Z',
  initialMargin: 0.024138628,
  initialMarginPercentage: 4.000301706844126,
  maintenanceMargin: 0.012070224,
  maintenanceMarginPercentage: 2.000301660441966,
  entryPrice: 49.81,
  notional: 0.603420186,
  leverage: 25,
  unrealizedPnl: -0.001131489,
  contracts: undefined,
  contractSize: 10,
  marginRatio: undefined,
  liquidationPrice: 21.98,
  markPrice: 49.72,
  collateral: undefined,
  marginMode: undefined,
  marginType: undefined,
  side: 'long',
  percentage: -4.687461938598996
}
```

### CODE REVIEW

**Comment by kroitor** [comment]
> contractSize to the size of the position in quote units:

I thing the size of the position in quote units is `collateral`, not the `contractSize`, right? The contractSize is just the value of one contract.

**Comment by Dan-krm** [comment]
> I think the size of the position in quote units is `collateral` or `notional`, not the `contractSize`, right? The contractSize is just the value of one contract.

From the docs for parsePosition it says:
```
'contractSize': 100,         // float, the size of one contract in quote units
```
Notional is the current value in the settlement currency, collateral is the posted margin

**Comment by kroitor** [comment]
@Dan-krm the info we load in the markets says that the contractSize of SOL/USDT:USDT is 10 (not 20):

```
~/ccxt $ node examples/js/cli deribit market SOL/USD:SOL
2022-05-21T05:14:50.125Z
Node.js: v16.13.2
CCXT v1.83.32
deribit.market (SOL/USD:SOL)
2022-05-21T05:14:50.924Z iteration 0 passed in 0 ms

{
  id: 'SOL-PERPETUAL',
  symbol: 'SOL/USD:SOL',
  base: 'SOL',
  quote: 'USD',
  baseId: 'SOL',
  quoteId: 'USD',
  active: true,
  type: 'swap',
  linear: false,
  inverse: true,
  spot: false,
  swap: true,
  future: false,
  option: false,
  margin: false,
  contract: true,
  contractSize: 10,
  expiry: 32503708800000,
  expiryDatetime: '3000-01-01T08:00:00.000Z',
  optionType: undefined,
  strike: undefined,
  settle: 'SOL',
  settleId: 'SOL',
  precision: { amount: 10, price: 0.01 },
  limits: {
    leverage: { min: undefined, max: undefined },
    amount: { min: 10, max: undefined },
    price: { min: 0.01, max: undefined },
    cost: { min: undefined, max: undefined }
  },
  info: {
    tick_size: '0.01',
    taker_commission: '0.0005',
    settlement_period: 'perpetual',
    settlement_currency: 'SOL',
    rfq: false,
    quote_currency: 'USD',
    price_index: 'sol_usd',
    min_trade_amount: '10.0',
    max_liquidation_commission: '0.009',
    max_leverage: '25',
    maker_commission: '-0.0002',
    kind: 'future',
    is_active: true,
    instrument_name: 'SOL-PERPETUAL',
    instrument_id: '215830',
    future_type: 'reversed',
    expiration_timestamp: '32503708800000',
    creation_timestamp: '1651219567000',
    counter_currency: 'USD',
    contract_size: '10.0',
    block_trade_commission: '0.0001',
    base_currency: 'SOL'
  },
  tierBased: undefined,
  percentage: undefined,
  taker: 0.0005,
  maker: -0.0002
}
```

I guess, the position `size` means something other than `contractSize`?

**Comment by Dan-krm** [comment]
> I guess, the position `size` means something other than `contractSize`?

Based on the interface, the position size is the total leveraged value of the position in USD when the position is first opened. I  removed position 'size' from the response and set the notional value to the current leveraged position value in the settlement currency.

I also redid maintenance margin, initial margin and their percentages.

**Pull request merged**
