### PR TITLE
Fetchcurrencies for okex3/okcoin

### PR DESCRIPTION
**Pull request by ttodua**
added first 'if block'. after 'else' everything is same, havent touched.

### CODE REVIEW

**Comment by ttodua** [comment]
@kroitor this seems to TRAVIS fail because of thrown exception (which is expected to happen that way). However, TRAVIS fails. What should I do in such case?

**Comment by kroitor** [comment]
@ttodua 

> However, TRAVIS fails. What should I do in such case?

We should fix `test.fetchCurrencies.js` for the `undefined` case.

**Comment by ttodua** [comment]
@kroitor I think this PR is also ready.

**Comment by kroitor** [comment]
@ttodua not sure why it was closed, i think, by accident.

**Pull request merged**
