### PR TITLE
travis - no tags

### PR DESCRIPTION
**Pull request by ttodua**
saves additional 3+ mins

### CODE REVIEW

**Comment by carlosmiei** [comment]
@ttodua if you don't mind I added it here: https://github.com/ccxt/ccxt/pull/17968, since I'm already doing a lot of small optimizations there

**Comment by ttodua** [comment]
ah, good! i have not seen it, sure !

**Comment by carlosmiei** [comment]
> ah, good! i have not seen it, sure !

@ttodua with the no-tags and new optimizations:
image

**Comment by ttodua** [comment]
> > ah, good! i have not seen it, sure !
> 
> @ttodua with the no-tags and new optimizations: image

ouch, damn... 
😎👍👍👍👍👍👍

**Pull request closed without merging**
