### PR TITLE
fix(currencycom) - handle trades [QUICK]

### PR DESCRIPTION
**Pull request by ttodua**
some strange error surfaced here: https://app.travis-ci.com/github/ccxt/ccxt/builds/269349696#L3734

the third argument, was neither used in that `handleTrades` method body, and it was neither ever passed to that function, because all handler functions are only provided with 2 arguments :  `https://github.com/ccxt/ccxt/blob/master/ts/src/pro/currencycom.ts#L577`

### CODE REVIEW

**Comment by carlosmiei** [comment]
For some reason this PR triggered a full build, weird, I rebased it let's see

**Comment by ttodua** [comment]
o_O ? but why did it, i remind such glitch in the past, but not in last 1-2 months.
ok, lets consider as somewhat one-time ocurrence, if this will re-occur, i'll look into.

**Comment by carlosmiei** [comment]
> o_O ? but why did it, i remind such glitch in the past, but not in last 1-2 months. ok, lets consider as somewhat one-time ocurrence, if this will re-occur, i'll look into.

@ttodua It detected a change in one of the tests file

**Comment by ttodua** [comment]
could it be some CR LF end line ending differences, that github doesn't show, but git (program itself) does detect? idk, hard to say.

**Comment by carlosmiei** [comment]
> could it be some CR LF end line ending differences, that github doesn't show, but git itself doesn't ignore? idk, hard to say.

if this continues we have to check that

**Pull request merged**
