### PR TITLE
 tests: added tests for InsufficientFunds and InvalidOrder exceptions

### PR DESCRIPTION
**Pull request by mkutny**
Commented out the tests for safe merging as they would trigger a lot of failures.

Adapting all exchanges to pass these tests will take few weeks, so I left a possibility to switch them on manually on a per-exchange basis for testing.

Had to extend Errors for pretty printing along the way. Hope it won't hurt.

### CODE REVIEW

**Comment by kroitor** [comment]
Fantastic work! We will start updating the exchanges one by one. Thank you! )

**Comment by kroitor** [comment]
BTW, we can actually go without the `.name`, if we use the `e.constructor.name` built-in property  – it's the same string )

**Comment by mkutny** [comment]
> we can actually go without the `.name`, if we use the e.constructor.name built-in property

Oh, that's great! I had I gut feeling there should be an easier way but unfortunately suppressed it )

**Comment by kroitor** [comment]
Alright! Merging it next ) Thx for the edits

**Comment by mkutny** [comment]
As we discussed before, I'm stumbling on the exchanges with lack of permissions for this kind of test:
```
  Error (ExchangeError) {
    constructor: Function ExchangeError {},
    message: 'binance {"code":-2015,"msg":"Invalid API-key, IP, or permissions for action."}',
  }
```
Could you permit binance keys to create orders?

**Comment by kroitor** [comment]
Sure, will add a new keypair there with needed permissions shortly.

**Pull request merged**
