### PR TITLE
fix(coinbasepro) - shadow vars rename (QUICK)

### PR DESCRIPTION
**Pull request by ttodua**
we had bug in `handleOrder`. idk how critical it was.

### CODE REVIEW

**Comment by carlosmiei** [comment]
@ttodua what was the bug?

**Comment by ttodua** [comment]
> @ttodua what was the bug?

558th line re-set the `const orders`, so let's use different names

**Comment by ttodua** [comment]
This PR ready too.

**Comment by ttodua** [comment]
@carlosmiei ^

**Comment by carlosmiei** [comment]
LGTM ✅

**Review by carlosmiei — APPROVED** [review]

**Pull request merged**
