### PR TITLE
Fees info

### PR DESCRIPTION
**Pull request by redindian**
Added some fees info.

### CODE REVIEW

**Comment by mkutny** [comment]
@redindian, thanks for these updates!

I see that bitmex and quoinex exchanges do provide their fees in their market properties, e.g. they are loaded on per-market basis by `fetchMarkets`.

I also see from their docs that their fees vary across markets.

Why do you think we need to provide them with `exchange.fees` property? It seems to be fine with zaif but I'm not sure it's quite accurate with bitmex/quoinex.

**Comment by kroitor** [comment]
I agree with @mkutny and I would prefer not hardcoding them, of course...

**Comment by redindian** [comment]
@mkutny @kroitor: I was unaware of that. I was trying to import the fees for various markets directly from describe() into a database and thought these fees were missing. Using dynamic fees is better off course!

**Comment by kroitor** [comment]
> I was trying to import the fees for various markets directly from describe() into a database and thought these fees were missing.

This is currently not very well documented (under development), but the logic behind it is to load market info first, then access the fee info within markets (trading fees are properties of a market). Thx for your involvement anyway! Appreciate your help!

**Pull request merged**
