### PR TITLE
add gateio trading fees

### PR DESCRIPTION
**Pull request by nerdDan**

### CODE REVIEW

**Comment by nerdDan** [comment]
This PR only changes `gateio.js` but Travis CI build failed on `zb.js`. What should I do?

**Comment by kroitor** [comment]
@nerdDan 

> This PR only changes gateio.js but Travis CI build failed on zb.js.

Yep, Travis will complain on all errors, even the ones that aren't related to your changes in any way... This is because some other exchange will occasionally go down or offline for maintenance, or will break, etc, but it has nothing to do with gateio.js, of course.

> What should I do?

Celebrate a version update with us as I'm merging it shortly )

Thanks for your participation! Really appreciate it!

**Comment by kroitor** [comment]
@nerdDan, one more thing, you really want to read these posts in chronological order to understand the direction in which we're moving for better support for fees:

- https://github.com/ccxt/ccxt/pull/1669
- https://github.com/ccxt/ccxt/pull/1814
- https://github.com/ccxt/ccxt/pull/1835

Thx again.

**Comment by nerdDan** [comment]
It is I must thank you for every you have done.
I am merely doing some tiny contribution in favour of my own trading bot. 😺

**Pull request merged**
