### PR TITLE
Exchange: build_ohlcv impl

### PR DESCRIPTION
**Pull request by kornrunner**
PHP implementation of #695 / #751

Also minor tidying around exceptions

### CODE REVIEW

**Comment by kroitor** [comment]
Respect! Merging this with Python and JS PRs!

**Comment by kroitor** [comment]
Thank you!

**Comment by kroitor** [comment]
Ref: #637

**Comment by 333miiko** [comment]
Would it be better we sort the parameters to be in the same order as fetchOHLCV?

ie. timeframe, since, limit

**Comment by kroitor** [comment]
Hey, @kornrunner ! Don't want to bother you, but, being a PHP-specialist, maybe you could take a look at this issue+PR on PSR-4 autoloading in Composer: https://github.com/ccxt/ccxt/issues/862 + https://github.com/ccxt/ccxt/pull/865
I'd merge it, but I'm not very familiar with Composer, therefore I don't know the correct way to include the library (tried replicating the PR locally, but it complained with a "class not found" message upon instantiation). We will be very thankful for your assistance on reviewing the above (need supervision from someone who has more experience with Composer). Thanks in advance!

**Pull request merged**
