### PR TITLE
`fetchOHLCV` - normalization of required arguments across exchanges

### PR DESCRIPTION
**Pull request by ttodua**
We had talked about this a few times in the past ([here](https://github.com/ccxt/ccxt/issues/14091#issuecomment-1168427549) and also somewhere on discord). 
so, there are some exchanges, that just require anything to be provided in `limit` param. I know, we typically don't invent values ourselves, but as 95%+ exchanges support just firing `e.fetchOHLCV ('BTC/USDT')` and users get some response without need to provide the `limit/since` argument (be it 100,500 or whatever default from any exchange), it is more reasonable that we set non-hurting values for `limit` for those exchanges which require it, so user's doesn't get exception/code-breaks for those 5% exchanges.

### CODE REVIEW

**Comment by ttodua** [comment]
moreover, when `limit` is known, there is no point to check whether since is defined or not, as we can calculate the `duration * limit` from current moment to set the `since`.

**Comment by ttodua** [comment]
@carlosmiei I think I've made the needed edits, to normalize the library and avoid unnecessary burden of throwing exceptions and etc. In most cases it was possible to define the default `limit` value (either finding out that from exchange/api responses itself, or setting some average user-expected value). Now, lib can be safely called without "several exchanges" breaking the loops.

**Comment by carlosmiei** [comment]
@ttodua thanks, will review it asap

**Comment by carlosmiei** [comment]
@ttodua `phemex` and `mercado` seem to not be working, can you check it?

**Comment by ttodua** [comment]
> @ttodua `phemex` and `mercado` seem to not be working, can you check it?

oh, i've missed the note in phemex, which says the last bar is not returned. so, the limit needed to be 1999 instead of 2000. 

about mercado, strange , i've not changed implementation, just defaulted to `1m` instead of `5m`, and I confirm that it doesn't work. I've tested without changes, and neither I can find a way to make mercado's fetchOHLCV work. the current update works (through v4 api request)

**Comment by ttodua** [comment]
I've removed mercado from this PR and making a separate PR for that.

**Comment by ttodua** [comment]
@carlosmiei the "request review" button doesn't show up, so, making a comment here :)

**Comment by carlosmiei** [comment]
LGTM ✅ 

```
bitbank method: fetch_ohlcv BTC/JPY res: [1664379300000, 2799041.0, 2799800.0, 2799041.0, 2799081.0, 0.135]
bitopro method: fetch_ohlcv BTC/USDT res: []
bitstamp method: fetch_ohlcv BTC/USDT res: [1664379300000, 19383.0, 19383.0, 19383.0, 19383.0, 0.00352007]
btcalpha method: fetch_ohlcv BTC/USDT res: [1664223300000, 19182.04, 19197.78, 19129.48, 19139.0, 16.942309]
bybit method: fetch_ohlcv BTC/USD:BTC res: [1664427300000, 19580.0, 19595.5, 19575.0, 19586.5, 576125.0]
coinex method: fetch_ohlcv BTC/USDT res: [1664433300000, 19325.45, 19332.99, 19325.45, 19332.98, 0.12701141]
deribit method: fetch_ohlcv SOL/USD:SOL-220930 res: [1664379360000, 32.54, 32.54, 32.54, 32.54, 0.0]
exmo method: fetch_ohlcv BTC/USDT res: [1664379360000, 19406.12, 19406.12, 19406.12, 19406.12, 0.0207]
gemini method: fetch_ohlcv BTC/USD res: [1664352960000, 18736.55, 18736.55, 18728.32, 18728.32, 0.0003011]
hollaex method: fetch_ohlcv BTC/USDT res: [1664379360000, 19397.26, 19397.26, 19397.26, 19397.26, 0.2309]
kucoin method: fetch_ohlcv BTC/USDT res: [1664433360000, 19335.2, 19353.4, 19335.2, 19353.4, 8.67720609]
kucoinfutures method: fetch_ohlcv BTC/USDT:USDT res: [1664427360000, 19590.0, 19590.0, 19582.0, 19585.0, 12623.0]
lbank method: fetch_ohlcv BTC/USDT res: [1664379360000, 19388.65, 19413.9, 19388.65, 19413.9, 3.1786]
lbank2 method: fetch_ohlcv BTC/USDT res: [1664433360000, 19333.57, 19351.74, 19333.57, 19351.74, 3.65]
phemex method: fetch_ohlcv BTC/USDT res: [1664433300000, 19326.94, 19337.29, 19320.05, 19334.25, 13.262818]
poloniex method: fetch_ohlcv BTC/USDT res: [1664433360000, 19333.25, 19348.92, 19333.25, 19348.92, 0.21678]
probit method: fetch_ohlcv BTC/USDT res: [1664433300000, 19323.4, 19336.9, 19323.4, 19336.9, 0.121316]
stex method: fetch_ohlcv BTC/USDT res: [1664433420000, 19358.474394, 19358.474395, 19358.474394, 19358.474395, 5.3e-05]
timex method: fetch_ohlcv BTC/USDT res: [1664379420000, 19382.0, 19382.0, 19382.0, 19382.0, 0.003]
```

**Review by carlosmiei — APPROVED** [review]

**Pull request merged**
