### PR TITLE
[coinmate] parse order status fix

### PR DESCRIPTION
**Pull request by npomfret**

### CODE REVIEW

**Comment by kroitor** [comment]
@npomfret the problem is that `PARTIALLY_FILLED` is ambiguous – could be set on a partially-filled but still open order. What do you think?

**Comment by npomfret** [comment]
It's a good question.

The websocket feed that I use has a stream for open orders only and I record all the messages.  I don't  see a single instance of partially filled in the data.  But I do see it coming from the Rest API via `fetchOrders`.

**Comment by kroitor** [comment]
Yeah, that's why i think the exchanges should not invent any nonsense like "PARTIALLY_FILLED", because that actually does not help the user, in fact it only complicates things. A spot order should be either open, closed or canceled, with a corresponding `filled` amount if it was partially traded.

**Comment by npomfret** [comment]
I've raised a ticket.  And am looking more into my data to see if I can prove myself wrong

**Comment by npomfret** [comment]
Ha, ok - I'm really sorry, but can you please revert that change?

I found an example where I saw that status BEFORE I issued a cancel

**Comment by kroitor** [comment]
@npomfret sure! Thx!

**Comment by npomfret** [comment]
Thanks.  I think it's probably 'OPEN' after all.  But let's wait to hear from their support.

**Comment by kroitor** [comment]
> I think it's probably 'OPEN' after all.

It probably depends on which endpoint you call. PARTIALLY_FILLED for open orders = open. PARTIALLY_FILLED for closed/canceled/historical orders = canceled... smth like that... which is, again, some nonsense that the user should not be bothered with.

**Comment by npomfret** [comment]
I was completely wrong. From their support team:

> Dear client, partially filled orders are only those open at the time and partially marketed. It does not display on cancelled ones.

**Comment by kroitor** [comment]
@npomfret nw, i think the current codebase works well for the above, thanks! lmk if you have any issues with it

**Pull request merged**
