### PR TITLE
fetchPremiumIndexOHLCV

### PR DESCRIPTION
**Pull request by samgermain**
Added unified fetchPremiumIndexOHLCV method
'premium_index', 'premiumIndex' or 'premium-index' can be used as the value for key `price` in `fetchOHLCV` params.

Currently only implemented on `Bybit`

### CODE REVIEW

**Comment by kroitor** [comment]
> 'premium_index', 'premiumIndex' or 'premium-index' can be used as the value for key `price` in `fetchOHLCV` params.

What if we rename it to `premium` ?

**Comment by samgermain** [comment]
> > 'premium_index', 'premiumIndex' or 'premium-index' can be used as the value for key `price` in `fetchOHLCV` params.
> 
> What if we rename it to just `'premium'` ?

I don't think that's concise enough. Premium Index makes it obvious what it is, any examples should just use `premiumIndex` but I wanted to include all 3 to make it idiot proof, and make it easier for people to guess and not have to look at the docs

It accepts all 3 because of

```
if (price === 'premiumIndex' || price === 'premium_index' || price === 'premium-index')
```

even it we were to just make it premium, I still like `(price === 'premium' || price === 'premiumIndex' || price === 'premium_index' || price === 'premium-index')` better because it's easier to use and idiot proof

**Comment by samgermain** [comment]
do merge yet btw, I'm going to add `has: false` on other exchanges

**Comment by samgermain** [comment]
> > > 'premium_index', 'premiumIndex' or 'premium-index' can be used as the value for key `price` in `fetchOHLCV` params.
> > 
> > 
> > What if we rename it to just `'premium'` ?
> 
> I don't think that's concise enough. Premium Index makes it obvious what it is, any examples should just use `premiumIndex`, and this is what `fetchPremiumIndexOHLCV` uses, but I wanted to include all 3 to make it idiot proof, and make it easier for people to guess and not have to look at the docs
> 
> It accepts all 3 because of
> 
> ```
> if (price === 'premiumIndex' || price === 'premium_index' || price === 'premium-index')
> ```
> 
> even it we were to just make it premium, I still like `(price === 'premium' || price === 'premiumIndex' || price === 'premium_index' || price === 'premium-index')` better because it's easier to use and idiot proof

On that note, what if we switched the binance config options to accept 

```
"options": {
      "defaultType": "future"
    }
 ```
 
 or 
 
 ```
 "options": {
      "defaultType": "futures"
    }
```

This is common problem right?

It also doesn't make it easier that for kucoin it needs to be 

```
"options": {
      "type": "futures"
    }
```

**Comment by kroitor** [comment]
> This is common problem right?
> It also doesn't make it easier that for kucoin it needs to be

Yes, there should be no defaultType per se, we would like to unify contracts as described here: https://github.com/ccxt/ccxt/wiki/Manual#contract-naming-conventions

**Comment by frosty00** [comment]
> > > > 'premium_index', 'premiumIndex' or 'premium-index' can be used as the value for key `price` in `fetchOHLCV` params.
> > > 
> > > 
> > > What if we rename it to just `'premium'` ?
> > 
> > 
> > I don't think that's concise enough. Premium Index makes it obvious what it is, any examples should just use `premiumIndex`, and this is what `fetchPremiumIndexOHLCV` uses, but I wanted to include all 3 to make it idiot proof, and make it easier for people to guess and not have to look at the docs
> > It accepts all 3 because of
> > ```
> > if (price === 'premiumIndex' || price === 'premium_index' || price === 'premium-index')
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > even it we were to just make it premium, I still like `(price === 'premium' || price === 'premiumIndex' || price === 'premium_index' || price === 'premium-index')` better because it's easier to use and idiot proof
> 
> On that note, what if we switched the binance config options to accept
> 
> ```
> "options": {
>       "defaultType": "future"
>     }
> ```
> 
> or
> 
> ```
> "options": {
>      "defaultType": "futures"
>    }
> ```
> 
> This is common problem right?
> 
> It also doesn't make it easier that for kucoin it needs to be
> 
> ```
> "options": {
>       "type": "futures"
>     }
> ```

idk if we should have multiple aliases for this, since it's a slipperly slope, soon we will need multiple aliases for everything, which is why we should instead avoid them as much as possible. "premium" is pretty concise and doesn't require any aliases

**Comment by kroitor** [comment]
@samgermain i'd agree with @frosty00 on `'premium'` and aliases... otherwise we would have to bloat the code with too many variations of these slugs.

**Comment by samgermain** [comment]
> idk if we should have multiple aliases for this, since it's a slipperly slope, soon we will need multiple aliases for everything, which is why we should instead avoid them as much as possible. "premium" is pretty concise and doesn't require any aliases

but the thing it's describing is premiumIndex, calling it premium will require most people to look it up in the docs in order to find out how to get it, it requires more work of people

I'm going to ask reddit what the consensus is on whether this is a good practice

**Comment by kroitor** [comment]
> but the thing it's describing is premiumIndex, calling it premium will require most people to look it up in the docs in order to find out how to get it, it requires more work of people

There's no other mention of `premium` within Binance docs, except in the context of premium index.

> I'm going to ask reddit what the consensus is on whether this is a good practice

That would be great!

**Comment by samgermain** [comment]
@kroitor @frosty00 

Actually, do we have a unified way of naming params already? Maybe it would be better if we had a method on the Exchange class called `safeParam` or something, which converted snake_case and kebab-case to camelCase?

Then anyone could pass in parameters in what convention that their project is using

**Comment by kroitor** [comment]
@samgermain we are mostly unifying them with camelCase, and the general approach is to support both the exchange-specific parameter name and the camelcase unified name. Some of those params are already unified in some exchanges, like `clientOrderId`, `timeInForce` and `postOnly`. Others will be added as soon as possible. So, i think it makes sense to stick to camelCase in the unified API and in the unified params, and also support the exchange-specific names (regardless of their notation and syntax).

**Comment by kroitor** [comment]
We do prefer single words over multiple words, however, so i'm still not sure if `premium` is worse than `premiumIndex`, a public opinion would help.

**Comment by samgermain** [comment]
> We do prefer single words over multiple words, however, so i'm still not sure if `premium` is worse than `premiumIndex`, a public opinion would help.

In general I found there were too many synonyms in exchanges docs around this area, and terms that were similar (it took me a bit to discover that premium index, and index price were different) so I'd rather use the exact term

**Comment by kroitor** [comment]
Ok, I would then proceed with premiumIndex, but would remove the aliases. We better document the proper name, then let them guess.

**Comment by samgermain** [comment]
> don't merge yet btw, I'm going to add `has: false` on other exchanges

@kroitor This is done now, feel free to merge

**Pull request merged**
