### PR TITLE
bitmex - watchTicker & watchTickers & ws tests return

### PR DESCRIPTION
**Pull request by ttodua**
```
 npm run cli.js -- bitmex watchTickers  "['BTC/USDT:USDT','ETH/USDT:USDT']"         

> ccxt@4.2.50 cli.js
> node ./examples/js/cli.js bitmex watchTickers ['BTC/USDT:USDT','ETH/USDT:USDT']

2024-02-23T21:43:22.543Z
Node.js: v20.10.0
CCXT v4.2.50
bitmex.watchTickers (BTC/USDT:USDT,ETH/USDT:USDT)
{
  'BTC/USDT:USDT': {
    symbol: 'BTC/USDT:USDT',
    timestamp: 1708724603100,
    datetime: '2024-02-23T21:43:23.100Z',
    high: 51758.4,
    low: 50674.4,
    bid: 51079.7,
    ask: 51079.8,
    vwap: 51170.161,
    open: 51669.1,
    close: 51080,
    last: 51080,
    change: -589.1,
    percentage: -1.1401398514779626,
    average: 51374.55,
    baseVolume: 541.8070000000006,
    quoteVolume: 27724351.094100006,
    info: {
      symbol: 'XBTUSDT',
      rootSymbol: 'XBT',
      state: 'Open',
      typ: 'FFWCSX',
      listing: '2021-11-10T04:00:00.000Z',
      front: '2021-11-10T04:00:00.000Z',
      positionCurrency: 'XBT',
      underlying: 'XBT',
      quoteCurrency: 'USDT',
      underlyingSymbol: 'XBTT=',
      reference: 'BMEX',
      referenceSymbol: '.BXBTT',
      maxOrderQty: 1000000000,
      maxPrice: 1000000,
      lotSize: 1000,
      tickSize: 0.1,
      multiplier: 1,
      settlCurrency: 'USDt',
      underlyingToPositionMultiplier: 1000000,
      quoteToSettleMultiplier: 1000000,
      isQuanto: false,
      isInverse: false,
      initMargin: 0.01,
      maintMargin: 0.005,
      riskLimit: 1000000000000,
      riskStep: 1000000000000,
      taxed: true,
      deleverage: true,
      makerFee: -0.00015,
      takerFee: 0.00075,
      settlementFee: 0,
      fundingBaseSymbol: '.XBTBON8H',
      fundingQuoteSymbol: '.USDTBON8H',
      fundingPremiumSymbol: '.XBTUSDTPI8H',
      fundingTimestamp: '2024-02-24T04:00:00.000Z',
      fundingInterval: '2000-01-01T08:00:00.000Z',
      fundingRate: 0.000114,
      indicativeFundingRate: 0.0001,
      prevClosePrice: 51219.97,
      prevTotalVolume: 844521581000,
      totalVolume: 844524512000,
      volume: 2931000,
      volume24h: 541807000,
      prevTotalTurnover: '25556581447080200',
      totalTurnover: '25556731072007900',
      turnover: 149624927700,
      turnover24h: 27724351094100,
      homeNotional24h: 541.8070000000006,
      foreignNotional24h: 27724351.094100006,
      prevPrice24h: 51669.1,
      vwap: 51170.161,
      highPrice: 51758.4,
      lowPrice: 50674.4,
      lastPrice: 51080,
      lastPriceProtected: 51080,
      lastTickDirection: 'PlusTick',
      lastChangePcnt: -0.0114,
      bidPrice: 51079.7,
      midPrice: 51079.75,
      askPrice: 51079.8,
      impactBidPrice: 51079.7,
      impactMidPrice: 51081.15,
      impactAskPrice: 51082.683,
      hasLiquidity: true,
      openInterest: 309932000,
      openValue: 15825977133680,
      fairMethod: 'FundingRate',
      fairBasisRate: 0.12483000000000001,
      fairBasis: 4.57,
      fairPrice: 51062.74,
      markMethod: 'FairPrice',
      markPrice: 51062.74,
      indicativeSettlePrice: 51058.17,
      instantPnl: true,
      minTick: 0.01,
      timestamp: '2024-02-23T21:43:23.100Z'
    }
  }
}
```

```
npm run cli.js -- bitmex watchTicker 'ETH/USDT:USDT' 

> ccxt@4.2.50 cli.js
> node ./examples/js/cli.js bitmex watchTicker ETH/USDT:USDT

2024-02-23T21:44:06.040Z
Node.js: v20.10.0
CCXT v4.2.50
bitmex.watchTicker (ETH/USDT:USDT)
{
  symbol: 'ETH/USDT:USDT',
  timestamp: 1708724645734,
  datetime: '2024-02-23T21:44:05.734Z',
  high: 2995.69,
  low: 2907.59,
  bid: 2950.2,
  ask: 2950.21,
  vwap: 2954.0026,
  open: 2983.25,
  close: 2949.57,
  last: 2949.57,
  change: -33.68,
  percentage: -1.1289700829632112,
  average: 2966.41,
  baseVolume: 2190.659999999999,
  quoteVolume: 6471215.152399999,
  info: {
    symbol: 'ETHUSDT',
    ...
  }
}
```

### CODE REVIEW

**Comment by carlosmiei** [comment]
@ttodua the build fails consistently here, can u check it?

**Comment by ttodua** [comment]
> @ttodua the build fails consistently here, can u check it?

bitmex api is broken, I can confirm - https://i.imgur.com/x071EM2.png  OHLCV data is broken, `low` is above `open` in stream.
I'll skip that detail in tests, so it would pass. 
in implementation, i am not sure what to edit :)
I can manually "calculate" the low prices (find the lowest between o/h/l/c and overwrite `low` value with found lowest one), but i am not sure if that will be correct to edit the data provided by exchange.

**Comment by ttodua** [comment]
even on chart : https://www.bitmex.com/app/trade/XBT_USDT  it's visible: https://i.imgur.com/1Sm0GYL.png Open value being above high:) on the right side there is recent trades window, so by looking through it , you can conclude easily that their "open" value is synthetic - the last happened trade's price from previous bar  (which is outright incorrect to have that value as "open" value for the next bar if there happens trade on that next bar (only on bar where there is no trade, exchanges might place their o/h/l/c values same as last happened trade's value)

**Comment by ttodua** [comment]
so, i'll edit implementation to address the "open" price. it wont be absolutely correct, but at least will reduce the distortion. (i think I might set it to 'undefined')

**Comment by ttodua** [comment]
PR should be ready once travis finishes tests

**Pull request merged**
