### PR TITLE
Kucoin: update fetchOrderBook

### PR DESCRIPTION
**Pull request by DoctorSlimm**
as it stands, unauthenticated users cannot actually call fetchOrderBook unless they **specifically** supply the parameters : `limit: 100,  { level: 2}` otherwise an authentication error is thrown

- unauthenticated users call freely call fetchOrderBook now without issues
- authenticated users can now call the recommended full depth v3 orderbook endpoint

also: kucoin has no L3 orderbook endpoint so I removed the method

### CODE REVIEW

**Comment by dmh1974** [comment]
this appears to still be somewhat of a bug... as now authenticated users can no longer call the non-full depth (lv2_100) end-points from fetchOrderBook

**Comment by DoctorSlimm** [comment]
@dmh1974 thanks, will look into that shortly

**Comment by DoctorSlimm** [comment]
@dmh1974 you can still call the `lv2_100` endpoint by using implicit methods (and a kucoin specific marketId symbol) if you would like to, for example in node like this:

```JavaScript
const orderbook = kucoin.publicGetMarketOrderbookLevel2100 ({"symbol": "BTC-USDT"})
```

or in python 

```Python
orderbook = kucoin.publicGetMarketOrderbookLevel2100 ({"symbol": "BTC-USDT"})
```

**Comment by Matoran** [comment]
> @dmh1974 you can still call the `lv2_100` endpoint by using implicit methods (and a kucoin specific marketId symbol) if you would like to, for example in node like this:
> 
> ```js
> const orderbook = kucoin.publicGetMarketOrderbookLevel2100 ({"symbol": "BTC-USDT"})
> ```
> 
> or in python
> 
> ```python
> orderbook = kucoin.publicGetMarketOrderbookLevel2100 ({"symbol": "BTC-USDT"})
> ```

This won't give you a parsed order book. Will do a pull request to fix that. The private method should be called only if authenticated and limit is undefined.

**Pull request merged**
