### PR TITLE
use autoload on ccxt.php

### PR DESCRIPTION
**Pull request by silberbaum**
spl_autoload_register

### CODE REVIEW

**Comment by kroitor** [comment]
References: #633

**Comment by silberbaum** [comment]
is it good to merge? or is there a problem. i didnt see the earlier issues, sorry friendo

**Comment by kroitor** [comment]
Thank you! I've merged it already )

**Comment by silberbaum** [comment]
i will improve other areas using my godlike PHP knowledge

**Comment by kroitor** [comment]
@silberbaum woohoo! )

**Pull request merged**
