### PR TITLE
Update Hitbtc BTC deposit fee

### PR DESCRIPTION
**Pull request by adi90x**
BTC deposit fee is now 0.0006
Should be update for both exchange and should be dynamic in the future

### CODE REVIEW

**Comment by kroitor** [comment]
Hi! Can you please tell the source of info?

**Comment by adi90x** [comment]
https://hitbtc.com/account page under BTC deposit options, did not find any
API info... I will ask them if it is possible to add it maybe

**Comment by adi90x** [comment]
Quite strange that travis fail...

**Comment by kroitor** [comment]
Indeed...

screen shot 2018-01-17 at 15 11 25

screen shot 2018-01-17 at 15 11 34

The official announcement link points to https://blog.hitbtc.com/ and there's no official announcement there. They don't want us to find their reasons easily %)

**Pull request merged**
