### PR TITLE
binance.setMarginMode no need to set margin mode error squelch in python

### PR DESCRIPTION
**Pull request by samgermain**
The change on [this PR](https://github.com/ccxt/ccxt/pull/11821/files) only squelched the error in Javascript, it still shows up in Python, I think this might be a fix, but I'm not sure what else it would affect.

### CODE REVIEW

**Comment by kroitor** [comment]
Plz check linting on this PR: https://app.travis-ci.com/github/ccxt/ccxt/builds/246371047#L2086

**Comment by kroitor** [comment]
Unfortunately, this PR breaks the error handling cause it throws during handling an exception by calling `raise_for_status()` unconditionally. Let's try and fix it.

To reproduce:

```Python
import ccxt
exchange = ccxt.binance({
    'urls': {
        'api': {
            'public': 'https://api.binance.com/api/',  # set incorrect URL on purpose
        },
    },
})
markets = exchange.load_markets()
```

#### on `master` branch

```Python
~/ccxt/python $ python3
Python 3.8.2 (default, Apr  8 2021, 23:19:18)
[Clang 12.0.5 (clang-1205.0.22.9)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import ccxt
>>> exchange = ccxt.binance({
...     'urls': {
...         'api': {
...             'public': 'https://api.binance.com/api/',  # set incorrect URL on purpose
...         },
...     },
... })
>>> markets = exchange.load_markets()

Traceback (most recent call last):
  File "/Users/igorkroitor/ccxt/python/ccxt/base/exchange.py", line 659, in fetch
    response.raise_for_status()
  File "/Users/igorkroitor/Library/Python/3.8/lib/python/site-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.binance.com/api//exchangeInfo

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/igorkroitor/ccxt/python/ccxt/base/exchange.py", line 1489, in load_markets
    markets = self.fetch_markets(params)
  File "/Users/igorkroitor/ccxt/python/ccxt/binance.py", line 1372, in fetch_markets
    response = getattr(self, method)(query)
  File "/Users/igorkroitor/ccxt/python/ccxt/base/exchange.py", line 501, in inner
    return entry(_self, **inner_kwargs)
  File "/Users/igorkroitor/ccxt/python/ccxt/binance.py", line 4954, in request
    response = self.fetch2(path, api, method, params, headers, body, config, context)
  File "/Users/igorkroitor/ccxt/python/ccxt/base/exchange.py", line 548, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/Users/igorkroitor/ccxt/python/ccxt/base/exchange.py", line 677, in fetch
    self.handle_http_status_code(http_status_code, http_status_text, url, method, http_response)
  File "/Users/igorkroitor/ccxt/python/ccxt/base/exchange.py", line 713, in handle_http_status_code
    raise Exception(' '.join([self.id, method, url, string_code, http_status_text, body]))
ccxt.base.errors.ExchangeNotAvailable: binance GET https://api.binance.com/api//exchangeInfo 404 Not Found <html><body><h2>404 Not found</h2></body></html>
```

#### on `error-squelch-python` branch

```Python
~/ccxt/python $ python3
Python 3.8.2 (default, Apr  8 2021, 23:19:18)
[Clang 12.0.5 (clang-1205.0.22.9)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import ccxt
>>> exchange = ccxt.binance({
...     'urls': {
...         'api': {
...             'public': 'https://api.binance.com/api/',  # set incorrect URL on purpose
...         },
...     },
... })
>>> markets = exchange.load_markets()
Traceback (most recent call last):
  File "/Users/igorkroitor/ccxt/python/ccxt/base/exchange.py", line 672, in fetch
    json_response = self.handle_rest_response(response, url, method, request_headers, request_body)
  File "/Users/igorkroitor/ccxt/python/ccxt/base/exchange.py", line 640, in handle_rest_response
    response.raise_for_status()
  File "/Users/igorkroitor/Library/Python/3.8/lib/python/site-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.binance.com/api//exchangeInfo

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/igorkroitor/ccxt/python/ccxt/base/exchange.py", line 1504, in load_markets
    markets = self.fetch_markets(params)
  File "/Users/igorkroitor/ccxt/python/ccxt/binance.py", line 1372, in fetch_markets
    response = getattr(self, method)(query)
  File "/Users/igorkroitor/ccxt/python/ccxt/base/exchange.py", line 501, in inner
    return entry(_self, **inner_kwargs)
  File "/Users/igorkroitor/ccxt/python/ccxt/binance.py", line 4954, in request
    response = self.fetch2(path, api, method, params, headers, body, config, context)
  File "/Users/igorkroitor/ccxt/python/ccxt/base/exchange.py", line 548, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/Users/igorkroitor/ccxt/python/ccxt/base/exchange.py", line 688, in fetch
    skip_further_error_handling = self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "/Users/igorkroitor/ccxt/python/ccxt/binance.py", line 4885, in handle_errors
    if code >= 400:
TypeError: '>=' not supported between instances of 'NoneType' and 'int'
```

**Comment by samgermain** [comment]
@kroitor Do you have another idea for a solution? The problem I'm facing is that on freqtrade we've only programmed isolated margin_mode functionality, so before every trade, we are trying to set the margin_mode to isolated. We could catch the error and squelch it on freqtrade I guess. It's just that this isn't really an error, and it requires the user to either catch it and handle it, or to check the margin_mode before setting it, which requires another api call. It's just an unnecessary exception that requires users to put in more work

**Review by xmatthias — CHANGES_REQUESTED** [review]
@samgermain The problem @kroitor is pointing out happens because of the refactoring, not necessarily because of the "intended" change.

By moving the above code out of this method, `http_status_code` is initialized to `None` - and never changed again (in this context).
This means, we call `handle_errors()` with `http_status_code=None` - which causes a comparison error from within binance (code should not be None).

The same does happen for `http_response` and `http_status_text` too - they just don't raise an exception so far.

**Comment by kroitor** [comment]
@samgermain @xmatthias i'll try to fix this PR and will merge shortly, no need to change Freqtrade, we will intercept it properly in CCXT.

**Comment by samgermain** [comment]
Error handling for this error, so it should work as of version 1.74.31+ and by default it should not throw an exception, unless you enable the corresponding option, we will also need to fix the python handling for True returned from handleErrors

**Pull request closed without merging**
