### PR TITLE
coinex: v2, add endpoints, adjust sign

### PR DESCRIPTION
**Pull request by Dan-krm**
Added the v2 endpoints to coinex and adjusted sign to accomodate public and private v2 endpoints

https://docs.coinex.com/api/v2/rate-limit

### CODE REVIEW

**Comment by carlosmiei** [comment]
@Dan-krm you need to adjust the static tests we well, can you do that?

**Comment by Dan-krm** [comment]
> @Dan-krm you need to adjust the static tests we well, can you do that?

@carlosmiei I fixed the error with a fetchPositions static request that is calling an alternative v1 method. This PR should be good now, I can update the static request tests as I go through and update each individual method after this PR is merged

**Comment by carlosmiei** [comment]
@Dan-krm but aren't the current tests going to fail? We can't merge if the static tests are broken because that would break the build as a whole

**Comment by carlosmiei** [comment]
Ok they passed, all good then

**Comment by carlosmiei** [comment]
```
 n coinex v2PublicGetPing                                              
Debugger attached.
2024-03-28T11:34:46.058Z
Node.js: v20.7.0
CCXT v4.2.84
coinex.v2PublicGetPing ()
2024-03-28T11:34:47.450Z iteration 0 passed in 271 ms

{ code: '0', data: { result: 'pong' }, message: 'OK' }
2024-03-28T11:34:47.450Z iteration 1 passed in 271 ms
```

**Pull request merged**
