### PR TITLE
add bitget.com

### PR DESCRIPTION
**Pull request by BitgetLimited**
#6862 
New Exchange: bitget.com

### CODE REVIEW

**Comment by BitgetLimited** [comment]
@kroitor 
Hello, please handle our submission request as soon as possible, thank you

**Comment by kroitor** [comment]
@BitgetLimited it won't work in Python and PHP, since base classes are not transpiled:

- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#multilanguage-support
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#transpiled-generated-files

**Comment by BitgetLimited** [comment]
@kroitor  
hi There was a problem with the original encryption method, and now it has been adjusted and a new PR is submitted #7203

**Comment by kroitor** [comment]
@BitgetLimited understood, thx!

**Pull request closed without merging**
