### PR TITLE
Indodax: fix error handling

### PR DESCRIPTION
**Pull request by brandsimon**
Reproducible:
```
exchange = ccxt.indodax()
exchange.load_markets()
exchange.fetch_trades('BCH/IDR', 123)
```

### CODE REVIEW

**Comment by brandsimon** [comment]
I am not sure, that this wont break anything. Their API seams to have a lot of possible return values.

**Comment by kroitor** [comment]
```
mbp:ccxt igorkroitor$ node examples/js/cli indodax fetchTrades BCH/IDR 123 --verbose
indodax.fetchTrades (BCH/IDR, 123)
fetch:
 indodax GET https://indodax.com/api/bch_idr/trades
Request:
 {}
 undefined

handleRestResponse:
 indodax GET https://indodax.com/api/bch_idr/trades 200 OK
Response:
 {
  'Access-Control-Allow-Origin': '',
  'Cf-Ray': '4f893fb20f95d6dd-FRA',
  Connection: 'close',
  'Content-Encoding': 'gzip',
  'Content-Type': 'application/json',
  Date: 'Fri, 19 Jul 2019 02:26:09 GMT',
  'Expect-Ct': 'max-age=604800, ' +
    'report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"',
  Server: 'cloudflare',
  'Set-Cookie': '__cfduid=d4196492c786078b7b61cc4e9795fbdba1563503168; expires=Sat, ' +
    '18-Jul-20 02:26:08 GMT; path=/; domain=.indodax.com; HttpOnly; ' +
    'Secure',
  'Strict-Transport-Security': 'max-age=31536000; includeSubDomains; preload',
  'Transfer-Encoding': 'chunked',
  V: '2',
  'X-Content-Type-Options': 'nosniff',
  'X-Powered-By': 'INDODAX',
  'X-Served-By': 'PA5'
}
 {"error":"invalid_pair","error_description":"Invalid Pair"}

[]
0 objects
mbp:ccxt igorkroitor$
```

**Comment by brandsimon** [comment]
@kroitor 
Please try python

**Comment by kroitor** [comment]
I will rewrite this for a unified `handleErrors`, like we do in most other exchanges:

- https://github.com/ccxt/ccxt/blob/master/js/bitfinex.js#L311
- https://github.com/ccxt/ccxt/blob/master/js/bitfinex.js#L1165

```
mbp:ccxt igorkroitor$ python examples/py/cli.py indodax fetchTrades BCH/IDR 123 --verbose
('\nRequest:', 'GET', 'https://indodax.com/api/bch_idr/trades', {'Accept-Encoding': 'gzip, deflate', 'User-Agent': 'python-requests/2.18.4'}, None)
('\nResponse:', 'GET', 'https://indodax.com/api/bch_idr/trades', 200, {'Expect-CT': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"', 'X-Served-By': 'PA5', 'X-Content-Type-Options': 'nosniff', 'X-Powered-By': 'INDODAX', 'Transfer-Encoding': 'chunked', 'Set-Cookie': '__cfduid=d9bc150eb04940d7880c2723f31d0d88a1563503344; expires=Sat, 18-Jul-20 02:29:04 GMT; path=/; domain=.indodax.com; HttpOnly; Secure', 'Strict-Transport-Security': 'max-age=31536000; includeSubDomains; preload', 'Server': 'cloudflare', 'Connection': 'keep-alive', 'v': '2', 'Date': 'Fri, 19 Jul 2019 02:29:05 GMT', 'Access-Control-Allow-Origin': '', 'Content-Type': 'application/json', 'CF-RAY': '4f8943fe0e2ac29a-FRA', 'Content-Encoding': 'gzip'}, u'{"error":"invalid_pair","error_description":"Invalid Pair"}')
[]
mbp:ccxt igorkroitor$
```

**Comment by kroitor** [comment]
@brandsimon 

> Please try python

Yep, just tried it ) You can check yourself with the `cli` script – it's very handy when it comes to debugging, or calling a specific method with specific args. No need to write new code to test essential calls. 

- https://github.com/ccxt/ccxt/blob/master/examples/js/cli.js
- https://github.com/ccxt/ccxt/blob/master/examples/py/cli.py
- https://github.com/ccxt/ccxt/blob/master/examples/php/cli.php

**Comment by brandsimon** [comment]
@kroitor 
Thank you very much, I like the cli!
```
 $ python3 examples/py/cli.py indodax fetchTrades BCH/IDR 123
Traceback (most recent call last):
  File "examples/py/cli.py", line 126, in <module>
    result = method(*args)
  File "/usr/lib/python3/dist-packages/ccxt/indodax.py", line 215, in fetch_trades
    return self.parse_trades(response, market, since, limit)
  File "/usr/lib/python3/dist-packages/ccxt/base/exchange.py", line 1464, in parse_trades
    return self.filter_by_symbol_since_limit(array, symbol, since, limit)
  File "/usr/lib/python3/dist-packages/ccxt/base/exchange.py", line 1509, in filter_by_symbol_since_limit
    return self.filter_by_value_since_limit(array, 'symbol', symbol, since, limit)
  File "/usr/lib/python3/dist-packages/ccxt/base/exchange.py", line 1503, in filter_by_value_since_limit
    array = [entry for entry in array if entry['timestamp'] >= since]
  File "/usr/lib/python3/dist-packages/ccxt/base/exchange.py", line 1503, in <listcomp>
    array = [entry for entry in array if entry['timestamp'] >= since]
TypeError: '>=' not supported between instances of 'NoneType' and 'int'
```

**Comment by kroitor** [comment]
@brandsimon this is strange, can't reproduce the above on my side... which version of CCXT is it?

**Comment by kroitor** [comment]
@brandsimon ah, pardon, reproduced it with Python3 (was checking v2 before). Will fix that as well.

**Comment by kroitor** [comment]
@brandsimon thx to your report we found another inconsistency in py2 vs py3:

```
mbp:ccxt igorkroitor$ python
Python 2.7.10 (default, Feb 22 2019, 21:55:15)
[GCC 4.2.1 Compatible Apple LLVM 10.0.1 (clang-1001.0.37.14)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> None > 1
False
```
```
mbp:ccxt igorkroitor$ python3
Python 3.7.2 (v3.7.2:9a3ffc0492, Dec 24 2018, 02:44:43)
[Clang 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> None > 1
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: '>' not supported between instances of 'NoneType' and 'int'
```

That's why it fails to crash in py2, and it crashes in py3... Going to add the workarounds to the base code and the indodax implementation shortly.

**Comment by kroitor** [comment]
@brandsimon I hope you don't mind that we will throw a BadRequest exception in this case: https://indodax.com/api/bch_idr/trades. This is an error on the exchange side, because the market itself is present on their website: https://indodax.com/market/BCHIDR

**Comment by brandsimon** [comment]
@kroitor 
I dont mind. I checked out upstream master before reporting this. Glad to hear it is fixed :) Thank you!

**Pull request merged**
