### PR TITLE
Better PSR-4 support

### PR DESCRIPTION
**Pull request by darthf1**
- Added PSR-4 support in composer.json
- Moved files in Base folder to same folder as the other files
- Removed include_once statements
- Removed ?> file endings in .php files

Needs testing, and php examples need to be updated as well.

### CODE REVIEW

**Comment by kroitor** [comment]
Oh )) You should've read https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md first, as I told you ) Those files are generated, so if even if you change 98 of them, most of them will be overwritten upon build. So we just need to change the generation function here: https://github.com/ccxt/ccxt/blob/master/transpile.js. But don't worry, I'll do it properly. Thank you again for your involvement!

**Comment by darthf1** [comment]
Oh i missed that, was already changing the code.

Would be great if you can fix it in the generation function.

**Comment by kroitor** [comment]
Also, I'm not sure why you deleted the php/base/Exchange.php and php/base/errors.php. Can you explain this change, please? I may be misunderstanding something. Sorry for bothering you. And thanks again.

**Comment by darthf1** [comment]
I moved the files from php/base to php/.

All the files have the same namespace, so they are expected to be in the same folder.

**Comment by kroitor** [comment]
@darthf1 oh, I see... missed that somehow. Thanks for the clarification!
My last question is about including it in non-Composer environments, do we lose it and become Composer-only from here? Or it does not affect native PHP in any way?

**Comment by darthf1** [comment]
Not sure about that, I only use composer in my projects.

**Comment by kroitor** [comment]
@darthf1 got it, thanks again. Will do some more testing on my side and will merge this very soon.

**Comment by kroitor** [comment]
Ref: #862

**Comment by thijstriemstra** [comment]
> Oh-Oh )) You should've read https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md first, as I told you ) Those files are generated, so if even if you change 98 of them, most of them will be overwritten upon build.

I had the same realization when I first contributed, perhaps it should be made really really clear you're transpiling the code into multiple languages.

**Comment by kroitor** [comment]
@thijstriemstra we tried, however... seems like we didn't succeed very much, people still tend to edit their favourite language first )

screen shot 2017-12-19 at 01 40 28

screen shot 2017-12-19 at 01 41 10

screen shot 2017-12-19 at 01 41 55

The above notices didn't help, obviously... Can you suggest some edits on this? We'd love to make it really clear! Your contributions are welcome!

**Comment by thijstriemstra** [comment]
I'll open a PR to show what I mean :)

**Comment by kroitor** [comment]
> The transpiling is mentioned near the bottom of the docs

To be precise, it is near the bottom of README for **all** users, and it is right the middle of instructions for **contributors**... However, I agree, this might not be obvious enough for all contributors. I guess, I'm just projecting what I would do before submitting any code to any public library – I'd read the docs and click the Contributing link beforehand. In other words, if a developer doesn't have a habit to read first, then I'm afraid, even if I rename the whole repo to "This whole code is transpiled" in caps bold – they will miss it %) Yet I will be happy to merge any enhancements to the docs that would make it clear.

**Comment by thijstriemstra** [comment]
The fact is transpiled is smart but people should know about it because contributors end up wasting time realizing later that everything's generated and not static code for their fav language.

**Comment by kroitor** [comment]
@thijstriemstra I agree, absolutely, just having difficulty keeping up with the amount of work needed to polish all aspects of it, including the docs... I really appreciate your advice and your participation!

**Pull request merged**
