### PR TITLE
Fix: HuobiPro should be "huobipro.com" instead of "huobi.pro"

### PR DESCRIPTION
**Pull request by winkidney**
Hi,
Thanks for your great work on `ccxt`.

"huobipro.com" couldn't be access in some area of china(for example Guangdong) for now.
"ping" command for huobi.pro doesn't work.

So I use the new hostname for huobi's api.

If this PR works well, please issue a new release on `PYPI`.

More details about the issue:

Output of library of python version.
```python
ccxt.base.errors.RequestTimeout: huobipro GET https://api.huobi.pro/v1/common/symbols HTTPSConnectionPool(host='api.huobi.pro', port=443): Max retries exceeded with url: /v1/common/symbols (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f312d426710>, 'Connection to api.huobi.pro timed out. (connect timeout=10)'))
```

Ping command from Guangdong, China:

```shell
ping api.huobi.pro
PING api.huobi.pro (31.13.83.8) 56(84) bytes of data.
^C
--- api.huobi.pro ping statistics ---
5 packets transmitted, 0 received, 100% packet loss, time 4017ms
```

### CODE REVIEW

**Comment by kroitor** [comment]
Thanks for the contribution! You don't have to edit the docs, however, as those are generated automatically, we only need to submit just a single JS file to bring the changes into effect.
More about it: https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

Thx again!

**Comment by winkidney** [comment]
@kroitor Thanks for your tips about contribution. 
I noticed that there is no expectation described in contribution-guide.

Directories listed below is from the guide.
```
/doc/*
/build/*
/php/* (except for base classes)
/python/* (except for base classes)
```
It seems that `wiki` and `readme.md` is not listed there?

So if I only change the the js file, will the change take effect automatically in wiki and readme?

**Comment by kroitor** [comment]
> So if I only change the the js file, will the change take effect automatically in wiki and readme?

Yes, after a successful build and merge, the changes will be automatically propagated to the wiki and to the readme, all URLs are taken from the JS file itself.

**Comment by kroitor** [comment]
> I noticed that there is no expectation described in contribution-guide.
> It seems that wiki and readme.md is not listed there?

That doc itself it a work in progress as well, so, if you find some info missing there that you think should be there, then feel free to submit edits to it to include the necessary details based on your experience. We will be happy for any assistance in building a better and more understandable documentation. Thx ;)

**Pull request merged**
