### PR TITLE
 parse_timeframe: dont allow wrong unit 

### PR DESCRIPTION
**Pull request by brandsimon**
I dont think, we should accept wrong values and just assume minutes are meant.

### CODE REVIEW

**Comment by brandsimon** [comment]
Sorry, I had an issue in php. I am not used to using php.

**Comment by kroitor** [comment]
@brandsimon thx, great to hear from you ) 

> Sorry, I had an issue in php. I am not used to using php.

No worries, I'll look into it upon merging if needed. Will get to it shortly. Thx again)

**Comment by brandsimon** [comment]
I tested it and it worked, but apparently, using `+` for string concatenation is wrong, probably the language should throw on this.

**Comment by kroitor** [comment]
@brandsimon yep, unfortunately, it's type agnostic when it comes to concatenation, that's the reason for having this rule in our guides:

- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#adding-numbers-and-concatenating-strings

) Thx for the fixup! Will test on my side and will merge asap!

**Comment by brandsimon** [comment]
@kroitor 
my php version also shows a warning when using + for strings:
`PHP Warning:  A non-numeric value encountered in test.php on line 1`
Which I had overseen when making the PR.

**Comment by brandsimon** [comment]
@kroitor Great, thanks for merging :)

**Pull request merged**
