### PR TITLE
update allcoin's load markets with new URI

### PR DESCRIPTION
**Pull request by bugking**
* old uri doesn't work anymore, always timeout error
 * web uri 'allcoin.com' sometime won't respond, but 'www.allcoin.com'
   always responds

### CODE REVIEW

**Comment by bugking** [comment]
Sorry, I messed up my previous branch. please decline my old pull request.

**Comment by kroitor** [comment]
Awesome! Thank you very much for the edits! Will merge shortly!

**Comment by bugking** [comment]
I just found some indents issue after review the pull request, do you want me to fix them? @kroitor

**Comment by kroitor** [comment]
@bugking if you can, please, go for it, however, it's totally up to you... you would save me a few moments, but I don't mind cleaning the rest of it, no worries at all.

**Comment by bugking** [comment]
done

**Pull request merged**
