### PR TITLE
Bit2c - added support for 'fetchMyTrades'

### PR DESCRIPTION
**Pull request by JacobHanouna**
added new support for fetchMyTrades in bit2c exchange.
support included also a parse trade method (which was needed also for fetchTrades)

code was developed and tested in python.
and was committed also just as a reference to the code solution.

I'm not a js developer and couldn't really make the whole npm process work (really spent a lot of time)!
js code was committed but should be treated like a skeleton code that need be finished.
I believe most of it is ready.
some parts are commented as this is python code that need to be converted to js

sorry for the overhead but js is really not my thing

### CODE REVIEW

**Comment by kroitor** [comment]
https://github.com/ccxt/ccxt/wiki/Manual#how-orders-are-related-to-trades

**Comment by JacobHanouna** [comment]
not sure I understand why you have ref me to that section.

'Orderhistory' entery in bit2c API is a bit misleading as it is more trade history 
https://bit2c.co.il/home/api

all I did was getting all past trade and return them

**Comment by kroitor** [comment]
@JacobHanouna it's ok, was just a reminder for myself to check on that, but, you're right, it's a trade list, not an order list, everything is great, will merge asap. Thank you!

**Comment by JacobHanouna** [comment]
I also spoke with the exchange developers team and they will make in the near future a few changes. so will update the code when it will be available

**Pull request merged**
