### PR TITLE
Binance fetchCurrencies option set to true

### PR DESCRIPTION
**Pull request by petardudas**
If the fetchCurrencies property in the options has a false value, the fetchCurrencies function returns undefined. It need to be set to true because it's private call and options are needed to sign the call.

### CODE REVIEW

**Comment by kroitor** [comment]
Hi! Thanks for your involvement! We appreciate your help!
Unfortunately, we will not merge this PR, since that option is set to `false` by default on purpose – not all users will supply the apiKey credentials, some users only use public APIs. Enabling that option would break the unauthenticated anonymous usage of the exchange and the lib. Let us know if you have further questions. Closing it for now.

**Comment by kroitor** [comment]
Actually, on a second thought, I will edit it a bit to work automatically (will probably remove that option completely), and will merge it soon.

**Comment by petardudas** [comment]
Please take look at this: 
https://binance-docs.github.io/apidocs/spot/en/#all-coins-39-information-user_data
It's a user wallet endpoint and it has to be signed.

**Comment by kroitor** [comment]
@petardudas yep, i've merged this PR, thanks.

**Pull request merged**
