### PR TITLE
Settlements

### PR DESCRIPTION
**Pull request by samgermain**
This is just a draft because it mixes a lot. It looks like few exchanges have a swap settlement history, but many provide future and option settlement history. I'm wondering if huobi is incorrectly naming the swap settlement history and if it should be something else.

for future and option, I've come up with 

- fetchSettlements (private settlement history specific to an account)
- fetchSettlementHistory (public)

I've combined the parser for both of them, let me know if I should separate them

### CODE REVIEW

**Comment by samgermain** [comment]
@Dan-krm Review the parser please, and let me know if you know anything about if huobi is incorrectly naming swap settlements

**Comment by samgermain** [comment]
ftx.fetchSettlementHistory is hard to test, because it requires an expired future contract, but I can only get active contracts from fetchMarkets

**Review by Dan-krm — APPROVED** [review]
Everything looks okay to me. The settlement price can be calculated in various ways and vary for different types of derivatives and exchanges. It might get confusing mixing options in with delivery and perpetual futures for these methods since they behave quite differently in regards to settlement.

I think a strike key would make sense for options, it seems like the options endpoints don't keep track of the actual entry price and setting the entry price to the strike price for options would be confusing and inaccurate. FTX returns a strike price for their MOVE futures and it looks like it's actually the open price, not the same as an options strike price.

Maybe a type key would make sense for telling if the settlement was from an expiration/delivery, exercise, or just a general settlement marking the value of an open derivatives contract. I think that would help clear some confusion with these methods.

**Comment by Dan-krm** [comment]
> I'm wondering if huobi is incorrectly naming the swap settlement history and if it should be something else.

Perpetual futures are always 'cash settled', but delivery futures can settle with physical delivery of the underlying asset at the expiry date. So it makes sense that Huobi has a swap settlement history endpoint. A settlementType key that could be expiry, exercised or cash settled might be good to have.

**Comment by samgermain** [comment]
> > I'm wondering if huobi is incorrectly naming the swap settlement history and if it should be something else.
> 
> Perpetual futures are always 'cash settled', but delivery futures can settle with physical delivery of the underlying asset at the expiry date. So it makes sense that Huobi has a swap settlement history endpoint. A settlementType key that could be expiry, exercised or cash settled might be good to have.

@Dan-krm It sounds like you might have a better understanding of this than I do. If this is a PR you would like to take over then feel free to do that. I don't have any plans to look at it any time in the near future

**Comment by samgermain** [comment]
@Dan-krm I'm going to close this PR because I don't have any intentions of working on it anytime soon. Feel free to take it over if you want.

**Pull request closed without merging**
