### PR TITLE
fix(waves) - createOrder params

### PR DESCRIPTION
**Pull request by ttodua**
add `defaultExpiry` and params extension

### CODE REVIEW

**Comment by carlosmiei** [comment]
@ttodua is it possible to add a static test?

**Comment by ttodua** [comment]
> @ttodua is it possible to add a static test?

iirc, we don't support static tests with multi-request method (in waves createOrder there are chain of endpoints called till last one which places order)

**Comment by ttodua** [comment]
anyway, i'll recheck, will regenerated and run static tests with new item

**Comment by carlosmiei** [comment]
> > @ttodua is it possible to add a static test?
> 
> iirc, we don't support static tests with multi-request method (in waves createOrder there are chain of endpoints called till last one which places order)

@ttodua yes we don't I forgot waves requires multiple reqs.

**Pull request merged**
