### PR TITLE
coinex - `fetchDepositWithdrawFees()`

### PR DESCRIPTION
**Pull request by AlgoQ**
# Testing
## Python
```
Python v3.10.6
CCXT v2.4.71
coinex.fetchDepositWithdrawFees(['BTC', 'USDT'])
{'BTC': {'deposit': {'fee': None, 'percentage': None},
         'info': {'BTC': {'asset': 'BTC',
                          'can_deposit': True,
                          'can_withdraw': True,
                          'chain': 'BTC',
                          'deposit_least_amount': '0.001',
                          'withdraw_least_amount': '0.001',
                          'withdraw_tx_fee': '0.0001',
                          'withdrawal_precision': '8'}},
         'networks': {},
         'withdraw': {'fee': '0.0001', 'percentage': False}},
 'USDT': {'deposit': {'fee': None, 'percentage': None},
          'info': {'USDT-BSC': {'asset': 'USDT',
                                'can_deposit': True,
                                'can_withdraw': True,
                                'chain': 'BSC',
                                'deposit_least_amount': '0.83',
                                'withdraw_least_amount': '0.83',
                                'withdraw_tx_fee': '0.83',
                                'withdrawal_precision': '8'},
                   'USDT-CSC': {'asset': 'USDT',
                                'can_deposit': True,
                                'can_withdraw': True,
                                'chain': 'CSC',
                                'deposit_least_amount': '0.015',
                                'withdraw_least_amount': '0.6',
                                'withdraw_tx_fee': '0.015',
                                'withdrawal_precision': '8'},
                   'USDT-ERC20': {'asset': 'USDT',
                                  'can_deposit': True,
                                  'can_withdraw': True,
                                  'chain': 'ERC20',
                                  'deposit_least_amount': '3.5',
                                  'withdraw_least_amount': '3.5',
                                  'withdraw_tx_fee': '3.5',
                                  'withdrawal_precision': '6'},
                   'USDT-TRC20': {'asset': 'USDT',
                                  'can_deposit': True,
                                  'can_withdraw': True,
                                  'chain': 'TRC20',
                                  'deposit_least_amount': '0.66',
                                  'withdraw_least_amount': '0.66',
                                  'withdraw_tx_fee': '0.66',
                                  'withdrawal_precision': '6'}},
          'networks': {'BSC': {'deposit': {'fee': None, 'percentage': None},
                               'withdraw': {'fee': '0.83',
                                            'percentage': False}},
                       'CSC': {'deposit': {'fee': None, 'percentage': None},
                               'withdraw': {'fee': '0.015',
                                            'percentage': False}},
                       'ERC20': {'deposit': {'fee': None, 'percentage': None},
                                 'withdraw': {'fee': '3.5',
                                              'percentage': False}},
                       'TRC20': {'deposit': {'fee': None, 'percentage': None},
                                 'withdraw': {'fee': '0.66',
                                              'percentage': False}}},
          'withdraw': {'fee': None, 'percentage': None}}}
```

### CODE REVIEW

**Comment by hosseinab** [comment]
hi @carlosmiei . please check this PR

**Comment by carlosmiei** [comment]
> hi @carlosmiei . please check this PR

Hello @hosseinab, it needs to be updated because we decided to go with a slightly different approach, but I'll sync with @AlgoQ.

**Comment by hosseinab** [comment]
@carlosmiei thank you
i get the withdraw fee from the currencies, often time loaded withdraw fee is incorrect .
I am going to try load withdraw fee from this link : https://www.coinex.com/res/wallet/fee
I will let you know after trying this

**Comment by carlosmiei** [comment]
LGTM ✅ 

```
p coinex fetchDepositWithdrawFees '["USDT"]'
Python v3.10.8
CCXT v2.4.71
coinex.fetchDepositWithdrawFees(['USDT'])
{'USDT': {'deposit': {'fee': None, 'percentage': None},
          'info': {'USDT-BSC': {'asset': 'USDT',
                                'can_deposit': True,
                                'can_withdraw': True,
                                'chain': 'BSC',
                                'deposit_least_amount': '0.83',
                                'withdraw_least_amount': '0.83',
                                'withdraw_tx_fee': '0.83',
                                'withdrawal_precision': '8'},
                   'USDT-CSC': {'asset': 'USDT',
                                'can_deposit': True,
                                'can_withdraw': True,
                                'chain': 'CSC',
                                'deposit_least_amount': '0.015',
                                'withdraw_least_amount': '0.6',
                                'withdraw_tx_fee': '0.015',
                                'withdrawal_precision': '8'},
                   'USDT-ERC20': {'asset': 'USDT',
                                  'can_deposit': True,
                                  'can_withdraw': True,
                                  'chain': 'ERC20',
                                  'deposit_least_amount': '3',
                                  'withdraw_least_amount': '3',
                                  'withdraw_tx_fee': '3',
                                  'withdrawal_precision': '6'},
                   'USDT-TRC20': {'asset': 'USDT',
                                  'can_deposit': True,
                                  'can_withdraw': True,
                                  'chain': 'TRC20',
                                  'deposit_least_amount': '0.65',
                                  'withdraw_least_amount': '0.65',
                                  'withdraw_tx_fee': '0.65',
                                  'withdrawal_precision': '6'}},
          'networks': {'BSC': {'deposit': {'fee': None, 'percentage': None},
                               'withdraw': {'fee': '0.83',
                                            'percentage': False}},
                       'CSC': {'deposit': {'fee': None, 'percentage': None},
                               'withdraw': {'fee': '0.015',
                                            'percentage': False}},
                       'ERC20': {'deposit': {'fee': None, 'percentage': None},
                                 'withdraw': {'fee': '3', 'percentage': False}},
                       'TRC20': {'deposit': {'fee': None, 'percentage': None},
                                 'withdraw': {'fee': '0.65',
                                              'percentage': False}}},
          'withdraw': {'fee': None, 'percentage': None}}}

**Review by carlosmiei — APPROVED** [review]

**Comment by hosseinab** [comment]
hello @AlgoQ . this function returns the same data from currencies object ?

**Pull request merged**
