### PR TITLE
Update bitfinex2.py

### PR DESCRIPTION
**Pull request by blackstock**
Additional ledger endpoint: https://docs.bitfinex.com/v2/reference#ledgers (similar to existing endpoint, but without `Symbol`)

### CODE REVIEW

**Comment by kroitor** [comment]
Hi) Can you please move this edit to the .js file? ) 

- https://github.com/ccxt/ccxt/pull/5024/files#diff-3439456de6d649e4111c4edd318e0567R3
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#multilanguage-support

**Comment by kroitor** [comment]
No worries, i've moved the endpoint, will merge shortly.

**Comment by blackstock** [comment]
@kroitor You beat me to it :P Thanks and I just read the docs for future contributions . Great work with CCXT 👍

**Comment by kroitor** [comment]
@blackstock thx again for your involvement, looking forward! )

**Pull request merged**
