### PR TITLE
New Exchange: HBTC

### PR DESCRIPTION
**Pull request by tufei8438**
our brand has changed from bhex to hbtc.

### CODE REVIEW

**Comment by tangfl** [comment]
@kroitor  please reply my email when this work start

**Comment by kroitor** [comment]
@tangfl we are already working on, i've sent you an email yesterday, resent again today. I will keep you updated on our progress. Thx! 👍

**Comment by tangfl** [comment]
Got the email
Thx 
mail me if anything you need from our side

**Comment by tufei8438** [comment]
@kroitor 

I did not find the definition of this function: throwExactlyMatchedException
if test createOrder return error code, would cause exception:

**Comment by kroitor** [comment]
> I did not find the definition of this function: throwExactlyMatchedException

It is in place, though (and it works with all other exchanges and it works when i test against an updated repository locally):

- https://github.com/ccxt/ccxt/blob/master/js/base/Exchange.js#L541
- https://github.com/ccxt/ccxt/blob/master/python/ccxt/base/exchange.py#L481
- https://github.com/ccxt/ccxt/blob/master/php/base/Exchange.php#L1195

It just means that your fork of the repository has very old base classes. So you want to update your branch to the current master. I've been testing the implementation against the master branch. 

The HBTC implementation will be built against the master branch anyway upon merging. So, you want to update the other files in your branch to the current master if you want to test it on your side.

> And i has pushed two commits:

Both commits are good, thank you!

**Comment by kroitor** [comment]
@tufei8438 

> update your branch to the current master

Let me know if you have difficulties with that.

**Comment by tufei8438** [comment]
@kroitor We will test after merging from master branch. thanks very much.

**Comment by tufei8438** [comment]
> @kroitor We will test after merging from master branch. thanks very much.

We have merged from master branch and finished the tests, thanks.

**Comment by tangfl** [comment]
@kroitor  It looks good to us now, and can be merged

Thanks for your great job

**Comment by kroitor** [comment]
@tufei8438 @tangfl HBTC has been merged in CCXT 1.27.36+. Thank you for your involvement!

**Pull request merged**
