### PR TITLE
new exchange: tradesatoshi #763 (work in progress)

### PR DESCRIPTION
**Pull request by kroitor**

### CODE REVIEW

**Comment by kroitor** [comment]
Related to #763

**Comment by zakstack** [comment]
@kroitor Just Incase you are running into the same error I was in your development; It seems that the private API is currently disabled. All attempts to post are refused.

**Comment by kroitor** [comment]
@zakstack yep, this is still a work in progress (not completed), as mentioned in the referenced issue. I uploaded it to satisfy a request from a user who showed interest in it. Thx!

**Comment by crackfoo** [comment]
api addresses are listed as bittrex's:

+                'api' => array (
+                    'public' => 'https://bittrex.com/api',
+                    'account' => 'https://bittrex.com/api',
+                    'market' => 'https://bittrex.com/api',
+                    'v2' => 'https://bittrex.com/api/v2.0/pub',
+                ),

**Comment by crypto-maniac** [comment]
hello guys, any update on this new ccxt adapter please?
thanks you very much

**Comment by Nathapon8899** [comment]
#763

**Comment by xCuri0** [comment]
@kroitor @crypto-maniac @crackfoo i have done a very basic implementation for tradesatoshi (only orderbook and tickers/markets work)

**Comment by crypto-maniac** [comment]
Thank you xCuri0 , its a good start thanks you very much!

**Comment by crypto-maniac** [comment]
xCuri0  please share , my dev will help on this one , he's already working to fix some exchanges

**Comment by xCuri0** [comment]
@crypto-maniac ok will

**Comment by crackfoo** [comment]
Just wondering if this will get pushed out soon?

Thanks!

**Comment by kroitor** [comment]
@crackfoo https://github.com/ccxt/ccxt/wiki/FAQ#when-will-you-add-feature-foo-for-exchange-bar--whats-the-estimated-time-when-should-we-expect-this ;)

**Comment by kroitor** [comment]
https://github.com/ccxt/ccxt/issues/1576#issuecomment-604736399

**Pull request closed without merging**
