### PR TITLE
Fix when an order fills immediately, 'filled' should be set to the amount.

### PR DESCRIPTION
**Pull request by payala**
When an order is immediately filled, the current behaviour is to set the orders 'filled' attribute to None. 

IMO it makes more sense, since we know that it filled completely to set 'filled' to the 'amount' value.

### CODE REVIEW

**Comment by payala** [comment]
Maybe it's not so easy. Some cases that I'm thinking about:

1. If the order fills partially, would we receive 'OrderId' and also 'FilledOrders' in the response?. If so, it might be better to set 'filled' to 'amount' only when we don't receive an 'OrderId' in the response. The API is quite bad, and the API doc is very unclear.

2. In the case of immediate complete fill, the status is still not accurate, since it is always 'open', and it should actually be 'closed'.

**Comment by kroitor** [comment]
> And, I see that a test is failing...

The test failure is actually not related to this PR – it's an issue with another endpoint of Cryptopia – they will return erroneous responses occasionally... 

But you're absolutely right, the order can be filled partially and we should expect OrderId and a list of filling trades. On the status – you're correct as well.

**Comment by payala** [comment]
OK, thanks, it's good to know about the failing tests, I was really not seeing how that could be related with this PR.

I'll try to make a better fix that covers these cases and include them here.

**Comment by payala** [comment]
OK, there's a small twist in here.

So, now it should only be set as closed on a complete fill, setting both 'status' and 'filled' correctly.

On a partial fill, the order is left as 'open', and the 'filled' is left to 0, since we get the fill id's, but we don't know the filled amounts corresponding to those id's. In order to know the filled amount, a successive call to fetch_order is needed.

In the end, if I got it right, there is no point in processing the returned trades, since we don't have the amounts, that's why I removed it altogether.

**Comment by payala** [comment]
The 'remaining' amount also needed a fix.

**Comment by frosty00** [comment]
If I were you I would be wary about trying to get too much information from the order API endpoint since an order and a trade are two completely different things. Rather it is much better to ask the exchange about the recent trades since that will tell you the price the order was executed at. For example I could set an order at 0.01 and the exchange might execute that at 0.02 - anyways rant over use `fetch_my_trades` over `fetch_my_orders`.

**Comment by payala** [comment]
I agree @frosty00 , however in this case with cryptopia not relating trades and orders it's a bit of a mess.

I'm mostly interested on the order status and fill amount, anyways. Hopefully fetch_order is reliable enough for that.

**Pull request merged**
