### PR TITLE
coinex withdraw takes params["network"]

### PR DESCRIPTION
**Pull request by samgermain**
I get an invalid withdrawal address error from the exchange no matter what. I'm not sure what to do differently 

```
% coinex withdraw USDT 2 '"TEY6qjnKDyyq5jDc3DJizWLCdUySrpQ4yp"' '{"network": "TRC20"}' --verbose
2023-01-10T05:13:47.126Z
Node.js: v18.4.0
CCXT v2.5.68
coinex.withdraw (USDT, 2, TEY6qjnKDyyq5jDc3DJizWLCdUySrpQ4yp, [object Object])
fetch Request:
 coinex POST https://api.coinex.com/v1/balance/coin/withdraw 
RequestHeaders:
 {
  Authorization: '',
  'Content-Type': 'application/json'
} 
RequestBody:
 {"access_id":"86CC7F5E54E34198BDE897345C968990","actual_amount":2,"coin_address":"TEY6qjnKDyyq5jDc3DJizWLCdUySrpQ4yp","coin_type":"USDT","smart_contract_name":"TRC20","tonce":"1673327628865","transfer_method":"onchain"} 

handleRestResponse:
 coinex POST https://api.coinex.com/v1/balance/coin/withdraw 200 OK 
ResponseHeaders:
 {
  'Cf-Cache-Status': 'DYNAMIC',
  'Cf-Ray': '7872ecf3d869d2dd-CDG',
  Connection: 'keep-alive',
  'Content-Encoding': 'gzip',
  'Content-Type': 'application/json',
  Date: 'Tue, 10 Jan 2023 05:13:49 GMT',
  Server: 'cloudflare',
  'Transfer-Encoding': 'chunked',
  'X-Ratelimit-Limit': '20',
  'X-Ratelimit-Remaining': '39'
} 
ResponseBody:
 {"code": 310, "data": {}, "message": "Invalid Withdrawal Address."} 

ExchangeError Invalid Withdrawal Address.
---------------------------------------------------
[ExchangeError] Invalid Withdrawal Address.

    at handleErrors               ../../ccxt/ccxt/js/coinex.js:4585              throw new ErrorClass (response['message']);                                     
    at                            ../../ccxt/ccxt/js/base/Exchange.js:603        const skipFurtherErrorHandling = this.handleErrors (response.status, response.s…
    at processTicksAndRejections  node:internal/process/task_queues:95                                                                                           
    at async timeout              ../../ccxt/ccxt/js/base/functions/time.js:181  return await Promise.race ([promise, expires.then (() => { throw new TimedOut (…
    at fetch2                     ../../ccxt/ccxt/js/base/Exchange.js:2023       return await this.fetch (request['url'], request['method'], request['headers'],…
    at request                    ../../ccxt/ccxt/js/base/Exchange.js:2027       return await this.fetch2 (path, api, method, params, headers, body, config, con…
    at withdraw                   ../../ccxt/ccxt/js/coinex.js:3567              const response = await this.privatePostBalanceCoinWithdraw (this.extend (reques…
    at async run                  ../../ccxt/ccxt/examples/js/cli.js:293         const result = await exchange[methodName] (... args)                            

Invalid Withdrawal Address.
```

### CODE REVIEW

**Comment by kroitor** [comment]
@samgermain have you checked on the website if they require whitelisting the IP address for API withdrawals ?

**Comment by samgermain** [comment]
> @samgermain have you checked on the website if they require whitelisting the IP address for API withdrawals ?

It looks like it's optional

**Comment by ndubel** [comment]
@samgermain @kroitor will it be merged soon?

**Comment by samgermain** [comment]
coinex has both an address book and a separate withdrawal whitelist under the apiKeys section

I had only been adding the address to my address book

**Comment by samgermain** [comment]
reopened in https://github.com/ccxt/ccxt/pull/18729

**Pull request closed without merging**
