### PR TITLE
Add exchange: bw.com

### PR DESCRIPTION
**Pull request by brandsimon**
@kroitor 
Do you know when you will have time to look into it and merge it?
If it will take a few days I'd rather use a branch instead of waiting.

### CODE REVIEW

**Comment by kroitor** [comment]
@brandsimon i'd be honest, i may not have the time to merge it before the end of next week. But I'll do my best to merge it as quickly as possible.

Is it a complete set of their methods btw?

**Comment by brandsimon** [comment]
@kroitor 
Great, thank you for your honesty. :)
No, they support more methods, but I dont need more atm.

**Comment by brandsimon** [comment]
@kroitor 
Is the test failing because the methods are not implemented yet?

**Comment by kroitor** [comment]
> Is the test failing because the methods are not implemented yet?

@brandsimon `npm run build && node run-tests bw --python3 --verbose` should show the cause of the trouble... you can also launch the same python test this way:

```
npm run export-exchanges
npm run transpile
python python/test/test.py bw --verbose
```

↑ Let me know if that does not help locate the issue.

**Comment by brandsimon** [comment]
@kroitor 
Yes, thank you very much, I found it.
Python safeFloat is the only accessor method which supports arrays with indexes, all other methods fail.
I will fix this in a separate PR.

**Comment by brandsimon** [comment]
@kroitor 
are you still drowning in work?

**Comment by kroitor** [comment]
@brandsimon yes, unfortunately (terribly sorry for the long delays). I hope to get back to this PR within 2 weeks.

**Comment by brandsimon** [comment]
@kroitor 
It seams like your hopes got crushed :p

**Comment by kroitor** [comment]
@brandsimon ah, sh... you're right, my bad, pardon again for the delays. Another promise won't make too much sense, but i'll do my best to get to it asap.

**Pull request merged**
