### PR TITLE
Fix parsing side for Bitbay public trades

### PR DESCRIPTION
**Pull request by sohich**
A user trade history order sides are provided with attribute `userAction`: https://docs.bitbay.net/v1.0.1-en/reference#transactions-history.
A public trade history order sides are provided with attribute `ty`: https://docs.bitbay.net/v1.0.1-en/reference#last-transactions

The `parseTrade` method is used for parsing both private and public trades, but only the `userAction` parameter is being handled.
Due to that and the incorrect if-else clause, the `sell` side is returned for all public trades (including buy-trades).

Example where the bug is visible (look at the difference between "side" and "info.ty" attributes):
```
[
  {
    "id": "d3615f28-e93e-11eb-901d-0242ac110008",
    "timestamp": 1626774160855,
    "datetime": "2021-07-20T09:42:40.855Z",
    "symbol": "ATRI/USDT",
    "side": "sell",
    "price": 0.044278,
    "amount": 4,
    "cost": 0.177112,
    "info": {
      "id": "d3615f28-e93e-11eb-901d-0242ac110008",
      "t": "1626774160855",
      "a": "4",
      "r": "0.044278",
      "ty": "Buy"
    }
  },
  {
    "id": "d58d6682-e93e-11eb-901d-0242ac110008",
    "timestamp": 1626774164498,
    "datetime": "2021-07-20T09:42:44.498Z",
    "symbol": "ATRI/USDT",
    "side": "sell",
    "price": 0.044191,
    "amount": 5.5958,
    "cost": 0.2472839978,
    "info": {
      "id": "d58d6682-e93e-11eb-901d-0242ac110008",
      "t": "1626774164498",
      "a": "5.5958",
      "r": "0.044191",
      "ty": "Buy"
    }
  },
  {
    "id": "d5fa594f-e93e-11eb-901d-0242ac110008",
    "timestamp": 1626774165213,
    "datetime": "2021-07-20T09:42:45.213Z",
    "symbol": "ATRI/USDT",
    "side": "sell",
    "price": 0.044023,
    "amount": 7,
    "cost": 0.308161,
    "info": {
      "id": "d5fa594f-e93e-11eb-901d-0242ac110008",
      "t": "1626774165213",
      "a": "7",
      "r": "0.044023",
      "ty": "Sell"
    }
  },
  ...
]
```

### CODE REVIEW

**Comment by kroitor** [comment]
@sohich thx! Plz do not revert it, will merge shortly.

**Comment by sohich** [comment]
@kroitor, thank you a lot! 
Please note that I've force-pushed changes also to python and php implementations. I assume that you would want to edit these changes too

**Comment by kroitor** [comment]
> Please note that I've force-pushed changes also to python and php implementations. I assume that you would want to edit these changes too

Tbh, that is not necessary, since those files are generated from JS automatically:

- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#multilanguage-support
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#transpiled-generated-files

It's easier to maintain, if we just submit edits to one file, instead of 3-4-5 files. For example, there's still a couple of files missed in this PR, namely, the async versions of Python and PHP. No worries, though, those files will be regenerated from JS upon merging and building as well.

**Comment by sohich** [comment]
> Tbh, that is not necessary, since those files are generated from JS automatically:

Got it, thank you

**Pull request merged**
