### PR TITLE
bitcoincoid: fetchOpenOrders: fetching w/o symbol

### PR DESCRIPTION
**Pull request by mkutny**
Fix for #1678

### CODE REVIEW

**Comment by mkutny** [comment]
While working on it I found counter intuitive that `parseOrders` filters by since and limit but do not filter by a symbol:
https://github.com/ccxt/ccxt/blob/25eb8523cba9d9b0155f3517190f8b08f42da1c1/js/bitcoincoid.js#L270-L271

It would be much straightforward if it either does not filter at all or filters by all three, how do you feel about that?

**Comment by kroitor** [comment]
> It would be much straightforward if it either does not filter at all or filters by all three, how do you feel about that?

I agree, we need to redesign the filtering codepaths and make them more robust. Also, the since+symbol should be applied first, and the limit second after, for obvious reasons.

**Comment by mkutny** [comment]
> for obvious reasons

Not so obvious, BTW as it's not been done earlier )

**Comment by mkutny** [comment]
Well, now I see the proper order is implemented in `filterBySinceLimit`. Still, I wouldn't find your consideration obvious )

**Comment by kroitor** [comment]
Well, if you think of the logical order of filters here...
What would be the right thing to do:
1. Filter by since first.
2. Then limit the number of results.
3. Then filter limited results by symbols limiting them even more, effectively canceling the effect of `limit` from step 2.

What we would do instead, is
1. Filter by symbol (1 ←→ 2 can switch places)
2. Filter by since (1 ←→ 2 can switch places)
3. Filter the already-filtered results by limit (count)

So, limit should be the last one, as we don't know beforehand how many results will be left after 1+2.

**Comment by mkutny** [comment]
Yeah, I've got it once you mentioned it. I mean it's not obvious just because it was sitting there unnoticed for quite a while. I believe that snippet could be found on a plenty of exchanges.

**Comment by kroitor** [comment]
@mkutny probably all of them using filterBySinceLimit – all of those are affected now.

**Comment by nautonk** [comment]
@kroitor @mkutny it works :D you are both awesome 💃

**Pull request merged**
