### PR TITLE
luno - websockets

### PR DESCRIPTION
**Pull request by pcriadoperez**
ParseOrderBook functions could be removed if this PR is merged (https://github.com/kroitor/ccxt.pro/pull/401)

### CODE REVIEW

**Comment by waleedlashri18** [comment]
Dont

**Comment by frosty00** [comment]
we don't need the sequence number logic cause ws is over a tcp connection, so the internet would break if we couldn't be certain of the order of packets over tcp

**Comment by pcriadoperez** [comment]
> we don't need the sequence number logic cause ws is over a tcp connection, so the internet would break if we couldn't be certain of the order of packets over tcp

@frosty00 I included it because the documentation says `If an update is received out-of-sequence (for example update sequence n+2 or n-1 received after update sequence n), the client cannot continue and must reinitialise the state.`  (https://www.luno.com/en/developers/api#tag/Streaming-API)

**Review by frosty00 — APPROVED** [review]

**Comment by frosty00** [comment]
approved and will be merged automatically by the merge script

**Pull request merged**
