### PR TITLE
Use fetch-ponyfill to provide fetch-api on node

### PR DESCRIPTION
**Pull request by jla415**
I believe this solves both my issue and retains the original intent of the code that was causing my problem.

https://github.com/ccxt/ccxt/issues/606

### CODE REVIEW

**Comment by xpl** [comment]
Yeah, I have stumbled upon this project simultaneously with you :) This still needs to be checked with React Native, though, because if that ponyfill includes the `node-fetch` dependency via the plain `require` call, it will cause the same problem.

But apart from that, it eliminates the need to implement a custom XMLHttpRequest-based polyfill in our codebase, which is obviously a good thing.

**Comment by kroitor** [comment]
@jla415 thanks a lot for your effort! If you could help us test it with Webpack and React, it would be awesome! We will get cracking on this as soon as we finish our current urgent tasks.

**Comment by xpl** [comment]
As far as I remember, it is the `react-native-cli` tool that caused the problem. It's bundler simply cannot link against Node's system modules, like `http`, throwing an exception when trying to build projects that reference them (directly or indirectly, via `require`d modules). So a workaround was needed to prevent it's bundler from recognizing some unwanted `require` calls, while still being able to execute them in Node.

**Comment by jla415** [comment]
I created a basic react-native app and included ccxt, but it is unable to run due to the use of the fs module in journal.js

**Comment by kroitor** [comment]
@jla415 we've changed that to module.require recently, this is a related problem, need to exclude it somehow in non-Node environments

**Comment by jla415** [comment]
Just fyi - I commented out all the journal/fs stuff and my code loaded the fetch api on react-native no problem so this pull request appears to work

The current const journal = isNode && require ('./journal') stuff you are currently trying still errors under react-native with unable to resolve module 'fs' error.   previously the module.require call also errored under react native with a different error

**Comment by kroitor** [comment]
Ok, I commented out journal stuff, so, it looks like we can merge now! )

**Comment by munrocket** [comment]
This update added to npm package? I have error related to this library.
```
Uncaught (in promise): TypeError: Network request failed fetchPonyfill/</</self.fetch/</xhr.onerror@http://localhost:8100/build/vendor.js:133995:22 H@http://localhost:8100/build/polyfills.js:3:23948 F</l</t.prototype.invokeTask@http://localhost:8100/build/polyfills.js:3:15649 onInvokeTask@http://localhost:8100/build/vendor.js:4973:24 F</l</t.prototype.invokeTask@http://localhost:8100/build/polyfills.js:3:15562 F</c</r.prototype.runTask@http://localhost:8100/build/polyfills.js:3:10815 F</h</e.invokeTask@http://localhost:8100/build/polyfills.js:3:16787 p@http://localhost:8100/build/polyfills.js:2:27646 v@http://localhost:8100/build/polyfills.js:2:27893
```

**Comment by kroitor** [comment]
@munrocket can you show a minimal snippet of code that does not work for you?

**Comment by munrocket** [comment]
```
import { Component } from '@angular/core';
import { NavController } from 'ionic-angular';
import ccxt from 'ccxt';

@Component({
  selector: 'page-home',
  templateUrl: 'home.html'
})
export class HomePage {

  bit: any;

  async onInit() {
    this.bit = new ccxt.bittrex();
    this.bit = await this.bit.loadMarkets();
    console.dir(this.bit)
  }

  constructor(public navCtrl: NavController) {
    this.onInit();
  }
  
  ver = 'AAAAA';
}
```

**Comment by kroitor** [comment]
And what does verbose output tell?

```
import { Component } from '@angular/core';
import { NavController } from 'ionic-angular';
import ccxt from 'ccxt';

@Component({
  selector: 'page-home',
  templateUrl: 'home.html'
})
export class HomePage {

  bit: any;

  async onInit() {
    this.bit = new ccxt.bittrex({'verbose': true}); // ←---------- add this
    this.bit = await this.bit.loadMarkets();
    console.dir(this.bit)
  }

  constructor(public navCtrl: NavController) {
    this.onInit();
  }
  
  ver = 'AAAAA';
}
```

**Comment by kroitor** [comment]
Also, I'd recommend to catch the exception and output it properly to see the reason of failure:

```
import { Component } from '@angular/core';
import { NavController } from 'ionic-angular';
import ccxt from 'ccxt';

@Component({
  selector: 'page-home',
  templateUrl: 'home.html'
})
export class HomePage {

  bit: any;

  async onInit() {
    this.bit = new ccxt.bittrex({'verbose': true}); // ←---------- add this
    try {
        this.bit = await this.bit.loadMarkets();
    } catch (e) {
        console.log ('Exception:', e.constructor.prototype, 'Message:', e.message)
    }
    console.dir(this.bit)
  }

  constructor(public navCtrl: NavController) {
    this.onInit();
  }
  
  ver = 'AAAAA';
}
```

**Comment by munrocket** [comment]
Maybe some error with access rights in angular, i am not familiar with it
```
Failed to load https://bittrex.com/api/v1.1/public/getmarkets: No 'Access-Control-Allow-Origin'
header is present on the requested resource. Origin 'http://localhost:8100' is therefore not allowed access.

Exception: 
Error {name: "TypeError", message: "", constructor: ƒ, toString: ƒ}
constructor
:
ƒ TypeError()
message
:
""
name
:
"TypeError"
toString
:
ƒ toString()
__proto__
:
Object
```

**Comment by munrocket** [comment]
Ok i guess it's my fault. Here related error:
https://stackoverflow.com/questions/38357699/ionic-probleme-no-access-control-allow-origin

**Comment by kroitor** [comment]
Oh, that's an easy one. You're running from a browser and bittrex forbids CORS

https://github.com/ccxt/ccxt/wiki/Install#cors-access-control-allow-origin

**Comment by munrocket** [comment]
Thanks @kroitor !

**Comment by kroitor** [comment]
↑ The above is an explanation on how to workaround it. Cheers!

**Comment by kroitor** [comment]
@munrocket let's confirm this, does the following work for you? (It uses a publicly available CORS proxy, just a test):

```
import { Component } from '@angular/core';
import { NavController } from 'ionic-angular';
import ccxt from 'ccxt';

@Component({
  selector: 'page-home',
  templateUrl: 'home.html'
})
export class HomePage {

  bit: any;

  async onInit() {
    this.bit = new ccxt.bittrex({
        'proxy': 'https://cors-anywhere.herokuapp.com/', // ←---------- add this
        'verbose': true,
    }); 
    try {
        this.bit = await this.bit.loadMarkets();
    } catch (e) {
        console.log ('Exception:', e.constructor.prototype, 'Message:', e.message)
    }
    console.dir(this.bit)
  }

  constructor(public navCtrl: NavController) {
    this.onInit();
  }
  
  ver = 'AAAAA';
}
```

It should work without an exception. So, if it does, you need to set up a local CORS proxy, like described in the Manual (follow the link above).

**Comment by munrocket** [comment]
@kroitor all is perfect, thanks! Really cool.

**Pull request merged**
