### PR TITLE
fix(bingx)!: fetchBalance - undefined marketType fetches spot balance

### PR DESCRIPTION
**Pull request by samgermain**
passing a marginMode for spot fetchBalance throws an error	

```
% py bingx fetchBalance
Python v3.9.6
CCXT v4.2.15
bingx.fetchBalance()
{'USDT': {'free': 0.0, 'total': 0.0, 'used': 0.0},
 'VST': {'free': 0.0, 'total': 0.0, 'used': 0.0},
 'free': {'USDT': 0.0, 'VST': 0.0},
 'info': {'code': '0',
          'data': {'balances': [{'asset': 'USDT', 'free': '0', 'locked': '0'},
                                {'asset': 'VST', 'free': '0', 'locked': '0'}]},
          'debugMsg': '',
          'msg': ''},
 'total': {'USDT': 0.0, 'VST': 0.0},
 'used': {'USDT': 0.0, 'VST': 0.0}}
 ```
 
 ```
 % py bingx fetchBalance '{"defaultType": "swap"}'
Python v3.9.6
CCXT v4.2.15
bingx.fetchBalance({'defaultType': 'swap'})
{'USDT': {'free': 0.3645, 'total': 0.3565, 'used': -0.008},
 'free': {'USDT': 0.3645},
 'info': {'code': '0',
          'data': {'balance': {'asset': 'USDT',
                               'availableMargin': '0.3645',
                               'balance': '0.3565',
                               'equity': '0.9016',
                               'freezedMargin': '0.0000',
                               'realisedProfit': '-0.0878',
                               'unrealizedProfit': '0.5451',
                               'usedMargin': '-0.0080',
                               'userId': '1245247939641409536'}},
          'msg': ''},
 'total': {'USDT': 0.3565},
 'used': {'USDT': -0.008}}
 ```

### CODE REVIEW

**Comment by carlosmiei** [comment]
I don't think we need this, you can't check for every case we don't support

**Comment by samgermain** [comment]
> I don't think we need this, you can't check for every case we don't support

we should still fetch spot when the market type is undefined though

**Comment by carlosmiei** [comment]
> > I don't think we need this, you can't check for every case we don't support
> 
> we should still fetch spot when the market type is undefined though

@samgermain Market type will default to `defaultType` so won't be undefined.

**Comment by samgermain** [comment]
> > > I don't think we need this, you can't check for every case we don't support
> > 
> > 
> > we should still fetch spot when the market type is undefined though
> 
> @samgermain Market type will default to `defaultType` so won't be undefined.

Why did you close this? Every other exchange fetches the spot balance when the marketType is `undefined`

**Comment by carlosmiei** [comment]
> > > > I don't think we need this, you can't check for every case we don't support
> > > 
> > > 
> > > we should still fetch spot when the market type is undefined though
> > 
> > 
> > @samgermain Market type will default to `defaultType` so won't be undefined.
> 
> Why did you close this? Every other exchange fetches the spot balance when the marketType is `undefined`

@samgermain why would the marketType be undefined?, it always default to the value inside options

**Pull request closed without merging**
