### PR TITLE
add walutomat

### PR DESCRIPTION
**Pull request by jpospychala**
hi,
would you be interested in adding Walutomat, a fiat-only exchange?

### CODE REVIEW

**Comment by piotrmoszkowicz** [comment]
@kroitor  Are you interested in having this? As I am, I can take the PR and get it done.

**Comment by kroitor** [comment]
> @kroitor Are you interested in having this? As I am, I can take the PR and get it done.

@piotrmoszkowicz sure, we welcome all PRs and contributions, just make sure to follow these guides: 

- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#multilanguage-support
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#derived-exchange-classes

Thx!

**Comment by piotrmoszkowicz** [comment]
@kroitor Hey, it seems I can not push to @jpospychala 's branch, seems I would have to fork it myself and open new PR, should I do it now? Moreover I've fixed all linter errors & code style should comply with Contribution Guide, but I've found out that in the mean time Walutomat updated their API version. For some reason I can not generate API key for testing in their panel, I've already contacted them so I have to wait for them to push the work. 

Thanks,
Piotr.

**Comment by kroitor** [comment]
> seems I would have to fork it myself and open new PR, should I do it now?

If you can, then, please, do ) Thx for the update and for your involvement!

**Comment by jpospychala** [comment]
closing in favor of #4517

**Pull request closed without merging**
