### PR TITLE
test methods - checks for response arrays

### PR DESCRIPTION
**Pull request by ttodua**

### CODE REVIEW

**Comment by carlosmiei** [comment]
@ttodua I think we have a confusion here, in REST methods is absolutely fine and acceptable to return an empty array, only in the WS side (that is event-driven) it's not "correct"

**Comment by ttodua** [comment]
> @ttodua I think we have a confusion here, in REST methods is absolutely fine and acceptable to return an empty array, only in the WS side (that is event-driven) it's not "correct"

yes, ofc I know that they "might" return the empty array, but you might look from another angle - how they are supposed to return empty array? lets say fetchtrades or fetchOHLCV or other public methods? we are testing the most tradeable pair (BTC/USDxxx) so there is "very very little" chance that empty response has ever happen, and probably on the lowest tier exchanges. for most toptier ccxt exchanges it **is not ok** to have empty array from those methods, it means something is probably broken on our side.
as you see also in travis logs, all exchanges pass those tests and there is no problem.

**Comment by ttodua** [comment]
you might name some specific methods where empty response is expected and I would remove that check from those specific methods, but i think we will be sacrificing quality if we dont implement these checks. I had already observed many hidden glitches which were revealed such tests and without such tests we would pose a risk to have broken methods

**Comment by ttodua** [comment]
if there is some intermittent error or on specific run exchange might return empty response for that moment, it's ok, as I said i'll be adding skips for such crappy exchanges

**Comment by carlosmiei** [comment]
> if there is some intermittent error or on specific run exchange might return empty response for that moment, it's ok, as I said i'll be adding skips for such crappy exchanges

@ttodua Ok but if this update brings too many headaches I will remove it

**Comment by ttodua** [comment]
> > if there is some intermittent error or on specific run exchange might return empty response for that moment, it's ok, as I said i'll be adding skips for such crappy exchanges
> 
> @ttodua Ok but if this update brings too many headaches I will remove it

 if exchange returns empty trades for major tested pair (i.e. BTC/USDT ) then that exchange not worth to be tested at all, and i'll add skips for those exchanges. 
 i'll be keeping an eye on the builds in these days so will push fixes promptly

**Pull request merged**
