### PR TITLE
Common currency code

### PR DESCRIPTION
**Pull request by frosty00**
I needed to use a backwards commonCurrencyCode in my application so it is now possible. Some exchanges still define commonCurrencyId but this can now also be moved to the base class.

### CODE REVIEW

**Comment by frosty00** [comment]
Moved both commodCurrencyCode and currencyId to base class. Should shorten code base a little.

**Comment by frosty00** [comment]
Could you look at this relatively soon because I fear that merge conflicts will arise if you leave this PR for too long.

**Comment by kroitor** [comment]
@frosty00 yep, apologies for the long wait, will merge in few hours

**Comment by mkutny** [comment]
> I fear that merge conflicts will arise if you leave this PR for too long.

Conflicts only makes us stronger )))

**Comment by kroitor** [comment]
There are several issues with this commit:

1. currencyId is traversing all codes upon each call, whereas it should've really indexed the transposed version once, upon startup... And it is already done in `this.currencies_by_id` (by id) and `this.currencies` (by common code). Because of that, I removed the references to currencyId from derived classes and replaced them with a call to `this.currency (code)`. I think i'm going to remove currencyId for now, for less confusion...

2. The commonCodes themselves are not overrided, but extended in derived classes, which isn't a problem (yet), but may be a problem in future if we run into a parent-child conflict...

Anyway, I've merged it with minor edits along the way, thx for the help!

**Comment by frosty00** [comment]
Awesome, thanks for the merge.

Few questions about the current codebase, 

https://github.com/ccxt/ccxt/blob/d10a7b216921518a4e90d5115976f2b09e8d2a76/js/base/Exchange.js#L48 - when is the `Market` class used, if at all.

Could https://github.com/ccxt/ccxt/blob/d10a7b216921518a4e90d5115976f2b09e8d2a76/js/base/Exchange.js#L692 and https://github.com/ccxt/ccxt/blob/d10a7b216921518a4e90d5115976f2b09e8d2a76/js/base/Exchange.js#L653

be replaced with `Exchange.safeString` instead or another standard function?

**Comment by kroitor** [comment]
> - when is the Market class used, if at all?

This is a rudimentary part, I believe, so, probably, can clean it up.

> Could ... be replaced with Exchange.safeString instead or another standard function?

Their difference is that `market()` and `currency()` both throw an exception, while safeString does not... So, I guess, it depends on which replacement you mean, all is possible ))

**Pull request merged**
