### PR TITLE
Fix Documentation types

### PR DESCRIPTION
**Pull request by carlosmiei**
- Currently, our JSDocs are invalid because we're using python types (dict, int, float) for Javascript IntelliSense hinting. Besides not being pretty (users might get confused about why they have python types being suggested), it will be a problem when we migrate to typescript because it would break the build.
- The problem occurs in PHP as well.
- To fix it I'm converting JS types to the proper ones at transpile time, check `transpiler.js`
- The only thing that can be seen as a small downside is that Javascript does not distinguish between ints and float so to avoid losing information I'm converting `number` to --->`int|float`for both Python and PHP. 
- More info: https://usejsdoc.org/tags-param.html

### CODE REVIEW

**Comment by samgermain** [comment]
Don't merge this yet

**Comment by carlosmiei** [comment]
@samgermain why?

**Comment by samgermain** [comment]
> @samgermain why?

I just wanted some time to look over it. 

I don't think that we should convert `int` and `float` to number, whenever `int` or `float` is specified, it's specific that it's an int or a float. I know these aren't JS types, but nobody is going to be confused by this. We can create type aliases for integer and float for typescript if this will cause typescript problems

```
type integer = number;
type float = number;
```

There are some instances where the type is `int|float` and these can be changed to number.

I don't really see a downside to using int and float types in docstrings other than an overfixation that these aren't types in JS

**Comment by carlosmiei** [comment]
> > @samgermain why?
> 
> I just wanted some time to look over it.
> 
> I don't think that we should convert `int` and `float` to number, whenever `int` or `float` is specified, it's specific that it's an int or a float. I know these aren't JS types, but nobody is going to be confused by this. We can create type aliases for integer and float for typescript if this will cause typescript problems
> 
> ```
> type integer = number;
> type float = number;
> ```
> 
> There are some instances where the type is `int|float` and these can be changed to number.
> 
> I don't really see a downside to using int and float types in docstrings other than an overfixation that these aren't types in JS
> 
> I'm not hard set on doing it this way though

@samgermain I'm not strictly against keeping int/floats either,  @kroitor do you agree?

**Comment by samgermain** [comment]
@kroitor @frosty00 Whats your opinion on whether to specify a type as `int` or `float`, and whether to use the type `number`, which would transpile to `int|float` in Python. This is just for the docstrings, Javascript doesn't have an int or float type, but sometimes the exchange will require an even int for a parameter, the python docstrings would also be less specific. Everyone will also understand if the docstring says int or float instead of number, so I don't see it being a problem, but it's technically incorrect. With typescript, we would just create aliases for `int` and `float` that are aliases for number.

**Review by samgermain — CHANGES_REQUESTED** [review]
So lets not change `int` or `float` to `number`, but let's change `int` to `integer`, and let's change all the `int|float` to `number`, and then transpile them as well.

For typescript, we'll need to create custom types of `integer` and `float`

**Pull request merged**
