### PR TITLE
Include cryptopia minimum base trade amount limit

### PR DESCRIPTION
**Pull request by payala**
The api gives the minimum cost that any trade should have in the MinimumBaseTrade field. I have included it into the limits of the markets.

### CODE REVIEW

**Comment by payala** [comment]
Sorry for the dirty commits, I'm learning to use pull requests. only c4a41e0 applies.

**Comment by kroitor** [comment]
@payala can you please move this edit to the `cryptopia.js` ? https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code
Thx!

**Comment by kroitor** [comment]
https://github.com/ccxt/ccxt/pull/2752/files#diff-633e26334bffa59e393da2371d032e9fR3

**Comment by payala** [comment]
Thanks, sure I'll give it a try, sounds interesting

**Pull request closed without merging**
