### PR TITLE
TICK_SIZE - lbank2

### PR DESCRIPTION
**Pull request by ttodua**

### CODE REVIEW

**Comment by zgayjjf** [comment]
Do you have any proof that `lbank` uses `TICK_SIZE`? Since we have been using `DECIMAL_PLACES` for a long time. Maybe there is something I missed.

@ttodua

**Comment by zgayjjf** [comment]
https://api.lbkex.com/v2/accuracy.do
```json
{"symbol":"eth_usdt","quantityAccuracy":"4","priceAccuracy":"2", "minTranQua":"0.0001"}
```
According to the api, lbank is using `DECIMAL_PLACES`, so this PR seems to be a fault. Please correct me if I'm wrong. 🤗

**Comment by kroitor** [comment]
@zgayjjf we are converting from DECIMAL_PLACES to TICK_SIZE everywhere in CCXT, since TICK_SIZE allows all types of values, while DECIMAL_PLACES only allows powers of ten. Therefore TICK_SIZE covers DECIMAL_PLACES in its entirety, hence the DECIMAL_PLACES precisionMode is redundant.

**Comment by zgayjjf** [comment]
I see. Thanks for the information!

> @zgayjjf we are converting from DECIMAL_PLACES to TICK_SIZE everywhere in CCXT, since TICK_SIZE allows all types of values, while DECIMAL_PLACES only allows powers of ten. Therefore TICK_SIZE covers DECIMAL_PLACES in its entirety, hence the DECIMAL_PLACES precisionMode is redundant.

**Pull request merged**
