### PR TITLE
load in tests in python (todo in other languages)

### PR DESCRIPTION
**Pull request by frosty00**
Added a new precisionTests file where anyone can add new tests. The goal is for it to work across languages but so far I have only loaded in and implemented it in Python

### CODE REVIEW

**Comment by kroitor** [comment]
Oh, sorry, I wouldn't really merge this template yet... as the test itself isn't finished... I would prefer not to attempt cross-language testing yet.

**Comment by frosty00** [comment]
Ok - 

```
+INPUT_VALUE ROUNDING_MODE PREC COUNTING_MODE PADDING_MODE RESULT
+12.3456000 TRUNCATE 20 AFTER_DOT NO_PADDING 12.3456
+12.3456 TRUNCATE 20 AFTER_DOT NO_PADDING 12.3456
```

Could you recommend another template style?

**Comment by kroitor** [comment]
> Could you recommend another template style?

The natural language syntax )

**Comment by frosty00** [comment]
Yeah I guess "it works" technically now. However, when more edge cases show up with some precision needy exchange it would be a good idea to be able to test all three languages at once. Maybe by transpilling part of the javascript tests or loading it from a file.

**Comment by frosty00** [comment]
If I converted it to a json standard and attempted this again in other langauges would that be ok?

**Comment by kroitor** [comment]
@frosty00 not really, I think we should just set up the transpiler to transpile that test as well )

**Pull request closed without merging**
