### PR TITLE
Updates GDAX taker fee

### PR DESCRIPTION
**Pull request by amarvin**
New rate was effective April 4th, 2018

### CODE REVIEW

**Comment by kroitor** [comment]
Please read this: https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

**Comment by kroitor** [comment]
@amarvin can you please move this edit to the gdax.js ?

**Comment by amarvin** [comment]
Done. Sorry about that!

**Comment by amarvin** [comment]
Not sure why the Travis CI check is failing

**Comment by kroitor** [comment]
@amarvin no worries on the Travis error, not related to your PR. Thx!

**Pull request merged**
