### PR TITLE
Bitstamp: Update withdrawal / funds limits

### PR DESCRIPTION
**Pull request by DanielMartini**

### CODE REVIEW

**Comment by kroitor** [comment]
Hi! ) 

A quick question to you: https://www.bitstamp.net/fee_schedule/ ← this page still shows the currently existing version of the fee schedule (the "old one").

Can you please explain the edits or link to the source of info? Thx!

**Comment by DanielMartini** [comment]
Seems to be different from their API: https://www.bitstamp.net/api/ 

Is true that if you use the website there is no minimum, but I was getting limits errors at withdrawing XRP from the api and after look the section of "xrp_withdrawal error" they got error cases in the limits. After that I updated all of them

**Comment by kroitor** [comment]
But... those are not the limits, those are fees... %)

**Comment by DanielMartini** [comment]
Hmm.. my bad then. 

Maybe a new dimension with the withdrawal limits should be done? AFAIK (at least in bitstamp) I can't get the limits from any API call, and if is not harcoded I don't know how to get them.

**Comment by kroitor** [comment]
@DanielMartini no worries! For withdrawal limits we have `.currencies` property and the [`fethcCurrencies()`](https://github.com/ccxt/ccxt/search?q=fetchCurrencies&type=Issues) family of methods (where available with the exchange). This has not been documeted very thoroughly yet, because it is still in process of unification. We would be thankful for you contributions to that area as well. Thank you! I'm closing this for now, if you don't mind.

**Comment by DanielMartini** [comment]
I was fixing it hahaha! BCH should be added to the list anyway :D

**Comment by kroitor** [comment]
@DanielMartini oops, sorry, didn't expect that... Please feel free to reopen this pr or submit a new one. Thanks a lot!

**Pull request closed without merging**
