### PR TITLE
New exchange - timebit.sg

### LINKED ISSUE #9348: New Exchange: Timebit
uri: https://spot.timebit.sg/

Their api: https://public-api.timebit.sg/swagger-ui.html#/

### PR DESCRIPTION
**Pull request by timebird-dev**
uri: https://spot.timebit.sg/

Their api: https://public-api.timebit.sg/swagger-ui.html#/

fixes #9348

### CODE REVIEW

**Comment by kroitor** [comment]
Related: https://github.com/ccxt/ccxt/issues/9348

**Comment by timebird-dev** [comment]
Hi @kroitor any idea of when Timebit will be merged to master branch, please? Thanks

**Comment by kroitor** [comment]
@timebird-dev hi! Thanks for the PR! Please check this FAQ:

- https://github.com/ccxt/ccxt/wiki/FAQ

If you wish to speed it up, please, reach out to info@ccxt.trade

**Review by mrbaguvix — COMMENTED** [review]
Existing code for same exchange Tiimebit. Please see @kroitor's comment.

**Comment by haint** [comment]
> Existing code for same exchange Tiimebit. Please see @kroitor's comment.

could you help us get close your mention? Our branch is Timebit not Tiimebit(double `i`)

**Comment by ttodua** [comment]
seems exchange no longer functions

**Pull request closed without merging**
