### PR TITLE
liqui: cache: refix for #1830: cache should return Array, not map

### PR DESCRIPTION
**Pull request by mkutny**
`filterBySinceLimit` and `filterOrdersBySymbol` expect Array.

`filterOrdersBySymbol` still returns Array even if provided a map, so this passed my tests and remained unnoticed for a while.

### CODE REVIEW

**Comment by mkutny** [comment]
Let's say I've submitted an order and received and it's got immediately filled, i.e. `createOrder` returned: `{ remaining: 0 }`. I'd say in this case we should mark this order as `closed` right away.

I'm asking because this approach (while being valid) looks somewhat unusual although I guess for market orders it should work this way for sure.

**Comment by kroitor** [comment]
>  I'd say in this case we should mark this order as closed right away.

Sounds reasonable )

**Comment by mkutny** [comment]
Want to discuss it here, before submitting a PR.

When an order is created exchange returns an object which is immutable over time, a client may rely on that. What cache returns is a live object which changes over time. Moreover, if a client decides to change that object's properties (for whatever legitimate reason) it may break the cache.

It looks like cache should return a deep copy of the orders, not references to them. Does it sound good to you?

**Comment by kroitor** [comment]
> It looks like cache should return a deep copy of the orders, not references to them. Does it sound good to you?

A few of our concerns on this:

- we will lose the ability to actually inject something there (while this may not be legitimate design-wise, practically, it is very helpful sometimes).
- we would actually want the user to be responsible for keeping the cache and treat it with care, namely, implement whatever caching policy might be needed, prune the outdated orders, etc...
- this will significantly hit the memory and will raise RAM consumption... currently, even with the caching layer, the library is still quite thin (capable of working from a phone or an AWS nano instance)... In other words, it feels itself perfectly well within 512MB RAM. If we switch from shallow copying to deep copying with immutable states, the end-user app may become very greedy on mem and will fall out of 512 meg quite quickly in a loaded trading setup.

So, it's a tradeoff of Design vs Hackability+Performance. We can still consider switching, if there Is a practical need for immutability that overweighs the other factors. However, if there is such a need, it is not obvious to us yet, despite the well-known principles and benefits of immutable states. Not sure if this is aligned with your interest. Let me know if you have objections on this.

**Comment by mkutny** [comment]
> Let me know if you have objections on this.

Not at all, really... I just was sure there is a real need for it and this particular implementation just does not address it **yet** for some good reason (like a lack of time).

But what you wrote just made me think that I might be trying to misuse the cache or use a bad pattern.

What I'm trying to do is to track when an order gets closed. So I basically `fetchOpenOrders()` to see what's there and if any order from my list of open orders is not there then I know it's got closed.

That's obviously much like liqui/poloniex cache logic works, nothing special.

It works for all exchanges with no cache but fails to work for exchanges *with* the cache.
You see, if the order has been closed then upon `fetchOpenOrders` its status will get changed not only in the cache but also in my list of open orders too (as they are references to the cached ones). So basically there will be no difference in open orders between my list and what `fetchOpenOrders` returns.

As I guess you might track when your orders get closed too you probably use a different pattern and can suggest how should I deal with the cache in this case.

**Comment by mkutny** [comment]
Ok, if you haven't started writing ) I came up with a solution.

I'll split out `openOrdersArray` from `ordersArray` and disregard of the order's status in `openOrdersArray` I'll treat it as open. Indeed, not need to deep copies.

While it's easy to implement I'm sure users will be hit from this issue from time to time... because it's not obvious one needs to work with the cache this way. Likewise, it's not obvious how to handle those `RequestTimeout` exceptions.

**Pull request merged**
