### PR TITLE
fix(hyperliquid) - migrate to TICK_SIZE

### PR DESCRIPTION
**Pull request by ttodua**
we should have all exchanges handled in TICK_SIZE. 
it's better if it was done from the beginning of exchange integration, so later changes wouldn't be needed

### CODE REVIEW

**Comment by gaardiolor** [comment]
Hi @ttodua , 

Hyperliquid precision was broken since the beginning, it has been fixed in 
https://github.com/ccxt/ccxt/pull/23560
https://github.com/ccxt/ccxt/pull/24347
https://github.com/ccxt/ccxt/pull/24392 (yesterday)

This makes the freqtrade community happy, because this is the last fix (of ~20 that I submitted) that will make freqtrade work for this exchange. 

While I see that this PR is work in progress (in this state I think it will for sure break precisionMode again), I'm not sure if we want to fix something that (since yesterday) isn't broken?

If ccxt really has to do it, please let me and @carlosmiei thouroughly review and test it before merging.. thx :)

**Comment by ttodua** [comment]
@gaardiolor thanks for the reply!
I understand what you say, however, the migration to TICK_SIZE does(**should**) not affect the calculations what were broken.
I am convinced we should move to TICK_SIZE, but sure, I'll wait @carlosmiei input on this, we would need few mins to test it out

**Comment by gaardiolor** [comment]
ok! I just found the rationale of moving to TICK_SIZE [here](https://github.com/ccxt/ccxt/issues/13554), that makes sense. 

Please give me the opportunity to test this as well :) Should be able to do that later today. thx!

**Comment by gaardiolor** [comment]
ok, I've tested it, fetched all markets and compared the precisions, it looks good. Running freqtrade now with https://github.com/ccxt/ccxt/pull/24410 active, I'll let you know tonight if I run into any issues!

**Comment by gaardiolor** [comment]
ok, seems to work fine, sorry for the disturbance 😄 Hyperliquid precision is a bit complicated, spent quite some time in figuring it out and fixing it, I was afraid this would undo (some of) it. Happy to conclude that this is not the case :)

Migrating everything (both precision and amount) to TICK_SIZE seems like a good idea. Didn't know about it, otherwise I'd have done my fixes in TICK_SIZE. 

Keep up the good work!

**Comment by carlosmiei** [comment]
@gaardiolor Thanks a lot for double-checking it, this will be merged soon.

**Comment by ttodua** [comment]
@gaardiolor thanks for the tests & replies ! let us know if you'll face any issue 👍

**Pull request merged**
