### PR TITLE
fix(binance) - reduceOnly handling

### PR DESCRIPTION
**Pull request by ttodua**
when running :
```
await e.createOrder ('BTC/USDT', 'limit', 'buy', 0.001, 60000, {reduceOnly: true});
```
for spot markets, API throws an error: 
> {"code":-1104,"msg":"Not all sent parameters were read; read '11' parameter(s) but was sent '12'."}

however, `reduceOnly` is unified parameter, and it **has to be handled** correctly, independently whether it's spot or not. even if it's spot, and user provides that, it shouldn't lead to exception.

### CODE REVIEW

**Comment by carlosmiei** [comment]
@ttodua where's the test?

**Comment by ttodua** [comment]
right, i'll add static tests soon

**Comment by ttodua** [comment]
@carlosmiei can you give me hints, what other kind of static tests we should add for this edit?

**Comment by carlosmiei** [comment]
@ttodua can you check the static test failing

```

> ccxt@4.2.64 request-js
> node js/src/test/test.js --requestTests

[TEST_FAILURE][JS][STATIC_REQUEST_TEST_FAILURE][binance (WS) spot][createOrder][swap buy limit with reduceOnly]AssertionError [ERR_ASSERTION]: output length mismatch computed {"timestamp":"1709901622112","symbol":"BTCUSDT","side":"BUY","newOrderRespType":"RESULT","newClientOrderId":"x-xcKtGhcu2d0de91c08554cf89ef8fa","type":"LIMIT","quantity":"0.01","price":"10000","timeInForce":"GTC","reduceOnly":"true","recvWindow":"10000","signature":"f2274d9747f7d9cdbbfc5a85d83dd59c9ead96957284019f177ea3c811475db1"} stored: {"timestamp":"1709895616844","symbol":"BTCUSDT","side":"BUY","newOrderRespType":"RESULT","newClientOrderId":"x-xcKtGhcu2aaaefebcaf6437e8084bb","type":"LIMIT","quantity":"0.01","price":"10000","timeInForce":"GTC","recvWindow":"10000","signature":"49c86041752655f5f60308396297ad9b62db1d6480f8c28a74d45f3811071744"}
```
?

**Comment by ttodua** [comment]
I've pushed an update after last commit, now my change only affects spot market and that's all.

**Comment by ttodua** [comment]
now passes tests

**Comment by carlosmiei** [comment]
> however, reduceOnly is unified parameter, and it has to be handled correctly, independently whether it's spot or not

@ttodua sorry, I think was confused by the initial report, I'm not sure this is right actually. Why would you apply a concept that is not applicable here? What if the user provided `traillingPercent` and the exchange did not support it? Would we omit it and let the user think the order was properly placed?

**Comment by ttodua** [comment]
traillingPercent  or any other very specific params are not common. reduceOnly is a very common, which any exchange should support (unlike trailingPercent or whatsoever), and binance spot throws error when unrecognized param is provided (unlike binance futures, where you can send unrecognized param without any problem). but ok, lets leave this, i'll close

**Pull request closed without merging**
