### PR TITLE
fix: TypeError count(): Argument #1 ($value) must be of type Countabl…

### PR DESCRIPTION
**Pull request by dennydanek**
TypeError
count(): Argument #1 ($value) must be of type Countable|array, null given

### CODE REVIEW

**Comment by dennydanek** [comment]
I don't know where exactly is the source. Is it correct?

**Comment by kroitor** [comment]
@dennydanek yes, that should be it. Will merge shortly, thank you for your help!

**Comment by kroitor** [comment]
@dennydanek can you post your verbose output for the error mentioned in the title? I'm trying to understand how Binance can return empty markets in this case.

```PHP
$exchange->verbose = true;
$exchange->load_markets();
```

**Comment by dennydanek** [comment]
@kroitor I have some outputs for you. I believed in this case the RequestTimeout should be thrown but isnt because `$result = ''` and the condition `$result === false` never be true

```
Array (
    [0] => Response:
    [1] => GET
    [2] => https://api.binance.com/api/v3/exchangeInfo
    [3] => 0
    [4] => Resolving timed out after 10008 milliseconds
    [5] => Array
        (
        )
    [6] => 
)
```

```
Array
(
    [0] => Response:
    [1] => GET
    [2] => https://api.binance.com/api/v3/exchangeInfo
    [3] => 200
    [4] => Operation timed out after 10013 milliseconds with 32016 out of 42452 bytes received
    [5] => Array
        (
            [Content-Type] => application/json;charset=UTF-8
            [Content-Length] => 42452
            [Date] => Thu, 25 Mar 2021 16:00:06 GMT
            [Server] => nginx
            [X-Mbx-Uuid] => 0c9de49c-4498-4cd3-b5e4-6747510e280f
            [X-Mbx-Used-Weight] => 1
            [X-Mbx-Used-Weight-1m] => 1
            [Content-Encoding] => gzip
            [Strict-Transport-Security] => max-age=31536000; includeSubdomains
            [X-Frame-Options] => SAMEORIGIN
            [X-Xss-Protection] => 1; mode=block
            [X-Content-Type-Options] => nosniff
            [Content-Security-Policy] => default-src 'self'
            [X-Content-Security-Policy] => default-src 'self'
            [X-Webkit-Csp] => default-src 'self'
            [Cache-Control] => no-cache, no-store, must-revalidate
            [Pragma] => no-cache
            [Expires] => 0
            [Access-Control-Allow-Origin] => *
            [Access-Control-Allow-Methods] => GET, HEAD, OPTIONS
            [X-Cache] => Miss from cloudfront
            [Via] => 1.1 dd133741afef09b02f3e6afd7cb39f40.cloudfront.net (CloudFront)
            [X-Amz-Cf-Pop] => AMS50-C1
            [X-Amz-Cf-Id] => LgOEvQpgKloG0aTbfeks_7wkcOsg-WhlPqLUJUOn-e-TdCBoMplclQ==
        )
    [6] => 
)
```

**Comment by kroitor** [comment]
@dennydanek thanks, we will add the handling for that, appreciate your feedback!

**Pull request merged**
