### PR TITLE
Exchange: declare as abstract

### PR DESCRIPTION
**Pull request by kornrunner**
base/Exchange should be abstract

### CODE REVIEW

**Comment by kroitor** [comment]
Hi! Thx! I got one question on this: is it really *abstract* ? Afaik from C++, a class is only abstract if all of its methods are pure virtual... But this is not the case with this particular class, it does implement some of them.

**Comment by kroitor** [comment]
> This change prevents one from instantiating Exchange and using it without being initialized.

Yeah, that's exactly what I'm asking about, namely: is there a reason to not want that particular Exchange class to be instantiate-able?

**Comment by kornrunner** [comment]
Exchange instance on it's own is pretty useless - because it does not define any API URL (or any other data) required for an exchange to be functional.

All of utility functions in Exchange are already defined as public and static, so they will be available even without an instance of the class (eg: `Exchange::orderBy($something)`)

Currently, one is able to write something like:

```php
$exchange = new Exchange();
$exchange->fetch_orders();
```

Which would throw (as is expected) and would be encountered in run time.
If we declare it as abstract, it still wouldn't fail before run time - but a good IDE would at least warn user about it.

**Comment by kroitor** [comment]
Ok, thank you for answering!

**Comment by kornrunner** [comment]
Thank you!

**Pull request merged**
