### PR TITLE
Serialize fetchFees

### PR DESCRIPTION
**Pull request by frosty00**
Added deposit as another field in the fetchFees method. Changed 0 to undefined to better express the lack of value (if it means the same as none in Python)

### CODE REVIEW

**Comment by frosty00** [comment]
Maybe standardise is a better way of describing it. BTW I'm still working on the base class implementation of load_fees().

**Comment by kroitor** [comment]
> it could be called by load_markets.

It could, sometimes. However, with some exchanges fees are per-person, that means the need for keys to access actual fee info. Just need to keep that in my mind, we can't rely on fees being available immediately after loadMarkets. Maybe we should make loading personal fees conditional (depending on whether the keys are properly set or not). Will consider ways of solving this. Thx!

**Comment by frosty00** [comment]
Another interesting case is Kucoin. As well having percentage based withdrawal fees it also has a minimum withdrawal fee. Thus the calculation is much harder and cannot be stored in the .fees with the current structure:

    'withdrawFeeRate': 0.001,
    'withdrawMinAmount': 0.1,
    'withdrawMinFee': 0.05,

withdrawFeeRate is a percentage based withdrawal fee whereas withdrawMinFee is a flat rate. Therefore the calculate to for the fees in this example is (in Python):

      max(withdrawFeeRate * amount, withdrawMinFee)

I noticed there is a calculateFee method in the base Exchange class. Maybe this could be overwritten by in the Kucoin class. However, I am still stuck with the issue of storing both a percent_based and non percent_based fee in the .fees attribute which is impossible without a redesign of the fee structure.

**Comment by frosty00** [comment]
> keys to access actual fee info

I've been using a 'loaded' boolean inside the fees dictionary inside 'trading' and 'funding' to distinguish between loaded and hardcoded fees for this very reason.

**Comment by frosty00** [comment]
@kroitor perhaps a fees class with a calculate_fee method that could take a bunch of different arguments depending on the exchange and available fee implementations. For example this could gracefully handle tier based structures given the size of the order and currently monthly trade amount.

    {'funding': {'deposit': 0.0,
          'percentage': False,
           'tierBased': False,
           'withdraw': {'ACT': 0.1,
               'AMB': 3.0,
               ...,
    {'trading': {'maker': 0.1,
          'taker': 0.1,
          'percentage': False,
          'tierBased': False,

I'm thinking of changing the current fee structure above to

---                                                             
    {'funding': {'loaded': False,
          'deposit: {'flat': {}, 'percentage' {}},
           'tiers': {},
           'withdraw': {'percentage': {}, 
                                'flat': {'ACT': 0.1,
                                    'AMB': 3.0,
                                     ...,}
                               }
     },
    {'trading': {'loaded': False,
                       'percentage': {'maker': 0.1,
                           'taker': 0.1}
          'flat': {},
          'tiers': {},
    }

But this nested json is hard to read for the average user and incompatible with the past fees. 

Therefore it may be better to simply create a class called fees that can store every kind of fee and only show the relevant ones in a uniform structure. I think this could greatly improve the unified fee API.

**Comment by kroitor** [comment]
Check out the current method for precalculating fees:

- https://github.com/ccxt/ccxt/blob/master/js/base/Exchange.js#L830
- https://github.com/ccxt/ccxt/blob/master/python/ccxt/base/exchange.py#L1006
- https://github.com/ccxt/ccxt/blob/master/php/Exchange.php#L1385

Some exchanges having specific rules (25-50% of them) override this method.

**Comment by frosty00** [comment]
Ok. So trading fees are pretty straight-foward. How about withdrawal fees which can be a percentage, flat or both?

**Comment by kroitor** [comment]
> How about withdrawal fees

Currently not very well unified (therefore marked as a work in progress), and we are unifying them with your help.

> which can be a percentage, flat or both?

There's a little more to it, funding fees can consist of exchanges' fees and txfees, and some exchanges allow their users to set the txfees. Moreover, many exchanges (a significant count) have a conditional fee schedule like, for example, *"the fee is 0.005% in BTC but not less than $5 USD"* or something like that. Without a DSL for defining fee expressions it would be hard to unify the entire zoo. So we need to make a reasonably-deep structure, a detailed one, but not overwhelming one. This is hard.

**Pull request merged**
