### PR TITLE
PHP - feature to add method overload/override

### PR DESCRIPTION
**Pull request by ttodua**
so alike all other langs, we could also add overloads in PHP, so it would align with JS/PY.
PR is simple and includes also example & documentation

### CODE REVIEW

**Review by sc0Vu — COMMENTED** [review]
Can user extends the class and implement the feature they want?

```php
   class MyOKCoinUSD extends \ccxt\okcoinusd {
       public function __construct ($options = array ()) {
           parent::__construct (array_merge (array ('i' => 1), $options));
       }
       public function fetch_ticker(string $symbol, $params = array ()) {
           // parent::fetch_ticker($symbol, $params);
           // do something...
       }
   }
```

**Comment by ttodua** [comment]
@carlosmiei I've added anonymous class example too. also, my memory was wrong in part where I said that they can't be run from inside functions, as they can be created inside functions too (as shown in `APPROACH 2` example)

**Comment by ttodua** [comment]
> @sc0Vu 
ofc, that's possible, but that (`class X extends Y`) is also possible in any other lang, take JS or PY or any, and that wouldn't need any PR. The purpose of this PR is to bring ability of modifying instance's methods dynamically (on the fly), like it's possible in other langs (JS/PY). 

we had a small discussion in discord, you can take a look there too.

**Comment by carlosmiei** [comment]
LGTM

**Review by carlosmiei — APPROVED** [review]

**Pull request merged**
