### PR TITLE
fix(xt) - trades parsing

### LINKED ISSUE #24099: XT fetch_trades() returns only buy trades for all spot markets
### Operating System

Linux Mint

### Programming Languages

Python

### CCXT Version

4.4.24

### Description

All trades returned by `fetch_trades` have value 'buy' as 'side' for XT spot markets. 'takerOrMaker' on the other hand has both 'taker' and 'maker' values. For clarity it would be better to keep 'takerOrMaker' fixed (as 'taker') and let the 'side' have either 'buy' or 'sell' value. 

According to XT API documentation (https://doc.xt.com/#market5tradeRecent) 'b' value returned by the XT API means "whether is buyerMaker or not". In the other words, when 'b' is `True` it is a maker buy trade or, more intuitively, a taker sell trade. Also, in my opinion, when 'b' is `False` the trade should be considered to be a taker buy trade in the ccxt dictionary.

### Code

```
exchange = ccxt.xt()

total_trade_count = 0      
buy_trade_count = 0
sell_trade_count = 0  
maker_trade_count = 0
taker_trade_count = 0

trades = exchange.fetch_trades('BTC/USDT', limit=1000)
for trade in trades:
    total_trade_count += 1
    if trade['side'] == 'buy':
        buy_trade_count += 1
    if trade['side'] == 'sell':
        sell_trade_count += 1
    if trade['takerOrMaker'] == 'maker':
        maker_trade_count += 1
    if trade['takerOrMaker'] == 'taker':
        taker_trade_count += 1        
    
print(trades[0])
print('total trades:', total_trade_count)
print('buy trades:  ', buy_trade_count)
print('sell trades: ', sell_trade_count)   
print('maker trades:', maker_trade_count)
print('taker trades:', taker_trade_count)
print()
```
```
{'info': {'i': '420870962049751424', 't': '1730045456757', 'p': '67806.75', 'q': '0.00728', 'v': '493.63314', 'b': True}, 'id': '420870962049751424', 'timestamp': 1730045456757, 'datetime': '2024-10-27T16:10:56.757Z', 'symbol': 'BTC/USDT', 'order': None, 'type': None, 'side': 'buy', 'takerOrMaker': 'maker', 'price': 67806.75, 'amount': 0.00728, 'cost': 493.63314, 'fee': {'cost': None, 'currency': None}, 'fees': []}
total trades: 201
buy trades:   201
sell trades:  0
maker trades: 99
taker trades: 102
```

### PR DESCRIPTION
**Pull request by ttodua**
fix #24099

### CODE REVIEW

**Comment by carlosmiei** [comment]
@ttodua can you check the response tests?
image

**Comment by ttodua** [comment]
@carlosmiei sorry seems i've opened non-draft PR and was waiting for travis results. will push a fix now

**Comment by carlosmiei** [comment]
@ttodua np 😅

**Comment by ttodua** [comment]
@carlosmiei seems I had a typo, fixed now, travis passed

**Pull request merged**
