### PR TITLE
Mexc3: cancelOrder add margin support

### PR DESCRIPTION
**Pull request by Dan-krm**
Added spot-margin support to cancelOrder:
```
node examples/js/cli mexc3 cancelOrder '"762925761295421440"' BTC/USDT '{"marginMode":"isolated"}'

mexc3.cancelOrder (762925761295421440, BTC/USDT, [object Object])
2022-09-01T19:58:58.114Z iteration 0 passed in 322 ms

{
  id: '762925761295421440',
  clientOrderId: undefined,
  timestamp: 1662062142000,
  datetime: '2022-09-01T19:55:42.000Z',
  lastTradeTimestamp: undefined,
  status: 'open',
  symbol: 'BTC/USDT',
  type: 'limit',
  timeInForce: undefined,
  side: 'buy',
  price: 18000,
  stopPrice: undefined,
  average: undefined,
  amount: 0.0014,
  cost: 0,
  filled: 0,
  remaining: 0.0014,
  fee: undefined,
  trades: [],
  info: {
    symbol: 'BTCUSDT',
    orderId: '762925761295421440',
    orderListId: '-1',
    clientOrderId: null,
    price: '18000',
    origQty: '0.0014',
    executedQty: '0',
    cummulativeQuoteQty: '0',
    status: 'NEW',
    type: 'LIMIT',
    side: 'BUY',
    isIsolated: true,
    isWorking: true,
    time: '1662062142000',
    updateTime: '1662062142000'
  },
  fees: []
}
2022-09-01T19:58:58.114Z iteration 1 passed in 322 ms
```

### CODE REVIEW

**Comment by carlosmiei** [comment]
@Dan-krm can you update this PR ? (we don't override handleMarginMode anymore)

**Comment by Dan-krm** [comment]
> @Dan-krm can you update this PR ? (we don't override handleMarginMode anymore)

Yeah definitely, why aren't we overriding handleMarginMode anymore again?

**Comment by Dan-krm** [comment]
Should I remove the handleMarginModeAndParams override from mexc3.js entirely?

**Comment by carlosmiei** [comment]
> Should I remove the handleMarginModeAndParams override from mexc3.js entirely?

@Dan-krm, it exists only in pending PR, right? Since we've decided to validate the value inside each method yep we can remove the overrides

**Comment by carlosmiei** [comment]
LGTM ✅ 

```
p mexc3 cancelOrder "772270860831690752" "LTC/USDT" '{"marginMode":"isolated"}'
Python v3.9.7
CCXT v1.93.98
mexc3.cancelOrder(772270860831690752,LTC/USDT,{'marginMode': 'isolated'})
{'amount': 0.2,
 'average': None,
 'clientOrderId': None,
 'cost': 0.0,
 'datetime': '2022-09-27T14:49:47.000Z',
 'fee': None,
 'fees': [],
 'filled': 0.0,
 'id': '772270860831690752',
 'info': {'clientOrderId': None,
          'cummulativeQuoteQty': '0',
          'executedQty': '0',
          'isIsolated': True,
          'isWorking': True,
          'orderId': '772270860831690752',
          'orderListId': '-1',
          'origQty': '0.2',
          'price': '25',
          'side': 'BUY',
          'status': 'NEW',
          'symbol': 'LTCUSDT',
          'time': '1664290187000',
          'type': 'LIMIT',
          'updateTime': '1664290187000'},
 'lastTradeTimestamp': None,
 'price': 25.0,
 'remaining': 0.2,
 'side': 'buy',
 'status': 'open',
 'stopPrice': None,
 'symbol': 'LTC/USDT',
 'timeInForce': None,
 'timestamp': 1664290187000,
 'trades': [],
 'type': 'limit'}
```

**Comment by Dan-krm** [comment]
> @Dan-krm, it exists only in pending PR, right? Since we've decided to validate the value inside each method yep we can remove the overrides

@carlosmiei The override is still present in mexc3 but it only defaults to isolated if defaultType is margin or margin is true, should I delete it completely in a separate PR or leave it as is?

```
    handleMarginModeAndParams (methodName, params = {}) {
        /**
         * @ignore
         * @method
         * @description marginMode specified by params["marginMode"], this.options["marginMode"], this.options["defaultMarginMode"], params["margin"] = true or this.options["defaultType"] = 'margin'
         * @param {object} params extra parameters specific to the exchange api endpoint
         * @param {bool|undefined} params.margin true for trading spot-margin
         * @returns {[string|undefined, object]} the marginMode in lowercase
         */
        const defaultType = this.safeString (this.options, 'defaultType');
        const isMargin = this.safeValue (params, 'margin', false);
        let marginMode = undefined;
        [ marginMode, params ] = super.handleMarginModeAndParams (methodName, params);
        if ((defaultType === 'margin') || (isMargin === true)) {
            marginMode = 'isolated';
        }
        return [ marginMode, params ];
    }
```

**Pull request merged**
