### PR TITLE
Feature/bhex

### PR DESCRIPTION
**Pull request by tufei8438**

### CODE REVIEW

**Comment by tufei8438** [comment]
fix get trade.takeOrMaker value error

**Comment by tangfl** [comment]
How long will it take to merge this in ? Because one of our client is waiting to use this

**Comment by kroitor** [comment]
@tangfl unfortunately, we can't give promises on the free open-source work as explained in our FAQ: https://github.com/ccxt/ccxt/wiki/FAQ#when-will-you-add-feature-foo-for-exchange-bar--whats-the-estimated-time-when-should-we-expect-this. If BHEX wants it in a guaranteed timeframe email info@ccxt.trade.

**Comment by tufei8438** [comment]
we will change brand from bhex to hbtc

**Pull request closed without merging**
