### PR TITLE
add requestHeaders + requestBody to handleErrors for unified errors

### PR DESCRIPTION
**Pull request by frosty00**

### CODE REVIEW

**Comment by frosty00** [comment]
needs to transpile for it to pass tests

**Comment by kroitor** [comment]
@frosty00 should we also pass them to the defaultErrorHandler (in case the default handler is redefined in an inherited class) ?

**Comment by frosty00** [comment]
I think defaultErrorHandler should take the same args as `handleErrors` for simplicity. After bytetrade I will write some transpiled `defaultErrorHandler` tests

**Comment by kroitor** [comment]
@frosty00 yep, i think the same, so we should propagate request headers and request body to both methods.

**Pull request merged**
