### PR TITLE
Initial SFOX support

### PR DESCRIPTION
**Pull request by mattrasband**

### CODE REVIEW

**Comment by kroitor** [comment]
@mrasband thx for the PR! ) A quick question: can you please remove the README.md from the edited files? It's auto-generated. That would help keep it clean )

**Comment by mrasband** [comment]
Done @kroitor - thanks for taking the time to provide updates and fixes!

**Comment by mrasband** [comment]
I am trying to fix the tests @kroiter and am not sure what to do on this one:

```
FAILED sfox (JavaScript): (explain @ run-tests.js:187)


	TESTING { exchange: "sfox", symbol: "all" }  (<anonymous> @ test.js:32)

	10 symbols [] (loadExchange @ test.js:179)
	SYMBOL: bchbtc (testExchange @ test.js:255)
	fetching currencies not supported (exports [as fetchCurrencies] @ test.fetchCurrencies.js:35)
	bchbtc fetchTicker () not supported (exports [as fetchTicker] @ test.fetchTicker.js:52)
	fetching all tickers at once not supported (exports [as fetchTickers] @ test.fetchTickers.js:50)
	fetching OHLCV not supported (exports [as fetchOHLCV] @ test.fetchOHLCV.js:53)
	bchbtc fetchTrades () not supported (exports [as fetchTrades] @ test.fetchTrades.js:46)
	[AssertionError] bids[0][0]: 8754 (of 150); asks[0][0]:8746.79 (of 150)

	    actual:   null
	    expected: undefined

	    at exports                      js/test/Exchange/test.orderbook.js:71     assert (bids[0][0] <= asks[0][0],
	    at exports [as fetchOrderBook]  …test/Exchange/test.fetchOrderBook.js:24  testOrderBook (exchange, orderbook, method, symbol)
	    at _tickCallback                internal/process/next_tick.js:68                                                              (e @ test.js:28) (explain @ run-tests.js:190)
```

**Comment by kroitor** [comment]
```
	[AssertionError] bids[0][0]: 8754 (of 150); asks[0][0]:8746.79 (of 150)

	    actual:   null
	    expected: undefined

	    at exports                      js/test/Exchange/test.orderbook.js:71     assert (bids[0][0] <= asks[0][0],
```

We have to investigate all cases when orderbook bid >= orderbook ask (which isn't normal, especially, if this condition does hold for long). Basically, if you think of how a matching engine **should work**, bids can never cross asks for a long time – the matching engine should match and mutually-close them. The matching engine might not be able to close them, if the intersecting orders in question are _flagged_ in some way. But anyways, we need to find a documented explanation of how bids can cross asks with this exchange (some exchanges have explanations), or we need to forward the question to SFOX tech support.

**Comment by mrasband** [comment]
(full disclosure: I work at SFOX) 

SFOX is a prime dealer, so it is possible because that's a blended orderbook from a number of exchanges.

**Comment by kroitor** [comment]
@mrasband then you can add it to the exchanges excluded from that particular test here: https://github.com/ccxt/ccxt/blob/master/js/test/Exchange/test.orderbook.js#L61 with a meaningful comment. However, we need to think on how to convey this to the user, CCXT is mostly used to talk to the exchanges directly, and it may be very surprising if those orderbooks can cross. In fact, we  didn't have that many integrated aggregators for that reason, so I will need to think more on how to handle this in the lib...

**Comment by mrasband** [comment]
They don't trade directly on the underlying exchanges, they are trading with us as effectively an exchange - we have various algos to optimize trades for different strategies across them. In case you are interested: https://www.sfox.com/algos.html

**Comment by kroitor** [comment]
@mrasband i wonder why doesn't SFOX cut the arb to its benefit? Because of the underlying exchanges' fees?

**Comment by mrasband** [comment]
That's a question for above me :) Hopefully your users can find value with SFOX being added!

**Comment by mrasband** [comment]
@kroitor I am going to close this temporarily while I figure out a segment that isn't working as expected. If it's ok I will tag you when I reopen it this weekend.

**Comment by kroitor** [comment]
@mrasband sure, anytime!

**Comment by mrasband** [comment]
OK, it looks like I had a bad assumption and didn't test the trading properly. Just for posterity, here's my test script:

```javascript
'use strict';

const SFOX = require('./sfox');

const main = async () => {
    const sfox = new SFOX ({apiKey: '...'});

    let price = await sfox.publicGetOfferBuy({'amount': 0.1});
    console.log(price);

    let order = await sfox.createOrder(
        'ethusd',
        'limit',
        'buy',
        0.04,
        140.0,
    );
    console.log(order);

    await new Promise((res, rej) => {
        setTimeout(res, 10000);
    });

    let cancelled = await sfox.cancelOrder(order['id']);
    console.log("cancelled:", cancelled);

    order = await sfox.fetchOrder(order['id']);
    console.log('fetched:', order);
};

try {
    main();
} catch (e) {
    console.log(e);
}
```

**Comment by mrasband** [comment]
@kroitor - I think this is all happy now, I was able to do some trading today with this. Sorry for the inbox spam today and thank you for being a great library maintainer.

If you have any additional feedback, don't hesitate to share!

**Comment by kroitor** [comment]
@mrasband I will do my best to get to it as soon as I can, in the meantime, it would really help speed it up if you could do the following test on your side:

1. open `keys.json` or create `keys.local.json` in the cloned ccxt repo on your machine
2. add your keys there for`"sfox": { "apiKey": "YOUR_API_KEY", "secret": "YOUR_SECRET" },`
3. make sure you build the cloned repo on your side: `npm run build`
4. run the ccxt public test (should be ok) and private tests (not tested by travis CI without the keys):

```
node js/test/test sfox
```
```
python python/test/test.py sfox
```
```
php -f php/test/test.php sfox
```

**Comment by mrasband** [comment]
I can't trigger another build without pushing a new version, but the error looks to be unrelated to the SFOX addition: `bytetrade`. Running the stuff locally you asked influenced the latest commit #f5786ff

**Pull request closed without merging**
