### PR TITLE
Added Fetch Deposits and Fetch Withdrawls functionality to bitfinex

### PR DESCRIPTION
**Pull request by angad2102**

### CODE REVIEW

**Comment by kroitor** [comment]
Hi, @angad2102 ! First of, thanks for your involvement! Can you please clean up this PR for us a bit? If you can, please remove all files from it except the `bitfinex.js` (the source file that is used to generate all others):

- https://github.com/ccxt/ccxt/pull/4366/files#diff-833df9e0fe9b17fde3c4112553cfd9efR5
- https://github.com/ccxt/ccxt/pull/4366/files#diff-45118c9d16591287ec7c41756df6758bR3
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#multilanguage-support

Thx again!

**Comment by kroitor** [comment]
Err, nope, sorry, we won't merge it, because bitfinex does not have true endpoints for withdrawals and deposits, and it has an endpoint for all `transactions` instead, so the filtering for deposits and withdrawals is done outside of the lib, otherwise it breaks the pagination.

**Comment by kroitor** [comment]
@angad2102 anyways, we really appreciate your effort and we will be happy to see more PRs from you in the future. Please read about metainfo and emulation here: https://github.com/ccxt/ccxt/wiki/Manual#exchange-metadata

**Comment by angad2102** [comment]
@kroitor Thanks for pointing out these errors. I'll be careful in the future.

**Comment by kroitor** [comment]
@angad2102 thx to you for participation, really looking forward to seeing more contributions from you! ) Respect!

**Pull request closed without merging**
