### PR TITLE
liquid: lots of small fixes

### PR DESCRIPTION
**Pull request by npomfret**

### CODE REVIEW

**Comment by npomfret** [comment]
@kroitor I had some crazy git merge error on my old fork (for a bunch of files I've not touched).  Though it safest to recreate the fork from scratch.  So in summary the Liquid changes are:

 * added undocumented transactions api (for getting deposits and withdrawals)
 * added (more) hard coded minimum order sizes (although these can probably be parsed from a webpage)
 * added hard coded price and amount precisions (inferred from values in the order books)
 * changed the `used` field in balances from _"0.0"_ to _undefined_ as the exchange doesn't provide this data (a zero value is misleading)
 *  filled in the _order_ field in `myTrades` (using the `with_details` parameter in the api call)
 * added the fee currency to the order (it appears to always be the quote currency)
 * added the `cost` to the order (using the filled amount and average execution price)

**Comment by npomfret** [comment]
@kroitor i think the build error here is nothing to do with this PR - could you take a look?

Any chance of getting this merged?  There's more I'd like to do.

**Comment by kroitor** [comment]
Unfortunately, I will have to delete those inferred precisions for two reasons:
1. we don't want to list their markets in hardcode anywhere in the lib, this approach is deprecated
2. those values aren't always correct if inferred from the orderbooks

Is that ok?

**Comment by kroitor** [comment]
Actually, found this nice undocumented endpoint: https://api.liquid.com/currencies

**Comment by npomfret** [comment]
That api call looks useful!

FYI - I've just added edit order functionality.

**Comment by npomfret** [comment]
@kroitor thanks for the help with Liquid.  I have a question about the signature of `editOrder` which currently looks like:

`async editOrder (id, symbol, type, side, amount, price = undefined, params = {}) {`

The required params (I think) are `id`, `amount` and `price`.  What is the pattern to use with regard to defining defaults of _undefined_ parameters?

**Comment by npomfret** [comment]
@kroitor thanks for the help with Liquid.  I have a question about the signature of `editOrder` which currently looks like:

`async editOrder (id, symbol, type, side, amount, price = undefined, params = {}) {`

The required params (I think) are `id`, `amount` and `price`.  What is the pattern to use with regard to defining defaults of _undefined_ parameters?

**Comment by npomfret** [comment]
@kroitor did we lose the precision information as a part of this merge? I'm getting this now with ETH/BTC markets

```
TypeError: Cannot read property 'precision' of undefined
      at liquid.amountToPrecision (/Users/nickpomfret/projects/CrypPro-marketdata/gae-services/ticking-orderbook-service/node_modules/ccxt/js/base/Exchange.js:1209:75)
```

**Comment by kroitor** [comment]
> The required params (I think) are id, amount and price. 

For Liquid – yes, but we have to have them for cross-compatibility with other exchanges as well, some of them do require arguments even in cases where they don't seem to be necessary. But they still do require those. Therefore `type` and `side` is also there.

> What is the pattern to use with regard to defining defaults of undefined parameters?

The general approach is: if the parameter has an `undefined` default value, this makes it optional in most cases. Currently the `editOrder` method has almost the same signature as does the `createOrder` method with `id` prepended to the list of arguments. The first milestone for us was to implement a unified createOrder to cover basic *market* and *limit* orders, therefore those arguments have those specific default values for that particular call. For example, a `market` order doesn't always have a `price`, etc... 

However, with newly appearing distributed exchanges and with other types of trading (like, *margin trading*, *leveraged trading*, *otc* and other) there can be more types of orders, so when you're under constant active development like we are, it's hard to predict exchange-specific requirements. 

With spot trading, in most cases you can't really edit anything but your `limit` orders. So, the `price`  argument is checked inside the editOrder to make sure it was defined by the user. If upon the call it has the `undefined` default value, then it means the user hasn't specified it, and in that case we don't set any default value in the lib – instead we throw an `ArgumentsRequired` exception (if and only if some `undefined` argument is required indeed). We avoid setting any values for the user in the lib, unless there's no other way to implement this or that aspect of it.

**Pull request merged**
