### PR TITLE
Update binance withdraw fees

### PR DESCRIPTION
**Pull request by Deathamns**
According to https://binance.zendesk.com/hc/en-us/articles/115000429332.

### CODE REVIEW

**Comment by kroitor** [comment]
Awesome! Thx! Though, we are using math percentages, but I will divide those numbers by a hundred, no problem. Really appreciate you participation!

**Comment by Deathamns** [comment]
Aren't those exact amounts for each currency? As I can understand they don't seem to be percentages, nor is mentioned that they are. The trading fees are, but those didn't change.

**Comment by kroitor** [comment]
@Deathamns not really... we still have to think on how we should specify if the withdraw fee is fixed flat or a percentage... Maybe we should ultimately switch to strings with support for the `%` sign to indicate percentages, with the `%` sign absent if the fee is fixed flat...

**Comment by Deathamns** [comment]
If those are percentages, then 50% fee for SNT or FUN doesn't make sense to me, or even 500% for TRX. The table says UNIT, so I guessed it's a fixed flat. If you look at the withdraw fees at [bitfinex](https://www.bitfinex.com/fees#withdraw), the amounts are similar, and their "Bank wires" explicitly say percentage, but not with crypto-currencies, so again I can assume that all those are fixed.

Yes, a clear distinction between the two is needed. The `%` sing in a string is fine by me.

Side question: do you have plans to handle the trading fees based on the amount of trades (like at [bitfinex](https://www.bitfinex.com/fees))?

**Pull request merged**
