### PR TITLE
bybit: refactor fetchFundingRate

### PR DESCRIPTION
**Pull request by cheunhong**
Current bybit's `fetchFundingRate` has a few disadvantages

1) Uses private api which requires apikey
2) Has a lower rate limit
3) Does not have `fundingTimestamp`
4) Does not support multiple symbols

This PR utilises the ticker api to fetch the results and added `fetchFundingRates` method

### CODE REVIEW

**Comment by cheunhong** [comment]
require the team to review this PR. thank you.

**Comment by carlosmiei** [comment]
> require the team to review this PR. thank you.

Hello @cheunhong will review it soon, thanks for the contribution

**Comment by carlosmiei** [comment]
LGTM ✅ 

```
p bybit fetchFundingRate "LTC/USDT:USDT" --sandbox
Python v3.10.8
CCXT v2.5.94
bybit.fetchFundingRate(LTC/USDT:USDT)
{'LTC/USDT:USDT': {'datetime': '2023-01-16T16:58:12.239Z',
                   'estimatedSettlePrice': None,
                   'fundingDatetime': '2023-01-17T00:00:00.000Z',
                   'fundingRate': 0.0001,
                   'fundingTimestamp': 1673913600000,
                   'indexPrice': 86.26,
                   'info': {'askPrice': '86.28',
                            'basisRate': '',
                            'bidPrice': '86.27',
                            'deliveryFeeRate': '',
                            'deliveryTime': '0',
                            'fundingRate': '0.0001',
                            'highPrice24h': '89.17',
                            'indexPrice': '86.26',
                            'lastPrice': '86.24',
                            'lastTickDirection': 'MinusTick',
                            'lowPrice24h': '83.95',
                            'markPrice': '86.27',
                            'nextFundingTime': '1673913600000',
                            'openInterest': '2436436.2',
                            'openInterestValue': '210191350.97',
                            'predictedDeliveryPrice': '',
                            'prevPrice1h': '86.19',
                            'prevPrice24h': '87.82',
                            'price24hPcnt': '-0.017991',
                            'symbol': 'LTCUSDT',
                            'turnover24h': '1727913927.4299986',
                            'volume24h': '19822123.49999997'},
                   'interestRate': None,
                   'markPrice': 86.27,
                   'nextFundingDatetime': None,
                   'nextFundingRate': None,
                   'nextFundingTimestamp': None,
                   'previousFundingDatetime': None,
                   'previousFundingRate': None,
                   'previousFundingTimestamp': None,
                   'symbol': 'LTC/USDT:USDT',
                   'timestamp': 1673888292239}}
```

**Review by carlosmiei — APPROVED** [review]

**Comment by cheunhong** [comment]
@carlosmiei thanks for the review

**Comment by carlosmiei** [comment]
> @carlosmiei thanks for the review

@cheunhong will be merged soon! 🙂 thanks

**Pull request merged**
