### PR TITLE
make fetch_my_trades/fetch_orders support symbol param of 'None'

### PR DESCRIPTION
**Pull request by ngugc**
CoinEx apis (fetch_my_trades/fetch_orders) support 'symbol' param of 'None', while the current python implementation doesn't support it. This PR will fix it.

### CODE REVIEW

**Comment by ngugc** [comment]
@kroitor , why did it report “parseTrade is undefined” while parseOrder was OK?

**Comment by kroitor** [comment]
> @kroitor , why did it report “parseTrade is undefined” while parseOrder was OK?

In order to fix the issue, you don't need to edit the base class files at all (Exchange.js/exchange.py). The only edit that is required to make it work, is an edit in the coinex.js file itself and that's it.

**Comment by kroitor** [comment]
@ngugc no worries, just leave it as is, i'll upload a proper refix to it shortly.

**Comment by ngugc** [comment]
> > @kroitor , why did it report “parseTrade is undefined” while parseOrder was OK?
> 
> In order to fix the issue, you don't need to edit the base class files at all (Exchange.js/exchange.py). The only edit that is required to make it work, is an edit in the coinex.js file itself and that's it.

OK, I'll remove the js base changes right now.

**Comment by kroitor** [comment]
@ngugc ok, great! You will see the edits that I'm going to push, so from there you will also see how we do that in most other cases as well.

**Comment by ngugc** [comment]
@kroitor , by the way, do I need to commit the generated files as well?

**Comment by kroitor** [comment]
@ngugc nope, just the js file would be required, so no need to commit the transpiled files for other languages, those are generated and committed automatically upon the build.

**Comment by ngugc** [comment]
@kroitor , do you want me to change the python base exchange.py back as well? Or are you working on it?

**Comment by kroitor** [comment]
> do you want me to change the python base exchange.py back as well?

Yes, if you can, do please, I'll only push to coinex.js, so, no need to edit the base classes in this case as all methods from there already do work without a symbol or market specified (we have a few exchanges that behave in a similar way).

**Comment by ngugc** [comment]
> > do you want me to change the python base exchange.py back as well?
> 
> Yes, if you can, do please, I'll only push to coinex.js, so, no need to edit the base classes in this case as all methods from there already do work without a symbol or market specified (we have a few exchanges that behave in a similar way).

Changed back all other files except coinex.js

**Pull request merged**
