### PR TITLE
Bitcoincoid: Minimal amount and trading fee

### PR DESCRIPTION
**Pull request by Cengkaruk**
This minimal amount are not documented by the exchange, i try each one pair to know the amount.

### CODE REVIEW

**Comment by mkutny** [comment]
@Cengkaruk , thanks!

Have you happened to learn their `precisions` as well while testing? It would help a lot!

**Comment by kroitor** [comment]
@Cengkaruk when I try to place a small order with bitcoin.co.id it says that the minimal order size for buying is 50000INR, and for selling it is 0.0001 BTC. Can you provide a description of the methodology you used for finding those values? Thanks!

**Comment by mkutny** [comment]
IDR, not INR.

**Comment by Cengkaruk** [comment]
@kroitor 50k IDR (Indonesian Rupiah) not INR.

I finding those values by manually trying to buy and sell in their site by providing `0` in amount, one by one of all pairs. Not sure if we can get the minimum amount in error response from API.

screen shot 2018-01-27 at 3 29 10 pm
screen shot 2018-01-27 at 3 28 57 pm

Minimal buying using IDR pair are 50k, and selling are different each coin like in this PR.

**Comment by kroitor** [comment]
@mkutny oops... my bad!

screen shot 2018-01-27 at 11 38 49

Still a 3x difference!

**Comment by kroitor** [comment]
@Cengkaruk so, you took the buy side by default, right? Or the smallest? Or which one? )

**Comment by Cengkaruk** [comment]
@kroitor Smallest one.

**Comment by kroitor** [comment]
@Cengkaruk ok, thanks for answering )

**Comment by mkutny** [comment]
Probably minimum price is reported wrong:
```
$ node examples/js/cli.js bitcoincoid createLimitBuyOrder BTC/IDR 1 100
bitcoincoid.createLimitBuyOrder (BTC/IDR, 1, 100)
ExchangeError bitcoincoid Minimum price 1 IDR
```

```
$ node examples/js/cli.js bitcoincoid createLimitBuyOrder BTC/IDR 1 1000
bitcoincoid.createLimitBuyOrder (BTC/IDR, 1, 1000)
ExchangeError bitcoincoid Minimum order 50,000 IDR
```

**Comment by kroitor** [comment]
Yeah, current price is something like 152 000 000 IDR

**Pull request merged**
