### PR TITLE
gate.io parseTicker fix

### PR DESCRIPTION
**Pull request by ndubel**
Strange, but in Gate.io API it is so.

```
 'MXC/ETH':
   { symbol: 'MXC/ETH',
     timestamp: 1558093035217,
     datetime: '2019-05-17T11:37:15.217Z',
     high: 0.00003023,
     low: 0.00002502,
     bid: 0.00003016,
     bidVolume: undefined,
     ask: 0.00003106,
     askVolume: undefined,
     vwap: undefined,
     open: 0.000026971028791819894,
     close: 0.00003007,
     last: 0.00003007,
     previousClose: undefined,
     change: 0.0000030989712081801047,
     percentage: 11.49,
     average: 0.000028520514395909946,
     baseVolume: 47.67463396,
     quoteVolume: 1765854.03526205,
     info:
      { result: 'true',
        last: '0.00003007',
        lowestAsk: '0.00003106',
        highestBid: '0.00003016',
        percentChange: '11.49',
        baseVolume: '47.67463396',
        quoteVolume: '1765854.03526205',
        high24hr: '0.00003023',
        low24hr: '0.00002502' } }
```

image

### CODE REVIEW

**Comment by kroitor** [comment]
... yeah, but not with ETH/BTC:

```JavaScript
mbp:ccxt igorkroitor$ node examples/js/cli gateio fetchTicker ETH/BTC
gateio.fetchTicker (ETH/BTC)
{        symbol:   "ETH/BTC",
      timestamp:    1558094758916,
       datetime:   "2019-05-17T12:05:58.916Z",
           high:    0.03477,
            low:    0.03126,
            bid:    0.032165,
      bidVolume:    undefined,
            ask:    0.032301,
      askVolume:    undefined,
           vwap:    undefined,
           open:    0.03190140845070422,
          close:    0.032163,
           last:    0.032163,
  previousClose:    undefined,
         change:    0.00026159154929577405,
     percentage:    0.82,
        average:    0.03203220422535211,
     baseVolume:    2889.3999802852,
    quoteVolume:    95.4191121128312,
           info: {   quoteVolume: "95.4191121128311983",
                      baseVolume: "2889.3999802852",
                      highestBid: "0.032165",
                        high24hr: "0.03477",
                            last: "0.032163",
                       lowestAsk: "0.032301",
                         elapsed: "6ms",
                          result: "true",
                         low24hr: "0.03126",
                   percentChange: "0.82"                 } }
mbp:ccxt igorkroitor$
```

↑ Strange, huh? )

**Comment by kroitor** [comment]
I guess the only way to properly determine the base/quote volume for gateio is to divide one by the other or vice versa and then see which of the two divisions produces a result that is close to the current price... @ndubel what's your opinion on this?

**Comment by ndubel** [comment]
yes, I wanted to say the same

**Comment by kroitor** [comment]
There is a problem however: some of their markets have zero volumes (BTF/BTC, BOT/USDT, BOE/ETH, ...)

**Comment by ndubel** [comment]
so if volume is 0 - it's 0 in base and in quote. We can just check this before dividing

**Comment by ndubel** [comment]
haha, I discovered that when we use `fetchTicker` - it's all ok, and when `fetchTickers` volumes are confused

**Comment by kroitor** [comment]
@ndubel so we should simply invert them for `fetchTickers`, right?

**Comment by ndubel** [comment]
yes

**Comment by ndubel** [comment]
thank you!

**Pull request merged**
