### PR TITLE
php async & sync

### PR DESCRIPTION
**Pull request by ttodua**

### CODE REVIEW

**Comment by carlosmiei** [comment]
@ttodua did you test the patch? I still get the error

```
 php php/test/test_sync.php cryptocom 


[INFO] TESTING  php {"exchange":"cryptocom","symbol":"all","isWs":false} 

PHP Fatal error:  Uncaught AssertionError: Test files were not loaded in /Users/cjg/Git/ccxt10/ccxt/php/test/test_sync.php:341
Stack trace:
#0 /Users/cjg/Git/ccxt10/ccxt/php/test/test_sync.php(341): assert(false, 'Test files were...')
#1 /Users/cjg/Git/ccxt10/ccxt/php/test/test_sync.php(1581): ccxt\testMainClass->init('cryptocom', NULL)
#2 {main}
  thrown in /Users/cjg/Git/ccxt10/ccxt/php/test/test_sync.php on line 341

Fatal error: Uncaught AssertionError: Test files were not loaded in /Users/cjg/Git/ccxt10/ccxt/php/test/test_sync.php:341
Stack trace:
#0 /Users/cjg/Git/ccxt10/ccxt/php/test/test_sync.php(341): assert(false, 'Test files were...')
#1 /Users/cjg/Git/ccxt10/ccxt/php/test/test_sync.php(1581): ccxt\testMainClass->init('cryptocom', NULL)
#2 {main}
  thrown in /Users/cjg/Git/ccxt10/ccxt/php/test/test_sync.php on line 341
```

**Comment by ttodua** [comment]
i tested but not for cryptocom, for gate-io.
give me few mins, sorry for that glitch

**Comment by carlosmiei** [comment]
@ttodua hum, I don't think the exchange makes a difference here since the tests are equal for all of them

**Comment by ttodua** [comment]
did you run transpile locally?

**Comment by ttodua** [comment]
I'm switching back to this from another branch, give me 2 mins

**Comment by carlosmiei** [comment]
DEMO

```
 php php/test/test_sync.php gate


[INFO] TESTING  php {"exchange":"gate","symbol":"all","isWs":false} 

[INFO:MAIN] Exchange loaded 4509 symbols BTC/USDT, DASH/BTC, DOGE/BTC, ETH/BTC, LTC/BTC + more...
[INFO:MAIN] Selected SPOT SYMBOL: BTC/USDT
[INFO:MAIN] Selected SWAP SYMBOL: BTC/USDT:USDT
```

**Pull request merged**
