### PR TITLE
qryptos: cancelOrder: returns OrderNotFound on closed (filled) orders

### PR DESCRIPTION
**Pull request by mkutny**
My testcases started failing on this one - seems that the exchange fixed their response (they were responding with `null` which was quite stupid, IMHO).

### CODE REVIEW

**Comment by mkutny** [comment]
@kroitor , I'm not sure if you replaced OrderNotFound with InvalidOrder intentionally or not.

You introduced OrderNotFound somewhere near #383 and the main idea was to distinguish issues related to user input (wrong order types, statuses, and other inconsistencies) with issues related to order discovery.

Basically, I use OrderNotFound in the following scenario:
- you place an order
- you want to replace/cancel it
- but it's been fulfilled in between
- so you get an exception which informs you that your representation of an exchange is no more valid: you need to refetch a list of open orders, balances etc

**Comment by kroitor** [comment]
@mkutny initially, I thought InvalidOrder would be more representative of a *found, but not cancelable* order, but now I think, you're right, I will change it back to a more specific OrderNotFound for consistency with other exchanges (like Bittrex, for example)... Will change it in a few minutes.

**Comment by mkutny** [comment]
I'm perfectly fine with extending exceptions!

**Comment by kroitor** [comment]
> I'm perfectly fine with extending exceptions!

Ok, I will add an extended exception type for it to distinguish between different cases... Will rework this particular cancel-case for all exchanges hopefully soon. There's not so many of them so far...

**Comment by mkutny** [comment]
Well, it many of them return 'not found' then it does not worth the effort. We (users) will have to check for 'not found' anyway in this case.

**Pull request merged**
