### PR TITLE
Hitbtc ws order methods

### PR DESCRIPTION
**Pull request by samgermain**
```
% py hitbtc createOrderWs ADA/USDT:USDT limit buy 3 0.33                
Python v3.11.6
CCXT v4.1.56
hitbtc.createOrderWs(ADA/USDT:USDT,limit,buy,3,0.33)
{'amount': 3.0,
 'average': None,
 'clientOrderId': 't7eL9_2KcIO69vE4gs9oooHxn87ZV2nu',
 'cost': None,
 'datetime': None,
 'fee': None,
 'fees': [],
 'filled': None,
 'id': '119217624032',
 'info': {'client_order_id': 't7eL9_2KcIO69vE4gs9oooHxn87ZV2nu',
          'created_at': '2023-11-18T09:48:46.68Z',
          'id': 119217624032,
          'margin_mode': 'Cross',
          'post_only': False,
          'price': '0.33000',
          'quantity': '3',
          'quantity_cumulative': '0',
          'reduce_only': False,
          'report_type': 'new',
          'side': 'buy',
          'status': 'new',
          'symbol': 'ADAUSDT_PERP',
          'time_in_force': 'GTC',
          'type': 'limit',
          'updated_at': '2023-11-18T09:48:46.68Z'},
 'lastTradeTimestamp': None,
 'lastUpdateTimestamp': None,
 'postOnly': 'False',
 'price': 0.33,
 'reduceOnly': False,
 'remaining': None,
 'side': 'BUY',
 'status': 'open',
 'stopLossPrice': None,
 'stopPrice': None,
 'symbol': 'ADA/USDT:USDT',
 'takeProfitPrice': None,
 'timeInForce': 'GTC',
 'timestamp': None,
 'trades': [],
 'triggerPrice': None,
 'type': 'limit'}
 ```
 
 ```
 % py hitbtc createOrderWs ADA/USDT limit buy 3 0.33     
Python v3.11.6
CCXT v4.1.56
hitbtc.createOrderWs(ADA/USDT,limit,buy,3,0.33)
{'amount': 3.0,
 'average': None,
 'clientOrderId': 'KEQi3F2ylJkzcLdvcUfDEtPg1eztMUzS',
 'cost': None,
 'datetime': None,
 'fee': None,
 'fees': [],
 'filled': None,
 'id': '1130828464315',
 'info': {'client_order_id': 'KEQi3F2ylJkzcLdvcUfDEtPg1eztMUzS',
          'created_at': '2023-11-18T09:50:08.97Z',
          'id': 1130828464315,
          'post_only': False,
          'price': '0.3300000',
          'quantity': '3',
          'quantity_cumulative': '0',
          'report_type': 'new',
          'side': 'buy',
          'status': 'new',
          'symbol': 'ADAUSDT',
          'time_in_force': 'GTC',
          'type': 'limit',
          'updated_at': '2023-11-18T09:50:08.97Z'},
 'lastTradeTimestamp': None,
 'lastUpdateTimestamp': None,
 'postOnly': 'False',
 'price': 0.33,
 'reduceOnly': None,
 'remaining': None,
 'side': 'BUY',
 'status': 'open',
 'stopLossPrice': None,
 'stopPrice': None,
 'symbol': 'ADA/USDT',
 'takeProfitPrice': None,
 'timeInForce': 'GTC',
 'timestamp': None,
 'trades': [],
 'triggerPrice': None,
 'type': 'limit'}
 ```

### CODE REVIEW

**Comment by pcriadoperez** [comment]
Hi @samgermain, I wrote a few of these for other exchanges so I'm happy to help review it once you feel it's ready.

**Comment by carlosmiei** [comment]
[🤖 TestsManager 🤖  Id: 655a10a5303ff6da383e53d5]
 ```

Testing { exchanges: ["hitbtc", "hitbtc"], symbol: "all", debugKeys: { '--warnings': false, '--info': false }, langKeys: { '--ts': false, '--js': false, '--php': false, '--python': false, '--python-async': true, '--php-async': false }, exchangeSpecificFlags: { '--sandbox': false, '--verbose': false, '--private': false, '--privateOnly': true, '--info': false }, maxConcurrency: 5 } (run-tests.js:389)
[50%] Tested hitbtc FAIL (testExchange @ run-tests.js:303)
[100%] Tested hitbtc FAIL (testExchange @ run-tests.js:303)

FAILED hitbtc (Python 3 Async): (explain @ run-tests.js:320)

TESTING  py {'exchange': 'hitbtc', 'symbol': 'all'} 

Exchange loaded 1571 symbols BTC/USDT, DASH/BTC, DOGE/BTC, ETH/BTC, LTC/BTC + more...
Selected SPOT SYMBOL: BTC/USDT
Selected SWAP SYMBOL: BTC/USDT:USDT
[TEST_FAILURE] [AssertionError] Traceback (most recent call last):
  File "/root/ccxt/python/ccxt/test/test_async.py", line 328, in test_safe
    await self.test_method(methodName, exchange, args, isPublic)
  File "/root/ccxt/python/ccxt/test/test_async.py", line 308, in test_method
    await call_method(self.testFiles, methodNameInTest, exchange, skippedProperties, args)
  File "/root/ccxt/python/ccxt/test/test_async.py", line 133, in call_method
    return await getattr(testFiles[methodName], methodName)(exchange, skippedProperties, *args)
  File "/root/ccxt/python/ccxt/test/async/test_fetch_positions.py", line 27, in test_fetch_positions
    test_position(exchange, skipped_properties, method, positions[i], None, now)
  File "/root/ccxt/python/ccxt/test/base/test_position.py", line 44, in test_position
    test_shared_methods.assert_structure(exchange, skipped_properties, method, entry, format, emptyot_allowed_for)
  File "/root/ccxt/python/ccxt/test/base/test_shared_methods.py", line 87, in assert_structure
    assert value is not None, '\"' + string_value(key) + '\" key is expected to have a value' + log_text
AssertionError: "symbol" key is expected to have a value <<< hitbtc fetchPositions ::: {"info":{"symbol":"","type":"cross","leverage":"","created_at":"2023-10-29T14:46:13.235016478Z","updated_at":"2023-11-19T12:38:41.536343195Z","currencies":[{"code":"USDT","margin_balance":"12.25","reserved_orders":"","reserved_positions":"0"}],"positions":[{"id":"214271131","symbol":"ADAUSDT_PERP","margin_mode":"Cross","quantity":"0","price_entry":"0","price_margin_call":"","price_liquidation":"0","pnl":"0","created_at":"2023-11-18T09:20:18.815Z","updated_at":"2023-11-19T12:38:41.536Z"},{"id":"202471640","symbol":"TRXUSDT_PERP","margin_mode":"Cross","quantity":"0","price_entry":"0","price_margin_call":"","price_liquidation":"0","pnl":"0","created_at":"2023-10-29T14:46:13.235Z","updated_at":"2023-11-19T12:38:41.536Z"}]},"id":null,"symbol":null,"notional":null,"marginMode":"cross","marginType":"cross","liquidationPrice":0.0,"entryPrice":0.0,"unrealizedPnl":null,"percentage":null,"contracts":0.0,"contractSize":null,"markPrice":null,"lastPrice":null,"side":null,"hedged":null,"timestamp":1700397521536,"datetime":"2023-11-19T12:38:41.536343195Z","lastUpdateTimestamp":null,"maintenanceMargin":null,"maintenanceMarginPercentage":null,"collateral":12.25,"initialMargin":null,"initialMarginPercentage":null,"leverage":null,"marginRatio":null,"stopLossPrice":null,"takeProfitPrice":null} >>> 
 hitbtc fetchPositions ["BTC/USDT:USDT"]
[TEST_FAILURE] Failed private tests [swap]: fetchPositions (explain @ run-tests.js:323)

FAILED hitbtc (Python 3 Async): (explain @ run-tests.js:320)

TESTING  py {'exchange': 'hitbtc', 'symbol': 'all'} 

Exchange loaded 1571 symbols BTC/USDT, DASH/BTC, DOGE/BTC, ETH/BTC, LTC/BTC + more...
Selected SPOT SYMBOL: BTC/USDT
Selected SWAP SYMBOL: BTC/USDT:USDT
[TEST_FAILURE] [AssertionError] Traceback (most recent call last):
  File "/root/ccxt/python/ccxt/test/test_async.py", line 328, in test_safe
    await self.test_method(methodName, exchange, args, isPublic)
  File "/root/ccxt/python/ccxt/test/test_async.py", line 308, in test_method
    await call_method(self.testFiles, methodNameInTest, exchange, skippedProperties, args)
  File "/root/ccxt/python/ccxt/test/test_async.py", line 133, in call_method
    return await getattr(testFiles[methodName], methodName)(exchange, skippedProperties, *args)
  File "/root/ccxt/python/ccxt/test/async/test_fetch_positions.py", line 27, in test_fetch_positions
    test_position(exchange, skipped_properties, method, positions[i], None, now)
  File "/root/ccxt/python/ccxt/test/base/test_position.py", line 44, in test_position
    test_shared_methods.assert_structure(exchange, skipped_properties, method, entry, format, emptyot_allowed_for)
  File "/root/ccxt/python/ccxt/test/base/test_shared_methods.py", line 87, in assert_structure
    assert value is not None, '\"' + string_value(key) + '\" key is expected to have a value' + log_text
AssertionError: "symbol" key is expected to have a value <<< hitbtc fetchPositions ::: {"info":{"symbol":"","type":"cross","leverage":"","created_at":"2023-10-29T14:46:13.235016478Z","updated_at":"2023-11-19T12:38:41.536343195Z","currencies":[{"code":"USDT","margin_balance":"12.25","reserved_orders":"","reserved_positions":"0"}],"positions":[{"id":"214271131","symbol":"ADAUSDT_PERP","margin_mode":"Cross","quantity":"0","price_entry":"0","price_margin_call":"","price_liquidation":"0","pnl":"0","created_at":"2023-11-18T09:20:18.815Z","updated_at":"2023-11-19T12:38:41.536Z"},{"id":"202471640","symbol":"TRXUSDT_PERP","margin_mode":"Cross","quantity":"0","price_entry":"0","price_margin_call":"","price_liquidation":"0","pnl":"0","created_at":"2023-10-29T14:46:13.235Z","updated_at":"2023-11-19T12:38:41.536Z"}]},"id":null,"symbol":null,"notional":null,"marginMode":"cross","marginType":"cross","liquidationPrice":0.0,"entryPrice":0.0,"unrealizedPnl":null,"percentage":null,"contracts":0.0,"contractSize":null,"markPrice":null,"lastPrice":null,"side":null,"hedged":null,"timestamp":1700397521536,"datetime":"2023-11-19T12:38:41.536343195Z","lastUpdateTimestamp":null,"maintenanceMargin":null,"maintenanceMarginPercentage":null,"collateral":12.25,"initialMargin":null,"initialMarginPercentage":null,"leverage":null,"marginRatio":null,"stopLossPrice":null,"takeProfitPrice":null} >>> 
 hitbtc fetchPositions ["BTC/USDT:USDT"]
[TEST_FAILURE] Failed private tests [swap]: fetchPositions (explain @ run-tests.js:323)
FAIL ["hitbtc", "hitbtc"] (run-tests.js:405)
All done, 2 failed (run-tests.js:410)


```

**Comment by carlosmiei** [comment]
DEMO

```
 p hitbtc cancelOrderWs "KEQi3F2ylJkzcLdvcUfDEtPg1eztMUzS" "TRX/USDT"
Python v3.11.5
CCXT v4.1.56
hitbtc.cancelOrderWs(KEQi3F2ylJkzcLdvcUfDEtPg1eztMUzS,TRX/USDT)
{'amount': 3.0,
 'average': None,
 'clientOrderId': 'KEQi3F2ylJkzcLdvcUfDEtPg1eztMUzS',
 'cost': None,
 'datetime': None,
 'fee': None,
 'fees': [],
 'filled': None,
 'id': '1130828464315',
 'info': {'client_order_id': 'KEQi3F2ylJkzcLdvcUfDEtPg1eztMUzS',
          'created_at': '2023-11-18T09:50:08.97Z',
          'id': 1130828464315,
          'post_only': False,
          'price': '0.3300000',
          'quantity': '3',
          'quantity_cumulative': '0',
          'report_type': 'canceled',
          'side': 'buy',
          'status': 'canceled',
          'symbol': 'ADAUSDT',
          'time_in_force': 'GTC',
          'type': 'limit',
          'updated_at': '2023-11-19T12:21:54.52Z'},
 'lastTradeTimestamp': None,
 'lastUpdateTimestamp': None,
 'postOnly': 'False',
 'price': 0.33,
 'reduceOnly': None,
 'remaining': None,
 'side': 'BUY',
 'status': 'canceled',
 'stopLossPrice': None,
 'stopPrice': None,
 'symbol': 'ADA/USDT',
 'takeProfitPrice': None,
 'timeInForce': 'GTC',
 'timestamp': None,
 'trades': [],
 'triggerPrice': None,
 'type': 'limit'}
```

```
 p hitbtc createOrderWs "TRX/USDT" market buy 10   
Python v3.11.5
CCXT v4.1.56
hitbtc.createOrderWs(TRX/USDT,market,buy,10)
{'amount': 10.0,
 'average': None,
 'clientOrderId': '8LrONDfQyoD0V1HvngiPDbIbEpgSuHYF',
 'cost': None,
 'datetime': None,
 'fee': None,
 'fees': [],
 'filled': None,
 'id': '1131419512674',
 'info': {'client_order_id': '8LrONDfQyoD0V1HvngiPDbIbEpgSuHYF',
          'created_at': '2023-11-19T13:44:43.271Z',
          'id': 1131419512674,
          'post_only': False,
          'quantity': '10',
          'quantity_cumulative': '0',
          'report_type': 'new',
          'side': 'buy',
          'status': 'new',
          'symbol': 'TRXUSDT',
          'time_in_force': 'FOK',
          'type': 'market',
          'updated_at': '2023-11-19T13:44:43.271Z'},
 'lastTradeTimestamp': None,
 'lastUpdateTimestamp': None,
 'postOnly': 'False',
 'price': None,
 'reduceOnly': None,
 'remaining': None,
 'side': 'BUY',
 'status': 'open',
 'stopLossPrice': None,
 'stopPrice': None,
 'symbol': 'TRX/USDT',
 'takeProfitPrice': None,
 'timeInForce': 'FOK',
 'timestamp': None,
 'trades': [],
 'triggerPrice': None,
 'type': 'market'}
```

```p hitbtc fetchOpenOrdersWs                         
Python v3.11.5
CCXT v4.1.56
hitbtc.fetchOpenOrdersWs()
[{'amount': 10.0,
  'average': None,
  'clientOrderId': '18ycNnqxGasZmcZgJsBaRmM_wPnlQnLj',
  'cost': None,
  'datetime': None,
  'fee': None,
  'fees': [],
  'filled': None,
  'id': '1131419972513',
  'info': {'client_order_id': '18ycNnqxGasZmcZgJsBaRmM_wPnlQnLj',
           'created_at': '2023-11-19T13:46:14.328Z',
           'id': 1131419972513,
           'post_only': False,
           'price': '0.0500000',
           'quantity': '10',
           'quantity_cumulative': '0',
           'report_type': 'status',
           'side': 'buy',
           'status': 'new',
           'symbol': 'TRXUSDT',
           'time_in_force': 'GTC',
           'type': 'limit',
           'updated_at': '2023-11-19T13:46:14.328Z'},
  'lastTradeTimestamp': None,
  'lastUpdateTimestamp': None,
  'postOnly': 'False',
  'price': 0.05,
  'reduceOnly': None,
  'remaining': None,
  'side': 'BUY',
  'status': 'open',
  'stopLossPrice': None,
  'stopPrice': None,
  'symbol': 'TRX/USDT',
  'takeProfitPrice': None,
  'timeInForce': 'GTC',
  'timestamp': None,
  'trades': [],
  'triggerPrice': None,
  'type': 'limit'}]
```

```
 p hitbtc cancelAllOrdersWs                         
Python v3.11.5
CCXT v4.1.56
hitbtc.cancelAllOrdersWs()
[{'amount': 10.0,
  'average': None,
  'clientOrderId': '18ycNnqxGasZmcZgJsBaRmM_wPnlQnLj',
  'cost': None,
  'datetime': None,
  'fee': None,
  'fees': [],
  'filled': None,
  'id': '1131419972513',
  'info': {'client_order_id': '18ycNnqxGasZmcZgJsBaRmM_wPnlQnLj',
           'created_at': '2023-11-19T13:46:14.328Z',
           'id': 1131419972513,
           'post_only': False,
           'price': '0.0500000',
           'quantity': '10',
           'quantity_cumulative': '0',
           'report_type': 'canceled',
           'side': 'buy',
           'status': 'new',
           'symbol': 'TRXUSDT',
           'time_in_force': 'GTC',
           'type': 'limit',
           'updated_at': '2023-11-19T13:46:14.328Z'},
  'lastTradeTimestamp': None,
  'lastUpdateTimestamp': None,
  'postOnly': 'False',
  'price': 0.05,
  'reduceOnly': None,
  'remaining': None,
  'side': 'BUY',
  'status': 'canceled',
  'stopLossPrice': None,
  'stopPrice': None,
  'symbol': 'TRX/USDT',
  'takeProfitPrice': None,
  'timeInForce': 'GTC',
  'timestamp': None,
  'trades': [],
  'triggerPrice': None,
  'type': 'limit'}]
```

**Comment by samgermain** [comment]
@carlosmiei I was going to add to those other methods in the next PR, it's just easier to merge smaller PRs, sometimes I already have those branches coded also, but I'm waiting for the first PR to get merged, you're free to ask if I missed the methods by mistake also though

**Pull request merged**
