### PR TITLE
Huobi fetchTicker / fetchTickers bid, ask, bidVolume, askVolume fix

### PR DESCRIPTION
**Pull request by arielorvits**

### CODE REVIEW

**Comment by kroitor** [comment]
@arielorvits hi! Thx for the edits. A quick question – can you please share the details (verbose request/response) about this PR? When I run it on my side I still see those fields as arrays:

```
huobipro.fetchTicker (ETH/BTC)
fetch:
 huobipro GET https://api.huobi.pro/market/detail/merged?symbol=ethbtc
Request:
 {
  'User-Agent': 'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 ' +
    '(KHTML, like Gecko) Chrome/39.0.2171.71 Safari/537.36'
}
 undefined

handleRestResponse:
 huobipro GET https://api.huobi.pro/market/detail/merged?symbol=ethbtc 200 OK
Response:
 {
  'Cf-Cache-Status': 'DYNAMIC',
  'Cf-Ray': '590f43623d43dfeb-FRA',
  'Cf-Request-Id': '029d6871630000dfeb53a5e200000001',
  Connection: 'keep-alive',
  'Content-Encoding': 'gzip',
  'Content-Type': 'application/json; charset=utf-8',
  Date: 'Sat, 09 May 2020 23:40:02 GMT',
  'Expect-Ct': 'max-age=604800, ' +
    'report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"',
  Server: 'cloudflare',
  'Set-Cookie': '__cfduid=d2ade9620a47cf5137268332fb40d4f601589067602; expires=Mon, ' +
    '08-Jun-20 23:40:02 GMT; path=/; domain=.huobi.pro; HttpOnly; SameSite=Lax; ' +
    'Secure',
  'Transfer-Encoding': 'chunked',
  'X-Request-Id': '181031ab4db5139fc7f99a9aebbc6095'
}
 {"status":"ok","ch":"market.ethbtc.detail.merged","ts":1589067602380,"tick":{"amount":77603.6954,"open":0.021548,"close":0.022,"high":0.022049,"id":204839143486,"count":38239,"low":0.02148,"version":204839143486,"ask":[0.022001,30.2371],"vol":1693.2741125342,"bid":[0.022,10.4737]}}

{        symbol:   "ETH/BTC",
      timestamp:    1589067602380,
       datetime:   "2020-05-09T23:40:02.380Z",
           high:    0.022049,
            low:    0.02148,
            bid:    0.022,
      bidVolume:    10.4737,
            ask:    0.022001,
      askVolume:    30.2371,
           vwap:    0.021819503617790347,
           open:    0.021548,
          close:    0.022,
           last:    0.022,
  previousClose:    undefined,
         change:    0.00045199999999999754,
     percentage:    2.097642472619257,
        average:    0.021774,
     baseVolume:    77603.6954,
    quoteVolume:    1693.2741125342,
           info: {  amount:    77603.6954,
                      open:    0.021548,
                     close:    0.022,
                      high:    0.022049,
                        id:    204839143486,
                     count:    38239,
                       low:    0.02148,
                   version:    204839143486,
                       ask: [0.022001, 30.2371],
                       vol:    1693.2741125342,
                       bid: [0.022, 10.4737]     } }
mbp:ccxt igorkroitor$
```

Thx again!

**Comment by kroitor** [comment]
@arielorvits looks like, the format of `fetchTickers` differs from `fetchTicker` in that regard.

**Comment by arielorvits** [comment]
@kroitor yes, you're right. I changed that because of fetchTickers. missed that it's not the same like fetchTikcer. so maybe you can leave the "if(array)" as is, and add "else" with my code

**Comment by kroitor** [comment]
@arielorvits no worries, thx for your involvement! I've uploaded a minor edit to it, will merge shortly.

**Comment by arielorvits** [comment]
you are so fast... king!

**Pull request merged**
