### PR TITLE
Some eslint fixes

### PR DESCRIPTION
**Pull request by Deathamns**

### CODE REVIEW

**Comment by kroitor** [comment]
Oops, the last one was probably not necessary, it's mostly a linting problem, not a syntax problem... In other words, that semicolon will break the transpiler now. Not very intuitive, it's just that the linting rules were added not so long ago and it does not cover the entire set of code yet. Can you revert the last commit, plz ?

**Comment by kroitor** [comment]
Hooray, it didn't break it ) Interesting though )

**Comment by Deathamns** [comment]
I messed it up though, rebasing...

**Comment by kroitor** [comment]
@Deathamns if you can please keep one request per exchange in future (multiple prs for many requests). I will merge this particular PR anyway, it would just make it easier later (less conflicts). Thx again for your help!

**Comment by mkutny** [comment]
It has found actual bugs... Cool!

Thanks, @Deathamns !

**Comment by mkutny** [comment]
> Also, related to PR #1197, I could have fixed those too, but I saw that you was not sure about them, and @mkutny already wanted to fix them, so I didn't touch them.

I didn't plan to fix them in a single row, actually. Rather, as I now have the linter switched 'on' by default, my approach was to fix them one-by-one along the way while fixing other issues.

There are quite a lot of `eqeqeu`, so if you address some of them I won't be upset at all )

**Comment by Deathamns** [comment]
Alright, I'll change them as I encounter them...

Last two:
1) any reason the `use strict` directive is in double quotes, instead of single?
2) any reason for the missing last semicolon after the `module.exports = class ex extends Exchange {}`?

**Comment by kroitor** [comment]
@Deathamns 

1. no particular reason
2. In JS we would like to not use `;`, where it is unnecessary, and only add to transpile it properly to other languages and for that the last ; seems to be unnecessary, as long as regex-matching rules for these syntax constructs are pretty-much hardcoded. In other words, the reasoning for not putting it there was: why have it there in the first place? Not needed in either of supported languages. I would better add an exception to the linter somehow, if it is possible, then add colons everywhere, they kinda add unnecessary noise, imho. Yet, if you think differently or have some arguments for this or that, your opinion is important to me, and I would be interested to know what @mkutny says on this.

**Comment by mkutny** [comment]
1. If we switch to single quotes we'll be able to add one more rule to the linter and it'll bring more consistency.

2. With regard to the `;` - there are two opposite camps, each with valid arguments for pro- and against them. I have my personal preferences on the issue but suppress them in favor of more consistency as more consistency leads to fewer questions. Basically, we can have different linter rules for different folders: requiring semicolons in `./js/` and forbidding them in `./js/base/`, for example.

**Comment by kroitor** [comment]
> I have my personal preferences on the issue but suppress them in favor of more consistency as more consistency leads to fewer questions.

This is reasonable.

> Basically, we can have different linter rules for different folders: requiring semicolons in ./js/ and forbidding them in ./js/base/, for example.

Though this is against the previous point about consistency, I tend to go for adding special cases for folders. Basically, I prefer less noise over consistency. It feels like a more flexible approach to me, as sometimes consistency really introduces some unnecessary burden. I'm still ready to go for consistency, if you insist.

**Comment by Deathamns** [comment]
I don't want to change your mind, I just wanted to respect the coding style.

But here are my personal opinions for these cases (since they cannot be more than just opinions if they are different "working" ways).

1) Since in JavaScript it doesn't matter which one, it's simply for the sake of consistency. PHP is a different story, but since ccxt is transpiled from JS, this is not an issue here.
2) Semicolons are actually required in JavaScript, it's just there's this language feature called ASI (automatic semicolon insertion), which in some cases can figure out where to insert semicolons. And that's the issue; it works only in some cases, in other cases it can cause bugs (I'm lazy to pull examples here, but probably you already know about this). For me, this one defected behavior is enough to consider ASI as non-existent. Sure, again, in ccxt it might not be an issue, because of the crippled down syntax used for the transpiler, though it's still JavaScript, so I look at it that way.
You may say that if you don't use semicolons it's less noise, but for me, correct code and consistency is less noise. Perspectives, unnecessary to argue about them...

**Comment by mkutny** [comment]
>> I have my personal preferences on the issue but suppress them in favor of more consistency as more consistency leads to fewer questions.

> This is reasonable.

Actually, I've found that sentence ambiguous and removed it promptly, but you managed to catch it anyway )

I meant that forbidding unnecessary semicolons in `./js/base` and forcing them in `./js/` would lead to more consistency and less noise than the currently mixed approach in `./js`.

We, contributors, are usually touching only `./js` so for us it's quite consistent anyway.

**Comment by kroitor** [comment]
@mkutny I would go this way then. We will need to edit the linter rules. If you can help with that, I would then take the other issues.

**Comment by mkutny** [comment]
That actually boils down to the overall linting approach.

I've been under assumption that you prefer to stay away from the linter (as it was not setup) but then noticed empty `.eslintrc` and decided to make it as little intrusive as possible just for `./js` files to help fight with transpilation issues.

With the current setup, it's not standing in your way. Once we remove the reds we can set it as a part of CI pipeline to check just `./js` part of the project, no more.

If we stick to the above approach then there is actually nothing to do from my side (except fixing the issues and updating the file with new rules if we find them).

On the other hand, you might want to put all the '*.js' files under its supervision. In this case, I'll split it among folders. And then it might be wise to add a preset rules package, like this one https://github.com/standard/standard, instead of coding all that rules by hands. How do you feel about that?

**Comment by kroitor** [comment]
> How do you feel about that?

I'm all for it, however, it currently shows linting errors even in the base files, name the `js/Exchange.js`, where most of linting errors aren't errors, that is why I asked about splitting the ruleset somehow. Is it possible at all?

**Comment by mkutny** [comment]
>  it currently shows linting errors even in the base files

Try to run it as `npm run lint "js/*.js"` and see if it solves the problem. For me it doesn't look into subdirs.


>  I asked about splitting the ruleset somehow. Is it possible at all?

I'm not a linting expert, honestly, but I'm sure it is possible. Just give me some time )

Maybe @Deathamns have more experience with it and can tell right away. BTW, I like semicolons too! )

**Comment by kroitor** [comment]
> Try to run it as npm run lint "js/*.js" and see if it solves the problem. For me it doesn't look into subdirs.

I'm not running it by hand, my VS Code detects it in the folder automatically and highlights the errors as I edit the code, so it currently covers all sources, if you disregard the launching method and account for the contents of `.eslintrc` only. However, if you're not familiar with (as myself), I will google it up quickly. ) Will get to it very soon.

**Comment by mkutny** [comment]
> I'm not running it by hand, my VS Code detects it in the folder automatically

Oh.
Eslit says that they support per-directory config: https://eslint.org/docs/user-guide/configuring#using-configuration-files

> ESLint will automatically look for configuration files in the directory of the file to be linted, and in successive parent directories all the way up to the root directory of the filesystem. This option is useful when you want different configurations for different parts of a project

Basically, if you put empty `.eslintrc` into `js/base/` it should block the linter from reporting. But I'm not sure if VS Code obeys this logic, it may be configured by other means. Now I understand why you kept those files empty.

**Comment by kroitor** [comment]
No worries about the conflicts here, will merge.

**Comment by Deathamns** [comment]
> I'm not sure if VS Code obeys this logic

It does, but I guess `.eslintrc` files are handled by eslint, so it would work on other text editors too.

**Comment by kroitor** [comment]
@Deathamns yep, afaik Sublime also has this feature, most modern extendable editors will integrate intellisense + linter in some way.

**Comment by Deathamns** [comment]
Left an accidental `let` instead of `const` in lykke.

**Pull request merged**
