### PR TITLE
Decoin New Exchange

### PR DESCRIPTION
**Pull request by decoin-exchange**
Hi @kroitor ,
Please kindly assist us to merge this integration for the **[Decoin Exchange](https://www.decoin.io/)** to **CCXT**.
Let us know if anything is missing or have some issues.

Thanks!

### CODE REVIEW

**Comment by kroitor** [comment]
@decoin-exchange hi! Thank your for the PR! We will get to it and will review and merge it as soon as we can. If you wish to speed it up, please reach out to us at info@ccxt.trade.

**Comment by decoin-exchange** [comment]
@kroitor Thanks for the response, really appreciate it, Let us know in case something is missing or needed for integration from our end. thanks

**Comment by decoin-exchange** [comment]
Hi, @kroitor any news or time estimation when it will be merged. Let me know.
Thanks

**Comment by decoin-exchange** [comment]
Hi, @kroitor any updates regarding Decoin integration. Let us know
Thanks

**Comment by kroitor** [comment]
@decoin-exchange hi! Hope to get to it as soon as possible.

**Comment by decoin-exchange** [comment]
@kroitor  Thank you so much really appreciate it

**Review by jonhpham — APPROVED** [review]

**Comment by decoin-exchange** [comment]
Hi, Thanks for approval
Any time estimation of when it will appear on CCXT official repository.
Thanks

**Comment by kroitor** [comment]
@decoin-exchange we will get to it as soon as we can, thx for your patience!

**Comment by decoin-exchange** [comment]
Hi @kroitor any news?
Thanks

**Comment by decoin-exchange** [comment]
Guys any news?

**Comment by decoin-exchange** [comment]
Hi @kroitor 
Its been quite a while now, please let us know how we can help accelerate the process technically. Thanks

**Comment by ttodua** [comment]
dead exchange

**Pull request closed without merging**
