### PR TITLE
binance proper cost

### PR DESCRIPTION
**Pull request by benediamond**
re: #1175, #1011. _work in progress, not tested_.

### CODE REVIEW

**Comment by benediamond** [comment]
@kroitor do you need any help testing this, or are we good to go?

**Comment by kroitor** [comment]
Good to go, but your help with testing it is always welcome anyway ) Will merge shortly )

**Comment by benediamond** [comment]
@kroitor actually, there is an issue... even when `self.options['newOrderRespType'] == 'FULL'`, then the complete information is only provided _directly_ by the response to `create_order` (i.e., `privatePostOrder`), but it is missing from subsequent calls to `fetch_order` (i.e., `privateGetOrder`). So, this code will only actually execute when `parseOrder` is called by `createOrder`. But not when it is called by `fetchOrder`.

Therefore, if e.g. the trade doesn't fill right away, if one wants to know guaranteed the actual market price at which it was executed, then one must call `fetchMyTrades`, it would appear.

**Comment by kroitor** [comment]
@benediamond you're right, that's why i was talking of market orders initially. But anyways, this is the best we can do at this point, so I'm going to merge this anyways.

**Pull request merged**
