### PR TITLE
update zb.js

### PR DESCRIPTION
**Pull request by lechengyu**
fix sign,cancelOrder,fetchOrder methods and add some methods base on the offical document.  

Fixes issue: #1024 
Relates to: #1269

### CODE REVIEW

**Comment by kroitor** [comment]
Thank you! Will spend some time merging and refactoring this, for commonCurrencyCode. Hope to finish it soon.

**Comment by lechengyu** [comment]
Hope to merge it soon , I have test all these methods and it works fine.

**Comment by redindian** [comment]
@lechengyu Took the liberty of copying your code and rewriting a few parts the causes transpile errors. See: https://github.com/ccxt/ccxt/pull/1717

**Comment by kroitor** [comment]
This PR will be merged today.

**Pull request merged**
