### PR TITLE
liqui: no such endpoint TransHistory

### PR DESCRIPTION
**Pull request by kornrunner**
At least not according to https://liqui.io/api (and requests to it fail, as well)

### CODE REVIEW

**Comment by kroitor** [comment]
Unfortunately, it will probably break other exchanges, derived from Liqui... Basically, their API is 99% similar, but differs in one endpoint name. We might need to carry the entire API definition to child classes then, otherwise it will most likely break one of them (DSX, Tidex, Yobit, etc).

**Comment by kornrunner** [comment]
You're right, WEX has `TransHistory`.

**Comment by kornrunner** [comment]
Ok, as far as I've checked:
- `liqui` does not have this endpoint, so this change should be fine
- `tidex` also does not have this endpoint, and inherits `liqui` stuff directly, so that's fine
- `yobit` overrides API endpoints (doesn't have this one listed)
- `wex` overrides API endpoints (has this one listed in docs and in code)
- `dsx` overrides API endpoints, but seems completely wrong as their API changed in the meantime ? https://dsx.docs.apiary.io/

So, IMO this should be ok to merge

**Comment by kroitor** [comment]
> overrides API endpoints, but seems completely wrong as their API changed in the meantime ?

Could easily be the case. I haven't looked into it for a long time now, need to revise it. Thankfully, @mkutny submitted multiple new tests for that. Will rework DSX asap.

Merging this PR anyway ) Thank you for your effort!

**Comment by mkutny** [comment]
> @mkutny submitted multiple new tests for that

Thanks for the attribution ) Feel that I need to clarify their scope so one will not have over expectations on test coverage )

From all the tests that I've done only deep tests of ticker properties are being run at the moment (well, half-deeply tests I'd say as part of them were commented out).

Other tests are not merged yet. Funny, while being not run they still discovered a bug in bibox implementation )

Have some more waiting in the queue, just don't want to increase PRs backlog. At the end, they will cover all trading actions which are possible to execute with zero balance (that's basically, testing of error handling).

**Comment by kornrunner** [comment]
> Other tests are not merged yet. Funny, while being not run they still discovered a bug in bibox implementation )

Ha, neat that! I'm still not using `bibox`, it was written mostly by following api docs & just tested what `js/test.js` did at the moment. Looking forward to more tests of any sort. 

I've tried to do some tests in PHP in my own fork, some of PRs I've submitted are based on it's findings. Yet, I'm not happy with the state of PHP tests I did, so never submitted any of them to the main repo.

**Comment by mkutny** [comment]
> I'm still not using bibox, it was written mostly by following api docs

It's amazing )

I'm always surprised when someone is able to make a pretty much workable solution without throughout testing ) I'm definitely not that type of a guy )

It failed just once if you're curious and that was a minor issue: https://travis-ci.org/ccxt/ccxt/builds/328398483?utm_source=github_status&utm_medium=notification

And I'm actually glad that project acquired someone with deep PHP knowledge and proactive position ) Hope you'll be hanging here for a while )

**Comment by kroitor** [comment]
+1 for hanging here for a while )

**Pull request merged**
