### PR TITLE
Exmo string math

### PR DESCRIPTION
**Pull request by samgermain**
```
 % exmo createOrder ADA/USDT market buy 10 0.45
Debugger attached.
2022-09-14T23:00:36.354Z
Node.js: v18.4.0
CCXT v1.93.52
(node:9139) ExperimentalWarning: The Fetch API is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
exmo.createOrder (ADA/USDT, market, buy, 10, 0.45)
2022-09-14T23:00:39.212Z iteration 0 passed in 580 ms
```
```JavaScript
{
  id: '31055748322',
  info: { result: true, error: '', order_id: '31055748322' },
  timestamp: 1663196439211,
  datetime: '2022-09-14T23:00:39.211Z',
  lastTradeTimestamp: undefined,
  status: 'open',
  symbol: 'ADA/USDT',
  type: 'market',
  side: 'buy',
  price: 0.45,
  cost: undefined,
  amount: 10,
  remaining: 10,
  filled: 0,
  fee: undefined,
  trades: undefined,
  clientOrderId: undefined,
  average: undefined
}
```
```
2022-09-14T23:00:39.212Z iteration 1 passed in 580 ms
```
---------------------------
```
2022-09-14T22:58:50.172Z
Node.js: v18.4.0
CCXT v1.93.52
exmo.fetchCurrencies ()
2022-09-14T22:58:54.307Z iteration 0 passed in 1338 ms
```
```JavaScript
{
  VLX: {
    id: 'VLX',
    code: 'VLX',
    name: 'Velas',
    type: 'crypto',
    active: false,
    deposit: false,
    withdraw: false,
    fee: undefined,
    precision: 1e-8,
    limits: {
      deposit: { min: undefined, max: undefined },
      withdraw: { min: undefined, max: undefined }
    },
    info: [
      {
        type: 'deposit',
        name: 'VLX (Legacy)',
        currency_name: 'VLX',
        min: '0.1',
        max: '10000000',
        enabled: false,
        comment: 'Minimum deposit amount is 0.1 VLX',
        commission_desc: '0%',
        currency_confirmations: '1'
      },
      {
        type: 'withdraw',
        name: 'VLX (Legacy)',
        currency_name: 'VLX',
        min: '5',
        max: '1000000',
        enabled: false,
        comment: '',
        commission_desc: '1 VLX',
        currency_confirmations: '1'
      }
    ]
  },
  ...
  PLCU: {
    id: 'PLCU',
    code: 'PLCU',
    name: undefined,
    type: 'crypto',
    active: true,
    deposit: true,
    withdraw: false,
    fee: undefined,
    precision: 1e-8,
    limits: {
      deposit: { min: 0.0001, max: 1000000 },
      withdraw: { min: undefined, max: undefined }
    },
    info: [
      {
        type: 'deposit',
        name: 'PLCU',
        currency_name: 'PLCU',
        min: '0.0001',
        max: '1000000',
        enabled: true,
        comment: '',
        commission_desc: '',
        currency_confirmations: '30'
      },
      {
        type: 'withdraw',
        name: 'PLCU',
        currency_name: 'PLCU',
        min: '0.001',
        max: '100000',
        enabled: false,
        comment: '',
        commission_desc: '0.0005 PLCU',
        currency_confirmations: '60'
      }
    ]
  }
}
```
```
2022-09-14T22:58:54.307Z iteration 1 passed in 1338 ms
```

-----------------------

```
2022-09-14T23:00:17.957Z
Node.js: v18.4.0
CCXT v1.93.52
exmo.fetchTransactionFees ()
2022-09-14T23:00:21.772Z iteration 0 passed in 1424 ms
```
```JavaScript
{
  info: { ... },
  withdraw: {
    VLX: 1,
    BTC: 0.0005,
    LTC: 0.01,
    DOGE: 5,
    DASH: 0.002,
    ETH: 0.004,
    WAVES: 1,
    ZEC: 0.001,
    USDT: 1,
    XRP: 0.02,
    ETC: 0.01,
    BCH: 0.001,
    BTG: 0.001,
    EOS: 0.05,
    XLM: 0.01,
    OMG: 3.3,
    TRX: 1,
    ADA: 1,
    NEO: 0,
    GAS: 0,
    ZRX: 28,
    GUSD: 7,
    XEM: 5,
    SMART: 0.5,
    QTUM: 0.01,
    DAI: 15,
    MKR: 0.002,
    USDC: 10,
    ROOBEE: 4000,
    DCR: 0.01,
    XTZ: 0.1,
    EXM: 50,
    CRON: 0.5,
    ONT: 1,
    ONG: 5,
    ALGO: 0.01,
    ATOM: 0.05,
    WXT: 50,
    CHZ: 30,
    ONE: 1,
    IQN: 3,
    PRQ: 20,
    HAI: 50,
    LINK: 0.5,
    UNI: 1.4,
    YFI: 0.0002,
    GNY: 10,
    XYM: 0.5,
    BTCV: 50,
    DOT: 0.1,
    TON: 0.1,
    SHIB: 900000,
    'GMT Token': 90,
    SOL: 0.01,
    NEAR: 0.05,
    DEBT: 0.05,
    PLCU: 0.0005
  },
  deposit: {
    VLX: 0,
    BTC: 0,
    LTC: 0,
    DOGE: 0,
    DASH: 0,
    ETH: 0,
    WAVES: 0,
    ZEC: 0,
    USDT: 0,
    XRP: 0,
    ETC: 0,
    BCH: 0,
    BTG: 0,
    EOS: 0,
    XLM: 0,
    OMG: 0.1,
    TRX: 0,
    ADA: 0,
    NEO: 0,
    GAS: 0,
    ZRX: 0,
    GUSD: 0,
    XEM: 0,
    SMART: 0,
    QTUM: 0,
    DAI: 0,
    MKR: 0,
    USDC: 0,
    ROOBEE: 0,
    DCR: 0,
    XTZ: undefined,
    EXM: 0,
    CRON: 0,
    ONT: 0,
    ONG: 0,
    ALGO: 0,
    ATOM: 0,
    WXT: 0,
    CHZ: 0,
    ONE: undefined,
    IQN: 0,
    PRQ: 0,
    HAI: undefined,
    LINK: 0,
    UNI: 0,
    YFI: 0,
    GNY: 0,
    BTCV: 0,
    DOT: undefined,
    TON: 0,
    SHIB: 0,
    'GMT Token': 0,
    SOL: undefined,
    NEAR: 0,
    DEBT: undefined,
    PLCU: undefined
  }
}
```
```
2022-09-14T23:00:21.772Z iteration 1 passed in 1424 ms
```

### CODE REVIEW

**Comment by frosty00** [comment]
we should remove most of that code that is handled in safeOrder already

**Comment by samgermain** [comment]
> we should remove most of that code that is handled in safeOrder already

line 1529 and 687 are the only 2 lines that look like they could be changed, the other ones are changing arithemetic on exchange responses to string math

**Comment by frosty00** [comment]
@samgermain look at the code inside of safeOrder, all of the code that does arithmetic inside of parseOrder should be removed

**Comment by samgermain** [comment]
We still need this PR even if we need to remove those parts

**Pull request closed without merging**
