### PR TITLE
Fix python datetime functions

### PR DESCRIPTION
**Pull request by meold**

### CODE REVIEW

**Comment by frosty00** [comment]
Is it worth rewriting these tests in js and transpiling with the new general transpiller `transpileJavaScriptToPythonAndPHP`

**Comment by kroitor** [comment]
> Is it worth rewriting these tests in js and transpiling with the new general transpiller transpileJavaScriptToPythonAndPHP?

Yep, the ultimate goal is to unify the tests as well, one day... some day... )) These tests seem to mirror each other line-to-line, so I guess we will do something similar to what we did with precision tests. Feel free to do this or just let me know if you want me to unify them.

**Comment by kroitor** [comment]
@meold first of, thanks for the contribution. I'm watching the edits you make, good job so far! ) Now Travis says that it cannot divide the timestamp by a thousand in another method, where it previously could. This means that the new version of `parse8601` function is now returning None for cases where it survived previously, compared to the earlier version of `parse8601`. Something was added that is making an almost-parseable timestring into a `None` now. And it didn't do this earlier. So, this makes me think, it's probably due to one of the newly added sanitizing clauses. Can you debug this further to make it pass, plz? ) Thx! )

**Comment by kroitor** [comment]
@meold I mean, https://travis-ci.org/ccxt/ccxt/builds/388410386#L1776 ← multiple occurrences of this:

```
FAILED therock (Python 2): (explain @ run-tests.js:170)
	<type 'exceptions.TypeError'> unsupported operand type(s) for /: 'NoneType' and 'int' 
	
	  File "python/test/test.py", line 398, in <module>
	    main()
	
	  File "python/test/test.py", line 385, in main
	    try_all_proxies(exchange, proxies)
	
	  File "python/test/test.py", line 320, in try_all_proxies
	    test_exchange(exchange)
	
	  File "python/test/test.py", line 258, in test_exchange
	    test_symbol(exchange, symbol)
	
	  File "python/test/test.py", line 222, in test_symbol
	    test_ohlcv(exchange, symbol)
	
	  File "python/test/test.py", line 140, in test_ohlcv
	    ohlcvs = exchange.fetch_ohlcv(symbol)
	
	  File "/home/travis/build/ccxt/ccxt/python/ccxt/base/exchange.py", line 1103, in fetch_ohlcv
	    return self.build_ohlcv(trades, timeframe, since, limit)
	
	  File "/home/travis/build/ccxt/ccxt/python/ccxt/base/exchange.py", line 1146, in build_ohlcv
	    opening_time = int(math.floor(trade['timestamp'] / ms) * ms)  # Shift the edge of the m/h/d (but not M) (explain @ run-tests.js:173)
```

**Comment by frosty00** [comment]
@kroitor I'll do this, *when I have time 0;*

Also I don't like this style of coding:

    except (TypeError, OverflowError, OSError, ValueError, AttributeError):
         return None

**Comment by frosty00** [comment]
@kroitor by unifying the tests do you mean **all** the tests or just a subset. I don't think all tests need to be unified, for example testing the exchange API responses can be done in just one language - I think we only do it in python and js but correct me if I'm wrong.

**Comment by kroitor** [comment]
> by unifying the tests do you mean all the tests or just a subset. 

I mean a subset first, of course, but, will see how it goes, who knows... ))

**Comment by kroitor** [comment]
> Also I don't like this style of coding:

Ok, what would you propose instead of that line?

**Comment by frosty00** [comment]
@kroitor for example instead of:
```
except AttributeError:
```

```
if match is None:
    return
```

It makes the code easier to read

**Comment by meold** [comment]
@kroitor fixed and now Travis is happy.

**Comment by frosty00** [comment]
@kroitor checkout #3058

**Pull request merged**
