### PR TITLE
ws - this.orberbooks : remove local variables (PART 2)

### PR DESCRIPTION
**Pull request by ttodua**

### CODE REVIEW

**Comment by ttodua** [comment]
same here

**Comment by carlosmiei** [comment]
@ttod YOu tested those right?

**Comment by ttodua** [comment]
the changes were not functional, just variable replacements, and I relied on tests to avoid manual testing of those 25 exchanges, but i'll test them and let you know then

**Comment by ttodua** [comment]
@carlosmiei wdyt, should I close this PR?

**Pull request closed without merging**
