### PR TITLE
fix(python) - unclosed connection leak

### LINKED ISSUE #9218: "ResourceWarning: unclosed transport" after Exchange.close()
- OS: macOS 11.3.1
- Programming Language version: Python 3.9
- CCXT version: CCXT Pro 0.6.90, CCXT 1.50.11

Run this with `python -X dev -X tracemalloc`:
```python
import asyncio

from ccxtpro import ftx


async def main() -> None:

    client = ftx({"verbose": True})

    await client.fetch_ticker("BTC-PERP")

    await client.close()
    #await asyncio.sleep(1)

if __name__ == '__main__':
    asyncio.run(main())
```

It prints out:
```
.venv/bin/python -X dev -X tracemalloc "/Users/pd/Library/Application Support/JetBrains/PyCharm2021.1/scratches/scratch_2.py"

[...]

Response: GET https://ftx.com/api/markets/BTC-PERP 200 {'Date': 'Thu, 20 May 2021 13:19:58 GMT', 'Content-Type': 'application/json', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Vary': 'Accept-Encoding, Accept-Encoding, Accept-Encoding', 'Cache-Control': 'public, max-age=0', 'Etag': 'W/"e9b93c03662ea7b15ff32bd585f1512e"', 'Content-Encoding': 'gzip', 'CF-Cache-Status': 'MISS', 'cf-request-id': '0a2b87dfb000000e22470c4000000001', 'Expect-CT': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"', 'Strict-Transport-Security': 'max-age=31536000; includeSubDomains; preload', 'X-Content-Type-Options': 'nosniff', 'Server': 'cloudflare', 'CF-RAY': '6525dc12b8b60e22-MXP', 'alt-svc': 'h3-27=":443"; ma=86400, h3-28=":443"; ma=86400, h3-29=":443"; ma=86400'} {"success":true,"result":{"name":"BTC-PERP","enabled":true,"postOnly":false,"priceIncrement":1.0,"sizeIncrement":0.0001,"minProvideSize":0.001,"last":42411.0,"bid":42399.0,"ask":42412.0,"price":42411.0,"type":"future","baseCurrency":null,"quoteCurrency":null,"underlying":"BTC","restricted":false,"highLeverageFeeExempt":true,"change1h":0.01942167632141913,"change24h":0.26872681584300584,"changeBod":0.14497448772981292,"quoteVolume24h":7698561559.9802,"volumeUsd24h":7698561559.9802}}
/Users/pd/.pyenv/versions/3.9.4/lib/python3.9/asyncio/selector_events.py:704: ResourceWarning: unclosed transport <_SelectorSocketTransport fd=9>
  _warn(f"unclosed transport {self!r}", ResourceWarning, source=self)
Object allocated at (most recent call last):
  File "/Users/pd/.pyenv/versions/3.9.4/lib/python3.9/asyncio/selector_events.py", lineno 78
    _SelectorSocketTransport(self, rawsock, ssl_protocol,
```

Notice that if you uncomment the sleep after the `.close()`, the warning disappears.

### PR DESCRIPTION
**Pull request by ttodua**
turns out that (as mentioned [here](https://github.com/Azure/azure-sdk-for-python/issues/23645#issuecomment-1085240434) and [here](#9218)) we might need to have await for some MS to close connection.

fix #9218

### CODE REVIEW

**Comment by carlosmiei** [comment]
Even with this PR I get the warnings

```
 ccxt git:(python-close-connecto) ✗ python -X dev -X tracemalloc examples/py/bybit-updated.py
CCXT Version: 4.3.84
Executing <Task finished name='Task-2' coro=<Exchange.load_markets_helper() done, defined at /Users/cjg/Git/ccxt10/ccxt/python/ccxt/async_support/base/exchange.py:263> result={'10000000AIDOGE/USDT:USDT': {'active': True, 'base': '10000000AIDOGE', 'baseId': '10000000AIDOGE', 'contract': True, ...}, '1000000BABYDOGE/USDT:USDT': {'active': True, 'base': '1000000BABYDOGE', 'baseId': '1000000BABYDOGE', 'contract': True, ...}, '1000000MOG/USDT:USDT': {'active': True, 'base': '1000000MOG', 'baseId': '1000000MOG', 'contract': True, ...}, '1000000PEIPEI/USDT:USDT': {'active': True, 'base': '1000000PEIPEI', 'baseId': '1000000PEIPEI', 'contract': True, ...}, ...} created at /opt/homebrew/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/tasks.py:695> took 0.803 seconds
/opt/homebrew/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/selector_events.py:879: ResourceWarning: unclosed transport <_SelectorSocketTransport fd=9>
  _warn(f"unclosed transport {self!r}", ResourceWarning, source=self)
Object allocated at (most recent call last):
  File "/opt/homebrew/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/selector_events.py", lineno 89
    _SelectorSocketTransport(self, rawsock, ssl_protocol,
/opt/homebrew/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/selector_events.py:879: ResourceWarning: unclosed transport <_SelectorSocketTransport fd=11>
  _warn(f"unclosed transport {self!r}", ResourceWarning, source=self)
Object allocated at (most recent call last):
  File "/opt/homebrew/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/selector_events.py", lineno 89
    _SelectorSocketTransport(self, rawsock, ssl_protocol,
/opt/homebrew/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/selector_events.py:879: ResourceWarning: unclosed transport <_SelectorSocketTransport fd=14>
  _warn(f"unclosed transport {self!r}", ResourceWarning, source=self)
Object allocated at (most recent call last):
  File "/opt/homebrew/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/selector_events.py", lineno 89
    _SelectorSocketTransport(self, rawsock, ssl_protocol,
/opt/homebrew/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/selector_events.py:879: ResourceWarning: unclosed transport <_SelectorSocketTransport fd=10>
  _warn(f"unclosed transport {self!r}", ResourceWarning, source=self)
Object allocated at (most recent call last):
  File "/opt/homebrew/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/selector_events.py", lineno 89
    _SelectorSocketTransport(self, rawsock, ssl_protocol,
/opt/homebrew/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/selector_events.py:879: ResourceWarning: unclosed transport <_SelectorSocketTransport fd=12>
  _warn(f"unclosed transport {self!r}", ResourceWarning, source=self)
Object allocated at (most recent call last):
  File "/opt/homebrew/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/selector_events.py", lineno 89
    _SelectorSocketTransport(self, rawsock, ssl_protocol,
/opt/homebrew/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/selector_events.py:879: ResourceWarning: unclosed transport <_SelectorSocketTransport fd=13>
  _warn(f"unclosed transport {self!r}", ResourceWarning, source=self)
Object allocated at (most recent call last):
```

**Comment by ttodua** [comment]
> Even with this PR I get the warnings
> 
> ```
humm,
can you try with e.g 50 or 100 MS , instead of 10 MS ?

**Comment by ttodua** [comment]
but maybe it doesnt look a good solution.
anyway, at least i now have confirmed that you also see the error. i'll continue looking for better solution

**Comment by ttodua** [comment]
Carlos, even though this PR does not solve the unclosed transport, at least, I've added the missing `close()` for other connectors

**Comment by carlosmiei** [comment]
@ttodua this build was weird, let's restart

**Comment by ttodua** [comment]
> @ttodua this build was weird, let's restart

hm yeah, was weird result

**Comment by ttodua** [comment]
@carlosmiei this PR also passed

**Pull request merged**
