### PR TITLE
Fix nonce for bitstamp

### PR DESCRIPTION
**Pull request by 13pass**
I was having "Invalid nonce" errors with bitstamp so I have updated the nonce format.

### CODE REVIEW

**Comment by kroitor** [comment]
Have you read this?
- https://github.com/ccxt/ccxt/wiki/Manual#troubleshooting
- https://github.com/ccxt/ccxt/wiki/Manual#overriding-the-nonce

**Comment by 13pass** [comment]
Thanks @kroitor, I have just had a look at it. Bitstamp request limit is about 600 requests per 10 minutes and per IP address. So in that case another key would not arrange things. I still think the change I have done is relevant to be able to send 600 request within a second.

What do you think I should change here?

**Comment by kroitor** [comment]
> Bitstamp request limit is about 600 requests per 10 minutes and per IP address.

Right.

> So in that case another key would not arrange things.

The Manual describes how to redefine a nonce function the way you want it. No need to change the library for that, you can define your nonce right away.

> I still think the change I have done is relevant to be able to send 600 request within a second.

We have a slightly more advanced solution which uses an implementation of [Token Bucket](https://en.wikipedia.org/wiki/Token_bucket), which, when properly configured, throttles requests in whatever fashion you like, in bursts of up 600 requests per sec, or with regular delays. It supports method call costs and much more, so it's very flexible. However, it is still not documented (we're under active development).

More about it:
- https://github.com/ccxt/ccxt/issues/297#issuecomment-341345247
- https://github.com/ccxt/ccxt/issues/736#issuecomment-349160535
- https://github.com/ccxt/ccxt/issues/892#issuecomment-352621836

> What do you think I should change here?

Well... ) What I'm trying to say is: whenever you have a difficulty with a particular exchange, there may be no need to edit the implementation of it, because this is already addressed in a more generic way with a different solution.

You could use the `.tokenBucket` settings to control it, or, alternatively, the other way of controlling your nonces and throttling would be via a simple override, like this one:

```JavaScript
let yourInstanceOfBitstamp = new ccxt.bitstamp ({ 
    nonce: function () {
             let nonce = this.milliseconds ().toString ();
             if (nonce !== this.last) {
               this.nonceIncr = -1;
             }
             this.last = nonce;
             this.nonceIncr ++;
             let nonceSuffix = ('000'+this.nonceIncr).slice (-4);
             nonce = nonce + nonceSuffix;
    }
})
```

So, there may be no need to redefine the default. You just configure it the way you want it on your side and there you have it. Do you think we *should* integrate this change?

**Comment by 13pass** [comment]
Cool, thank you so much @kroitor

**Comment by kroitor** [comment]
@13pass do you mind if I close this for now? We would be happy to see more contributions from you! Also, feel free to ask, if you have any difficulty with it, some functionality may not be obvious at all, but most of it can be explained )

**Comment by 13pass** [comment]
Yes sorry I forgot to close it. I will definitely spend more times on the docs. I like this project already so hopefully I'll be able to contribute in the future. Thanks again

**Pull request closed without merging**
