### PR TITLE
Add binance endpoint

### PR DESCRIPTION
**Pull request by blackstock**
Adding new dividend endpoint: https://github.com/binance-exchange/binance-official-api-docs/blob/master/wapi-api.md#asset-dividend-record-user_data

### CODE REVIEW

**Comment by kroitor** [comment]
Should we add it so `sign()` as well?

**Comment by kroitor** [comment]
Related: https://github.com/ccxt/ccxt/issues/5693

**Comment by blackstock** [comment]
Good call - sorry I haven't made many contributions and didn't see that `sign` logic. Good to know for next time. Thanks!

**Comment by kroitor** [comment]
@blackstock thx! Looking forward! )

**Comment by tredondo** [comment]
I was looking for a way to obtain aidrops from Binance.

What would be a simple example of using this API?

**Comment by ludekvodicka** [comment]
Hi, can I ask for an example of how to use `/sapi/v1/asset/assetDividend` endpoint through ccxt?

thanks

**Comment by kroitor** [comment]
@ludekvodicka what is your programming language?

**Comment by ludekvodicka** [comment]
> @ludekvodicka what is your programming language?

Sorry, JS. Thanks a lot for the example.

**Pull request merged**
