### PR TITLE
kucoin: one less yellow: switching off OHLCV (accessed from different urls)

### PR DESCRIPTION
**Pull request by mkutny**
As per #602 OHLCV is accessible at a different host (kitchen.kucoin.com, not api.kucoin.com).

Don't know if it's possible to support two different hosts in one implementation but the method is not working anyway.

### CODE REVIEW

**Comment by kroitor** [comment]
> Don't know if it's possible to support two different host in one implementation but the method is not working anyway.

We do support web fallbacks for some methods, so, yes, possible in general. Will look why this one wouldn't work. Thx!

**Comment by mkutny** [comment]
If fallbacks are supported then they have to be configured somehow but i don't see "kitchen.kucoin.com" mentioned anywhere in this file.

**Comment by kroitor** [comment]
@mkutny yep, it's missing, will add it (their API endpoints for OHLCV don't really work as expected)...

**Comment by kroitor** [comment]
Merged it temporarily, will rework the fetchOHLCV for kitchen.kucoin.com soon.

**Comment by mkutny** [comment]
Oh, didn't notice your comment and done it already.

**Comment by mkutny** [comment]
Realized how to add a separate api point once noticed your kraken "scrapping" commit today.

**Pull request merged**
