### PR TITLE
Change API links from http to https

### PR DESCRIPTION
**Pull request by marcuswin**

### CODE REVIEW

**Comment by kroitor** [comment]
Hi! Unfortunately, you've edited files that will be overwritten upon the automatic rebuild as documented in CONTRIBUTING doc here: https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

So, that info is taken from the actual `js/theocean.js` and `js/zaif.js` files – those are the only edits we need. Also see this: https://github.com/ccxt/ccxt/pull/4482 ← we can't change version numbers, without adding the code to support new versions. If you can resubmit the edits in `js/zaif.js` (just one single file) – that will be great! Thank you!

**Comment by marcuswin** [comment]
What about Coingi, Coinmate, etc.?

**Comment by kroitor** [comment]
> What about Coingi, Coinmate, etc.?

Pardon, missed them (we rarely have to deal with reviewing generated files on GitHub), we will be happy if you edit the corresponding `js/*.js` files. Thx again!

**Comment by marcuswin** [comment]
Ok. What is the best way to do this? New pull request?

**Comment by kroitor** [comment]
@marcuswin 

> Ok. What is the best way to do this? New pull request?

Yep, that can probably be the easiest way, if it's ok to you

**Pull request merged**
