### PR TITLE
[yobit] higher resolution nonce (to allow up to 100 requests per minute)

### PR DESCRIPTION
**Pull request by npomfret**

### CODE REVIEW

**Comment by adeel94mirza** [comment]
Hello devs,
I know this issue is closed, but when will this be done for PHP?

**Comment by kroitor** [comment]
@adeel94mirza you can do that with a user-defined nonce with any language, JS, Python, PHP...

In PHP it would look like so:

- https://github.com/ccxt/ccxt/tree/master/examples/php/nonce-override.php

```PHP
<?php

$root = dirname (dirname (dirname (__FILE__)));

include $root . '/ccxt.php';

date_default_timezone_set ('UTC');

class MillisecondsNonceExchange extends \ccxt\yobit {
    public function nonce () {
        return $this->milliseconds();
    }
}

$exchange = new MillisecondsNonceExchange (array (
    'enableRateLimit' => true,
    'apiKey' => 'YOUR_API_KEY',
    'secret' => 'YOUR_SECRET',
));

try {
    $symbol = 'ETH/BTC';
    $result = $exchange->fetch_balance ($symbol);
    var_dump ($result);
} catch (\ccxt\NetworkError $e) {
    echo '[Network Error] ' . $e->getMessage () . "\n";
} catch (\ccxt\ExchangeError $e) {
    echo '[Exchange Error] ' . $e->getMessage () . "\n";
} catch (Exception $e) {
    echo '[Error] ' . $e->getMessage () . "\n";
}

?>
```

**Comment by npomfret** [comment]
I rolled this change back as obit doesn't allow nonce at millisecond accuracy.

**Comment by adeel94mirza** [comment]
Yes I also referred to the docs but I dont understand what the nonce is. I have tried below but I get the error "invalid nonce (has already been used)"

```
<?php

namespace App\Custom;


class MyYobit extends \ccxt\yobit {
    public function __construct ($options = array ()) {
        parent::__construct (array_merge (array ('i' => 1), $options));
    }
    public function nonce(){
        return $this->i++;
    }
}
```

**Comment by kroitor** [comment]
@adeel94mirza 

>  I dont understand what the nonce is

It is a number that has to be:
a) unique
b) higher than the previous nonce

It is sent towards the exchange along with all your private requests.

> but I get the error
> invalid nonce (has already been used)

That means that you're trying to use a nonce, that has been used in one of your previous requests. If you set it to 1 everytime your program starts, and increment it on each request, then upon a relaunch your program will attempt to use 1, 2, 3... again – which is an error, because it violated rules (a) + (b) above.

> Am I doing something wrong?

Looks like you're trying to use a key, that has a higher nonce than you're sending. It means, you've been using that key before with higher nonces. You can reset the nonce on your key if you recreate it. CCXT will use the request timestamp for the nonce ($this->seconds()) to guarantee (a) + (b).

This error is caused by one of two possible issues:

- either you have been using your api key with a different software previously (and that software has higher nonces than 1,2,3...)
- or you have been using that key with ccxt's default timestamp-nonce algorithm (which yields values higher than 1,2,3...), and then trying to reuse it with nonce=1,2,3...

In both cases recreating your API key will reset the nonce, so you can start all over from 1, 2, 3...

> When I enable rate limit I get

You should always enable it, like it is shown in the snippet above.

Let us know if that does not answer your question.

**Comment by adeel94mirza** [comment]
Thanks for the amazing response!

I have done this 
> or you have been using that key with ccxt's default timestamp-nonce algorithm (which yields values higher than 1,2,3...), and then trying to reuse it with nonce=1,2,3...

but I am getting this error from the beginning
> Parameter nonce (1 minimum to 2147483646 maximum) in succeeding request should exceed that in the previous one.

I will try with new keys in a while and play around with this more.

**Pull request closed without merging**
