### PR TITLE
Independent reserve trades

### PR DESCRIPTION
**Pull request by Burtonium**
Fix for issue #2366 
Also added some functionality I required. Let me know if you would like some changes.

### CODE REVIEW

**Comment by kroitor** [comment]
Unfortunately, it breaks the code, because of multiple violations of transpilations rules from here:
https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#derived-exchange-classes ... Will have to rewrite it. But thanks anyway for your effort, really appreciate it!

**Comment by Burtonium** [comment]
My first ever PR so I knew I wasn't going to get it right. I'll see if I can get to it soon if you don't have the time to.

**Comment by kroitor** [comment]
@Burtonium i'll do my best to merge it soon...

**Comment by Burtonium** [comment]
Important consideration: the way I order params doesnt work with RequestFiatWithdrawal from the IndependentReserve API. One fix is to hardcode the order from all methods which I was too lazy for because I didn't need that method in particular.

**Comment by kroitor** [comment]
This breaks public trades and transpilation completely...

**Pull request merged**
