### PR TITLE
bitvavo.createOrder string math

### PR DESCRIPTION
**Pull request by samgermain**
```
2022-12-09T22:44:07.470Z
Node.js: v18.4.0
CCXT v2.0.44
bitvavo.createOrder (ADA/EUR, market, buy, 30, 0.29611)
2022-12-09T22:44:16.607Z iteration 0 passed in 430 ms

{
  info: {
    orderId: '208c4fee-4bc8-41b0-9e4b-39ebc1da7d26',
    market: 'ADA-EUR',
    created: '1670625856533',
    updated: '1670625856533',
    status: 'filled',
    side: 'buy',
    orderType: 'market',
    amountQuote: '8.8',
    amountQuoteRemaining: '0',
    onHold: '0',
    onHoldCurrency: 'EUR',
    filledAmount: '29.710796',
    filledAmountQuote: '8.7780546782',
    feePaid: '0.0219453218',
    feeCurrency: 'EUR',
    fills: [
      {
        id: 'e019b70a-40f5-4fa5-9074-8b2105f6fd87',
        timestamp: '1670625856546',
        amount: '29.710796',
        price: '0.29545',
        taker: true,
        fee: '0.0219453218',
        feeCurrency: 'EUR',
        settled: true
      }
    ],
    selfTradePrevention: 'decrementAndCancel',
    visible: false,
    disableMarketProtection: false
  },
  id: '208c4fee-4bc8-41b0-9e4b-39ebc1da7d26',
  clientOrderId: undefined,
  timestamp: 1670625856533,
  datetime: '2022-12-09T22:44:16.533Z',
  lastTradeTimestamp: 1670625856546,
  symbol: 'ADA/EUR',
  type: 'market',
  timeInForce: 'IOC',
  postOnly: undefined,
  side: 'buy',
  price: 0.29545,
  stopPrice: undefined,
  amount: 29.710796,
  cost: 8.7780546782,
  average: 0.29545,
  filled: 29.710796,
  remaining: 0,
  status: 'closed',
  fee: { cost: 0.0219453218, currency: 'EUR' },
  trades: [
    {
      info: {
        id: 'e019b70a-40f5-4fa5-9074-8b2105f6fd87',
        timestamp: '1670625856546',
        amount: '29.710796',
        price: '0.29545',
        taker: true,
        fee: '0.0219453218',
        feeCurrency: 'EUR',
        settled: true
      },
      id: 'e019b70a-40f5-4fa5-9074-8b2105f6fd87',
      symbol: 'ADA/EUR',
      timestamp: 1670625856546,
      datetime: '2022-12-09T22:44:16.546Z',
      order: '208c4fee-4bc8-41b0-9e4b-39ebc1da7d26',
      type: 'market',
      side: 'buy',
      takerOrMaker: 'taker',
      price: 0.29545,
      amount: 29.710796,
      cost: 8.7780546782,
      fee: { cost: 0.0219453218, currency: 'EUR' },
      fees: [ { currency: 'EUR', cost: '0.0219453218' } ]
    }
  ],
  fees: [ { currency: 'EUR', cost: 0.0219453218 } ]
}
2022-12-09T22:44:16.607Z iteration 1 passed in 430 ms
```

```
% node examples/js/cli bitvavo createOrder ADA/EUR market sell 29.710796    
2022-12-09T22:45:04.382Z
Node.js: v18.4.0
CCXT v2.0.44
bitvavo.createOrder (ADA/EUR, market, sell, 29.710796)
2022-12-09T22:45:07.563Z iteration 0 passed in 447 ms

{
  info: {
    orderId: '5d119272-20d8-4aba-9ef0-a1bb6513a8f4',
    market: 'ADA-EUR',
    created: '1670625907480',
    updated: '1670625907480',
    status: 'filled',
    side: 'sell',
    orderType: 'market',
    amount: '29.710796',
    amountRemaining: '0',
    onHold: '0',
    onHoldCurrency: 'ADA',
    filledAmount: '29.710796',
    filledAmountQuote: '8.76735879164',
    feePaid: '0.02735879164',
    feeCurrency: 'EUR',
    fills: [
      {
        id: 'e1c897a1-4b58-4464-b7fd-12b642db89cc',
        timestamp: '1670625907496',
        amount: '29.710796',
        price: '0.29509',
        taker: true,
        fee: '0.02735879164',
        feeCurrency: 'EUR',
        settled: true
      }
    ],
    selfTradePrevention: 'decrementAndCancel',
    visible: false,
    disableMarketProtection: false
  },
  id: '5d119272-20d8-4aba-9ef0-a1bb6513a8f4',
  clientOrderId: undefined,
  timestamp: 1670625907480,
  datetime: '2022-12-09T22:45:07.480Z',
  lastTradeTimestamp: 1670625907496,
  symbol: 'ADA/EUR',
  type: 'market',
  timeInForce: 'IOC',
  postOnly: undefined,
  side: 'sell',
  price: 0.29509,
  stopPrice: undefined,
  amount: 29.710796,
  cost: 8.76735879164,
  average: 0.29509,
  filled: 29.710796,
  remaining: 0,
  status: 'closed',
  fee: { cost: 0.02735879164, currency: 'EUR' },
  trades: [
    {
      info: {
        id: 'e1c897a1-4b58-4464-b7fd-12b642db89cc',
        timestamp: '1670625907496',
        amount: '29.710796',
        price: '0.29509',
        taker: true,
        fee: '0.02735879164',
        feeCurrency: 'EUR',
        settled: true
      },
      id: 'e1c897a1-4b58-4464-b7fd-12b642db89cc',
      symbol: 'ADA/EUR',
      timestamp: 1670625907496,
      datetime: '2022-12-09T22:45:07.496Z',
      order: '5d119272-20d8-4aba-9ef0-a1bb6513a8f4',
      type: 'market',
      side: 'sell',
      takerOrMaker: 'taker',
      price: 0.29509,
      amount: 29.710796,
      cost: 8.76735879164,
      fee: { cost: 0.02735879164, currency: 'EUR' },
      fees: [ { currency: 'EUR', cost: '0.02735879164' } ]
    }
  ],
  fees: [ { currency: 'EUR', cost: 0.02735879164 } ]
}
2022-12-09T22:45:07.563Z iteration 1 passed in 447 ms
```

### CODE REVIEW

**Comment by AlgoQ** [comment]
`$ node examples/js/cli bitvavo createOrder ADA/EUR market buy 12.5 0.39900`:

```
BadRequest bitvavo {"errorCode":205,"error":"amountQuote parameter is invalid."}
---------------------------------------------------
[BadRequest] bitvavo {"errorCode":205,"error":"amountQuote parameter is invalid."}

    at throwExactlyMatchedException  js/base/Exchange.js:2142            throw new exact[string] (message);                                              
    at handleErrors                  js/bitvavo.js:1777                  this.throwExactlyMatchedException (this.exceptions['exact'], errorCode, feedbac…
    at                               js/base/Exchange.js:598             const skipFurtherErrorHandling = this.handleErrors (response.status, response.s…
    at processTicksAndRejections     internal/process/task_queues.js:95                                                                                  
    at async timeout                 js/base/functions/time.js:181       return await Promise.race ([promise, expires.then (() => { throw new TimedOut (…
    at fetch2                        js/base/Exchange.js:1803            return await this.fetch (request['url'], request['method'], request['headers'],…
    at request                       js/base/Exchange.js:1807            return await this.fetch2 (path, api, method, params, headers, body, config, con…
    at createOrder                   js/bitvavo.js:1025                  const response = await this.privatePostOrder (this.extend (request, params));   
    at async run                     examples/js/cli.js:281              const result = await exchange[methodName] (... args)                            

bitvavo {"errorCode":205,"error":"amountQuote parameter is invalid."}
```

**Comment by AlgoQ** [comment]
You are right, the minimum cost is 5 EUR. Still the same issue tho:
```
bitvavo.createOrder (ADA/EUR, market, buy, 30, 0.39962)
fetch Request:
 bitvavo POST https://api.bitvavo.com/v2/order 
RequestHeaders:
 {
  'BITVAVO-ACCESS-TIMESTAMP': '1666863814921',
  'BITVAVO-ACCESS-WINDOW': '10000',
  'Content-Type': 'application/json'
} 
RequestBody:
 {"market":"ADA-EUR","side":"buy","orderType":"market","amountQuote":"11.988"} 

handleRestResponse:
 bitvavo POST https://api.bitvavo.com/v2/order 400 Bad Request 
ResponseHeaders:
 {
  'Access-Control-Allow-Origin': '*',
  'Alt-Svc': 'h3=":443"; ma=86400, h3-29=":443"; ma=86400',
  'Bitvavo-Ratelimit-Limit': '1000',
  'Bitvavo-Ratelimit-Remaining': '999',
  'Bitvavo-Ratelimit-Resetat': '1666863840000',
  'Cf-Cache-Status': 'DYNAMIC',
  'Cf-Ray': '760a7cfb4a58b9b4-BRU',
  Connection: 'keep-alive',
  'Content-Length': '61',
  'Content-Type': 'application/json; charset=utf-8',
  Date: 'Thu, 27 Oct 2022 09:43:35 GMT',
  Etag: 'W/"3d-xIczCOb+npzIyrpffTRpH2OZ/UQ"',
  Server: 'cloudflare',
  'Set-Cookie': '__cf_bm=.Idz5liYJVchb2mJYArhAEOO6TrVoxapCE0B9PdydXI-1666863815-0-AWid7jurf8j6ywY4Izh8reYnB5BVLMhIrLz3nf1v1pjTjuWrnpVrUKTU/Jkb62ZPBTEuC/BTCVsHSr3SpbW4uVo=; path=/; expires=Thu, 27-Oct-22 10:13:35 GMT; domain=.bitvavo.com; HttpOnly; Secure; SameSite=None',
  'Strict-Transport-Security': 'max-age=15552000; includeSubDomains; preload',
  Via: '1.1 f32f19f2f9b3c0c60a4ff31c809ed008.cloudfront.net (CloudFront)',
  'X-Amz-Cf-Id': 'FNjaYdALA0pbuibnFeVlDzRa36JI2SR7KU08OsunUlo-BOMEyXxYQw==',
  'X-Amz-Cf-Pop': 'AMS1-C1',
  'X-Cache': 'Error from cloudfront',
  'X-Envoy-Upstream-Service-Time': '52'
} 
ResponseBody:
 {"errorCode":205,"error":"amountQuote parameter is invalid."} 

BadRequest bitvavo {"errorCode":205,"error":"amountQuote parameter is invalid."}
---------------------------------------------------
[BadRequest] bitvavo {"errorCode":205,"error":"amountQuote parameter is invalid."}

    at throwExactlyMatchedException  js/base/Exchange.js:2142              throw new exact[string] (message);                                              
    at handleErrors                  js/bitvavo.js:1777                    this.throwExactlyMatchedException (this.exceptions['exact'], errorCode, feedbac…
    at                               js/base/Exchange.js:598               const skipFurtherErrorHandling = this.handleErrors (response.status, response.s…
    at processTicksAndRejections     node:internal/process/task_queues:95                                                                                  
    at async timeout                 js/base/functions/time.js:181         return await Promise.race ([promise, expires.then (() => { throw new TimedOut (…
    at fetch2                        js/base/Exchange.js:1803              return await this.fetch (request['url'], request['method'], request['headers'],…
    at request                       js/base/Exchange.js:1807              return await this.fetch2 (path, api, method, params, headers, body, config, con…
    at createOrder                   js/bitvavo.js:1025                    const response = await this.privatePostOrder (this.extend (request, params));   
    at async run                     examples/js/cli.js:281                const result = await exchange[methodName] (... args)                            

bitvavo {"errorCode":205,"error":"amountQuote parameter is invalid."}
```

**Comment by samgermain** [comment]
@AlgoQ Could you pull the updated branch and try again?

**Comment by carlosmiei** [comment]
LGTM ✅ 
```
p bitvavo createOrder "LTC/EUR" market buy  0.1 
Python v3.10.8
CCXT v2.0.44
bitvavo.createOrder(LTC/EUR,market,buy,0.1)
{'amount': 0.1,
 'average': 61.976,
 'clientOrderId': None,
 'cost': 6.1976,
 'datetime': '2022-12-23T10:02:20.125Z',
 'fee': {'cost': 0.0224, 'currency': 'EUR'},
 'fees': [{'cost': 0.0224, 'currency': 'EUR'}],
 'filled': 0.1,
 'id': '4e05e61a-3b07-4121-ac30-760136486d57',
 'info': {'amount': '0.1',
          'amountRemaining': '0',
          'created': '1671789740125',
          'disableMarketProtection': False,
          'feeCurrency': 'EUR',
          'feePaid': '0.0224',
          'filledAmount': '0.1',
          'filledAmountQuote': '6.1976',
          'fills': [{'amount': '0.1',
                     'fee': '0.0224',
                     'feeCurrency': 'EUR',
                     'id': 'b2c58156-d8da-41db-b577-a0541d8eadd9',
                     'price': '61.976',
                     'settled': True,
                     'taker': True,
                     'timestamp': '1671789740135'}],
          'market': 'LTC-EUR',
          'onHold': '21.95',
          'onHoldCurrency': 'EUR',
          'orderId': '4e05e61a-3b07-4121-ac30-760136486d57',
          'orderType': 'market',
          'selfTradePrevention': 'decrementAndCancel',
          'side': 'buy',
          'status': 'filled',
          'updated': '1671789740125',
          'visible': False},
```

**Review by carlosmiei — APPROVED** [review]

**Pull request merged**
