### PR TITLE
Add endpoint to retrieve deposit/withdrawal records from Huobipro

### PR DESCRIPTION
**Pull request by pioul**
Straightforward PR to add the endpoint `/query/deposit-withdraw`.

API doc section relevant to that endpoint: https://github.com/huobiapi/API_Docs_en/wiki/REST_Reference#get-v1querydeposit-withdraw---get-deposit-or-withdraw-records

### CODE REVIEW

**Comment by kroitor** [comment]
@pioul thank you so much!

**Comment by pioul** [comment]
Thanks for the quick merge!

**Comment by salty82** [comment]
how do you call this in python? having some issues.

**Comment by kroitor** [comment]
@salty82 https://github.com/ccxt/ccxt/wiki/Manual#implicit-api-methods

**Comment by salty82** [comment]
I tried both ways with no luck. I get an error saying there’s no function. Have you been able to successfully call it? Below is what I’ve tried, excluding the params. 

exchange.private_get_query_deposit_withdraw
exchange.privateGetQueryDepositWithdraw

**Comment by salty82** [comment]
Yes I am. I had not upgraded ccxt since this was added. All good now.

**Comment by salty82** [comment]
anyone have any issues receiving the withdrawals from this end point? i am able to receive deposits, but no luck on withdrawals.

**Comment by kroitor** [comment]
> but no luck on withdrawals

Without your code it's hard to tell. What are your values for `curr`, `id` ?
All values should be strings, and your size is not a string, it's an integer. Should be `"100"` instead.

screen shot 2018-05-26 at 05 58 51

**Comment by kroitor** [comment]
@salty82 

Does this work? ↓

```huobipro.private_get_query_deposit_withdraw({"currency" : curr, "type" : "withdraw"})```

**Comment by salty82** [comment]
No, and I tried everything as strings too. The from and size params are
actually required.

This is a huobi pro issue not ccxt but they are literally no help. I get a
successful call but nothing in the data field for withdrawals.

{“status” : “ok”, “data” : []}

**Pull request merged**
