### PR TITLE
WIP: More detail in  typings

### PR DESCRIPTION
**Pull request by robertohuertasm**
This still doesn't cover all the api but it exposes a lot more and allows using dynamic properties and methods to cover missing and dynamic fields/methods

### CODE REVIEW

**Comment by kroitor** [comment]
Hi!

We now have:

- this: https://github.com/ccxt/ccxt/pull/705
- this: https://github.com/ccxt/ccxt/pull/764
- and your pull request

... and we're not sure how we should align them together. Looks like we need to merge them all together somehow. Would you take a look?

**Comment by robertohuertasm** [comment]
@kroitor, of course! No problem, I'll tackle this during the week and will merge the other PR info.

**Comment by kroitor** [comment]
Thanks a lot! Let us know if you have any questions in the process. Looking forward to continue.

**Comment by robertohuertasm** [comment]
Just a question. Have you ever considered migrating your `js` code to `typescript`? It would be the easiest way to keep in sync your code with your typings as they would be automatically generated.

**Comment by kroitor** [comment]
> It would be the easiest way to keep in sync your code with your typings as they would be automatically generated.

I'd agree, having a more restrictive set of types in source and generating less restrictive typings from there would be better than the other way. 

We thought of solving this by full AST traversion and by mapping from the tree. We even started the [crosspile project](https://github.com/ccxt/crosspile) for cross-language conversions, it is going to do any ←→ any transpilation eventually. 

I don't rule out the possibility of using Typescript as the main language at all. Our current transpiler is an ad-hoc script, for now it does its regexp job, but it isn't the most convenient way of doing the conversion, of course. The obvious reason for having it in the first place is: it was the quickest way that worked. But we will reconsider migrating to Typescript.

**Comment by robertohuertasm** [comment]
I've just seen the transpilation process while looking at the code deeply. Yesterday I just needed my typescript to work and I didn't pay attention to how this library works (my bad :disappointed: ). I've also checked out that my proposed changes are not compatible with how the build process works so... I'll have to do my homework here.

**Comment by robertohuertasm** [comment]
@kroitor, feel free to merge previous `typescript` related PRs. Given the complexity of the project I'm going to consider the approach I'm taking for this PR. I really like this library so I think it's better to do things right. 

For the moment, I need to use this in a new `typescript` project I'm working in so maybe I'll just use my fork to get rid of all the `python` and `php` support and face the typescript conversion in order to get my types right. Once I have this, I'll see how I can contribute to this project by providing types and trying to accommodate your transpilation process to the `typescript` output. 

I'm closing this PR. Thanks for your awesome work!

**Pull request closed without merging**
