### PR TITLE
New exchange: Bitmax

### PR DESCRIPTION
**Pull request by ericjjj**

### CODE REVIEW

**Comment by ericjjj** [comment]
@kroitor @frosty00 it still pending review😭

**Comment by hanyoonLDA** [comment]
Thank you @ericjjj :) We've been waiting for BitMax integration for a long time.

**Comment by ericjjj** [comment]
@kroitor @frosty00 still pending review, some users are waiting BitMax integration, How can we speed up the progress?

**Comment by kroitor** [comment]
@ericjjj we need to make it conform the guidelines from here: https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#derived-exchange-classes

**Comment by fuqi1001** [comment]
> @ericjjj we need to make it conform to the guidelines from here: https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#derived-exchange-classes

Hi kroitor, thanks for review, may I know which code are not conform to the guidelines?

**Comment by kroitor** [comment]
@fuqi1001 mostly these throughout the file:

- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#sending-market-ids
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#parsing-symbols
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#sanitizing-input-with-safe-methods
- https://github.com/ccxt/ccxt/wiki/Requirements

It looks like the code was taken from Binance, however, there's a lot of redundant code that should not be there. It has to be rewritten to make it unified.

**Comment by ericjjj** [comment]
that's my test scrpt,  of course including private API,
just copy binance.js as template file
some type errors(safeFloat...), I will check again

```js
bitmax.loadMarkets().then(data => {
    console.log(data)
}).catch(error => {
    console.error(error)
})

bitmax.fetchBalance().then(data => {
    console.log('data', data)
}).catch(error => {
    console.error(error)
})

let symbol = 'ETH/USDC'
bitmax.fetchOrderBook(symbol).then(data => {
    console.log('data', data)
}).catch(error => {
    console.error(error)
})
bitmax.fetchTicker(symbol).then(data => {
    console.log('data', data)
}).catch(error => {
    console.error(error)
})

bitmax.fetchTickers().then(data => {
    console.log('data', data)
}).catch(error => {
    console.error(error)
})


bitmax.fetchTrades(symbol).then(data => {
    console.log('data', data)
}).catch(error => {
    console.error(error)
})

let order_id = 'xx'

bitmax.createOrder(symbol, 'limit', 'sell', 0.01, 5000).then(data => {
    console.log('data', data)
}).catch(error => {
    console.error(error)
})

bitmax.cancelOrder(order_id, symbol).then(data => {
    console.log('data', data)
}).catch(error => {
    console.error(error)
})

bitmax.fetchOrder(order_id, symbol).then(data => {
    console.log('data', data)
}).catch(error => {
    console.error(error)
})


bitmax.fetchOpenOrders(symbol).then(data => {
    console.log('data', data)
}).catch(error => {
    console.error(error)
})

bitmax.fetchClosedOrders(symbol).then(data => {
    console.log('data', data)
}).catch(error => {
    console.error(error)
})

bitmax.fetchOrders(symbol).then(data => {
    console.log('data', data)
}).catch(error => {
    console.error(error)
})


bitmax.fetchOHLCV(symbol, '1m').then(data => {
    console.log('data', data)
}).catch(error => {
    console.error(error)
})
```

**Comment by kroitor** [comment]
@ericjjj the problem is that not everything is tested that way, for example, that does test for errors coming from exchanges, but it does not test the actual values within orders or trades. In order to run the CCXT tests including the private API (without changing your balance, of course) you can simply do the following:

1. create `keys.local.json` in the root of your CCXT working directory/repo with the following contents: `{"bitmax":{"apiKey":"YOUR_API_KEY","secret":"YOUR_SECRET"}}`
2. `npm run build`
3. `node run-tests.js bitmax`

These tests run over exchange methods, but also check values and other things. However, this does not catch logical errors, of course, therefore the final code has to be reviewed manually.

**Comment by ericjjj** [comment]
@kroitor thank you, that is test result
```
node run-tests.js bitmax --js
Testing { exchanges: ["bitmax"], symbol: "all", keys: { '--js': true, '--php': false, '--python': false, '--python2': false, '--python3': false }, maxConcurrency: 5 } (run-tests.js:252)
[100%] Testing bitmax WARN (testExchange @ run-tests.js:169)

WARN bitmax (JavaScript): (explain @ run-tests.js:188)


	TESTING { exchange: "bitmax", symbol: "all" }  (<anonymous> @ test.js:33)

	[Request Timeout] bitmax GET https://bitmax.io/api/v1/products request timed out (20000 ms) (tryAllProxies @ test.js:391)
	195 symbols BTC/USDT, DASH/BTC, ETH/BTC, LTC/BTC + more... (loadExchange @ test.js:186)
	SYMBOL: BTC/USDT (testExchange @ test.js:261)
	fetching currencies not supported (exports [as fetchCurrencies] @ test.fetchCurrencies.js:35)
	BTC/USDT fetchTicker 2019-08-15T06:10:00.000Z bid: undefined ask: undefined (printTickerOneLiner @ test.fetchTicker.js:16)
	fetched all 195 tickers (exports [as fetchTickers] @ test.fetchTickers.js:35)
	BTC/USDT fetched 10 OHLCVs (exports [as fetchOHLCV] @ test.fetchOHLCV.js:47)
	BTC/USDT fetched 10 trades (exports [as fetchTrades] @ test.fetchTrades.js:22)
	BTC/USDT fetchOrderBook 2019-08-15T06:13:46.304Z bid: 9612.52 bidVolume: 0.0425241 ask: 9612.74 askVolume: 0.011 (printOrderBookOneLiner @ test.orderbook.js:18)
	BTC/USDT fetchL2OrderBook 2019-08-15T06:13:47.539Z bid: 9609.81 bidVolume: 0.0007 ask: 9612.72 askVolume: 0.2981803 (printOrderBookOneLiner @ test.orderbook.js:18)
	fetchOrderBooks() not supported (exports [as fetchOrderBooks] @ test.fetchOrderBooks.js:44)
	fetching balance... (exports [as fetchBalance] @ test.fetchBalance.js:20)
	BTC: 0, ETH: 0.2, LTC: 0, DASH: 0, XRP: 0 (exports [as fetchBalance] @ test.fetchBalance.js:71)
	fetching funding fees not supported (exports [as fetchFundingFees] @ test.fetchFundingFees.js:35)
	fetching trading fees not supported (exports [as fetchTradingFees] @ test.fetchTradingFees.js:34)
	fetching status not supported (exports [as fetchStatus] @ test.fetchStatus.js:30)
	fetched 0 orders, asserting each... (exports [as fetchOrders] @ test.fetchOrders.js:32)
	fetched 0 open orders (exports [as fetchOpenOrders] @ test.fetchOpenOrders.js:24)
	fetched 0 closed orders, testing each (exports [as fetchClosedOrders] @ test.fetchClosedOrders.js:22)
	fetching my trades not supported (exports [as fetchMyTrades] @ test.fetchMyTrades.js:51)
	fetching ledger items not supported (exports [as fetchLedger] @ test.fetchLedger.js:45) (explain @ run-tests.js:190)
WARN ["bitmax"] (run-tests.js:269)
All done, 1 warnings (run-tests.js:273)
```

**Comment by ericjjj** [comment]
@kroitor The Travis CI build failed, but it seem not about bitmax
```
FAIL ["mercado"] (run-tests.js:268)
WARN <array[81]> (run-tests.js:269)
All done, 1 failed, 43 succeeded, 81 warnings (run-tests.js:273)
The command "node run-tests --js --python 5; export TESTS_FAILED=$?" exited with 0.
```

**Comment by kroitor** [comment]
@ericjjj what does it say in these cases:

- `node js/test/test bitmax`
- `python python/test/test.py bitmax` (if you have py2)
- `python3 python/test/test.py bitmax` 
- `php -f php/test/test.php bitmax`

? Unfortunately, with 0 orders it's skipping the most essential private tests... So there have to be some orders (we usually do them manually), in order to verify that the parsing is ok in all languages. 

I'll review the code thoroughly and will get back to you with comments asap. Pardon for the delays.

P.S. These 3 lines look redundant:

https://github.com/ccxt/ccxt/pull/5413/files#diff-6f5a9449168202758b3e571465d1b2f4R491

**Comment by ericjjj** [comment]
@kroitor   Under your guidance, I create a  order before run the test script, and fix some bugs

https://github.com/ccxt/ccxt/pull/5413/files#diff-6f5a9449168202758b3e571465d1b2f4R491 

has 1 lines is redundant


# node js/test/test bitmax
```
TESTING { exchange: "bitmax", symbol: "all" }  (<anonymous> @ test.js:33)

[Request Timeout] bitmax GET https://bitmax.io/api/v1/products request timed out (20000 ms) (tryAllProxies @ test.js:391)
195 symbols BTC/USDT, DASH/BTC, ETH/BTC, LTC/BTC + more... (loadExchange @ test.js:186)
SYMBOL: BTC/USDT (testExchange @ test.js:261)
fetching currencies not supported (exports [as fetchCurrencies] @ test.fetchCurrencies.js:35)
BTC/USDT fetchTicker 2019-08-16T02:50:00.000Z bid: undefined ask: undefined (printTickerOneLiner @ test.fetchTicker.js:16)
fetched all 195 tickers (exports [as fetchTickers] @ test.fetchTickers.js:35)
BTC/USDT fetched 10 OHLCVs (exports [as fetchOHLCV] @ test.fetchOHLCV.js:47)
BTC/USDT fetched 10 trades (exports [as fetchTrades] @ test.fetchTrades.js:22)
BTC/USDT fetchOrderBook 2019-08-16T02:52:58.359Z bid: 10353.48 bidVolume: 0.0478272 ask: 10353.54 askVolume: 0.049145 (printOrderBookOneLiner @ test.orderbook.js:18)
BTC/USDT fetchL2OrderBook 2019-08-16T02:53:00.585Z bid: 10353.29 bidVolume: 0.1091029 ask: 10353.54 askVolume: 0.049145 (printOrderBookOneLiner @ test.orderbook.js:18)
fetchOrderBooks() not supported (exports [as fetchOrderBooks] @ test.fetchOrderBooks.js:44)
fetching balance... (exports [as fetchBalance] @ test.fetchBalance.js:20)
BTC: 0, ETH: 0.2, LTC: 0, DASH: 0, XRP: 0 (exports [as fetchBalance] @ test.fetchBalance.js:71)
fetching funding fees not supported (exports [as fetchFundingFees] @ test.fetchFundingFees.js:35)
fetching trading fees not supported (exports [as fetchTradingFees] @ test.fetchTradingFees.js:34)
fetching status not supported (exports [as fetchStatus] @ test.fetchStatus.js:30)
fetched 6 orders, asserting each... (exports [as fetchOrders] @ test.fetchOrders.js:32)
fetched 1 open orders (exports [as fetchOpenOrders] @ test.fetchOpenOrders.js:24)
fetched 6 closed orders, testing each (exports [as fetchClosedOrders] @ test.fetchClosedOrders.js:22)
fetching my trades not supported (exports [as fetchMyTrades] @ test.fetchMyTrades.js:51)
fetching ledger items not supported (exports [as fetchLedger] @ test.fetchLedger.js:45)
```

# python3 python/test/test.py bitmax
```
{'type': 'RequestTimeout', 'num_retries': 0, 'max_retries': 2} bitmax GET https://bitmax.io/api/v1/products HTTPSConnectionPool(host='bitmax.io', port=443): Max retries exceeded with url: /api/v1/products (Caused by ConnectTimeoutError(<urllib3.connection.Verifie
bitmax using proxy `https://cors-anywhere.herokuapp.com/`
EXCHANGE: bitmax
SYMBOL: BTC/USDT
bitmax BTC/USDT ticker 2019-08-16T03:15:00.000Z high: 10457.89 low: 9521.99 bid: None ask: None volume: None
bitmax BTC/USDT order book 2019-08-16T03:19:31.199Z bid: 10342.88 bidVolume: 0.0257329 ask: 10342.99 askVolume: 0.0008314
bitmax BTC/USDT fetched 10 trades
bitmax fetched all 195 tickers
bitmax fetched 10 OHLCVs
bitmax fetched balance
bitmax fetched 6 orders
```

# php -f php/test/test.php bitmax
```
string(17) "./keys.local.json"

Notice: Undefined index: bitmax in /Users/jk/work/ccxt/php/test/test.php on line 228

Warning: A non-numeric value encountered in /Users/jk/work/ccxt/php/test/test.php on line 241

Warning: A non-numeric value encountered in /Users/jk/work/ccxt/php/test/test.php on line 241
```

# node run-tests.js bitmax --php
```
Testing { exchanges: ["bitmax"], symbol: "all", keys: { '--js': false, '--php': true, '--python': false, '--python2': false, '--python3': false }, maxConcurrency: 5 } (run-tests.js:252)
[100%] Testing bitmax OK (testExchange @ run-tests.js:169)
All done, 1 succeeded (run-tests.js:273)
```

**Comment by hanyoonLDA** [comment]
Very eager to see BitMax on CCXT. I'm getting the following error from our MM bot:

`8/16/2019 3:06:07 AM | [TypeError] Cannot read property 'toString' of undefined
                       
                           at numberToString             ccxt/js/base/functions/number.js:56   let e = parseInt (x.toString ().split ('+')[1])                                 
                           at decimalToPrecision         ccxt/js/base/functions/number.js:136  const str          = numberToString (x)                                         
                           at priceToPrecision           ccxt/js/base/Exchange.js:1308         return decimalToPrecision (price, ROUND, this.markets[symbol].precision.price, …
                           at createOrder                ccxt/js/bitmax.js:456                 'orderPrice': this.priceToPrecision (symbol, price),                            
                           at processTicksAndRejections  internal/process/next_tick.js:81                                                                                      
                       
8/16/2019 3:06:07 AM | [ExchangeNotAvailable] bitmax GET https://bitmax.io/0/api/v1/depth?symbol=DEEP%2FUSDT 404 Not Found The requested resource could not be found.…
                       
                           at defaultErrorHandler        ccxt/js/base/Exchange.js:607      throw new ErrorClass ([ this.id, method, url, code, reason, details ].join (' '…
                           at then                       ccxt/js/base/Exchange.js:650      this.defaultErrorHandler (response.status, response.statusText, responseBody, u…
                           at processTicksAndRejections  internal/process/next_tick.js:81       `

**Comment by ericjjj** [comment]
@hanyoonLDA Hi, are you manual compile `bitmax.js` file ? 
`https://bitmax.io/0/api/v1/depth?symbol=DEEP%2FUSDT` is a mistake, 
`0` is account group of bitmax, only private api need that, that url should be `https://bitmax.io/api/v1/depth?symbol=DEEP%2FUSDT`

**Comment by ericjjj** [comment]
@kroitor Hi，I‘m waiting for codereview 😭

**Comment by ericjjj** [comment]
@lpxxfaintxx test cases have passed， just need review the code

**Comment by kroitor** [comment]
@ericjjj @lpxxfaintxx I hope to get to it this week and will merge or will post here if there's anything left to do. Pardon again for the very long wait.

**Comment by ericjjj** [comment]
@kroitor How is the progress? 😭

**Comment by hanyoonLDA** [comment]
@ericjjj I'm having issues with my NodeJS based program using async. The public API endpoint works fine at first, but once the program accesses a private API, all future calls to the public API adds in the usergroup /x/ in front of /api/ causing a 404 error -- any idea how to prevent that from happening?  If you want to take a look msg me: wechat - hanyoon93 or tg - @LDA_Han

**Comment by ericjjj** [comment]
@kroitor Can it be merged this month? some peoples have to manually compile the file 😭, and it open about three month ago...

**Comment by kroitor** [comment]
@ericjjj yes, i'll do my best, thx for your patience!

**Comment by ericjjj** [comment]
@kroitor What is the progress? 😭

**Pull request merged**
