### PR TITLE
ftx: fix fetch trades

### PR DESCRIPTION
**Pull request by brandsimon**
They use `since / 1000` everywhere (`fetchMyTrades`, `fetchOHLCV`, `fetchOrders`), but only for `fetchTrades` they support both `since` and `since / 1000`.
I changed it for `fetchTrades` to be consistent with the rest of the code, but my investigations resulted in: the result is equivalent with and without this code change. Please double check!

### CODE REVIEW

**Comment by kroitor** [comment]
@brandsimon does `start_time` work for you with `fetchTrades` at all?

**Comment by brandsimon** [comment]
@kroitor Yes, they only provide the last 1500 entries. If my `since` is in this range, it works and reduces the entries to begins with the correct time.

**Comment by kroitor** [comment]
@brandsimon it didn't work for me without the `end_time`...

**Comment by brandsimon** [comment]
@kroitor I tried it with python:
```
 $ .venv/bin/python examples/py/cli.py ftx fetch_ohlcv BTC/USD 1m | wc -l
1500
 $ .venv/bin/python examples/py/cli.py ftx fetch_ohlcv BTC/USD 1m 1574039880000 | wc -l
26

```

**Comment by kroitor** [comment]
@brandsimon i mean, i've added the `end_time` there, because it didn't work for me without that argument. But no worries, this is already in the master ) Thx for your help!

**Comment by brandsimon** [comment]
@kroitor 
Sorry, I mentioned ohlcv, but I have the same behaviour with fetch_trades in 1.19.44 (start_time in the request)

**Pull request merged**
