### PR TITLE
eslint: 'YmdHMS' can be called without 'new'

### PR DESCRIPTION
**Pull request by mkutny**

### CODE REVIEW

**Comment by kroitor** [comment]
maybe I should rename it to ymdHMS...

**Comment by mkutny** [comment]
Agree. Just didn't want to touch the core )

**Comment by mkutny** [comment]
BTW, if you call eslint with `--fix` option it will fix almost all exchanges automatically. Majority of those issues are `"use strict"` and semicolons at the very last line of a file, it can fix such issues by itself.

Submitting a separate PR for such a trivial issue is quite boring, I also think you're not happy about merging them too )

**Comment by kroitor** [comment]
@mkutny will do that, also, no worries about touching the core, it's all subject to editing as well, just need to make sure to mirror the changes to other bases classes and voila.

**Comment by kroitor** [comment]
> BTW, if you call eslint with --fix option it will fix almost all exchanges automatically. Majority of those issues are "use strict" and semicolons at the very last line of a file, it can fix such issues by itself.

Thx for the hint! Will update the remaining ones, no worries at all.

**Pull request merged**
