### PR TITLE
fix(bingx) - spot /swap candles

### PR DESCRIPTION
**Pull request by ttodua**
fixes https://github.com/ccxt/ccxt/pull/22629#discussion_r1643347514

```
bingx watchOHLCV BTC/USDT 1m

2024-06-18T10:36:47.353Z
Node.js: v21.6.2
CCXT v4.3.47
bingx.watchOHLCV (BTC/USDT, 1m)
1718706960000 | 65570.08 | 65603.9 | 65567.54000000001 | 65567.54000000001 | 0.33182
```

```
bingx watchOHLCV BTC/USDT:USDT 1m

2024-06-18T10:37:06.635Z
Node.js: v21.6.2
CCXT v4.3.47
bingx.watchOHLCV (BTC/USDT:USDT, 1m)
1718707020000 | 65525.4 | 65527.1 | 65510.3 | 65519.3 | 1.6041
```

### CODE REVIEW

**Comment by carlosmiei** [comment]
@ttodua was fixed here: https://github.com/ccxt/ccxt/pull/22834

**Comment by ttodua** [comment]
> @ttodua was fixed here: #22834

ok but i dont that edit is good, we need still to merge the edit i have pushed

**Comment by carlosmiei** [comment]
@ttodua yes we can merge yours since does not use safeValue, can you rebase?

**Comment by ttodua** [comment]
sure give me few moments. the reason we need to avoid that, is not just "safeValue", but i was afraid that in near future, any of our dev would look that line and he will probably think to convert `this.safeValue (.., [ ] )` into safeList again, thus the bug will be back again,

**Comment by ttodua** [comment]
pushed

**Pull request merged**
