### PR TITLE
feat(coinex): improve parseTicker to handle buy_amount and sell_amount

### PR DESCRIPTION
**Pull request by paulofreitas**
- Improve `parseTicker()` method to handle `buy_amount` and `sell_amount` fields to offer `bidVolume` and `askVolume` 🙂

### CODE REVIEW

**Comment by paulofreitas** [comment]
Sorry for force-pushing my fork after making the PR, I forgot to branch another change and had to undo. 🫠

**Comment by carlosmiei** [comment]
Hey @paulofreitas, thanks again for your contribution 🙂

**Comment by carlosmiei** [comment]
LGTM ✅ 

```
 p coinex fetchTicker "BTC/USDT"              
Python v3.10.9
CCXT v4.0.75
coinex.fetchTicker(BTC/USDT)
{'ask': 26065.12,
 'askVolume': 1.25622929,
 'average': 26059.345,
 'baseVolume': 78.82444919,
 'bid': 26065.11,
 'bidVolume': 0.66706096,
 'change': 11.53,
 'close': 26065.11,
 'datetime': '2023-08-26T07:27:53.055Z',
 'high': 26294.95,
 'info': {'buy': '26065.11',
          'buy_amount': '0.66706096',
          'high': '26294.95',
          'last': '26065.11',
          'low': '25785.90',
          'open': '26053.58',
          'sell': '26065.12',
          'sell_amount': '1.25622929',
          'vol': '78.82444919'},
 'last': 26065.11,
 'low': 25785.9,
 'open': 26053.58,
 'percentage': 0.0442549545974104,
 'previousClose': None,
 'quoteVolume': None,
 'symbol': 'BTC/USDT',
 'timestamp': 1693034873055,
 'vwap': None}
```

**Review by carlosmiei — APPROVED** [review]

**Comment by paulofreitas** [comment]
> Hey @paulofreitas, thanks again for your contribution 🙂

Glad to help mate, just sent a similar PR for `bitfinex2` on https://github.com/ccxt/ccxt/pull/19003! 🙂

**Pull request merged**
