### PR TITLE
Add smartvalor exchange

### PR DESCRIPTION
**Pull request by angelov-todor**

### CODE REVIEW

**Comment by sarathdevanand** [comment]
Hello @kroitor, 
Could you please let us know if you have an ETA? If we are missing any requirements, please feel free to let us know.

**Comment by kroitor** [comment]
@sarathdevanand we can't promise an ETA on the free open-source work, as explained in the FAQ here: 

- https://github.com/ccxt/ccxt/wiki/FAQ#can-you-implement-feature-foo-in-exchange-bar
- https://github.com/ccxt/ccxt/wiki/FAQ#when-will-you-add-feature-foo-for-exchange-bar--whats-the-estimated-time-when-should-we-expect-this
- https://github.com/ccxt/ccxt/wiki/FAQ#when-will-you-add-the-support-for-an-exchange-requested-in-the-issues
- https://github.com/ccxt/ccxt/wiki/FAQ#what-is-the-status-of-this-pr-any-update

The PR currently breaks the following guidelines:

- https://github.com/ccxt/ccxt/wiki/Manual#symbols-and-market-ids
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#derived-exchange-classes
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#new-exchange-integrations

**Comment by sarathdevanand** [comment]
@kroitor Thanks for the update. Would it be possible to pinpoint what breaks the guidelines? This could make it so much more easier on us.

**Comment by kroitor** [comment]
@sarathdevanand 

> https://github.com/ccxt/ccxt/wiki/FAQ#can-you-point-out-the-errors-or-what-should-i-edit-in-my-pr-to-get-it-merged-into-master-branch

I'll do that as soon as I can, however, if you want to save the time, the algorithm is very simple, the only requirement is to be very pedantic:

1. Take each line of the integration
2. Take these guidelines: 
  - https://github.com/ccxt/ccxt/wiki/Manual
  - https://github.com/ccxt/ccxt/wiki/Manual#symbols-and-market-ids
  - https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#derived-exchange-classes 
  - https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#new-exchange-integrations
  Consider the information from the Manual (requires reading the entire Manual at least once from top to bottom) and the CONTRIBUTING doc
3. Compare the line in question against every single guideline thoroughly and precisely
4. If it satisfies all guidelines – move to next line
5. If it does not satisfy some guideline, see other already-integrated implementations and change the line in question by example
6. When you're done, you will have a clean integration ready for merging

**Pull request closed without merging**
