### PR TITLE
Add EMX exchange

### PR DESCRIPTION
**Pull request by jc-emx**
Our API doc: https://docs.emx.com/#introduction
Github: https://github.com/evermarkets/emx-python

We are really interested integrate on CCXT library advise by one of our friend.

feel free to shot me email: jchen@emx.com

### CODE REVIEW

**Comment by kroitor** [comment]
@jc-emx hi! In order to accept an exchange implementation in a Pull Request (PR), the Pull Request has to include the implementation of EMX according to the CONTRIBUTING guidelines. However, this PR does not include such an implementation. Do you understand how GitHub PRs work and how to submit an implementation?

**Comment by jc-emx** [comment]
Sorry, I any not tech team. Could you tell me how Github pr works and how to submit an implementation?

**Comment by kroitor** [comment]
@jc-emx it's very hard to explain, since you will need to know the programming aspects to do it right. If you're not from a tech team, then it will take an eternity. Therefore I'd suggest you to reach out to us via info@ccxt.trade if you want the CCXT Dev Team to do the technical work for you quickly.

**Comment by kroitor** [comment]
Closing this for now if you don't mind.

**Pull request closed without merging**
