### PR TITLE
Update transpile.js

### PR DESCRIPTION
**Pull request by goznauk**
createOrderRequest and editOrderRequest were not transpiled properly

https://github.com/ccxt/ccxt/issues/20502

### CODE REVIEW

**Comment by carlosmiei** [comment]
Hello @goznauk, where did you find that issue? I can't see the snake_case version inside the python files:

image
image

**Comment by goznauk** [comment]
@carlosmiei As I mentioned in Issue, I've found it on `ccxt.pro.okx.py`.

https://github.com/ccxt/ccxt/blob/master/python/ccxt/pro/okx.py

**Comment by goznauk** [comment]
and I've just found it on `ccxt.pro.binance.py`, via run `npm run transpile`

https://github.com/ccxt/ccxt/blob/master/python/ccxt/pro/binance.py

**Comment by carlosmiei** [comment]
@goznauk got it, thanks 🙂

**Pull request merged**
