### PR TITLE
gateio add fetchOrder, modify cancelOrder, createOrder & queryDeposit…

### PR DESCRIPTION
**Pull request by lfern**
…Address

### CODE REVIEW

**Comment by kroitor** [comment]
Man, you're so helpful! Merging this shortly ) Respect!

**Comment by kroitor** [comment]
Fixes #2647

**Comment by frosty00** [comment]
@kroitor any chance you could merge this. I wanna build ontop of the `fetchOrders` added in this commit.

**Comment by frosty00** [comment]
Also https://twitter.com/RevelliCarlo twitter bot is starting to pick up speed (;

**Comment by kroitor** [comment]
@frosty00 yep, i'm going to merge this and a few other PRs by @lfern and @grandmore after I merge the promised precision transpiling. The latter will be finished today (at last). Thx for your patience!

**Comment by frosty00** [comment]
Here is `fetchMyTrades` and `fetchOpenOrders` for when this commit is merged.

```
    async fetchOpenOrders (symbol = undefined, since = undefined, limit = undefined, params = {}) {
        this.loadMarkets ();
        let response = this.privatePostOpenOrders ();
        return this.parseOrders (response['orders'], undefined, since, limit);
    }

    async fetchMyTrades (symbol = undefined, since = undefined, limit = undefined, params = {}) {
        this.loadMarkets ();
        if (typeof symbol === 'undefined')
            throw new ExchangeError (this.id + ' fetchMyTrades requires symbol param');
        let market = this.market (symbol);
        let id = market['id'];
        let response = this.privatePostTradeHistory (this.extend ({ 'currencyPair': id }, params));
        return this.parseTrades (response['trades'], market, since, limit);
    }
```

**Comment by egorFiNE** [comment]
Any updates on this one? Badly needed. I implemented part of these methods myself and then found out this PR.

**Comment by egorFiNE** [comment]
```javascript
let timestamp = this.safeInteger (order, 'timestamp');  //* 1000;
```

BTW, gateio returns timestamps in seconds, not milliseconds, so it is indeed necessary to multiply by 1000.

**Comment by frosty00** [comment]
Here are some error codes that could be added to handleErrors also - 

```
            'exceptions': {
                '1': ExchangeError,
                '2': ExchangeError,
                '3': ExchangeError,
                '4': DDoSProtection,
                '10': AuthenticationError,
                '11': InvalidAddress,
                '19': InvalidOrder,
                '20': InvalidOrder,
                '21': InsufficientFunds,
                '101': InsufficientFunds,
            },
```

These are just a few of the errors displayed on their [API docs](https://gate.io/api2#errCode)

**Comment by egorFiNE** [comment]
@frosty00 Actually I have already created handleErrors support based on @lfern work, so as soon as this PR gets merged, I will immediately follow with handleErrors support with those exceptions, just like you listed.

**Comment by frosty00** [comment]
Yeah, I have also built a couple of changes on @lfern 's work. 

@kroitor when will we get this and the forsaken transpilled decimal_to_precision tests merged?

**Comment by frosty00** [comment]
@egorFiNE can you make a new PR with all the changes to gateio?

**Pull request merged**
