### PR TITLE
 adding tokenomy exchange platform (Singapore) to ccxt

### PR DESCRIPTION
**Pull request by yogisofiharja**

### CODE REVIEW

**Comment by kroitor** [comment]
@yogisofiharja hi! Can you plz remove the generated files from this PR? It would help merge it quicker. 

- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#transpiled-generated-files

We need just the `tokenomy.js` file only.

**Comment by yogisofiharja** [comment]
> @yogisofiharja hi! Can you plz remove the generated files from this PR? It would help merge it quicker.
> 
> * https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code
> * https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#transpiled-generated-files
> 
> We need just the `tokenomy.js` file only.

Hi, for sure. i'm sorry for this. will make a new PR soon

**Comment by kroitor** [comment]
@yogisofiharja thx so much! ) And thx for the PR as well! )

**Comment by yogisofiharja** [comment]
another question,
Can i include examples to PR?
thanks

**Comment by kroitor** [comment]
@yogisofiharja sure, you're welcome! )

**Pull request closed without merging**
