### PR TITLE
Bibox handle errors

### PR DESCRIPTION
**Pull request by samgermain**
Builds on https://github.com/ccxt/ccxt/pull/14193

### CODE REVIEW

**Comment by samgermain** [comment]
@pcriadoperez Did you ever get v4 private endpoints working for bibox? The invalid signature error was the reasonn I stopped working on my bibox PR originally. I get this when calling v4 private api endpoints (on this PR, because the handleErrors method isn't correct for bibox either)

```
bibox.v4PrivateGetUserdataFills ()
ExchangeError bibox {"error":-2006,"message":"Invalid signature"}
---------------------------------------------------
[ExchangeError] bibox {"error":-2006,"message":"Invalid signature"}

    at handleErrors               ../../ccxt/ccxt/js/bibox.js:1780               throw new ExchangeError (feedback);                                             
    at                            ../../ccxt/ccxt/js/base/Exchange.js:602        const skipFurtherErrorHandling = this.handleErrors (response.status, response.s…
    at processTicksAndRejections  node:internal/process/task_queues:95                                                                                           
    at async timeout              ../../ccxt/ccxt/js/base/functions/time.js:181  return await Promise.race ([promise, expires.then (() => { throw new TimedOut (…
    at fetch2                     ../../ccxt/ccxt/js/base/Exchange.js:1807       return await this.fetch (request['url'], request['method'], request['headers'],…
    at request                    ../../ccxt/ccxt/js/base/Exchange.js:1811       return await this.fetch2 (path, api, method, params, headers, body, config, con…
    at async run                  ../../ccxt/ccxt/examples/js/cli.js:273         const result = await exchange[methodName] (... args)                            

bibox {"error":-2006,"message":"Invalid signature"}
```

**Comment by pcriadoperez** [comment]
> @pcriadoperez Did you ever get v4 private endpoints working for bibox? The invalid signature error was the reasonn I stopped working on my bibox PR originally. I get this when calling v4 private api endpoints (on this PR, because the handleErrors method isn't correct for bibox either)
> 
> ```
> bibox.v4PrivateGetUserdataFills ()
> ExchangeError bibox {"error":-2006,"message":"Invalid signature"}
> ---------------------------------------------------
> [ExchangeError] bibox {"error":-2006,"message":"Invalid signature"}
> 
>     at handleErrors               ../../ccxt/ccxt/js/bibox.js:1780               throw new ExchangeError (feedback);                                             
>     at                            ../../ccxt/ccxt/js/base/Exchange.js:602        const skipFurtherErrorHandling = this.handleErrors (response.status, response.s…
>     at processTicksAndRejections  node:internal/process/task_queues:95                                                                                           
>     at async timeout              ../../ccxt/ccxt/js/base/functions/time.js:181  return await Promise.race ([promise, expires.then (() => { throw new TimedOut (…
>     at fetch2                     ../../ccxt/ccxt/js/base/Exchange.js:1807       return await this.fetch (request['url'], request['method'], request['headers'],…
>     at request                    ../../ccxt/ccxt/js/base/Exchange.js:1811       return await this.fetch2 (path, api, method, params, headers, body, config, con…
>     at async run                  ../../ccxt/ccxt/examples/js/cli.js:273         const result = await exchange[methodName] (... args)                            
> 
> bibox {"error":-2006,"message":"Invalid signature"}
> ```

Yes, I thought I solved that issue on the last PR and tested the endpoints. But it was a while ago, so I don't really remember anymore.
But I am getting the same error, I'll take a look at the docs and get back to you.

**Comment by pcriadoperez** [comment]
Hi @samgermain , I found the bug in calling the v4 private endpoints and posted a fix here: https://github.com/ccxt/ccxt/pull/14281

Let me know if you run into any other issues.

**Comment by samgermain** [comment]
Moved to #14281

**Pull request closed without merging**
