### PR TITLE
bittrex since filters too many orders

### PR DESCRIPTION
**Pull request by frosty00**
its a bit tacky, however I couldn't think of a better way to solve this issue. I think it may help with the same issue of since using closedAt on other exchanges. And ultimately I wanted to retain the created time information in the `timestamp`.

### CODE REVIEW

**Comment by kroitor** [comment]
To be honest, I don't I think the solution should not be intrusive, i mean this is the Bittrex-specific case, and should be handled in `bittrex.js` rather than added to the base methods for all exchanges.

**Comment by frosty00** [comment]
yes, however would you remove the since parameter completely then?

**Comment by frosty00** [comment]
how do you propose solving the bittrex issue, without removing support for the since in `request[startDate]`?

**Comment by kroitor** [comment]
> however would you remove support for the since parameter completely then?

Why? In order to solve the problem we need to understand the root cause of it. And approach it in a way that would satisfy most of the users. Our rules for pagination state that `since` is for orders that have been created after `since`, so, we need to approach this issue differently. 

> how do you propose solving the bittrex issue, without removing support for the since in request[startDate]?

- First of all, it's not an issue with filtering – the filtering does work, no need to fix it if it works. 
- Second, this is the issue with the understanding of `since` – `fetchClosedOrders` can't return orders created before `since` even in theory.
- Third, because the ability to query orders bittrex-style (by the closing timestamp instead of conventional opening timestamp) may still be a feature very wanted by bittrex users. 

So, I would make the filtering of orders by `since` on the parsing stage optional – controllable on the user side as an exchange option. The `since` argument would still be accepted and sent, but not applied on filtering, if the option is switched off. 

We could call that option `fetchClosedOrdersFilterBySince = true`. The filtering would remain on by default, but users could switch off that specific filtering stage. That requires adding a bittrex-specific override for parseOrders that would account for the option described. And we have to explain the fundamental pagination rules to the user. 

This would be the best approach that would be the least-intrusive backward-compatible way to solve the issue. However, we need to mind exchanges derived from bittrex as well.

**Pull request closed without merging**
