### PR TITLE
fix(base) - ESLINT no shadow

### PR DESCRIPTION
**Pull request by ttodua**
I think it's better we used this, because even though it's valid JS code, it's not multilanguage friendly and we should sacrifice JS's "nice to have" feature.

NOTE: other PRs (named "shadow var"...) need to be merged, after them this PR will pass.

### CODE REVIEW

**Comment by ttodua** [comment]
@carlosmiei when "shadow vars" PRs are approved, then this is the last one, which needs your review, to merge the `eslintrc`. it also involved renaming things in base, and if you feel harder to review this PR, then just do it from the ground on your separate branch, so you can ensure the results are same.

**Comment by ttodua** [comment]
@carlosmiei ^ now passes, as all those individual exchanges/PRs  (with `shadow-vars` issues) were merged

**Comment by carlosmiei** [comment]
> @carlosmiei ^ now passes, as all those individual exchanges/PRs (with `shadow-vars` issues) were merged

@ttodua will check it thanks

**Comment by carlosmiei** [comment]
LGTM

**Review by carlosmiei — APPROVED** [review]

**Pull request merged**
