### PR TITLE
new exchange coinone

### PR DESCRIPTION
**Pull request by jjhesk**
implementation of coinone - first draft success in checking #1209

### CODE REVIEW

**Comment by kroitor** [comment]
Oops, for some reason you again submitted too many files... can you please resubmit just the coinone.js ? That would make it much easier for me to merge! Thank you! )

**Comment by jjhesk** [comment]
just fixed the eslint

**Comment by jjhesk** [comment]
dont get the meaning `TypeError: Cannot read property '1' of null` from transpilig

**Comment by kroitor** [comment]
@jjhesk oh, it's described here: https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#derived-exchange-classes

Basically, the error is because we can't use commented blocks in between the methods and can't use multiline-comments, have to clean it up a little bit...

**Comment by jjhesk** [comment]
@kroitor is there a way to support comment and remain them in js because these are some important note for the devs.

**Comment by jjhesk** [comment]
@kroitor i have no idea on py part transpile, would you help me out?

**Comment by kroitor** [comment]
> @kroitor i have no idea on py part transpile, would you help me out? im limited on this area.

Yep, sure, no worries.

**Pull request closed without merging**
