### PR TITLE
Added funding fee exchange hours to describe.fees

### PR DESCRIPTION
**Pull request by samgermain**
Added the property fees.future.fundingFee.exchangedAt to the exchanges bibox, binance, bybit, ftx, gateio, hitbtc, kraken and kucoin

This property is a dictionary containing the properties
- **start** (string): the time of day that the first funding fee is exchanged with format `hh:mm`
- **interval** (number): The number of hours between funding fee exchanges
Example:

```
`fees`: {
          'fundingFee': {
                        'start': '00:00',
                        'interval': 8,
           },
}
```

This exchange would have funding fees exchanged between traders at times 00:00, 08:00, and 16:00

### CODE REVIEW

**Comment by frosty00** [comment]
idk if this is a good pr, since different contracts have different funding periods

**Comment by kroitor** [comment]
@samgermain that error is intermittent with Travis, we're still investigating into the cause of it, but I suspect that it's some kind of cache on one of the servers on Travis. Still trying to figure it out. One way of mitigating it is to restart the build that will get run on a different vbox.

**Comment by samgermain** [comment]
> starting timestamp in milliseconds (market launch time).

I think that the start time as an hour of the day is much more convenient for users

**Comment by frosty00** [comment]
can we rename `fungingFee` -> `funding`, since it's already inside of the `fee` object

**Review by frosty00 — APPROVED** [review]

**Comment by samgermain** [comment]
> can we rename `fungingFee` -> `funding`, since it's already inside of the `fees` object

The problem is that `funding` already refers to something something else inside the fee subdictionary on some exchanges like bibox and ascendex

--------------

I also realized there's a way to get these hours from the method `fetchFundingRateHistory` by getting all the unique time properties from datetimes, so maybe this PR is unnecessary

Here's a python example

```
funding_rate_timestamps = [
    rate['timestamp'] for rate in exchange.fetch_funding_rate_history(
        exchange.symbols[1],
        limit=48
    )
]
funding_fee_times = list(set([
    int(datetime.utcfromtimestamp(time / 1000).strftime("%H")) for time in funding_rate_timestamps
]))
```

**Comment by frosty00** [comment]
https://www.binance.com/en/support/announcement/c943ef87fdcd40b194884805309f4f7f

different contracts have different funding rate settlement periods, has to be a property of each market

**Pull request closed without merging**
