### PR TITLE
fix(exchange): safemarket with empty delimiter

### PR DESCRIPTION
**Pull request by pcriadoperez**
In php was throwing an error when passing as an empty string delimiter = '';

### CODE REVIEW

**Comment by carlosmiei** [comment]
@pcriadoperez question, can you give an example where this was happening?

**Comment by pcriadoperez** [comment]
> @pcriadoperez question, can you give an example where this was happening?

Yes, it's anywhere were we might do a call like this:
https://github.com/pcriadoperez/ccxt/blob/master/ts/src/pro/bitmart.ts#L935

**Comment by carlosmiei** [comment]
@pcriadoperez ofc we can protect against it, but why would we provide that as a delimiter?

**Comment by pcriadoperez** [comment]
> @pcriadoperez ofc we can protect against it, but why would we provide that as a delimiter? I think we should provide undefined

I agree, I can search and clean up where it's happening, but I thought it was better to protect against it, so the error doesn't sneak in again in the future

**Comment by carlosmiei** [comment]
@pcriadoperez yeah I removed it from bitmart, but we can still merge this just in case

**Pull request merged**
