### PR TITLE
gateio.constructor sets createMarketOrder to true if swap or future

### PR DESCRIPTION
**Pull request by samgermain**
```
Node.js: v14.17.0                            PHP v8.1.6                               Python v3.10.4
CCXT v1.84.75                                CCXT v1.84.75                            CCXT v1.84.75
{                                            gateio->has()                            {'CORS': None,
 publicAPI: true,                            (                                         'addMargin': None,
 privateAPI: true,                            [publicAPI] => 1                         'cancelAllOrders': True,
 CORS: undefined,                             [privateAPI] => 1                        'cancelOrder': True,
 spot: true,                                  [CORS] =>                                'cancelOrders': None,
 margin: true,                                [spot] => 1                              'createDepositAddress': None,
 swap: true,                                  [margin] => 1                            'createLimitOrder': True,
                                                                                       ----------------------------------
 future: true,                                [swap] => 1                              'createMarketOrder': True,
                                                                                       ----------------------------------
 option: undefined,                           [future] => 1                            'createOrder': True,
 addMargin: undefined,                        [option] =>                              'createPostOnlyOrder': True,
 cancelAllOrders: true,                       [addMargin] =>                           'createReduceOnlyOrder': None,
 cancelOrder: true,                           [cancelAllOrders] => 1                   'createStopLimitOrder': True,
 cancelOrders: undefined,                     [cancelOrder] => 1                       'createStopMarketOrder': False,
 createDepositAddress: undefined,             [cancelOrders] =>                        'createStopOrder': True,
 createLimitOrder: true,                      [createDepositAddress] =>                'editOrder': 'emulated',
-----------------------------
 createMarketOrder: true,                     [createLimitOrder] => 1                  'fetchAccounts': None,
-----------------------------                 -----------------------------
 createOrder: true,                           [createMarketOrder] => 1                 'fetchBalance': True,
                                             -----------------------------
 createPostOnlyOrder: true,                   [createOrder] => 1                       'fetchBidsAsks': None,
 createReduceOnlyOrder: undefined,            [createPostOnlyOrder] => 1               'fetchBorrowInterest': None,
 createStopOrder: true,                       [createReduceOnlyOrder] =>               'fetchBorrowRate': False,
 createStopLimitOrder: true,                  [createStopOrder] => 1                   'fetchBorrowRateHistories': False,
 createStopMarketOrder: false,                [editOrder] => emulated                  'fetchBorrowRateHistory': False,
 editOrder: 'emulated',                       [fetchAccounts] =>                       'fetchBorrowRates': False,
 fetchAccounts: undefined,                    [fetchBalance] => 1                      'fetchBorrowRatesPerSymbol': None,
 fetchBalance: true,                          [fetchBidsAsks] =>                       'fetchCanceledOrders': None,
 fetchBidsAsks: undefined,                    [fetchBorrowInterest] =>                 'fetchClosedOrder': None,
 fetchBorrowInterest: undefined,              [fetchBorrowRate] =>                     'fetchClosedOrders': True,
 fetchBorrowRate: false,                      [fetchBorrowRateHistory] =>              'fetchCurrencies': True,
 fetchBorrowRateHistory: false,               [fetchBorrowRatesPerSymbol] =>           'fetchDeposit': None,
 fetchBorrowRatesPerSymbol: undefined,        [fetchBorrowRates] =>                    'fetchDepositAddress': True,
 fetchBorrowRates: false,                     [fetchCanceledOrders] =>                 'fetchDepositAddresses': None,
 fetchCanceledOrders: undefined,              [fetchClosedOrder] =>                    'fetchDepositAddressesByNetwork': None,
 fetchClosedOrder: undefined,                 [fetchClosedOrders] => 1                 'fetchDeposits': True,
 fetchClosedOrders: true,                     [fetchCurrencies] => 1                   'fetchFundingFee': None,
 fetchCurrencies: true,                       [fetchDeposit] =>                        'fetchFundingFees': None,
 fetchDeposit: undefined,                     [fetchDepositAddress] => 1               'fetchFundingHistory': True,
 fetchDepositAddress: true,                   [fetchDepositAddresses] =>               'fetchFundingRate': True,
 fetchDepositAddresses: undefined,            [fetchDepositAddressesByNetwork] =>      'fetchFundingRateHistory': True,
 fetchDepositAddressesByNetwork: undefined,   [fetchDeposits] => 1                     'fetchFundingRates': True,
 fetchDeposits: true,                         [fetchFundingFee] =>                     'fetchIndexOHLCV': True,
 fetchTransactionFee: undefined,              [fetchFundingFees] =>                    'fetchL2OrderBook': True,
 fetchTransactionFees: true,                  [fetchFundingHistory] => 1               'fetchLedger': None,
 fetchFundingHistory: true,                   [fetchFundingRate] => 1                  'fetchLedgerEntry': None,
 fetchFundingRate: true,                      [fetchFundingRateHistory] => 1           'fetchLeverage': False,
 fetchFundingRateHistory: true,               [fetchFundingRates] => 1                 'fetchLeverageTiers': True,
 fetchFundingRates: true,                     [fetchIndexOHLCV] => 1                   'fetchMarkOHLCV': True,
 fetchIndexOHLCV: true,                       [fetchL2OrderBook] => 1                  'fetchMarketLeverageTiers': 'emulated',
 fetchL2OrderBook: true,                      [fetchLedger] =>                         'fetchMarkets': True,
 fetchLedger: undefined,                      [fetchLedgerEntry] =>                    'fetchMyTrades': True,
 fetchLedgerEntry: undefined,                 [fetchLeverageTiers] => 1                'fetchNetworkDepositAddress': True,
 fetchLeverageTiers: true,                    [fetchMarketLeverageTiers] => emulated   'fetchOHLCV': True,
 fetchMarketLeverageTiers: 'emulated',        [fetchMarkets] => 1                      'fetchOpenInterestHistory': False,
 fetchMarkets: true,                          [fetchMarkOHLCV] => 1                    'fetchOpenOrder': None,
 fetchMarkOHLCV: true,                        [fetchMyTrades] => 1                     'fetchOpenOrders': True,
 fetchMyTrades: true,                         [fetchOHLCV] => 1                        'fetchOrder': True,
 fetchOHLCV: true,                            [fetchOpenOrder] =>                      'fetchOrderBook': True,
 fetchOpenOrder: undefined,                   [fetchOpenOrders] => 1                   'fetchOrderBooks': None,
 fetchOpenOrders: true,                       [fetchOrder] => 1                        'fetchOrderTrades': None,
 fetchOrder: true,                            [fetchOrderBook] => 1                    'fetchOrders': None,
 fetchOrderBook: true,                        [fetchOrderBooks] =>                     'fetchPermissions': None,
 fetchOrderBooks: undefined,                  [fetchOrders] =>                         'fetchPosition': None,
 fetchOrders: undefined,                      [fetchOrderTrades] =>                    'fetchPositions': True,
 fetchOrderTrades: undefined,                 [fetchPermissions] =>                    'fetchPositionsRisk': None,
 fetchPermissions: undefined,                 [fetchPosition] =>                       'fetchPremiumIndexOHLCV': False,
 fetchPosition: undefined,                    [fetchPositions] => 1                    'fetchStatus': 'emulated',
 fetchPositions: true,                        [fetchPositionsRisk] =>                  'fetchTicker': True,
 fetchPositionsRisk: undefined,               [fetchPremiumIndexOHLCV] =>              'fetchTickers': True,
 fetchPremiumIndexOHLCV: false,               [fetchStatus] => emulated                'fetchTime': False,
 fetchStatus: 'emulated',                     [fetchTicker] => 1                       'fetchTrades': True,
 fetchTicker: true,                           [fetchTickers] => 1                      'fetchTradingFee': True,
 fetchTickers: true,                          [fetchTime] =>                           'fetchTradingFees': True,
 fetchTime: false,                            [fetchTrades] => 1                       'fetchTradingLimits': None,
 fetchTrades: true,                           [fetchTradingFee] => 1                   'fetchTransactionFees': True,
 fetchTradingFee: true,                       [fetchTradingFees] => 1                  'fetchTransactions': None,
 fetchTradingFees: true,                      [fetchTradingLimits] =>                  'fetchTransfers': None,
 fetchTradingLimits: undefined,               [fetchTransactions] =>                   'fetchWithdrawal': None,
 fetchTransactions: undefined,                [fetchTransfers] =>                      'fetchWithdrawals': True,
 fetchTransfers: undefined,                   [fetchWithdrawal] =>                     'future': True,
 fetchWithdrawal: undefined,                  [fetchWithdrawals] => 1                  'loadMarkets': True,
 fetchWithdrawals: true,                      [loadMarkets] => 1                       'margin': True,
 loadMarkets: true,                           [reduceMargin] =>                        'option': None,
 reduceMargin: undefined,                     [setLeverage] => 1                       'privateAPI': True,
 setLeverage: true,                           [setMargin] =>                           'publicAPI': True,
 setMargin: undefined,                        [setMarginMode] =>                       'reduceMargin': None,
 setMarginMode: false,                        [setPositionMode] =>                     'setLeverage': True,
 setPositionMode: undefined,                  [signIn] =>                              'setMargin': None,
 signIn: undefined,                           [transfer] => 1                          'setMarginMode': False,
 transfer: true,                              [withdraw] => 1                          'setPositionMode': None,
 withdraw: true,                              [createStopLimitOrder] => 1              'signIn': None,
 fetchBorrowRateHistories: false,             [createStopMarketOrder] =>               'spot': True,
 fetchLeverage: false,                        [fetchBorrowRateHistories] =>            'swap': True,
 fetchNetworkDepositAddress: true,            [fetchLeverage] =>                       'transfer': True,
 fetchOpenInterestHistory: false              [fetchNetworkDepositAddress] => 1        'withdraw': True}
}                                             [fetchOpenInterestHistory] =>           
                                              [fetchTransactionFees] => 1             
                                             )                                        
```

### CODE REVIEW

**Comment by kroitor** [comment]
I would suggest to move this bit to `describe()`, since it's called from the constructor (and we cannot transpile constructors).

**Comment by samgermain** [comment]
> I would suggest to move this bit to `describe()`, since it's called from the constructor (and we cannot transpile constructors).

I don't understand how that would work, the `type` wouldn't be set yet, so you couldn't check if it's spot or futures

Writing the transpilation for constructor also wouldn't be very hard

**Comment by samgermain** [comment]
The word `constructor` won't be transpiled

**Comment by kroitor** [comment]
Those regexes are wrong, and we should not change the common regexes, just the python and php regexes:

Screenshot 2022-04-07 at 08 43 21

I'll edit this PR before merging.

**Comment by samgermain** [comment]
> Those regexes are wrong, and we should not change the common regexes, just the python and php regexes:
> 
> Screenshot 2022-04-07 at 08 43 21
> 
> I'll edit this PR before merging.

I know that they are wrong, no matter what I do, I can't get the word `constructor` to transpile to `__init__` for python

**Comment by samgermain** [comment]
@kroitor I create I new method of doing this that you might like, it involves creating a method called `ccxtContructor` and then all the `constructor method does, is call this method, which contains the code that was in constructor. The new method can be transpiled like any other language

**Pull request closed without merging**
