### PR TITLE
new exchange: cobinhood

### PR DESCRIPTION
**Pull request by Deathamns**
#885

### CODE REVIEW

**Comment by kroitor** [comment]
Multi-kill! ))

**Comment by NullVoxPopuli** [comment]
Adding this link to docs for easy finding: https://cobinhood.github.io/api-public/ :-)

I'm excited for this addition!

**Comment by snugghash** [comment]
Strangely enough, I can't find your cobinhood.js in @Deathamns 's forked repo. Or the transpiled code in other folders. How can I run this before the official merge?

Also, does this need any help? I can contribute a few hours, and I want this up too.

**Comment by Deathamns** [comment]
You can help testing it, as I mostly just blindly implemented the private APIs.

**Comment by snugghash** [comment]
@Deathamns I can't find it though. I look for these changes in Deathmans/ccxt and it doesn't have cobinhood.js

**Comment by kroitor** [comment]
@snugghash it's in the `cobinhood` branch
screen shot 2018-01-16 at 19 05 03

**Comment by kroitor** [comment]
Merging this one next )

**Comment by NullVoxPopuli** [comment]
@Deathamns how are you testing this? I don't see anywhere to actually get an api key

**Comment by Deathamns** [comment]
@NullVoxPopuli I didn't find it either. Maybe you have to be verified first, or as the docs says it, their API is still experimental. Most of the exchanges I did, I implemented their private APIs blindly, that's why they need testing.

**Pull request merged**
