### PR TITLE
`array` rename

### PR DESCRIPTION
**Pull request by ttodua**

### CODE REVIEW

**Comment by frosty00** [comment]
i've restored the js test cause it's not transpiled

**Comment by ttodua** [comment]
> i've restored the js test cause it's not transpiled

ok, but in long run, would that hurt if we avoided `array` variables at all?

**Comment by frosty00** [comment]
@ttodua we will avoid it in the future in transpiled tests, which is something we are moving to. However editing existing code that already works just to change variable names (that might break things) is not worth it.

**Comment by ttodua** [comment]
> @ttodua we will avoid it in the future in transpiled tests, which is something we are moving to. However editing existing code that already works just to change variable names (that might break things) is not worth it.

yeah, my question was "what just changing variable name might break there" as you know full insights behind it, but i didnt know and wanted to find out more info about that 'possibilities', but ok, dont mind.

**Pull request merged**
