### PR TITLE
add fetchMyTrades method to SouthXchange wrapper

### PR DESCRIPTION
**Pull request by inuitwallet**
Hi,

I've had a go at adding the fetchMyTrades method to the SouthXchange wrapper.
I followed the CONTRIUBUTING guide as closely as I could but apologies if I've missed something. The transpilation to python and PHP seemed to go well though so I can't be far off.

I wasn't able to run all the tests against the updated wrapper. SouthXchange wants to use milliseconds for the nonce (at least, using my account it does. It's possible that it's just because I've been using milliseconds historically and it always wants a higher nonce) and I wasn't able to see how to get the tests to use a millisecond nonce. Apologies for that.

The method is a bit tricky as SouthXchange hide the private trades inside the listTransactions API endpoint along with all deposits and withdrawals. I'm a Python dev primarily so apologies too if my Javascript is a little off.

### CODE REVIEW

**Comment by kroitor** [comment]
> The method is a bit tricky as SouthXchange hide the private trades inside the listTransactions API endpoint along with all deposits and withdrawals.

Yes, we have the same configuration with other exchanges that do not return just the trades, but return all balance modifications instead. So we decided to introduce a class of new entities, called `Ledger` and `LedgerEntry`: https://github.com/ccxt/ccxt/wiki/Manual#ledger that would cover this case. Those are closer to the accounting principles. However, the exchanges don't always include prices in their ledgers, and a trade is technically equal to 2 ledger entries (one subtraction from base/quote + one addition to base/quote), where a deposit or a withdrawal are equal to 1 ledger entry each (subtraction or addition). Sometimes the fee is a separate entry in the ledger, thus a complete ledger history for a sell ETH/BTC trade would look like 3 ledger entries on different currencies:
- subtraction from ETH
- addition to BTC
- fee in ETH, BTC or other currency

One particular issue why the `fetchMyTrades` model is not fully applicable here – it does break the pagination. 

- https://github.com/ccxt/ccxt/wiki/Manual#pagination

With this implementation of fetchMyTrades we have to filter out the unrelated deposits and withdrawals (or whatever other type of balance modifications the exchange may introduce in the future, like referral bonuses, maker bonuses, etc..). Without the pagination it's very hard to traverse the history. So, if it doesn't work as the user expects, then it requires tedious workarounds. The `fetchLedger`'s pagination isn't ideal either – because it also breaks the `limit` argument in the pagination mechanism.

So, from here what we could do is:

- either rewrite this for southxchange + fetchLedger
- have fetchMyTrades with southxchange with a known pagination flaw in it
- have both of the above
- other

What would you suggest, @inuitwallet , @ndubel  ?

**Comment by inuitwallet** [comment]
Ah! I wasn't aware of fetchLedger. That does feel a better fit for how the data is received. I'll look at implementing that. For my workflow I do need a fetchMyTrades method though so would like to leave that in even if it has the pagination flaw if possible? I could call the fetchLedger method and just filter the trades though. Does that seem acceptable?

**Comment by kroitor** [comment]
@inuitwallet 

> I could call the fetchLedger method and just filter the trades though. Does that seem acceptable?

To me that seems the better way to go than having a flawed fetchMyTrades. So, if you could add `fetchLedger` (and then do the filtering on your side) – that would be awesome. However, it may be tricky enough, because for trades we will have to add two ledger entries instead of one, see how that is done in coinfloor: https://github.com/ccxt/ccxt/blob/master/js/coinfloor.js#L326. And, after all, adding two trades per one entry also breaks the pagination. So, in the end, we will probably end up having both `fetchMyTrades` and `fetchLedger` with known pagination flaws.

Here's what we need to do to get this implementation merged:

- On `fetchMyTrades` in particular – we have to call `parseTrades` instead of a loop here: https://github.com/ccxt/ccxt/pull/6198/files#diff-556dcc516be50045e7621c628a350705R277 – we should unify all trade parsing in parseTrade. See how the same is done in the other exchanges. The filtering by type is done with `this.filterBy`, again, see how that is used in other exchanges.

- We need to clean it up a bit, no need to write the word `response` multiple times:

```Python
        request['TransactionType'] = 'transactions';
        request['SortField'] = 'Date';
        request['Descending'] = true;
```
 if you want to say:

```JavaScript
const response = {
   ...
   'TransactionType': 'transactions',
   'SortField': 'Date',
   'Descending': true,
};
// much cleaner right? ;)
```

- Of course, we don't have to call `safeString (trade, 'Amount')` twice here:
    - https://github.com/ccxt/ccxt/pull/6198/files#diff-556dcc516be50045e7621c628a350705R227
    - https://github.com/ccxt/ccxt/pull/6198/files#diff-556dcc516be50045e7621c628a350705R235
    
    A good rule of thumb – if you call the same pure function twice or more with the same arguments – make a constant or a variable for the value.

- And we need to make sure that there is no violations of CONTRIBUTING guidelines for sanitizing in the parser, here:
    - https://github.com/ccxt/ccxt/pull/6198/files#diff-556dcc516be50045e7621c628a350705R235
    - https://github.com/ccxt/ccxt/pull/6198/files#diff-556dcc516be50045e7621c628a350705R249

We need to use `safeString` and other `safe*` methods everywhere. However, because a safe-method can return an `undefined` value, we should check if it is not undefined before trying to do anything meaningful with it, like arithmetic operations, comparisons, etc... So, 

```
if (this.safeFloat (trade, 'Amount') > 0.0) {
}
```
↓
```
const amount = this.safeFloat (trade, 'Amount');
// ...
if ((amount !== undefined) && (amount > 0.0)) {
}
```

**Comment by ndubel** [comment]
it's not possible to add `fetchMyTrades` method, only `fetchLedger`?

**Comment by kroitor** [comment]
@ndubel yep, they only allow one of these types:
- "transactions" (trades + deposits + withdrawals)
- "deposits"
- "withdrawals"
- "depositswithdrawals"

No separate value for "just the personal trades".

**Comment by kroitor** [comment]
@ndubel also, in most cases a trade in a ledger is represented as 2 rows (income and outcome) not one.

**Pull request closed without merging**
