### PR TITLE
remove symbols

### PR DESCRIPTION
**Pull request by jjhesk**
BCC, BT1, BT2, BCU are removed from bitfienx

### CODE REVIEW

**Comment by frosty00** [comment]
call load_markets() perhaps...

**Comment by jjhesk** [comment]
@frosty00 
it has been taken off from the official trading market now. you may go check,

**Comment by frosty00** [comment]
@jjhesk the fix is pretty simple in Python.

Inside bitfinex2 add

    def fetch_markets(self):
        return bitfinex().fetch_markets()

**Comment by kroitor** [comment]
Thank you!

**Pull request merged**
