### PR TITLE
Fix decimal_to_precision for really small numbers

### PR DESCRIPTION
**Pull request by beniloew**
This applies only for TRUNCATE and DECIMAL_PLACES, though the method
used could be helpfull for other methods

Signed-off-by: Beni Lev <beniloew@gmail.com>

### CODE REVIEW

**Comment by beniloew** [comment]
Didnt had time to test this at all, maybe tomorrow

**Comment by kroitor** [comment]
@beniloew any problems/difficulties with it? just let me know if anything

**Comment by beniloew** [comment]
Did close it by mistake
Just created a new one now.

**Comment by beniloew** [comment]
https://github.com/ccxt/ccxt/pull/3803
Sorry about that

**Comment by kroitor** [comment]
No worries )

**Pull request closed without merging**
