### PR TITLE
- "kucoin futures" tag removal

### PR DESCRIPTION
**Pull request by ttodua**
it was duplicate of :589 line

### CODE REVIEW

**Comment by kroitor** [comment]
> it was duplicate of :589 line

Those tags are actually generated, so removing one manually from there won't help – will be overwritten on Travis. Gotta fix the root cause of it (if it's really necessary).

**Comment by kroitor** [comment]
Here: https://github.com/ccxt/ccxt/blob/master/build/export-exchanges.js#L369

**Comment by kroitor** [comment]
We can add a call to `unique` here: https://github.com/ccxt/ccxt/blob/master/build/export-exchanges.js#L384

```JavaScript
packageJSON.keywords = [ ... unique (keywords) ]
```

**Comment by ttodua** [comment]
yes, I think keyword spamming is not of any good effect (maybe it doesn't get any penalties from search engines of whatseover, but why to risk/spam?) so, let's clear them.
Btw, there are also cases of same phrases with just difference of Uppercase/lowecase. Will your above `unique` approach filter them too?

**Comment by kroitor** [comment]
> Will your above `unique` approach filter them too?

Nope, it will filter out just the strict matches. Will get to it soon.

**Pull request closed without merging**
