### PR TITLE
Browser bundle :: allow webworker usage

### PR DESCRIPTION
**Pull request by carlosmiei**
Web Workers don't have a window object so as is` ccxt.browser` can't be imported because we're assuming that window is defined. I added that check. Should have no impact on normal browser usage (I've tested ofc).

image

More info: https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Using_web_workers

### CODE REVIEW

**Comment by frosty00** [comment]
#12646

**Comment by frosty00** [comment]
@carlosmiei can you test if my edit works in a webworker with the global "ccxt"

**Comment by kroitor** [comment]
Before we merge, let's also make sure to test it within the regular in-browser context (not in a webworker). That line was there for a reason, put simply. Cause we have to support quite a number of browsers.

**Comment by frosty00** [comment]
i've refixed it and tested it and it's working in both normal and webworker contexts, pls test and lmk if it doesn't work

**Comment by carlosmiei** [comment]
> i've refixed it and tested it and it's working in both normal and webworker contexts, pls test and lmk if it doesn't work

@frosty00 I've tested and it is all good now

**Comment by kroitor** [comment]
@carlosmiei thx, I'll test on my side as well and will merge.

**Pull request merged**
