### PR TITLE
fix(bitmart) - watch tickers filter

### PR DESCRIPTION
**Pull request by ttodua**

### CODE REVIEW

**Comment by ttodua** [comment]
@carlosmiei PR ready.

**Comment by ttodua** [comment]
unrelated travis issues

**Comment by ttodua** [comment]
not yet ready

**Comment by carlosmiei** [comment]
continues here https://github.com/ccxt/ccxt/pull/20711

**Comment by ttodua** [comment]
> continues here #20711

bitmart had other issues too and that PR wouldnt fix, but i'll re-open a new PR later

**Pull request closed without merging**
