### PR TITLE
lbank v2

### PR DESCRIPTION
**Pull request by DoctorSlimm**

### CODE REVIEW

**Comment by aFluxx** [comment]
Hi,

I've been testing out the `fetch_my_trades` method and it seems that it doesn't always retrieve data. For example I have the following transactions for coin `dba_usdt`. These transactions are from yesterday & today, so it shouldn't interfere with their restriction of [2 days](https://docs.lbkex.net/en/#historical-transaction-details)


Trade Time | Direction | Price(USDT) | Amount(DBA) | Vol(USDT) | Fee rate | Fee
-- | -- | -- | -- | -- | -- | --
2022-04-21 20:36:04 | SELL | 0.1818 | 63.52 | 11.5479 | 0.1% | 0.01154800 USDT
2022-04-21 19:34:51 | BUY | 0.1715 | 63.59 | 10.9056 | 0.1% | 0.06359000 DBA
2022-04-20 22:54:37 | SELL | 0.1867 | 36.95 | 6.8985 | 0.1% | 0.00689900 USDT
2022-04-20 20:47:08 | BUY | 0.1730 | 36.99 | 6.3992 | 0.1% | 0.03699000 DBA


But when I query the endpoint I don't get any transactions, I just get an empty array `[ ]`



For example I have one EOS trade

Trade Time | Direction | Price(USDT) | Amount(EOS) | Vol(USDT) | Fee rate | Fee
-- | -- | -- | -- | -- | -- | --
2022-04-20 19:40:46 | SELL | 2.5981 | 93.3238 | 216.4835 | 0.1% | 0.21648400 USDT


But when I query the endpoint I get the following result from the `$response` :

```
array:4 [
  "result" => true
  "data" => array:2 [
    "page_length" => "100"
    "current_page" => "1"
  ]
  "error_code" => "0"
  "ts" => "1650572732770"
]
```

So the response is valid (no error code), but the data is empty.

**Comment by kroitor** [comment]
@aFluxx thx for your feedback, we will check and will add edits where possible.

**Comment by samgermain** [comment]
Should [this PR](https://github.com/ccxt/ccxt/pull/8221) be closed?

**Comment by kroitor** [comment]
> Should [this PR](https://github.com/ccxt/ccxt/pull/8221) be closed?

No worries, I'll merge related PRs to credit the contributors.

**Comment by zgayjjf** [comment]
> 

I asked their customer service and they said that those pairs were inactive, and would be delisted in the future.

**Comment by zgayjjf** [comment]
> @kroitor @DoctorSlimm
> 
> I've done some trades on another pair (`ray_usdt`) and for this pair the methods do return trade data.
> 
> There doesn't really seem to be a red wire here. For example, `eos_usdt` is a pretty high volume pair and this does not return data. While `dba_usdt` is a pretty low volume pair, also no data.
> 
> And for `ray_usdt` (a pretty high volume pair) I do retrieve data.
> 
> I've also noticed that the https://www.lbkex.net/v2/accuracy.do does not return all pairs listed on their GUI. I've sent them an enquiry asking why this is, no reply atm.
> 
> For example; the following pairs are tradeable via their GUI, but are not returned via their api: LVI/USDT - https://www.lbank.info/exchange/lvi/usdt/#usd BTY/USDT - https://www.lbank.info/exchange/bty/usdt/#usd EBSO/UDST - https://www.lbank.info/exchange/ebso/usdt/#usd

@aFluxx 
I asked their customer service and they said that those pairs were inactive, and would be delisted in the future.

**Comment by kroitor** [comment]
@aFluxx thanks for your feedback, it is very much appreciated!

**Comment by aFluxx** [comment]
> > @kroitor @DoctorSlimm
> > I've done some trades on another pair (`ray_usdt`) and for this pair the methods do return trade data.
> > There doesn't really seem to be a red wire here. For example, `eos_usdt` is a pretty high volume pair and this does not return data. While `dba_usdt` is a pretty low volume pair, also no data.
> > And for `ray_usdt` (a pretty high volume pair) I do retrieve data.
> > I've also noticed that the https://www.lbkex.net/v2/accuracy.do does not return all pairs listed on their GUI. I've sent them an enquiry asking why this is, no reply atm.
> > For example; the following pairs are tradeable via their GUI, but are not returned via their api: LVI/USDT - https://www.lbank.info/exchange/lvi/usdt/#usd BTY/USDT - https://www.lbank.info/exchange/bty/usdt/#usd EBSO/UDST - https://www.lbank.info/exchange/ebso/usdt/#usd
> 
> @aFluxx I asked their customer service and they said that those pairs were inactive, and would be delisted in the future.

One more thing to add here. There's coins which do more then 500K/24h volume which are not provided by their [api endpoint](https://www.lbkex.net//v2/accuracy.do). I'm pretty sure it's not only about coins being delisted.

They purposely leave some of the trading pairs out of reach for API access. f.e: [NTX/USDT](https://www.lbank.info/exchange/ntx/usdt/#usd)

**Comment by zgayjjf** [comment]
Any progress here? 😄

**Comment by samgermain** [comment]
@DoctorSlimm Could add support for the `stopPrice` param in `createOrder` or add these to has

```
"createStopOrder": false,
"createStopLimitOrder": false,
"createStopMarketOrder": false,
````

**Pull request merged**
