### PR TITLE
Fix: okex3.fetchOHLCV throws on undefined answer

### PR DESCRIPTION
**Pull request by brandsimon**

### CODE REVIEW

**Comment by kroitor** [comment]
@brandsimon can you plz elaborate a bit on the nature of this error? It would be super-awesome if you could post your verbose response for this case, because, if `undefined` made it through the callchain, then we might have a bug somewhere lower down the callstack.

**Comment by brandsimon** [comment]
@kroitor 
Thank you for the information.
This happend in the python implementation. I can look into this later.

**Comment by kroitor** [comment]
@brandsimon that would be awesome! Thx so much, lmk if anything!

**Comment by brandsimon** [comment]
@kroitor 
Sorry, cant reproduce. It happend with python3.

**Comment by kroitor** [comment]
@brandsimon no worries! let me know if you encounter it again... thx!

**Comment by brandsimon** [comment]
@kroitor
You are right, I dont fix the problem! 
```
                                                                                 File "/usr/lib/python3/dist-packages/ccxt/base/exchange.py", line 455, in request
                                                                                   return self.fetch2(path, api, method, params, headers, body)
                                                                                 File "/usr/lib/python3/dist-packages/ccxt/base/exchange.py", line 451, in fetch2
                                                                                   return self.fetch(request['url'], request['method'], request['headers'], request['body'])
                                                                                 File "/usr/lib/python3/dist-packages/ccxt/base/exchange.py", line 547, in fetch
                                                                                   self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response)
                                                                                 File "/usr/lib/python3/dist-packages/ccxt/okex3.py", line 2581, in handle_errors
                                                                                   message = self.safe_string(response, 'message')
                                                                                 File "/usr/lib/python3/dist-packages/ccxt/base/exchange.py", line 607, in safe_string
                                                                                   return str(dictionary[key]) if key is not None and (key in dictionary) and dictionary[key] is not None else default_value
                                                                               TypeError: argument of type 'NoneType' is not iterable
```

**Comment by brandsimon** [comment]
@kroitor Pls merge

**Pull request merged**
