### PR TITLE
PHP/Exchange verbosity option

### PR DESCRIPTION
**Pull request by dennydanek**
PHP class Exchange

in function filter_by_value_since_limit was used variable $key which wasn't declare inside of array_filter function

user defined function for display verbosity added for better readability. will be store in $this->verboseUserFunc and default value is the same as was.

### CODE REVIEW

**Comment by kroitor** [comment]
Hi! Thx for the PR! Appreciate your help!

> in function filter_by_value_since_limit was used variable $key which wasn't declare inside of array_filter function

Yes, you're right on this one.

> user defined function for display verbosity added for better readability. will be store in $this->verboseUserFunc and default value is the same as was.

We need to keep it unified across all languages, so i was thinking of adding a base method for printing, that could be overrided via both constructor args and subclassing. Do you mind if I revert this change for now and merge just the first one?

**Comment by dennydanek** [comment]
Hi, thanks for reply!
I can't really help with the other languages. But the public functions for verbose sounds good and it's even better than this solution.

**Comment by kroitor** [comment]
@dennydanek alright, will edit and will merge it shortly, thx again!

**Comment by kroitor** [comment]
@dennydanek i've merged the `$key` fix for now and will also add those base methods to all languages including PHP soon. Will be happy to see more PRs from you in the future.

**Comment by dennydanek** [comment]
Maybe I'm wrong but the commit what you merged is d10a2cb - the bad one :-O

**Comment by kroitor** [comment]
@dennydanek nope, it's the right one: https://github.com/ccxt/ccxt/commit/8db43844718191704127329a4815bbd9b25fc746 )

**Pull request merged**
