### PR TITLE
fix!(exceptions) - ProxyError into InvalidProxySettings

### PR DESCRIPTION
**Pull request by ttodua**

### CODE REVIEW

**Comment by carlosmiei** [comment]
@ttodua you can't only update the proxy exception and not update the static tests where we're relying on it to avoid the request

**Comment by ttodua** [comment]
> @ttodua you can't only update the proxy exception and not update the static tests where we're relying on it to avoid the request

I don't know what i was thinking about when I submitted this PR 😶‍🌫️

pushed now

**Comment by carlosmiei** [comment]
build still broken here

**Comment by ttodua** [comment]
one sec

**Comment by ttodua** [comment]
@carlosmiei i dont understand how that issue happens on travis. that proxyError reference lives nowhere across lib now

**Comment by ttodua** [comment]
ah, seems inside `transpile.js` itself

**Pull request merged**
