### PR TITLE
Load Bittrex fees

### PR DESCRIPTION
**Pull request by frosty00**
More eloquent solution to my pull request yesterday. This loads withdraw fees from the publicGetCurrencies into the fees attribute of the object. A great learning experience!

### CODE REVIEW

**Comment by kroitor** [comment]
@frosty00 have you explored the `.currencies` property yet? All your fees should be there (see fetchCurrencies()). We basically don't need to fetch them twice %)

**Comment by frosty00** [comment]
I'm aware but it would be nice to have all the fees the same place for all exchanges, you even said so yourself in a comment: `// todo: will need to rethink the fees`

**Comment by frosty00** [comment]
I think this is better than https://github.com/ccxt/ccxt/commit/4e6c48b2ef4ad71cebcb70670b2bbf7e0c746b46 since it will stay up to date when the exchange updates the withdrawal fee to reflect the price of the token.

**Comment by kroitor** [comment]
> but it would be nice to have all the fees the same place for all exchanges

Aren't they already in the same place? Trading fees in markets, withdrawal fees in currencies, everywhere? ;) Seriously, think, why wouldn't I document them in the exchange properties, and why would I document them in the markets and currencies. This is because the `.fees` property in the exchange is a non-recommended way of setting up hardcoded fees.

Basically, the designed way of working with fees is via markets and currencies, not via the `.fees` property. Anyway, even if you take your own idea a step further, those fees should have been populated from fetchCurrencies into `.fees`, because they use the same endpoint, right? And, they are getting populated, right where they should – into currencies. It becomes obvious, that fees themselves are not properties of exchanges, fees are properties of markets and currencies within exchanges. Does it make sense?

> you even said so yourself in a comment: // todo: will need to rethink the fees

By rethinking, I mean a conceptual redesign of the fee structure, it has to account for different types of fees, percentage and flat formulas for commissions, the fee currency (on Binance you can trade ETH/BTC and pay fees in BNB), the cost, the rate, and maybe some other properties and special cases:

'fee': { currency: ..., cost: ... , rate: percentageOrFlat, ... }

**Comment by frosty00** [comment]
So basically the .fees property is just hardcoded fees, whereas .currencies actually fetches them from the exchange. Well since I can't code transpillable javascript at all I guess I could help express what you just said in the wiki...

`
             Fees (wip)
                Maker / Taker Order Fees
                Deposit / Withdraw
`

**Comment by kroitor** [comment]
> So basically the .fees property is just hardcoded fees, whereas .currencies actually fetches them from the exchange.

Yep, we only use them when there's no other way of fetching "live" fees. Sorry for the confusion with the fees, the docs could be better, you're right.

>  I could help express what you just said in the wiki...

You're awesome! ) That would be great! And thx a lot! Really appreciate your effort!

**Comment by frosty00** [comment]
Would you consider populating the fees property from loadMarkets since fees are already in the same place, and could be loaded in into .fees in the base Exchange class?

It is slightly easier to read and could make for a slightly better API. It's your call but as someone trying to do computations that involved fees the first place I, and probably others, looked was .fees and not .markets or .currencies.

**Comment by kroitor** [comment]
> Would you consider populating the fees property from loadMarkets since fees are already in the same place, and could be loaded in into .fees in the base Exchange class?

Yes, we think this is a task for the base class, indeed. No need to duplicate the code, as long as the info is populated into markets and currencies, the base class code can take the normalized info and denormalize it a little by duplicating it into the `.fees` property, for convenience. I'd say, it is the preferred and the least intrusive method of solving this particular issue. I don't mind doing that at all. We can start with Python, I would then port it to JS and PHP, for example.

**Comment by frosty00** [comment]
Awesome, I'll start the Python implementation now since I can actually understand that language 😜

I'll make a pull request when I'm done.

Appreciate all the work you're doing for this project. I'm writing a Python trading bot based off the unified API that you're providing.

**Comment by kroitor** [comment]
Thank you again, @frosty00 ! I would still appreciate your help on the docs after we populate those fees properly ) Let me know if you have any questions, will be happy to answer!

**Comment by frosty00** [comment]
If you were to redesign the structure of the fee dictionary, how would you go about it. Perhaps we could make it:

    'fees': 
        {'ETH': 
            {'withdraw': 'x',
             'deposit': 'y',
             'taker': 'z'
             'maker': 'j'
             'special': False,
             },
         'BCH': ...

And we could assume that maker and taker are always percentagebased and withdraw and deposit are always flat rates. Are there any exchanges that are exceptions to this rule?

**Comment by kroitor** [comment]
> Are there any exchanges that are exceptions to this rule?

Well... all of them )

Think this way: there are no `maker` and `taker` fees for `ETH`, because you can't trade ETH for itself. You trade `ETH` (a currency) against, say, `BTC` (some other currency), that makes it a trading pair of `ETH/BTC` and the trading fee relates to that pair, it's not related to either of the two currencies. Also, ETH can be traded against USDT and the fees there can be totally different. SO you can't unify taker/maker under ETH, but you can unify them under ETH/BTC...

You see where this is going?

**Comment by kroitor** [comment]
> If you were to redesign the structure of the fee dictionary, how would you go about it?

Take a look at its current state, for example, here
https://github.com/ccxt/ccxt/blob/master/js/kraken.js#L58

We can take that structure as a basis for further edits and development, and it already fits most of our needs. So, we could just implement the same structure everywhere, where missing.

**Comment by frosty00** [comment]
To make the already overcomplicated tier based system even more complicated it seems kracken has no trading fees for the month of January - https://www.kraken.com/en-us/help/fees
and I'm sure they will change it frequently.

Even better - the API is sending the wrong the fees:
    'taker': [[0, 0.0026], [50000, 0.0024], [100000, 0.0022], [250000, 0.002], [500000, 0.0018], [1000000, 0.0016]

What does 'lot' and 'lot_multiplier' mean in this context?

I'm working on getting fees automatically generated since IMO they are too volatile to be hardcoded.

**Comment by kroitor** [comment]
> To make the already overcomplicated tier based system even more complicated it seems kracken has no trading fees for the month of January - https://www.kraken.com/en-us/help/fees
and I'm sure they will change it frequently.

Not really, they haven't changed their fees for a long time, and the January zeroing was their "excuse" for their previous downtimes throughout November and December... Most likely they will return to their previous fee schedule in February and "that's enough, folks" )

Anyway, their API currently reports proper actual trading fees.

> Even better - the API is sending the wrong the fees:

I don't see that, to me it looks like their current fee is set to 0 and it is returned as 0 from both their API and from ccxt:

```
mbp:python igorkroitor$ python
Python 2.7.13 (default, Jun  5 2017, 10:04:07) 
[GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.42)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from pprint import pprint
>>> import ccxt
>>> pprint(ccxt.kraken().load_markets()['ETH/BTC']['taker'])
0.0
```

↑ the fee is zero (actual).

You're probably still looking at hardcoded `exchange.fees`, but you shouldn't. Really ) Look at markets and currencies, as we will be propagating info from there.

↓ this is the entire actual structure of the 'ETH/BTC' market, for example:


```
{     limits: { amount: { min: 0.02, max: 100000000 },
                 price: { min: 0.00001, max: undefined },
                  cost: { min: 0, max: undefined }        },
   precision: { amount: 8, price: 5 },
   tierBased:    true,
  percentage:    true,
       taker:    0,
       maker:    0,
       tiers: { taker: [ [0, 0.0026],
                         [50000, 0.0024],
                         [100000, 0.0022],
                         [250000, 0.002],
                         [500000, 0.0018],
                         [1000000, 0.0016],
                         [2500000, 0.0014000000000000002],
                         [5000000, 0.0012],
                         [10000000, 0.001]                 ],
                maker: [ [0, 0.0016],
                         [50000, 0.0014000000000000002],
                         [100000, 0.0012],
                         [250000, 0.001],
                         [500000, 0.008],
                         [1000000, 0.006],
                         [2500000, 0.004],
                         [5000000, 0.002],
                         [10000000, 0]                   ]    },
          id:   "XETHXXBT",
      symbol:   "ETH/BTC",
        base:   "ETH",
       quote:   "BTC",
    darkpool:    false,
        info: {             altname:   "ETHXBT",
                        aclass_base:   "currency",
                               base:   "XETH",
                       aclass_quote:   "currency",
                              quote:   "XXBT",
                                lot:   "unit",
                      pair_decimals:    5,
                       lot_decimals:    8,
                     lot_multiplier:    1,
                       leverage_buy: [2, 3, 4, 5],
                      leverage_sell: [2, 3, 4, 5],
                               fees: [ [0, 0],
                                       [50000, 0],
                                       [100000, 0],
                                       [250000, 0],
                                       [500000, 0],
                                       [1000000, 0],
                                       [2500000, 0],
                                       [5000000, 0],
                                       [10000000, 0] ],
                         fees_maker: [ [0, 0],
                                       [50000, 0],
                                       [100000, 0],
                                       [250000, 0],
                                       [500000, 0],
                                       [1000000, 0],
                                       [2500000, 0],
                                       [5000000, 0],
                                       [10000000, 0] ],
                fee_volume_currency:   "ZUSD",
                        margin_call:    80,
                        margin_stop:    40              },
     altname:   "ETHXBT",
         lot:    0.02,
      active:    true                                            }
```

> What does 'lot' and 'lot_multiplier' mean in this context?

The amount of any order should be evenly divisible by lot size (order amount % lot size == 0).

**Comment by frosty00** [comment]
@kroitor 

There are a couple of issues I am facing at the moment. Firstly, exchange.set_markets loads in fees from the hardcoded exchange.fees, which is counter-intuitive since I am trying to populate exchange.fees from the .markets property.

        let values = Object.values (markets).map (market => deepExtend ({
            'limits': this.limits,
            'precision': this.precision,
        }, this.fees['trading'], #remove this line?
        market))  

Secondly, the fees are are not always found in the same place. I've had alright luck with withdrawal fees, they are usually in the currencies property, however many don't specify deposit fees at all - is it safe to assume these are 0? Others, like cex.io, keep their fees in a non standard location - 'privatePostGetMyfee' so maybe the method should be overwritten in the subclass?

**Comment by frosty00** [comment]
@kroitor didn't mean to close this. Think github did it automatically when my fork became level with ccxt/master on github. Perhaps I should open an issue to discuss how the exchange.fees should be loaded and formated?

**Comment by kroitor** [comment]
@frosty00 yeah, it was closed automatically, but don't worry, i'm still taking everything from this pull-request into consideration.

> Perhaps I should open an issue to discuss how the exchange.fees should be loaded and formated?

Yep, feel free to open an issue if feel the need, I would put the explanation and currently targeted formats there. Will be happy to help. Thank you! )

**Comment by kroitor** [comment]
Sorry, the answers to your previous questions:

> There are a couple of issues I am facing at the moment. Firstly, exchange.set_markets loads in fees from the hardcoded exchange.fees, which is counter-intuitive since I am trying to populate exchange.fees from the .markets property.

It does that in a specific order, so the market info overrides the default fees, if the proper fee info is placed inside a market.

> Secondly, the fees are are not always found in the same place. I've had alright luck with withdrawal fees, they are usually in the currencies property, however many don't specify deposit fees at all

Exchanges not only miss that info in their API, some of them don't even document it at all, so we sometimes have to deduce them with trial and error ) Welcome to our world! ) 

> is it safe to assume these are 0 -> collections.defaultdict(lambda: 0)? 

No. And this is the problem.

> Others, like cex.io, keep their fees in a non standard location - 'privatePostGetMyfee', so maybe the method should be overwritten in the subclass?

We have `fetchFees()` for that, but in cases where fees are available from `.markets` and/or `.currencies`, it should not make a network request, obviously, it should serve them either from default `.fees` or from populated `.markets` and `.currencies`. So, that method should only do a network request if the exchange has user-specific fees (see fetchFees in poloniex.js/py). Moreover, some exchanges send that info along with the balance or with other endpoints. So, it's not that trivial as it may seem at first ;)

**Pull request closed without merging**
