### PR TITLE
Add Integration for Delta Exchange

### PR DESCRIPTION
**Pull request by bbc4468**
Delta Exchange is a crypto derivatives exchange. 
https://www.delta.exchange

Testnet - https://testnet.delta.exchange/app
Mainnet - https://www.delta.exchange/app

- Added Integration for Delta Exchange
- Integration includes the following methods
1. fetchMarkets
2. fetchL2OrderBook
3. fetchTicker
4. fetchTrades
5. fetchOHLCV
6. fetchBalance
7. fetchOpenOrders
8. fetchClosedOrders
9. createOrder
10. cancelOrder

### CODE REVIEW

**Comment by bbc4468** [comment]
@kroitor Understand you must have a busy schedule. But some of our traders have been following up continuously on CCXT integration. 

Do you have any immediate comments on this PR so that i can start working on them. 

Thanks

**Comment by bbc4468** [comment]
@kroitor Bunch of our users have been after us for ccxt integration. Can you please expedite the review?

**Comment by kroitor** [comment]
@bbc4468 my apologies for the delay, too many parallel tasks... Hope for your understanding... I'll try and do my best to get it reviewed this week.

**Comment by kroitor** [comment]
@bbc4468 can you please remove the generated files from this PR? I mean, the files that are generated automatically:

- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

```
README.md
ccxt.d.ts
ccxt.js
package-lock.json
package.json
php/Exchange.php
python/ccxt/__init__.py
python/ccxt/async_support/__init__.py
wiki/Exchange-Markets-By-Country.md
wiki/Exchange-Markets.md
wiki/Manual.md
```

In other words, we need just the `js/delta.js`, the rest of them are generated upon Travis CI build.

**Comment by bbc4468** [comment]
@kroitor I have removed auto generated files. Just kept delta.js. Can you please review it now?

**Comment by bbc4468** [comment]
@kroitor Our users have been asking for this constantly. Please let me know if I can help in anyway to get this merged sooner.

**Comment by bbc4468** [comment]
@kroitor Another reminder.

**Comment by arbaaz** [comment]
@kroitor Gentle reminder.

**Comment by arbaaz** [comment]
@kroitor Our clients use CCXT for trading and they are not able to use our platform.

We have informed our clients that we have made the changes and we are waiting from CCXT maintainers to give feedback or merge.

Please look into this. It might take 15-20 mins of your time. It means a lot to us.

**Pull request closed without merging**
