### PR TITLE
Added jsDelivr CDN (along with unpkg) + fixed version number in CDN urls + refactored vss.js script

### PR DESCRIPTION
**Pull request by xpl**
CDN urls in our README.md now include the (current) version number:

```javascript
<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/ccxt@1.18.456/dist/ccxt.browser.js"></script>
```

vss.js had to be refactored, to allow more sane templating:

```javascript
vss ('./php/Exchange.php',                           "$version = '{version}'")
vss ('./php/Exchange.php',                           "VERSION = '{version}'")
vss ('./ccxt.js',                                    "const version = '{version}'")
vss ('./python/ccxt/__init__.py',                    "__version__ = '{version}'")
vss ('./python/ccxt/async_support/__init__.py',      "__version__ = '{version}'")
vss ('./python/ccxt/base/exchange.py',               "__version__ = '{version}'")
vss ('./python/ccxt/async_support/base/exchange.py', "__version__ = '{version}'")

vss ('./README.md',       "ccxt@{version}")
vss ('./wiki/Install.md', "ccxt@{version}")
```

Instead of that verbosity (that didn't allow handling of something like `ccxt@1.18.456` because of a hard-coded comma in that function):

```javascript
vss ('./php/Exchange.php',                           /\$version \= \'[^\']+\'/, "$version = '")
vss ('./php/Exchange.php',                           /VERSION \= \'[^\']+\'/, "VERSION = '")
vss ('./ccxt.js',                                    /const version \= \'[^\']+\'/, "const version = '")
vss ('./python/ccxt/__init__.py',                    /\_\_version\_\_ \= \'[^\']+\'/, "__version__ = '")
vss ('./python/ccxt/async_support/__init__.py',      /\_\_version\_\_ \= \'[^\']+\'/, "__version__ = '")
vss ('./python/ccxt/base/exchange.py',               /\_\_version\_\_ \= \'[^\']+\'/, "__version__ = '")
vss ('./python/ccxt/async_support/base/exchange.py', /\_\_version\_\_ \= \'[^\']+\'/, "__version__ = '")
```

### CODE REVIEW

**Comment by kroitor** [comment]
> CDN urls in our README.md now include the (current) version number:

But this doesn't really fix anything, right? I mean, what's the point of having it fixed statically in our docs, if the version isn't updated automatically on all end-user clients in all projects that use a non-versioned (most recent) unpkg url?

**Comment by xpl** [comment]
> But this doesn't really fix anything, right?

No sane app developer would want a _live-updated_ version of a library to be included into his website in production mode — because if a sudden update breaks anything, there will be no way to easily roll it back. Just imagine if you had your NPM dependencies updated automatically, that would be a maintenance nightmare.

> the version isn't updated automatically on all end-user web-clients in all projects that use a non-versioned (most recent) unpkg url?

That's not how the things are meant to be done in webdev. Surely there will be people who would prefer a live version for dev purposes or maybe because they simply don't care (in that case they might want to erase the version number), but we shouldn't default to that and promote that kind of approach, it just smells bad.

**Comment by xpl** [comment]
> You don't want them to go and change the version number in their software each time, do you? )

Yes, I want them to do exactly that, just as we run `npm update` each time we want to get our dependencies updated. Dependencies should _never_ be updated by themselves in _run-time_, that is plain crazy.

So if a developer wants to update CCXT bundle in their app/website — they copy a new CDN url with an updated version number and redeploy their app. We should never break their existing already deployed apps with commits to our master branch, as we do currently (unfortunately).

**Comment by kroitor** [comment]
> Dependencies should never be updated by themselves in run-time, that is plain crazy.

Users might not always agree with the above. Especially users of actively-updated project. Especially when it comes to not having a bug vs having a bug.

https://github.com/unpkg/unpkg.com/issues/186#issuecomment-481309194

> Here is my use case:
> - I use unpkg to serve a js library that is under heavy development
> - Users of this library want to always use the latest version of the library, in order to benefit from quick fixes. So ideally they would use the URL without version number.
> - But it's not possible: because it takes hours for the "URL without version number" to point to the latest published version, they need to point to the versioned URL and update their code each time the library changes.
```

Apparently 12 hours can make a difference, really...

**Comment by kroitor** [comment]
@xpl what if we rather add one more clarification sentence, something like: "If you want to always default to the most recent version, remove the version number from the CDN url" ? This way we will not encourage unsafe usage, but will at least give them (mostly newcoming users) an alternative option... How about that?

**Comment by xpl** [comment]
> Users might not always agree with the above

In that case they might erase the version number to get the live-updated version — but we should not default to that, as we do currently now. You can add a notice to the README.md about that if that bothers you.

Initially when I added unpkg to our docs, I picked the live-updated URL just because we didn't have the means to embed a version number in our README, but that wasn't because it is a bright idea or something.

**Comment by xpl** [comment]
> what if we rather add one more clarification sentence, something like: "If you want to always default to the most recent version, remove the version number from the CDN url" ?

@kroitor Just saw that your message. I can add it no problem.

**Comment by kroitor** [comment]
@xpl no worries, added it.

**Comment by xpl** [comment]
The version numbers in README are currently outdated, but that should resolve upon a next CI build...

**Pull request merged**
