### PR TITLE
quoinex: handleErrors revamped, ready for extended tests

### PR DESCRIPTION
**Pull request by mkutny**

### CODE REVIEW

**Comment by mkutny** [comment]
Now it failed for a good reason.

**Comment by kroitor** [comment]
@mkutny yep, PHP is slightly more critical to consistency of inherited signatures...

**Comment by mkutny** [comment]
Well... `handleErrors` now relies on json provided by the base class.

So if we want to take advantage of json being parsed once PHP/Python base classes need to implement something similar to #1551.

Alternatively, I can declare argument as `json = undefined` (I guess PHP will be ok with that) and parse it conditionally inside `handleErrors`. So it will be one-time parse in JS and two-times parse in PHP/Python. And someday in the future, we'll remove that check (once PHP/Python are ready).

Or I can hold on with that json, parse it unconditionally (as usual) and submit just extended testing (which finally works).

**Comment by kroitor** [comment]
Alright, give me some time to review them, plz, and I'll get back to you this. Should be no problem to add one more param. However, I'm thinking, if projected further, maybe, that long list of arguments kinda tells us to wrap them all up into a single `params = {}` argument, that could be extended later and would still remain backward-compatible further on.

**Comment by mkutny** [comment]
I'd prefer object pattern too.

With regard to this particular method, it seems that it needs just three params: `Request`, `Response`, and json.

What I think I'll do now is make json parse inside `handleErrors` conditional.
This will allow us to finally have error handling a part of regression test suite so I'll feel much safer touching `handleErrors`.

**Comment by mkutny** [comment]
Ok, it's fine now.

**Pull request merged**
