### PR TITLE
New Exchange: Coinzip 

### PR DESCRIPTION
**Pull request by iammac360**
Hi, we recently launch Coinzip(https://www.coinzip.co/) and we want to integrate with ccxt. Hope you can accept our PR. Thanks

### CODE REVIEW

**Comment by kroitor** [comment]
Hi!

First of, thanks for the PR! Appreciate your involvement!

There's a few issues with it, however, namely, on the language portability... Have you read this:

- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

... and, especially, this:

- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#multilanguage-support
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#derived-exchange-classes

? )

**Comment by kroitor** [comment]
You might also want to read this to run the same set of tests locally: https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-build--run-tests-on-your-local-machine

**Comment by iammac360** [comment]
> Hi!
> 
> First of, thanks for the PR! Appreciate your involvement!
> 
> There's a few issues with it, however, namely, on the language portability... Have you read this:
> 
> * https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue
> 
> ... and, especially, this:
> 
> * https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#multilanguage-support
> * https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#derived-exchange-classes
> 
> ? )
> 
> We need to make sure that it passes the tests and syntactic checks. After that we will be able to verify that all methods are implemented properly, but tests first.
> 
> * https://travis-ci.org/ccxt/ccxt/builds/503046596?utm_source=github_status&utm_medium=notification
> * https://ci.appveyor.com/project/ccxt/ccxt/builds/22896013

Thanks for the feedback. I guess I have to refactor all the `const` declation to `let`.  I mislook the coding standards stated here https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#derived-exchange-classes and coded on my own way which is derived from a functional, immutable style which is why I always use `const`.
I also forgot to run the linters and only run the tests. 

Though I've run this script on my local machine:
```
node run-tests.js --js --php --python coinzip
```
Everythings green on my last run, but I guess I need to remove the `--language` option also or did I just missed something?? I'll just rerun this again once I'm home.

I'll update this PR once I've complied to all the standards and everythings green.

**Comment by kroitor** [comment]
> Thanks for the feedback. I guess I have to refactor all the const declation to let.

This isn't necessary, we actually do support `const` already ) So, yeah, we prefer `const` as well. I will edit that particular rule in the guidelines. But the rest of them still apply.

**Comment by kroitor** [comment]
Ok, I've updated the guidelines – `const` and `let` are ok (if used properly), but not `var` ;)

**Comment by iammac360** [comment]
> > Thanks for the feedback. I guess I have to refactor all the const declation to let.
> 
> This isn't necessary, we actually do support `const` already ) So, yeah, we prefer `const` as well. I will edit that particular rule in the guidelines. But the rest of them still apply.

Okay good to hear that. Thanks again. I'll review the CI errors also to see where that Issue is.

**Comment by iammac360** [comment]
Hi @kroitor, I've updated my fork and fixed the failing test. Can you please verify it. Thank you.

**Comment by kroitor** [comment]
Hi Mark! Thank you for the effort and for your time on this! I will review the work that you've done asap and will post my comments on it. In the meantime, if you can help clean up this PR a bit more – that would really speed up things, namely, we need to restore the generated files to their original versions – no need to commit those, as most of them will be overwritten upon building on travis anyway.

From this list:

```JavaScript 
.editorconfig   // ←-------- we'd take this file
README.md
ccxt.d.ts
ccxt.js
dist/ccxt.browser.js
js/coinzip.js  // ←------------- and we need this file
php/Exchange.php
php/coinzip.php
python/ccxt/__init__.py
python/ccxt/async_support/__init__.py
python/ccxt/async_support/coinzip.py
python/ccxt/coinzip.py
wiki/Exchange-Markets-By-Country.md
wiki/Exchange-Markets.md
wiki/Manual.md
```

All the other files are generated, so you can revert them to the master version with this command in your local repo:

```
git checkout master -- README.md ccxt.d.ts ccxt.js dist/ccxt.browser.js php/Exchange.php php/coinzip.php python/ccxt/__init__.py python/ccxt/async_support/__init__.py python/ccxt/async_support/coinzip.py python/ccxt/coinzip.py wiki/Exchange-Markets-By-Country.md wiki/Exchange-Markets.md wiki/Manual.md
git commit -am 'reverted generated files to master'
git push
```

Thx again! Will get back to you on this soon!

**Comment by iammac360** [comment]
HI @kroitor, I've already updated my PR. Can you please check it again. Thanks!

**Comment by iammac360** [comment]
Hi @kroitor any feedback?

**Comment by kroitor** [comment]
@iammac360 pardon for the long wait, i'll do my best to get to it asap, didn't have the chance to do it yet, hope for your understanding.

**Comment by ttodua** [comment]
dead exchange

**Pull request closed without merging**
