### PR TITLE
Gdax and Kucoin changes

### PR DESCRIPTION
**Pull request by wannesdemaeght**

### CODE REVIEW

**Comment by wannesdemaeght** [comment]
#1416

**Comment by kroitor** [comment]
They now return different fee formats and the L303 is the correct one. It would be a little easier for me to merge if they were separate pull-requests (different branches), but I'm going to merge it soon, anyway, as I said earlier.

- https://github.com/ccxt/ccxt/pull/1431/files#diff-03145d38fecb5a74e76f74154826789dL303
- https://github.com/ccxt/ccxt/pull/1431/files#diff-9453f5a8dee427abd6a1b4a0aed6a819R345

**Comment by wannesdemaeght** [comment]
Right, didn't notice that, sorry.

One more thing:
In kucoin.js, we need to set has.fetchOrder to true (forgot about that one)

**Comment by jjhesk** [comment]
@kroitor can merge this one yet?

**Comment by kroitor** [comment]
@jjhesk in progress, will merge soon.

**Comment by kchaban0v** [comment]
When i use this method for kucoin (with stating id, pair and type) - i get the following anytime i try.

[Exchange Error] kucoin {"success":true,"code":"OK","msg":"Operation succeeded.","timestamp":1518793719920,"data":null} 

Is it some Kucoin issue?

**Comment by kchaban0v** [comment]
The simplest code gives this error. 

`<?php

include 'ccxt.php';

date_default_timezone_set ('UTC');
$exchange = new \ccxt\kucoin (array (
    'apiKey' => 'myKey',
    'secret' => 'mySecret',
));

try {
	print_r($exchange->fetchOrder('5a7efcebeecbd52ab20c0921','DAT/BTC',array('type'=> "SELL"))); 

} catch (\ccxt\NetworkError $e) {
    echo '[Network Error] ' . $e->getMessage () . "\n";
} catch (\ccxt\ExchangeError $e) {
    echo '[Exchange Error] ' . $e->getMessage () . "\n";
} catch (Exception $e) {
    echo '[Error] ' . $e->getMessage () . "\n";
}

?>`

Other methods work without any problem. And if I don't state the id or (the type or the pair) - it tells me correct error message that the specific parameter is missing.

**Comment by wannesdemaeght** [comment]
Kucoin stopped giving fetchOrder info for closed orders.

**Comment by kchaban0v** [comment]
There were the problem was. Got it. Thank you, @wannesdemaeght

**Pull request merged**
