### PR TITLE
Add bitrue exchange API implementation (python)

### PR DESCRIPTION
**Pull request by dust**
Add bitrue exchange API implementation (python)

### CODE REVIEW

**Comment by kroitor** [comment]
@dust hi! Plz read this:

- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#multilanguage-support
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#new-exchange-integrations

**Comment by kroitor** [comment]
@dust plz read the contributing guidelines i've posted above.

**Comment by binares** [comment]
@dust Here is the public part transpiled to javascript and tested, you can do rest. https://github.com/binares/ccxt/tree/bitrue

**Comment by dust** [comment]
@binares ok.

**Review by jonhpham — APPROVED** [review]

**Pull request merged**
