### PR TITLE
Exchange Tokens.net

### PR DESCRIPTION
**Pull request by dtokens**
Official Tokens.net commit

### CODE REVIEW

**Comment by dtokens** [comment]
Hello, any updates regarding this issue?

**Comment by kroitor** [comment]
@dtokens sorry for a long wait – we are going to review and merge it asap: https://github.com/ccxt/ccxt/issues/6332

**Comment by domenkoneski** [comment]
Hi, any news for Tokens.net integration?

**Comment by dtokens** [comment]
Hello, any news?

**Comment by DavidIvanusa** [comment]
Exchange is closing, you can close pull request.

**Comment by kroitor** [comment]
https://twitter.com/TokensNet/status/1356572079718600704

**Pull request closed without merging**
