### PR TITLE
kucoin: request: removed (obsolete)

### PR DESCRIPTION
**Pull request by mkutny**

### CODE REVIEW

**Comment by kroitor** [comment]
Oops, didn't expect `json = undefined`, it's still not available in Python/PHP yet...

**Comment by mkutny** [comment]
I've done it before already. Will check.

**Comment by kroitor** [comment]
> I've done it before already. Will check.

Thx, sorry for taking so long with a proper python/php fix, will do that today or tomorrow, hopefully.

**Comment by mkutny** [comment]
That's fine, approach with `json = undefined` works.

It appeared that `json` is a reserved keyword for transpiler. Will use another one.

**Pull request merged**
