### PR TITLE
save raw content from response

### PR DESCRIPTION
**Pull request by galvanizze**

### CODE REVIEW

**Comment by kroitor** [comment]
Hey! First of, thx for the suggestion and for the PR! We really appreciate your help! One thing, however: those instance properties are deprecated and we will most likely remove them soon, because they break asynchronous execution (more about it here: https://github.com/ccxt/ccxt/issues/5517). For that reason we think adding a new property that would be deprecated soon is probably not what we'd want to do, instead, i would rather return the response as http_response in case if its not JSON. And we will need to make sure that it works in all supported languages, not just Python. If you can rework the PR a bit to account for these details, that would be awesome! If not, no worries, we will do this as soon as we get to it (hopefully soon).

**Comment by galvanizze** [comment]
Hi, we use ccxt a lot, I'm glad to help.
Thanks for clarification, I didn't know that those properties are deprecated. You suggest to just return http_response in case if it's not JSON - but now it works like this.
```
if json_response is not None:
    return json_response
return http_response
```
In my case from #5302 I want to get non-text bytes content (`response.content`), current implementation returns text (`response.text`). I suggest to decide which response type (json, http, raw) will be returned by `response.headers['Content-Type']` - it should works.
What do you think? Or do you have better solution?

**Comment by kroitor** [comment]
> I suggest to decide which response type (json, http, raw) will be returned by response.headers['Content-Type'] - it should works.
> What do you think? Or do you have better solution?

Yes, I think that should work. Hope to get to it asap.

**Comment by galvanizze** [comment]
Hi, I've added solution for Python. If I have some time I'll try to implement it for other languages.

**Pull request merged**
