### PR TITLE
Margin mode types

### PR DESCRIPTION
**Pull request by samgermain**
All setMarginMode methods now accept `CROSS` or `ISOLATED`. The error messages say to pass the type in capital letters because all caps is used for order types and symbols and I wanted to make it consistent. No user code will be broken with these changes.

------------------------------------------------------------------

```
bybit setMarginMode cross ETH/USDT '{"leverage": "10"}'
2022-02-02T07:32:17.204Z
Node.js: v14.17.0
CCXT v1.71.84
bybit.setMarginMode (cross, ETH/USDT, [object Object])
350 ms
{
  ret_code: '0',
  ret_msg: 'OK',
  ext_code: '',
  ext_info: '',
  result: null,
  time_now: '1643787138.038292',
  rate_limit_status: '72',
  rate_limit_reset_ms: '1643787138034',
  rate_limit: '75'
}
```
```
% okex setMarginMode cross ETH/USDT:USDT '{"lever": "10"}'   
2022-02-02T07:32:39.703Z
Node.js: v14.17.0
CCXT v1.71.84
okex.setMarginMode (cross, ETH/USDT:USDT, [object Object])
291 ms
{
  code: '0',
  data: [
    {
      instId: 'ETH-USDT-SWAP',
      lever: '10',
      mgnMode: 'cross',
      posSide: ''
    }
  ],
  msg: ''
}
```
```
% binanceusdm setMarginMode cross BTC/USDT               
2022-02-02T07:32:57.205Z
Node.js: v14.17.0
CCXT v1.71.84
binanceusdm.setMarginMode (cross, BTC/USDT)
349 ms
{ code: 200, msg: 'success' }
```

```
% okex setLeverage 10 ETH/USDT:USDT '{"mgnMode": "cross"}'           
2022-02-02T07:37:11.697Z
Node.js: v14.17.0
CCXT v1.71.84
okex.setLeverage (10, ETH/USDT:USDT, [object Object])
289 ms
{
  code: '0',
  data: [
    {
      instId: 'ETH-USDT-SWAP',
      lever: '10',
      mgnMode: 'cross',
      posSide: ''
    }
  ],
  msg: ''
}
```
```
% okex fetchLeverage ETH/USDT:USDT '{"mgnMode": "cross"}'            
2022-02-02T07:37:22.856Z
Node.js: v14.17.0
CCXT v1.71.84
okex.fetchLeverage (ETH/USDT:USDT, [object Object])
301 ms
{
  code: '0',
  data: [
    {
      instId: 'ETH-USDT-SWAP',
      lever: '10',
      mgnMode: 'cross',
      posSide: 'long'
    },
    {
      instId: 'ETH-USDT-SWAP',
      lever: '10',
      mgnMode: 'cross',
      posSide: 'short'
    }
  ],
  msg: ''
}
```

### CODE REVIEW

**Comment by kroitor** [comment]
> All setMarginMode methods now accept `CROSS` or `ISOLATED`. The error messages say to pass the type in capital letters because all caps is used for order types and symbols and I wanted to make it consistent. No user code will be broken with these changes.

For the order types we use lowercase `limit`, `market`, etc. I would use `cross` and `isolated` for margin types in lowercase. Do you mind changing that to lowercase? In general, we tend to avoid uppercasing, and mostly use it for symbols. The other values are all lowercase, including contract types, different fields in orders, trades, etc.

**Comment by samgermain** [comment]
> > All setMarginMode methods now accept `CROSS` or `ISOLATED`. The error messages say to pass the type in capital letters because all caps is used for order types and symbols and I wanted to make it consistent. No user code will be broken with these changes.
> 
> For the order types we use lowercase `limit`, `market`, etc. I would use `cross` and `isolated` for margin types in lowercase. Do you mind changing that to lowercase? In general, we tend to avoid uppercasing, and mostly use it for symbols. The other values are all lowercase, including contract types, different fields in orders, trades, etc.
> 
> Alternatively, we can support both the uppercase and the lowercase identifiers (`cross`+`isolated` and `CROSS`+`ISOLATED`), defaulting to a single unified letter case (i'd still prefer lowercase as the default). Let me know your thoughts.

Sure

**Comment by kroitor** [comment]
@samgermain one more thing – before we actually merge it, we should investigate which value is used by the majority of the exchange's APIs – either `cross` or `crossed` (i mean in their docs, not in our code). If most of them use `crossed` – the users would expect the same in CCXT and we should stick to `crossed/CROSSED`. Otherwise, if most of them use the term `cross` for that, then we should conform. Can you make a complete list of exchanges that have this margin type distinction and share that?

**Comment by samgermain** [comment]
> 

Ascendex and binance is the only place I'm seeing `crossed`

**Pull request merged**
