### PR TITLE
hitbtc fetchOrderTrades, okcoinusd fees

### PR DESCRIPTION
**Pull request by beniloew**

### CODE REVIEW

**Comment by kroitor** [comment]
Awesome! Thanks so much! Merging it shortly! Happy holidays! )

**Comment by beniloew** [comment]
I see now that more exchanges have 2 IDs per order - the exchanges ID and the user assigned ID.
Isnt it worth to add this to the unified API?

**Comment by kroitor** [comment]
> I see now that more exchanges have 2 IDs per order - the exchanges ID and the user assigned ID.
Isnt it worth to add this to the unified API?

We will consider this, however, this might require a little more significant effort than it seems at first. But, yes, we are taking this into consideration when we design the future of the library. Currently this is already supported in the form of extra params added to each method, but not in a unified fashion of course. We will get to it sooner or later ;)

**Comment by beniloew** [comment]
Great!
Not sure why travis failed - counting on you on this one ;)

**Comment by kroitor** [comment]
@beniloew it's because of a missed comma and a multi-line comment, the transpiler is very sensitive to that, and we have to be careful with each symbol literally. But, no worries, I've merged it ) Thank you once again for your help!

**Pull request merged**
