### PR TITLE
bittrex: updated exceptions handling

### PR DESCRIPTION
**Pull request by egorFiNE**
* added InvalidOrder exception on plain INVALID_ORDER response
* throw OrderNotFound in cancelOrder for the ambiguous bittrex responses on invalid or closed order ids.

### CODE REVIEW

**Comment by frosty00** [comment]
Should we be using `this.last_json_response` or is it depreciated?

**Comment by kroitor** [comment]
> Should we be using this.last_json_response or is it depreciated?

I think we should deprecate it, globals don't really work well with async/concurrent calls. Will need to switch to using method arguments instead of globals. Good catch, btw.

**Comment by frosty00** [comment]
> Will also have to wrap the errors class in a portable way...

Yeah this is not going to be easy. We will have to change every instance of throw to a`this.raise_error`, but I agree it is something we need to do <:>

**Comment by kroitor** [comment]
@frosty00

> Yeah this is not going to be easy.

This should not be too hard either, I hope ) 

I mean, we will need to add the following attributes to the BaseError:

```JavaScript
{
    message, // this is probably already built-in under `message` or `msg` in all languages
    call, // the method of CCXT which triggered the exception
    arguments, // the arguments of that method
    file, // if needed
    line, // if needed
    endpoint, // the exchange endpoint
    method, // HTTP GET, POST, PUT or DELETE
    requestParams, // ...
    responseBody, // ...
    responseJson, // ?
}
```

Let me know your thoughts on the above )

**Comment by frosty00** [comment]
I agree with your implementation except for 

```
    call,     // the method of CCXT which triggered the exception
    args,     // the arguments of that method
    file,     // name, if needed
    line,     // number, if needed

```

since these will be hard to populate and any decent debugger should do this for us.

When I have time I will try make a regex to convert `throw Error` to `this.raiseError` (once js and php have the method added to their base classes)

**Comment by egorFiNE** [comment]
@kroitor Should I rewrite this to read `response` instead of `last_json_response` ?

**Comment by egorFiNE** [comment]
(merged with current master)

**Comment by egorFiNE** [comment]
ping? :)

**Comment by kroitor** [comment]
> ping? :)

I'm going to merge this shortly, however, I think I'll move this edit to handleErrors (will do a special-case url-string-matching for the cancelOrder), that is, to avoid using the global instance-wide `.last_json_response` – it kinda breaks the async pattern. It's not your fault at all, as you've copied this from a different place where it was already implemented this way. But we should consider this a bad design that was there even before you approached it. And we are going to redesign this a little. In the end, it is likely that handleErrors will return proper response in case of "no error", this would work without the need for globals and would also resolve our double-json-parsing-problem quite elegantly.

**Comment by egorFiNE** [comment]
Excellent, thanks!

**Pull request merged**
