### PR TITLE
New exchange: HollaEx

### PR DESCRIPTION
**Pull request by brandonkimmmm**

### CODE REVIEW

**Comment by kroitor** [comment]
Hi! First of all, thx for your effort! Appreciate your help very much!

One quick question: can you please remove the php and py files from this PR? We need just one file, `hollaex.js`, other files are generated: https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code.

**Comment by brandonkimmmm** [comment]
@kroitor Thank you for the reply. Should I remove the entire `/php`, `/python`, `/build`, `/doc` directories?

**Comment by kroitor** [comment]
> @kroitor Thank you for the reply. Should I remove the entire /php, /python, /build, /doc directories?

Yep ) I mean, do not delete them, but remove them from this PR – just checkout the originals from the master branch )

**Comment by frosty00** [comment]
```
git checkout master
git pull
git checkout -b new_branch
git checkout old_branch js/hollaex.js
```

and make a new pr

**Comment by brandonkimmmm** [comment]
@frosty00 should i close this one?

**Comment by frosty00** [comment]
@brandonkimmmm yes please!

**Pull request closed without merging**
