### PR TITLE
gate: fix parse_order for spot orders

### PR DESCRIPTION
**Pull request by xmatthias**
Current order parsing on gate is broken.
```
{
    "id": "276266839423",
    "clientOrderId": "apiv4",
    "timestamp": 1675936898746,
    "datetime": "2023-02-09T10:01:38.746Z",
    "lastTradeTimestamp": 1675936898746,
    "status": "closed",
    "symbol": "BTC/USDT",
    "type": "limit",
    "timeInForce": "GTC",
    "postOnly": False,
    "reduceOnly": None,
    "side": "buy",
    "price": 22727.4,
    "stopPrice": None,
    "triggerPrice": None,
    "average": 20.45466,   <-- this is supposed to be avg_deal_price - not cost.
    "amount": 0.0009,
    "cost": 20.45466,
    "filled": 0.0009,
    "remaining": 0.0,
    "fee": {
        "currency": "BTC",
        "cost": 1.8e-06
    },
    "fees": [
        {
            "currency": "BTC",
            "cost": 1.8e-06
        }
    ],
    "trades": [],
    "info": {
        "id": "276266839423",
        "text": "apiv4",
        "create_time": "1675936898",
        "update_time": "1675936898",
        "create_time_ms": "1675936898746",
        "update_time_ms": "1675936898746",
        "status": "closed",
        "currency_pair": "BTC_USDT",
        "type": "limit",
        "account": "spot",
        "side": "buy",
        "amount": "0.0009",
        "price": "22727.4",
        "time_in_force": "gtc",
        "iceberg": "0",
        "left": "0",
        "fill_price": "20.45466",
        "filled_total": "20.45466",
        "avg_deal_price": "22727.4",
        "fee": "0.0000018",
        "fee_currency": "BTC",
        "point_fee": "0",
        "gt_fee": "0",
        "gt_maker_fee": "0",
        "gt_taker_fee": "0.0015",
        "gt_discount": True,
        "rebated_fee": "0",
        "rebated_fee_currency": "USDT"
    }
}

```

New format:
```
{"id": "276266839423",
 "clientOrderId": "apiv4",
 "timestamp": 1675936898746,
 "datetime": "2023-02-09T10:01:38.746Z",
 "lastTradeTimestamp": 1675936898746,
 "status": "closed",
 "symbol": "BTC/USDT",
 "type": "limit",
 "timeInForce": "GTC",
 "postOnly": False,
 "reduceOnly": None,
 "side": "buy",
 "price": 22727.4,
 "stopPrice": None,
 "triggerPrice": None,
 "average": 22727.4,
 "amount": 0.0009,
 "cost": 20.45466,
 "filled": 0.0009,
 "remaining": 0.0,
 "fee": {"currency": "BTC", "cost": 1.8e-06},
 "fees": [{"currency": "BTC", "cost": 1.8e-06}],
 "trades": [],
 "info": {"id": "276266839423",
  "text": "apiv4",
  "create_time": "1675936898",
  "update_time": "1675936898",
  "create_time_ms": "1675936898746",
  "update_time_ms": "1675936898746",
  "status": "closed",
  "currency_pair": "BTC_USDT",
  "type": "limit",
  "account": "spot",
  "side": "buy",
  "amount": "0.0009",
  "price": "22727.4",
  "time_in_force": "gtc",
  "iceberg": "0",
  "left": "0",
  "fill_price": "20.45466",
  "filled_total": "20.45466",
  "avg_deal_price": "22727.4",
  "fee": "0.0000018",
  "fee_currency": "BTC",
  "point_fee": "0",
  "gt_fee": "0",
  "gt_maker_fee": "0",
  "gt_taker_fee": "0.0015",
  "gt_discount": True,
  "rebated_fee": "0",
  "rebated_fee_currency": "USDT"}}
```

I also performed a market sell - just to do a "regression test" of some sorts ...

```
{'id': '276402737296',
 'clientOrderId': '3',
 'timestamp': 1675963721000,
 'datetime': '2023-02-09T17:28:41.000Z',
 'lastTradeTimestamp': 1675963721000,
 'status': 'closed',
 'symbol': 'SOL/USDT',
 'type': 'market',
 'timeInForce': 'FOK',
 'postOnly': False,
 'reduceOnly': None,
 'side': 'sell',
 'price': 22.52,
 'stopPrice': None,
 'triggerPrice': None,
 'average': 22.52,
 'amount': 0.4529,
 'cost': 10.199308,
 'filled': 0.4529,
 'remaining': 0.0,
 'fee': None,
 'fees': [],
 'trades': [],
 'info': {'id': '276402737296',
  'text': '3',
  'create_time': '1675963721',
  'update_time': '1675963721',
  'create_time_ms': '1675963721000',
  'update_time_ms': '1675963721000',
  'status': 'closed',
  'currency_pair': 'SOL_USDT',
  'type': 'market',
  'account': 'spot',
  'side': 'sell',
  'amount': '0.4529',
  'price': '0',
  'time_in_force': 'fok',
  'iceberg': '0',
  'left': '0.0000',
  'fill_price': '10.199308',
  'filled_total': '10.199308',
  'avg_deal_price': '22.52',
  'fee': '0',
  'fee_currency': 'USDT',
  'point_fee': '0.020398616',
  'gt_fee': '0',
  'gt_maker_fee': '0',
  'gt_taker_fee': '0',
  'gt_discount': False,
  'rebated_fee': '0',
  'rebated_fee_currency': 'SOL'}}
```

corresponding on exchange:
image

### CODE REVIEW

**Comment by carlosmiei** [comment]
[🤖 TestsManager 🤖  Id: 63e542f0c391f053efe0a9e0]
 ```

 Keys not found for gate, skipping tests!
```

**Comment by samgermain** [comment]
> [🤖 TestsManager 🤖 Id: 63e542f0c391f053efe0a9e0]
> 
> ```
> 
> Keys not found for gate, skipping tests!
> ```

You posted this on my tokocrypto PR as well and I didn't know what you were trying to say. I think the problem lies with you or Travis not having api keys for that exchange.

**Comment by carlosmiei** [comment]
Hello @xmatthias, thanks will review and merge soon!

**Comment by carlosmiei** [comment]
LGTM ✅ 

```
 p gate createOrder "LTC/USDT" market buy 5 1
Python v3.10.9
CCXT v2.7.69
gate.createOrder(LTC/USDT,market,buy,5,1)
{'amount': 0.054353734101532776,
 'average': 91.99,
 'clientOrderId': 'apiv4',
 'cost': 5.0,
 'datetime': '2023-02-10T11:30:07.311Z',
 'fee': {'cost': 0.0001087074682, 'currency': 'LTC'},
 'fees': [{'cost': 0.0001087074682, 'currency': 'LTC'}],
 'filled': 0.0543537341,
 'id': '276762839244',
 'info': {'account': 'spot',
          'amount': '5',
          'avg_deal_price': '91.99',
          'create_time': '1676028607',
          'create_time_ms': '1676028607311',
          'currency_pair': 'LTC_USDT',
          'fee': '0.0001087074682',
          'fee_currency': 'LTC',
          'fill_price': '4.999999999859',
          'filled_total': '4.999999999859',
          'gt_discount': False,
          'gt_fee': '0',
          'gt_maker_fee': '0',
          'gt_taker_fee': '0',
          'iceberg': '0',
          'id': '276762839244',
          'left': '0.000000000141',
          'point_fee': '0',
          'price': '0',
          'rebated_fee': '0',
          'rebated_fee_currency': 'USDT',
          'side': 'buy',
          'status': 'cancelled',
          'text': 'apiv4',
          'time_in_force': 'ioc',
          'type': 'market',
          'update_time': '1676028607',
          'update_time_ms': '1676028607311'},
 'lastTradeTimestamp': 1676028607311,
 'postOnly': False,
 'price': 91.99,
 'reduceOnly': None,
 'remaining': 1.532775e-12,
 'side': 'buy',
 'status': 'canceled',
 'stopPrice': None,
 'symbol': 'LTC/USDT',
 'timeInForce': 'IOC',
 'timestamp': 1676028607311,
 'trades': [],
 'triggerPrice': None,
 'type': 'market'}
```

**Review by carlosmiei — APPROVED** [review]

**Pull request merged**
