### PR TITLE
fix(tests-currencies) - skip flag for FIAT deposit & withdraw for exchange (QUICK)

### PR DESCRIPTION
**Pull request by ttodua**
added special skip flag for those exchanges that does not have networks & widthdrawal|deposit flags for fiats (kucoin is one of them, so I've added that skip-flag for kucoin)

p.s. there were two exceptional buggy coins returning from kucoin v3 endpoint, and hardcoded them temporarily.

### CODE REVIEW

**Comment by ttodua** [comment]
@carlosmiei this PR is ready

**Comment by ttodua** [comment]
ah sorry, not yet

**Comment by ttodua** [comment]
@carlosmiei PR ready.

**Comment by ttodua** [comment]
@carlosmiei

**Comment by carlosmiei** [comment]
LGTM

**Review by carlosmiei — APPROVED** [review]

**Pull request merged**
