### PR TITLE
Remove old raise_error in preparation for new raise_error invoked in handle_errors

### PR DESCRIPTION
**Pull request by frosty00**
the old code was not present in javascript and was not unified. the new raise_error will add properties from the arguments of `handle_errors` to the errors so that they can be read by the user.

i also think the old `raise_error` was useless and made the code harder to read.

### CODE REVIEW

**Comment by kroitor** [comment]
Have you stress-tested it?

`node run-tests --js`, `node run-tests --python`, php?

**Comment by frosty00** [comment]
@kroitor yep i am passing those tests (although i wouldn't call them stress tests, more like check i didn't break the lib tests)

**Comment by frosty00** [comment]
If you merge this by tomorrow morning i should be able to add the errors handling like we discussed previously and begin editing handleErrors in derived classes (will do 5 exchanges at a time as before)

**Comment by frosty00** [comment]
We may have to pass the error type as a string since in php you cannot pass classes to functions. However seems like this is handled by the transpiler already, for example in '.exceptions'. So maybe it will work by passing pointers too.

**Comment by frosty00** [comment]
This is my test output:

https://i.imgur.com/tg09GHc.png

**Comment by kroitor** [comment]
> We may have to pass the error type as a string since in php you cannot pass classes to functions. 

We already had that in the transpiler+here https://github.com/ccxt/ccxt/pull/5399/files#diff-d087d122b9d18390abb24d8b2cb6160fL1074. Those two lines would account for that specific PHP behaviour, because the transpiler would transpile all mentions of the exception subclasses in PHP – to strings, if necessary. We will have to keep that logic, otherwise merging this PR would break a few exchanges in PHP. I've added that workaround not so long ago, because `node run-tests --php` did not work. Now it does. However it's not launched on Travis, so the js and py tests are green... Need to test more with PHP.

**Comment by kroitor** [comment]
I've added it here within your previous PR: https://github.com/ccxt/ccxt/pull/5360

https://github.com/ccxt/ccxt/commit/b44f888626369570ee5e6454a15648d06d927bd9#diff-d087d122b9d18390abb24d8b2cb6160f

**Pull request merged**
