### PR TITLE
Printed time in verbose

### PR DESCRIPTION
**Pull request by SmartManoj**

### CODE REVIEW

**Comment by kroitor** [comment]
We use this.iso8601 () and this.milliseconds () instead, cause we already have the functions for working with datetimes:

- https://docs.ccxt.com/en/latest/manual.html#pagination

We also have to add that to the other languages:

- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#multilanguage-support

The verbose response already contains the timestamp within HTTP headers.

**Comment by SmartManoj** [comment]
Updated code in other languages.

**Comment by SmartManoj** [comment]
> Yes, but not readable. I am parsing that now

For future users,
```
file = open(path).read().splitlines()
import re
request_re = r"'KC-API-TIMESTAMP': '(\d+)'"
response_re = r'"time":(\d+),'
from datetime import *
for line in file:
    if line:
        request = re.search(request_re, line)
        request = datetime.utcfromtimestamp(int(request[1]) / 1000) if request else ''
        response = re.search(response_re, line)
        response = datetime.utcfromtimestamp(int(response[1]) / 1000) if response else ''
        print(request, response, line)
        print('-' * 50)
from datetime import *
a = datetime.now().isoformat()
print(a)
```

**Comment by SmartManoj** [comment]
`fetch Response: kucoin POST http://localhost:8080/kucoin/api/v1/orders 200 ResponseHeaders: {'Server': 'cloudflare', 'Date': 'Fri, 08 Apr 2022 10:59:59 GMT', 'Content-Type': 'application/json', 'Content-Length': '93', 'Connection': 'keep-alive', 'Strict-Transport-Security': 'max-age=9800; includeSubDomains; preload', 'Cf-Cache-Status': 'DYNAMIC', 'Expect-Ct': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"', 'Cf-Ray': '6f8a7f2e7bd41f99-NRT', 'Content-Encoding': 'gzip', 'Set-Cookie': ''} ResponseBody: {"code":"400600","msg":"validation.createOrder.symbolNotAvailable"}`

not contains millisecond

**Pull request closed without merging**
