### PR TITLE
Adds Exchange.setSandboxMode

### PR DESCRIPTION
**Pull request by clarkmoody**
As an alternative to #369, this adds `setSandboxMode` to the base exchange class. The argument is the desired sandbox mode, and the method throws if no test URLs are available.

To prepare an exchange for sandbox mode, add URLs to `exchange.urls.test`.

### CODE REVIEW

**Comment by kroitor** [comment]
The difficulty with this approach is that many exchanges have specific endpoints for order testing, but don't have a testnet (the orders are tested on their live APIs). So, in general, just switching the URLs may not work – additional params or specific endpoints may be required. For example, Binance – we had to add support for test orders separately... We should consider unifying these differences in nearest future.

**Comment by clarkmoody** [comment]
Perhaps this method could be expanded in the future? For now, exchanges that have a full Sandbox API will be supported, and edge-case exchanges could override the `setSandboxMode` method locally?

**Comment by kroitor** [comment]
@clarkmoody yep, i think you're right. However, because base class files are not transpiled, we will need to also implement the same method in `exchange.py` and `Exchange.php` as well. If you can target this, then, please, do. If not, let me know, we will add these implementations asap. Thx so much!

**Comment by clarkmoody** [comment]
My Python and PHP are a bit rusty at this point, so your implementation would be appreciated.

**Comment by rspadim** [comment]
why not a test exchange to send orders / emulate position / etc? market data can be from other exchange

**Comment by adi90x** [comment]
@rspadim  That would be a really nice idea , just a test exchange pull all market data from a random exchange

**Comment by buddylindsey** [comment]
@kroitor is there anything that we can do to get this merged since it has been approved?

**Pull request merged**
