### PR TITLE
getbtc: .has.fetchTrades = false, their API won't work

### PR DESCRIPTION
**Pull request by mkutny**
They return negative amounts/prices for trades in "BTW" currency:
```
{        id:   "1007438",
       info: {         id: "1007438",
                     date: "2018-02-19 14:07:01",
                timestamp: "1519038421",
                      btc: "0.00430000",
               maker_type: "buy",
                    price: "-195300.60",
                   amount: "-839.79",
                 currency: "BTW"                  },
  timestamp:    1519038421000,
   datetime:   "2018-02-19T11:07:01.000Z",
     symbol:   "BTC/USD",
      order:    undefined,
       type:    undefined,
       side:   "buy",
      price:    -195300.6,
     amount:    -839.79                              }
```

I'd assume that negative values mean `side === 'sell'` but I don't see any negative values and 'sell' trades in other currencies to check this hypothesis.

So I guess this endpoint simply does not properly work.

### CODE REVIEW

**Comment by mkutny** [comment]
Why the following works?
https://github.com/ccxt/ccxt/blob/aadb0be7f77cc5f7cedad124cd78e0271d58227a/js/acx.js#L93

**Comment by kroitor** [comment]
> Why the following works?`

Integers are ok as array indices, however, you might want to convert them to strings for consistency. (If I got your question correctly)

**Comment by mkutny** [comment]
Sorry, I wanted to ask this question in #1954, it's out of context here, my fault.

The issue is that `{ fetchTrades: false }` fails on python syntax check while `{ 2002: false }` do not. And `.exceptions` is not an Array so why integers work?

**Comment by kroitor** [comment]
`{ fetchTrades: false }` is a bad python syntax, it will treat fetchTrades as a variable containing the key name. Therefore it requires quotes around `fetchTrades`. It doesn't complain on integer keys only (those are allowed to be assoc-keys).

> And .exceptions is not an Array so why integers work?

Not a js-isArray(), yet still an array, an associative one ) You see, there's some term ambiguity:

- JS: plain array = *Array*, assoc array = *Object*
- Python: plain array = *list*, assoc array = *dict*
- PHP: plain array = *array*, assoc array = *array*.

So, from here, I would call any object or plain list "an array". I would call any object having assoc-keys, an "assoc array" or "map" or "dictionary". )

**Comment by mkutny** [comment]
That's quite explanatory, thanks!

**Comment by kroitor** [comment]
BTW, because in Python {} = dict, and in JS {} = Object, we can't really use the JS-syntax and dereference non-quoted keys, like so: `jsObject.someProperty`. Because of that difference this simple common js-line will trigger a linter error, a transpiler error or a syntax check failure. Python and PHP differentiate between assoc keys and object properties and demand properties to be pre-declared on the object type.

**Comment by mkutny** [comment]
Linter error won't be triggered, unfortunately.

JS community considers `.someProperty` to be a good practice (at least those who support eslint). Thus linter can enforce `.someProperty` by restricting `[someProperty]` but can't do the other way )

**Comment by kroitor** [comment]
It's ok as long as we have multiple layers of protection there )

**Comment by mkutny** [comment]
Yeah, they somewhat reinforce each other.

And, if we're paranoid on this, I guess we can add one more linter; since it's a dev dependency it won't hurt 😄

**Pull request merged**
