### PR TITLE
feat(binance): Added order 'origClientOrderId'

### PR DESCRIPTION
**Pull request by FreekyDev**

### CODE REVIEW

**Comment by carlosmiei** [comment]
Hello @FreekyDev, 
Thanks for your addition, but `origClientOrderId` is not a unified field, so I'm not sure if it should be added directly to the order structure.

**Comment by FreekyDev** [comment]
@carlosmiei
> Hello @FreekyDev, Thanks for your addition, but `origClientOrderId` is not a unified field, so I'm not sure if it should be added directly to the order structure.

How do you guys determine if a field is unified or not? So I can avoid this mistake

**Comment by carlosmiei** [comment]
> @carlosmiei
> 
> > Hello @FreekyDev, Thanks for your addition, but `origClientOrderId` is not a unified field, so I'm not sure if it should be added directly to the order structure.
> 
> How do you guys determine if a field is unified or not? So I can avoid this mistake. I mean, are you guys using a tool or just look at most of the exchanges docs?

Usually, it needs to be discussed beforehand, after identifying a common pattern across different exchanges.

**Comment by FreekyDev** [comment]
> > @carlosmiei
> > > Hello @FreekyDev, Thanks for your addition, but `origClientOrderId` is not a unified field, so I'm not sure if it should be added directly to the order structure.
> > 
> > 
> > How do you guys determine if a field is unified or not? So I can avoid this mistake. I mean, are you guys using a tool or just look at most of the exchanges docs?
> 
> Usually, it needs to be discussed beforehand, after identifying a common pattern across different exchanges.

Well, then I believe this PR can be closed without merge. No problem!

**Comment by carlosmiei** [comment]
@FreekyDev Thanks for your understanding.

**Pull request closed without merging**
