### PR TITLE
Add topq exchange

### PR DESCRIPTION
**Pull request by brandsimon**

### CODE REVIEW

**Comment by brandsimon** [comment]
@kroitor 
I dont see why travis failed, is it possible to rerun this?

**Comment by kroitor** [comment]
@brandsimon sure, i've restarted it, however, Travis currently does not intercept stderr from Python, so it cannot really show the details of the error if it crashed Python. In order to check for that, please run this locally:

```shell
npm run build
python python/test/test.py topq
```

or

```shell
npm run export-exchanges
npm run transpile
python python/test/test.py topq
```

**Comment by brandsimon** [comment]
@kroitor 
Great, thank you, fixed it!

**Comment by brandsimon** [comment]
@kroitor 
Do you know when you have time to review this?
Otherwise I'd merge it into a fork branch for my project.

**Comment by kroitor** [comment]
@brandsimon technically this integration is a clone, so it should not take too long. I will test the private part and will merge it this week.

**Pull request merged**
