### PR TITLE
Add Exchange Bybit support

### PR DESCRIPTION
**Pull request by keyganker**

### CODE REVIEW

**Comment by arnoudb** [comment]
This is awesome, was hoping this would come soon!

**Comment by Herklos** [comment]
Can we imagine to add conditionnal order and positions management ?

**Comment by willoughby** [comment]
Exchange limits are not implemented

`limits:Object {amount: Object, price: Object, cost: Object}
[[StableObjectId]]:7
amount:Object {min: undefined, max: undefined}
cost:Object {min: undefined, max: undefined}
price:Object {min: undefined, max: undefined}`

**Comment by willoughby** [comment]
Screenshot 2019-11-05 at 20 55 16
Order response is wrong, cost is always 0 on new orders when it should match info.qty, filled and fee could be initialised as the information is available.

**Comment by kroitor** [comment]
@willoughby thx, you're absolutely right, this PR needs a bit more work and polishing. 

@keyganker would you be willing to edit it for unification?

**Comment by willoughby** [comment]
@kroitor If there is a better way for me to provide feedback let me know, ill continue to publish my findings otherwise.

**Comment by kroitor** [comment]
@willoughby really appreciate your involvement, it's very helpful!

**Comment by willoughby** [comment]
Happy to were using this integration to upgrade our hand-rolled bybit integration in two bots as a service

**Comment by firepol** [comment]
Hi guys, any ideas when this PR submitted 24 days ago will be finalized (and merged)? From my understanding it needs extra work, but I guess everybody is busy?

**Comment by kroitor** [comment]
@firepol i hope to get to it in 2 weeks if no one else does it sooner, we are going to resolve the backlog of integrations and will merge most of them quickly after the release of websockets.

**Comment by keyganker** [comment]
> @willoughby thx, you're absolutely right, this PR needs a bit more work and polishing.
> 
> @keyganker would you be willing to edit it for unification?

**Comment by keyganker** [comment]
> Screenshot 2019-11-05 at 20 55 16
> Order response is wrong, cost is always 0 on new orders when it should match info.qty, filled and fee could be initialised as the information is available.

Ok, I'll check and fix it

**Comment by keyganker** [comment]
> Can we imagine to add conditionnal order and positions management ?

In fact, there is a trick for `createOrder`,  if you pass `stop_px` and `base_price` in the request, it'll call creating stop order endpoint, otherwise it'll call creating active order endpoint.

Maybe the better way is  creating a new function named `createStopOrder`?

**Comment by devcryp** [comment]
bump

**Comment by firepol** [comment]
Sorry, but I could not resist... it's only since May 2019 that we are waiting for this... :)

<a href="https://imgflip.com/i/3hdp9z"></a>

**Comment by kroitor** [comment]
@firepol this implementation has erros, you could help speed it up by downloading this PR, building it and testing/editing it: 

- Bad use of `safeInteger`: https://github.com/ccxt/ccxt/pull/5985/files#diff-0c35d7cd011ec68aecf8322c3d0d47c2R200
- Duplicate code instead of `parseOrderBook` in `fetchOrderBook`: https://github.com/ccxt/ccxt/pull/5985/files#diff-0c35d7cd011ec68aecf8322c3d0d47c2R216
- Volation of CONTRIBUTING guidelines: https://github.com/ccxt/ccxt/pull/5985/files#diff-0c35d7cd011ec68aecf8322c3d0d47c2R226 (in particular, [this](https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#accessing-dictionary-keys) and [this](https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#sanitizing-input-with-safe-methods))
- `fetchFundRecords` should be moved to `fetchDeposits` or unified as `fetchTransactions`: https://github.com/ccxt/ccxt/pull/5985/files#diff-0c35d7cd011ec68aecf8322c3d0d47c2R384
- Invalid use of the `currency` object in the arguments: https://github.com/ccxt/ccxt/pull/5985/files#diff-0c35d7cd011ec68aecf8322c3d0d47c2R396
- Fees should only be populated if fee cost is defined, and should be a positive value: https://github.com/ccxt/ccxt/pull/5985/files#diff-0c35d7cd011ec68aecf8322c3d0d47c2R424
- The `convertSymbolToCurrency` method is redundant, we can simply use `market['base']` or `market['quote']`: https://github.com/ccxt/ccxt/pull/5985/files#diff-0c35d7cd011ec68aecf8322c3d0d47c2R509
- More violations of contributing guidelines here: https://github.com/ccxt/ccxt/pull/5985/files#diff-0c35d7cd011ec68aecf8322c3d0d47c2R657
- `request()` should not be overrided for errror handling, need to move it to `handleErrors` instead:
https://github.com/ccxt/ccxt/pull/5985/files#diff-0c35d7cd011ec68aecf8322c3d0d47c2R665
- Missing definitions of some endpoints and a `fetchTrades()` public method: https://github.com/bybit-exchange/bybit-official-api-docs/blob/master/en/rest_api.md#trading-records
- ...

↑ All of this could be easily tested. Trying, testing and reporting bugs is much more helpful than waiting or asking repeatedly when it will be ready ) I hope to get to it as soon as I can.

**Comment by Manycaek** [comment]
I could provide a bounty for the merge if anyone is interested. It wouldn't be much but it's something.

**Comment by xiandong79** [comment]
Did anybody do anything?

**Comment by kroitor** [comment]
Bybit is now available in CCXT 1.24.4+ https://github.com/ccxt/ccxt/issues/6612

**Pull request merged**
