### PR TITLE
remove deprecated properties last_http_response, last_json_response, last_response_headers

### PR DESCRIPTION
**Pull request by frosty00**

### CODE REVIEW

**Comment by npomfret** [comment]
Why are these being removed? They're very useful

**Comment by kroitor** [comment]
> Why are these being removed? 

To fix the bug that currently exists there – one async *"last"* response overwrites another... These fields will now live inside the exception instance, where they belong.

> They're very useful

Check this PR: https://github.com/ccxt/ccxt/pull/5494/files

Let us know your thoughts.

**Comment by npomfret** [comment]
Will they be available outside of an exception instance?  Or perhaps we could add a mechanism to intercept them.

**Comment by xpl** [comment]
@frosty00 A grammar advice: it's _deprecated_ not depreciated.

Proof: https://techterms.com/definition/deprecated

**Comment by xpl** [comment]
And yes, these properties are quite useful, despite the possible issues with async execution. So you're removing, but not providing any alternative. That would require people to implement hacky workarounds to get this functionality back outside of the exception scope.

**Comment by frosty00** [comment]
Hi @xpl,

> We use it to access the original response when something is returned from method calls. So it's being used like info but even lower level.

Good to hear from you ) We will provide an alternative to get this data in the unified response before removing this code, it may end up being after august the 1st. Not sure what the alternative will be, maybe array properties?

```
response = exchange.methodcall ()
response.headers
response.info
response.body
```

If you have any suggestions about how we could solve this issue for the async context we would love to hear it.

**Comment by kroitor** [comment]
@xpl 

> An adequate alternative would be to return the original response along with info. But that would be incompatible with methods that do not return objects, but return arrays/scalars. That would require reworking them, breaking the back compatibility...

What if we return instances of classes inherited from native arrays, objects and dicts, having the raw response data as properties – in general case. That would preserve backward-compatibility and would allow access to raw response data without hacky workarounds, no?

**Comment by frosty00** [comment]
> What if we return instances of classes inherited from native arrays, objects and dicts, having the raw response data propagated as properties – in general case. That would preserve backward-compatibility and would allow access to raw response data without hacky workarounds, no?

This doesn't really make it any easier to figure out how we propagate the properties in every single method

**Comment by kroitor** [comment]
> This doesn't really make it any easier to figure out how we propagate the properties in every single method

Suppose the following pseudocode:

```JavaScript
response = await this.anyImplicitMethod ()

// response is a json-dictionary or a json-array
// request() or fetch() should propagate these properties
console.log (response.body, response.json, response.code)
```

↑ That way we return last_xxx_fields from every dict-response within `info`, automatically. That covers 50% of the cases – for dicts. To cover the other 50% cases for arrays – we slightly edit all `parseXXXs`  base methods.

**Pull request closed without merging**
