### PR TITLE
Huobi Japan

### PR DESCRIPTION
**Pull request by newbdez33**
I didn't touch ccxt.d.ts , i guess that file will be changed by CI?

### CODE REVIEW

**Comment by kroitor** [comment]
@newbdez33 yes, that is correct. If you can remove the edits in `ccxt.js` from this PR – that would also help. All those files are generated. We need just one derived implementation file (just the `huobijp.js` file).

**Comment by newbdez33** [comment]
this time should be fine.

**Comment by kroitor** [comment]
We will have to review and partially rewrite it, since Huobi Japan does not have v2 endpoints like the original Huobi global:

- https://github.com/ccxt/ccxt/blob/master/js/huobipro.js#L63
- https://github.com/ccxt/ccxt/blob/master/js/huobipro.js#L1201

**Comment by newbdez33** [comment]
I see. i just tested few apis i'm using in my project. any way please let me know if anything i can help.

**Pull request merged**
