### PR TITLE
gemini fetchTickers, adjust fetchTicker

### PR DESCRIPTION
**Pull request by TheTrunk**
Implements FetchTickers which uses new publicGetV1Pricefeed api endpoint
Extends fetchTicker for new fields but uses both ticker endpoints of Gemini combined.

### CODE REVIEW

**Comment by kroitor** [comment]
@TheTrunk hey! We usually don't do more than one HTTPS request per unified method, i would rewrite `fetchTicker` for an option that would allow the user to choose one of the two calls, depending on which specific data is needed. What do you say?

**Comment by TheTrunk** [comment]
Hi @kroitor 
It would be a great idea to give users the choice of what api they want to use or even both, cool!
I am not sure if I technically understand your proposal correctly. Do you mean expanding function
```js
async fetchTicker (symbol, params = {}) {
```
adding one more variable to something like including an array of methods that it will use eg
```js
async fetchTicker (symbol, params = {}, methods = ['publicGetV1PubtickerSymbol', 'publicGetV2TickerSymbol']) {
```

**Comment by kroitor** [comment]
@TheTrunk yep, however, i would not add a new argument to it, i'd say, we should rather introduce an exchange-specific option, like, for example, here: 

- https://github.com/ccxt/ccxt/blob/master/js/binance.js#L310

```JavaScript
describe () {
    // ...
    'options': {
        'fetchTickerMethod': 'fetchTickerV1', // or fetchTickerV2, or fetchTickerBoth
    }
    // ...
}
```

**Comment by kroitor** [comment]
P.S. The `parseTicker` can remain a single universal method anyway.

**Comment by TheTrunk** [comment]
@kroitor  Now it works with the option to choose the fetchTickerMethod. Falling back to default previous implementation.
Great idea! Thank you for reviewing it.

**Comment by kroitor** [comment]
@TheTrunk thx for your involvement, will merge it shortly!

**Comment by TheTrunk** [comment]
Hi @kroitor 
Would it be possible to merge it?
Thank you for an update.

**Comment by kroitor** [comment]
@TheTrunk hi! Yes, pardon for the delay, I will get back to it and I'll merge it asap!

**Pull request merged**
