### PR TITLE
Gateio futures markets

### PR DESCRIPTION
**Pull request by samgermain**
Adds future and delivery markets to Gateio

### CODE REVIEW

**Comment by frosty00** [comment]
this can be merged

**Comment by kroitor** [comment]
> this can be merged

We want to indicate if a market is linear or inverse, by adding `type` (string), `linear` (bool) and `inverse` (bool) flags to each contract market.

**Comment by kroitor** [comment]
@samgermain check these market properties (type, swap, spot, future, linear, inverse) and add them accordingly:

- https://github.com/ccxt/ccxt/blob/master/js/bybit.js#L537
- https://github.com/ccxt/ccxt/blob/master/js/phemex.js#L432
- https://github.com/ccxt/ccxt/blob/master/js/mexc.js#L503
- https://github.com/ccxt/ccxt/blob/master/js/okex.js#L683

**Comment by samgermain** [comment]
> > this can be merged
> 
> We want to indicate if a market is linear or inverse, by adding `type` (string), `linear` (bool) and `inverse` (bool) to each contract market. Probably settlement currency as well, though, this is not standardized yet.

I was thinking we could load both the `usdt` and `btc` markets and save them in markets

**Comment by kroitor** [comment]
Related: #10931

**Pull request merged**
