### PR TITLE
Tests: move proxy to skip-tests.json [ci skip]

### PR DESCRIPTION
**Pull request by carlosmiei**

### CODE REVIEW

**Comment by ttodua** [comment]
looks good 👍

**Review by ttodua — APPROVED** [review]

**Comment by ttodua** [comment]
additionally, I had a thought that in `keys.json` we might add one sample entry, like:
```
{
    "xyzexchange" : {
        "httpProxy": "012.345.678.910"
        "apiKey": "xxxxxxxx",
        "secret": "xxxxxxxx",
        "options": {
            "defaultType": "spot" // or whatever
        }
    }
}
```

**Comment by carlosmiei** [comment]
> additionally, I had a thought that in `keys.json` we might add one sample entry, like:
> 
> ```
> {
>     "xyzexchange" : {
>         "httpProxy": "012.345.678.910"
>         "apiKey": "xxxxxxxx",
>         "secret": "xxxxxxxx",
>         "options": {
>             "defaultType": "spot" // or whatever
>         }
>     }
> }
> ```

@ttodua sure will add it

**Comment by ttodua** [comment]
yeah, `sampleExchange` reads better

**Pull request merged**
