### PR TITLE
Declare cobinhood fetchOrderTrades.

### PR DESCRIPTION
**Pull request by miracle2k**

### CODE REVIEW

**Comment by Showgofar** [comment]
its returns
```

Response:

Caught exception: cobinhood 404 page not found


Response:

Caught exception: cobinhood 404 page not found

```

**Comment by kroitor** [comment]
@Showgofar for a filled order?

**Comment by Showgofar** [comment]
for filled

**Comment by kroitor** [comment]
@Showgofar can you please post your code to reproduce it and verbose request/response (without the keys) ?

**Comment by Showgofar** [comment]
sorry but problem was on my side

**Pull request merged**
