### PR TITLE
Kucoin: ohlcv fix

### PR DESCRIPTION
**Pull request by mkutny**

### CODE REVIEW

**Comment by kroitor** [comment]
The endpoint path may be different there with kitchen.kucoin.com. I mean it may not need a version number or some other part in the path. The exchanges put it all how they want it...

**Comment by kroitor** [comment]
The kraken failure is not related (it's a travis cache problem). No worries!

**Comment by mkutny** [comment]
> The endpoint path may be different there with kitchen.kucoin.com

I made it exactly per your comment in #602:

>https://kitchen.kucoin.com/v1/open/chart/history?symbol=ETH-BTC&resolution=480&from=1471799606&to=1513271666

**Comment by kroitor** [comment]
@mkutny yep, works perfectly!

**Comment by bernatfortet** [comment]
@kroitor and @mkutny I see that ohlcv is set to true in this commit but the blob in master is set to false: https://github.com/ccxt/ccxt/blob/master/js/kucoin.js

I'm curious when we'll be able to access the ohlcv data using the regular method.

Thanks!

(Awesome job in the library btw 🙏 )

**Pull request merged**
