### PR TITLE
fix(onetrading): bitpanda updated to new name onetrading, bitpanda class left as an alias

### PR DESCRIPTION
**Pull request by samgermain**
Support of the existing API domains will cease on January 4th, 2024

fixes: #20629

-----------------------------------

It looks like everything is working correctly, but all the markets are frozen/closed, so I can't test any order methods, and all the WS methods will only give the snapshot and won't update, but this is a problem with the server and not the code

```
Python v3.9.6
CCXT v4.2.3
onetrading.fetchBalance()
{'BTC': {'free': 0.0008379, 'total': 0.0008379, 'used': 0.0},
 'EUR': {'free': 0.06099889, 'total': 0.06099889, 'used': 0.0},
 'LTC': {'free': 0.0, 'total': 0.0, 'used': 0.0},
 'USDT': {'free': 11.804532, 'total': 11.804532, 'used': 0.0},
 'free': {'BTC': 0.0008379, 'EUR': 0.06099889, 'LTC': 0.0, 'USDT': 11.804532},
 'info': {'account_holder': 'b7f4e27e-b34a-493a-b0d4-4bd341a3f2e0',
          'account_id': 'b7f4e27e-b34a-493a-b0d4-4bd341a3f2e0',
          'balances': [{'account_holder': 'b7f4e27e-b34a-493a-b0d4-4bd341a3f2e0',
                        'account_id': 'b7f4e27e-b34a-493a-b0d4-4bd341a3f2e0',
                        'available': '0.0008379',
                        'change': '0.000399',
                        'currency_code': 'BTC',
                        'locked': '0.0',
                        'sequence': '12618545315',
                        'time': '2023-09-11T15:19:17.137216Z'},
                       {'account_holder': 'b7f4e27e-b34a-493a-b0d4-4bd341a3f2e0',
                        'account_id': 'b7f4e27e-b34a-493a-b0d4-4bd341a3f2e0',
                        'available': '0.06099889',
                        'change': '13.673283',
                        'currency_code': 'EUR',
                        'locked': '0.0',
                        'sequence': '12472395060',
                        'time': '2023-08-14T13:23:00.134268Z'},
                       {'account_holder': 'b7f4e27e-b34a-493a-b0d4-4bd341a3f2e0',
                        'account_id': 'b7f4e27e-b34a-493a-b0d4-4bd341a3f2e0',
                        'available': '0.0',
                        'change': '1.16178',
                        'currency_code': 'LTC',
                        'locked': '0.0',
                        'sequence': '9688664235',
                        'time': '2022-10-12T00:56:19.697459Z'},
                       {'account_holder': 'b7f4e27e-b34a-493a-b0d4-4bd341a3f2e0',
                        'account_id': 'b7f4e27e-b34a-493a-b0d4-4bd341a3f2e0',
                        'available': '11.804532',
                        'change': '10.0',
                        'currency_code': 'USDT',
                        'locked': '0.0',
                        'sequence': '12618545315',
                        'time': '2023-09-11T15:19:17.137216Z'}]},
 'total': {'BTC': 0.0008379, 'EUR': 0.06099889, 'LTC': 0.0, 'USDT': 11.804532},
 'used': {'BTC': 0.0, 'EUR': 0.0, 'LTC': 0.0, 'USDT': 0.0}}
```

```
% py onetrading watchTicker BTC/USDT
Python v3.9.6
CCXT v4.2.3
onetrading.watchTicker(BTC/USDT)
{'ask': None,
 'askVolume': None,
 'average': None,
 'baseVolume': None,
 'bid': None,
 'bidVolume': None,
 'change': None,
 'close': 45666.49,
 'datetime': '2024-01-03T23:18:54.936Z',
 'high': 45666.49,
 'info': {'high': '45666.49',
          'instrument': 'BTC_USDT',
          'last_price': '45666.49',
          'low': '45666.49',
          'price_change': '0.0',
          'price_change_percentage': '0.0',
          'price_points': [],
          'volume': '0.0'},
 'last': 45666.49,
 'low': 45666.49,
 'open': None,
 'percentage': None,
 'previousClose': None,
 'quoteVolume': 0.0,
 'symbol': 'BTC/USDT',
 'timestamp': 1704323934936,
 'vwap': None}
{'ask': None,
 'askVolume': None,
 'average': None,
 'baseVolume': None,
 'bid': None,
 'bidVolume': None,
 'change': None,
 'close': 45666.49,
 'datetime': '2024-01-03T23:19:00.064Z',
 'high': 45666.49,
 'info': {'high': '45666.49',
          'instrument': 'BTC_USDT',
          'last_price': '45666.49',
          'low': '45666.49',
          'price_change': '0.0',
          'price_change_percentage': '0.0',
          'price_points': [],
          'volume': '0.0'},
 'last': 45666.49,
 'low': 45666.49,
 'open': None,
 'percentage': None,
 'previousClose': None,
 'quoteVolume': 0.0,
 'symbol': 'BTC/USDT',
 'timestamp': 1704323940064,
 'vwap': None}
```

```
% py onetrading fetchTicker MANA/EUR
Python v3.9.6
CCXT v4.2.3
onetrading.fetchTicker(MANA/EUR)
{'ask': None,
 'askVolume': None,
 'average': None,
 'baseVolume': 0.0,
 'bid': None,
 'bidVolume': None,
 'change': None,
 'close': 0.4245,
 'datetime': '2024-01-03T23:21:00.065Z',
 'high': 0.4245,
 'info': {'base_volume': '0.0',
          'high': '0.4245',
          'instrument_code': 'MANA_EUR',
          'is_frozen': '1',
          'last_price': '0.4245',
          'low': '0.4245',
          'price_change': '0.0',
          'price_change_percentage': '0.0',
          'quote_volume': '0.0',
          'sequence': '24166',
          'state': 'CLOSED',
          'time': '2024-01-03T23:21:00.065019Z'},
 'last': 0.4245,
 'low': 0.4245,
 'open': None,
 'percentage': None,
 'previousClose': None,
 'quoteVolume': 0.0,
 'symbol': 'MANA/EUR',
 'timestamp': 1704324060065,
 'vwap': None}
```

---------------------

Travis is failing for unrelated reasons that have nothing to do with this PR

```
[TEST_FAILURE][PY][STATIC_REQUEST_TEST_FAILURE][huobi  spot [subType: linear] ][fetchOrders][Swap trailing orders]url mismatch expected "/linear-swap-api/v3/swap_cross_hisorders" received: "/linear-swap-api/v1/swap_cross_track_hisorders"

[TEST_FAILURE][PY][STATIC_REQUEST_TEST_FAILURE][huobi  spot [subType: linear] ][cancelAllOrders][Swap cancel all trailing orders]url mismatch expected "/linear-swap-api/v1/swap_cross_cancelall" received: "/linear-swap-api/v1/swap_cross_track_cancelall"
```

### CODE REVIEW

**Comment by carlosmiei** [comment]
I would like to keep the history of the file (if possible) instead of removing + adding onetrading. have you tried to, rename files + commit and then change the domains?

**Comment by samgermain** [comment]
> I would like to keep the history of the file (if possible) instead of removing + adding onetrading. have you tried to, rename files + commit and then change the domains?

I did what you said here, the first commit says the file was renamed. This should probably be merged soon because the bitpanda URL became deprecated on the 4th

**Comment by carlosmiei** [comment]
> > I would like to keep the history of the file (if possible) instead of removing + adding onetrading. have you tried to, rename files + commit and then change the domains?
> 
> I did what you said here, the first commit says the file was renamed. This should probably be merged soon because the bitpanda URL became deprecated on the 4th

@samgermain check the PR attached, it just moves the file, so it does not detect a deletation+addition.

Regarding the bitpanda thing, the problem is onetrading has all markets disabled

**Comment by samgermain** [comment]
> @samgermain check the PR attached, it just moves the file, so it does not detect a deletation+addition.

The first commit is saying that the files are renamed, the only reason this whole PR detects a deletion/addition is because bitpanda is left as an alias

**Comment by carlosmiei** [comment]
> > @samgermain check the PR attached, it just moves the file, so it does not detect a deletation+addition.
> 
> The first commit is saying that the files are renamed, the only reason this whole PR detects a deletion/addition is because bitpanda is left as an alias
> 
> 

@samgermain still, I think that means that git just assumed now that instead of the rename we have two different files because it couldn't keep track of the rename + complete rewrite

**Comment by samgermain** [comment]
> @samgermain still, I think that means that git just assumed now that instead of the rename we have two different files because it couldn't keep track of the rename + complete rewrite

@carlosmiei would that still be the case if this PR was separated into 2 separate PRs? One for the rename, and one for the alias?

**Comment by carlosmiei** [comment]
continues here: https://github.com/ccxt/ccxt/pull/20739

**Pull request closed without merging**
