### PR TITLE
Exchange qTrade.io

### PR DESCRIPTION
**Pull request by Henelik**
Official qTrade.io commit.
Let me know if there's anything I can do to help you merge!

### CODE REVIEW

**Comment by icook** [comment]
@kroitor I believe this meets the `CONTRIBUTING.md` guidelines. Is there anything we can do to help merge?

**Comment by kroitor** [comment]
@icook i will get to it asap, will review and will either merge or provide feedback as soon as i can, can't promise the exact ETA, due to:

- https://github.com/ccxt/ccxt/issues/4823#issuecomment-540924102
- https://github.com/ccxt/ccxt/issues/56#issuecomment-507290536

... but we will hopefully get the backlog of integrations resolved soon.

**Comment by kroitor** [comment]
@Henelik @icook you can help speed it up a bit, if you do the full public+private testing in js/py/php on your side, as described here: https://github.com/ccxt/ccxt/pull/6122#issuecomment-555298544

**Comment by Henelik** [comment]
@kroitor I did the testing you outlined and updated the code as necessary.  Let me know if there's anything else I can do, and thanks for helping us get this merged!

**Pull request merged**
