### PR TITLE
Add Bitmart exchange.

### PR DESCRIPTION
**Pull request by devsi**
Plenty of endpoints still to come. Initial commit. private sign() untested.

Please let me know if there's anything noticeable wrong with my code. 

Also please note Bitmart requires a call to a token endpoint to retrieve a Bearer Token which has to then be added to every subsequent private call after. The token is active for a limited time, but can be re-used.

@kroitor do you know if this has been done in any other exchange up until now? 

[https://github.com/bitmartexchange/bitmart-official-api-docs/blob/master/rest/authenticated/oauth.md](https://github.com/bitmartexchange/bitmart-official-api-docs/blob/master/rest/authenticated/oauth.md)

### CODE REVIEW

**Comment by devsi** [comment]
Aware that I need to lint and build

**Comment by kroitor** [comment]
> @kroitor do you know if this has been done in any other exchange up until now?

@devsi see the answer to the same question here: https://github.com/ccxt/ccxt/issues/4891#issuecomment-476908723

**Comment by devsi** [comment]
> > @kroitor do you know if this has been done in any other exchange up until now?
> 
> @devsi see the answer to the same question here: [#4891 (comment)](https://github.com/ccxt/ccxt/issues/4891#issuecomment-476908723)

Ah that looks good. Thanks. Will try and get it implemented well. Would you suggest making the sign-in call separate for the exchange,? or how about tying it in to the sign() method so users don't have to make a manual call to it? In Bitmart's case we don't need any extra params for the sign in so it could just happen in the background when a call to sign() is made. (and then be active until expired)

**Comment by kroitor** [comment]
> Would you suggest making the sign-in call separate for the exchange,?

Yes.

> or how about tying it in to the sign() method so users don't have to make a manual call to it?

I would rather leave the management of the token to the user. Otherwise we will have to unify the expiration logic right away.

> In Bitmart's case we don't need any extra params for the sign in so it could just happen in the background when a call to sign() is made. (and then be active until expired)

We don't want to manage the rate limits for the user, so you don't know if the user wants to wait till his current token expires or wants to get a new token before the old one expires. And, in CCXT we have a rule: "no more than one HTTP request per unified call". Managing the calls, priority and the ordering is really beyond the scope of the lib. To remain a utilitarian tool, we just need to provide the methods for the user to combine them how he wants.

**Comment by kroitor** [comment]
@devsi also, note that in the sample implementation linked above we allow the user to avoid calling `signIn` completely – by just supplying the auth token (if he wants to reuse the old one, from a saved file).

**Comment by devsi** [comment]
@kroitor I've tested and added `signIn(`) which behaves the same way as your example above. I set the `accessToken` and `expires` options on `signIn()` and a call to `token/xxx` endpoint tailors the request headers/params.

Subsequent calls to a private endpoint utilize the `accessToken` in the headers, and along with  `expires` are throwing an `AuthenticationError`. Same concept again as your example above.

Added `fetchBalance` as the first private call as it was easy to test with.

Please advise if this is not suitable! :)

**Comment by devsi** [comment]
All endpoints added and tested. Should be in a fairly good state to go now I hope.

**Comment by devsi** [comment]
> All endpoints added and tested. Failed test for Python, unsure why!

KeyError : <type 'exceptions.KeyError'> 'bitmart' 

Do I need to add the exchange somewhere else for Python? Everything passes the tests except Python, and it seems to think the exchange key doesn't exist. 

```
bitmart (Python 2): (explain @ run-tests.js:170)
	<type 'exceptions.KeyError'> 'bitmart' 
	
	  File "python/test/test.py", line 403, in <module>
	    main()
	
	  File "python/test/test.py", line 380, in main
	    exchange = exchanges[argv.exchange] (explain @ run-tests.js:173)
```

Hopefully something very straight forward to fix :)

**Comment by kroitor** [comment]
> Do I need to add the exchange somewhere else for Python?

No ) You just need to read the entire text of the error:

Screen Shot 2019-04-06 at 22 12 57

It says: there's a KeyError, and that the key `'to'` doesn't exist in the object you're trying to access in `fetchOHLCV`.
 
You're essentially breaking the rule from here:

- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#derived-exchange-classes

> **don't access non-existent keys, `array['key'] || {}` won't work in other languages!**

JS will tolerate that and the value of `params['to']` in `fetchOHLCV` will be `undefined` in JavaScript. However, other languages will not tolerate an attempt to access a non-existent key in an object. 

Therefore we have a family of `safe*` functions, which check for the existence of the key in the object and properly return `undefined/None/null` values for JS/Python/PHP. Alternatively, you could check for the key existence first...

So, you have to change that line:

```JavaScript
        if (params['to'] === undefined) {
            request['to'] = this.milliseconds ();
        }
```

↓

```JavaScript
        const toParam = this.safeValue (params, 'to');
        if (toParam === undefined) {
            request['to'] = this.milliseconds ();
        }
        //
        // OR
        //
        if (!('to' in params)) {
            request['to'] = this.milliseconds ();
        }
```

↑ I will add more clarifications on that to the CONTRIBUTING guidelines to make it more explicit.

But this is not the end of the story ) 

You don't have to check for that value at all. Because if the user passes it in `params`, then the default will get overrided in this line: https://github.com/ccxt/ccxt/pull/4913/files#diff-273938661117246b2e9d61ea04f96d41R286. The `extend` will take all keys from `params` and will replace the keys in `request`. So, the "default value" logic works automatically without having to check those values. So, you may want to change that line again:

```JavaScript
        if (!('to' in params)) {
            request['to'] = this.milliseconds ();
        }
```

↓

```JavaScript
request['to'] = this.milliseconds ();
```

One last thing that worries me in the current implementation of fetchOHLCV – it will always use the 1-day from-to range for whatever timeframe the user requested, which looks incorrect and we have to rework this. The duration of the range should be calculated using `timeframe`, `since` and `limit` arguments. In general:

- `from = since` (may need milliseconds to seconds conversion or vice versa)`
- `to = from + timeframe * limit`
- if `since` is `undefined`, then `to = this.milliseconds ()`, `from = to - timeframe * limit`.

From there ↑ it follows that `limit` is required to do the calculation of either `from` or `to`, in any case. So, to do this right, we need to first answer this question: does the exchange require `from` and `to` for `fetchOHLCV`? Because, if the exchange does not require those arguments, or any of them, we should not send them in the first place (we should use whatever the exchange default range is). So, does Bitmart require both of `from` and `to` ?

**Comment by devsi** [comment]
Will look at your concern regarding from and to. However Bitmart **does** require that both are present. You cannot miss either one out, so by default it would seem best to at least use something if the user doesn't supply them, seeing as timeframe/since/limit are optional. I could see from another exchange in the library already that it was defaulting, so I opted to do the same.

**Comment by devsi** [comment]
@kroitor looks like all tests check out now. I think OHLCV is a lot better now. I still default `limit` to 1 if it is not defined as it is essential for `from` and `to` and both of those are mandatory. The other choice would be to throw an exception if `limit` is not set. Which one would you prefer?

On another note when I run `node run-tests --python2 bitmart` locally, I still get an error. Its as follows:

Screen Shot 2019-04-16 at 12 53 29 PM

This doesn't happen during the CI tests as the checks have passed. But I'm not sure why it fails locally. Thats the error I had the first time, and unfortunately it stops me seeing if there are any further python errors. (which is why I never saw the "to" error that you helped me with above)

**Comment by wliday** [comment]
When will the pull request been merged?

**Comment by wliday** [comment]
?

**Comment by kroitor** [comment]
@wliday sorry for the long delays, will get to it as soon as I can: https://github.com/ccxt/ccxt/wiki/FAQ

**Comment by wliday** [comment]
> @wliday sorry for the long delays, will get to it as soon as I can: https://github.com/ccxt/ccxt/wiki/FAQ

@kroitor the FAQ do to have the timeline estimation 😂, it has been two months.

**Comment by devsi** [comment]
I would agree. Although @wliday do remember that @kroitor is the sole author on this project, and there's 300 open issues and 161 new exchanges waiting for implementation! In the mean time, I've been using my fork at https://github.com/devsi/ccxt. Feel free to pull it for your own use for now if you'd like. 

On that note however @kroitor, @wliday is right Bitmart is growing. It's now top 20 on coinmarketcap and is becoming more prominent every month. It's definitely one of the largest ones on the list of new exchanges waiting for merge. I too would love to see this available on the master branch!

**Comment by kroitor** [comment]
@wliday @devsi i'm sorry for the delays on my side, will get to merge it as soon as I can, hope to do it this week.

**Comment by devsi** [comment]
> @wliday @devsi i'm sorry for the delays on my side, will get to merge it as soon as I can, hope to do it this week.

Let me know if you have any pending bugs or clean up you'd like attending to. As technically working on Bitmart for CCXT is directly related to what I'm working on in the office, I can spare time to work on it :)

**Comment by wliday** [comment]
> @wliday @devsi i'm sorry for the delays on my side, will get to merge it as soon as I can, hope to do it this week.

Hi Kroitor, appreciated on your work, hope to see bitmart on ccxt asap.

**Comment by wliday** [comment]
> > @wliday @devsi i'm sorry for the delays on my side, will get to merge it as soon as I can, hope to do it this week.
> 
> Let me know if you have any pending bugs or clean up you'd like attending to. As technically working on Bitmart for CCXT is directly related to what I'm working on in the office, I can spare time to work on it :)

Hi Devsi, thanks so much for your work. I'll let you know if bitmart api have updates.

**Comment by devsi** [comment]
> Hi Devsi, thanks so much for your work. I'll let you know if bitmart api have updates.

No worries, I'm in the Bitmart API Telegram channel or on here if you wish to contact me re updates. Will happily integrate for you :)

**Comment by devsi** [comment]
Hey, @kroitor any ETA at this point?  No pressure, just so I know whether I should continue using my fork for our up coming production release!

**Comment by kroitor** [comment]
@devsi i'm afraid, i can't promise due to unknown unknowns, i didn't have the chance to get to it yet, so i failed on the previous one... i will do my best to find the time to resolve it asap, probably within a couple of weeks. If you don't want to depend on it, I'd suggest to use the fork, and switch after the merge. Pardon for the inconvenience, sorry for delays again... and thx for your understanding!

**Comment by devsi** [comment]
@kroitor eep, what happened here? I made a change and subsequently reverted it. Have you made the linting process stricter since the last time this built?

**Comment by kroitor** [comment]
> Have you made the linting process stricter since the last time this built?

Yes, it is now checking for `const` vs `let` + the trade structure format is now formalized and unified according to the Manual everywhere. But no worries, if you don't want to clean it out, I'll do that upon merging. Thx!

**Comment by devsi** [comment]
> > Have you made the linting process stricter since the last time this built?
> 
> Yes, it is now checking for `const` vs `let` + the trade structure format is now formalized and unified according to the Manual everywhere. But no worries, if you don't want to clean it up, I'll do that upon merging. Thx!

No worries, I got you! consts updated throughout and have added the additional properties the fetchTrades object. Also noticed I needed to drop the `* 100` from parseOHLCV as it was triggering your assertion: `assert (ohlcv[0] < 2147483648000)` in test.ohlcv.js

**Comment by devsi** [comment]
@kroitor Everything passed here. However locally I can't get it to build. I want to be able to access the PHP file for Bitmart, but it won't get past the Python stage. Running a python unit test causes the following error: 

```
[100%] Testing bitmart FAIL (testExchange @ run-tests.js:169)

FAILED bitmart (Python): (explain @ run-tests.js:187)

	<type 'exceptions.KeyError'> 'bitmart' 
	
	  File "python/test/test.py", line 409, in <module>
	    main()
	
	  File "python/test/test.py", line 386, in main
	    exchange = exchanges[argv.exchange] (explain @ run-tests.js:190)
FAIL ["bitmart"] (run-tests.js:268)
All done, 1 failed (run-tests.js:273)
```

Weird considering it passes fine here. Any ideas?

**Comment by kroitor** [comment]
> However locally I can't get it to build. I want to be able to access the PHP file for Bitmart, but it won't get past the Python stage.

Make sure you don't have a previous version of `ccxt` pip-installed, because if you have it, the tests will import it, instead of the package from the built folder. Check `pip list` or `pip3 list` for older versions of ccxt.

**Comment by devsi** [comment]
Hmm. It WAS out of date, but same problem. I ran `pip install ccxt --upgrade` and `pip3 install ccxt --upgrade` to bring the version number in pip list up to date.

`npm run build` gives me this:
```
> ccxt@1.18.841 qa /ccxt
> npm run check-python-syntax && npm run check-php-syntax


> ccxt@1.18.841 check-python-syntax /ccxt
> cd python && tox -e qa && cd ..

sh: 1: tox: not found
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! ccxt@1.18.841 check-python-syntax: `cd python && tox -e qa && cd ..`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the ccxt@1.18.841 check-python-syntax script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-06-28T00_03_07_142Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ccxt@1.18.841 qa: `npm run check-python-syntax && npm run check-php-syntax`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ccxt@1.18.841 qa script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-06-28T00_03_07_158Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ccxt@1.18.841 build-without-docs: `npm run export-exchanges && npm run vss && npm run check-js-syntax && npm run browserify && npm run transpile && npm run qa`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ccxt@1.18.841 build-without-docs script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-06-28T00_03_07_177Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ccxt@1.18.841 build: `npm run build-without-docs && npm run pandoc-all && npm run update-badges`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ccxt@1.18.841 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-06-28T00_03_07_193Z-debug.log
```

The `node run-tests --python bitmart` output is the same error as before.

**Comment by kroitor** [comment]
> Hmm. It WAS out of date, but same problem. I ran pip install ccxt --upgrade and pip3 install ccxt --upgrade to bring the version number in pip list up to date.

You should deinstall both ) Because installed `site-packages` in python override all local packages. The `ccxt` package that it is trying to test from a local folder – is substituted by your installed ccxt that is also installed on the same system. Just deinstall the pip-version of ccxt to test the version from your local folder.

**Comment by kroitor** [comment]
> sh: 1: tox: not found

Make sure you have `tox` installed – `pip3 install tox` or `pip install tox` depending on your version.

**Comment by devsi** [comment]
> > sh: 1: tox: not found
> 
> Do you have `tox` installed? (`pip3 install tox` or `pip install tox` depending on your version, or use a debian package for it: https://tox.readthedocs.io/en/latest/install.html )

All good now. Thank you. Yea I had to pip uninstall ccxt and then install tox. That covered it for me!

**Comment by devsi** [comment]
@wliday if you are urgent on using Bitmart, you can change your composer json to :

```
"repositories": [{
        "type": "vcs",
        "url": "git@github.com:devsi/ccxt.git",
        "no-api": true
    }],
```

and

```
"ccxt/ccxt": "dev-bitmart-built",
```

That'll override the ccxt repo and pull my pre-built branch. It's up to date and I built it before committing this particular branch. I'll keep it maintained so it's in-date with CCXT until it's merged in officially.

**Comment by vxnuke** [comment]
Hey @devsi is a python version far away?

**Comment by wliday** [comment]
hmm, I think I'll never see BitMart in CCXT 😂

**Comment by devsi** [comment]
> Hey @devsi is a python version far away?

@vxnuke a Python version is already done. When you integrate the exchange you build it in JS, but the system transpiles it to PHP, Python and Python3 for you. When this is merged the Python version will be immediately available. If you want access to it now, I suggest you use my fork (specific branch) as described above. It's fully built and includes the Python version.

**Comment by vxnuke** [comment]
Ok cheers :)
Having a bit of trouble decoding fetch tickers.
here is what i have
```
    if (exchange.has['fetchTickers']):
        data = exchange.fetch_tickers() # all tickers indexed by their symbols
    for k in data.items():
        print(k)
```
I would like to have
ticker = []
symbol = ?
ask = ?['ask_1_amount']
ticker.update([ ( symbol + '_ask', ask) ]) 
```

**Comment by devsi** [comment]
Hi @vxnuke I'm not sure what you're trying to achieve here?

If I know my symbol I can do the following:

```
"symbol" => "APL_BTC"
  "timestamp" => "1562703242008"
  "datetime" => "2019-07-09T20:14:02.008Z"
  "high" => 1.7E-7
  "low" => 1.529E-7
  "bid" => 1.66E-7
  "bidVolume" => 13393.0
  "ask" => 1.697E-7
  "askVolume" => 37100.0
  "vwap" => null
  "open" => null
  "close" => 1.68E-7
  "last" => 1.68E-7
  "previousClose" => null
  "change" => null
  "percentage" => 5.33
  "average" => null
  "baseVolume" => 51.0
  "quoteVolume" => 316687784.0
  "info" => array:12 [▶]
```

If i want to fetch all then `fetchTickers` returns the same results but as an array indexed by the symbol. In this case I could get Apollo by doing `tickers['APL_BTC']`;

Can you explain what you are trying to do please.

**Comment by vxnuke** [comment]
@devsi ok cheers ill have a play :)

**Comment by devsi** [comment]
@kroitor just running tests and they're failing again since the latest sync with master.

This time:

`node run-tests --js bitmart`

> TESTING { exchange: "bitmart", symbol: "all" }  (<anonymous> @ test.js:33)
> 	
> 	226 symbols BTC/USDT, ETH/BTC, LTC/BTC + more... (loadExchange @ test.js:186)
> 	SYMBOL: BTC/USDT (testExchange @ test.js:261)
> 	BTC/USDT fetchTicker 2019-07-12T22:39:01.142Z bid: 11799.57 ask: 11809 (printTickerOneLiner @ test.fetchTicker.js:16)
> 	fetched all 226 tickers (exports [as fetchTickers] @ test.fetchTickers.js:35)
> 	[AssertionError] ticker bid is greater than ticker ask!
> 	
> 	    actual:   null
> 	    expected: undefined
> 	
> 	    at exports                    js/test/Exchange/test.ticker.js:86        assert (ticker['bid'] <= ticker['ask'], 'ticker bid is greater than ticker ask!…
> 	    at ticker                     js/test/Exchange/test.fetchTickers.js:44  Object.values (tickers).forEach (ticker => testTicker (exchange, ticker, method…
> 	    at forEach                                                                                                                                              
> 	    at exports [as fetchTickers]  js/test/Exchange/test.fetchTickers.js:44  Object.values (tickers).forEach (ticker => testTicker (exchange, ticker, method…
> 	    at processTicksAndRejections  internal/process/task_queues.js:86

Obviously the problem is clearly explained here, but why is this now happening, and what do I need to do to fix this?

Cheers!

**Comment by kroitor** [comment]
> why is this now happening

That's a very tricky issue. Some exchanges will allow bids and asks to cross the orderbook, due to how their matching engines work. If the order is restricted from being partially-closed, due to limits or other factors – it can hang in the orderbook with a seemingly-erroneous price. And this is technically an error. Because they don't add any specific indications for such orders. Another reason for seeing bid > ask may be due to a lagging orderbook itself on the exchange side.

So, if that happens, that is usually a temporary error. And most often, the erroneous bid goes away very quickly.

> what do I need to do to fix this?

Either ignore this check for this exchange here: https://github.com/ccxt/ccxt/blob/master/js/test/Exchange/test.ticker.js#L80

Or forward to the exchange this question on how to treat their data when the bid price crosses the ask price )

**Comment by devsi** [comment]
@wliday are you aware of this issue? It seems Bitmart is overlapping the order books. The price of largest bid > than the price of smallest ask. Is this something you and your team would be willing to look at?

**Comment by wliday** [comment]
> @wliday are you aware of this issue? It seems Bitmart is overlapping the order books. It's possible for the price of largest bid to be greater than the price of smallest ask. Is this something you and your team would be willing to look at?

It may happen one or two minutes when we are deploying our matching engine. Bid can't be greater than ask normally.

**Comment by kroitor** [comment]
@devsi a quick question – can you please remove the auto-generated files from this PR so that it includes just the `bitmart.js` file? Thx! 

Just in case:

- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#transpiled-generated-files

**Comment by devsi** [comment]
> @devsi a quick question – can you please remove the auto-generated files from this PR so that it includes just the `bitmart.js` file? Thx!
> 
> Just in case:
> 
> * https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code
> * https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#transpiled-generated-files

Hey sorry that must have been a mistake when I tried to sync my fork with upstream/master. I must've accidentally pushed all the other built files from master. Will do this now :)

**Comment by devsi** [comment]
Actually I'm unsure how to go about doing this without causing a delete on master. Do I simply need to delete the files... completely delete? Or do I need to revert the commit back before this happened and force-push the changes?

**Comment by kroitor** [comment]
> Do I simply need to delete the files... completely delete? Or do I need to revert the commit back before this happened and force-push the changes?

We need to revert them, however, the easiest way it close this PR and resubmit it from a clean master fork with just the `js/bitmart.js` file in it. However, if you want to keep the commits history, then we might need to revert them manually (by adding more commits)... Unfortunately git is not too flexible in this regard.

**Comment by devsi** [comment]
I don't think it happened that long ago. What I can do is go back to before I merged, and re-commit the last few with a force-push. that should remove the files

**Comment by kroitor** [comment]
@devsi actually, it looks like your last commit did the trick )

**Comment by devsi** [comment]
I don't even know how that happened. I pushed a delete on one file to test what would happen, and then hard reset to the previous commit and force-pushed. I don't know why that fixed it. I suspect the master files that were pushed were the same or older than current master so it just removed them auto-magically?

**Comment by kroitor** [comment]
> I suspect the master files that were pushed were the same or older than current master so it just removed them auto-magically?

Yep, looks like it )

**Comment by devsi** [comment]
^ Thanks @kroitor. Lack of experience with CCXT I guess leads to missing properties. Looks a lot more comprehensive now!

**Comment by kroitor** [comment]
@devsi your help and your initial effort were invaluable! Thx to you!

**Comment by devsi** [comment]
@wliday there we go :)

**Comment by wliday** [comment]
thanks, thanks so much!!!

**Comment by kroitor** [comment]
@wliday your guidance or clarifications on the quote price increment here would be very helpful and would be very much appreciated: https://github.com/ccxt/ccxt/issues/5612! Thx in advance!

**Pull request merged**
