### PR TITLE
Okx Websocket watch_order_book fix for different limits

### PR DESCRIPTION
**Pull request by jparekh28**
This code fixes the case where user wants the websockets (asks and bids) according to limit. By default, its returning 400 asks and bids every time which may not be desired.

### CODE REVIEW

**Comment by jparekh28** [comment]
I have created the issue here  : https://github.com/ccxt/ccxt/issues/21945

**Review by sc0Vu — COMMENTED** [review]
The python files are transpiled automatically. You may want to update ts file.

**Comment by jparekh28** [comment]
Hi @sc0Vu 

Can you please teach me how to transpile and update ts file. Its my first time contributing .

**Comment by carlosmiei** [comment]
@jparekh28 Thanks for your contribution, we will do it this time nw.
Next time please check this out: https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md

**Comment by carlosmiei** [comment]
DEMO

```
 p okx watchOrderBook "LTC/USDT" 1                            
Python v3.11.7
CCXT v4.2.84
okx.watchOrderBook(LTC/USDT,1)
{'asks': [[96.37, 3.349567, 0]],
 'bids': [[96.35, 18.399243, 0]],
 'datetime': '2024-03-27T11:00:08.403Z',
 'nonce': None,
 'symbol': 'LTC/USDT',
 'timestamp': 1711537208403}
{'asks': [[96.37, 3.349567, 0]],
 'bids': [[96.35, 12.342477, 0]],
 'datetime': '2024-03-27T11:00:08.473Z',
 'nonce': None,
 'symbol': 'LTC/USDT',
 'timestamp': 1711537208473}
{'asks': [[96.37, 3.349567, 0]],
 'bids': [[96.35, 0.550976, 0]],
 'datetime': '2024-03-27T11:00:08.553Z',
```
```
p okx watchOrderBook "LTC/USDT" 5
Python v3.11.7
CCXT v4.2.84
okx.watchOrderBook(LTC/USDT,5)
{'asks': [[96.19, 7.13004, 0], [96.2, 51.121728, 0], [96.21, 22.37824, 0], [96.22, 24.286587, 0], [96.23, 42.762677, 0]],
 'bids': [[96.17, 28.092775, 0], [96.16, 70.23551, 0], [96.15, 32.661667, 0], [96.14, 31.017429, 0], [96.13, 25.36803, 0]],
 'datetime': '2024-03-27T11:00:40.503Z',
 'nonce': None,
 'symbol': 'LTC/USDT',
```
```
Python v3.11.7
CCXT v4.2.84
okx.watchOrderBook(LTC/USDT)
{'asks': [[96.54, 4.577669], [96.55, 9.418135], [96.56, 7.259551], [96.57, 13.337693], [96.58, 19.769146], [96.59, 35.304838], [96.6, 92.986123], [96.61, 78.807668], [96.62, 53.036936], [96.63, 5.76979], [96.64, 28.883222], [96.65, 38.528401], [96.66, 36.961363], [96.67, 35.39396], [96.68, 56.784329], [96.69, 26.795264], [96.7, 34.965573], [96.71, 64.30832], [96.72, 55.438692], [96.73, 32.673263], [96.74, 62.407518], [96.75, 72.520572], [96.76, 26.791012], [96.77, 17.283273], [96.78, 36.02388], [96.79, 34.879725], [96.8, 277.203165], [96.81, 62.041877], [96.82, 32.49294], [96.83, 9.791666], [96.84, 24.138363], [96.85, 90.657348], [96.86, 11.356526], [96.87, 19.709518], [96.88, 35.588089], [96.89, 99.884158], [96.9, 224.635991], [96.91, 150.796106], [96.92, 1.522557], [96.93, 0.48354], [96.94, 10.941072], [96.95, 4.583721], [96.96, 172.217872], [96.97, 10.364214], [96.98, 64.244315], [96.99, 48.780324], [97.0, 180.012656], [97.01, 0.60513], [97.02, 10.384866], [97.03, 10.810431], [97.04, 0.239592], [97.05, 0.046157], [97.06, 0.386759], [97.07, 16.392843], [97.08, 0.08147], [97.09, 0.248813], [97.1, 25.671983], [97.11, 532.374926], [97.12, 0.293218], [97.13, 0.128943], [97.14, 0.258632], [97.15, 0.467972], [97.16, 0.038921], [97.17, 5.09294], [97.18, 107.321429], [97.19, 1.507187], [97.2, 2.94218], [97.21, 113.293203], [97.22, 218.443568], [97.23, 0.074722], [97.24, 0.19936], [97.25, 0.1151], [97.26, 0.316095], [97.27, 1.966927], [97.28, 0.477901], [97.29, 0.469365], [97.3, 2.358391], [97.31, 0.812877], [97.32, 1.727395], [97.33, 0.288259], [97.34, 0.434293], [97.35, 0.931075], [97.36, 0.20031], [97.37, 0.965411], [97.38, 288.639686], [97.39, 1.119552], [97.4, 104.713843], [97.41, 2.119749], [97.42, 0.55865], [97.43, 2.017131], [97.44, 0.14578], [97.45, 1.541778], [97.46, 10.176037], [97.47, 0.135205], [97.48, 0.858411], [97.49, 3.596158], [97.5, 102.359964], [97.51, 50.03086], [97.52, 0.372373], [97.53, 0.653186], [97.54, 0.243449], [97.55, 0.193074], [97.56, 0.029864], [97.57, 3.96717], [97.58, 851.142378], [97.59, 1.503415], [97.6, 212.361964], [97.61, 0.105984], [97.62, 1.021923], [97.63, 1232.614841], [97.64, 0.372668], [97.66, 6.207631], [97.67, 0.134291], [97.68, 0.188221], [97.69, 0.055877], [97.7, 10.16723], [97.71, 0.798177], [97.72, 0.23496], [97.73, 0.222549], [97.74, 0.890026], [97.75, 1.918879], [97.76, 0.790814], [97.77, 1.449221], [97.78, 0.303376], [97.79, 2.233809], [97.8, 7.064944], [97.81, 7.895346], [97.82, 48.347856], [97.83, 0.396758], [97.84, 0.271955], [97.85, 2.222536], [97.86, 0.639952], [97.87, 8.701103], [97.88, 133.807027], [97.9, 12.251424], [97.91, 10.139238], [97.92, 0.154625], [97.93, 0.211344], [97.94, 13.675318], [97.95, 1.930282], [97.96, 0.520457], [97.97, 0.976528], [97.98, 0.253721], [97.99, 2.192215], [98.0, 715.861646], [98.01, 0.143922], [98.03, 1.948524], [98.04, 0.163209], [98.05, 15.539295], [98.06, 0.075328], [98.07, 0.043146], [98.08, 0.030529], [98.09, 0.704422], [98.1, 19.11524], [98.11, 2.23544], [98.12, 5.301904], [98.13, 1.075888], [98.14, 0.784578], [98.15, 0.129491], [98.16, 44.087811], [98.17, 8.716464], [98.18, 2.413169], [98.19, 1.142854], [98.2, 3.699566], [98.21, 0.498698], [98.22, 1.753778], [98.23, 0.126725], [98.24, 0.063126], [98.25, 0.954752], [98.26, 0.083816], [98.27, 0.362238], [98.28, 57.403482], [98.29, 0.069333], [98.3, 28.752137], [98.31, 0.035978], [98.32, 2.244959], [98.33, 6.156854], [98.34, 1.179527], [98.35, 0.144347], [98.36, 0.042716], [98.37, 1.012652], [98.38, 25.362062], [98.39, 2.316028], [98.4, 23.257546], [98.41, 2.372599], [98.42, 11.661857], [98.43, 0.075498], [98.44, 0.054873], [98.45, 1.590178], [98.46, 6.119915], [98.47, 29.718203], [98.48, 1.263036], [98.49, 6.368208], [98.5, 241.641096], [98.51, 0.238083], [98.52, 0.991771], [98.53, 0.044799], [98.54, 0.07795], [98.55, 0.167436], [98.56, 0.17332], [98.57, 0.366575], [98.58, 0.020222], [98.59, 1.130542], [98.6, 3.54432], [98.61, 0.70926], [98.62, 1.068204], [98.63, 1.688906], [98.64, 40.196025], [98.65, 2.252169], [98.66, 11.331617], [98.67, 0.093755], [98.68, 0.041406], [98.69, 0.199768], [98.7, 71.051605], [98.71, 0.206712], [98.72, 0.22864], [98.73, 0.853617], [98.74, 2.170686], [98.75, 0.025132], [98.76, 2.627558], [98.77, 0.034521], [98.78, 1.845177], [98.79, 0.174849], [98.8, 5.262574], [98.81, 15.986508], [98.82, 0.213167], [98.83, 3.357751], [98.84, 0.030057], [98.85, 0.971943], [98.86, 5.011732], [98.87, 1.810768], [98.88, 25.96426], [98.9, 61.513283], [98.91, 0.382344], [98.92, 7.851065], [98.93, 0.699287], [98.94, 1.380178], [98.95, 2.574461], [98.96, 0.609668], [98.97, 0.176635], [98.98, 0.433884], [98.99, 13.322769], [99.0, 1344.978607], [99.01, 0.047377], [99.02, 2.275433], [99.03, 4.649985], [99.04, 0.259741], [99.07, 0.757038], [99.08, 0.448659], [99.09, 2.898917], [99.1, 23.946338], [99.11, 0.032351], [99.12, 2.103416], [99.13, 52.675763], [99.14, 1.284373], [99.15, 0.145785], [99.16, 1.809434], [99.17, 2.521991], [99.18, 2.2], [99.19, 0.269441], [99.2, 76.639453], [99.21, 1.252244], [99.22, 0.25], [99.23, 11.586721], [99.24, 0.186223], [99.25, 0.162575], [99.26, 0.012501], [99.27, 0.10489], [99.28, 0.751298], [99.29, 0.049258], [99.3, 55.147842], [99.31, 0.972525], [99.32, 0.148616], [99.33, 6.059378], [99.34, 0.522973], [99.35, 6.342055], [99.36, 1.405572], [99.37, 0.141824], [99.38, 25.195895], [99.39, 0.351388], [99.4, 5.486135], [99.41, 2.02084], [99.42, 0.449849], [99.43, 0.040583], [99.44, 0.01011], [99.45, 3.406802], [99.46, 0.011732], [99.47, 14.180841], [99.48, 0.789765], [99.49, 0.411844], [99.5, 39.818271], [99.51, 0.205469], [99.52, 1.180521], [99.53, 0.851452], [99.54, 0.209698], [99.55, 2.212527], [99.56, 0.376254], [99.57, 0.471193], [99.58, 8.77982], [99.6, 11.302551], [99.61, 0.089917], [99.62, 0.339291], [99.63, 11.684896], [99.64, 0.392466], [99.65, 1.751861], [99.66, 58.287317], [99.68, 0.230641], [99.69, 469.118332], [99.7, 8.920233], [99.71, 0.422413], [99.72, 1.304055], [99.73, 32.704445], [99.74, 250.672953], [99.75, 0.136691], [99.76, 5.123407], [99.77, 8.525675], [99.78, 2.568251], [99.79, 3.191928], [99.8, 171.553102], [99.81, 0.8103], [99.82, 0.161887], [99.83, 0.036668], [99.84, 0.299224], [99.85, 85.405913], [99.86, 12.680844], [99.87, 2.010016], [99.88, 77.337666], [99.89, 0.473748], [99.9, 114.8259], [99.91, 0.877788], [99.92, 2.203705], [99.94, 0.8574], [99.95, 0.116581], [99.96, 2.057741], [99.97, 0.227514], [99.98, 1.499822], [99.99, 25.626301], [100.0, 2424.826752], [100.01, 0.852067], [100.02, 0.06826], [100.03, 0.388838], [100.04, 0.496691], [100.05, 0.073611], [100.06, 0.93221], [100.07, 0.719453], [100.08, 10.302795], [100.09, 1.062006], [100.1, 12.191952], [100.11, 0.010029], [100.12, 2.097064], [100.13, 0.111369], [100.14, 0.010032], [100.15, 0.010178], [100.16, 4.267208], [100.18, 4.493922], [100.19, 0.010557], [100.2, 5.181467], [100.21, 0.034584], [100.22, 1.280417], [100.23, 0.52398], [100.24, 0.890477], [100.25, 3.778235], [100.26, 0.051639], [100.27, 0.034521], [100.28, 4.966748], [100.29, 0.127919], [100.3, 2.273637], [100.31, 0.142836], [100.32, 0.093423], [100.33, 200.122545], [100.34, 0.191588], [100.35, 0.134341], [100.36, 0.23896], [100.37, 0.407074], [100.38, 5.24994], [100.4, 5.399058], [100.41, 2.010172], [100.42, 0.020195], [100.43, 0.595841], [100.44, 0.219409], [100.45, 0.060283], [100.46, 6.31271], [100.47, 0.98955], [100.48, 0.91021], [100.49, 6.460502], [100.5, 92.423284], [100.51, 0.022134], [100.52, 0.376067], [100.53, 0.010088], [100.55, 0.010282], [100.56, 0.329717], [100.57, 0.742607], [100.59, 0.080178], [100.6, 8.16525], [100.61, 0.033651], [100.62, 21.624361], [100.63, 0.212183], [100.64, 0.458863], [100.65, 1.151409], [100.66, 0.28826]],
 'bids': [[96.51, 34.792212], [96.5, 43.440282], [96.49, 46.108305], [96.48, 51.543464], [96.47, 61.1516], [96.46, 55.518846], [96.45, 43.578112], [96.44, 135.644992], [96.43, 142.365032], [96.42, 217.23443], [96.41, 178.389587], [96.4, 149.731467], [96.39, 55.007258], [96.38, 80.914223], [96.37, 79.148152], [96.36, 328.6842], [96.35, 180.784202], [96.34, 52.517126], [96.33, 38.496158], [96.32, 142.75084], [96.31, 48.808911], [96.3, 25.898205], [96.29, 28.476903], [96.28, 30.875325], [96.27, 184.967789], [96.26, 14.42921], [96.25, 0.102657], [96.24, 76.106218], [96.23, 5.634705], [96.22, 20.126555], [96.21, 214.679792], [96.2, 6.615648], [96.19, 0.198424], [96.18, 491.811204], [96.17, 0.154225], [96.16, 0.148729], [96.14, 0.058782], [96.13, 10.896706], [96.11, 0.010186], [96.1, 3.495173], [96.09, 10.431611], [96.08, 0.088625], [96.07, 0.020634], [96.06, 0.028222], [96.05, 0.025291], [96.04, 0.789482], [96.02, 0.040892], [96.01, 1.053629], [96.0, 22.123138], [95.99, 15.971089], [95.98, 10.388655], [95.97, 0.458509], [95.96, 1.104281], [95.95, 0.158503], [95.93, 0.031535], [95.92, 301.885694], [95.9, 1.203884], [95.89, 0.020499], [95.88, 8.86], [95.85, 5.586435], [95.84, 0.082682], [95.83, 0.188449], [95.82, 0.468626], [95.81, 99.774543], [95.8, 51.628357], [95.79, 1.226002], [95.78, 0.103332], [95.77, 0.051624], [95.75, 0.10596], [95.74, 4.085232], [95.73, 0.010999], [95.72, 1.104223], [95.71, 0.449124], [95.7, 2.325088], [95.69, 0.063357], [95.68, 1.10132], [95.67, 0.021379], [95.66, 6.190907], [95.65, 0.197717], [95.64, 0.032415], [95.63, 0.026898], [95.62, 1.227912], [95.61, 0.058911], [95.6, 1.073858], [95.58, 298.106674], [95.57, 0.808266], [95.56, 0.025788], [95.55, 0.38043], [95.54, 0.010054], [95.53, 0.173178], [95.52, 0.233529], [95.51, 0.52308], [95.5, 52.561482], [95.49, 0.247135], [95.48, 5.581979], [95.46, 0.087535], [95.45, 0.318727], [95.44, 0.455602], [95.43, 1.028075], [95.42, 0.022362], [95.41, 2.113459], [95.4, 3.272785], [95.39, 0.18108], [95.38, 25.204953], [95.37, 5.077908], [95.36, 0.182076], [95.35, 0.025358], [95.34, 0.08217], [95.33, 12.452829], [95.32, 0.654594], [95.31, 49.74905], [95.3, 9.664084], [95.29, 0.97988], [95.28, 0.064359], [95.26, 0.038792], [95.25, 0.305231], [95.24, 2.015915], [95.23, 0.028049], [95.22, 0.029534], [95.2, 120.841341], [95.19, 0.433722], [95.18, 0.094966], [95.17, 0.068968], [95.16, 0.062531], [95.15, 0.542941], [95.14, 0.10354], [95.13, 0.036017], [95.12, 0.056011], [95.11, 1.91071], [95.1, 18.166945], [95.09, 0.036024], [95.08, 2.266881], [95.07, 0.24869], [95.06, 2.625713], [95.05, 0.175095], [95.04, 0.306936], [95.03, 0.080167], [95.02, 0.022291], [95.01, 53.460525], [95.0, 10.745136], [94.99, 5.890752], [94.98, 1.645512], [94.97, 0.216076], [94.96, 0.127141], [94.94, 0.095471], [94.93, 7.630351], [94.92, 1.82334], [94.91, 0.240888], [94.9, 12.996315], [94.89, 0.332817], [94.88, 0.25582], [94.87, 11.868693], [94.86, 0.250654], [94.85, 0.258904], [94.84, 0.814098], [94.83, 0.450458], [94.82, 0.630002], [94.81, 0.243729], [94.8, 50.838899], [94.79, 0.305726], [94.78, 0.947277], [94.77, 10.870018], [94.76, 0.198009], [94.75, 0.13071], [94.74, 0.011011], [94.73, 1.861023], [94.72, 3.68454], [94.71, 0.374127], [94.7, 4.84434], [94.69, 0.187947], [94.68, 0.075248], [94.67, 1.963726], [94.66, 5.98534], [94.65, 0.676886], [94.64, 4.142749], [94.63, 0.951532], [94.62, 2.201914], [94.6, 156.319229], [94.59, 0.207873], [94.58, 1.572256], [94.57, 0.10354], [94.56, 0.078129], [94.55, 2.010027], [94.54, 0.064981], [94.53, 0.050736], [94.52, 0.152942], [94.51, 2.814696], [94.5, 34.199324], [94.49, 0.995576], [94.48, 0.272662], [94.47, 0.010186], [94.46, 1.99035], [94.45, 0.176336], [94.44, 0.185056], [94.43, 0.011639], [94.42, 2.968183], [94.41, 4.103461], [94.4, 21.420391], [94.39, 0.020142], [94.38, 25.2115], [94.37, 0.011292], [94.36, 0.020102], [94.35, 2.974703], [94.34, 8.879703], [94.33, 6.307054], [94.32, 0.262901], [94.31, 0.038608], [94.3, 2.205082], [94.29, 0.025975], [94.28, 1.618281], [94.27, 0.528015], [94.26, 2.320486], [94.25, 62.896799], [94.24, 0.345661], [94.23, 0.900714], [94.21, 50.010665], [94.2, 23.87669], [94.18, 0.23563], [94.17, 0.28208], [94.16, 11.934183], [94.15, 1.06207], [94.14, 0.17406], [94.13, 0.185215], [94.12, 2.72176], [94.11, 0.918514], [94.1, 20.251161], [94.09, 2.780918], [94.08, 503.884461], [94.07, 0.010501], [94.06, 0.157465], [94.05, 0.835739], [94.04, 0.158037], [94.03, 0.916445], [94.02, 0.413855], [94.01, 204.520846], [94.0, 175.862275], [93.99, 0.499256], [93.98, 0.664141], [93.97, 1.318143], [93.96, 8.837334], [93.95, 1.753162], [93.94, 0.172151], [93.93, 1.455999], [93.92, 0.159401], [93.91, 11.551682], [93.9, 520.997316], [93.89, 506.443504], [93.88, 0.329842], [93.87, 1.31417], [93.86, 0.351452], [93.85, 3.418481], [93.84, 0.985624], [93.83, 0.050994], [93.82, 9.25004], [93.81, 630.436295], [93.8, 13.523714], [93.79, 2.127674], [93.78, 0.532361], [93.77, 0.39026], [93.76, 5.052153], [93.75, 9.002656], [93.74, 0.031955], [93.73, 0.604826], [93.72, 0.276142], [93.71, 1061.675765], [93.7, 5.713438], [93.69, 3.226857], [93.68, 0.377878], [93.67, 1.217643], [93.66, 6.574367], [93.65, 0.020665], [93.64, 0.010186], [93.63, 0.088023], [93.62, 1.072755], [93.61, 0.621666], [93.6, 283.144251], [93.59, 3.259521], [93.58, 0.456088], [93.57, 0.06559], [93.55, 0.839194], [93.54, 2.14052], [93.53, 0.127666], [93.52, 0.022015], [93.51, 0.244461], [93.5, 12.565697], [93.49, 0.309071], [93.48, 0.109792], [93.47, 1.82672], [93.46, 0.177187], [93.45, 6.880045], [93.44, 0.765002], [93.43, 0.015138], [93.42, 5.365014], [93.41, 0.282305], [93.4, 3.578185], [93.39, 0.399001], [93.38, 35.4561], [93.37, 268.667874], [93.36, 4.065969], [93.35, 8.11278], [93.34, 0.559924], [93.33, 2.502698], [93.32, 0.010187], [93.31, 0.025975], [93.3, 111.57038], [93.29, 0.108413], [93.28, 0.023089], [93.27, 1.108247], [93.26, 0.023689], [93.25, 1.374467], [93.24, 0.153516], [93.23, 0.350115], [93.22, 1.121831], [93.21, 0.476319], [93.2, 34.941159], [93.19, 0.172501], [93.17, 1.250404], [93.16, 0.419176], [93.15, 0.996125], [93.14, 0.053247], [93.13, 0.334576], [93.12, 0.904317], [93.11, 0.24864], [93.1, 27.888172], [93.09, 0.085912], [93.08, 2.297088], [93.07, 11.187849], [93.06, 0.93966], [93.05, 0.164734], [93.04, 0.053898], [93.03, 0.078733], [93.02, 0.189865], [93.0, 171.557509], [92.99, 4.579429], [92.98, 0.010364], [92.96, 0.01004], [92.95, 0.455476], [92.94, 0.447919], [92.93, 0.523877], [92.92, 0.088554], [92.91, 0.494132], [92.9, 23.574757], [92.89, 1.27], [92.88, 55.493404], [92.87, 1.389413], [92.86, 0.752537], [92.85, 0.803267], [92.84, 0.430262], [92.83, 0.09641], [92.82, 49.457025], [92.81, 1.523849], [92.8, 22.219786], [92.79, 0.076255], [92.78, 0.0374], [92.77, 0.02927], [92.76, 1.435779], [92.75, 10.593787], [92.74, 0.010672], [92.73, 0.413923], [92.72, 0.425596], [92.71, 0.302152], [92.7, 3.340846], [92.69, 6.584496], [92.68, 1.584386], [92.67, 1.216781], [92.66, 3.60054], [92.65, 0.879922], [92.64, 1.732153], [92.62, 3.037783], [92.61, 0.924734], [92.6, 45.681501], [92.59, 1.052957], [92.58, 1.668021], [92.57, 11.705146], [92.56, 0.660827], [92.55, 8.055506], [92.54, 1.215287], [92.53, 0.592168], [92.52, 2.827739], [92.51, 58.133934], [92.5, 99.521153], [92.49, 1.783332], [92.48, 0.302339], [92.47, 80.20758], [92.46, 0.462716], [92.45, 0.061223], [92.44, 0.589842], [92.43, 0.022008], [92.42, 64.246467], [92.41, 0.573732], [92.4, 352.471168], [92.39, 12.489729], [92.38, 25.162406], [92.37, 2.015915], [92.36, 0.50937], [92.35, 0.150474], [92.34, 0.95258], [92.33, 4.675706], [92.32, 0.412795], [92.31, 0.403853]],
 'datetime': '2024-03-27T11:03:38.403Z',
 'nonce': None,
 'symbol': 'LTC/USDT',
 'timestamp': 1711537418403}
```

**Pull request merged**
