### PR TITLE
Bitget: Add Stop Order (EndPoint: /api/mix/v1/plan/placeTPSL)

### PR DESCRIPTION
**Pull request by nvrossett**
This type of order is different from the others that exist, in fact for me it is the one that has the most common and expected behavior.

It's not a triggerOrder, it's a common stop!!

I'm using this endpoint
https://bitgetlimited.github.io/apidoc/en/mix/#place-stop-order

The other version that already exists in ccxt:
https://bitgetlimited.github.io/apidoc/en/mix/#place-position-tpsl

It's always giving me an error and it doesn't understand the position opening I did, whereas the endpoint I added worked

I am creating orders in futures markets and adding stop:

For this stop I created the parameter:
stopOrderPrice, so just add it in params, and the planType that I used here is the planType

When the stopOrderPrice parameter exists, it converts the default variable side (close_long) to holdSide (long), which is the requirement for this stop, and adds the triggerPrice

Here it worked perfectly

### CODE REVIEW

**Comment by Dan-krm** [comment]
Hi @nvrossett for unifying these orders we want to follow the manual if possible:
https://github.com/ccxt/ccxt/wiki/Manual#stop-orders

If you want to do something outside of the unified schema you can always call the implicit API endpoint directly with the required parameters: https://github.com/ccxt/ccxt/wiki/Manual#implicit-api

If you would like to contribute code to CCXT you can follow these guidelines:
https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

Here is some examples of the unified orders available on Bitget:

### 1. trigger order / stop order, using triggerPrice or stopPrice:
```
bitget createOrder BTC/USD:BTC limit buy 0.001 23000 '{"triggerPrice":"24000"}'

bitget.createOrder (BTC/USD:BTC, limit, buy, 0.001, 23000, [object Object])
2023-08-03T03:27:11.143Z iteration 0 passed in 376 ms

{
  info: { clientOid: '1070836474223071232', orderId: '1070836474223071233' },
  id: '1070836474223071233',
  clientOrderId: '1070836474223071232',
  timestamp: undefined,
  datetime: undefined,
  lastTradeTimestamp: undefined,
  lastUpdateTimestamp: undefined,
  symbol: 'BTC/USD:BTC',
  type: undefined,
  timeInForce: undefined,
  postOnly: undefined,
  side: undefined,
  price: undefined,
  stopPrice: undefined,
  triggerPrice: undefined,
  average: undefined,
  cost: undefined,
  amount: undefined,
  filled: undefined,
  remaining: undefined,
  status: undefined,
  fee: undefined,
  trades: [],
  fees: [],
  reduceOnly: undefined,
  takeProfitPrice: undefined,
  stopLossPrice: undefined
}
```

### 2. stopLoss and takeProfit attached after opening a position:
```
bitget createOrder BTC/USD:BTC market buy 0.001 undefined '{"stopLossPrice":"24000"}'

bitget.createOrder (BTC/USD:BTC, market, buy, 0.001, , [object Object])
2023-08-03T03:28:35.601Z iteration 0 passed in 332 ms

{
  info: { clientOid: '1070836828532711424', orderId: '1070836828532711425' },
  id: '1070836828532711425',
  clientOrderId: '1070836828532711424',
  timestamp: undefined,
  datetime: undefined,
  lastTradeTimestamp: undefined,
  lastUpdateTimestamp: undefined,
  symbol: 'BTC/USD:BTC',
  type: undefined,
  timeInForce: undefined,
  postOnly: undefined,
  side: undefined,
  price: undefined,
  stopPrice: undefined,
  triggerPrice: undefined,
  average: undefined,
  cost: undefined,
  amount: undefined,
  filled: undefined,
  remaining: undefined,
  status: undefined,
  fee: undefined,
  trades: [],
  fees: [],
  reduceOnly: undefined,
  takeProfitPrice: undefined,
  stopLossPrice: undefined
}
```

### 3. stopLoss + takeProfit attached upon opening a position:
```
bitget createOrder BTC/USD:BTC limit buy 0.001 25000 '{"stopLoss":{"stopPrice":"24000"}}'

bitget.createOrder (BTC/USD:BTC, limit, buy, 0.001, 25000, [object Object])
2023-08-03T03:29:42.970Z iteration 0 passed in 404 ms

{
  info: { clientOid: '1070837110903808000', orderId: '1070837110849282053' },
  id: '1070837110849282053',
  clientOrderId: '1070837110903808000',
  timestamp: undefined,
  datetime: undefined,
  lastTradeTimestamp: undefined,
  lastUpdateTimestamp: undefined,
  symbol: 'BTC/USD:BTC',
  type: undefined,
  timeInForce: undefined,
  postOnly: undefined,
  side: undefined,
  price: undefined,
  stopPrice: undefined,
  triggerPrice: undefined,
  average: undefined,
  cost: undefined,
  amount: undefined,
  filled: undefined,
  remaining: undefined,
  status: undefined,
  fee: undefined,
  trades: [],
  fees: [],
  reduceOnly: undefined,
  takeProfitPrice: undefined,
  stopLossPrice: undefined
}
```

**Comment by nvrossett** [comment]
Perfect, thanks for help =)

**Comment by Dan-krm** [comment]
Closing this PR, let us know if you have any other questions

**Comment by nvrossett** [comment]
Perfect, and just for the knowledge of anyone who needs to do the same in the future, just pass the parameters as requested in the bitget documentation

```
let data = {
      marginCoin: 'your margin',
      symbol: 'your symbol',
      type: 'market',
      holdSide: 'long', // long or short
      size: 20, // Size
      clientOid: 'your custom id',
      triggerPrice: 25000, // Price
      planType: 'loss_plan' // Stop Loss = Loss_PLan
}
```

Pass as a parameter in the function below
`bitget.privateMixPostPlanPlaceTPSL(data)
`

I didn't know about these possibilities with CCXT and I just became more of a fan of the project, I felt even more free to do whatever was necessary

Gratitude

**Pull request closed without merging**
