### PR TITLE
allow to run CCXT on the waves testnet

### PR DESCRIPTION
**Pull request by peterwilli**
There were some errors I had with test net. I fixed them, also tested main net (with real money and actual trades) and this change didn't break the normal main net trades.

Demo code (I loaded the keys with some test funds):

```py
import asyncio
import os
import traceback
import sys
import ccxt.async_support as ccxt  # noqa: E402

async def test():
    exchange = ccxt.wavesexchange({
        'apiKey': '5AhPwpojq2tVaq1uWKY7X44vu8XLGRrdLU71cjthXayF',
        'secret': '5s38BH9JUCqrSyDRkqCYamhttZCdh6HyKCZBPBhmngiw',
        'enableRateLimit': True,  # this is required, as documented in the Manual!
    })
    exchange.set_sandbox_mode(True)

    response = None

    try:

        await exchange.load_markets()  # force-preload markets first

        exchange.verbose = True  # this is for debugging

        symbol = 'WAVES/USDN'  # change for your symbol
        amount = 0.4        # change the amount
        price = 100     # change the price
        response = await exchange.create_limit_sell_order(symbol, amount, price)

    except Exception as e:
        traceback.print_exc(file=sys.stdout)

    await exchange.close()
    return response

if __name__ == '__main__':
    print(asyncio.get_event_loop().run_until_complete(test()))
```

### CODE REVIEW

**Comment by kroitor** [comment]
@peterwilli thank you very much for the PR and for your involvement! If possible, can you please elaborate a bit more on what exactly was wrong with the testnet?

**Comment by kroitor** [comment]
Could you please remove the auto-generated py/php/browser files from this PR? We need just the js/wavesexchange.js file (one file), the other files are overwritten on the CI end: https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#multilanguage-support – I'll be able to merge it sooner.

**Comment by peterwilli** [comment]
> Could you please remove the auto-generated py/php/browser files from this PR? We need just the js/wavesexchange.js file (one file), the other files are overwritten on the CI end: https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#multilanguage-support – I'll be able to merge it sooner.

Sorry, I misunderstood the contributing file wrong then. I thought we had to run it on our end. I spent a couple of days tackling this so my understanding may have been a little off from all that xD

**Comment by peterwilli** [comment]
> @peterwilli thank you very much for the PR and for your involvement! If possible, can you please elaborate a bit more on what exactly was wrong with the testnet?

Yes, if you run the code on the latest commit before my changes (`26342ab9e98610bf64e18d9d7a199acf7f9b8699`) you get this error:

```
Traceback (most recent call last):
  File "/freqtrade/user_data/extras/test_waves_order.py", line 34, in test
    response = await exchange.create_limit_sell_order(symbol, amount, price)
  File "/freqtrade/user_data/ccxt/python/ccxt/async_support/wavesexchange.py", line 1073, in create_order
    priceAssets = list(rates.keys())
AttributeError: 'NoneType' object has no attribute 'keys'
```

I believe this happens because when calling http://matcher-testnet.waves.exchange/matcher/settings for test net the fees are in an object called `composite`. When you call the same on main net: http://matcher.waves.exchange/matcher/settings you can see the fees are immediately after `orderFee`. 

Note there was nothing that really suggested me to do this as the docs are lacking, but it seemed to work.

**Comment by peterwilli** [comment]
i see it's already merged, does this mean I still have to delete the generated files?

**Comment by kroitor** [comment]
> i see it's already merged, does this mean I still have to delete the generated files?

No worries, that is not relevant anymore. Thanks again for your help!

**Comment by peterwilli** [comment]
I'm also going to make another PR soon for market orders on Waves with CCXT. But need some help with that as many pages of CCXT (including the Waves page) states there's no support for that.

**Comment by kroitor** [comment]
@peterwilli technically, CCXT does support market orders, if the underlying exchange supports them. That has to be investigated.

**Comment by peterwilli** [comment]
Already got it working but im too distracted to make a solid pr rn

**Comment by kroitor** [comment]
@peterwilli nw, take your time! We appreciate your help! Thanks!

**Pull request merged**
