### PR TITLE
Add korbit exhange

### PR DESCRIPTION
**Pull request by Sebdevar**
Korbit is an exchange for South Korea. Here is it's documentation page: https://apidocs.korbit.co.kr/

I would like to use the ccxt library in link with this exchange for a python application, so I started wrapping its API for this library only on the python side.

If anyone knows how I could test it out without having to write the javascript portion, that would be great. Thanks!

### CODE REVIEW

**Comment by kroitor** [comment]
> so I started wrapping its API for this library only on the python side

Travis CI will overwrite it with the transpiled code, because CCXT has to support multiple languages:

- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#multilanguage-support
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#derived-exchange-classes

**Comment by Sebdevar** [comment]
> [...] CCXT has to support multiple languages:

In the 'How to Contribute' section is mentioned the following:
> But it doesn't mean that you have to be a JS coder to contribute. The portability principle allows Python and PHP devs to effectively participate in developing the source version as well.

How does one contribute with python in that sense?

**Comment by kroitor** [comment]
> How does one contribute with python in that sense?

If you compare any three files, say, binance.js, binance.py and binance.php – you will notice that the implementations match line-to-line. So, you don't have to know JS to add an exchange integration, even if you know Python only. In fact, if you can code the implementation in Python – you can easily code it in JS and PHP as well, because they will match very closely. You probably didn't know that you can code in JS and PHP, but, well, now you can and now you know that ) 

Most of the cases where those languages don't match are outlined and explained in the "derived classes" section of that same doc. So, adding syntax modifications throughout the file to port it from Python to JS is not hard if you follow the CONTRIBUTING guidelines precisely. 

Unfortunately, we have many pending PRs in the backlog, so we cannot rewrite it from Py to JS immediately – it will take some time for us to get to it. However, you could help port it, using the guidelines in practice. You don't even have to know the JS to code in it. The only requirement is to follow the CONTRIBUTING guidelines literally to a word. One can do that by example. 

We appreciate all help. If not, no worries, we will get there. Thx for your involvement!

**Comment by Sebdevar** [comment]
Thx, I'll look into it.

**Pull request closed without merging**
