### PR TITLE
add websocket feature

### PR DESCRIPTION
**Pull request by lfern**
@kroitor I don't know if it is would be posible now, or you think this branch is not mature enough to merge, but here you have feature/websockets branch with current status. Anyway I will add more websocket exchanges in feature/websocket-multiple brach. If you need some help to make this merge, please let me know. Thanks!

### CODE REVIEW

**Comment by frosty00** [comment]
> methodmap: this is a hack to convert a method from 'camel' format to 'snake' format, used in php & python transpiled code. Is is usefull when you need to invoke a class method with a string.

have you heard of getattr?

> 
    conx-tpl: id of the websocket connection defined in 'conx-tpls'.
    conx-param: additional config for websocket:
        url: url to connecto to
        id: internl id for the connection

We're going to have to come up with better variable names than this, who is going to use this? Ninjas?

**Comment by frosty00** [comment]
At the risk of sounding like a noob, why don't we just use regular callbacks and get rid of the event based dependency? We will have to code an interface so that the languages are unified, and all three languages support passing in functions as arguments already...

**Comment by lfern** [comment]
> > methodmap: this is a hack to convert a method from 'camel' format to 'snake' format, used in php & python transpiled code. Is is usefull when you need to invoke a class method with a string.
> 
> have you heard of getattr?
Yes, I don't like much this. I need to create a method in js file (transpiled to php and python) that could be invoked when a timeout is reached. I need to pass a string, not a pointer to this method (I think that python or php library didn't let me to use a pointer to func). But this method name is transpiled to snake format, and at that moment I wanted to test if the complete idea could works, and can't find an easy way to do this. I will try with getattr, I think we will have the same problem, but I will try.

> 
> > 
> 
> ```
> conx-tpl: id of the websocket connection defined in 'conx-tpls'.
> conx-param: additional config for websocket:
>     url: url to connecto to
>     id: internl id for the connection
> ```
> We're going to have to come up with better variable names than this, who is going to use this? Ninjas?

Yes, config is not very "friendly". `conx-tpl` define the websocket connection type and url for the exchange. Right now, we didn't implement exchanges with more that one websocket URL, but I am sure it will happen (like gemini that has different websocket URLs for each symbol).

For each event you define a `conx-tpl` reference from defined abobe, and a `conx-param` with `id` attribute, that defines an unique websocket connection id (used as contextId or connection id) and `url` attribute that it would be the real url to connect to. 

E.g. for cobinhood (and most of exchanges) this is the websocket configuration:
```javascript
           'conx-tpls': {
                    'default': {
                        'type': 'ws',
                        'baseurl': 'wss://ws.cobinhood.com/v2/ws',
                    },
                },
                'methodmap': {
                    '_websocketTimeoutRemoveNonce': '_websocketTimeoutRemoveNonce',
                },
                'events': {
                    'ob': {
                        'conx-tpl': 'default',
                        'conx-param': {
                            'url': '{baseurl}',
                            'id': '{id}',
                        },
                    },
}
```
* Only one `conx-tpl`,
* same socket url for all, same connection id and url.

For binance (streams):
```javascript
           'conx-tpls': {
                    'default': {
                        'type': 'ws-s',
                        'baseurl': 'wss://stream.binance.com:9443/stream?streams=',
                    },
                },
                'methodmap': {
                    'fetchOrderBook': 'fetchOrderBook',
                    '_websocketHandleObRestSnapshot': '_websocketHandleObRestSnapshot',
                },
                'events': {
                    'ob': {
                        'conx-tpl': 'default',
                        'conx-param': {
                            'url': '{baseurl}',
                            'id': '{id}',
                            'stream': '{symbol}@depth',
                        },
                    },
```
* again ony one url but different symbols must be passed as attributes in url, and you must reconnect to the socket if you want add a new symbol.

**Comment by lfern** [comment]
> At the risk of sounding like a noob, why don't we just use regular callbacks and get rid of the event based dependency? We will have to code an interface so that the languages are unified, and all three languages support passing in functions as arguments already...

Yes, I think it could be done, I used it because underlying websocket libraries used something like this, and I think it was easier and I though it could be useful that you could capture websocket raw events in client side to process data in another way they could need. 

Maybe you are right, you could pass a callback function to websocketSubscribe methods, and change websocket classes to receive callback function to send messages, errors, etc. to Exchange class.

**Comment by frosty00** [comment]
regardless, this branch is extremely impressive, thank you so much for your contributions to ccxt!

We'll work on cleaning this over the coming months, but this is not going to be a easy task by any means.

**Comment by lfern** [comment]
Sorry @frosty00 , I know it is not easy. Maybe I would have to request this merge before, but at the begining it was a challenge for me to find or contribute to find some method to include all websocket exchange types. I am sure there are some mistakes or some code pieces could be improved/simplified. I had to test it with some exchanges to proove that it could be a good solution, Now I am be able to add support for websocket exchanges very easily and quickly, so I had thought that it could be the right time to do this pull request.

Anyway, if you think I could help you to simplify this merge, please let me know. But, if you know or feel that this solution does not fit with ccxt guidelines or philosophy, please, let me know too. I have been watching #56 issue and I think not too much people really need this websocket facility. Maybe it would be better to convert it to a separe node/python project that include ccxt as dependency.

Meanwhile, I will add and test other exchanges in other branch "feature/websockets-multiple'

Thanks!!


> regardless, this branch is extremely impressive, thank you so much for your contributions to ccxt!
> 
> We'll work on cleaning this over the coming months, but this is not going to be a easy task by any means.

**Comment by maayank** [comment]
@kroitor @frosty00 , et al., what can I do to contribute to the merging of the websocket branch to master? Both me personally and my employer would be interested to help.

**Comment by guotie** [comment]
when will websocket support be ready and release?

**Comment by Nitrooo** [comment]
@lfern's job is impressive, but I spotted many bugs in his branch, some of them very sneaky (e.g. Kraken's order book kinda working, but reporting wrong values), so be careful and let's wait for an official integration in ccxt where bugs like that would be spotted and fixed much easier.

**Comment by Nitrooo** [comment]
@lfern's work is impressive, but I spotted a few bugs in his branch, some of them very sneaky (e.g. Kraken's order book kinda working, but reporting wrong values), so be careful and let's wait for an official integration in ccxt where bugs like that would be spotted and fixed more easily.

**Comment by Nitrooo** [comment]
@lfern's work is impressive, but I spotted a few bugs in his branch, some of them very sneaky (e.g. Kraken's order book kinda working, but reporting wrong bids values), so be careful and let's wait for an official integration in ccxt where bugs like that would be spotted and fixed more easily.

**Comment by kroitor** [comment]
Pardon for the delays. We will announce the work on streaming with a roadmap.

**Comment by lfern** [comment]
> @lfern's work is impressive, but I spotted a few bugs in his branch, some of them very sneaky (e.g. Kraken's order book kinda working, but reporting wrong bids values), so be careful and let's wait for an official integration in ccxt where bugs like that would be spotted and fixed more easily.

Sorry @Nitroo, I see some reported bugs about this, but last months I couldn't get time to try to resolve them. Some people are contributing with pull request to websocket branch, and I try to merge it into branch and merge ccxt master to it too, so people could test it with last version of ccxt code.  So if any one can resolve this bugs or add some websocket exchange support I will try to merge it into websocket branch till websocket is supported in ccxt master.

**Comment by kroitor** [comment]
For all new users who may be reading this, please, follow here: https://github.com/ccxt/ccxt/issues/6543

**Pull request closed without merging**
