### PR TITLE
Exchange: parse json once

### PR DESCRIPTION
**Pull request by mkutny**
Actually, this consists of two commits.

The first one is just variable/args renaming without functionality change. It fixes ambiguities that inhibit code comprehension, such as:
https://github.com/ccxt/ccxt/blob/0cc2191190748c57d460c0c49f617d197ea29bcc/js/base/Exchange.js#L271-L272
(first `response` is response object, second `response` is response body)

or:
https://github.com/ccxt/ccxt/blob/0cc2191190748c57d460c0c49f617d197ea29bcc/js/base/Exchange.js#L373
(`headers` belong to request, while `body` belongs to response)

First commit makest these distinctions apparent. It still could be safely merged if you won't like the second one.

The second one is as per discussion in #1250. It makes one less `.then()` and one less `JSON.parse()`. Proposed order of calls:
1. json = parseJson () // or throw Ddos
2. handleErrors (...args, json)
3. defaultErrorHandler (...args, json)

As the next step, I'd remove `last_json_response`/`last_http_response` - I see these are used in few exchanges (probably were invented before `handleErrors` was born).

### CODE REVIEW

**Comment by kroitor** [comment]
> First commit makest these distinctions apparent. It still could be safely merged if you won't like the second one.

Both of look ok to me ) Thx!

> As the next step, I'd remove last_json_response/last_http_response - I see these are used in few exchanges (probably were invented before handleErrors was born).

We still need those last*** sometimes for debugging unexpected (or yet unhandled) errors, otherwise it would be harder to reach the last raw response upon exception... And this is utilized for proper exception handling with some exchanges. For example, Polo will return a HTTP error when you fetch trades for an open order that has no trades yet.

**Comment by mkutny** [comment]
Just to polish it up.

1.
https://github.com/ccxt/ccxt/blob/9150e434570765c0752b9cd2858eeafba118e79f/js/base/Exchange.js#L404-L405

300 is not considered 'OK' by web standards. I'd switch to 299 unless you set it there specifically to address a known bug. 


2.
https://github.com/ccxt/ccxt/blob/9150e434570765c0752b9cd2858eeafba118e79f/js/base/Exchange.js#L375

If the body is empty or one character it will return an empty object. I can still accept cases when the body is empty but what one char response looks like? And when does it happen?

**Comment by mkutny** [comment]
With regard to Polo & `.last_*`. There are few lines in `cancelOrder`:
https://github.com/ccxt/ccxt/blob/9150e434570765c0752b9cd2858eeafba118e79f/js/poloniex.js#L680-L686

What if we moved to to `handleErrors` so it will throw `InvalidOrder` instead?

So code in `cancelOrder` will become:
```javascript
catch (e) {
    if (e instanceof InvalidOrder)
        throw new OrderNotFound ()
```

**Comment by kroitor** [comment]
>  I'd switch to 299 unless you set it there specifically to address a known bug.

Nope, no bugs I know of, so, safe to switch to 299.

>  I can still accept cases when the body is empty but what one char response looks like? And when does it happen?

Cryptopia, Bitfinex and some other exchanges sometimes return a body of single space, which is not a parseable json. However, I'm not able to tell right away, in which particular cases, it was added as a quickfix. We can remove it with care and see if it breaks now or not.

> What if we moved to to handleErrors so it will throw InvalidOrder instead?

The problem is that other languages have a different exception-type-matching syntax, the one in JS is pretty unique, so instanceof isn't easily transpileable (currently, not transpileable at all). Otherwise we would indeed do that with types and there would be no need for that workaround with last_http_response...

In Python/PHP the catch-clauses looks like:

```Python
    try:
        foo = bar
    except ExceptionType as exception_variable:
        ...
    except OtherErrorType as exception_variable:
        ....
```

That does not align very well with JS:

```
    try {
    } catch (e) {
        if (firstType)
            ...
        else if (secondType)
            ...
    }
```

**Comment by mkutny** [comment]
> Cryptopia, Bitfinex and some other exchanges sometimes return a body of single space, which is not a parseable json.

Let's say, we `fetchTicker` (or `createOrder`) and bitfinex responded with `' '`. We substitute is with an empty object, it passes all error handlers and hits `fetchTicker`. And `fetchTicker` throws with "can't access property xxx of undefined" or similar anyway. Why not throw `ExchangeError` right away as a result of invalid json?

Poloniex response on canceling a non-existent order:
`{"error":"Invalid order number, or you are not the person who placed the order.","success":0}`

"Invalid order number" is quite an unambiguous message that we could check inside `handleErrors` and throw the proper exception right from that place.

At the same time, I understand that a number of those `.last*` checks are for a good reason and need to be treated wisely.

**Comment by kroitor** [comment]
> Poloniex response on canceling a non-existent order:

For canceling – I totally agree with you, but I was talking of handling a special case for fetching empty trades list for a yet unfilled order – that one still triggers a HTTP error, need to figure out a way to handle it better. So, basically, I all for it, just trying not to break anything. Apart from the discussed two situations with Polo, I don't know of any other special cases... yet )))

**Comment by mkutny** [comment]
> Apart from the discussed two situations with Polo, I don't know of any other special cases... yet 

That was not Poloniex (don't see this type of handling is their code). Nevertheless, I've got the idea, no need to dig further.

> So, basically, I'm all for it, just trying not to break anything.

As a general note if/when #1292 is merged error handling will be a part of regression test suite so we will be much safer with this kind of changes.

**Comment by mkutny** [comment]
BTW, I'm not sure what the order of calls Python and PHP base classes do. If it as was in JS until this change then error handling will get broken if `handleErrors` start to rely on json.

**Comment by kroitor** [comment]
> If it as was in JS until this change then error handling will get broken if handleErrors start to rely on json.

If we detect those cases, we'll fix them, that legacy code has to be reworked anyway. There's still so much to decouple and reengineer. )

**Pull request merged**
