### PR TITLE
Add querying contract funds from Phemex

### LINKED ISSUE #20929: Unable to query contract funds from Phemex
### Operating System

Linux

### Programming Languages

JavaScript

### CCXT Version

4.2.18

### Description

I'm unable to query funds from the contract. It seems that `/api-data/futures/v2/tradeAccountDetail` isn't wrapped by ccxt yet? https://phemex-docs.github.io/#query-funds-detail

### Code

n/a

### PR DESCRIPTION
**Pull request by ThatOneCalculator**
Method: `privateGetApiDataFuturesV2TradeAccountDetail()`
Closes #20929

Tested:

```
{
  code: "0",
  msg: "OK",
  data: [
    {
      typeDesc: "REALIZED_PNL",
      amountRv: "REDACTED",
      balanceRv: "REDACTED",
      createTime: "REDACTED
      currency: "USDT",
    },
    // ...
  ],
}
```

### CODE REVIEW

**Comment by sc0Vu** [comment]
@carlosmiei should we add this in `fetchBalance`?

**Comment by carlosmiei** [comment]
@sc0Vu yes probably, will check it

**Comment by carlosmiei** [comment]
@ThatOneCalculator Thanks for adding it!

**Comment by carlosmiei** [comment]
@sc0Vu actually I'm not sure this would be a good fit for fetchBalance 
image

**Comment by ThatOneCalculator** [comment]
Yeah, I still actually have to find the function for total balance. I thought it was this since I only had a single item of history but I guess not.

**Pull request merged**
