### PR TITLE
Bithumb fetchOrder, fetchOpenOrders

### PR DESCRIPTION
**Pull request by brandsimon**

### CODE REVIEW

**Comment by kroitor** [comment]
@brandsimon thx, great stuff, as always!

**Comment by brandsimon** [comment]
@kroitor 
you're welcome and thank you too, it was a great thing to just sleep and wait.
Today there are no issues anymore with their API.

**Comment by kroitor** [comment]
> it was a great thing to just sleep and wait.

Yep, that's my favorite thing to do ))

**Comment by brandsimon** [comment]
@kroitor 
On my side this PR is ready.
Do you know when you have time to review and merge?
I need this in ~6h, I would use an own branch if you have lots of stuff to do.

**Comment by kroitor** [comment]
@kroitor in their docs they say that order_details returns an array – if you can confirm that it works with those few edits added to this PR – I will merge in no time.

**Comment by kroitor** [comment]
@brandsimon ...another problem is that GitHub is having trouble today (again):

- https://githubstatus.com

Screen Shot 2020-04-23 at 16 59 55
Screen Shot 2020-04-23 at 17 00 05

**Comment by brandsimon** [comment]
@kroitor 
fetchOpenOrders works for me, fetchOrder does not. On my side, order_details returns an object, at least if I use it with a specific order_id. Without order_id I was not able to get this endpoint working. (I tried for fetchOrders unified method)

**Comment by kroitor** [comment]
@brandsimon can you plz post a verbose output for fetchOrder for your case (unfortunately, I don't have a working keypair atm, otherwise I would test on my side).

**Comment by brandsimon** [comment]
@kroitor 
You mean something like this:
```
fetch:
 bithumb POST https://api.bithumb.com/info/order_detail 
Request:
 {
  Accept: 'application/json',
  'Content-Type': 'application/x-www-form-urlencoded',
  'Api-Key': 'XXX',
  'Api-Sign': 'XXX',
  'Api-Nonce': 'XXX'
} 
 endpoint=%2Finfo%2Forder_detail&order_id=C0101000000095458211&count=1&order_currency=BTC&payment_currency=KRW 

handleRestResponse:
 bithumb POST https://api.bithumb.com/info/order_detail 200 OK 
Response:
 {
  'Access-Control-Allow-Headers': '*',
  'Access-Control-Allow-Methods': '*',
  'Access-Control-Allow-Origin': '*',
  'Cf-Cache-Status': 'DYNAMIC',
  'Cf-Ray': '5888268c5919076a-LHR',
  'Cf-Request-Id': '0248f66bb20000076a322cd200000001',
  Connection: 'keep-alive',
  'Content-Encoding': 'gzip',
  'Content-Type': 'application/json',
  Date: 'Thu, 23 Apr 2020 14:07:23 GMT',
  'Expect-Ct': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"',
  Server: 'cloudflare',
  'Set-Cookie': '__cfduid=defb761f15c6fd153f9eeb1372bb8cd201587650843; expires=Sat, 23-May-20 14:07:23 GMT; path=/; domain=.bithumb.com; HttpOnly; SameSite=Lax, WMONID=MZfFGOBXwuF; expires=Fri, 23-Apr-2021 14:07:23 GMT; Max-Age=31536000; path=/',
  'Transfer-Encoding': 'chunked'
} 
 {"status":"0000","data":{"order_date":"1587640185400161","type":"ask","order_status":"Completed","order_currency":"BTC","payment_currency":"KRW","order_price":"8650000","order_qty":"0.001","cancel_date":"","cancel_type":"","contract":[{"transaction_date":"1587642306676954","price":"8650000","units":"0.001","fee_currency":"KRW","fee":"21.63","total":"8650"}]}} 
```

**Comment by brandsimon** [comment]
I am quite new to this verbose and debugging stuff in ccxt, usually everything just works. :D

**Comment by kroitor** [comment]
@brandsimon thx, merging shortly, this won't take long.

**Comment by brandsimon** [comment]
@kroitor 
Great, thank you, with the last change everythings seams to work again.

**Comment by kroitor** [comment]
@brandsimon btw, i would highly recommend you the `cli` examples – you can pretty much launch any method or endpoint from command line, without even having to write the code.
I am also going to upload a manual on the CLI to the wiki soon.

**Comment by brandsimon** [comment]
@kroitor 
Yeah, great idea, I think you told me at least 3 times. :D 
Probably next time I remember ;)

**Pull request merged**
