### PR TITLE
Bitmex addMargin, reduceMargin

### PR DESCRIPTION
**Pull request by Dan-krm**
Inlcuded addMargin and reduceMargin on Bitmex.

This PR isn't ready to merge. The endpoint currently doesn't change the margin amount of the specified position on the Bitmex interface.

```
bitmex.addMargin (ETH/USDT:USDT, 5)
2022-05-25T01:03:15.291Z iteration 0 passed in 2165 ms

{
  info: {
    account: '2079371',
    symbol: 'ETHUSDT',
    currency: 'USDt',
    underlying: 'ETH',
    quoteCurrency: 'USDT',
    commission: '0.00075',
    initMarginReq: '0.5',
    maintMarginReq: '0.01',
    riskLimit: '1000000000000',
    leverage: '2',
    crossMargin: false,
    deleveragePercentile: null,
    rebalancedPnl: '0',
    prevRealisedPnl: '0',
    prevUnrealisedPnl: '0',
    prevClosePrice: '1967.122',
    openingTimestamp: '2022-05-25T01:00:00.000Z',
    openingQty: '0',
    openingCost: '0',
    openingComm: '0',
    openOrderBuyQty: '0',
    openOrderBuyCost: '0',
    openOrderBuyPremium: '0',
    openOrderSellQty: '0',
    openOrderSellCost: '0',
    openOrderSellPremium: '0',
    execBuyQty: '2000',
    execBuyCost: '39424000',
    execSellQty: '0',
    execSellCost: '0',
    execQty: '2000',
    execCost: '39424000',
    execComm: '26611',
    currentTimestamp: '2022-05-25T01:03:15.522Z',
    currentQty: '2000',
    currentCost: '39424000',
    currentComm: '26611',
    realisedCost: '0',
    unrealisedCost: '39424000',
    grossOpenCost: '0',
    grossOpenPremium: '0',
    grossExecCost: '39424000',
    isOpen: true,
    markPrice: '1972.847',
    markValue: '39456940',
    riskValue: '39456940',
    homeNotional: '0.02',
    foreignNotional: '-39.45694',
    posState: '',
    posCost: '39424000',
    posCost2: '39424000',
    posCross: '8',
    posInit: '19712000',
    posComm: '44353',
    posLoss: '0',
    posMargin: '19756361',
    posMaint: '442536',
    posAllowance: '0',
    taxableMargin: '0',
    initMargin: '0',
    maintMargin: '19789301',
    sessionMargin: '0',
    targetExcessMargin: '0',
    varMargin: '0',
    realisedGrossPnl: '0',
    realisedTax: '0',
    realisedPnl: '-26611',
    unrealisedGrossPnl: '32940',
    longBankrupt: '0',
    shortBankrupt: '0',
    taxBase: '0',
    indicativeTaxRate: null,
    indicativeTax: '0',
    unrealisedTax: '0',
    unrealisedPnl: '32940',
    unrealisedPnlPcnt: '0.0008',
    unrealisedRoePcnt: '0.0017',
    simpleQty: null,
    simpleCost: null,
    simpleValue: null,
    simplePnl: null,
    simplePnlPcnt: null,
    avgCostPrice: '1971.2',
    avgEntryPrice: '1971.2',
    breakEvenPrice: '1972.55',
    marginCallPrice: '1005.55',
    liquidationPrice: '1005.55',
    bankruptPrice: '985.6',
    timestamp: '2022-05-25T01:03:15.522Z',
    lastPrice: '1972.847',
    lastValue: '39456940'
  },
  type: 'add',
  amount: 5,
  code: 'USDT',
  symbol: 'ETH/USDT:USDT',
  status: undefined
}
```

### CODE REVIEW

**Comment by samgermain** [comment]
@Dan-krm Do you think you could finish this PR up?

**Comment by Dan-krm** [comment]
> Do you think you could finish this PR up?

The PR is ready, I left it as a draft because the endpoint being used doesn't work properly and doesn't adjust your margin if you check your position on the website or using fetchPositions, I just checked again and it looks like it's still not functioning properly

**Comment by samgermain** [comment]
> > Do you think you could finish this PR up?
> 
> The PR is ready, I left it as a draft because the endpoint being used doesn't work properly and doesn't adjust your margin if you check your position on the website or using fetchPositions, I just checked again and it looks like it's still not functioning properly

how is the PR ready if the endpoint doesn't work properly?

**Comment by Dan-krm** [comment]
> > > Do you think you could finish this PR up?
> > 
> > 
> > The PR is ready, I left it as a draft because the endpoint being used doesn't work properly and doesn't adjust your margin if you check your position on the website or using fetchPositions, I just checked again and it looks like it's still not functioning properly
> 
> how is the PR ready if the endpoint doesn't work properly?

There is nothing to finish from our end

**Comment by samgermain** [comment]
> > > > Do you think you could finish this PR up?
> > > 
> > > 
> > > The PR is ready, I left it as a draft because the endpoint being used doesn't work properly and doesn't adjust your margin if you check your position on the website or using fetchPositions, I just checked again and it looks like it's still not functioning properly
> > 
> > 
> > how is the PR ready if the endpoint doesn't work properly?
> 
> There is nothing to finish from our end

ok, well if it doesn't work the PR should probably be closed, and addMargin/reduceMargin switched to false, or another pathway should be taken for writing the methods, unless there's something I'm not understanding

**Comment by Dan-krm** [comment]
> > > > > Do you think you could finish this PR up?
> > > > 
> > > > 
> > > > The PR is ready, I left it as a draft because the endpoint being used doesn't work properly and doesn't adjust your margin if you check your position on the website or using fetchPositions, I just checked again and it looks like it's still not functioning properly
> > > 
> > > 
> > > how is the PR ready if the endpoint doesn't work properly?
> > 
> > 
> > There is nothing to finish from our end
> 
> ok, well if it doesn't work the PR should probably be closed, and addMargin/reduceMargin switched to false, or another pathway should be taken for writing the methods, unless there's something I'm not understanding

Yeah we can do that, or we could leave this as a draft in case they resolve the issue on their end then it's ready. I think since it's been 7 months we can close the PR

**Comment by Dan-krm** [comment]
Closing this PR, can reopen if the Bitmex endpoints for addMargin and reduceMargin are fixed

**Pull request closed without merging**
