### PR TITLE
New exchange: paradex

### PR DESCRIPTION
**Pull request by sc0Vu**
New Exchange: Paradex https://www.paradex.trade/

There are starknet libraries need to checkout whether implemented in c# or php (hash methods , different curve and different typed data).

Rest:
  - public
    - ...

  - private
    - ...

  - test
    - ...

WS:
  - public
    - ...

  - private
    - ...

### CODE REVIEW

**Comment by carlosmiei** [comment]
paradex-logo

**Review by 1alexbc1 — COMMENTED** [review]
Proof

**Review by 1alexbc1 — COMMENTED** [review]
Proof

**Review by 1alexbc1 — APPROVED** [review]
Proof

**Comment by carlosmiei** [comment]
paradex-logo-resized

**Pull request merged**
