### PR TITLE
Add 'change' support to fetchtickers on bittrex

### PR DESCRIPTION
**Pull request by hippylover**
Hi, hopefully i did this correct(first time doing this github fork/push/pull thing).

The aim of this push(pull?) is to add 'change' support to fetchTickers for bittrex. Seems to be correct respective to webinterface on bittrex.

Also my javascript may be completely wrong :D

### CODE REVIEW

**Comment by hippylover** [comment]
#643 might be relevant.

**Comment by hippylover** [comment]
why is my kucoin stuff showing here?

**Comment by kroitor** [comment]
> btw, i see binance supplies 3 decimals and i have truncated it to 2 here. Idk if you want me to post a patch to get binance to display 2 decimals or if you want to change these to 3 decimals or how it is with other exchanges(i dont know).

I'd say, for output values, I wouldn't do the truncation at all, and let the user decide how he wants it.

**Comment by hippylover** [comment]
That is an idea, however i fail to see any usecases where a user needs more than -- say 3 -- decimals on 24H data.

**Comment by kroitor** [comment]
@hippylover it's better to give the user the most precise value, for him to decide on the rounding, than to force 3-digit rounding when a user expects 4 digits.

**Comment by hippylover** [comment]
But when would a user need 4 digits?

**Comment by kroitor** [comment]
@hippylover when calculating precise order amounts to be placed based on strategy indicators built on top of derivatives taken from that percentage values, for example )

**Comment by hippylover** [comment]
"when calculating precise order amounts to be placed based on strategy indicators built on top of derivatives taken from those percentage values, for example"

Ok that sentence went over my head. Oh well. Nice that you merged atleast.

**Pull request merged**
