### PR TITLE
phemex withdraw

### PR DESCRIPTION
**Pull request by ndubel**
https://phemex-docs.github.io/#create-withdraw-request https://phemex-docs.github.io/#deposit-status
https://phemex-docs.github.io/#withdraw-status

### CODE REVIEW

**Comment by carlosmiei** [comment]
@ndubel sorry we had a pending PR that I forgot to merge that also implements `withdraw` https://github.com/ccxt/ccxt/pull/19936.

For that reason, I'm closing this PR but let me know if anything

**Comment by ndubel** [comment]
> @ndubel sorry we had a pending PR that I forgot to merge that also implements `withdraw` #19936.
> 
> For that reason, I'm closing this PR but let me know if anything

probably we need to take `parseTransaction` from my PR cause Phemex now gives more info (for example `network`) and also there is no `amountEv` and `feeEv` in `withdraw` response, we have `amountRv` and `feeRv` instead which is directly `amount` and `fee cost` without any ratio.
Also I add many statuses to `parseTransactionStatus`.
And I can't understand the logic of `stableCoins`. If we don't provide `network` for `USDT` network will be `USDT`, strange.

**Comment by carlosmiei** [comment]
@ndubel Can you pleae update a different PR with the parseTransaction part? 

> And I can't understand the logic of stableCoins in @samgermain PR. If we don't provide network for USDT network will be USDT, strange.

I suspect that weird logic was inferred through manual testing, but I agree that it is strange, I will try to clarify it with him

**Comment by ndubel** [comment]
I will do it probably tomorrow

**Comment by ndubel** [comment]
@carlosmiei so I created https://github.com/ccxt/ccxt/pull/20395
But I don't touch the logic of `stableCoins`. 

> If we don't provide `network` for `USDT` network will be `USDT`, strange.
I confused here, vice versa stableCoins needs network and all other coins no, but still strange logic as for me. But I don't try to test it.

**Comment by ndubel** [comment]
> If we don't provide `network` for `USDT` network will be `USDT`, strange.

I confused here, vice versa stableCoins needs network and all other coins no, but still strange logic as for me. But I don't try to test it.

**Pull request closed without merging**
