### PR TITLE
fix(safeTicker) - omit zeros

### PR DESCRIPTION
**Pull request by ttodua**
this PR just skips zero values and returns undefined.
even if our Precise does not calculate well, this edit should be still merged

### CODE REVIEW

**Comment by egorbulat98** [comment]
hi, in telegram, I wrote about a bug when safeticker returns 0 to average, although it should not be 0.
I check this again with omitZero, "0.0000000000000000016319" / 2 now returns null instead of 0

image

**Comment by egorbulat98** [comment]
you can check it with mexc fetchTicker("BNBSHIB/USDT")

**Comment by ttodua** [comment]
@carlosmiei this PR might still need to be merged, independently the underlying error of mexc. we can solve that separately, but this current PR is still somewhat applicable to all scenarios/exchanges, to avoid incorrect zero value

**Comment by ttodua** [comment]
this PR mitigates mexc high precision issues, by setting `undefined` for the non-calculated values.

**Comment by ttodua** [comment]
after we implement custom precisions, things will work as expected, so there will be no problem by this.

**Review by 1alexbc1 — COMMENTED** [review]
Proof

**Review by 1alexbc1 — COMMENTED** [review]
Proof

**Review by 1alexbc1 — APPROVED** [review]
Proof

**Review by 1alexbc1 — APPROVED** [review]
Proof

**Review by 1alexbc1 — APPROVED** [review]
Proof

**Review by 1alexbc1 — APPROVED** [review]
Proof

**Pull request closed without merging**
