### PR TITLE
Bybit :: createOrder fix

### PR DESCRIPTION
**Pull request by carlosmiei**
- small create order fixes

Demo:

```
python cli.py bybit create_order "ETH/USDT" "market" "buy" 0.1 100 --verbose --sandbox --spot
Python v3.9.10
CCXT v1.84.13
bybit.create_order(ETH/USDT,market,buy,0.1,100)

fetch Request: bybit POST https://api-testnet.bybit.com/spot/v1/order RequestHeaders: {'Content-Type': 'application/x-www-form-urlencoded', 'User-Agent': 'python-requests/2.27.1', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive'} RequestBody: symbol=ETHUSDT&side=Buy&type=MARKET&timeInForce=GTC&qty=10&agentSource=CCXT&api_key=9rFT6uR4uz9Imkw4Wx&recv_window=5000&timestamp=1653647802782&sign=b2276b81f506b085fd9726e02b82a1927e1d740fd07f2708ac583c0f0586260d

fetch Response: bybit POST https://api-testnet.bybit.com/spot/v1/order 200 ResponseHeaders: {'Content-Type': 'application/json;charset=UTF-8', 'Content-Length': '338', 'Server': 'T-GATEWAY', 'Expires': 'Fri, 27 May 2022 10:36:43 GMT', 'Cache-Control': 'max-age=0, no-cache, no-store', 'Pragma': 'no-cache', 'Date': 'Fri, 27 May 2022 10:36:43 GMT', 'Connection': 'keep-alive'} ResponseBody: {"ret_code":0,"ret_msg":"","ext_code":null,"ext_info":null,"result":{"accountId":"551167","symbol":"ETHUSDT","symbolName":"ETHUSDT","orderLinkId":"1653647803029389","orderId":"1165276662244334080","transactTime":"1653647803036","price":"0","origQty":"10","executedQty":"0","status":"NEW","timeInForce":"GTC","type":"MARKET","side":"BUY"}}
{'amount': 10.0,
 'average': None,
 'clientOrderId': '1653647803029389',
 'cost': None,
 'datetime': None,
 'fee': None,
 'fees': [],
 'filled': 0.0,
 'id': '1165276662244334080',
 'info': {'accountId': '551167',
          'executedQty': '0',
          'orderId': '1165276662244334080',
          'orderLinkId': '1653647803029389',
          'origQty': '10',
          'price': '0',
          'side': 'BUY',
          'status': 'NEW',
          'symbol': 'ETHUSDT',
          'symbolName': 'ETHUSDT',
          'timeInForce': 'GTC',
          'transactTime': '1653647803036',
          'type': 'MARKET'},
 'lastTradeTimestamp': None,
 'postOnly': False,
 'price': None,
 'remaining': 10.0,
 'side': 'buy',
 'status': 'open',
 'stopPrice': None,
 'symbol': 'ETH/USDT',
 'timeInForce': 'GTC',
 'timestamp': 1653647803036.0,
 'trades': [],
 'type': 'market'}
 ```

```
 python cli.py bybit create_order "BTC/USD:USDC" "limit" "buy" 0.01 29000 --verbose --sandbox --swap
Python v3.9.10
CCXT v1.84.13
bybit.create_order(BTC/USD:USDC,limit,buy,0.01,29000)

fetch Request: bybit POST https://api-testnet.bybit.com/perpetual/usdc/openapi/private/v1/place-order RequestHeaders: {'Content-Type': 'application/json', 'X-BAPI-API-KEY': '9rFT6uR4uz9Imkw4Wx', 'X-BAPI-TIMESTAMP': '1653648314476', 'X-BAPI-SIGN': 'a017319413f3ef9cc2003aabc2b104656dd1f235301db971b363da56bc8b5ac5', 'User-Agent': 'python-requests/2.27.1', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive'} RequestBody: {"symbol":"BTCPERP","side":"Buy","orderType":"Limit","timeInForce":"GoodTillCancel","orderQty":"0.01","orderPrice":"29000","orderFilter":"Order","reduceOnly":false}

fetch Response: bybit POST https://api-testnet.bybit.com/perpetual/usdc/openapi/private/v1/place-order 200 ResponseHeaders: {'Content-Type': 'application/json; charset=utf-8', 'Content-Length': '436', 'Traceid': '74bb4ac780cab4ea', 'Timenow': '1653648314704982357', 'Server': 'T-GATEWAY', 'Expires': 'Fri, 27 May 2022 10:45:14 GMT', 'Cache-Control': 'max-age=0, no-cache, no-store', 'Pragma': 'no-cache', 'Date': 'Fri, 27 May 2022 10:45:14 GMT', 'Connection': 'keep-alive'} ResponseBody: {"retCode":0,"retMsg":"","result":{"orderId":"477ad8b5-c047-48ba-82a5-9aeddea32e8a","orderLinkId":"","mmp":false,"symbol":"BTCPERP","orderType":"Limit","side":"Buy","orderQty":"0.01000000","orderPrice":"29000.00","iv":"0","timeInForce":"GoodTillCancel","orderStatus":"Created","createdAt":"1653648314700509","basePrice":"0.00","triggerPrice":"0.00","takeProfit":"0.00","stopLoss":"0.00","slTriggerBy":"UNKNOWN","tpTriggerBy":"UNKNOWN"}}
{'amount': 0.01,
 'average': None,
 'clientOrderId': None,
 'cost': None,
 'datetime': '2022-05-27T10:45:14.700Z',
 'fee': None,
 'fees': [],
 'filled': None,
 'id': '477ad8b5-c047-48ba-82a5-9aeddea32e8a',
 'info': {'basePrice': '0.00',
          'createdAt': '1653648314700509',
          'iv': '0',
          'mmp': False,
          'orderId': '477ad8b5-c047-48ba-82a5-9aeddea32e8a',
          'orderLinkId': '',
          'orderPrice': '29000.00',
          'orderQty': '0.01000000',
          'orderStatus': 'Created',
          'orderType': 'Limit',
          'side': 'Buy',
          'slTriggerBy': 'UNKNOWN',
          'stopLoss': '0.00',
          'symbol': 'BTCPERP',
          'takeProfit': '0.00',
          'timeInForce': 'GoodTillCancel',
          'tpTriggerBy': 'UNKNOWN',
          'triggerPrice': '0.00'},
 'lastTradeTimestamp': None,
 'postOnly': False,
 'price': 29000.0,
 'remaining': None,
 'side': 'buy',
 'status': 'open',
 'stopPrice': '0.00',
 'symbol': 'BTC/USD:USDC',
 'timeInForce': 'GTC',
 'timestamp': 1653648314700,
 'trades': [],
 'type': 'limit'}
```

### CODE REVIEW

**Comment by flieks** [comment]
Thanks for this change but i still get this error on bybit limit order:
`"ret_code":10001,"ret_msg":"qty err",`

i see in request log it is still placing qty 4.5 for ADA. It whould probably floor it to qty: 4 no ?

**Comment by carlosmiei** [comment]
Hello @flieks,
Nop you can buy fractional sizes the same way you can buy 0.0001 BTC you should be able to buy 4.5 ADA. One thing to bear in mind at Bybit is that usually, the order cost cannot be less than 10 USD so that might explain the error you're facing

4.5 ADA = +- 2.7 USD < 10 USD

**Comment by carlosmiei** [comment]
@flieks Oh ok I thought we were talking about spot markets but yes you're right it is missing there I'll add it, thanks

**Comment by flieks** [comment]
thanks alot. 
And for other exchanges the quantities/positions are floored also with decimalToPrecision or the exchanges can handle the overfloating numbers ?

**Comment by flieks** [comment]
ok so i shouldn't care about it. Thanks

**Pull request merged**
