### PR TITLE
feat(coinone):  replace endpoint for fetch orders to use query order instead of deprecated endpoint

### PR DESCRIPTION
**Pull request by pcriadoperez**
fix: #17202 

Note: Did not have api key to test

### CODE REVIEW

**Comment by jkjin7** [comment]
I would like to express my gratitude for contribution @pcriadoperez and this pull request.

I have conducted some testing using my API keys with the new Coinone code and have noticed a few differences in the response compared to the current code on the master branch. 
Specifically, when using the fetchOrder function, I received an object with many undefined values indicating an error.

Additionally, I noticed differences when creating an order compared to the current code. I have included the responses below for your reference:

1. Response when creating an order with the current code on the master branch:
```
{
  info: {
    result: 'success',
    errorCode: '0',
    orderId: '38d3e731-1e4f-11e9-9ec7-00e04c3600d7'
  },
  id: '38d3e731-1e4f-11e9-9ec7-00e04c3600d7',
  clientOrderId: undefined,
  timestamp: undefined,
  datetime: undefined,
  lastTradeTimestamp: undefined,
  symbol: 'ETH/KRW',
  type: 'limit',
  timeInForce: undefined,
  postOnly: undefined,
  side: undefined,
  price: undefined,
  stopPrice: undefined,
  triggerPrice: undefined,
  cost: undefined,
  average: undefined,
  amount: undefined,
  filled: undefined,
  remaining: undefined,
  status: undefined,
  fee: undefined,
  trades: [],
  fees: [],
  reduceOnly: undefined
}
```

2. Response when fetching an order with the current code on the master branch:
```
await coinone.fetchOrder('38d3e731-1e4f-11e9-9ec7-00e04c3600d7', 'ETH/KRW')
{
  info: {
    orderId: '38d3e731-1e4f-11e9-9ec7-00e04c3600d7',
    currency: 'ETH',
    type: 'bid',
    price: '2000000.0',
    qty: '0.0026',
    remainQty: '0.0026',
    feeRate: '0.002',
    fee: '0.0',
    timestamp: '1679579397',
    status: undefined
  },
  id: '38d3e731-1e4f-11e9-9ec7-00e04c3600d7',
  clientOrderId: undefined,
  timestamp: 1679579397000,
  datetime: '2023-03-23T13:49:57.000Z',
  lastTradeTimestamp: undefined,
  symbol: 'ETH/KRW',
  type: 'limit',
  timeInForce: undefined,
  postOnly: undefined,
  side: 'buy',
  price: 2000000,
  stopPrice: undefined,
  triggerPrice: undefined,
  cost: 0,
  average: undefined,
  amount: 0.0026,
  filled: 0,
  remaining: 0.0026,
  status: undefined,
  fee: { cost: 0, rate: 0.002, currency: 'ETH' },
  trades: [],
  fees: [ { cost: 0, rate: 0.002, currency: 'ETH' } ],
  reduceOnly: undefined
}
```

3. Response when creating an order with the new code in this pull request:
```
> await coinone.createLimitBuyOrder('ETH/KRW', 0.0026, 2000000)
{
  info: {
    result: 'success',
    errorCode: '0',
    orderId: '38d55b2d-1e4f-11e9-9ec7-00e04c3600d7'
  },
  id: '38d55b2d-1e4f-11e9-9ec7-00e04c3600d7',
  clientOrderId: undefined,
  timestamp: undefined,
  datetime: undefined,
  lastTradeTimestamp: undefined,
  symbol: 'undefined/undefined',
  type: 'limit',
  timeInForce: undefined,
  postOnly: undefined,
  side: undefined,
  price: undefined,
  stopPrice: undefined,
  triggerPrice: undefined,
  cost: undefined,
  average: undefined,
  amount: undefined,
  filled: undefined,
  remaining: undefined,
  status: undefined,
  fee: undefined,
  trades: [],
  fees: [],
  reduceOnly: undefined
}
```

4. Response when fetching an order with the new code in this pull request:
```
> await coinone.fetchOrder('38d55b2d-1e4f-11e9-9ec7-00e04c3600d7', 'ETH/KRW')
{
  info: { status: undefined },
  id: undefined,
  clientOrderId: undefined,
  timestamp: undefined,
  datetime: undefined,
  lastTradeTimestamp: undefined,
  symbol: 'undefined/undefined',
  type: 'limit',
  timeInForce: undefined,
  postOnly: undefined,
  side: undefined,
  price: undefined,
  stopPrice: undefined,
  triggerPrice: undefined,
  cost: undefined,
  average: undefined,
  amount: undefined,
  filled: undefined,
  remaining: undefined,
  status: undefined,
  fee: undefined,
  trades: [],
  fees: [],
  reduceOnly: undefined
}
```

Thank you again for your hard work and contribution to this project.

**Comment by pcriadoperez** [comment]
Hi @jkjin7 thanks so much for testing this. I made some changes that hopefully now should work, howver I don't have an api key to test and confirm

**Comment by jkjin7** [comment]
It looks like the fix worked well. 😃 @pcriadoperez 

Here is my test using node REPL:
```
> await coinone.createLimitBuyOrder('ETH/KRW', 0.0026, 2001000)
{
  info: {
    result: 'success',
    errorCode: '0',
    orderId: '410951a1-1e4f-11e9-9ec7-00e04c3600d7'
  },
  id: '410951a1-1e4f-11e9-9ec7-00e04c3600d7',
  clientOrderId: undefined,
  timestamp: undefined,
  datetime: undefined,
  lastTradeTimestamp: undefined,
  symbol: 'ETH/KRW',
  type: 'limit',
  timeInForce: undefined,
  postOnly: undefined,
  side: undefined,
  price: undefined,
  stopPrice: undefined,
  triggerPrice: undefined,
  cost: undefined,
  average: undefined,
  amount: undefined,
  filled: undefined,
  remaining: undefined,
  status: undefined,
  fee: undefined,
  trades: [],
  fees: [],
  reduceOnly: undefined
}
>
> await coinone.fetchOrder('410951a1-1e4f-11e9-9ec7-00e04c3600d7', 'ETH/KRW')
{
  info: {
    orderId: '410951a1-1e4f-11e9-9ec7-00e04c3600d7',
    currency: 'ETH',
    type: 'bid',
    price: '2001000.0',
    qty: '0.0026',
    remainQty: '0.0026',
    feeRate: '0.002',
    fee: '0.0',
    timestamp: '1684305894',
    status: undefined
  },
  id: '410951a1-1e4f-11e9-9ec7-00e04c3600d7',
  clientOrderId: undefined,
  timestamp: 1684305894000,
  datetime: '2023-05-17T06:44:54.000Z',
  lastTradeTimestamp: undefined,
  symbol: 'ETH/KRW',
  type: 'limit',
  timeInForce: undefined,
  postOnly: undefined,
  side: 'buy',
  price: 2001000,
  stopPrice: undefined,
  triggerPrice: undefined,
  cost: 0,
  average: undefined,
  amount: 0.0026,
  filled: 0,
  remaining: 0.0026,
  status: undefined,
  fee: { cost: 0, rate: 0.002, currency: 'ETH' },
  trades: [],
  fees: [ { cost: 0, rate: 0.002, currency: 'ETH' } ],
  reduceOnly: undefined
}
> await coinone.cancelOrder('410951a1-1e4f-11e9-9ec7-00e04c3600d7', 'ETH/KRW', {price: 2000000, qty: 0.0026, is_ask: 0})
{ result: 'success', errorCode: '0' }
```

**Comment by carlosmiei** [comment]
LGTM ✅

**Review by carlosmiei — APPROVED** [review]

**Pull request merged**
