### PR TITLE
Rename `fetchFundingFees/fetch_funding_fees` into `fetchTransactionFees/fetch_transaction_fees`

### PR DESCRIPTION
**Pull request by ttodua**

### CODE REVIEW

**Comment by ttodua** [comment]
@kroitor  PR is ready

**Comment by chenkaiC4** [comment]
hi, `js/test/Exchange/test.fetchFundingFees.js` should rename to `js/test/Exchange/test.fetchTransactionFees.js`.

image

**Comment by kroitor** [comment]
> hi, `js/test/Exchange/test.fetchFundingFees.js` should rename to `js/test/Exchange/test.fetchTransactionFees.js`.
> 
> image

Good catch! 

 @ttodua let’s rename the tests as well

**Comment by ttodua** [comment]
right! done: https://github.com/ccxt/ccxt/pull/13327

**Pull request merged**
