### PR TITLE
safeNumber first arg default

### PR DESCRIPTION
**Pull request by frosty00**
we might also want to do `safeNumber('0.0001')`

this PR adds support for this type of usage

### CODE REVIEW

**Comment by kroitor** [comment]
@frosty00 is there a place for the use case? Tbh, i'd rather not have the extra conditional inside the method, instead, we could add a new method name and call it in-place where needed instead of safeNumber – that would reduce the excess jumps on the stack. Lmk your thoughts.

**Comment by frosty00** [comment]
it is a different use case but the logic is very similar, so it'd rather just reuse safeNumber

**Comment by kroitor** [comment]
> so it'd rather just reuse safeNumber

I mean, there's not much sense in doing the unnecessary work in every safeNumber call, right?

**Comment by frosty00** [comment]
> > so it'd rather just reuse safeNumber
> 
> I mean, there's not much sense in doing the unnecessary work in every safeNumber call, right?

Yes, but also we are speaking of less than a microsecond, might not be worth optimizing

**Comment by kroitor** [comment]
> might not be worth optimizing

I mean, it is already optimized and if we merge it as is we get a worse result than we already have, so merging as is would be a regress? If we can keep it without adding the extra jump, then maybe we should not add it there at all and have this coded with a different call, thus removing that conditional from the userland entirely and leaving the dispatching of the value to the language itself. To me it depends on the frequency of use-cases. If we use safeNumber in 90% of cases, then we should not change it, and we should rather add another method. If that makes sense to you, i'll add the edits and will merge shortly.

**Comment by frosty00** [comment]
Screenshot 2021-03-30 at 23 22 00

**Comment by frosty00** [comment]
when we speak of 0.01us I don't see the point of optimising

**Comment by kroitor** [comment]
> when we speak of 0.01us I don't see the point of optimising

When we speak of hundreds of calls each costing 0.01us extra – it starts making a difference, cause it accumulates and we call safeNumber hundreds of times per each response. Which is why calling the above single-run test is not too representative to me (mostly due to caching and other CPUvsJS specifics).

**Comment by frosty00** [comment]
let's assume 10x per call, and 100x calls is still 10us which is 0.01ms - there is many things in the lib that we need to optimise before we get to this point, for example the newly added string regex is ~4ms per call

**Comment by frosty00** [comment]
to me we should not bother to optimise a single if clause, cause that is not really true optimisation

**Comment by kroitor** [comment]
> let's assume 10x per call, and 100x calls is still 10us which is 0.01ms - there is many things in the lib that we need to optimise before we get to this point, for example the newly added string regex is ~4ms per call

Tbh, I still don't see a point of making it slightly slower when there's an opportunity of keeping it slightly faster.

> to me we should not bother to optimise a single if clause, cause that is not really true optimisation

We should avoid optimizing it by just not having it in the code (no need to optimize the code that does not exist).

**Comment by kroitor** [comment]
It also makes sense to separate them for semantical reasons.

**Comment by frosty00** [comment]
it becomes a question of code complexity cause now there is more functions. `safeCurrencyCode` does the same thing. why don't we split that into three functions to get rid of the if statements. why don't we get rid of extend and just mutate the objects to optimise... there is many things that are higher priority than this and keeping the naming convention the same would match with `safeCurrencyCode`

**Comment by kroitor** [comment]
@frosty00 can you point out the places where we would call it without the second arg?

**Comment by frosty00** [comment]
it depends on https://github.com/ccxt/ccxt/pull/8630

**Comment by frosty00** [comment]
basically we would do this:

```
priceString = safeString (order, 'price')
amountString = safeString (order, 'amount')
costString = Precision.stringMul(priceString, amountString)
price = safeNumber (priceString)
amount = safeNumber (amountString)
cost = safeNumber (costString)


```

**Comment by kroitor** [comment]
@frosty00 i'd change it to this if you don't mind:

```
priceString = safeString (order, 'price')
amountString = safeString (order, 'amount')
costString = Precision.stringMul (priceString, amountString)
price = parseNumber (priceString)
amount = parseNumber (amountString)
cost = parseNumber (costString)
```

**Pull request closed without merging**
