### PR TITLE
base - nonNull

### PR DESCRIPTION
**Pull request by ttodua**
This PR is needed across other PRs (i.e. #14807,  #14582 , #14579)

### CODE REVIEW

**Comment by frosty00** [comment]
why do we need this code? can't we just check the truthiness instead like this

```
if (!nullValue) {
   // run code
}
```

imo having this extra function is ugly and I would not propose to merge it

**Comment by ttodua** [comment]
> why do we need this code? can't we just check the truthiness instead like this
> 
> ```
> if (!nullValue) {
>    // run code
> }
> ```
> 
> imo having this extra function is ugly and I would not propose to merge it

I understand your concern, but let me explain the reasons for it.
For example, across different issues, there are cases (rarely, but still) when exchange returns `null` (caused due to unexpected consequences, be it server side or whatever). However, we can't do `value !== null` as it is not transpilable. To check again language-specific `null` values (null/undefined/None...) I think that the only good way might be the base function, because `!value` is not  good/bulletproof way, as we aim to have different langs supported, and the value will not be directly convertable into `bool` (say `C#` or other langs, as opposed to js/php where yes - you can have `!value` for different types). 

So, if you look through the linked issues/PRs, you will see that users are getting `null` (not `undefined`) in here or there. 
let me know your thoughts

**Comment by ttodua** [comment]
the second alternative might be, that we added the regex to transpiler, so: 
```
value === null || value=== undefined  (but ofc with different operators cases)
```
 converts just to single , target-language-specific syntax, like:
`value === None` (py)
`value === null` (php)

so, we can alternatively amend transpiler to handle that.

**Comment by kroitor** [comment]
@ttodua 

> However, we can't do value !== null as it is not transpilable.

We can use safeString, safeNumber, and other safe methods to sanitize non-null and non-undefined input that will return undefined if the input does not qualify – I would stick to that approach everywhere and don't compare to null specifically.

**Comment by ttodua** [comment]
> @ttodua
> 
> > However, we can't do value !== null as it is not transpilable.
> 
> We can use safeString, safeNumber, and other safe methods to sanitize non-null and non-undefined input that will return undefined if the input does not qualify – I would stick to that approach everywhere and don't compare to null specifically.
> 
> Let's avoid using this PR as a dependency in the other PRs.

but how to handle cases when response itself returns `null` (not `undefined`) from exchange?  i.e.:
`const response = this.privateGetWhatever();`
where `response` is `null`?

**Comment by carlosmiei** [comment]
> > @ttodua
> > > However, we can't do value !== null as it is not transpilable.
> > 
> > 
> > We can use safeString, safeNumber, and other safe methods to sanitize non-null and non-undefined input that will return undefined if the input does not qualify – I would stick to that approach everywhere and don't compare to null specifically.
> > Let's avoid using this PR as a dependency in the other PRs.
> 
> but how to handle cases when response itself returns `null` (not `undefined`) from exchange? i.e.: `const response = this.privateGetWhatever();` where `response` is `null`?

@ttodua do you know any case where an exchange would return `null` as the result while having a 200 as the status code? I'd say that if they return null they will also return an error status so it will be handled before arriving to our unified method

**Comment by ttodua** [comment]
> > > @ttodua
> > > > However, we can't do value !== null as it is not transpilable.
> > > 
> > > 
> > > We can use safeString, safeNumber, and other safe methods to sanitize non-null and non-undefined input that will return undefined if the input does not qualify – I would stick to that approach everywhere and don't compare to null specifically.
> > > Let's avoid using this PR as a dependency in the other PRs.
> > 
> > 
> > but how to handle cases when response itself returns `null` (not `undefined`) from exchange? i.e.: `const response = this.privateGetWhatever();` where `response` is `null`?
> 
> @ttodua do you know any case where an exchange would return `null` as the result while having a 200 as the status code? I'd say that if they return null they will also return an error status so it will be handled before arriving to our unified method

As you see, I don't know a reproduceable occasion myself, I am just basing on user's report (and that report/log seems reliable to me, why he would have lied?)

**Pull request closed without merging**
